/**
 * Class 052: 单调栈（上）四语言真实执行源码与精准 1-based 行号映射
 *
 * 严格遵循 1-based 相对行号准则：
 * 1. 数组第 1 行下标对应行号 1；
 * 2. 集中定义行号字典，使用点只引用字典键名，严禁裸写魔法数字；
 * 3. Java / C++ / Python / JavaScript 四语种语义严格一致。
 */

// ==========================================
// 1. Code01: 单调栈无重复值标准模板
// ==========================================
export const MONOTONIC_NO_REPEAT_CODES = {
  java: [
    'public static int[][] getNearLessNoRepeat(int[] arr) {',
    '    int n = arr.length;',
    '    int[][] ans = new int[n][2];',
    '    int[] stack = new int[n]; // 数组模拟栈存下标',
    '    int r = 0; // 栈顶指针',
    '    for (int i = 0; i < n; i++) {',
    '        while (r > 0 && arr[stack[r - 1]] > arr[i]) {',
    '            int cur = stack[--r]; // 弹出栈顶',
    '            int left = r > 0 ? stack[r - 1] : -1;',
    '            ans[cur][0] = left;',
    '            ans[cur][1] = i; // 当前 i 即为右侧最近较小值',
    '        }',
    '        stack[r++] = i; // 当前下标入栈',
    '    }',
    '    while (r > 0) { // 清算阶段',
    '        int cur = stack[--r];',
    '        int left = r > 0 ? stack[r - 1] : -1;',
    '        ans[cur][0] = left;',
    '        ans[cur][1] = -1; // 右侧无更小值',
    '    }',
    '    return ans;',
    '}',
  ],
  cpp: [
    'vector<vector<int>> getNearLessNoRepeat(const vector<int>& arr) {',
    '    int n = arr.size();',
    '    vector<vector<int>> ans(n, vector<int>(2));',
    '    vector<int> st; // 栈存下标',
    '    for (int i = 0; i < n; i++) {',
    '        while (!st.empty() && arr[st.back()] > arr[i]) {',
    '            int cur = st.back(); st.pop_back();',
    '            int left = !st.empty() ? st.back() : -1;',
    '            ans[cur][0] = left;',
    '            ans[cur][1] = i;',
    '        }',
    '        st.push_back(i);',
    '    }',
    '    while (!st.empty()) {',
    '        int cur = st.back(); st.pop_back();',
    '        int left = !st.empty() ? st.back() : -1;',
    '        ans[cur][0] = left;',
    '        ans[cur][1] = -1;',
    '    }',
    '    return ans;',
    '}',
  ],
  python: [
    'def get_near_less_no_repeat(arr):',
    '    n = len(arr)',
    '    ans = [[-1, -1] for _ in range(n)]',
    '    stack = []',
    '    for i in range(n):',
    '        while stack and arr[stack[-1]] > arr[i]:',
    '            cur = stack.pop()',
    '            left = stack[-1] if stack else -1',
    '            ans[cur][0] = left',
    '            ans[cur][1] = i',
    '        stack.append(i)',
    '    while stack:',
    '        cur = stack.pop()',
    '        left = stack[-1] if stack else -1',
    '        ans[cur][0] = left',
    '        ans[cur][1] = -1',
    '    return ans',
  ],
  javascript: [
    'function getNearLessNoRepeat(arr) {',
    '  const n = arr.length;',
    '  const ans = Array.from({ length: n }, () => [-1, -1]);',
    '  const stack = [];',
    '  for (let i = 0; i < n; i++) {',
    '    while (stack.length > 0 && arr[stack[stack.length - 1]] > arr[i]) {',
    '      const cur = stack.pop();',
    '      const left = stack.length > 0 ? stack[stack.length - 1] : -1;',
    '      ans[cur][0] = left;',
    '      ans[cur][1] = i;',
    '    }',
    '    stack.push(i);',
    '  }',
    '  while (stack.length > 0) {',
    '    const cur = stack.pop();',
    '    const left = stack.length > 0 ? stack[stack.length - 1] : -1;',
    '    ans[cur][0] = left;',
    '    ans[cur][1] = -1;',
    '  }',
    '  return ans;',
    '}',
  ],
};

export const MONOTONIC_NO_REPEAT_LINES = {
  entry: { java: 1, cpp: 1, python: 1, javascript: 1 },
  init: { java: 3, cpp: 3, python: 3, javascript: 3 },
  forLoop: { java: 6, cpp: 5, python: 5, javascript: 5 },
  whileCheck: { java: 7, cpp: 6, python: 6, javascript: 6 },
  popResolve: { java: 8, cpp: 7, python: 7, javascript: 7 },
  push: { java: 13, cpp: 12, python: 11, javascript: 12 },
  clearStack: { java: 15, cpp: 14, python: 12, javascript: 14 },
  clearPop: { java: 16, cpp: 15, python: 13, javascript: 15 },
  returnAns: { java: 21, cpp: 20, python: 17, javascript: 20 },
};

// ==========================================
// 2. Code02: 单调栈有重复值进阶模板
// ==========================================
export const MONOTONIC_WITH_REPEAT_CODES = {
  java: [
    'public static int[][] getNearLessWithRepeat(int[] arr) {',
    '    int n = arr.length;',
    '    int[][] ans = new int[n][2];',
    '    // 栈中每个元素存一个列表，放数值相同的连续下标',
    '    List<List<Integer>> stack = new ArrayList<>();',
    '    for (int i = 0; i < n; i++) {',
    '        while (!stack.isEmpty() && arr[stack.get(stack.size() - 1).get(0)] > arr[i]) {',
    '            List<Integer> popList = stack.remove(stack.size() - 1);',
    '            int left = !stack.isEmpty() ? stack.get(stack.size() - 1).get(stack.get(stack.size() - 1).size() - 1) : -1;',
    '            for (int idx : popList) {',
    '                ans[idx][0] = left; ans[idx][1] = i;',
    '            }',
    '        }',
    '        if (!stack.isEmpty() && arr[stack.get(stack.size() - 1).get(0)] == arr[i]) {',
    '            stack.get(stack.size() - 1).add(i); // 相同值追加到列表尾',
    '        } else {',
    '            List<Integer> list = new ArrayList<>(); list.add(i);',
    '            stack.add(list); // 更大值新建列表入栈',
    '        }',
    '    }',
    '    while (!stack.isEmpty()) { // 清算阶段',
    '        List<Integer> popList = stack.remove(stack.size() - 1);',
    '        int left = !stack.isEmpty() ? stack.get(stack.size() - 1).get(stack.get(stack.size() - 1).size() - 1) : -1;',
    '        for (int idx : popList) {',
    '            ans[idx][0] = left; ans[idx][1] = -1;',
    '        }',
    '    }',
    '    return ans;',
    '}',
  ],
  cpp: [
    'vector<vector<int>> getNearLessWithRepeat(const vector<int>& arr) {',
    '    int n = arr.size();',
    '    vector<vector<int>> ans(n, vector<int>(2));',
    '    vector<vector<int>> st; // 栈内每个槽位存下标列表',
    '    for (int i = 0; i < n; i++) {',
    '        while (!st.empty() && arr[st.back()[0]] > arr[i]) {',
    '            vector<int> popList = st.back(); st.pop_back();',
    '            int left = !st.empty() ? st.back().back() : -1;',
    '            for (int idx : popList) { ans[idx][0] = left; ans[idx][1] = i; }',
    '        }',
    '        if (!st.empty() && arr[st.back()[0]] == arr[i]) {',
    '            st.back().push_back(i);',
    '        } else {',
    '            st.push_back({i});',
    '        }',
    '    }',
    '    while (!st.empty()) {',
    '        vector<int> popList = st.back(); st.pop_back();',
    '        int left = !st.empty() ? st.back().back() : -1;',
    '        for (int idx : popList) { ans[idx][0] = left; ans[idx][1] = -1; }',
    '    }',
    '    return ans;',
    '}',
  ],
  python: [
    'def get_near_less_with_repeat(arr):',
    '    n = len(arr)',
    '    ans = [[-1, -1] for _ in range(n)]',
    '    stack = []  # 存下标列表',
    '    for i in range(n):',
    '        while stack and arr[stack[-1][0]] > arr[i]:',
    '            pop_list = stack.pop()',
    '            left = stack[-1][-1] if stack else -1',
    '            for idx in pop_list:',
    '                ans[idx] = [left, i]',
    '        if stack and arr[stack[-1][0]] == arr[i]:',
    '            stack[-1].append(i)',
    '        else:',
    '            stack.append([i])',
    '    while stack:',
    '        pop_list = stack.pop()',
    '        left = stack[-1][-1] if stack else -1',
    '        for idx in pop_list:',
    '            ans[idx] = [left, -1]',
    '    return ans',
  ],
  javascript: [
    'function getNearLessWithRepeat(arr) {',
    '  const n = arr.length;',
    '  const ans = Array.from({ length: n }, () => [-1, -1]);',
    '  const stack = []; // 存列表 [idx1, idx2, ...]',
    '  for (let i = 0; i < n; i++) {',
    '    while (stack.length > 0 && arr[stack[stack.length - 1][0]] > arr[i]) {',
    '      const popList = stack.pop();',
    '      const left = stack.length > 0 ? stack[stack.length - 1][stack[stack.length - 1].length - 1] : -1;',
    '      for (const idx of popList) { ans[idx][0] = left; ans[idx][1] = i; }',
    '    }',
    '    if (stack.length > 0 && arr[stack[stack.length - 1][0]] === arr[i]) {',
    '      stack[stack.length - 1].push(i);',
    '    } else {',
    '      stack.push([i]);',
    '    }',
    '  }',
    '  while (stack.length > 0) {',
    '    const popList = stack.pop();',
    '    const left = stack.length > 0 ? stack[stack.length - 1][stack[stack.length - 1].length - 1] : -1;',
    '    for (const idx of popList) { ans[idx][0] = left; ans[idx][1] = -1; }',
    '  }',
    '  return ans;',
    '}',
  ],
};

export const MONOTONIC_WITH_REPEAT_LINES = {
  entry: { java: 1, cpp: 1, python: 1, javascript: 1 },
  init: { java: 4, cpp: 4, python: 4, javascript: 4 },
  forLoop: { java: 6, cpp: 5, python: 5, javascript: 5 },
  whileCheck: { java: 7, cpp: 6, python: 6, javascript: 6 },
  popResolveList: { java: 8, cpp: 7, python: 7, javascript: 7 },
  pushOrAppend: { java: 14, cpp: 11, python: 11, javascript: 11 },
  clearStack: { java: 21, cpp: 17, python: 15, javascript: 18 },
  clearPopList: { java: 22, cpp: 18, python: 16, javascript: 19 },
  returnAns: { java: 28, cpp: 23, python: 20, javascript: 22 },
};

// ==========================================
// 3. Code03: 每日温度 (Daily Temperatures)
// ==========================================
export const DAILY_TEMPERATURES_CODES = {
  java: [
    'public static int[] dailyTemperatures(int[] temperatures) {',
    '    int n = temperatures.length;',
    '    int[] ans = new int[n];',
    '    int[] stack = new int[n]; // 递减栈存下标',
    '    int r = 0;',
    '    for (int i = 0; i < n; i++) {',
    '        while (r > 0 && temperatures[i] > temperatures[stack[r - 1]]) {',
    '            int cur = stack[--r];',
    '            ans[cur] = i - cur; // 遇到更高温，结算等待天数跨度',
    '        }',
    '        stack[r++] = i;',
    '    }',
    '    return ans;',
    '}',
  ],
  cpp: [
    'vector<int> dailyTemperatures(const vector<int>& temperatures) {',
    '    int n = temperatures.size();',
    '    vector<int> ans(n, 0);',
    '    vector<int> st;',
    '    for (int i = 0; i < n; i++) {',
    '        while (!st.empty() && temperatures[i] > temperatures[st.back()]) {',
    '            int cur = st.back(); st.pop_back();',
    '            ans[cur] = i - cur;',
    '        }',
    '        st.push_back(i);',
    '    }',
    '    return ans;',
    '}',
  ],
  python: [
    'def daily_temperatures(temperatures):',
    '    n = len(temperatures)',
    '    ans = [0] * n',
    '    stack = []',
    '    for i in range(n):',
    '        while stack and temperatures[i] > temperatures[stack[-1]]:',
    '            cur = stack.pop()',
    '            ans[cur] = i - cur',
    '        stack.append(i)',
    '    return ans',
  ],
  javascript: [
    'function dailyTemperatures(temperatures) {',
    '  const n = temperatures.length;',
    '  const ans = new Array(n).fill(0);',
    '  const stack = [];',
    '  for (let i = 0; i < n; i++) {',
    '    while (stack.length > 0 && temperatures[i] > temperatures[stack[stack.length - 1]]) {',
    '      const cur = stack.pop();',
    '      ans[cur] = i - cur;',
    '    }',
    '    stack.push(i);',
    '  }',
    '  return ans;',
    '}',
  ],
};

export const DAILY_TEMPERATURES_LINES = {
  entry: { java: 1, cpp: 1, python: 1, javascript: 1 },
  init: { java: 3, cpp: 3, python: 3, javascript: 3 },
  forLoop: { java: 6, cpp: 5, python: 5, javascript: 5 },
  whileCheck: { java: 7, cpp: 6, python: 6, javascript: 6 },
  popResolve: { java: 8, cpp: 7, python: 7, javascript: 7 },
  push: { java: 11, cpp: 10, python: 9, javascript: 10 },
  returnAns: { java: 13, cpp: 12, python: 10, javascript: 12 },
};

// ==========================================
// 4. Code04: 子数组的最小值之和 (Sum of Subarray Minimums)
// ==========================================
export const SUM_SUBARRAY_MINIMUMS_CODES = {
  java: [
    'public static int sumSubarrayMins(int[] arr) {',
    '    int n = arr.length;',
    '    long ans = 0, mod = 1000000007;',
    '    int[] stack = new int[n];',
    '    int r = 0;',
    '    for (int i = 0; i < n; i++) {',
    '        while (r > 0 && arr[stack[r - 1]] >= arr[i]) {',
    '            int cur = stack[--r]; // 弹出最小值结算贡献',
    '            int left = r > 0 ? stack[r - 1] : -1;',
    '            ans = (ans + (long)(cur - left) * (i - cur) * arr[cur]) % mod;',
    '        }',
    '        stack[r++] = i;',
    '    }',
    '    while (r > 0) { // 清算阶段',
    '        int cur = stack[--r];',
    '        int left = r > 0 ? stack[r - 1] : -1;',
    '        ans = (ans + (long)(cur - left) * (n - cur) * arr[cur]) % mod;',
    '    }',
    '    return (int) ans;',
    '}',
  ],
  cpp: [
    'int sumSubarrayMins(const vector<int>& arr) {',
    '    int n = arr.size();',
    '    long long ans = 0, mod = 1e9 + 7;',
    '    vector<int> st;',
    '    for (int i = 0; i < n; i++) {',
    '        while (!st.empty() && arr[st.back()] >= arr[i]) {',
    '            int cur = st.back(); st.pop_back();',
    '            int left = !st.empty() ? st.back() : -1;',
    '            ans = (ans + 1LL * (cur - left) * (i - cur) % mod * arr[cur]) % mod;',
    '        }',
    '        st.push_back(i);',
    '    }',
    '    while (!st.empty()) {',
    '        int cur = st.back(); st.pop_back();',
    '        int left = !st.empty() ? st.back() : -1;',
    '        ans = (ans + 1LL * (cur - left) * (n - cur) % mod * arr[cur]) % mod;',
    '    }',
    '    return ans;',
    '}',
  ],
  python: [
    'def sum_subarray_mins(arr):',
    '    n = len(arr)',
    '    ans, mod = 0, 10**9 + 7',
    '    stack = []',
    '    for i in range(n):',
    '        while stack and arr[stack[-1]] >= arr[i]:',
    '            cur = stack.pop()',
    '            left = stack[-1] if stack else -1',
    '            ans = (ans + (cur - left) * (i - cur) * arr[cur]) % mod',
    '        stack.append(i)',
    '    while stack:',
    '        cur = stack.pop()',
    '        left = stack[-1] if stack else -1',
    '        ans = (ans + (cur - left) * (n - cur) * arr[cur]) % mod',
    '    return ans',
  ],
  javascript: [
    'function sumSubarrayMins(arr) {',
    '  const n = arr.length;',
    '  const mod = 1000000007;',
    '  let ans = 0;',
    '  const stack = [];',
    '  for (let i = 0; i < n; i++) {',
    '    while (stack.length > 0 && arr[stack[stack.length - 1]] >= arr[i]) {',
    '      const cur = stack.pop();',
    '      const left = stack.length > 0 ? stack[stack.length - 1] : -1;',
    '      ans = (ans + (cur - left) * (i - cur) * arr[cur]) % mod;',
    '    }',
    '    stack.push(i);',
    '  }',
    '  while (stack.length > 0) {',
    '    const cur = stack.pop();',
    '    const left = stack.length > 0 ? stack[stack.length - 1] : -1;',
    '    ans = (ans + (cur - left) * (n - cur) * arr[cur]) % mod;',
    '  }',
    '  return ans;',
    '}',
  ],
};

export const SUM_SUBARRAY_MINIMUMS_LINES = {
  entry: { java: 1, cpp: 1, python: 1, javascript: 1 },
  init: { java: 3, cpp: 3, python: 3, javascript: 4 },
  forLoop: { java: 6, cpp: 5, python: 5, javascript: 6 },
  whileCheck: { java: 7, cpp: 6, python: 6, javascript: 7 },
  popCalc: { java: 8, cpp: 7, python: 7, javascript: 8 },
  push: { java: 12, cpp: 11, python: 10, javascript: 12 },
  clearLoop: { java: 14, cpp: 13, python: 11, javascript: 14 },
  clearCalc: { java: 15, cpp: 14, python: 12, javascript: 15 },
  returnAns: { java: 19, cpp: 18, python: 15, javascript: 19 },
};

// ==========================================
// 5. Code05: 柱状图中最大的矩形 (Largest Rectangle in Histogram)
// ==========================================
export const LARGEST_RECTANGLE_CODES = {
  java: [
    'public static int largestRectangleArea(int[] heights) {',
    '    int n = heights.length;',
    '    int[] stack = new int[n];',
    '    int r = 0, maxArea = 0;',
    '    for (int i = 0; i < n; i++) {',
    '        while (r > 0 && heights[stack[r - 1]] >= heights[i]) {',
    '            int cur = stack[--r]; // 以当前柱为高度',
    '            int left = r > 0 ? stack[r - 1] : -1;',
    '            int width = i - left - 1;',
    '            maxArea = Math.max(maxArea, heights[cur] * width);',
    '        }',
    '        stack[r++] = i;',
    '    }',
    '    while (r > 0) { // 清算阶段',
    '        int cur = stack[--r];',
    '        int left = r > 0 ? stack[r - 1] : -1;',
    '        int width = n - left - 1;',
    '        maxArea = Math.max(maxArea, heights[cur] * width);',
    '    }',
    '    return maxArea;',
    '}',
  ],
  cpp: [
    'int largestRectangleArea(const vector<int>& heights) {',
    '    int n = heights.size();',
    '    vector<int> st;',
    '    int maxArea = 0;',
    '    for (int i = 0; i < n; i++) {',
    '        while (!st.empty() && heights[st.back()] >= heights[i]) {',
    '            int cur = st.back(); st.pop_back();',
    '            int left = !st.empty() ? st.back() : -1;',
    '            int width = i - left - 1;',
    '            maxArea = max(maxArea, heights[cur] * width);',
    '        }',
    '        st.push_back(i);',
    '    }',
    '    while (!st.empty()) {',
    '        int cur = st.back(); st.pop_back();',
    '        int left = !st.empty() ? st.back() : -1;',
    '        int width = n - left - 1;',
    '        maxArea = max(maxArea, heights[cur] * width);',
    '    }',
    '    return maxArea;',
    '}',
  ],
  python: [
    'def largest_rectangle_area(heights):',
    '    n = len(heights)',
    '    stack = []',
    '    max_area = 0',
    '    for i in range(n):',
    '        while stack and heights[stack[-1]] >= heights[i]:',
    '            cur = stack.pop()',
    '            left = stack[-1] if stack else -1',
    '            width = i - left - 1',
    '            max_area = max(max_area, heights[cur] * width)',
    '        stack.append(i)',
    '    while stack:',
    '        cur = stack.pop()',
    '        left = stack[-1] if stack else -1',
    '        width = n - left - 1',
    '        max_area = max(max_area, heights[cur] * width)',
    '    return max_area',
  ],
  javascript: [
    'function largestRectangleArea(heights) {',
    '  const n = heights.length;',
    '  const stack = [];',
    '  let maxArea = 0;',
    '  for (let i = 0; i < n; i++) {',
    '    while (stack.length > 0 && heights[stack[stack.length - 1]] >= heights[i]) {',
    '      const cur = stack.pop();',
    '      const left = stack.length > 0 ? stack[stack.length - 1] : -1;',
    '      const width = i - left - 1;',
    '      maxArea = Math.max(maxArea, heights[cur] * width);',
    '    }',
    '    stack.push(i);',
    '  }',
    '  while (stack.length > 0) {',
    '    const cur = stack.pop();',
    '    const left = stack.length > 0 ? stack[stack.length - 1] : -1;',
    '    const width = n - left - 1;',
    '    maxArea = Math.max(maxArea, heights[cur] * width);',
    '  }',
    '  return maxArea;',
    '}',
  ],
};

export const LARGEST_RECTANGLE_LINES = {
  entry: { java: 1, cpp: 1, python: 1, javascript: 1 },
  init: { java: 4, cpp: 4, python: 4, javascript: 4 },
  forLoop: { java: 5, cpp: 5, python: 5, javascript: 5 },
  whileCheck: { java: 6, cpp: 6, python: 6, javascript: 6 },
  popCalc: { java: 7, cpp: 7, python: 7, javascript: 7 },
  push: { java: 12, cpp: 12, python: 11, javascript: 12 },
  clearLoop: { java: 14, cpp: 14, python: 12, javascript: 14 },
  clearCalc: { java: 15, cpp: 15, python: 13, javascript: 15 },
  returnAns: { java: 20, cpp: 19, python: 17, javascript: 20 },
};

// ==========================================
// 6. Code06: 最大矩形 (Maximal Rectangle)
// ==========================================
export const MAXIMAL_RECTANGLE_CODES = {
  java: [
    'public static int maximalRectangle(char[][] matrix) {',
    '    if (matrix.length == 0 || matrix[0].length == 0) return 0;',
    '    int m = matrix.length, n = matrix[0].length, maxArea = 0;',
    '    int[] heights = new int[n]; // 压缩为柱状图高度',
    '    for (int i = 0; i < m; i++) {',
    '        for (int j = 0; j < n; j++) {',
    '            heights[j] = matrix[i][j] == "1" ? heights[j] + 1 : 0;',
    '        }',
    '        maxArea = Math.max(maxArea, largestRectangleArea(heights));',
    '    }',
    '    return maxArea;',
    '}',
  ],
  cpp: [
    'int maximalRectangle(const vector<vector<char>>& matrix) {',
    '    if (matrix.empty() || matrix[0].empty()) return 0;',
    '    int m = matrix.size(), n = matrix[0].size(), maxArea = 0;',
    '    vector<int> heights(n, 0);',
    '    for (int i = 0; i < m; i++) {',
    '        for (int j = 0; j < n; j++) {',
    '            heights[j] = matrix[i][j] == "1" ? heights[j] + 1 : 0;',
    '        }',
    '        maxArea = max(maxArea, largestRectangleArea(heights));',
    '    }',
    '    return maxArea;',
    '}',
  ],
  python: [
    'def maximal_rectangle(matrix):',
    '    if not matrix or not matrix[0]: return 0',
    '    m, n = len(matrix), len(matrix[0])',
    '    heights = [0] * n',
    '    max_area = 0',
    '    for i in range(m):',
    '        for j in range(n):',
    '            heights[j] = heights[j] + 1 if matrix[i][j] == "1" else 0',
    '        max_area = max(max_area, largest_rectangle_area(heights))',
    '    return max_area',
  ],
  javascript: [
    'function maximalRectangle(matrix) {',
    '  if (!matrix.length || !matrix[0].length) return 0;',
    '  const m = matrix.length, n = matrix[0].length;',
    '  const heights = new Array(n).fill(0);',
    '  let maxArea = 0;',
    '  for (let i = 0; i < m; i++) {',
    '    for (let j = 0; j < n; j++) {',
    '      heights[j] = matrix[i][j] === "1" ? heights[j] + 1 : 0;',
    '    }',
    '    maxArea = Math.max(maxArea, largestRectangleArea(heights));',
    '  }',
    '  return maxArea;',
    '}',
  ],
};

export const MAXIMAL_RECTANGLE_LINES = {
  entry: { java: 1, cpp: 1, python: 1, javascript: 1 },
  initHeights: { java: 4, cpp: 4, python: 4, javascript: 4 },
  rowLoop: { java: 5, cpp: 5, python: 6, javascript: 6 },
  updateHeights: { java: 7, cpp: 7, python: 8, javascript: 8 },
  calcHistogram: { java: 9, cpp: 9, python: 9, javascript: 10 },
  returnAns: { java: 11, cpp: 11, python: 10, javascript: 12 },
};
