/**
 * 第 92 课：左神贪心算法专题 4 - 多语言代码片段与 1-based 相对行号映射
 */

// ==========================================
// 1. 数组的最小偏移量 (LeetCode 1675)
// ==========================================
export const MINIMIZE_DEVIATION_CODES: Record<string, string[]> = {
  java: [
    'public int minimumDeviation(int[] nums) {',
    '    TreeSet<Integer> set = new TreeSet<>();',
    '    for (int num : nums) {',
    '        set.add(num % 2 == 1 ? num * 2 : num);',
    '    }',
    '    int ans = set.last() - set.first();',
    '    while (ans > 0 && set.last() % 2 == 0) {',
    '        int maxVal = set.last();',
    '        set.remove(maxVal);',
    '        set.add(maxVal / 2);',
    '        ans = Math.min(ans, set.last() - set.first());',
    '    }',
    '    return ans;',
    '}',
  ],
  cpp: [
    'int minimumDeviation(vector<int>& nums) {',
    '    set<int> st;',
    '    for (int num : nums) {',
    '        st.insert(num % 2 == 1 ? num * 2 : num);',
    '    }',
    '    int ans = *st.rbegin() - *st.begin();',
    '    while (ans > 0 && *st.rbegin() % 2 == 0) {',
    '        int maxVal = *st.rbegin();',
    '        st.erase(maxVal);',
    '        st.insert(maxVal / 2);',
    '        ans = min(ans, *st.rbegin() - *st.begin());',
    '    }',
    '    return ans;',
    '}',
  ],
  python: [
    'def minimumDeviation(nums: List[int]) -> int:',
    '    max_heap = []',
    '    min_val = float("inf")',
    '    for num in nums:',
    '        v = num * 2 if num % 2 == 1 else num',
    '        heapq.heappush(max_heap, -v)',
    '        min_val = min(min_val, v)',
    '    ans = -max_heap[0] - min_val',
    '    while -max_heap[0] % 2 == 0:',
    '        top = -heapq.heappop(max_heap)',
    '        half = top // 2',
    '        min_val = min(min_val, half)',
    '        heapq.heappush(max_heap, -half)',
    '        ans = min(ans, -max_heap[0] - min_val)',
    '    return ans',
  ],
  javascript: [
    'function minimumDeviation(nums) {',
    '    const heap = nums.map(n => n % 2 === 1 ? n * 2 : n);',
    '    let minVal = Math.min(...heap);',
    '    let ans = Math.max(...heap) - minVal;',
    '    while (true) {',
    '        heap.sort((a, b) => b - a);',
    '        const maxVal = heap[0];',
    '        if (maxVal % 2 !== 0) break;',
    '        heap[0] = maxVal / 2;',
    '        minVal = Math.min(minVal, heap[0]);',
    '        ans = Math.min(ans, Math.max(...heap) - minVal);',
    '    }',
    '    return ans;',
    '}',
  ],
};

export const MINIMIZE_DEVIATION_LINES = {
  entry:     { java: 1, cpp: 1, python: 1, javascript: 1 },
  initHeap:  { java: 4, cpp: 4, python: 6, javascript: 2 },
  calcAns:   { java: 6, cpp: 6, python: 8, javascript: 4 },
  reduceEven:{ java: 10, cpp: 10, python: 13, javascript: 9 },
  done:      { java: 13, cpp: 13, python: 15, javascript: 13 },
};

// ==========================================
// 2. 森林中的兔子 (LeetCode 781)
// ==========================================
export const RABBITS_IN_FOREST_CODES: Record<string, string[]> = {
  java: [
    'public int numRabbits(int[] answers) {',
    '    Map<Integer, Integer> count = new HashMap<>();',
    '    for (int ans : answers) {',
    '        count.put(ans, count.getOrDefault(ans, 0) + 1);',
    '    }',
    '    int total = 0;',
    '    for (Map.Entry<Integer, Integer> entry : count.entrySet()) {',
    '        int x = entry.getKey(), cnt = entry.getValue();',
    '        int groupSize = x + 1;',
    '        int groups = (cnt + x) / groupSize;',
    '        total += groups * groupSize;',
    '    }',
    '    return total;',
    '}',
  ],
  cpp: [
    'int numRabbits(vector<int>& answers) {',
    '    unordered_map<int, int> count;',
    '    for (int ans : answers) {',
    '        count[ans]++;',
    '    }',
    '    int total = 0;',
    '    for (auto& [x, cnt] : count) {',
    '        int groupSize = x + 1;',
    '        int groups = (cnt + x) / groupSize;',
    '        total += groups * groupSize;',
    '    }',
    '    return total;',
    '}',
  ],
  python: [
    'def numRabbits(answers: List[int]) -> int:',
    '    count = collections.Counter(answers)',
    '    total = 0',
    '    for x, cnt in count.items():',
    '        group_size = x + 1',
    '        groups = (cnt + x) // group_size',
    '        total += groups * group_size',
    '    return total',
  ],
  javascript: [
    'function numRabbits(answers) {',
    '    const count = new Map();',
    '    for (const ans of answers) {',
    '        count.set(ans, (count.get(ans) || 0) + 1);',
    '    }',
    '    let total = 0;',
    '    for (const [x, cnt] of count.entries()) {',
    '        const groupSize = x + 1;',
    '        const groups = Math.floor((cnt + x) / groupSize);',
    '        total += groups * groupSize;',
    '    }',
    '    return total;',
    '}',
  ],
};

export const RABBITS_IN_FOREST_LINES = {
  entry:     { java: 1, cpp: 1, python: 1, javascript: 1 },
  countFreq: { java: 4, cpp: 4, python: 2, javascript: 4 },
  calcGroup: { java: 10, cpp: 10, python: 6, javascript: 10 },
  done:      { java: 13, cpp: 13, python: 8, javascript: 13 },
};

// ==========================================
// 3. 使数组相似的最少操作次数 (LeetCode 2449)
// ==========================================
export const MIN_OPERATIONS_SIMILAR_CODES: Record<string, string[]> = {
  java: [
    'public long makeSimilar(int[] nums, int[] target) {',
    '    Arrays.sort(nums); Arrays.sort(target);',
    '    List<Integer> oddNums = new ArrayList<>(), evenNums = new ArrayList<>();',
    '    List<Integer> oddTarget = new ArrayList<>(), evenTarget = new ArrayList<>();',
    '    for (int x : nums) (x % 2 == 1 ? oddNums : evenNums).add(x);',
    '    for (int x : target) (x % 2 == 1 ? oddTarget : evenTarget).add(x);',
    '    long ops = 0;',
    '    for (int i = 0; i < oddNums.size(); i++) {',
    '        if (oddNums.get(i) > oddTarget.get(i)) ops += (oddNums.get(i) - oddTarget.get(i)) / 2;',
    '    }',
    '    for (int i = 0; i < evenNums.size(); i++) {',
    '        if (evenNums.get(i) > evenTarget.get(i)) ops += (evenNums.get(i) - evenTarget.get(i)) / 2;',
    '    }',
    '    return ops;',
    '}',
  ],
  cpp: [
    'long long makeSimilar(vector<int>& nums, vector<int>& target) {',
    '    sort(nums.begin(), nums.end()); sort(target.begin(), target.end());',
    '    vector<int> oddNums, evenNums, oddTarget, evenTarget;',
    '    for (int x : nums) (x % 2 == 1 ? oddNums : evenNums).push_back(x);',
    '    for (int x : target) (x % 2 == 1 ? oddTarget : evenTarget).push_back(x);',
    '    long long ops = 0;',
    '    for (size_t i = 0; i < oddNums.size(); i++) {',
    '        if (oddNums[i] > oddTarget[i]) ops += (oddNums[i] - oddTarget[i]) / 2;',
    '    }',
    '    for (size_t i = 0; i < evenNums.size(); i++) {',
    '        if (evenNums[i] > evenTarget[i]) ops += (evenNums[i] - evenTarget[i]) / 2;',
    '    }',
    '    return ops;',
    '}',
  ],
  python: [
    'def makeSimilar(nums: List[int], target: List[int]) -> int:',
    '    nums.sort(); target.sort()',
    '    odd_nums = [x for x in nums if x % 2 == 1]',
    '    even_nums = [x for x in nums if x % 2 == 0]',
    '    odd_target = [x for x in target if x % 2 == 1]',
    '    even_target = [x for x in target if x % 2 == 0]',
    '    ops = 0',
    '    for a, b in zip(odd_nums, odd_target):',
    '        if a > b: ops += (a - b) // 2',
    '    for a, b in zip(even_nums, even_target):',
    '        if a > b: ops += (a - b) // 2',
    '    return ops',
  ],
  javascript: [
    'function makeSimilar(nums, target) {',
    '    nums.sort((a, b) => a - b); target.sort((a, b) => a - b);',
    '    const oddNums = nums.filter(x => x % 2 !== 0);',
    '    const evenNums = nums.filter(x => x % 2 === 0);',
    '    const oddTarget = target.filter(x => x % 2 !== 0);',
    '    const evenTarget = target.filter(x => x % 2 === 0);',
    '    let ops = 0;',
    '    for (let i = 0; i < oddNums.length; i++) {',
    '        if (oddNums[i] > oddTarget[i]) ops += (oddNums[i] - oddTarget[i]) / 2;',
    '    }',
    '    for (let i = 0; i < evenNums.length; i++) {',
    '        if (evenNums[i] > evenTarget[i]) ops += (evenNums[i] - evenTarget[i]) / 2;',
    '    }',
    '    return ops;',
    '}',
  ],
};

export const MIN_OPERATIONS_SIMILAR_LINES = {
  entry:     { java: 1, cpp: 1, python: 1, javascript: 1 },
  sortSplit: { java: 2, cpp: 2, python: 2, javascript: 2 },
  oddPairs:  { java: 9, cpp: 9, python: 9, javascript: 9 },
  evenPairs: { java: 12, cpp: 12, python: 11, javascript: 12 },
  done:      { java: 14, cpp: 14, python: 12, javascript: 14 },
};

// ==========================================
// 4. 知识竞赛得分最大化 (Quiz Score)
// ==========================================
export const QUIZ_SCORE_CODES: Record<string, string[]> = {
  java: [
    'public int maxScore(int[][] questions, int k) {',
    '    Arrays.sort(questions, (q1, q2) -> (q2[0] - q2[1]) - (q1[0] - q1[1]));',
    '    int total = 0;',
    '    for (int i = 0; i < k; i++) {',
    '        total += questions[i][0];',
    '    }',
    '    for (int i = k; i < questions.length; i++) {',
    '        total += questions[i][1];',
    '    }',
    '    return total;',
    '}',
  ],
  cpp: [
    'int maxScore(vector<vector<int>>& questions, int k) {',
    '    sort(questions.begin(), questions.end(), [](const vector<int>& a, const vector<int>& b){',
    '        return (b[0] - b[1]) < (a[0] - a[1]);',
    '    });',
    '    int total = 0;',
    '    for (int i = 0; i < k; i++) total += questions[i][0];',
    '    for (size_t i = k; i < questions.size(); i++) total += questions[i][1];',
    '    return total;',
    '}',
  ],
  python: [
    'def maxScore(questions: List[List[int]], k: int) -> int:',
    '    questions.sort(key=lambda q: q[0] - q[1], reverse=True)',
    '    total = sum(q[0] for q in questions[:k])',
    '    total += sum(q[1] for q in questions[k:])',
    '    return total',
  ],
  javascript: [
    'function maxScore(questions, k) {',
    '    questions.sort((a, b) => (b[0] - b[1]) - (a[0] - a[1]));',
    '    let total = 0;',
    '    for (let i = 0; i < k; i++) total += questions[i][0];',
    '    for (let i = k; i < questions.length; i++) total += questions[i][1];',
    '    return total;',
    '}',
  ],
};

export const QUIZ_SCORE_LINES = {
  entry:     { java: 1, cpp: 1, python: 1, javascript: 1 },
  sortDiff:  { java: 2, cpp: 2, python: 2, javascript: 2 },
  pickA:     { java: 5, cpp: 6, python: 3, javascript: 4 },
  pickB:     { java: 8, cpp: 7, python: 4, javascript: 5 },
  done:      { java: 10, cpp: 8, python: 5, javascript: 6 },
};

// ==========================================
// 5. 将数组分成几个递增序列 (LeetCode 1121)
// ==========================================
export const DIVIDE_ARRAY_SEQ_CODES: Record<string, string[]> = {
  java: [
    'public boolean canDivideIntoSubsequences(int[] nums, int k) {',
    '    int maxFreq = 1, curFreq = 1;',
    '    for (int i = 1; i < nums.length; i++) {',
    '        if (nums[i] == nums[i - 1]) {',
    '            curFreq++;',
    '            maxFreq = Math.max(maxFreq, curFreq);',
    '        } else {',
    '            curFreq = 1;',
    '        }',
    '    }',
    '    return nums.length >= maxFreq * k;',
    '}',
  ],
  cpp: [
    'bool canDivideIntoSubsequences(vector<int>& nums, int k) {',
    '    int maxFreq = 1, curFreq = 1;',
    '    for (size_t i = 1; i < nums.size(); i++) {',
    '        if (nums[i] == nums[i - 1]) {',
    '            curFreq++;',
    '            maxFreq = max(maxFreq, curFreq);',
    '        } else {',
    '            curFreq = 1;',
    '        }',
    '    }',
    '    return (int)nums.size() >= maxFreq * k;',
    '}',
  ],
  python: [
    'def canDivideIntoSubsequences(nums: List[int], k: int) -> bool:',
    '    max_freq = max(collections.Counter(nums).values())',
    '    return len(nums) >= max_freq * k',
  ],
  javascript: [
    'function canDivideIntoSubsequences(nums, k) {',
    '    let maxFreq = 1, curFreq = 1;',
    '    for (let i = 1; i < nums.length; i++) {',
    '        if (nums[i] === nums[i - 1]) {',
    '            curFreq++;',
    '            maxFreq = Math.max(maxFreq, curFreq);',
    '        } else {',
    '            curFreq = 1;',
    '        }',
    '    }',
    '    return nums.length >= maxFreq * k;',
    '}',
  ],
};

export const DIVIDE_ARRAY_SEQ_LINES = {
  entry:     { java: 1, cpp: 1, python: 1, javascript: 1 },
  scanFreq:  { java: 6, cpp: 6, python: 2, javascript: 6 },
  checkBottleneck: { java: 11, cpp: 11, python: 3, javascript: 11 },
};

// ==========================================
// 6. 最低加油次数 (LeetCode 871)
// ==========================================
export const MIN_REFUELING_STOPS_CODES: Record<string, string[]> = {
  java: [
    'public int minRefuelStops(int target, int startFuel, int[][] stations) {',
    '    PriorityQueue<Integer> maxHeap = new PriorityQueue<>((a, b) -> b - a);',
    '    int curFuel = startFuel, stops = 0, i = 0, n = stations.length;',
    '    while (curFuel < target) {',
    '        while (i < n && stations[i][0] <= curFuel) {',
    '            maxHeap.offer(stations[i][1]); i++;',
    '        }',
    '        if (maxHeap.isEmpty()) return -1;',
    '        curFuel += maxHeap.poll();',
    '        stops++;',
    '    }',
    '    return stops;',
    '}',
  ],
  cpp: [
    'int minRefuelStops(int target, int startFuel, vector<vector<int>>& stations) {',
    '    priority_queue<int> maxHeap;',
    '    long long curFuel = startFuel; int stops = 0, i = 0, n = stations.size();',
    '    while (curFuel < target) {',
    '        while (i < n && stations[i][0] <= curFuel) {',
    '            maxHeap.push(stations[i][1]); i++;',
    '        }',
    '        if (maxHeap.empty()) return -1;',
    '        curFuel += maxHeap.top(); maxHeap.pop();',
    '        stops++;',
    '    }',
    '    return stops;',
    '}',
  ],
  python: [
    'def minRefuelStops(target: int, startFuel: int, stations: List[List[int]]) -> int:',
    '    max_heap = []',
    '    cur_fuel, stops, i, n = startFuel, 0, 0, len(stations)',
    '    while cur_fuel < target:',
    '        while i < n and stations[i][0] <= cur_fuel:',
    '            heapq.heappush(max_heap, -stations[i][1])',
    '            i += 1',
    '        if not max_heap: return -1',
    '        cur_fuel += (-heapq.heappop(max_heap))',
    '        stops += 1',
    '    return stops',
  ],
  javascript: [
    'function minRefuelStops(target, startFuel, stations) {',
    '    const heap = [];',
    '    let curFuel = startFuel, stops = 0, i = 0, n = stations.length;',
    '    while (curFuel < target) {',
    '        while (i < n && stations[i][0] <= curFuel) {',
    '            heap.push(stations[i][1]); i++;',
    '        }',
    '        if (heap.length === 0) return -1;',
    '        heap.sort((a, b) => b - a);',
    '        curFuel += heap.shift();',
    '        stops++;',
    '    }',
    '    return stops;',
    '}',
  ],
};

export const MIN_REFUELING_STOPS_LINES = {
  entry:     { java: 1, cpp: 1, python: 1, javascript: 1 },
  collectGas:{ java: 6, cpp: 6, python: 6, javascript: 6 },
  refuelMax: { java: 9, cpp: 9, python: 9, javascript: 9 },
  done:      { java: 12, cpp: 12, python: 11, javascript: 12 },
};
