/**
 * Class 075 多重背包与混合背包 4-Stage 演化多语言代码库
 * 包含：
 * 1. bounded-knapsack-naive:
 *    - 阶段 1: 暴力递归尝试每种宝物拿 0..c[i] 件
 *    - 阶段 2: 记忆化搜索 memo[i][remCap]
 *    - 阶段 3: 严格位置依赖二维动态规划 dp[i][j]
 *    - 阶段 4: 空间压缩三重循环倒序枚举
 */

export const BOUNDED_NAIVE_STAGE1_CODE_LANGUAGES: Record<string, string[]> = {
  cpp: [
    '#include <iostream>',
    '#include <vector>',
    '#include <algorithm>',
    'using namespace std;',
    '',
    '// 阶段 1: 多重背包暴力递归 (每种物品决策尝试选 k 件，其中 0 <= k <= c[i])',
    'int dfs(int i, int remCap, int n, const vector<int>& v, const vector<int>& w, const vector<int>& c) { // @step:callRoot // @step:fnEnter',
    '    if (i >= n || remCap <= 0) return 0; // @step:baseCheck',
    '    int maxVal = 0; // @step:initMax',
    '    // 枚举选取当前物品的件数 k',
    '    for (int k = 0; k <= c[i] && k * w[i] <= remCap; ++k) { // @step:loopK',
    '        int nextVal = dfs(i + 1, remCap - k * w[i], n, v, w, c) + k * v[i]; // @step:branchNext',
    '        maxVal = max(maxVal, nextVal);',
    '    }',
    '    return maxVal; // @step:returnMax',
    '}',
  ],
  java: [
    'package class075;',
    '',
    '// 阶段 1: 多重背包暴力递归',
    'public class Code01_BoundedKnapsackNaiveStage1 {',
    '    public static int dfs(int i, int remCap, int n, int[] v, int[] w, int[] c) { // @step:callRoot // @step:fnEnter',
    '        if (i >= n || remCap <= 0) return 0; // @step:baseCheck',
    '        int maxVal = 0; // @step:initMax',
    '        // 枚举当前物品选择件数 k',
    '        for (int k = 0; k <= c[i] && k * w[i] <= remCap; k++) { // @step:loopK',
    '            int nextVal = dfs(i + 1, remCap - k * w[i], n, v, w, c) + k * v[i]; // @step:branchNext',
    '            maxVal = Math.max(maxVal, nextVal);',
    '        }',
    '        return maxVal; // @step:returnMax',
    '    }',
    '}',
  ],
  python: [
    'def dfs_bounded(i: int, rem_cap: int, n: int, v: list, w: list, c: list) -> int: # @step:callRoot # @step:fnEnter',
    '    """阶段 1: 多重背包暴力递归"""',
    '    if i >= n or rem_cap <= 0: # @step:baseCheck',
    '        return 0',
    '    max_val = 0 # @step:initMax',
    '    # 枚举当前物品选择件数 k',
    '    k = 0',
    '    while k <= c[i] and k * w[i] <= rem_cap: # @step:loopK',
    '        next_val = dfs_bounded(i + 1, rem_cap - k * w[i], n, v, w, c) + k * v[i] # @step:branchNext',
    '        max_val = max(max_val, next_val)',
    '        k += 1',
    '    return max_val # @step:returnMax',
  ],
  javascript: [
    '// 阶段 1: 多重背包暴力递归',
    'export function dfsBounded(i, remCap, n, v, w, c) { // @step:callRoot // @step:fnEnter',
    '  if (i >= n || remCap <= 0) return 0; // @step:baseCheck',
    '  let maxVal = 0; // @step:initMax',
    '  // 枚举当前物品选择件数 k',
    '  for (let k = 0; k <= c[i] && k * w[i] <= remCap; k++) { // @step:loopK',
    '    const nextVal = dfsBounded(i + 1, remCap - k * w[i], n, v, w, c) + k * v[i]; // @step:branchNext',
    '    maxVal = Math.max(maxVal, nextVal);',
    '  }',
    '  return maxVal; // @step:returnMax',
    '}',
  ],
};

export const BOUNDED_NAIVE_STAGE2_CODE_LANGUAGES: Record<string, string[]> = {
  cpp: [
    '#include <iostream>',
    '#include <vector>',
    '#include <algorithm>',
    'using namespace std;',
    '',
    '// 阶段 2: 多重背包记忆化搜索 memo[i][remCap]',
    'int dfsMemo(int i, int remCap, int n, const vector<int>& v, const vector<int>& w, const vector<int>& c, vector<vector<int>>& memo) { // @step:callRoot // @step:fnEnter',
    '    if (i >= n || remCap <= 0) return 0; // @step:baseCheck',
    '    if (memo[i][remCap] != -1) return memo[i][remCap]; // @step:memoCheck',
    '    int maxVal = 0;',
    '    for (int k = 0; k <= c[i] && k * w[i] <= remCap; ++k) { // @step:loopK',
    '        int nextVal = dfsMemo(i + 1, remCap - k * w[i], n, v, w, c, memo) + k * v[i]; // @step:branchNext',
    '        maxVal = max(maxVal, nextVal);',
    '    }',
    '    return memo[i][remCap] = maxVal; // @step:memoStore',
    '}',
  ],
  java: [
    'package class075;',
    '',
    '// 阶段 2: 多重背包记忆化搜索',
    'public class Code01_BoundedKnapsackNaiveStage2 {',
    '    public static int dfsMemo(int i, int remCap, int n, int[] v, int[] w, int[] c, int[][] memo) { // @step:callRoot // @step:fnEnter',
    '        if (i >= n || remCap <= 0) return 0; // @step:baseCheck',
    '        if (memo[i][remCap] != -1) return memo[i][remCap]; // @step:memoCheck',
    '        int maxVal = 0;',
    '        for (int k = 0; k <= c[i] && k * w[i] <= remCap; k++) { // @step:loopK',
    '            int nextVal = dfsMemo(i + 1, remCap - k * w[i], n, v, w, c, memo) + k * v[i]; // @step:branchNext',
    '            maxVal = Math.max(maxVal, nextVal);',
    '        }',
    '        return memo[i][remCap] = maxVal; // @step:memoStore',
    '    }',
    '}',
  ],
  python: [
    'def bounded_knapsack_memo(t: int, n: int, v: list, w: list, c: list) -> int:',
    '    """阶段 2: 多重背包记忆化搜索"""',
    '    memo = [[-1] * (t + 1) for _ in range(n + 1)]',
    '    def dfs(i: int, rem_cap: int) -> int: # @step:callRoot # @step:fnEnter',
    '        if i >= n or rem_cap <= 0: # @step:baseCheck',
    '            return 0',
    '        if memo[i][rem_cap] != -1: # @step:memoCheck',
    '            return memo[i][rem_cap]',
    '        max_val = 0',
    '        k = 0',
    '        while k <= c[i] and k * w[i] <= rem_cap: # @step:loopK',
    '            val = dfs(i + 1, rem_cap - k * w[i]) + k * v[i] # @step:branchNext',
    '            max_val = max(max_val, val)',
    '            k += 1',
    '        memo[i][rem_cap] = max_val # @step:memoStore',
    '        return max_val',
    '    return dfs(0, t)',
  ],
  javascript: [
    '// 阶段 2: 多重背包记忆化搜索',
    'export function boundedKnapsackMemo(t, n, v, w, c) {',
    '  const memo = Array.from({ length: n + 1 }, () => new Array(t + 1).fill(-1));',
    '  function dfs(i, remCap) { // @step:callRoot // @step:fnEnter',
    '    if (i >= n || remCap <= 0) return 0; // @step:baseCheck',
    '    if (memo[i][remCap] !== -1) return memo[i][remCap]; // @step:memoCheck',
    '    let maxVal = 0;',
    '    for (let k = 0; k <= c[i] && k * w[i] <= remCap; k++) { // @step:loopK',
    '      const val = dfs(i + 1, remCap - k * w[i]) + k * v[i]; // @step:branchNext',
    '      maxVal = Math.max(maxVal, val);',
    '    }',
    '    return (memo[i][remCap] = maxVal); // @step:memoStore',
    '  }',
    '  return dfs(0, t);',
    '}',
  ],
};

export const BOUNDED_NAIVE_STAGE3_CODE_LANGUAGES: Record<string, string[]> = {
  cpp: [
    '#include <iostream>',
    '#include <vector>',
    '#include <algorithm>',
    'using namespace std;',
    '',
    '// 阶段 3: 严格位置依赖二维动态规划',
    '// dp[i][j]: 考察完前 i 种宝物，背包容量为 j 时的最大总价值',
    'int computeBounded2D(int n, int t, const vector<int>& v, const vector<int>& w, const vector<int>& c) {',
    '    vector<vector<int>> dp(n + 1, vector<int>(t + 1, 0)); // @step:initDp',
    '    for (int i = 1; i <= n; ++i) { // @step:outerLoopI',
    '        for (int j = 0; j <= t; ++j) { // @step:innerLoopJ',
    '            dp[i][j] = dp[i - 1][j]; // @step:inheritK0',
    '            for (int k = 1; k <= c[i - 1] && k * w[i - 1] <= j; ++k) { // @step:loopK',
    '                dp[i][j] = max(dp[i][j], dp[i - 1][j - k * w[i - 1]] + k * v[i - 1]); // @step:updateDp',
    '            }',
    '        }',
    '    }',
    '    return dp[n][t]; // @step:returnAns',
    '}',
  ],
  java: [
    'package class075;',
    '',
    '// 阶段 3: 严格位置依赖二维动态规划',
    'public class Code01_BoundedKnapsackNaiveStage3 {',
    '    public static int compute(int n, int t, int[] v, int[] w, int[] c) {',
    '        int[][] dp = new int[n + 1][t + 1]; // @step:initDp',
    '        for (int i = 1; i <= n; i++) { // @step:outerLoopI',
    '            for (int j = 0; j <= t; j++) { // @step:innerLoopJ',
    '                dp[i][j] = dp[i - 1][j]; // @step:inheritK0',
    '                for (int k = 1; k <= c[i - 1] && k * w[i - 1] <= j; k++) { // @step:loopK',
    '                    dp[i][j] = Math.max(dp[i][j], dp[i - 1][j - k * w[i - 1]] + k * v[i - 1]); // @step:updateDp',
    '                }',
    '            }',
    '        }',
    '        return dp[n][t]; // @step:returnAns',
    '    }',
    '}',
  ],
  python: [
    'def compute_bounded_2d(n: int, t: int, v: list, w: list, c: list) -> int:',
    '    """阶段 3: 严格位置依赖二维动态规划"""',
    '    dp = [[0] * (t + 1) for _ in range(n + 1)] # @step:initDp',
    '    for i in range(1, n + 1): # @step:outerLoopI',
    '        for j in range(t + 1): # @step:innerLoopJ',
    '            dp[i][j] = dp[i - 1][j] # @step:inheritK0',
    '            k = 1',
    '            while k <= c[i - 1] and k * w[i - 1] <= j: # @step:loopK',
    '                dp[i][j] = max(dp[i][j], dp[i - 1][j - k * w[i - 1]] + k * v[i - 1]) # @step:updateDp',
    '                k += 1',
    '    return dp[n][t] # @step:returnAns',
  ],
  javascript: [
    '// 阶段 3: 严格二维动态规划',
    'export function computeBounded2D(n, t, v, w, c) {',
    '  const dp = Array.from({ length: n + 1 }, () => new Array(t + 1).fill(0)); // @step:initDp',
    '  for (let i = 1; i <= n; i++) { // @step:outerLoopI',
    '    for (let j = 0; j <= t; j++) { // @step:innerLoopJ',
    '      dp[i][j] = dp[i - 1][j]; // @step:inheritK0',
    '      for (let k = 1; k <= c[i - 1] && k * w[i - 1] <= j; k++) { // @step:loopK',
    '        dp[i][j] = Math.max(dp[i][j], dp[i - 1][j - k * w[i - 1]] + k * v[i - 1]); // @step:updateDp',
    '      }',
    '    }',
    '  }',
    '  return dp[n][t]; // @step:returnAns',
    '}',
  ],
};

// ==========================================
// 2. bounded-knapsack-binary 二进制拆分转化为 01 背包演化代码
// ==========================================

export const BINARY_SPLIT_STAGE1_CODE_LANGUAGES: Record<string, string[]> = {
  cpp: [
    '#include <iostream>',
    '#include <vector>',
    'using namespace std;',
    '',
    '// 阶段 1: 衍生 01 包暴力递归',
    'int dfs(int idx, int remCap, const vector<int>& nv, const vector<int>& nw) { // @step:callRoot // @step:fnEnter',
    '    if (idx >= (int)nv.size() || remCap <= 0) return 0; // @step:baseCheck',
    '    int p1 = dfs(idx + 1, remCap, nv, nw); // @step:branchNoPick',
    '    int p2 = 0;',
    '    if (remCap >= nw[idx]) { // @step:branchPick',
    '        p2 = dfs(idx + 1, remCap - nw[idx], nv, nw) + nv[idx];',
    '    }',
    '    return max(p1, p2); // @step:returnMax',
    '}',
  ],
  java: [
    'package class075;',
    '',
    '// 阶段 1: 衍生 01 包暴力递归',
    'public class Code02_BinarySplittingStage1 {',
    '    public static int dfs(int idx, int remCap, int[] nv, int[] nw, int m) { // @step:callRoot // @step:fnEnter',
    '        if (idx > m || remCap <= 0) return 0; // @step:baseCheck',
    '        int p1 = dfs(idx + 1, remCap, nv, nw, m); // @step:branchNoPick',
    '        int p2 = 0;',
    '        if (remCap >= nw[idx]) { // @step:branchPick',
    '            p2 = dfs(idx + 1, remCap - nw[idx], nv, nw, m) + nv[idx];',
    '        }',
    '        return Math.max(p1, p2); // @step:returnMax',
    '    }',
    '}',
  ],
  python: [
    'def dfs_binary_derived(idx: int, rem_cap: int, nv: list, nw: list) -> int: # @step:callRoot # @step:fnEnter',
    '    """阶段 1: 衍生 01 包暴力递归"""',
    '    if idx >= len(nv) or rem_cap <= 0: # @step:baseCheck',
    '        return 0',
    '    p1 = dfs_binary_derived(idx + 1, rem_cap, nv, nw) # @step:branchNoPick',
    '    p2 = 0',
    '    if rem_cap >= nw[idx]: # @step:branchPick',
    '        p2 = dfs_binary_derived(idx + 1, rem_cap - nw[idx], nv, nw) + nv[idx]',
    '    return max(p1, p2) # @step:returnMax',
  ],
  javascript: [
    '// 阶段 1: 衍生 01 包暴力递归',
    'export function dfsBinaryDerived(idx, remCap, nv, nw) { // @step:callRoot // @step:fnEnter',
    '  if (idx >= nv.length || remCap <= 0) return 0; // @step:baseCheck',
    '  const p1 = dfsBinaryDerived(idx + 1, remCap, nv, nw); // @step:branchNoPick',
    '  let p2 = 0;',
    '  if (remCap >= nw[idx]) { // @step:branchPick',
    '    p2 = dfsBinaryDerived(idx + 1, remCap - nw[idx], nv, nw) + nv[idx];',
    '  }',
    '  return Math.max(p1, p2); // @step:returnMax',
    '}',
  ],
};

export const BINARY_SPLIT_STAGE2_CODE_LANGUAGES: Record<string, string[]> = {
  cpp: [
    '#include <iostream>',
    '#include <vector>',
    'using namespace std;',
    '',
    '// 阶段 2: 衍生 01 包记忆化搜索 memo[idx][remCap]',
    'int dfsMemo(int idx, int remCap, const vector<int>& nv, const vector<int>& nw, vector<vector<int>>& memo) { // @step:callRoot // @step:fnEnter',
    '    if (idx >= (int)nv.size() || remCap <= 0) return 0; // @step:baseCheck',
    '    if (memo[idx][remCap] != -1) return memo[idx][remCap]; // @step:memoCheck',
    '    int p1 = dfsMemo(idx + 1, remCap, nv, nw, memo); // @step:branchNoPick',
    '    int p2 = 0;',
    '    if (remCap >= nw[idx]) { // @step:branchPick',
    '        p2 = dfsMemo(idx + 1, remCap - nw[idx], nv, nw, memo) + nv[idx];',
    '    }',
    '    return memo[idx][remCap] = max(p1, p2); // @step:memoStore',
    '}',
  ],
  java: [
    'package class075;',
    '',
    '// 阶段 2: 衍生 01 包记忆化搜索',
    'public class Code02_BinarySplittingStage2 {',
    '    public static int dfsMemo(int idx, int remCap, int[] nv, int[] nw, int m, int[][] memo) { // @step:callRoot // @step:fnEnter',
    '        if (idx > m || remCap <= 0) return 0; // @step:baseCheck',
    '        if (memo[idx][remCap] != -1) return memo[idx][remCap]; // @step:memoCheck',
    '        int p1 = dfsMemo(idx + 1, remCap, nv, nw, m, memo); // @step:branchNoPick',
    '        int p2 = 0;',
    '        if (remCap >= nw[idx]) { // @step:branchPick',
    '            p2 = dfsMemo(idx + 1, remCap - nw[idx], nv, nw, m, memo) + nv[idx];',
    '        }',
    '        return memo[idx][remCap] = Math.max(p1, p2); // @step:memoStore',
    '    }',
    '}',
  ],
  python: [
    'def binary_derived_memo(rem_cap: int, nv: list, nw: list) -> int:',
    '    """阶段 2: 衍生 01 包记忆化搜索"""',
    '    memo = [[-1] * (rem_cap + 1) for _ in range(len(nv))]',
    '    def dfs(idx: int, cap: int) -> int: # @step:callRoot # @step:fnEnter',
    '        if idx >= len(nv) or cap <= 0: # @step:baseCheck',
    '            return 0',
    '        if memo[idx][cap] != -1: # @step:memoCheck',
    '            return memo[idx][cap]',
    '        p1 = dfs(idx + 1, cap) # @step:branchNoPick',
    '        p2 = dfs(idx + 1, cap - nw[idx]) + nv[idx] if cap >= nw[idx] else 0 # @step:branchPick',
    '        memo[idx][cap] = max(p1, p2) # @step:memoStore',
    '        return memo[idx][cap]',
    '    return dfs(0, rem_cap)',
  ],
  javascript: [
    '// 阶段 2: 衍生 01 包记忆化搜索',
    'export function binaryDerivedMemo(remCap, nv, nw) {',
    '  const memo = Array.from({ length: nv.length }, () => new Array(remCap + 1).fill(-1));',
    '  function dfs(idx, cap) { // @step:callRoot // @step:fnEnter',
    '    if (idx >= nv.length || cap <= 0) return 0; // @step:baseCheck',
    '    if (memo[idx][cap] !== -1) return memo[idx][cap]; // @step:memoCheck',
    '    const p1 = dfs(idx + 1, cap); // @step:branchNoPick',
    '    const p2 = cap >= nw[idx] ? dfs(idx + 1, cap - nw[idx]) + nv[idx] : 0; // @step:branchPick',
    '    return (memo[idx][cap] = Math.max(p1, p2)); // @step:memoStore',
    '  }',
    '  return dfs(0, remCap);',
    '}',
  ],
};

export const BINARY_SPLIT_STAGE3_CODE_LANGUAGES: Record<string, string[]> = {
  cpp: [
    '#include <iostream>',
    '#include <vector>',
    'using namespace std;',
    '',
    '// 阶段 3: 衍生 01 包二维 DP 填表',
    'int computeBinary2D(int t, const vector<int>& nv, const vector<int>& nw) {',
    '    int m = nv.size();',
    '    vector<vector<int>> dp(m + 1, vector<int>(t + 1, 0)); // @step:initDp',
    '    for (int i = 1; i <= m; ++i) { // @step:outerLoopI',
    '        for (int j = 0; j <= t; ++j) { // @step:innerLoopJ',
    '            dp[i][j] = dp[i - 1][j]; // @step:inheritNoPick',
    '            if (j >= nw[i - 1]) { // @step:updatePick',
    '                dp[i][j] = max(dp[i][j], dp[i - 1][j - nw[i - 1]] + nv[i - 1]);',
    '            }',
    '        }',
    '    }',
    '    return dp[m][t]; // @step:returnAns',
    '}',
  ],
  java: [
    'package class075;',
    '',
    '// 阶段 3: 衍生 01 包二维 DP 填表',
    'public class Code02_BinarySplittingStage3 {',
    '    public static int computeBinary2D(int t, int m, int[] nv, int[] nw) {',
    '        int[][] dp = new int[m + 1][t + 1]; // @step:initDp',
    '        for (int i = 1; i <= m; i++) { // @step:outerLoopI',
    '            for (int j = 0; j <= t; j++) { // @step:innerLoopJ',
    '                dp[i][j] = dp[i - 1][j]; // @step:inheritNoPick',
    '                if (j >= nw[i]) { // @step:updatePick',
    '                    dp[i][j] = Math.max(dp[i][j], dp[i - 1][j - nw[i]] + nv[i]);',
    '                }',
    '            }',
    '        }',
    '        return dp[m][t]; // @step:returnAns',
    '    }',
    '}',
  ],
  python: [
    'def compute_binary_2d(t: int, nv: list, nw: list) -> int:',
    '    """阶段 3: 衍生 01 包二维 DP 填表"""',
    '    m = len(nv)',
    '    dp = [[0] * (t + 1) for _ in range(m + 1)] # @step:initDp',
    '    for i in range(1, m + 1): # @step:outerLoopI',
    '        for j in range(t + 1): # @step:innerLoopJ',
    '            dp[i][j] = dp[i - 1][j] # @step:inheritNoPick',
    '            if j >= nw[i - 1]: # @step:updatePick',
    '                dp[i][j] = max(dp[i][j], dp[i - 1][j - nw[i - 1]] + nv[i - 1])',
    '    return dp[m][t] # @step:returnAns',
  ],
  javascript: [
    '// 阶段 3: 衍生 01 包二维 DP 填表',
    'export function computeBinary2D(t, nv, nw) {',
    '  const m = nv.length;',
    '  const dp = Array.from({ length: m + 1 }, () => new Array(t + 1).fill(0)); // @step:initDp',
    '  for (let i = 1; i <= m; i++) { // @step:outerLoopI',
    '    for (let j = 0; j <= t; j++) { // @step:innerLoopJ',
    '      dp[i][j] = dp[i - 1][j]; // @step:inheritNoPick',
    '      if (j >= nw[i - 1]) { // @step:updatePick',
    '        dp[i][j] = Math.max(dp[i][j], dp[i - 1][j - nw[i - 1]] + nv[i - 1]);',
    '      }',
    '    }',
    '  }',
    '  return dp[m][t]; // @step:returnAns',
  ],
};

// ==========================================
// 3. Cherry Blossom Viewing (P1833 混合背包)
// ==========================================

export const CHERRY_STAGE1_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    'package class075;',
    '',
    '// 阶段 1: 观赏樱花 (统一二进制拆分后的衍生 01 递归分治)',
    'public class Code03_CherryRecursion {',
    '    public static int dfs(int[] cost, int[] val, int m, int idx, int remTime) {',
    '        if (idx == m || remTime <= 0) return 0;',
    '        int p1 = dfs(cost, val, m, idx + 1, remTime);',
    '        int p2 = 0;',
    '        if (remTime >= cost[idx]) {',
    '            p2 = dfs(cost, val, m, idx + 1, remTime - cost[idx]) + val[idx];',
    '        }',
    '        return Math.max(p1, p2);',
    '    }',
    '}',
  ],
  cpp: [
    '#include <vector>',
    '#include <algorithm>',
    'using namespace std;',
    '',
    '// 阶段 1: 观赏樱花暴力递归',
    'int dfs(const vector<int>& cost, const vector<int>& val, int idx, int remTime) {',
    '    if (idx == (int)cost.size() || remTime <= 0) return 0;',
    '    int p1 = dfs(cost, val, idx + 1, remTime);',
    '    int p2 = 0;',
    '    if (remTime >= cost[idx]) {',
    '        p2 = dfs(cost, val, idx + 1, remTime - cost[idx]) + val[idx];',
    '    }',
    '    return max(p1, p2);',
    '}',
  ],
  python: [
    '# 阶段 1: 观赏樱花暴力递归',
    'def dfs_cherry(cost: list, val: list, idx: int, rem_time: int) -> int:',
    '    if idx == len(cost) or rem_time <= 0:',
    '        return 0',
    '    p1 = dfs_cherry(cost, val, idx + 1, rem_time)',
    '    p2 = 0',
    '    if rem_time >= cost[idx]:',
    '        p2 = dfs_cherry(cost, val, idx + 1, rem_time - cost[idx]) + val[idx]',
    '    return max(p1, p2)',
  ],
  javascript: [
    '// 阶段 1: 观赏樱花暴力递归',
    'export function dfsCherry(cost, val, idx, remTime) {',
    '  if (idx === cost.length || remTime <= 0) return 0;',
    '  const p1 = dfsCherry(cost, val, idx + 1, remTime);',
    '  let p2 = 0;',
    '  if (remTime >= cost[idx]) {',
    '    p2 = dfsCherry(cost, val, idx + 1, remTime - cost[idx]) + val[idx];',
    '  }',
    '  return Math.max(p1, p2);',
    '}',
  ],
};

export const CHERRY_STAGE2_CODE_LANGUAGES: Record<string, string[]> = {
  cpp: [
    '#include <vector>',
    '#include <algorithm>',
    'using namespace std;',
    '',
    '// 阶段 2: 观赏樱花记忆化搜索',
    'int dfsMemo(int idx, int remTime, const vector<int>& cost, const vector<int>& val, vector<vector<int>>& memo) {',
    '    if (idx >= (int)cost.size() || remTime <= 0) return 0;',
    '    if (memo[idx][remTime] != -1) return memo[idx][remTime];',
    '    int p1 = dfsMemo(idx + 1, remTime, cost, val, memo);',
    '    int p2 = 0;',
    '    if (remTime >= cost[idx]) {',
    '        p2 = dfsMemo(idx + 1, remTime - cost[idx], cost, val, memo) + val[idx];',
    '    }',
    '    return memo[idx][remTime] = max(p1, p2);',
    '}',
  ],
  java: [
    'package class075;',
    '',
    '// 阶段 2: 观赏樱花记忆化搜索',
    'public class Code03_CherryMemo {',
    '    public static int dfsMemo(int idx, int remTime, int[] cost, int[] val, int m, int[][] memo) {',
    '        if (idx >= m || remTime <= 0) return 0;',
    '        if (memo[idx][remTime] != -1) return memo[idx][remTime];',
    '        int p1 = dfsMemo(idx + 1, remTime, cost, val, m, memo);',
    '        int p2 = 0;',
    '        if (remTime >= cost[idx]) {',
    '            p2 = dfsMemo(idx + 1, remTime - cost[idx], cost, val, m, memo) + val[idx];',
    '        }',
    '        return memo[idx][remTime] = Math.max(p1, p2);',
    '    }',
    '}',
  ],
  python: [
    'def cherry_memo(t: int, cost: list, val: list) -> int:',
    '    """阶段 2: 观赏樱花记忆化搜索"""',
    '    memo = [[-1] * (t + 1) for _ in range(len(cost))]',
    '    def dfs(idx: int, rem_time: int) -> int:',
    '        if idx >= len(cost) or rem_time <= 0:',
    '            return 0',
    '        if memo[idx][rem_time] != -1:',
    '            return memo[idx][rem_time]',
    '        p1 = dfs(idx + 1, rem_time)',
    '        p2 = dfs(idx + 1, rem_time - cost[idx]) + val[idx] if rem_time >= cost[idx] else 0',
    '        memo[idx][rem_time] = max(p1, p2)',
    '        return memo[idx][rem_time]',
    '    return dfs(0, t)',
  ],
  javascript: [
    '// 阶段 2: 衍生 01 包记忆化搜索',
    'export function cherryMemo(t, cost, val) {',
    '  const memo = Array.from({ length: cost.length }, () => new Array(t + 1).fill(-1));',
    '  function dfs(idx, remTime) {',
    '    if (idx >= cost.length || remTime <= 0) return 0;',
    '    if (memo[idx][remTime] !== -1) return memo[idx][remTime];',
    '    const p1 = dfs(idx + 1, remTime);',
    '    const p2 = remTime >= cost[idx] ? dfs(idx + 1, remTime - cost[idx]) + val[idx] : 0;',
    '    return (memo[idx][remTime] = Math.max(p1, p2));',
    '  }',
    '  return dfs(0, t);',
    '}',
  ],
};

export const CHERRY_STAGE3_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    'package class075;',
    '',
    '// 阶段 3: 观赏樱花严格二维动态规划',
    'public class Code03_Cherry2D {',
    '    public static int compute2D(int[] cost, int[] val, int m, int t) {',
    '        int[][] dp = new int[m + 1][t + 1];',
    '        for (int i = 1; i <= m; i++) {',
    '            int c = cost[i - 1], v = val[i - 1];',
    '            for (int j = 0; j <= t; j++) {',
    '                dp[i][j] = dp[i - 1][j];',
    '                if (j >= c) {',
    '                    dp[i][j] = Math.max(dp[i][j], dp[i - 1][j - c] + v);',
    '                }',
    '            }',
    '        }',
    '        return dp[m][t];',
    '    }',
    '}',
  ],
  cpp: [
    '#include <vector>',
    '#include <algorithm>',
    'using namespace std;',
    '',
    '// 阶段 3: 严格二维动态规划',
    'int compute2D(const vector<int>& cost, const vector<int>& val, int t) {',
    '    int m = cost.size();',
    '    vector<vector<int>> dp(m + 1, vector<int>(t + 1, 0));',
    '    for (int i = 1; i <= m; ++i) {',
    '        int c = cost[i - 1], v = val[i - 1];',
    '        for (int j = 0; j <= t; ++j) {',
    '            dp[i][j] = dp[i - 1][j];',
    '            if (j >= c) dp[i][j] = max(dp[i][j], dp[i - 1][j - c] + v);',
    '        }',
    '    }',
    '    return dp[m][t];',
    '}',
  ],
  python: [
    '# 阶段 3: 严格二维动态规划',
    'def compute_cherry_2d(cost: list, val: list, t: int) -> int:',
    '    m = len(cost)',
    '    dp = [[0] * (t + 1) for _ in range(m + 1)]',
    '    for i in range(1, m + 1):',
    '        c, v = cost[i - 1], val[i - 1]',
    '        for j in range(t + 1):',
    '            dp[i][j] = dp[i - 1][j]',
    '            if j >= c:',
    '                dp[i][j] = max(dp[i][j], dp[i - 1][j - c] + v)',
    '    return dp[m][t]',
  ],
  javascript: [
    '// 阶段 3: 严格二维动态规划',
    'export function computeCherry2D(cost, val, t) {',
    '  const m = cost.length;',
    '  const dp = Array.from({ length: m + 1 }, () => new Array(t + 1).fill(0));',
    '  for (let i = 1; i <= m; i++) {',
    '    const c = cost[i - 1], v = val[i - 1];',
    '    for (let j = 0; j <= t; j++) {',
    '      dp[i][j] = dp[i - 1][j];',
    '      if (j >= c) dp[i][j] = Math.max(dp[i][j], dp[i - 1][j - c] + v);',
    '    }',
    '  }',
    '  return dp[m][t];',
    '}',
  ],
};

// ==========================================
// 4. Coins Change Kinds (POJ 1742 混合背包求种类)
// ==========================================

export const COINS_CHANGE_STAGE1_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    'package class075;',
    '',
    '// 阶段 1: 暴力递归判定能否凑出金额',
    'public class Code05_CoinsRecursion {',
    '    public static boolean check(int[] val, int[] cnt, int n, int i, int rem) { // @step:fnEnter',
    '        if (rem == 0) return true; // @step:baseZero',
    '        if (i == n || rem < 0) return false; // @step:baseBound',
    '        for (int k = 0; k <= cnt[i] && k * val[i] <= rem; k++) { // @step:loopK',
    '            if (check(val, cnt, n, i + 1, rem - k * val[i])) return true; // @step:callNext',
    '        }',
    '        return false; // @step:returnFalse',
    '    }',
    '}',
  ],
  cpp: [
    '#include <vector>',
    'using namespace std;',
    '',
    '// 阶段 1: 暴力递归判定',
    'bool check(const vector<int>& val, const vector<int>& cnt, int i, int rem) { // @step:fnEnter',
    '    if (rem == 0) return true; // @step:baseZero',
    '    if (i == (int)val.size() || rem < 0) return false; // @step:baseBound',
    '    for (int k = 0; k <= cnt[i] && k * val[i] <= rem; ++k) { // @step:loopK',
    '        if (check(val, cnt, i + 1, rem - k * val[i])) return true; // @step:callNext',
    '    }',
    '    return false; // @step:returnFalse',
    '}',
  ],
  python: [
    '# 阶段 1: 暴力递归判定',
    'def check(val: list, cnt: list, i: int, rem: int) -> bool: # @step:fnEnter',
    '    if rem == 0: # @step:baseZero',
    '        return True',
    '    if i == len(val) or rem < 0: # @step:baseBound',
    '        return False',
    '    for k in range(cnt[i] + 1): # @step:loopK',
    '        if k * val[i] <= rem and check(val, cnt, i + 1, rem - k * val[i]): # @step:callNext',
    '            return True',
    '    return False # @step:returnFalse',
  ],
  javascript: [
    '// 阶段 1: 暴力递归判定',
    'export function check(val, cnt, i, rem) { // @step:fnEnter',
    '  if (rem === 0) return true; // @step:baseZero',
    '  if (i === val.length || rem < 0) return false; // @step:baseBound',
    '  for (let k = 0; k <= cnt[i] && k * val[i] <= rem; k++) { // @step:loopK',
    '    if (check(val, cnt, i + 1, rem - k * val[i])) return true; // @step:callNext',
    '  }',
    '  return false; // @step:returnFalse',
    '}',
  ],
};

export const COINS_CHANGE_STAGE2_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    'package class075;',
    '',
    '// 阶段 2: 记忆化搜索',
    'public class Code05_CoinsMemo {',
    '    public static boolean checkMemo(int[] val, int[] cnt, int n, int i, int rem, int[][] memo) { // @step:fnEnter',
    '        if (rem == 0) return true; // @step:baseZero',
    '        if (i == n || rem < 0) return false; // @step:baseBound',
    '        if (memo[i][rem] != -1) return memo[i][rem] == 1; // @step:checkMemo',
    '        for (int k = 0; k <= cnt[i] && k * val[i] <= rem; k++) { // @step:loopK',
    '            if (checkMemo(val, cnt, n, i + 1, rem - k * val[i], memo)) { // @step:callNext',
    '                memo[i][rem] = 1; // @step:memoTrue',
    '                return true;',
    '            }',
    '        }',
    '        memo[i][rem] = 0; // @step:memoFalse',
    '        return false;',
    '    }',
    '}',
  ],
  cpp: [
    '#include <vector>',
    'using namespace std;',
    '',
    '// 阶段 2: 记忆化搜索',
    'bool checkMemo(const vector<int>& val, const vector<int>& cnt, int i, int rem, vector<vector<int>>& memo) { // @step:fnEnter',
    '    if (rem == 0) return true; // @step:baseZero',
    '    if (i == (int)val.size() || rem < 0) return false; // @step:baseBound',
    '    if (memo[i][rem] != -1) return memo[i][rem] == 1; // @step:checkMemo',
    '    for (int k = 0; k <= cnt[i] && k * val[i] <= rem; ++k) { // @step:loopK',
    '        if (checkMemo(val, cnt, i + 1, rem - k * val[i], memo)) { // @step:callNext',
    '            return memo[i][rem] = 1, true; // @step:memoTrue',
    '        }',
    '    }',
    '    return memo[i][rem] = 0, false; // @step:memoFalse',
    '}',
  ],
  python: [
    '# 阶段 2: 记忆化搜索',
    'def check_memo(val: list, cnt: list, i: int, rem: int, memo: list) -> bool: # @step:fnEnter',
    '    if rem == 0: # @step:baseZero',
    '        return True',
    '    if i == len(val) or rem < 0: # @step:baseBound',
    '        return False',
    '    if memo[i][rem] != -1: # @step:checkMemo',
    '        return memo[i][rem] == 1',
    '    for k in range(cnt[i] + 1): # @step:loopK',
    '        if k * val[i] <= rem and check_memo(val, cnt, i + 1, rem - k * val[i], memo): # @step:callNext',
    '            memo[i][rem] = 1 # @step:memoTrue',
    '            return True',
    '    memo[i][rem] = 0 # @step:memoFalse',
    '    return False',
  ],
  javascript: [
    '// 阶段 2: 记忆化搜索',
    'export function checkMemo(val, cnt, i, rem, memo) { // @step:fnEnter',
    '  if (rem === 0) return true; // @step:baseZero',
    '  if (i === val.length || rem < 0) return false; // @step:baseBound',
    '  if (memo[i][rem] !== -1) return memo[i][rem] === 1; // @step:checkMemo',
    '  for (let k = 0; k <= cnt[i] && k * val[i] <= rem; k++) { // @step:loopK',
    '    if (checkMemo(val, cnt, i + 1, rem - k * val[i], memo)) { // @step:callNext',
    '      memo[i][rem] = 1; // @step:memoTrue',
    '      return true;',
    '    }',
    '  }',
    '  memo[i][rem] = 0; // @step:memoFalse',
    '  return false;',
    '}',
  ],
};

export const COINS_CHANGE_STAGE3_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    'package class075;',
    '',
    '// 阶段 3: 严格二维布尔动态规划',
    'public class Code05_Coins2D {',
    '    public static int compute2D(int[] val, int[] cnt, int n, int m) {',
    '        boolean[][] dp = new boolean[n + 1][m + 1]; // @step:initDp',
    '        dp[0][0] = true; // @step:initBase',
    '        for (int i = 1; i <= n; i++) { // @step:outerI',
    '            int v = val[i - 1], c = cnt[i - 1];',
    '            for (int j = 0; j <= m; j++) { // @step:innerJ',
    '                dp[i][j] = dp[i - 1][j]; // @step:inherit',
    '                for (int k = 1; k <= c && k * v <= j; k++) { // @step:loopK',
    '                    if (dp[i - 1][j - k * v]) { // @step:updateTrue',
    '                        dp[i][j] = true;',
    '                        break;',
    '                    }',
    '                }',
    '            }',
    '        }',
    '        int kinds = 0;',
    '        for (int j = 1; j <= m; j++) if (dp[n][j]) kinds++; // @step:countKinds',
    '        return kinds; // @step:returnAns',
    '    }',
    '}',
  ],
  cpp: [
    '#include <vector>',
    'using namespace std;',
    '',
    '// 阶段 3: 严格二维动态规划',
    'int compute2D(const vector<int>& val, const vector<int>& cnt, int m) {',
    '    int n = val.size();',
    '    vector<vector<bool>> dp(n + 1, vector<bool>(m + 1, false)); // @step:initDp',
    '    dp[0][0] = true; // @step:initBase',
    '    for (int i = 1; i <= n; ++i) { // @step:outerI',
    '        int v = val[i - 1], c = cnt[i - 1];',
    '        for (int j = 0; j <= m; ++j) { // @step:innerJ',
    '            dp[i][j] = dp[i - 1][j]; // @step:inherit',
    '            for (int k = 1; k <= c && k * v <= j; ++k) { // @step:loopK',
    '                if (dp[i - 1][j - k * v]) { dp[i][j] = true; break; } // @step:updateTrue',
    '            }',
    '        }',
    '    }',
    '    int kinds = 0;',
    '    for (int j = 1; j <= m; ++j) if (dp[n][j]) kinds++; // @step:countKinds',
    '    return kinds; // @step:returnAns',
    '}',
  ],
  python: [
    '# 阶段 3: 严格二维动态规划',
    'def compute_coins_2d(val: list, cnt: list, m: int) -> int:',
    '    n = len(val)',
    '    dp = [[False] * (m + 1) for _ in range(n + 1)] # @step:initDp',
    '    dp[0][0] = True # @step:initBase',
    '    for i in range(1, n + 1): # @step:outerI',
    '        v, c = val[i - 1], cnt[i - 1]',
    '        for j in range(m + 1): # @step:innerJ',
    '            dp[i][j] = dp[i - 1][j] # @step:inherit',
    '            for k in range(1, c + 1): # @step:loopK',
    '                if k * v <= j and dp[i - 1][j - k * v]: # @step:updateTrue',
    '                    dp[i][j] = True',
    '                    break',
    '    return sum(1 for j in range(1, m + 1) if dp[n][j]) # @step:returnAns',
  ],
  javascript: [
    '// 阶段 3: 严格二维动态规划',
    'export function computeCoins2D(val, cnt, m) {',
    '  const n = val.length;',
    '  const dp = Array.from({ length: n + 1 }, () => new Array(m + 1).fill(false)); // @step:initDp',
    '  dp[0][0] = true; // @step:initBase',
    '  for (let i = 1; i <= n; i++) { // @step:outerI',
    '    const v = val[i - 1], c = cnt[i - 1];',
    '    for (let j = 0; j <= m; j++) { // @step:innerJ',
    '      dp[i][j] = dp[i - 1][j]; // @step:inherit',
    '      for (let k = 1; k <= c && k * v <= j; k++) { // @step:loopK',
    '        if (dp[i - 1][j - k * v]) { // @step:updateTrue',
    '          dp[i][j] = true;',
    '          break;',
    '        }',
    '      }',
    '    }',
    '  }',
    '  let kinds = 0;',
    '  for (let j = 1; j <= m; j++) if (dp[n][j]) kinds++; // @step:countKinds',
    '  return kinds; // @step:returnAns',
    '}',
  ],
};

