/**
 * LeetCode 257: 二叉树的所有路径 (Binary Tree Paths)
 * 四语言权威解法与精准 1-Based 代码行号映射
 */

// ----------------------------------------------------
// Stage 1: 回溯法 DFS 递归与显式路径栈 (Backtracking DFS with Path Stack)
// ----------------------------------------------------
export const ALL_PATHS_STAGE1_CODES = {
  java: [
    'public class Solution {',
    '    public List<String> binaryTreePaths(TreeNode root) {',
    '        List<String> paths = new ArrayList<>();',
    '        if (root == null) return paths;',
    '        List<Integer> path = new ArrayList<>();',
    '        dfs(root, path, paths);',
    '        return paths;',
    '    }',
    '    private void dfs(TreeNode node, List<Integer> path, List<String> paths) {',
    '        path.add(node.val);',
    '        if (node.left == null && node.right == null) {',
    '            paths.add(buildPathString(path));',
    '        }',
    '        if (node.left != null) dfs(node.left, path, paths);',
    '        if (node.right != null) dfs(node.right, path, paths);',
    '        path.remove(path.size() - 1);',
    '    }',
    '}',
  ],
  cpp: [
    'class Solution {',
    'public:',
    '    vector<string> binaryTreePaths(TreeNode* root) {',
    '        vector<string> paths;',
    '        if (!root) return paths;',
    '        vector<int> path;',
    '        dfs(root, path, paths);',
    '        return paths;',
    '    }',
    '    void dfs(TreeNode* node, vector<int>& path, vector<string>& paths) {',
    '        path.push_back(node->val);',
    '        if (!node->left && !node->right) {',
    '            paths.push_back(buildPath(path));',
    '        }',
    '        if (node->left) dfs(node->left, path, paths);',
    '        if (node->right) dfs(node->right, path, paths);',
    '        path.pop_back();',
    '    }',
    '};',
  ],
  python: [
    'class Solution:',
    '    def binaryTreePaths(self, root: Optional[TreeNode]) -> List[str]:',
    '        paths = []',
    '        if not root: return paths',
    '        path = []',
    '        def dfs(node):',
    '            path.append(str(node.val))',
    '            if not node.left and not node.right:',
    '                paths.append("->".join(path))',
    '            if node.left: dfs(node.left)',
    '            if node.right: dfs(node.right)',
    '            path.pop()',
    '        dfs(root)',
    '        return paths',
  ],
  javascript: [
    'function binaryTreePaths(root) {',
    '    const paths = [];',
    '    if (!root) return paths;',
    '    const path = [];',
    '    function dfs(node) {',
    '        path.push(node.val);',
    '        if (!node.left && !node.right) {',
    '            paths.push(path.join("->"));',
    '        }',
    '        if (node.left) dfs(node.left);',
    '        if (node.right) dfs(node.right);',
    '        path.pop();',
    '    }',
    '    dfs(root);',
    '    return paths;',
    '}',
  ],
};

export const ALL_PATHS_STAGE1_LINES = {
  entry: { java: 2, cpp: 3, python: 2, javascript: 1 },
  baseNull: { java: 4, cpp: 5, python: 4, javascript: 3 },
  initPath: { java: 5, cpp: 6, python: 5, javascript: 4 },
  callDfs: { java: 6, cpp: 7, python: 13, javascript: 14 },
  returnPaths: { java: 7, cpp: 8, python: 14, javascript: 15 },
  dfsEntry: { java: 9, cpp: 10, python: 6, javascript: 5 },
  addNode: { java: 10, cpp: 11, python: 7, javascript: 6 },
  checkLeaf: { java: 11, cpp: 12, python: 8, javascript: 7 },
  harvestPath: { java: 12, cpp: 13, python: 9, javascript: 8 },
  recurseLeft: { java: 14, cpp: 15, python: 10, javascript: 10 },
  recurseRight: { java: 15, cpp: 16, python: 11, javascript: 11 },
  backtrack: { java: 16, cpp: 17, python: 12, javascript: 12 },
};

// ----------------------------------------------------
// Stage 2: 纯函数递归与不可变字符串传递 (Pure Functional DFS)
// ----------------------------------------------------
export const ALL_PATHS_STAGE2_CODES = {
  java: [
    'public class Solution {',
    '    public List<String> binaryTreePaths(TreeNode root) {',
    '        List<String> paths = new ArrayList<>();',
    '        if (root == null) return paths;',
    '        dfs(root, String.valueOf(root.val), paths);',
    '        return paths;',
    '    }',
    '    private void dfs(TreeNode node, String path, List<String> paths) {',
    '        if (node.left == null && node.right == null) {',
    '            paths.add(path);',
    '            return;',
    '        }',
    '        if (node.left != null) {',
    '            dfs(node.left, path + "->" + node.left.val, paths);',
    '        }',
    '        if (node.right != null) {',
    '            dfs(node.right, path + "->" + node.right.val, paths);',
    '        }',
    '    }',
    '}',
  ],
  cpp: [
    'class Solution {',
    'public:',
    '    vector<string> binaryTreePaths(TreeNode* root) {',
    '        vector<string> paths;',
    '        if (!root) return paths;',
    '        dfs(root, to_string(root->val), paths);',
    '        return paths;',
    '    }',
    '    void dfs(TreeNode* node, string path, vector<string>& paths) {',
    '        if (!node->left && !node->right) {',
    '            paths.push_back(path);',
    '            return;',
    '        }',
    '        if (node->left) {',
    '            dfs(node->left, path + "->" + to_string(node->left->val), paths);',
    '        }',
    '        if (node->right) {',
    '            dfs(node->right, path + "->" + to_string(node->right->val), paths);',
    '        }',
    '    }',
    '};',
  ],
  python: [
    'class Solution:',
    '    def binaryTreePaths(self, root: Optional[TreeNode]) -> List[str]:',
    '        paths = []',
    '        if not root: return paths',
    '        def dfs(node, path):',
    '            if not node.left and not node.right:',
    '                paths.append(path)',
    '                return',
    '            if node.left:',
    '                dfs(node.left, path + "->" + str(node.left.val))',
    '            if node.right:',
    '                dfs(node.right, path + "->" + str(node.right.val))',
    '        dfs(root, str(root.val))',
    '        return paths',
  ],
  javascript: [
    'function binaryTreePaths(root) {',
    '    const paths = [];',
    '    if (!root) return paths;',
    '    function dfs(node, path) {',
    '        if (!node.left && !node.right) {',
    '            paths.push(path);',
    '            return;',
    '        }',
    '        if (node.left) {',
    '            dfs(node.left, path + "->" + node.left.val);',
    '        }',
    '        if (node.right) {',
    '            dfs(node.right, path + "->" + node.right.val);',
    '        }',
    '    }',
    '    dfs(root, String(root.val));',
    '    return paths;',
    '}',
  ],
};

export const ALL_PATHS_STAGE2_LINES = {
  entry: { java: 2, cpp: 3, python: 2, javascript: 1 },
  baseNull: { java: 4, cpp: 5, python: 4, javascript: 3 },
  callDfs: { java: 5, cpp: 6, python: 13, javascript: 16 },
  returnPaths: { java: 6, cpp: 7, python: 14, javascript: 17 },
  dfsEntry: { java: 8, cpp: 9, python: 5, javascript: 4 },
  checkLeaf: { java: 9, cpp: 10, python: 6, javascript: 5 },
  harvestPath: { java: 10, cpp: 11, python: 7, javascript: 6 },
  leafReturn: { java: 11, cpp: 12, python: 8, javascript: 7 },
  checkLeft: { java: 13, cpp: 14, python: 9, javascript: 9 },
  recurseLeft: { java: 14, cpp: 15, python: 10, javascript: 10 },
  checkRight: { java: 16, cpp: 17, python: 11, javascript: 12 },
  recurseRight: { java: 17, cpp: 18, python: 12, javascript: 13 },
};

// ----------------------------------------------------
// Stage 3: 广度优先搜索双队列层序遍历 (BFS Double Queue Level Order)
// ----------------------------------------------------
export const ALL_PATHS_STAGE3_CODES = {
  java: [
    'public class Solution {',
    '    public List<String> binaryTreePaths(TreeNode root) {',
    '        List<String> paths = new ArrayList<>();',
    '        if (root == null) return paths;',
    '        Queue<TreeNode> nodeQueue = new LinkedList<>();',
    '        Queue<String> pathQueue = new LinkedList<>();',
    '        nodeQueue.offer(root);',
    '        pathQueue.offer(String.valueOf(root.val));',
    '        while (!nodeQueue.isEmpty()) {',
    '            TreeNode node = nodeQueue.poll();',
    '            String path = pathQueue.poll();',
    '            if (node.left == null && node.right == null) {',
    '                paths.add(path);',
    '            }',
    '            if (node.left != null) {',
    '                nodeQueue.offer(node.left);',
    '                pathQueue.offer(path + "->" + node.left.val);',
    '            }',
    '            if (node.right != null) {',
    '                nodeQueue.offer(node.right);',
    '                pathQueue.offer(path + "->" + node.right.val);',
    '            }',
    '        }',
    '        return paths;',
    '    }',
    '}',
  ],
  cpp: [
    'class Solution {',
    'public:',
    '    vector<string> binaryTreePaths(TreeNode* root) {',
    '        vector<string> paths;',
    '        if (!root) return paths;',
    '        queue<TreeNode*> nodeQueue;',
    '        queue<string> pathQueue;',
    '        nodeQueue.push(root);',
    '        pathQueue.push(to_string(root->val));',
    '        while (!nodeQueue.empty()) {',
    '            auto node = nodeQueue.front(); nodeQueue.pop();',
    '            auto path = pathQueue.front(); pathQueue.pop();',
    '            if (!node->left && !node->right) {',
    '                paths.push_back(path);',
    '            }',
    '            if (node->left) {',
    '                nodeQueue.push(node->left);',
    '                pathQueue.push(path + "->" + to_string(node->left->val));',
    '            }',
    '            if (node->right) {',
    '                nodeQueue.push(node->right);',
    '                pathQueue.push(path + "->" + to_string(node->right->val));',
    '            }',
    '        }',
    '        return paths;',
    '    }',
    '};',
  ],
  python: [
    'class Solution:',
    '    def binaryTreePaths(self, root: Optional[TreeNode]) -> List[str]:',
    '        paths = []',
    '        if not root: return paths',
    '        node_q = collections.deque([root])',
    '        path_q = collections.deque([str(root.val)])',
    '        while node_q:',
    '            node = node_q.popleft()',
    '            path = path_q.popleft()',
    '            if not node.left and not node.right:',
    '                paths.append(path)',
    '            if node.left:',
    '                node_q.append(node.left)',
    '                path_q.append(path + "->" + str(node.left.val))',
    '            if node.right:',
    '                node_q.append(node.right)',
    '                path_q.append(path + "->" + str(node.right.val))',
    '        return paths',
  ],
  javascript: [
    'function binaryTreePaths(root) {',
    '    const paths = [];',
    '    if (!root) return paths;',
    '    const nodeQueue = [root];',
    '    const pathQueue = [String(root.val)];',
    '    while (nodeQueue.length > 0) {',
    '        const node = nodeQueue.shift();',
    '        const path = pathQueue.shift();',
    '        if (!node.left && !node.right) {',
    '            paths.push(path);',
    '        }',
    '        if (node.left) {',
    '            nodeQueue.push(node.left);',
    '            pathQueue.push(path + "->" + node.left.val);',
    '        }',
    '        if (node.right) {',
    '            nodeQueue.push(node.right);',
    '            pathQueue.push(path + "->" + node.right.val);',
    '        }',
    '    }',
    '    return paths;',
    '}',
  ],
};

export const ALL_PATHS_STAGE3_LINES = {
  entry: { java: 2, cpp: 3, python: 2, javascript: 1 },
  baseNull: { java: 4, cpp: 5, python: 4, javascript: 3 },
  initQueues: { java: 5, cpp: 6, python: 5, javascript: 4 },
  offerRoot: { java: 7, cpp: 8, python: 5, javascript: 4 },
  whileLoop: { java: 9, cpp: 10, python: 7, javascript: 6 },
  pollNodeAndPath: { java: 10, cpp: 11, python: 8, javascript: 7 },
  checkLeaf: { java: 12, cpp: 13, python: 10, javascript: 9 },
  harvestPath: { java: 13, cpp: 14, python: 11, javascript: 10 },
  pushLeft: { java: 16, cpp: 17, python: 13, javascript: 13 },
  pushRight: { java: 20, cpp: 21, python: 16, javascript: 17 },
  returnPaths: { java: 24, cpp: 25, python: 18, javascript: 21 },
};
