/**
 * 二叉树中的最大路径和多阶段演进代码模板 (LeetCode 124 / Zuoshen Class 077)
 *
 * Stage 1: 递归后序遍历与单边最大贡献分离 (Recursive Postorder & Single-Branch Gain · LC 124 经典树形 DP)
 * Stage 2: 树形 DP 二元信息汇聚模型 (Tree DP Info Tuple Pattern · Zuoshen Class 077 套路)
 * Stage 3: 显式后序遍历与状态表映射 (Iterative Postorder & Gain Table · 零系统栈递归)
 *
 * 覆盖 Java / C++ / Python / JavaScript 四语言
 */

export const MAX_PATH_SUM_STAGE1_CODES: Record<string, string[]> = {
  java: [
    'public class Solution {',
    '    private int maxSum = Integer.MIN_VALUE;',
    '    public int maxPathSum(TreeNode root) {',
    '        maxGain(root);',
    '        return maxSum;',
    '    }',
    '    private int maxGain(TreeNode node) {',
    '        if (node == null) return 0;',
    '        int leftGain = Math.max(0, maxGain(node.left));',
    '        int rightGain = Math.max(0, maxGain(node.right));',
    '        int currentArch = node.val + leftGain + rightGain;',
    '        maxSum = Math.max(maxSum, currentArch);',
    '        return node.val + Math.max(leftGain, rightGain);',
    '    }',
    '}',
  ],
  cpp: [
    'class Solution {',
    '    int maxSum = INT_MIN;',
    '    int maxGain(TreeNode* node) {',
    '        if (!node) return 0;',
    '        int leftGain = max(0, maxGain(node->left));',
    '        int rightGain = max(0, maxGain(node->right));',
    '        int currentArch = node->val + leftGain + rightGain;',
    '        maxSum = max(maxSum, currentArch);',
    '        return node->val + max(leftGain, rightGain);',
    '    }',
    'public:',
    '    int maxPathSum(TreeNode* root) {',
    '        maxGain(root);',
    '        return maxSum;',
    '    }',
    '};',
  ],
  python: [
    'class Solution:',
    '    def maxPathSum(self, root: Optional[TreeNode]) -> int:',
    '        self.max_sum = float("-inf")',
    '        def max_gain(node):',
    '            if not node: return 0',
    '            left_gain = max(0, max_gain(node.left))',
    '            right_gain = max(0, max_gain(node.right))',
    '            current_arch = node.val + left_gain + right_gain',
    '            self.max_sum = max(self.max_sum, current_arch)',
    '            return node.val + max(left_gain, right_gain)',
    '        max_gain(root)',
    '        return self.max_sum',
  ],
  javascript: [
    'function maxPathSum(root) {',
    '    let maxSum = -Infinity;',
    '    function maxGain(node) {',
    '        if (!node) return 0;',
    '        const leftGain = Math.max(0, maxGain(node.left));',
    '        const rightGain = Math.max(0, maxGain(node.right));',
    '        const currentArch = node.val + leftGain + rightGain;',
    '        maxSum = Math.max(maxSum, currentArch);',
    '        return node.val + Math.max(leftGain, rightGain);',
    '    }',
    '    maxGain(root);',
    '    return maxSum;',
    '}',
  ],
};

export const MAX_PATH_SUM_STAGE2_CODES: Record<string, string[]> = {
  java: [
    'public class Solution {',
    '    static class Info {',
    '        int maxPathSum, maxGainFromRoot;',
    '        Info(int m, int g) { maxPathSum = m; maxGainFromRoot = g; }',
    '    }',
    '    public int maxPathSum(TreeNode root) {',
    '        if (root == null) return 0;',
    '        return process(root).maxPathSum;',
    '    }',
    '    private Info process(TreeNode x) {',
    '        if (x == null) return null;',
    '        Info left = process(x.left);',
    '        Info right = process(x.right);',
    '        int leftGain = left != null ? Math.max(0, left.maxGainFromRoot) : 0;',
    '        int rightGain = right != null ? Math.max(0, right.maxGainFromRoot) : 0;',
    '        int maxGainFromRoot = x.val + Math.max(leftGain, rightGain);',
    '        int arch = x.val + leftGain + rightGain;',
    '        int maxPath = arch;',
    '        if (left != null) maxPath = Math.max(maxPath, left.maxPathSum);',
    '        if (right != null) maxPath = Math.max(maxPath, right.maxPathSum);',
    '        return new Info(maxPath, maxGainFromRoot);',
    '    }',
    '}',
  ],
  cpp: [
    'class Solution {',
    '    struct Info { int maxPathSum; int maxGainFromRoot; };',
    '    Info process(TreeNode* x) {',
    '        if (!x) return {INT_MIN, 0};',
    '        Info left = process(x->left);',
    '        Info right = process(x->right);',
    '        int leftGain = max(0, left.maxGainFromRoot);',
    '        int rightGain = max(0, right.maxGainFromRoot);',
    '        int gain = x->val + max(leftGain, rightGain);',
    '        int arch = x->val + leftGain + rightGain;',
    '        int maxPath = max({arch, left.maxPathSum, right.maxPathSum});',
    '        return {maxPath, gain};',
    '    }',
    'public:',
    '    int maxPathSum(TreeNode* root) {',
    '        return process(root).maxPathSum;',
    '    }',
    '};',
  ],
  python: [
    'class Solution:',
    '    def maxPathSum(self, root: Optional[TreeNode]) -> int:',
    '        def process(x):',
    '            if not x: return float("-inf"), 0',
    '            l_max, l_gain = process(x.left)',
    '            r_max, r_gain = process(x.right)',
    '            left_gain = max(0, l_gain)',
    '            right_gain = max(0, r_gain)',
    '            gain = x.val + max(left_gain, right_gain)',
    '            arch = x.val + left_gain + right_gain',
    '            max_path = max(arch, l_max, r_max)',
    '            return max_path, gain',
    '        return process(root)[0]',
  ],
  javascript: [
    'function maxPathSum(root) {',
    '    function process(x) {',
    '        if (!x) return { maxPathSum: -Infinity, maxGainFromRoot: 0 };',
    '        const left = process(x.left);',
    '        const right = process(x.right);',
    '        const leftGain = Math.max(0, left.maxGainFromRoot);',
    '        const rightGain = Math.max(0, right.maxGainFromRoot);',
    '        const gain = x.val + Math.max(leftGain, rightGain);',
    '        const arch = x.val + leftGain + rightGain;',
    '        const maxPath = Math.max(arch, left.maxPathSum, right.maxPathSum);',
    '        return { maxPathSum: maxPath, maxGainFromRoot: gain };',
    '    }',
    '    return process(root).maxPathSum;',
    '}',
  ],
};

export const MAX_PATH_SUM_STAGE3_CODES: Record<string, string[]> = {
  java: [
    'public class Solution {',
    '    public int maxPathSum(TreeNode root) {',
    '        if (root == null) return 0;',
    '        int maxSum = Integer.MIN_VALUE;',
    '        Map<TreeNode, Integer> gainMap = new HashMap<>();',
    '        Deque<TreeNode> stack = new ArrayDeque<>();',
    '        TreeNode curr = root, lastVisited = null;',
    '        while (curr != null || !stack.isEmpty()) {',
    '            while (curr != null) { stack.push(curr); curr = curr.left; }',
    '            TreeNode top = stack.peek();',
    '            if (top.right != null && top.right != lastVisited) {',
    '                curr = top.right;',
    '            } else {',
    '                stack.pop();',
    '                int l = Math.max(0, gainMap.getOrDefault(top.left, 0));',
    '                int r = Math.max(0, gainMap.getOrDefault(top.right, 0));',
    '                maxSum = Math.max(maxSum, top.val + l + r);',
    '                gainMap.put(top, top.val + Math.max(l, r));',
    '                lastVisited = top;',
    '            }',
    '        }',
    '        return maxSum;',
    '    }',
    '}',
  ],
  cpp: [
    'class Solution {',
    'public:',
    '    int maxPathSum(TreeNode* root) {',
    '        if (!root) return 0;',
    '        int maxSum = INT_MIN;',
    '        unordered_map<TreeNode*, int> gainMap;',
    '        stack<TreeNode*> st;',
    '        TreeNode* curr = root; TreeNode* last = nullptr;',
    '        while (curr || !st.empty()) {',
    '            while (curr) { st.push(curr); curr = curr->left; }',
    '            TreeNode* top = st.top();',
    '            if (top->right && top->right != last) {',
    '                curr = top->right;',
    '            } else {',
    '                st.pop();',
    '                int l = max(0, gainMap[top->left]);',
    '                int r = max(0, gainMap[top->right]);',
    '                maxSum = max(maxSum, top->val + l + r);',
    '                gainMap[top] = top->val + max(l, r);',
    '                last = top;',
    '            }',
    '        }',
    '        return maxSum;',
    '    }',
    '};',
  ],
  python: [
    'class Solution:',
    '    def maxPathSum(self, root: Optional[TreeNode]) -> int:',
    '        if not root: return 0',
    '        max_sum = float("-inf")',
    '        gain_map = {}',
    '        stack = []',
    '        curr, last = root, None',
    '        while curr or stack:',
    '            while curr: stack.append(curr); curr = curr.left',
    '            top = stack[-1]',
    '            if top.right and top.right != last:',
    '                curr = top.right',
    '            else:',
    '                stack.pop()',
    '                l = max(0, gain_map.get(top.left, 0))',
    '                r = max(0, gain_map.get(top.right, 0))',
    '                max_sum = max(max_sum, top.val + l + r)',
    '                gain_map[top] = top.val + max(l, r)',
    '                last = top',
    '        return max_sum',
  ],
  javascript: [
    'function maxPathSum(root) {',
    '    if (!root) return 0;',
    '    let maxSum = -Infinity;',
    '    const gainMap = new Map();',
    '    const stack = [];',
    '    let curr = root, last = null;',
    '    while (curr || stack.length) {',
    '        while (curr) { stack.push(curr); curr = curr.left; }',
    '        const top = stack[stack.length - 1];',
    '        if (top.right && top.right !== last) {',
    '            curr = top.right;',
    '        } else {',
    '            stack.pop();',
    '            const l = Math.max(0, gainMap.get(top.left) || 0);',
    '            const r = Math.max(0, gainMap.get(top.right) || 0);',
    '            maxSum = Math.max(maxSum, top.val + l + r);',
    '            gainMap.set(top, top.val + Math.max(l, r));',
    '            last = top;',
    '        }',
    '    }',
    '    return maxSum;',
    '}',
  ],
};

export const MAX_PATH_SUM_STAGE1_LINES = {
  entry: { java: 3, cpp: 12, python: 2, javascript: 1 },
  callRoot: { java: 4, cpp: 13, python: 11, javascript: 11 },
  done: { java: 5, cpp: 14, python: 12, javascript: 12 },
  dfsEntry: { java: 7, cpp: 3, python: 4, javascript: 3 },
  baseNull: { java: 8, cpp: 4, python: 5, javascript: 4 },
  calcLeft: { java: 9, cpp: 5, python: 6, javascript: 5 },
  leftDone: { java: 9, cpp: 5, python: 6, javascript: 5 },
  calcRight: { java: 10, cpp: 6, python: 7, javascript: 6 },
  rightDone: { java: 10, cpp: 6, python: 7, javascript: 6 },
  calcArch: { java: 11, cpp: 7, python: 8, javascript: 7 },
  updateMax: { java: 12, cpp: 8, python: 9, javascript: 8 },
  returnSingle: { java: 13, cpp: 9, python: 10, javascript: 9 },
};

export const MAX_PATH_SUM_STAGE2_LINES = {
  entry: { java: 6, cpp: 15, python: 2, javascript: 1 },
  baseNull: { java: 7, cpp: 15, python: 2, javascript: 1 },
  callProcess: { java: 8, cpp: 16, python: 13, javascript: 13 },
  done: { java: 8, cpp: 16, python: 13, javascript: 13 },
  processEntry: { java: 10, cpp: 3, python: 3, javascript: 2 },
  processNull: { java: 11, cpp: 4, python: 4, javascript: 3 },
  callLeft: { java: 12, cpp: 5, python: 5, javascript: 4 },
  callRight: { java: 13, cpp: 6, python: 6, javascript: 5 },
  calcGains: { java: 16, cpp: 9, python: 9, javascript: 8 },
  calcArch: { java: 17, cpp: 10, python: 10, javascript: 9 },
  mergeMax: { java: 20, cpp: 11, python: 11, javascript: 10 },
  returnInfo: { java: 21, cpp: 12, python: 12, javascript: 11 },
};

export const MAX_PATH_SUM_STAGE3_LINES = {
  entry: { java: 2, cpp: 3, python: 2, javascript: 1 },
  baseNull: { java: 3, cpp: 4, python: 3, javascript: 2 },
  init: { java: 7, cpp: 8, python: 7, javascript: 6 },
  whileLoop: { java: 8, cpp: 9, python: 8, javascript: 7 },
  pushLeftBranch: { java: 9, cpp: 10, python: 9, javascript: 8 },
  peekTop: { java: 10, cpp: 11, python: 10, javascript: 9 },
  turnRight: { java: 12, cpp: 13, python: 12, javascript: 11 },
  popNode: { java: 14, cpp: 15, python: 14, javascript: 13 },
  calcGains: { java: 16, cpp: 17, python: 16, javascript: 15 },
  updateMax: { java: 17, cpp: 18, python: 17, javascript: 16 },
  saveGain: { java: 18, cpp: 19, python: 18, javascript: 17 },
  done: { java: 22, cpp: 23, python: 20, javascript: 21 },
};

