/**
 * LeetCode 513: 找树左下角的值 (Find Bottom Left Tree Value)
 * 四语言权威解法与精准 1-Based 代码行号映射
 */

// ----------------------------------------------------
// Stage 1: 先序递归 DFS 与最深层先登者锁定 (Preorder DFS with Max Depth First-Visit)
// ----------------------------------------------------
export const BOTTOM_LEFT_STAGE1_CODES = {
  java: [
    'public class Solution {',
    '    private int maxDepth = -1;',
    '    private int bottomLeft = 0;',
    '    public int findBottomLeftValue(TreeNode root) {',
    '        maxDepth = -1; bottomLeft = 0;',
    '        if (root == null) return 0;',
    '        dfs(root, 0);',
    '        return bottomLeft;',
    '    }',
    '    private void dfs(TreeNode node, int depth) {',
    '        if (node == null) return;',
    '        if (node.left == null && node.right == null) {',
    '            if (depth > maxDepth) {',
    '                maxDepth = depth; bottomLeft = node.val;',
    '            }',
    '            return;',
    '        }',
    '        if (node.left != null) dfs(node.left, depth + 1);',
    '        if (node.right != null) dfs(node.right, depth + 1);',
    '    }',
    '}',
  ],
  cpp: [
    'class Solution {',
    '    int maxDepth = -1; int bottomLeft = 0;',
    'public:',
    '    int findBottomLeftValue(TreeNode* root) {',
    '        maxDepth = -1; bottomLeft = 0;',
    '        if (!root) return 0;',
    '        dfs(root, 0);',
    '        return bottomLeft;',
    '    }',
    '    void dfs(TreeNode* node, int depth) {',
    '        if (!node) return;',
    '        if (!node->left && !node->right) {',
    '            if (depth > maxDepth) {',
    '                maxDepth = depth; bottomLeft = node->val;',
    '            }',
    '            return;',
    '        }',
    '        if (node->left) dfs(node->left, depth + 1);',
    '        if (node->right) dfs(node->right, depth + 1);',
    '    }',
    '};',
  ],
  python: [
    'class Solution:',
    '    def findBottomLeftValue(self, root: Optional[TreeNode]) -> int:',
    '        if not root: return 0',
    '        max_depth, bottom_left = -1, 0',
    '        def dfs(node, depth):',
    '            nonlocal max_depth, bottom_left',
    '            if not node.left and not node.right:',
    '                if depth > max_depth:',
    '                    max_depth, bottom_left = depth, node.val',
    '                return',
    '            if node.left: dfs(node.left, depth + 1)',
    '            if node.right: dfs(node.right, depth + 1)',
    '        dfs(root, 0)',
    '        return bottom_left',
  ],
  javascript: [
    'function findBottomLeftValue(root) {',
    '    if (!root) return 0;',
    '    let maxDepth = -1; let bottomLeft = 0;',
    '    function dfs(node, depth) {',
    '        if (!node.left && !node.right) {',
    '            if (depth > maxDepth) {',
    '                maxDepth = depth; bottomLeft = node.val;',
    '            }',
    '            return;',
    '        }',
    '        if (node.left) dfs(node.left, depth + 1);',
    '        if (node.right) dfs(node.right, depth + 1);',
    '    }',
    '    dfs(root, 0);',
    '    return bottomLeft;',
    '}',
  ],
};

export const BOTTOM_LEFT_STAGE1_LINES = {
  entry: { java: 4, cpp: 4, python: 2, javascript: 1 },
  initVars: { java: 5, cpp: 5, python: 4, javascript: 3 },
  baseNull: { java: 6, cpp: 6, python: 3, javascript: 2 },
  callDfs: { java: 7, cpp: 7, python: 13, javascript: 14 },
  returnAns: { java: 8, cpp: 8, python: 14, javascript: 15 },
  dfsEntry: { java: 10, cpp: 10, python: 5, javascript: 4 },
  checkNull: { java: 11, cpp: 11, python: 6, javascript: 4 },
  checkLeaf: { java: 12, cpp: 12, python: 7, javascript: 5 },
  checkDepth: { java: 13, cpp: 13, python: 8, javascript: 6 },
  updateAns: { java: 14, cpp: 14, python: 9, javascript: 7 },
  leafReturn: { java: 16, cpp: 16, python: 10, javascript: 9 },
  recurseLeft: { java: 18, cpp: 18, python: 11, javascript: 11 },
  recurseRight: { java: 19, cpp: 19, python: 12, javascript: 12 },
  done: { java: 8, cpp: 8, python: 14, javascript: 15 },
};

// ----------------------------------------------------
// Stage 2: 标准层序 BFS 队列与层首捕获 (Standard Level-Order BFS)
// ----------------------------------------------------
export const BOTTOM_LEFT_STAGE2_CODES = {
  java: [
    'public class Solution {',
    '    public int findBottomLeftValue(TreeNode root) {',
    '        if (root == null) return 0;',
    '        Queue<TreeNode> queue = new LinkedList<>();',
    '        queue.offer(root);',
    '        int bottomLeft = root.val;',
    '        while (!queue.isEmpty()) {',
    '            int size = queue.size();',
    '            for (int i = 0; i < size; i++) {',
    '                TreeNode cur = queue.poll();',
    '                if (i == 0) bottomLeft = cur.val;',
    '                if (cur.left != null) queue.offer(cur.left);',
    '                if (cur.right != null) queue.offer(cur.right);',
    '            }',
    '        }',
    '        return bottomLeft;',
    '    }',
    '}',
  ],
  cpp: [
    'class Solution {',
    'public:',
    '    int findBottomLeftValue(TreeNode* root) {',
    '        if (!root) return 0;',
    '        queue<TreeNode*> q;',
    '        q.push(root);',
    '        int bottomLeft = root->val;',
    '        while (!q.empty()) {',
    '            int size = q.size();',
    '            for (int i = 0; i < size; i++) {',
    '                auto cur = q.front(); q.pop();',
    '                if (i == 0) bottomLeft = cur->val;',
    '                if (cur->left) q.push(cur->left);',
    '                if (cur->right) q.push(cur->right);',
    '            }',
    '        }',
    '        return bottomLeft;',
    '    }',
    '};',
  ],
  python: [
    'class Solution:',
    '    def findBottomLeftValue(self, root: Optional[TreeNode]) -> int:',
    '        if not root: return 0',
    '        q = collections.deque([root])',
    '        bottom_left = root.val',
    '        while q:',
    '            size = len(q)',
    '            for i in range(size):',
    '                cur = q.popleft()',
    '                if i == 0: bottom_left = cur.val',
    '                if cur.left: q.append(cur.left)',
    '                if cur.right: q.append(cur.right)',
    '        return bottom_left',
  ],
  javascript: [
    'function findBottomLeftValue(root) {',
    '    if (!root) return 0;',
    '    const queue = [root];',
    '    let bottomLeft = root.val;',
    '    while (queue.length > 0) {',
    '        const size = queue.length; ',
    '        for (let i = 0; i < size; i++) {',
    '            const cur = queue.shift();',
    '            if (i === 0) bottomLeft = cur.val;',
    '            if (cur.left) queue.push(cur.left);',
    '            if (cur.right) queue.push(cur.right);',
    '        }',
    '    }',
    '    return bottomLeft;',
    '}',
  ],
};

export const BOTTOM_LEFT_STAGE2_LINES = {
  entry: { java: 2, cpp: 3, python: 2, javascript: 1 },
  baseNull: { java: 3, cpp: 4, python: 3, javascript: 2 },
  initQueue: { java: 4, cpp: 5, python: 4, javascript: 3 },
  initAns: { java: 6, cpp: 7, python: 5, javascript: 4 },
  whileLoop: { java: 7, cpp: 8, python: 6, javascript: 5 },
  getLevelSize: { java: 8, cpp: 9, python: 7, javascript: 6 },
  forLevel: { java: 9, cpp: 10, python: 8, javascript: 7 },
  pollNode: { java: 10, cpp: 11, python: 9, javascript: 8 },
  captureFirst: { java: 11, cpp: 12, python: 10, javascript: 9 },
  pushLeft: { java: 12, cpp: 13, python: 11, javascript: 10 },
  pushRight: { java: 13, cpp: 14, python: 12, javascript: 11 },
  returnAns: { java: 16, cpp: 17, python: 13, javascript: 14 },
};

// ----------------------------------------------------
// Stage 3: 逆向右先层序 BFS (Reverse Right-to-Left BFS · 最优解)
// ----------------------------------------------------
export const BOTTOM_LEFT_STAGE3_CODES = {
  java: [
    'public class Solution {',
    '    public int findBottomLeftValue(TreeNode root) {',
    '        if (root == null) return 0;',
    '        Queue<TreeNode> queue = new LinkedList<>();',
    '        queue.offer(root);',
    '        TreeNode cur = root;',
    '        while (!queue.isEmpty()) {',
    '            cur = queue.poll();',
    '            if (cur.right != null) queue.offer(cur.right);',
    '            if (cur.left != null) queue.offer(cur.left);',
    '        }',
    '        return cur.val;',
    '    }',
    '}',
  ],
  cpp: [
    'class Solution {',
    'public:',
    '    int findBottomLeftValue(TreeNode* root) {',
    '        if (!root) return 0;',
    '        queue<TreeNode*> q;',
    '        q.push(root);',
    '        TreeNode* cur = root;',
    '        while (!q.empty()) {',
    '            cur = q.front(); q.pop();',
    '            if (cur->right) q.push(cur->right);',
    '            if (cur->left) q.push(cur->left);',
    '        }',
    '        return cur->val;',
    '    }',
    '};',
  ],
  python: [
    'class Solution:',
    '    def findBottomLeftValue(self, root: Optional[TreeNode]) -> int:',
    '        if not root: return 0',
    '        q = collections.deque([root])',
    '        cur = root',
    '        while q:',
    '            cur = q.popleft()',
    '            if cur.right: q.append(cur.right)',
    '            if cur.left: q.append(cur.left)',
    '        return cur.val',
  ],
  javascript: [
    'function findBottomLeftValue(root) {',
    '    if (!root) return 0;',
    '    const queue = [root];',
    '    let cur = root;',
    '    while (queue.length > 0) {',
    '        cur = queue.shift();',
    '        if (cur.right) queue.push(cur.right);',
    '        if (cur.left) queue.push(cur.left);',
    '    }',
    '    return cur.val;',
    '}',
  ],
};

export const BOTTOM_LEFT_STAGE3_LINES = {
  entry: { java: 2, cpp: 3, python: 2, javascript: 1 },
  baseNull: { java: 3, cpp: 4, python: 3, javascript: 2 },
  initQueue: { java: 4, cpp: 5, python: 4, javascript: 3 },
  initCur: { java: 6, cpp: 7, python: 5, javascript: 4 },
  whileLoop: { java: 7, cpp: 8, python: 6, javascript: 5 },
  pollCur: { java: 8, cpp: 9, python: 7, javascript: 6 },
  pushRightFirst: { java: 9, cpp: 10, python: 8, javascript: 7 },
  pushLeftSecond: { java: 10, cpp: 11, python: 9, javascript: 8 },
  returnAns: { java: 12, cpp: 13, python: 10, javascript: 10 },
};
