/**
 * 从前序/后序与中序遍历构造二叉树多阶段演进代码模板 (LeetCode 105 & 106)
 *
 * Stage 1: 前序+中序分治切分递归构造 (Preorder + Inorder Recursive · LC 105)
 * Stage 2: 后序+中序分治切分递归构造 (Postorder + Inorder Recursive · LC 106)
 * Stage 3: 迭代显式栈模拟前序重构 (Iterative Stack Preorder Construction · LC 105 迭代法)
 *
 * 覆盖 Java / C++ / Python / JavaScript 四语言
 */

export const BUILD_TREE_STAGE1_PRE_IN_CODE: Record<string, string[]> = {
  java: [
    'class Solution {',
    '    private Map<Integer, Integer> inMap = new HashMap<>();',
    '    public TreeNode buildTree(int[] preorder, int[] inorder) {',
    '        for (int i = 0; i < inorder.length; i++) inMap.put(inorder[i], i);',
    '        return build(preorder, 0, preorder.length - 1, 0, inorder.length - 1);',
    '    }',
    '    private TreeNode build(int[] pre, int pL, int pR, int iL, int iR) {',
    '        if (pL > pR || iL > iR) return null;',
    '        int rootVal = pre[pL];',
    '        TreeNode root = new TreeNode(rootVal);',
    '        int inRoot = inMap.get(rootVal);',
    '        int leftLen = inRoot - iL;',
    '        root.left = build(pre, pL + 1, pL + leftLen, iL, inRoot - 1);',
    '        root.right = build(pre, pL + leftLen + 1, pR, inRoot + 1, iR);',
    '        return root;',
    '    }',
    '}',
  ],
  cpp: [
    'class Solution {',
    '    unordered_map<int, int> inMap;',
    'public:',
    '    TreeNode* buildTree(vector<int>& preorder, vector<int>& inorder) {',
    '        for (int i = 0; i < inorder.size(); i++) inMap[inorder[i]] = i;',
    '        return build(preorder, 0, preorder.size() - 1, 0, inorder.size() - 1);',
    '    }',
    '    TreeNode* build(vector<int>& pre, int pL, int pR, int iL, int iR) {',
    '        if (pL > pR || iL > iR) return nullptr;',
    '        int rootVal = pre[pL];',
    '        TreeNode* root = new TreeNode(rootVal);',
    '        int inRoot = inMap[rootVal];',
    '        int leftLen = inRoot - iL;',
    '        root->left = build(pre, pL + 1, pL + leftLen, iL, inRoot - 1);',
    '        root->right = build(pre, pL + leftLen + 1, pR, inRoot + 1, iR);',
    '        return root;',
    '    }',
    '};',
  ],
  python: [
    'class Solution:',
    '    def buildTree(self, preorder: list[int], inorder: list[int]) -> Optional[TreeNode]:',
    '        in_map = {val: idx for idx, val in enumerate(inorder)}',
    '        def build(pL: int, pR: int, iL: int, iR: int) -> Optional[TreeNode]:',
    '            if pL > pR or iL > iR: return None',
    '            root_val = preorder[pL]',
    '            root = TreeNode(root_val)',
    '            in_root = in_map[root_val]',
    '            left_len = in_root - iL',
    '            root.left = build(pL + 1, pL + left_len, iL, in_root - 1)',
    '            root.right = build(pL + left_len + 1, pR, in_root + 1, iR)',
    '            return root',
    '        return build(0, len(preorder) - 1, 0, len(inorder) - 1)',
  ],
  javascript: [
    'function buildTree(preorder, inorder) {',
    '    const inMap = new Map();',
    '    inorder.forEach((val, idx) => inMap.set(val, idx));',
    '    function build(pL, pR, iL, iR) {',
    '        if (pL > pR || iL > iR) return null;',
    '        const rootVal = preorder[pL];',
    '        const root = new TreeNode(rootVal);',
    '        const inRoot = inMap.get(rootVal);',
    '        const leftLen = inRoot - iL;',
    '        root.left = build(pL + 1, pL + leftLen, iL, inRoot - 1);',
    '        root.right = build(pL + leftLen + 1, pR, inRoot + 1, iR);',
    '        return root;',
    '    }',
    '    return build(0, preorder.length - 1, 0, inorder.length - 1);',
    '}',
  ],
};

export const BUILD_TREE_STAGE2_POST_IN_CODE: Record<string, string[]> = {
  java: [
    'class Solution {',
    '    private Map<Integer, Integer> inMap = new HashMap<>();',
    '    public TreeNode buildTree(int[] inorder, int[] postorder) {',
    '        for (int i = 0; i < inorder.length; i++) inMap.put(inorder[i], i);',
    '        return build(postorder, 0, postorder.length - 1, 0, inorder.length - 1);',
    '    }',
    '    private TreeNode build(int[] post, int postL, int postR, int inL, int inR) {',
    '        if (postL > postR || inL > inR) return null;',
    '        int rootVal = post[postR];',
    '        TreeNode root = new TreeNode(rootVal);',
    '        int inRoot = inMap.get(rootVal);',
    '        int leftLen = inRoot - inL;',
    '        root.left = build(post, postL, postL + leftLen - 1, inL, inRoot - 1);',
    '        root.right = build(post, postL + leftLen, postR - 1, inRoot + 1, inR);',
    '        return root;',
    '    }',
    '}',
  ],
  cpp: [
    'class Solution {',
    '    unordered_map<int, int> inMap;',
    'public:',
    '    TreeNode* buildTree(vector<int>& inorder, vector<int>& postorder) {',
    '        for (int i = 0; i < inorder.size(); i++) inMap[inorder[i]] = i;',
    '        return build(postorder, 0, postorder.size() - 1, 0, inorder.size() - 1);',
    '    }',
    '    TreeNode* build(vector<int>& post, int postL, int postR, int inL, int inR) {',
    '        if (postL > postR || inL > inR) return nullptr;',
    '        int rootVal = post[postR];',
    '        TreeNode* root = new TreeNode(rootVal);',
    '        int inRoot = inMap[rootVal];',
    '        int leftLen = inRoot - inL;',
    '        root->left = build(post, postL, postL + leftLen - 1, inL, inRoot - 1);',
    '        root->right = build(post, postL + leftLen, postR - 1, inRoot + 1, inR);',
    '        return root;',
    '    }',
    '};',
  ],
  python: [
    'class Solution:',
    '    def buildTree(self, inorder: list[int], postorder: list[int]) -> Optional[TreeNode]:',
    '        in_map = {val: idx for idx, val in enumerate(inorder)}',
    '        def build(postL: int, postR: int, inL: int, inR: int) -> Optional[TreeNode]:',
    '            if postL > postR or inL > inR: return None',
    '            root_val = postorder[postR]',
    '            root = TreeNode(root_val)',
    '            in_root = in_map[root_val]',
    '            left_len = in_root - inL',
    '            root.left = build(postL, postL + left_len - 1, inL, in_root - 1)',
    '            root.right = build(postL + left_len, postR - 1, in_root + 1, inR)',
    '            return root',
    '        return build(0, len(postorder) - 1, 0, len(inorder) - 1)',
  ],
  javascript: [
    'function buildTree(inorder, postorder) {',
    '    const inMap = new Map();',
    '    inorder.forEach((val, idx) => inMap.set(val, idx));',
    '    function build(postL, postR, inL, inR) {',
    '        if (postL > postR || inL > inR) return null;',
    '        const rootVal = postorder[postR];',
    '        const root = new TreeNode(rootVal);',
    '        const inRoot = inMap.get(rootVal);',
    '        const leftLen = inRoot - inL;',
    '        root.left = build(postL, postL + leftLen - 1, inL, inRoot - 1);',
    '        root.right = build(postL + leftLen, postR - 1, inRoot + 1, inR);',
    '        return root;',
    '    }',
    '    return build(0, postorder.length - 1, 0, inorder.length - 1);',
    '}',
  ],
};

export const BUILD_TREE_STAGE3_STACK_CODE: Record<string, string[]> = {
  java: [
    'class Solution {',
    '    public TreeNode buildTree(int[] preorder, int[] inorder) {',
    '        if (preorder.length == 0) return null;',
    '        TreeNode root = new TreeNode(preorder[0]);',
    '        Deque<TreeNode> stack = new ArrayDeque<>();',
    '        stack.push(root);',
    '        int inIdx = 0;',
    '        for (int i = 1; i < preorder.length; i++) {',
    '            int val = preorder[i];',
    '            TreeNode node = stack.peek();',
    '            if (node.val != inorder[inIdx]) {',
    '                node.left = new TreeNode(val);',
    '                stack.push(node.left);',
    '            } else {',
    '                while (!stack.isEmpty() && stack.peek().val == inorder[inIdx]) {',
    '                    node = stack.pop();',
    '                    inIdx++;',
    '                }',
    '                node.right = new TreeNode(val);',
    '                stack.push(node.right);',
    '            }',
    '        }',
    '        return root;',
    '    }',
    '}',
  ],
  cpp: [
    'class Solution {',
    'public:',
    '    TreeNode* buildTree(vector<int>& preorder, vector<int>& inorder) {',
    '        if (preorder.empty()) return nullptr;',
    '        TreeNode* root = new TreeNode(preorder[0]);',
    '        stack<TreeNode*> st;',
    '        st.push(root);',
    '        int inIdx = 0;',
    '        for (int i = 1; i < preorder.size(); i++) {',
    '            int val = preorder[i];',
    '            TreeNode* node = st.top();',
    '            if (node->val != inorder[inIdx]) {',
    '                node->left = new TreeNode(val);',
    '                st.push(node->left);',
    '            } else {',
    '                while (!st.empty() && st.top()->val == inorder[inIdx]) {',
    '                    node = st.top(); st.pop();',
    '                    inIdx++;',
    '                }',
    '                node->right = new TreeNode(val);',
    '                st.push(node->right);',
    '            }',
    '        }',
    '        return root;',
    '    }',
    '};',
  ],
  python: [
    'class Solution:',
    '    def buildTree(self, preorder: list[int], inorder: list[int]) -> Optional[TreeNode]:',
    '        if not preorder: return None',
    '        root = TreeNode(preorder[0])',
    '        stack = [root]',
    '        in_idx = 0',
    '        for i in range(1, len(preorder)):',
    '            val = preorder[i]',
    '            node = stack[-1]',
    '            if node.val != inorder[in_idx]:',
    '                node.left = TreeNode(val)',
    '                stack.append(node.left)',
    '            else:',
    '                while stack and stack[-1].val == inorder[in_idx]:',
    '                    node = stack.pop()',
    '                    in_idx += 1',
    '                node.right = TreeNode(val)',
    '                stack.append(node.right)',
    '        return root',
  ],
  javascript: [
    'function buildTree(preorder, inorder) {',
    '    if (!preorder.length) return null;',
    '    const root = new TreeNode(preorder[0]);',
    '    const stack = [root];',
    '    let inIdx = 0;',
    '    for (let i = 1; i < preorder.length; i++) {',
    '        const val = preorder[i];',
    '        let node = stack[stack.length - 1];',
    '        if (node.val !== inorder[inIdx]) {',
    '            node.left = new TreeNode(val);',
    '            stack.push(node.left);',
    '        } else {',
    '            while (stack.length && stack[stack.length - 1].val === inorder[inIdx]) {',
    '                node = stack.pop();',
    '                inIdx++;',
    '            }',
    '            node.right = new TreeNode(val);',
    '            stack.push(node.right);',
    '        }',
    '    }',
    '    return root;',
    '}',
  ],
};
