/**
 * LeetCode 404: 左叶子之和 (Sum of Left Leaves)
 * 四语言权威解法与精准 1-Based 代码行号映射
 */

// ----------------------------------------------------
// Stage 1: 后序递归分治与父节点识别左叶子 (Postorder Recursive DFS)
// ----------------------------------------------------
export const LEFT_LEAVES_STAGE1_CODES = {
  java: [
    'public class Solution {',
    '    public int sumOfLeftLeaves(TreeNode root) {',
    '        if (root == null) return 0;',
    '        int leftSum = 0;',
    '        if (root.left != null && root.left.left == null && root.left.right == null) {',
    '            leftSum = root.left.val;',
    '        } else {',
    '            leftSum = sumOfLeftLeaves(root.left);',
    '        }',
    '        int rightSum = sumOfLeftLeaves(root.right);',
    '        return leftSum + rightSum;',
    '    }',
    '}',
  ],
  cpp: [
    'class Solution {',
    'public:',
    '    int sumOfLeftLeaves(TreeNode* root) {',
    '        if (!root) return 0;',
    '        int leftSum = 0;',
    '        if (root->left && !root->left->left && !root->left->right) {',
    '            leftSum = root->left->val;',
    '        } else {',
    '            leftSum = sumOfLeftLeaves(root->left);',
    '        }',
    '        int rightSum = sumOfLeftLeaves(root->right);',
    '        return leftSum + rightSum;',
    '    }',
    '};',
  ],
  python: [
    'class Solution:',
    '    def sumOfLeftLeaves(self, root: Optional[TreeNode]) -> int:',
    '        if not root:',
    '            return 0',
    '        left_sum = 0',
    '        if root.left and not root.left.left and not root.left.right:',
    '            left_sum = root.left.val',
    '        else:',
    '            left_sum = self.sumOfLeftLeaves(root.left)',
    '        right_sum = self.sumOfLeftLeaves(root.right)',
    '        return left_sum + right_sum',
  ],
  javascript: [
    'function sumOfLeftLeaves(root) {',
    '    if (!root) return 0;',
    '    let leftSum = 0;',
    '    if (root.left && !root.left.left && !root.left.right) {',
    '        leftSum = root.left.val;',
    '    } else {',
    '        leftSum = sumOfLeftLeaves(root.left);',
    '    }',
    '    const rightSum = sumOfLeftLeaves(root.right);',
    '    return leftSum + rightSum;',
    '}',
  ],
};

export const LEFT_LEAVES_STAGE1_LINES = {
  entry: { java: 2, cpp: 3, python: 2, javascript: 1 },
  baseNull: { java: 3, cpp: 4, python: 3, javascript: 2 },
  isLeftLeaf: { java: 6, cpp: 7, python: 6, javascript: 4 },
  recurseLeft: { java: 8, cpp: 9, python: 8, javascript: 6 },
  recurseRight: { java: 10, cpp: 11, python: 9, javascript: 8 },
  returnSum: { java: 11, cpp: 12, python: 10, javascript: 9 },
};

// ----------------------------------------------------
// Stage 2: 广度优先搜索层序队列遍历 (BFS Queue Traversal)
// ----------------------------------------------------
export const LEFT_LEAVES_STAGE2_CODES = {
  java: [
    'public class Solution {',
    '    public int sumOfLeftLeaves(TreeNode root) {',
    '        if (root == null) return 0;',
    '        Queue<TreeNode> queue = new LinkedList<>();',
    '        queue.offer(root);',
    '        int sum = 0;',
    '        while (!queue.isEmpty()) {',
    '            TreeNode cur = queue.poll();',
    '            if (cur.left != null) {',
    '                if (cur.left.left == null && cur.left.right == null) {',
    '                    sum += cur.left.val;',
    '                } else {',
    '                    queue.offer(cur.left);',
    '                }',
    '            }',
    '            if (cur.right != null) {',
    '                queue.offer(cur.right);',
    '            }',
    '        }',
    '        return sum;',
    '    }',
    '}',
  ],
  cpp: [
    'class Solution {',
    'public:',
    '    int sumOfLeftLeaves(TreeNode* root) {',
    '        if (!root) return 0;',
    '        queue<TreeNode*> q;',
    '        q.push(root);',
    '        int sum = 0;',
    '        while (!q.empty()) {',
    '            auto cur = q.front(); q.pop();',
    '            if (cur->left) {',
    '                if (!cur->left->left && !cur->left->right) {',
    '                    sum += cur->left->val;',
    '                } else {',
    '                    q.push(cur->left);',
    '                }',
    '            }',
    '            if (cur->right) {',
    '                q.push(cur->right);',
    '            }',
    '        }',
    '        return sum;',
    '    }',
    '};',
  ],
  python: [
    'class Solution:',
    '    def sumOfLeftLeaves(self, root: Optional[TreeNode]) -> int:',
    '        if not root:',
    '            return 0',
    '        q = collections.deque([root])',
    '        total_sum = 0',
    '        while q:',
    '            cur = q.popleft()',
    '            if cur.left:',
    '                if not cur.left.left and not cur.left.right:',
    '                    total_sum += cur.left.val',
    '                else:',
    '                    q.append(cur.left)',
    '            if cur.right:',
    '                q.append(cur.right)',
    '        return total_sum',
  ],
  javascript: [
    'function sumOfLeftLeaves(root) {',
    '    if (!root) return 0;',
    '    const queue = [root];',
    '    let sum = 0;',
    '    while (queue.length > 0) {',
    '        const cur = queue.shift();',
    '        if (cur.left) {',
    '            if (!cur.left.left && !cur.left.right) {',
    '                sum += cur.left.val;',
    '            } else {',
    '                queue.push(cur.left);',
    '            }',
    '        }',
    '        if (cur.right) {',
    '            queue.push(cur.right);',
    '        }',
    '    }',
    '    return sum;',
    '}',
  ],
};

export const LEFT_LEAVES_STAGE2_LINES = {
  entry: { java: 2, cpp: 3, python: 2, javascript: 1 },
  baseNull: { java: 3, cpp: 4, python: 3, javascript: 2 },
  initQueue: { java: 4, cpp: 5, python: 5, javascript: 3 },
  whileLoop: { java: 7, cpp: 8, python: 7, javascript: 5 },
  pollNode: { java: 8, cpp: 9, python: 8, javascript: 6 },
  findLeftLeaf: { java: 11, cpp: 12, python: 11, javascript: 9 },
  pushLeft: { java: 13, cpp: 14, python: 13, javascript: 11 },
  pushRight: { java: 17, cpp: 18, python: 15, javascript: 15 },
  returnSum: { java: 20, cpp: 21, python: 16, javascript: 18 },
};

// ----------------------------------------------------
// Stage 3: 显式迭代栈遍历与左叶子累加 (Iterative Stack DFS)
// ----------------------------------------------------
export const LEFT_LEAVES_STAGE3_CODES = {
  java: [
    'public class Solution {',
    '    public int sumOfLeftLeaves(TreeNode root) {',
    '        if (root == null) return 0;',
    '        Deque<TreeNode> stack = new ArrayDeque<>();',
    '        stack.push(root);',
    '        int sum = 0;',
    '        while (!stack.isEmpty()) {',
    '            TreeNode cur = stack.pop();',
    '            if (cur.left != null && cur.left.left == null && cur.left.right == null) {',
    '                sum += cur.left.val;',
    '            }',
    '            if (cur.right != null) stack.push(cur.right);',
    '            if (cur.left != null) stack.push(cur.left);',
    '        }',
    '        return sum;',
    '    }',
    '}',
  ],
  cpp: [
    'class Solution {',
    'public:',
    '    int sumOfLeftLeaves(TreeNode* root) {',
    '        if (!root) return 0;',
    '        stack<TreeNode*> st;',
    '        st.push(root);',
    '        int sum = 0;',
    '        while (!st.empty()) {',
    '            auto cur = st.top(); st.pop();',
    '            if (cur->left && !cur->left->left && !cur->left->right) {',
    '                sum += cur->left->val;',
    '            }',
    '            if (cur->right) st.push(cur->right);',
    '            if (cur->left) st.push(cur->left);',
    '        }',
    '        return sum;',
    '    }',
    '};',
  ],
  python: [
    'class Solution:',
    '    def sumOfLeftLeaves(self, root: Optional[TreeNode]) -> int:',
    '        if not root:',
    '            return 0',
    '        stack = [root]',
    '        total_sum = 0',
    '        while stack:',
    '            cur = stack.pop()',
    '            if cur.left and not cur.left.left and not cur.left.right:',
    '                total_sum += cur.left.val',
    '            if cur.right:',
    '                stack.append(cur.right)',
    '            if cur.left:',
    '                stack.append(cur.left)',
    '        return total_sum',
  ],
  javascript: [
    'function sumOfLeftLeaves(root) {',
    '    if (!root) return 0;',
    '    const stack = [root];',
    '    let sum = 0;',
    '    while (stack.length > 0) {',
    '        const cur = stack.pop();',
    '        if (cur.left && !cur.left.left && !cur.left.right) {',
    '            sum += cur.left.val;',
    '        }',
    '        if (cur.right) stack.push(cur.right);',
    '        if (cur.left) stack.push(cur.left);',
    '    }',
    '    return sum;',
    '}',
  ],
};

export const LEFT_LEAVES_STAGE3_LINES = {
  entry: { java: 2, cpp: 3, python: 2, javascript: 1 },
  baseNull: { java: 3, cpp: 4, python: 3, javascript: 2 },
  initStack: { java: 4, cpp: 5, python: 5, javascript: 3 },
  whileLoop: { java: 7, cpp: 8, python: 7, javascript: 5 },
  popNode: { java: 8, cpp: 9, python: 8, javascript: 6 },
  checkLeftLeaf: { java: 10, cpp: 11, python: 10, javascript: 8 },
  pushRight: { java: 12, cpp: 13, python: 12, javascript: 10 },
  pushLeft: { java: 13, cpp: 14, python: 14, javascript: 11 },
  returnSum: { java: 15, cpp: 16, python: 15, javascript: 13 },
};
