/**
 * 二叉树最小深度多阶段演进代码模板 (LeetCode 111 / Zuoshen Class 036)
 *
 * Stage 1: 后序递归分治与叶节点特判 (Postorder Recursive DFS · LC 111 经典)
 * Stage 2: 广度优先搜索层序最短路提前终止 (BFS Level Order with Early Exit)
 * Stage 3: 静态数组模拟队列 (Static Array Queue BFS · Zuoshen Class 036)
 *
 * 覆盖 Java / C++ / Python / JavaScript 四语言
 */

export const MIN_DEPTH_STAGE1_CODES: Record<string, string[]> = {
  java: [
    'public class Solution {',
    '    public int minDepth(TreeNode root) {',
    '        if (root == null) return 0;',
    '        if (root.left == null && root.right == null) return 1;',
    '        if (root.left == null) return minDepth(root.right) + 1;',
    '        if (root.right == null) return minDepth(root.left) + 1;',
    '        return Math.min(minDepth(root.left), minDepth(root.right)) + 1;',
    '    }',
    '}',
  ],
  cpp: [
    'class Solution {',
    'public:',
    '    int minDepth(TreeNode* root) {',
    '        if (!root) return 0;',
    '        if (!root->left && !root->right) return 1;',
    '        if (!root->left) return minDepth(root->right) + 1;',
    '        if (!root->right) return minDepth(root->left) + 1;',
    '        return min(minDepth(root->left), minDepth(root->right)) + 1;',
    '    }',
    '};',
  ],
  python: [
    'class Solution:',
    '    def minDepth(self, root: Optional[TreeNode]) -> int:',
    '        if not root:',
    '            return 0',
    '        if not root.left and not root.right:',
    '            return 1',
    '        if not root.left:',
    '            return self.minDepth(root.right) + 1',
    '        if not root.right:',
    '            return self.minDepth(root.left) + 1',
    '        return min(self.minDepth(root.left), self.minDepth(root.right)) + 1',
  ],
  javascript: [
    'function minDepth(root) {',
    '    if (!root) return 0;',
    '    if (!root.left && !root.right) return 1;',
    '    if (!root.left) return minDepth(root.right) + 1;',
    '    if (!root.right) return minDepth(root.left) + 1;',
    '    return Math.min(minDepth(root.left), minDepth(root.right)) + 1;',
    '}',
  ],
};

export const MIN_DEPTH_STAGE2_CODES: Record<string, string[]> = {
  java: [
    'public class Solution {',
    '    public int minDepth(TreeNode root) {',
    '        if (root == null) return 0;',
    '        Queue<TreeNode> queue = new LinkedList<>();',
    '        queue.offer(root);',
    '        int depth = 1;',
    '        while (!queue.isEmpty()) {',
    '            int size = queue.size();',
    '            for (int i = 0; i < size; i++) {',
    '                TreeNode node = queue.poll();',
    '                if (node.left == null && node.right == null) {',
    '                    return depth;',
    '                }',
    '                if (node.left != null) queue.offer(node.left);',
    '                if (node.right != null) queue.offer(node.right);',
    '            }',
    '            depth++;',
    '        }',
    '        return depth;',
    '    }',
    '}',
  ],
  cpp: [
    'class Solution {',
    'public:',
    '    int minDepth(TreeNode* root) {',
    '        if (!root) return 0;',
    '        queue<TreeNode*> q;',
    '        q.push(root);',
    '        int depth = 1;',
    '        while (!q.empty()) {',
    '            int size = q.size();',
    '            for (int i = 0; i < size; i++) {',
    '                TreeNode* node = q.front(); q.pop();',
    '                if (!node->left && !node->right) {',
    '                    return depth;',
    '                }',
    '                if (node->left) q.push(node->left);',
    '                if (node->right) q.push(node->right);',
    '            }',
    '            depth++;',
    '        }',
    '        return depth;',
    '    }',
    '};',
  ],
  python: [
    'class Solution:',
    '    def minDepth(self, root: Optional[TreeNode]) -> int:',
    '        if not root:',
    '            return 0',
    '        queue = deque([root])',
    '        depth = 1',
    '        while queue:',
    '            for _ in range(len(queue)):',
    '                node = queue.popleft()',
    '                if not node.left and not node.right:',
    '                    return depth',
    '                if node.left:',
    '                    queue.append(node.left)',
    '                if node.right:',
    '                    queue.append(node.right)',
    '            depth += 1',
    '        return depth',
  ],
  javascript: [
    'function minDepth(root) {',
    '    if (!root) return 0;',
    '    const queue = [root];',
    '    let depth = 1;',
    '    while (queue.length > 0) {',
    '        const size = queue.length;',
    '        for (let i = 0; i < size; i++) {',
    '            const node = queue.shift();',
    '            if (!node.left && !node.right) {',
    '                return depth;',
    '            }',
    '            if (node.left) queue.push(node.left);',
    '            if (node.right) queue.push(node.right);',
    '        } ',
    '        depth++;',
    '    }',
    '    return depth;',
    '}',
  ],
};

export const MIN_DEPTH_STAGE3_CODES: Record<string, string[]> = {
  java: [
    'public class Solution {',
    '    public static int MAXN = 100001;',
    '    public static TreeNode[] queue = new TreeNode[MAXN];',
    '    public int minDepth(TreeNode root) {',
    '        if (root == null) return 0;',
    '        int l = 0, r = 0;',
    '        queue[r++] = root;',
    '        int depth = 1;',
    '        while (l < r) {',
    '            int size = r - l;',
    '            for (int i = 0; i < size; i++) {',
    '                TreeNode node = queue[l++];',
    '                if (node.left == null && node.right == null) {',
    '                    return depth;',
    '                }',
    '                if (node.left != null) queue[r++] = node.left;',
    '                if (node.right != null) queue[r++] = node.right;',
    '            }',
    '            depth++;',
    '        }',
    '        return depth;',
    '    }',
    '}',
  ],
  cpp: [
    'class Solution {',
    'public:',
    '    static const int MAXN = 100001;',
    '    TreeNode* queueArr[MAXN];',
    '    int minDepth(TreeNode* root) {',
    '        if (!root) return 0;',
    '        int l = 0, r = 0;',
    '        queueArr[r++] = root;',
    '        int depth = 1;',
    '        while (l < r) {',
    '            int size = r - l;',
    '            for (int i = 0; i < size; i++) {',
    '                TreeNode* node = queueArr[l++];',
    '                if (!node->left && !node->right) {',
    '                    return depth;',
    '                }',
    '                if (node->left) queueArr[r++] = node->left;',
    '                if (node->right) queueArr[r++] = node->right;',
    '            }',
    '            depth++;',
    '        }',
    '        return depth;',
    '    }',
    '};',
  ],
  python: [
    'class Solution:',
    '    def minDepth(self, root: Optional[TreeNode]) -> int:',
    '        if not root:',
    '            return 0',
    '        queue = [None] * 100005',
    '        l, r = 0, 0',
    '        queue[r] = root',
    '        r += 1',
    '        depth = 1',
    '        while l < r:',
    '            size = r - l',
    '            for _ in range(size):',
    '                node = queue[l]',
    '                l += 1',
    '                if not node.left and not node.right:',
    '                    return depth',
    '                if node.left:',
    '                    queue[r] = node.left',
    '                    r += 1',
    '                if node.right:',
    '                    queue[r] = node.right',
    '                    r += 1',
    '            depth += 1',
    '        return depth',
  ],
  javascript: [
    'function minDepth(root) {',
    '    if (!root) return 0;',
    '    const queue = new Array(100005);',
    '    let l = 0, r = 0;',
    '    queue[r++] = root;',
    '    let depth = 1;',
    '    while (l < r) {',
    '        const size = r - l;',
    '        for (let i = 0; i < size; i++) {',
    '            const node = queue[l++];',
    '            if (!node.left && !node.right) {',
    '                return depth;',
    '            }',
    '            if (node.left) queue[r++] = node.left;',
    '            if (node.right) queue[r++] = node.right;',
    '        }',
    '        depth++;',
    '    }',
    '    return depth;',
    '}',
  ],
};
