/**
 * 求根节点到叶节点数字之和多阶段演进代码模板 (LeetCode 129 · Sum Root to Leaf Numbers)
 *
 * Stage 1: 前序遍历与路径数值自顶向下累加递归 (Preorder DFS with Top-Down Passing)
 * Stage 2: 广度优先搜索双队列同步 (BFS with Dual Queues: Node Queue + Value Queue)
 * Stage 3: 显式迭代双栈与回溯模拟 (Iterative Explicit Dual Stacks DFS)
 *
 * 覆盖 Java / C++ / Python / JavaScript 四语言
 */

export const SUM_NUMBERS_STAGE1_CODES: Record<string, string[]> = {
  java: [
    'public class Solution {',
    '    public int sumNumbers(TreeNode root) {',
    '        if (root == null) return 0;',
    '        return dfs(root, 0);',
    '    }',
    '    private int dfs(TreeNode node, int prevSum) {',
    '        if (node == null) return 0;',
    '        int currSum = prevSum * 10 + node.val;',
    '        if (node.left == null && node.right == null) {',
    '            return currSum;',
    '        }',
    '        int leftSum = dfs(node.left, currSum);',
    '        int rightSum = dfs(node.right, currSum);',
    '        return leftSum + rightSum;',
    '    }',
    '}',
  ],
  cpp: [
    'class Solution {',
    'public:',
    '    int sumNumbers(TreeNode* root) {',
    '        if (!root) return 0;',
    '        return dfs(root, 0);',
    '    }',
    '    int dfs(TreeNode* node, int prevSum) {',
    '        if (!node) return 0;',
    '        int currSum = prevSum * 10 + node->val;',
    '        if (!node->left && !node->right) {',
    '            return currSum;',
    '        }',
    '        int leftSum = dfs(node->left, currSum);',
    '        int rightSum = dfs(node->right, currSum);',
    '        return leftSum + rightSum;',
    '    }',
    '};',
  ],
  python: [
    'class Solution:',
    '    def sumNumbers(self, root: Optional[TreeNode]) -> int:',
    '        if not root: return 0',
    '        def dfs(node, prev_sum):',
    '            if not node: return 0',
    '            curr_sum = prev_sum * 10 + node.val',
    '            if not node.left and not node.right:',
    '                return curr_sum',
    '            left_sum = dfs(node.left, curr_sum)',
    '            right_sum = dfs(node.right, curr_sum)',
    '            return left_sum + right_sum',
    '        return dfs(root, 0)',
  ],
  javascript: [
    'function sumNumbers(root) {',
    '    if (!root) return 0;',
    '    function dfs(node, prevSum) {',
    '        if (!node) return 0;',
    '        const currSum = prevSum * 10 + node.val;',
    '        if (!node.left && !node.right) {',
    '            return currSum;',
    '        }',
    '        const leftSum = dfs(node.left, currSum);',
    '        const rightSum = dfs(node.right, currSum);',
    '        return leftSum + rightSum;',
    '    }',
    '    return dfs(root, 0);',
    '}',
  ],
};

export const SUM_NUMBERS_STAGE2_CODES: Record<string, string[]> = {
  java: [
    'public class Solution {',
    '    public int sumNumbers(TreeNode root) {',
    '        if (root == null) return 0;',
    '        int totalSum = 0;',
    '        Queue<TreeNode> nodeQueue = new LinkedList<>();',
    '        Queue<Integer> numQueue = new LinkedList<>();',
    '        nodeQueue.offer(root);',
    '        numQueue.offer(root.val);',
    '        while (!nodeQueue.isEmpty()) {',
    '            TreeNode node = nodeQueue.poll();',
    '            int num = numQueue.poll();',
    '            if (node.left == null && node.right == null) {',
    '                totalSum += num;',
    '            } else {',
    '                if (node.left != null) {',
    '                    nodeQueue.offer(node.left);',
    '                    numQueue.offer(num * 10 + node.left.val);',
    '                }',
    '                if (node.right != null) {',
    '                    nodeQueue.offer(node.right);',
    '                    numQueue.offer(num * 10 + node.right.val);',
    '                }',
    '            }',
    '        }',
    '        return totalSum;',
    '    }',
    '}',
  ],
  cpp: [
    'class Solution {',
    'public:',
    '    int sumNumbers(TreeNode* root) {',
    '        if (!root) return 0;',
    '        int totalSum = 0;',
    '        queue<TreeNode*> nodeQueue;',
    '        queue<int> numQueue;',
    '        nodeQueue.push(root);',
    '        numQueue.push(root->val);',
    '        while (!nodeQueue.empty()) {',
    '            TreeNode* node = nodeQueue.front(); nodeQueue.pop();',
    '            int num = numQueue.front(); numQueue.pop();',
    '            if (!node->left && !node->right) {',
    '                totalSum += num;',
    '            } else {',
    '                if (node->left) {',
    '                    nodeQueue.push(node->left);',
    '                    numQueue.push(num * 10 + node->left->val);',
    '                }',
    '                if (node->right) {',
    '                    nodeQueue.push(node->right);',
    '                    numQueue.push(num * 10 + node->right->val);',
    '                }',
    '            }',
    '        }',
    '        return totalSum;',
    '    }',
    '};',
  ],
  python: [
    'class Solution:',
    '    def sumNumbers(self, root: Optional[TreeNode]) -> int:',
    '        if not root:',
    '            return 0',
    '        total_sum = 0',
    '        node_queue = deque([root])',
    '        num_queue = deque([root.val])',
    '        while node_queue:',
    '            node = node_queue.popleft()',
    '            num = num_queue.popleft()',
    '            if not node.left and not node.right:',
    '                total_sum += num',
    '            else:',
    '                if node.left:',
    '                    node_queue.append(node.left)',
    '                    num_queue.append(num * 10 + node.left.val)',
    '                if node.right:',
    '                    node_queue.append(node.right)',
    '                    num_queue.append(num * 10 + node.right.val)',
    '        return total_sum',
  ],
  javascript: [
    'function sumNumbers(root) {',
    '    if (!root) return 0;',
    '    let totalSum = 0;',
    '    const nodeQueue = [root];',
    '    const numQueue = [root.val];',
    '    while (nodeQueue.length > 0) {',
    '        const node = nodeQueue.shift();',
    '        const num = numQueue.shift();',
    '        if (!node.left && !node.right) {',
    '            totalSum += num;',
    '        } else {',
    '            if (node.left) {',
    '                nodeQueue.push(node.left);',
    '                numQueue.push(num * 10 + node.left.val);',
    '            }',
    '            if (node.right) {',
    '                nodeQueue.push(node.right);',
    '                numQueue.push(num * 10 + node.right.val);',
    '            }',
    '        }',
    '    }',
    '    return totalSum;',
    '}',
  ],
};

export const SUM_NUMBERS_STAGE3_CODES: Record<string, string[]> = {
  java: [
    'public class Solution {',
    '    public int sumNumbers(TreeNode root) {',
    '        if (root == null) return 0;',
    '        int totalSum = 0;',
    '        Deque<TreeNode> nodeStack = new ArrayDeque<>();',
    '        Deque<Integer> numStack = new ArrayDeque<>();',
    '        nodeStack.push(root);',
    '        numStack.push(root.val);',
    '        while (!nodeStack.isEmpty()) {',
    '            TreeNode node = nodeStack.pop();',
    '            int curr = numStack.pop();',
    '            if (node.left == null && node.right == null) {',
    '                totalSum += curr;',
    '            }',
    '            if (node.right != null) {',
    '                nodeStack.push(node.right);',
    '                numStack.push(curr * 10 + node.right.val);',
    '            }',
    '            if (node.left != null) {',
    '                nodeStack.push(node.left);',
    '                numStack.push(curr * 10 + node.left.val);',
    '            }',
    '        }',
    '        return totalSum;',
    '    }',
    '}',
  ],
  cpp: [
    'class Solution {',
    'public:',
    '    int sumNumbers(TreeNode* root) {',
    '        if (!root) return 0;',
    '        int totalSum = 0;',
    '        stack<TreeNode*> nodeStack;',
    '        stack<int> numStack;',
    '        nodeStack.push(root);',
    '        numStack.push(root->val);',
    '        while (!nodeStack.empty()) {',
    '            TreeNode* node = nodeStack.top(); nodeStack.pop();',
    '            int curr = numStack.top(); numStack.pop();',
    '            if (!node->left && !node->right) {',
    '                totalSum += curr;',
    '            }',
    '            if (node->right) {',
    '                nodeStack.push(node->right);',
    '                numStack.push(curr * 10 + node->right->val);',
    '            }',
    '            if (node->left) {',
    '                nodeStack.push(node->left);',
    '                numStack.push(curr * 10 + node->left->val);',
    '            }',
    '        }',
    '        return totalSum;',
    '    }',
    '};',
  ],
  python: [
    'class Solution:',
    '    def sumNumbers(self, root: Optional[TreeNode]) -> int:',
    '        if not root:',
    '            return 0',
    '        total_sum = 0',
    '        node_stack = [root]',
    '        num_stack = [root.val]',
    '        while node_stack:',
    '            node = node_stack.pop()',
    '            curr = num_stack.pop()',
    '            if not node.left and not node.right:',
    '                total_sum += curr',
    '            if node.right:',
    '                node_stack.append(node.right)',
    '                num_stack.append(curr * 10 + node.right.val)',
    '            if node.left:',
    '                node_stack.append(node.left)',
    '                num_stack.append(curr * 10 + node.left.val)',
    '        return total_sum',
  ],
  javascript: [
    'function sumNumbers(root) {',
    '    if (!root) return 0;',
    '    let totalSum = 0;',
    '    const nodeStack = [root];',
    '    const numStack = [root.val];',
    '    while (nodeStack.length > 0) {',
    '        const node = nodeStack.pop();',
    '        const curr = numStack.pop();',
    '        if (!node.left && !node.right) {',
    '            totalSum += curr;',
    '        }',
    '        if (node.right) {',
    '            nodeStack.push(node.right);',
    '            numStack.push(curr * 10 + node.right.val);',
    '        }',
    '        if (node.left) {',
    '            nodeStack.push(node.left);',
    '            numStack.push(curr * 10 + node.left.val);',
    '        }',
    '    }',
    '    return totalSum;',
    '}',
  ],
};

export const SUM_NUMBERS_STAGE1_LINES = {
  entry: { java: 2, cpp: 3, python: 2, javascript: 1 },
  baseNull: { java: 3, cpp: 4, python: 3, javascript: 2 },
  callDfsRoot: { java: 4, cpp: 5, python: 12, javascript: 13 },
  dfsEntry: { java: 6, cpp: 7, python: 4, javascript: 3 },
  dfsNullCheck: { java: 7, cpp: 8, python: 5, javascript: 4 },
  calcSum: { java: 8, cpp: 9, python: 6, javascript: 5 },
  leafCheck: { java: 9, cpp: 10, python: 7, javascript: 6 },
  leafReturn: { java: 10, cpp: 11, python: 8, javascript: 7 },
  callLeft: { java: 12, cpp: 13, python: 9, javascript: 9 },
  callRight: { java: 13, cpp: 14, python: 10, javascript: 10 },
  returnSum: { java: 14, cpp: 15, python: 11, javascript: 11 },
  recurseChildren: { java: 14, cpp: 15, python: 11, javascript: 11 },
  done: { java: 4, cpp: 5, python: 12, javascript: 13 },
};

export const SUM_NUMBERS_STAGE2_LINES = {
  entry: { java: 2, cpp: 3, python: 2, javascript: 1 },
  init: { java: 5, cpp: 6, python: 6, javascript: 4 },
  whileLoop: { java: 9, cpp: 10, python: 8, javascript: 6 },
  pollNode: { java: 10, cpp: 11, python: 9, javascript: 7 },
  leafCheck: { java: 12, cpp: 13, python: 11, javascript: 9 },
  leafAdd: { java: 13, cpp: 14, python: 12, javascript: 10 },
  pushLeft: { java: 16, cpp: 17, python: 15, javascript: 13 },
  pushRight: { java: 20, cpp: 21, python: 18, javascript: 17 },
  done: { java: 25, cpp: 26, python: 20, javascript: 22 },
};

export const SUM_NUMBERS_STAGE3_LINES = {
  entry: { java: 2, cpp: 3, python: 2, javascript: 1 },
  init: { java: 5, cpp: 6, python: 6, javascript: 4 },
  whileLoop: { java: 9, cpp: 10, python: 8, javascript: 6 },
  popNode: { java: 10, cpp: 11, python: 9, javascript: 7 },
  leafCheck: { java: 12, cpp: 13, python: 11, javascript: 9 },
  leafAdd: { java: 13, cpp: 14, python: 12, javascript: 10 },
  pushRight: { java: 16, cpp: 17, python: 14, javascript: 13 },
  pushLeft: { java: 20, cpp: 21, python: 17, javascript: 17 },
  done: { java: 24, cpp: 25, python: 19, javascript: 21 },
};

