/**
 * 左程云《算法通关课》Class 107: 01-Trie 字典树四语言精准代码联动
 * 包含 Stage 1 (经典动态节点版), Stage 2 (竞赛静态连续数组版), Stage 3 (前缀异或子数组版)
 */

// ==========================================
// Stage 1: 经典动态节点版 01-Trie (LC 421)
// ==========================================
export const TRIE_XOR_STAGE1_CODES: Record<string, string[]> = {
  java: [
    'public class Solution {',
    '    static class Node {',
    '        Node[] next = new Node[2];',
    '    }',
    '    private Node root = new Node();',
    '',
    '    public void insert(int num) {',
    '        Node cur = root;',
    '        for (int i = 30; i >= 0; i--) {',
    '            int b = (num >> i) & 1;',
    '            if (cur.next[b] == null) {',
    '                cur.next[b] = new Node();',
    '            }',
    '            cur = cur.next[b];',
    '        }',
    '    }',
    '',
    '    public int query(int num) {',
    '        Node cur = root;',
    '        int ans = 0;',
    '        for (int i = 30; i >= 0; i--) {',
    '            int b = (num >> i) & 1;',
    '            int want = b ^ 1;',
    '            if (cur.next[want] != null) {',
    '                ans |= (1 << i);',
    '                cur = cur.next[want];',
    '            } else {',
    '                cur = cur.next[b];',
    '            }',
    '        }',
    '        return ans;',
    '    }',
    '',
    '    public int findMaximumXOR(int[] nums) {',
    '        for (int num : nums) insert(num);',
    '        int max = 0;',
    '        for (int num : nums) {',
    '            max = Math.max(max, query(num));',
    '        }',
    '        return max;',
    '    }',
    '}',
  ],
  cpp: [
    'class Solution {',
    '    struct Node {',
    '        Node* next[2] = {nullptr, nullptr};',
    '    };',
    '    Node* root = new Node();',
    'public:',
    '    void insert(int num) {',
    '        Node* cur = root;',
    '        for (int i = 30; i >= 0; i--) {',
    '            int b = (num >> i) & 1;',
    '            if (!cur->next[b]) cur->next[b] = new Node();',
    '            cur = cur->next[b];',
    '        }',
    '    }',
    '    int query(int num) {',
    '        Node* cur = root;',
    '        int ans = 0;',
    '        for (int i = 30; i >= 0; i--) {',
    '            int b = (num >> i) & 1;',
    '            int want = b ^ 1;',
    '            if (cur->next[want]) {',
    '                ans |= (1 << i);',
    '                cur = cur->next[want];',
    '            } else {',
    '                cur = cur->next[b];',
    '            }',
    '        }',
    '        return ans;',
    '    }',
    '    int findMaximumXOR(vector<int>& nums) {',
    '        for (int x : nums) insert(x);',
    '        int maxVal = 0;',
    '        for (int x : nums) maxVal = max(maxVal, query(x));',
    '        return maxVal;',
    '    }',
    '};',
  ],
  python: [
    'class Solution:',
    '    def findMaximumXOR(self, nums: List[int]) -> int:',
    '        root = {}',
    '        def insert(num: int):',
    '            cur = root',
    '            for i in range(30, -1, -1):',
    '                b = (num >> i) & 1',
    '                if b not in cur:',
    '                    cur[b] = {}',
    '                cur = cur[b]',
    '',
    '        def query(num: int) -> int:',
    '            cur = root',
    '            ans = 0',
    '            for i in range(30, -1, -1):',
    '                b = (num >> i) & 1',
    '                want = b ^ 1',
    '                if want in cur:',
    '                    ans |= (1 << i)',
    '                    cur = cur[want]',
    '                else:',
    '                    cur = cur[b]',
    '            return ans',
    '',
    '        for x in nums: insert(x)',
    '        max_val = 0',
    '        for x in nums:',
    '            max_val = max(max_val, query(x))',
    '        return max_val',
  ],
  javascript: [
    'var findMaximumXOR = function(nums) {',
    '    const root = {};',
    '    function insert(num) {',
    '        let cur = root;',
    '        for (let i = 30; i >= 0; i--) {',
    '            const b = (num >> i) & 1;',
    '            if (!cur[b]) cur[b] = {};',
    '            cur = cur[b];',
    '        }',
    '    }',
    '    function query(num) {',
    '        let cur = root, ans = 0;',
    '        for (let i = 30; i >= 0; i--) {',
    '            const b = (num >> i) & 1;',
    '            const want = b ^ 1;',
    '            if (cur[want]) {',
    '                ans |= (1 << i);',
    '                cur = cur[want];',
    '            } else {',
    '                cur = cur[b];',
    '            }',
    '        }',
    '        return ans;',
    '    }',
    '    for (const x of nums) insert(x);',
    '    let maxVal = 0;',
    '    for (const x of nums) {',
    '        maxVal = Math.max(maxVal, query(x));',
    '    }',
    '    return maxVal;',
    '};',
  ],
};

// ==========================================
// Stage 2: 竞赛静态连续数组版 01-Trie
// ==========================================
export const TRIE_XOR_STAGE2_CODES: Record<string, string[]> = {
  java: [
    'public class Solution {',
    '    // 竞赛极速静态数组：tree[cnt][0/1] 记录子节点行号',
    '    static int[][] tree = new int[3000005][2];',
    '    static int cnt = 1;',
    '',
    '    public static void insert(int num) {',
    '        int cur = 1;',
    '        for (int i = 30; i >= 0; i--) {',
    '            int b = (num >> i) & 1;',
    '            if (tree[cur][b] == 0) {',
    '                tree[cur][b] = ++cnt;',
    '            }',
    '            cur = tree[cur][b];',
    '        }',
    '    }',
    '',
    '    public static int query(int num) {',
    '        int cur = 1, ans = 0;',
    '        for (int i = 30; i >= 0; i--) {',
    '            int b = (num >> i) & 1;',
    '            int want = b ^ 1;',
    '            if (tree[cur][want] != 0) {',
    '                ans |= (1 << i);',
    '                cur = tree[cur][want];',
    '            } else {',
    '                cur = tree[cur][b];',
    '            }',
    '        }',
    '        return ans;',
    '    }',
    '',
    '    public int findMaximumXOR(int[] nums) {',
    '        cnt = 1; // 重置静态计数器',
    '        for (int x : nums) insert(x);',
    '        int maxVal = 0;',
    '        for (int x : nums) maxVal = Math.max(maxVal, query(x));',
    '        return maxVal;',
    '    }',
    '}',
  ],
  cpp: [
    'class Solution {',
    '    int tree[3000005][2];',
    '    int cnt = 1;',
    'public:',
    '    void insert(int num) {',
    '        int cur = 1;',
    '        for (int i = 30; i >= 0; i--) {',
    '            int b = (num >> i) & 1;',
    '            if (!tree[cur][b]) tree[cur][b] = ++cnt;',
    '            cur = tree[cur][b];',
    '        }',
    '    }',
    '    int query(int num) {',
    '        int cur = 1, ans = 0;',
    '        for (int i = 30; i >= 0; i--) {',
    '            int b = (num >> i) & 1;',
    '            int want = b ^ 1;',
    '            if (tree[cur][want]) {',
    '                ans |= (1 << i);',
    '                cur = tree[cur][want];',
    '            } else {',
    '                cur = tree[cur][b];',
    '            }',
    '        }',
    '        return ans;',
    '    }',
    '    int findMaximumXOR(vector<int>& nums) {',
    '        cnt = 1;',
    '        for (int x : nums) insert(x);',
    '        int maxVal = 0;',
    '        for (int x : nums) maxVal = max(maxVal, query(x));',
    '        return maxVal;',
    '    }',
    '};',
  ],
  python: [
    'class Solution:',
    '    def findMaximumXOR(self, nums: List[int]) -> int:',
    '        tree = [[0, 0] for _ in range(300005)]',
    '        cnt = 1',
    '        def insert(num: int):',
    '            nonlocal cnt',
    '            cur = 1',
    '            for i in range(30, -1, -1):',
    '                b = (num >> i) & 1',
    '                if tree[cur][b] == 0:',
    '                    cnt += 1',
    '                    tree[cur][b] = cnt',
    '                cur = tree[cur][b]',
    '        def query(num: int) -> int:',
    '            cur = 1; ans = 0',
    '            for i in range(30, -1, -1):',
    '                b = (num >> i) & 1',
    '                want = b ^ 1',
    '                if tree[cur][want] != 0:',
    '                    ans |= (1 << i)',
    '                    cur = tree[cur][want]',
    '                else:',
    '                    cur = tree[cur][b]',
    '            return ans',
    '        for x in nums: insert(x)',
    '        return max(query(x) for x in nums)',
  ],
  javascript: [
    'var findMaximumXOR = function(nums) {',
    '    const tree = Array.from({ length: 300005 }, () => [0, 0]);',
    '    let cnt = 1;',
    '    function insert(num) {',
    '        let cur = 1;',
    '        for (let i = 30; i >= 0; i--) {',
    '            const b = (num >> i) & 1;',
    '            if (tree[cur][b] === 0) tree[cur][b] = ++cnt;',
    '            cur = tree[cur][b];',
    '        }',
    '    }',
    '    function query(num) {',
    '        let cur = 1, ans = 0;',
    '        for (let i = 30; i >= 0; i--) {',
    '            const b = (num >> i) & 1;',
    '            const want = b ^ 1;',
    '            if (tree[cur][want] !== 0) {',
    '                ans |= (1 << i);',
    '                cur = tree[cur][want];',
    '            } else {',
    '                cur = tree[cur][b];',
    '            }',
    '        }',
    '        return ans;',
    '    }',
    '    for (const x of nums) insert(x);',
    '    let maxVal = 0;',
    '    for (const x of nums) maxVal = Math.max(maxVal, query(x));',
    '    return maxVal;',
    '};',
  ],
};

// ==========================================
// Stage 3: 子数组最大异或和 (前缀异或转化)
// ==========================================
export const TRIE_XOR_STAGE3_CODES: Record<string, string[]> = {
  java: [
    'public class Solution {',
    '    // 利用 eor[j..i] = eor[0..i] ^ eor[0..j-1]',
    '    public int maxXorSubarray(int[] nums) {',
    '        int maxVal = Integer.MIN_VALUE;',
    '        int eor = 0;',
    '        insert(0); // 关键基底：前缀为空时异或值为 0',
    '        for (int num : nums) {',
    '            eor ^= num;',
    '            int best = query(eor);',
    '            maxVal = Math.max(maxVal, eor ^ best);',
    '            insert(eor);',
    '        }',
    '        return maxVal;',
    '    }',
    '}',
  ],
  cpp: [
    'class Solution {',
    'public:',
    '    int maxXorSubarray(vector<int>& nums) {',
    '        int maxVal = INT_MIN;',
    '        int eor = 0;',
    '        insert(0); // 哨兵前缀',
    '        for (int x : nums) {',
    '            eor ^= x;',
    '            int best = query(eor);',
    '            maxVal = max(maxVal, eor ^ best);',
    '            insert(eor);',
    '        }',
    '        return maxVal;',
    '    }',
    '};',
  ],
  python: [
    'class Solution:',
    '    def maxXorSubarray(self, nums: List[int]) -> int:',
    '        max_val = float("-inf")',
    '        eor = 0',
    '        insert(0) # 哨兵前缀',
    '        for x in nums:',
    '            eor ^= x',
    '            best = query(eor)',
    '            max_val = max(max_val, eor ^ best)',
    '            insert(eor)',
    '        return max_val',
  ],
  javascript: [
    'var maxXorSubarray = function(nums) {',
    '    let maxVal = -Infinity;',
    '    let eor = 0;',
    '    insert(0); // 哨兵前缀',
    '    for (const x of nums) {',
    '        eor ^= x;',
    '        const best = query(eor);',
    '        maxVal = Math.max(maxVal, eor ^ best);',
    '        insert(eor);',
    '    }',
    '    return maxVal;',
    '};',
  ],
};
