/**
 * 第 93 课：左神贪心算法专题 5 - 多语言代码片段与 1-based 相对行号映射
 */

// ==========================================
// 1. 跳跃游戏 II (LeetCode 45)
// ==========================================
export const JUMP_GAME_II_CODES: Record<string, string[]> = {
  java: [
    'public int jump(int[] nums) {',
    '    int curEnd = 0, nextReach = 0, steps = 0;',
    '    for (int i = 0; i < nums.length - 1; i++) {',
    '        nextReach = Math.max(nextReach, i + nums[i]);',
    '        if (i == curEnd) {',
    '            curEnd = nextReach;',
    '            steps++;',
    '        }',
    '    }',
    '    return steps;',
    '}',
  ],
  cpp: [
    'int jump(vector<int>& nums) {',
    '    int curEnd = 0, nextReach = 0, steps = 0;',
    '    for (int i = 0; i < (int)nums.size() - 1; i++) {',
    '        nextReach = max(nextReach, i + nums[i]);',
    '        if (i == curEnd) {',
    '            curEnd = nextReach;',
    '            steps++;',
    '        }',
    '    }',
    '    return steps;',
    '}',
  ],
  python: [
    'def jump(nums: List[int]) -> int:',
    '    cur_end, next_reach, steps = 0, 0, 0',
    '    for i in range(len(nums) - 1):',
    '        next_reach = max(next_reach, i + nums[i])',
    '        if i == cur_end:',
    '            cur_end = next_reach',
    '            steps += 1',
    '    return steps',
  ],
  javascript: [
    'function jump(nums) {',
    '    let curEnd = 0, nextReach = 0, steps = 0;',
    '    for (let i = 0; i < nums.length - 1; i++) {',
    '        nextReach = Math.max(nextReach, i + nums[i]);',
    '        if (i === curEnd) {',
    '            curEnd = nextReach;',
    '            steps++;',
    '        }',
    '    }',
    '    return steps;',
    '}',
  ],
};

export const JUMP_GAME_II_LINES = {
  entry:     { java: 1, cpp: 1, python: 1, javascript: 1 },
  explore:   { java: 4, cpp: 4, python: 4, javascript: 4 },
  jumpStep:  { java: 7, cpp: 7, python: 7, javascript: 7 },
  done:      { java: 10, cpp: 10, python: 8, javascript: 10 },
};

// ==========================================
// 2. 灌溉花园的最少水龙头数目 (LeetCode 1326)
// ==========================================
export const MIN_TAPS_CODES: Record<string, string[]> = {
  java: [
    'public int minTaps(int n, int[] ranges) {',
    '    int[] rightReach = new int[n + 1];',
    '    for (int i = 0; i <= n; i++) {',
    '        int l = Math.max(0, i - ranges[i]);',
    '        rightReach[l] = Math.max(rightReach[l], Math.min(n, i + ranges[i]));',
    '    }',
    '    int curEnd = 0, nextReach = 0, steps = 0;',
    '    for (int i = 0; i < n; i++) {',
    '        nextReach = Math.max(nextReach, rightReach[i]);',
    '        if (i == curEnd) {',
    '            if (nextReach <= i) return -1;',
    '            curEnd = nextReach;',
    '            steps++;',
    '        }',
    '    }',
    '    return steps;',
    '}',
  ],
  cpp: [
    'int minTaps(int n, vector<int>& ranges) {',
    '    vector<int> rightReach(n + 1, 0);',
    '    for (int i = 0; i <= n; i++) {',
    '        int l = max(0, i - ranges[i]);',
    '        rightReach[l] = max(rightReach[l], min(n, i + ranges[i]));',
    '    }',
    '    int curEnd = 0, nextReach = 0, steps = 0;',
    '    for (int i = 0; i < n; i++) {',
    '        nextReach = max(nextReach, rightReach[i]);',
    '        if (i == curEnd) {',
    '            if (nextReach <= i) return -1;',
    '            curEnd = nextReach;',
    '            steps++;',
    '        }',
    '    }',
    '    return steps;',
    '}',
  ],
  python: [
    'def minTaps(n: int, ranges: List[int]) -> int:',
    '    right_reach = [0] * (n + 1)',
    '    for i, r in enumerate(ranges):',
    '        l = max(0, i - r)',
    '        right_reach[l] = max(right_reach[l], min(n, i + r))',
    '    cur_end, next_reach, steps = 0, 0, 0',
    '    for i in range(n):',
    '        next_reach = max(next_reach, right_reach[i])',
    '        if i == cur_end:',
    '            if next_reach <= i: return -1',
    '            cur_end = next_reach',
    '            steps += 1',
    '    return steps',
  ],
  javascript: [
    'function minTaps(n, ranges) {',
    '    const rightReach = new Array(n + 1).fill(0);',
    '    for (let i = 0; i <= n; i++) {',
    '        const l = Math.max(0, i - ranges[i]);',
    '        rightReach[l] = Math.max(rightReach[l], Math.min(n, i + ranges[i]));',
    '    }',
    '    let curEnd = 0, nextReach = 0, steps = 0;',
    '    for (let i = 0; i < n; i++) {',
    '        nextReach = Math.max(nextReach, rightReach[i]);',
    '        if (i === curEnd) {',
    '            if (nextReach <= i) return -1;',
    '            curEnd = nextReach;',
    '            steps++;',
    '        }',
    '    }',
    '    return steps;',
    '}',
  ],
};

export const MIN_TAPS_LINES = {
  entry:     { java: 1, cpp: 1, python: 1, javascript: 1 },
  buildRange:{ java: 5, cpp: 5, python: 5, javascript: 5 },
  extendReach:{ java: 9, cpp: 9, python: 8, javascript: 9 },
  jumpTap:   { java: 13, cpp: 13, python: 12, javascript: 13 },
  done:      { java: 16, cpp: 16, python: 13, javascript: 16 },
};

// ==========================================
// 3. 转化字符串的最少操作次数 (LeetCode 1153)
// ==========================================
export const STRING_TRANSFORMS_CODES: Record<string, string[]> = {
  java: [
    'public boolean canConvert(String str1, String str2) {',
    '    if (str1.equals(str2)) return true;',
    '    int[] map = new int[26];',
    '    Arrays.fill(map, -1);',
    '    Set<Character> set2 = new HashSet<>();',
    '    for (int i = 0; i < str1.length(); i++) {',
    '        int from = str1.charAt(i) - "a", to = str2.charAt(i) - "a";',
    '        if (map[from] != -1 && map[from] != to) return false;',
    '        map[from] = to;',
    '        set2.add(str2.charAt(i));',
    '    }',
    '    return set2.size() < 26;',
    '}',
  ],
  cpp: [
    'bool canConvert(string str1, string str2) {',
    '    if (str1 == str2) return true;',
    '    vector<int> map(26, -1);',
    '    unordered_set<char> set2;',
    '    for (int i = 0; i < (int)str1.size(); i++) {',
    '        int from = str1[i] - "a", to = str2[i] - "a";',
    '        if (map[from] != -1 && map[from] != to) return false;',
    '        map[from] = to;',
    '        set2.insert(str2[i]);',
    '    }',
    '    return set2.size() < 26;',
    '}',
  ],
  python: [
    'def canConvert(str1: str, str2: str) -> bool:',
    '    if str1 == str2: return True',
    '    char_map = {}',
    '    for a, b in zip(str1, str2):',
    '        if a in char_map and char_map[a] != b: return False',
    '        char_map[a] = b',
    '    return len(set(str2)) < 26',
  ],
  javascript: [
    'function canConvert(str1, str2) {',
    '    if (str1 === str2) return true;',
    '    const map = new Map();',
    '    for (let i = 0; i < str1.length; i++) {',
    '        const a = str1[i], b = str2[i];',
    '        if (map.has(a) && map.get(a) !== b) return false;',
    '        map.set(a, b);',
    '    }',
    '    return new Set(str2).size < 26;',
    '}',
  ],
};

export const STRING_TRANSFORMS_LINES = {
  entry:     { java: 1, cpp: 1, python: 1, javascript: 1 },
  equalGuard:{ java: 2, cpp: 2, python: 2, javascript: 2 },
  checkMap:  { java: 8, cpp: 7, python: 5, javascript: 6 },
  checkCycle:{ java: 12, cpp: 11, python: 7, javascript: 8 },
};

// ==========================================
// 4. 经典过河问题 (POJ 1700)
// ==========================================
export const CROSS_RIVER_CODES: Record<string, string[]> = {
  java: [
    'public int minCrossingTime(int[] times) {',
    '    Arrays.sort(times);',
    '    int n = times.length, ans = 0;',
    '    int i = n - 1;',
    '    while (i >= 3) {',
    '        int s1 = times[i] + times[0] + times[i - 1] + times[0];',
    '        int s2 = times[1] + times[0] + times[i] + times[1];',
    '        ans += Math.min(s1, s2);',
    '        i -= 2;',
    '    }',
    '    if (i == 2) ans += times[0] + times[1] + times[2];',
    '    else if (i == 1) ans += times[1];',
    '    else if (i == 0) ans += times[0];',
    '    return ans;',
    '}',
  ],
  cpp: [
    'int minCrossingTime(vector<int>& times) {',
    '    sort(times.begin(), times.end());',
    '    int n = times.size(), ans = 0, i = n - 1;',
    '    while (i >= 3) {',
    '        int s1 = times[i] + times[0] + times[i - 1] + times[0];',
    '        int s2 = times[1] + times[0] + times[i] + times[1];',
    '        ans += min(s1, s2);',
    '        i -= 2;',
    '    }',
    '    if (i == 2) ans += times[0] + times[1] + times[2];',
    '    else if (i == 1) ans += times[1];',
    '    else if (i == 0) ans += times[0];',
    '    return ans;',
    '}',
  ],
  python: [
    'def minCrossingTime(times: List[int]) -> int:',
    '    times.sort()',
    '    n, ans, i = len(times), 0, len(times) - 1',
    '    while i >= 3:',
    '        s1 = times[i] + times[0] + times[i - 1] + times[0]',
    '        s2 = times[1] + times[0] + times[i] + times[1]',
    '        ans += min(s1, s2)',
    '        i -= 2',
    '    if i == 2: ans += times[0] + times[1] + times[2]',
    '    elif i == 1: ans += times[1]',
    '    elif i == 0: ans += times[0]',
    '    return ans',
  ],
  javascript: [
    'function minCrossingTime(times) {',
    '    times.sort((a, b) => a - b);',
    '    let ans = 0, i = times.length - 1;',
    '    while (i >= 3) {',
    '        const s1 = times[i] + times[0] + times[i - 1] + times[0];',
    '        const s2 = times[1] + times[0] + times[i] + times[1];',
    '        ans += Math.min(s1, s2);',
    '        i -= 2;',
    '    }',
    '    if (i === 2) ans += times[0] + times[1] + times[2];',
    '    else if (i === 1) ans += times[1];',
    '    else if (i === 0) ans += times[0];',
    '    return ans;',
    '}',
  ],
};

export const CROSS_RIVER_LINES = {
  entry:     { java: 1, cpp: 1, python: 1, javascript: 1 },
  sortTimes: { java: 2, cpp: 2, python: 2, javascript: 2 },
  compareS1S2: { java: 8, cpp: 8, python: 7, javascript: 8 },
  baseCase:  { java: 11, cpp: 11, python: 9, javascript: 11 },
  done:      { java: 14, cpp: 14, python: 12, javascript: 14 },
};

// ==========================================
// 5. 超级洗衣机 (LeetCode 517)
// ==========================================
export const SUPER_WASHING_MACHINES_CODES: Record<string, string[]> = {
  java: [
    'public int findMinMoves(int[] machines) {',
    '    int sum = 0, n = machines.length;',
    '    for (int num : machines) sum += num;',
    '    if (sum % n != 0) return -1;',
    '    int avg = sum / n, leftSum = 0, maxMoves = 0;',
    '    for (int i = 0; i < n; i++) {',
    '        int leftNeed = i * avg - leftSum;',
    '        int rightNeed = (n - 1 - i) * avg - (sum - leftSum - machines[i]);',
    '        int curBottleneck;',
    '        if (leftNeed > 0 && rightNeed > 0) curBottleneck = leftNeed + rightNeed;',
    '        else curBottleneck = Math.max(Math.abs(leftNeed), Math.abs(rightNeed));',
    '        maxMoves = Math.max(maxMoves, curBottleneck);',
    '        leftSum += machines[i];',
    '    }',
    '    return maxMoves;',
    '}',
  ],
  cpp: [
    'int findMinMoves(vector<int>& machines) {',
    '    int sum = 0, n = machines.size();',
    '    for (int num : machines) sum += num;',
    '    if (sum % n != 0) return -1;',
    '    int avg = sum / n, leftSum = 0, maxMoves = 0;',
    '    for (int i = 0; i < n; i++) {',
    '        int leftNeed = i * avg - leftSum;',
    '        int rightNeed = (n - 1 - i) * avg - (sum - leftSum - machines[i]);',
    '        int curBottleneck;',
    '        if (leftNeed > 0 && rightNeed > 0) curBottleneck = leftNeed + rightNeed;',
    '        else curBottleneck = max(abs(leftNeed), abs(rightNeed));',
    '        maxMoves = max(maxMoves, curBottleneck);',
    '        leftSum += machines[i];',
    '    }',
    '    return maxMoves;',
    '}',
  ],
  python: [
    'def findMinMoves(machines: List[int]) -> int:',
    '    total, n = sum(machines), len(machines)',
    '    if total % n != 0: return -1',
    '    avg, left_sum, max_moves = total // n, 0, 0',
    '    for i, num in enumerate(machines):',
    '        left_need = i * avg - left_sum',
    '        right_need = (n - 1 - i) * avg - (total - left_sum - num)',
    '        if left_need > 0 and right_need > 0:',
    '            bottleneck = left_need + right_need',
    '        else:',
    '            bottleneck = max(abs(left_need), abs(right_need))',
    '        max_moves = max(max_moves, bottleneck)',
    '        left_sum += num',
    '    return max_moves',
  ],
  javascript: [
    'function findMinMoves(machines) {',
    '    const sum = machines.reduce((a, b) => a + b, 0);',
    '    const n = machines.length;',
    '    if (sum % n !== 0) return -1;',
    '    const avg = sum / n;',
    '    let leftSum = 0, maxMoves = 0;',
    '    for (let i = 0; i < n; i++) {',
    '        const leftNeed = i * avg - leftSum;',
    '        const rightNeed = (n - 1 - i) * avg - (sum - leftSum - machines[i]);',
    '        let bottleneck;',
    '        if (leftNeed > 0 && rightNeed > 0) bottleneck = leftNeed + rightNeed;',
    '        else bottleneck = Math.max(Math.abs(leftNeed), Math.abs(rightNeed));',
    '        maxMoves = Math.max(maxMoves, bottleneck);',
    '        leftSum += machines[i];',
    '    }',
    '    return maxMoves;',
    '}',
  ],
};

export const SUPER_WASHING_MACHINES_LINES = {
  entry:     { java: 1, cpp: 1, python: 1, javascript: 1 },
  guardDiv:  { java: 4, cpp: 4, python: 3, javascript: 4 },
  calcNeeds: { java: 8, cpp: 8, python: 7, javascript: 9 },
  bottleneck:{ java: 12, cpp: 12, python: 11, javascript: 12 },
  done:      { java: 15, cpp: 15, python: 13, javascript: 15 },
};
