/**
 * 左程云算法通关课 Class 062: 宽度优先遍历及其扩展
 * Java / C++ / Python / JavaScript 4 语言高保真源码与 1-Based 行号映射字典
 */

// ==========================================
// 1. 地图分析 (As Far from Land as Possible · LeetCode 1162)
// ==========================================
export const AS_FAR_FROM_LAND_062_CODES: Record<string, string[]> = {
  java: [
    'package class062;',
    'import java.util.ArrayDeque;',
    'import java.util.Queue;',
    '',
    '// 地图分析 (LeetCode 1162) - 多源 BFS',
    'public class Code01_AsFarFromLandAsPossible {',
    '    public static int maxDistance(int[][] grid) {',
    '        int n = grid.length;',
    '        Queue<int[]> queue = new ArrayDeque<>();',
    '        int seas = 0;',
    '        for (int i = 0; i < n; i++) {',
    '            for (int j = 0; j < n; j++) {',
    '                if (grid[i][j] == 1) {',
    '                    queue.offer(new int[] { i, j });',
    '                } else {',
    '                    seas++;',
    '                }',
    '            }',
    '        }',
    '        if (seas == 0 || seas == n * n) return -1;',
    '        int dist = -1;',
    '        int[][] dirs = { { -1, 0 }, { 1, 0 }, { 0, -1 }, { 0, 1 } };',
    '        while (!queue.isEmpty()) {',
    '            dist++;',
    '            int size = queue.size();',
    '            for (int k = 0; k < size; k++) {',
    '                int[] cur = queue.poll();',
    '                for (int[] d : dirs) {',
    '                    int ni = cur[0] + d[0], nj = cur[1] + d[1];',
    '                    if (ni >= 0 && ni < n && nj >= 0 && nj < n && grid[ni][nj] == 0) {',
    '                        grid[ni][nj] = 1;',
    '                        queue.offer(new int[] { ni, nj });',
    '                    }',
    '                }',
    '            }',
    '        }',
    '        return dist;',
    '    }',
    '}',
  ],
  cpp: [
    '#include <vector>',
    '#include <queue>',
    'using namespace std;',
    '',
    '// 地图分析 (LeetCode 1162) - 多源 BFS',
    'int maxDistance(vector<vector<int>>& grid) {',
    '    int n = grid.size();',
    '    queue<pair<int, int>> q;',
    '    int seas = 0;',
    '    for (int i = 0; i < n; i++) {',
    '        for (int j = 0; j < n; j++) {',
    '            if (grid[i][j] == 1) q.push({i, j});',
    '            else seas++;',
    '        }',
    '    }',
    '    if (seas == 0 || seas == n * n) return -1;',
    '    int dist = -1;',
    '    int dx[4] = {-1, 1, 0, 0}, dy[4] = {0, 0, -1, 1};',
    '    while (!q.empty()) {',
    '        dist++;',
    '        int sz = q.size();',
    '        while (sz--) {',
    '            auto [x, y] = q.front(); q.pop();',
    '            for (int k = 0; k < 4; k++) {',
    '                int nx = x + dx[k], ny = y + dy[k];',
    '                if (nx >= 0 && nx < n && ny >= 0 && ny < n && grid[nx][ny] == 0) {',
    '                    grid[nx][ny] = 1;',
    '                    q.push({nx, ny});',
    '                }',
    '            }',
    '        }',
    '    }',
    '    return dist;',
    '}',
  ],
  python: [
    'from collections import deque',
    '',
    '# 地图分析 (LeetCode 1162) - 多源 BFS',
    'def maxDistance(grid: list[list[int]]) -> int:',
    '    n = len(grid)',
    '    q = deque()',
    '    seas = 0',
    '    for i in range(n):',
    '        for j in range(n):',
    '            if grid[i][j] == 1:',
    '                q.append((i, j))',
    '            else:',
    '                seas += 1',
    '    if seas == 0 or seas == n * n: return -1',
    '    dist = -1',
    '    dirs = [(-1, 0), (1, 0), (0, -1), (0, 1)]',
    '    while q:',
    '        dist += 1',
    '        for _ in range(len(q)):',
    '            x, y = q.popleft()',
    '            for dx, dy in dirs:',
    '                nx, ny = x + dx, y + dy',
    '                if 0 <= nx < n and 0 <= ny < n and grid[nx][ny] == 0:',
    '                    grid[nx][ny] = 1',
    '                    q.append((nx, ny))',
    '    return dist',
  ],
  javascript: [
    '// 地图分析 (LeetCode 1162) - 多源 BFS',
    'function maxDistance(grid) {',
    '    const n = grid.length;',
    '    const q = [];',
    '    let seas = 0;',
    '    for (let i = 0; i < n; i++) {',
    '        for (let j = 0; j < n; j++) {',
    '            if (grid[i][j] === 1) q.push([i, j]);',
    '            else seas++;',
    '        }',
    '    }',
    '    if (seas === 0 || seas === n * n) return -1;',
    '    let dist = -1;',
    '    const dirs = [[-1, 0], [1, 0], [0, -1], [0, 1]];',
    '    let head = 0;',
    '    while (head < q.length) {',
    '        dist++;',
    '        const size = q.length - head;',
    '        for (let k = 0; k < size; k++) {',
    '            const [x, y] = q[head++];',
    '            for (const [dx, dy] of dirs) {',
    '                const nx = x + dx, ny = y + dy;',
    '                if (nx >= 0 && nx < n && ny >= 0 && ny < n && grid[nx][ny] === 0) {',
    '                    grid[nx][ny] = 1;',
    '                    q.push([nx, ny]);',
    '                }',
    '            }',
    '        }',
    '    }',
    '    return dist;',
    '}',
  ],
};

export const AS_FAR_FROM_LAND_062_LINES = {
  entry: { java: 7, cpp: 6, python: 4, javascript: 2 },
  initQueue: { java: 13, cpp: 12, python: 10, javascript: 7 },
  checkAllSeaOrLand: { java: 19, cpp: 16, python: 14, javascript: 12 },
  whileQueue: { java: 22, cpp: 19, python: 17, javascript: 16 },
  pollCell: { java: 26, cpp: 23, python: 20, javascript: 20 },
  expandNeighbor: { java: 30, cpp: 27, python: 24, javascript: 24 },
  returnDist: { java: 36, cpp: 33, python: 26, javascript: 30 },
};

// ==========================================
// 2. 贴纸拼词 (Stickers to Spell Word · LeetCode 691)
// ==========================================
export const STICKERS_TO_SPELL_WORD_062_CODES: Record<string, string[]> = {
  java: [
    'package class062;',
    'import java.util.*;',
    '',
    '// 贴纸拼词 (LeetCode 691) - BFS 状态空间探索 + 贪心首字符剪枝',
    'public class Code02_StickersToSpellWord {',
    '    public static int minStickers(String[] stickers, String target) {',
    '        int n = stickers.length;',
    '        int[][] counts = new int[n][26];',
    '        for (int i = 0; i < n; i++) {',
    '            for (char c : stickers[i].toCharArray()) counts[i][c - \'a\']++;',
    '        }',
    '        Queue<String> queue = new ArrayDeque<>();',
    '        Set<String> visited = new HashSet<>();',
    '        queue.offer(target);',
    '        visited.add(target);',
    '        int level = 0;',
    '        while (!queue.isEmpty()) {',
    '            int size = queue.size();',
    '            for (int k = 0; k < size; k++) {',
    '                String cur = queue.poll();',
    '                if (cur.isEmpty()) return level;',
    '                char first = cur.charAt(0);',
    '                for (int[] s : counts) {',
    '                    if (s[first - \'a\'] == 0) continue; // 核心剪枝',
    '                    String next = subtract(cur, s);',
    '                    if (!visited.contains(next)) {',
    '                        visited.add(next);',
    '                        queue.offer(next);',
    '                    }',
    '                }',
    '            }',
    '            level++;',
    '        }',
    '        return -1;',
    '    }',
    '}',
  ],
  cpp: [
    '#include <vector>',
    '#include <string>',
    '#include <queue>',
    '#include <unordered_set>',
    'using namespace std;',
    '',
    '// 贴纸拼词 (LeetCode 691) - BFS + 贪心剪枝',
    'int minStickers(vector<string>& stickers, string target) {',
    '    int n = stickers.size();',
    '    vector<vector<int>> counts(n, vector<int>(26, 0));',
    '    for (int i = 0; i < n; i++)',
    '        for (char c : stickers[i]) counts[i][c - \'a\']++;',
    '    queue<string> q; unordered_set<string> vis;',
    '    q.push(target); vis.insert(target);',
    '    int step = 0;',
    '    while (!q.empty()) {',
    '        int sz = q.size();',
    '        while (sz--) {',
    '            string cur = q.front(); q.pop();',
    '            if (cur.empty()) return step;',
    '            char first = cur[0];',
    '            for (auto& s : counts) {',
    '                if (s[first - \'a\'] == 0) continue;',
    '                string next = subtract(cur, s);',
    '                if (!vis.count(next)) { vis.insert(next); q.push(next); }',
    '            }',
    '        }',
    '        step++;',
    '    }',
    '    return -1;',
    '}',
  ],
  python: [
    'from collections import deque',
    '',
    '# 贴纸拼词 (LeetCode 691) - BFS + 贪心首字母剪枝',
    'def minStickers(stickers: list[str], target: str) -> int:',
    '    counts = []',
    '    for s in stickers:',
    '        c = [0] * 26',
    '        for ch in s: c[ord(ch) - 97] += 1',
    '        counts.append(c)',
    '    q = deque([target])',
    '    visited = {target}',
    '    step = 0',
    '    while q:',
    '        for _ in range(len(q)):',
    '            cur = q.popleft()',
    '            if not cur: return step',
    '            first = cur[0]',
    '            for s in counts:',
    '                if s[ord(first) - 97] == 0: continue',
    '                next_str = subtract(cur, s)',
    '                if next_str not in visited:',
    '                    visited.add(next_str)',
    '                    q.append(next_str)',
    '        step += 1',
    '    return -1',
  ],
  javascript: [
    '// 贴纸拼词 (LeetCode 691) - BFS + 贪心首字母剪枝',
    'function minStickers(stickers, target) {',
    '    const counts = stickers.map(s => {',
    '        const cnt = new Array(26).fill(0);',
    '        for (const ch of s) cnt[ch.charCodeAt(0) - 97]++;',
    '        return cnt;',
    '    });',
    '    const q = [target];',
    '    const visited = new Set([target]);',
    '    let step = 0, head = 0;',
    '    while (head < q.length) {',
    '        const size = q.length - head;',
    '        for (let i = 0; i < size; i++) {',
    '            const cur = q[head++];',
    '            if (cur === "") return step;',
    '            const firstIdx = cur.charCodeAt(0) - 97;',
    '            for (const s of counts) {',
    '                if (s[firstIdx] === 0) continue;',
    '                const next = subtract(cur, s);',
    '                if (!visited.has(next)) {',
    '                    visited.add(next);',
    '                    q.push(next);',
    '                }',
    '            }',
    '        }',
    '        step++;',
    '    }',
    '    return -1;',
    '}',
  ],
};

export const STICKERS_TO_SPELL_WORD_062_LINES = {
  entry: { java: 6, cpp: 8, python: 4, javascript: 2 },
  initTargetQueue: { java: 14, cpp: 14, python: 10, javascript: 8 },
  whileQueue: { java: 17, cpp: 16, python: 13, javascript: 11 },
  pollString: { java: 20, cpp: 19, python: 15, javascript: 14 },
  firstCharPrune: { java: 23, cpp: 22, python: 18, javascript: 17 },
  enqueueNext: { java: 27, cpp: 25, python: 22, javascript: 21 },
  returnStep: { java: 21, cpp: 20, python: 16, javascript: 15 },
};

// ==========================================
// 3. 到达角落需要移除障碍物的最小数目 (LeetCode 2290)
// ==========================================
export const MINIMUM_OBSTACLES_062_CODES: Record<string, string[]> = {
  java: [
    'package class062;',
    'import java.util.ArrayDeque;',
    'import java.util.Arrays;',
    'import java.util.Deque;',
    '',
    '// 0-1 BFS：到达角落需要移除障碍物的最小数目 (LeetCode 2290)',
    'public class Code03_MinimumObstacleRemovalToReachCorner {',
    '    public static int minimumObstacles(int[][] grid) {',
    '        int m = grid.length, n = grid[0].length;',
    '        int[][] dist = new int[m][n];',
    '        for (int[] row : dist) Arrays.fill(row, Integer.MAX_VALUE);',
    '        Deque<int[]> deque = new ArrayDeque<>();',
    '        dist[0][0] = 0;',
    '        deque.addFirst(new int[] { 0, 0 });',
    '        int[][] dirs = { { -1, 0 }, { 1, 0 }, { 0, -1 }, { 0, 1 } };',
    '        while (!deque.isEmpty()) {',
    '            int[] cur = deque.pollFirst();',
    '            int x = cur[0], y = cur[1];',
    '            if (x == m - 1 && y == n - 1) return dist[x][y];',
    '            for (int[] d : dirs) {',
    '                int nx = x + d[0], ny = y + d[1];',
    '                if (nx >= 0 && nx < m && ny >= 0 && ny < n) {',
    '                    int w = grid[nx][ny];',
    '                    if (dist[nx][ny] > dist[x][y] + w) {',
    '                        dist[nx][ny] = dist[x][y] + w;',
    '                        if (w == 0) deque.addFirst(new int[] { nx, ny });',
    '                        else deque.addLast(new int[] { nx, ny });',
    '                    }',
    '                }',
    '            }',
    '        }',
    '        return dist[m - 1][n - 1];',
    '    }',
    '}',
  ],
  cpp: [
    '#include <vector>',
    '#include <deque>',
    'using namespace std;',
    '',
    '// 0-1 BFS 双端队列 (LeetCode 2290)',
    'int minimumObstacles(vector<vector<int>>& grid) {',
    '    int m = grid.size(), n = grid[0].size();',
    '    vector<vector<int>> dist(m, vector<int>(n, 1e9));',
    '    deque<pair<int, int>> dq;',
    '    dist[0][0] = 0;',
    '    dq.push_front({0, 0});',
    '    int dx[4] = {-1, 1, 0, 0}, dy[4] = {0, 0, -1, 1};',
    '    while (!dq.empty()) {',
    '        auto [x, y] = dq.front(); dq.pop_front();',
    '        if (x == m - 1 && y == n - 1) return dist[x][y];',
    '        for (int i = 0; i < 4; ++i) {',
    '            int nx = x + dx[i], ny = y + dy[i];',
    '            if (nx >= 0 && nx < m && ny >= 0 && ny < n) {',
    '                int w = grid[nx][ny];',
    '                if (dist[nx][ny] > dist[x][y] + w) {',
    '                    dist[nx][ny] = dist[x][y] + w;',
    '                    if (w == 0) dq.push_front({nx, ny});',
    '                    else dq.push_back({nx, ny});',
    '                }',
    '            }',
    '        }',
    '    }',
    '    return dist[m - 1][n - 1];',
    '}',
  ],
  python: [
    'from collections import deque',
    '',
    '# 0-1 BFS (LeetCode 2290)',
    'def minimumObstacles(grid: list[list[int]]) -> int:',
    '    m, n = len(grid), len(grid[0])',
    '    dist = [[float("inf")] * n for _ in range(m)]',
    '    dq = deque([(0, 0)])',
    '    dist[0][0] = 0',
    '    dirs = [(-1, 0), (1, 0), (0, -1), (0, 1)]',
    '    while dq:',
    '        x, y = dq.popleft()',
    '        if x == m - 1 and y == n - 1: return dist[x][y]',
    '        for dx, dy in dirs:',
    '            nx, ny = x + dx, y + dy',
    '            if 0 <= nx < m and 0 <= ny < n:',
    '                w = grid[nx][ny]',
    '                if dist[nx][ny] > dist[x][y] + w:',
    '                    dist[nx][ny] = dist[x][y] + w',
    '                    if w == 0: dq.appendleft((nx, ny))',
    '                    else: dq.append((nx, ny))',
    '    return dist[m - 1][n - 1]',
  ],
  javascript: [
    '// 0-1 BFS 双端队列 (LeetCode 2290)',
    'function minimumObstacles(grid) {',
    '    const m = grid.length, n = grid[0].length;',
    '    const dist = Array.from({ length: m }, () => new Array(n).fill(Infinity));',
    '    const dq = [[0, 0]];',
    '    dist[0][0] = 0;',
    '    const dirs = [[-1, 0], [1, 0], [0, -1], [0, 1]];',
    '    while (dq.length > 0) {',
    '        const [x, y] = dq.shift();',
    '        if (x === m - 1 && y === n - 1) return dist[x][y];',
    '        for (const [dx, dy] of dirs) {',
    '            const nx = x + dx, ny = y + dy;',
    '            if (nx >= 0 && nx < m && ny >= 0 && ny < n) {',
    '                const w = grid[nx][ny];',
    '                if (dist[nx][ny] > dist[x][y] + w) {',
    '                    dist[nx][ny] = dist[x][y] + w;',
    '                    if (w === 0) dq.unshift([nx, ny]);',
    '                    else dq.push([nx, ny]);',
    '                }',
    '            }',
    '        }',
    '    }',
    '    return dist[m - 1][n - 1];',
    '}',
  ],
};

export const MINIMUM_OBSTACLES_062_LINES = {
  entry: { java: 8, cpp: 6, python: 4, javascript: 2 },
  initDist: { java: 11, cpp: 8, python: 6, javascript: 4 },
  initDeque: { java: 14, cpp: 11, python: 8, javascript: 6 },
  whileDeque: { java: 16, cpp: 13, python: 10, javascript: 8 },
  pollNode: { java: 17, cpp: 14, python: 11, javascript: 9 },
  targetCheck: { java: 19, cpp: 15, python: 12, javascript: 10 },
  pushZeroFront: { java: 26, cpp: 21, python: 18, javascript: 16 },
  pushOneBack: { java: 27, cpp: 22, python: 19, javascript: 17 },
  returnResult: { java: 32, cpp: 27, python: 20, javascript: 22 },
};

// ==========================================
// 4. 使网格图至少有一条有效路径的最小代价 (LeetCode 1368)
// ==========================================
export const MINIMUM_COST_VALID_PATH_062_CODES: Record<string, string[]> = {
  java: [
    'package class062;',
    'import java.util.ArrayDeque;',
    'import java.util.Arrays;',
    'import java.util.Deque;',
    '',
    '// 有效路径最小代价 (LeetCode 1368) - 0-1 BFS',
    'public class Code04_MinimumCostToMakeAtLeastOneValidPath {',
    '    public static int minCost(int[][] grid) {',
    '        int m = grid.length, n = grid[0].length;',
    '        int[][] dist = new int[m][n];',
    '        for (int[] r : dist) Arrays.fill(r, Integer.MAX_VALUE);',
    '        Deque<int[]> dq = new ArrayDeque<>();',
    '        dist[0][0] = 0;',
    '        dq.addFirst(new int[] { 0, 0 });',
    '        int[][] dirs = { {}, { 0, 1 }, { 0, -1 }, { 1, 0 }, { -1, 0 } };',
    '        while (!dq.isEmpty()) {',
    '            int[] cur = dq.pollFirst();',
    '            int r = cur[0], c = cur[1];',
    '            if (r == m - 1 && c == n - 1) return dist[r][c];',
    '            for (int d = 1; d <= 4; d++) {',
    '                int nr = r + dirs[d][0], nc = c + dirs[d][1];',
    '                if (nr >= 0 && nr < m && nc >= 0 && nc < n) {',
    '                    int w = (grid[r][c] == d) ? 0 : 1;',
    '                    if (dist[nr][nc] > dist[r][c] + w) {',
    '                        dist[nr][nc] = dist[r][c] + w;',
    '                        if (w == 0) dq.addFirst(new int[] { nr, nc });',
    '                        else dq.addLast(new int[] { nr, nc });',
    '                    }',
    '                }',
    '            }',
    '        }',
    '        return dist[m - 1][n - 1];',
    '    }',
    '}',
  ],
  cpp: [
    '#include <vector>',
    '#include <deque>',
    'using namespace std;',
    '',
    '// 有效路径最小代价 (LeetCode 1368) - 0-1 BFS',
    'int minCost(vector<vector<int>>& grid) {',
    '    int m = grid.size(), n = grid[0].size();',
    '    vector<vector<int>> dist(m, vector<int>(n, 1e9));',
    '    deque<pair<int, int>> dq;',
    '    dist[0][0] = 0; dq.push_front({0, 0});',
    '    int dirs[5][2] = {{0, 0}, {0, 1}, {0, -1}, {1, 0}, {-1, 0}};',
    '    while (!dq.empty()) {',
    '        auto [r, c] = dq.front(); dq.pop_front();',
    '        if (r == m - 1 && c == n - 1) return dist[r][c];',
    '        for (int d = 1; d <= 4; d++) {',
    '            int nr = r + dirs[d][0], nc = c + dirs[d][1];',
    '            if (nr >= 0 && nr < m && nc >= 0 && nc < n) {',
    '                int w = (grid[r][c] == d) ? 0 : 1;',
    '                if (dist[nr][nc] > dist[r][c] + w) {',
    '                    dist[nr][nc] = dist[r][c] + w;',
    '                    if (w == 0) dq.push_front({nr, nc});',
    '                    else dq.push_back({nr, nc});',
    '                }',
    '            }',
    '        }',
    '    }',
    '    return dist[m - 1][n - 1];',
    '}',
  ],
  python: [
    'from collections import deque',
    '',
    '# 有效路径最小代价 (LeetCode 1368) - 0-1 BFS',
    'def minCost(grid: list[list[int]]) -> int:',
    '    m, n = len(grid), len(grid[0])',
    '    dist = [[float("inf")] * n for _ in range(m)]',
    '    dq = deque([(0, 0)])',
    '    dist[0][0] = 0',
    '    dirs = [(0, 0), (0, 1), (0, -1), (1, 0), (-1, 0)]',
    '    while dq:',
    '        r, c = dq.popleft()',
    '        if r == m - 1 and c == n - 1: return dist[r][c]',
    '        for d in range(1, 5):',
    '            dr, dc = dirs[d]',
    '            nr, nc = r + dr, c + dc',
    '            if 0 <= nr < m and 0 <= nc < n:',
    '                w = 0 if grid[r][c] == d else 1',
    '                if dist[nr][nc] > dist[r][c] + w:',
    '                    dist[nr][nc] = dist[r][c] + w',
    '                    if w == 0: dq.appendleft((nr, nc))',
    '                    else: dq.append((nr, nc))',
    '    return dist[m - 1][n - 1]',
  ],
  javascript: [
    '// 有效路径最小代价 (LeetCode 1368) - 0-1 BFS',
    'function minCost(grid) {',
    '    const m = grid.length, n = grid[0].length;',
    '    const dist = Array.from({ length: m }, () => new Array(n).fill(Infinity));',
    '    const dq = [[0, 0]];',
    '    dist[0][0] = 0;',
    '    const dirs = [[0, 0], [0, 1], [0, -1], [1, 0], [-1, 0]];',
    '    while (dq.length > 0) {',
    '        const [r, c] = dq.shift();',
    '        if (r === m - 1 && c === n - 1) return dist[r][c];',
    '        for (let d = 1; d <= 4; d++) {',
    '            const [dr, dc] = dirs[d];',
    '            const nr = r + dr, nc = c + dc;',
    '            if (nr >= 0 && nr < m && nc >= 0 && nc < n) {',
    '                const w = grid[r][c] === d ? 0 : 1;',
    '                if (dist[nr][nc] > dist[r][c] + w) {',
    '                    dist[nr][nc] = dist[r][c] + w;',
    '                    if (w === 0) dq.unshift([nr, nc]);',
    '                    else dq.push([nr, nc]);',
    '                }',
    '            }',
    '        }',
    '    }',
    '    return dist[m - 1][n - 1];',
    '}',
  ],
};

export const MINIMUM_COST_VALID_PATH_062_LINES = {
  entry: { java: 8, cpp: 6, python: 4, javascript: 2 },
  initDist: { java: 11, cpp: 8, python: 6, javascript: 4 },
  initQueue: { java: 14, cpp: 10, python: 8, javascript: 6 },
  whileQueue: { java: 16, cpp: 12, python: 10, javascript: 8 },
  pollCoord: { java: 17, cpp: 13, python: 11, javascript: 9 },
  checkDirectionWeight: { java: 22, cpp: 17, python: 16, javascript: 14 },
  pushZeroFront: { java: 25, cpp: 20, python: 19, javascript: 17 },
  pushOneBack: { java: 26, cpp: 21, python: 20, javascript: 18 },
  returnMinCost: { java: 31, cpp: 26, python: 21, javascript: 23 },
};

// ==========================================
// 5. 二维接雨水 II (LeetCode 407 · Trapping Rain Water II)
// ==========================================
export const TRAPPING_RAIN_WATER_II_062_CODES: Record<string, string[]> = {
  java: [
    'package class062;',
    'import java.util.PriorityQueue;',
    '',
    '// 二维接雨水 (LeetCode 407) - 小根堆向内收缩木桶短板',
    'public class Code05_TrappingRainWaterII {',
    '    public static int trapRainWater(int[][] heightMap) {',
    '        int m = heightMap.length, n = heightMap[0].length;',
    '        PriorityQueue<int[]> pq = new PriorityQueue<>((a, b) -> a[2] - b[2]);',
    '        boolean[][] visited = new boolean[m][n];',
    '        for (int i = 0; i < m; i++) {',
    '            for (int j = 0; j < n; j++) {',
    '                if (i == 0 || i == m - 1 || j == 0 || j == n - 1) {',
    '                    pq.offer(new int[] { i, j, heightMap[i][j] });',
    '                    visited[i][j] = true;',
    '                }',
    '            }',
    '        }',
    '        int water = 0;',
    '        int[][] dirs = { { -1, 0 }, { 1, 0 }, { 0, -1 }, { 0, 1 } };',
    '        while (!pq.isEmpty()) {',
    '            int[] cur = pq.poll();',
    '            int r = cur[0], c = cur[1], h = cur[2];',
    '            for (int[] d : dirs) {',
    '                int nr = r + d[0], nc = c + d[1];',
    '                if (nr >= 0 && nr < m && nc >= 0 && nc < n && !visited[nr][nc]) {',
    '                    water += Math.max(0, h - heightMap[nr][nc]);',
    '                    pq.offer(new int[] { nr, nc, Math.max(h, heightMap[nr][nc]) });',
    '                    visited[nr][nc] = true;',
    '                }',
    '            }',
    '        }',
    '        return water;',
    '    }',
    '}',
  ],
  cpp: [
    '#include <vector>',
    '#include <queue>',
    '#include <tuple>',
    'using namespace std;',
    '',
    '// 3D 接雨水 (LeetCode 407) - 优先队列木桶短板',
    'int trapRainWater(vector<vector<int>>& heightMap) {',
    '    int m = heightMap.size(), n = heightMap[0].size();',
    '    priority_queue<tuple<int, int, int>, vector<tuple<int, int, int>>, greater<>> pq;',
    '    vector<vector<bool>> vis(m, vector<bool>(n, false));',
    '    for (int i = 0; i < m; i++) {',
    '        for (int j = 0; j < n; j++) {',
    '            if (i == 0 || i == m - 1 || j == 0 || j == n - 1) {',
    '                pq.push({heightMap[i][j], i, j});',
    '                vis[i][j] = true;',
    '            }',
    '        }',
    '    }',
    '    int water = 0;',
    '    int dirs[4][2] = {{-1, 0}, {1, 0}, {0, -1}, {0, 1}};',
    '    while (!pq.empty()) {',
    '        auto [h, r, c] = pq.top(); pq.pop();',
    '        for (auto& d : dirs) {',
    '            int nr = r + d[0], nc = c + d[1];',
    '            if (nr >= 0 && nr < m && nc >= 0 && nc < n && !vis[nr][nc]) {',
    '                water += max(0, h - heightMap[nr][nc]);',
    '                pq.push({max(h, heightMap[nr][nc]), nr, nc});',
    '                vis[nr][nc] = true;',
    '            }',
    '        }',
    '    }',
    '    return water;',
    '}',
  ],
  python: [
    'import heapq',
    '',
    '# 3D 接雨水 (LeetCode 407)',
    'def trapRainWater(heightMap: list[list[int]]) -> int:',
    '    m, n = len(heightMap), len(heightMap[0])',
    '    pq = []',
    '    visited = [[False] * n for _ in range(m)]',
    '    for i in range(m):',
    '        for j in range(n):',
    '            if i == 0 or i == m - 1 or j == 0 or j == n - 1:',
    '                heapq.heappush(pq, (heightMap[i][j], i, j))',
    '                visited[i][j] = True',
    '    water = 0',
    '    dirs = [(-1, 0), (1, 0), (0, -1), (0, 1)]',
    '    while pq:',
    '        h, r, c = heapq.heappop(pq)',
    '        for dr, dc in dirs:',
    '            nr, nc = r + dr, c + dc',
    '            if 0 <= nr < m and 0 <= nc < n and not visited[nr][nc]:',
    '                water += max(0, h - heightMap[nr][nc])',
    '                heapq.heappush(pq, (max(h, heightMap[nr][nc]), nr, nc))',
    '                visited[nr][nc] = True',
    '    return water',
  ],
  javascript: [
    '// 3D 接雨水 (LeetCode 407)',
    'function trapRainWater(heightMap) {',
    '    const m = heightMap.length, n = heightMap[0].length;',
    '    const visited = Array.from({ length: m }, () => new Array(n).fill(false));',
    '    const pq = [];',
    '    for (let i = 0; i < m; i++) {',
    '        for (let j = 0; j < n; j++) {',
    '            if (i === 0 || i === m - 1 || j === 0 || j === n - 1) {',
    '                pq.push([i, j, heightMap[i][j]]);',
    '                visited[i][j] = true;',
    '            }',
    '        }',
    '    }',
    '    pq.sort((a, b) => a[2] - b[2]);',
    '    let water = 0;',
    '    const dirs = [[-1, 0], [1, 0], [0, -1], [0, 1]];',
    '    while (pq.length > 0) {',
    '        const [r, c, h] = pq.shift();',
    '        for (const [dr, dc] of dirs) {',
    '            const nr = r + dr, nc = c + dc;',
    '            if (nr >= 0 && nr < m && nc >= 0 && nc < n && !visited[nr][nc]) {',
    '                water += Math.max(0, h - heightMap[nr][nc]);',
    '                pq.push([nr, nc, Math.max(h, heightMap[nr][nc])]);',
    '                pq.sort((a, b) => a[2] - b[2]);',
    '                visited[nr][nc] = true;',
    '            }',
    '        }',
    '    }',
    '    return water;',
    '}',
  ],
};

export const TRAPPING_RAIN_WATER_II_062_LINES = {
  entry: { java: 6, cpp: 7, python: 4, javascript: 2 },
  initBoundaryHeap: { java: 13, cpp: 14, python: 11, javascript: 8 },
  whileHeap: { java: 20, cpp: 21, python: 16, javascript: 17 },
  popShortestBoard: { java: 21, cpp: 22, python: 17, javascript: 18 },
  accumulateWater: { java: 25, cpp: 26, python: 21, javascript: 22 },
  pushNewBoard: { java: 26, cpp: 27, python: 22, javascript: 23 },
  returnTotalWater: { java: 31, cpp: 32, python: 23, javascript: 28 },
};

// ==========================================
// 6. 单词接龙 II (Word Ladder II · LeetCode 126)
// ==========================================
export const WORD_LADDER_II_062_CODES: Record<string, string[]> = {
  java: [
    'package class062;',
    'import java.util.*;',
    '',
    '// 单词接龙 II (LeetCode 126) - BFS 分层建图 + DFS 回溯输出全路径',
    'public class Code06_WordLadderII {',
    '    public static List<List<String>> findLadders(String beginWord, String endWord, List<String> wordList) {',
    '        Set<String> dict = new HashSet<>(wordList);',
    '        List<List<String>> res = new ArrayList<>();',
    '        if (!dict.contains(endWord)) return res;',
    '        Map<String, List<String>> nexts = new HashMap<>();',
    '        Map<String, Integer> dist = new HashMap<>();',
    '        bfs(beginWord, endWord, dict, nexts, dist);',
    '        List<String> path = new ArrayList<>();',
    '        path.add(beginWord);',
    '        dfs(beginWord, endWord, nexts, dist, path, res);',
    '        return res;',
    '    }',
    '    private static void bfs(String begin, String end, Set<String> dict, Map<String, List<String>> nexts, Map<String, Integer> dist) {',
    '        Queue<String> queue = new ArrayDeque<>();',
    '        queue.offer(begin);',
    '        dist.put(begin, 0);',
    '        for (String w : dict) nexts.put(w, new ArrayList<>());',
    '        nexts.put(begin, new ArrayList<>());',
    '        boolean found = false;',
    '        while (!queue.isEmpty() && !found) {',
    '            int size = queue.size();',
    '            for (int i = 0; i < size; i++) {',
    '                String cur = queue.poll();',
    '                int curD = dist.get(cur);',
    '                for (String nxt : getNextWords(cur, dict)) {',
    '                    if (!dist.containsKey(nxt)) {',
    '                        dist.put(nxt, curD + 1);',
    '                        queue.offer(nxt);',
    '                    }',
    '                    if (dist.get(nxt) == curD + 1) nexts.get(cur).add(nxt);',
    '                    if (nxt.equals(end)) found = true;',
    '                }',
    '            }',
    '        }',
    '    }',
    '}',
  ],
  cpp: [
    '#include <vector>',
    '#include <string>',
    '#include <unordered_map>',
    '#include <unordered_set>',
    '#include <queue>',
    'using namespace std;',
    '',
    '// 单词接龙 II (LeetCode 126) - BFS 分层建图 + DFS 回溯',
    'vector<vector<string>> findLadders(string beginWord, string endWord, vector<string>& wordList) {',
    '    unordered_set<string> dict(wordList.begin(), wordList.end());',
    '    vector<vector<string>> res;',
    '    if (!dict.count(endWord)) return res;',
    '    unordered_map<string, vector<string>> nexts;',
    '    unordered_map<string, int> dist;',
    '    queue<string> q; q.push(beginWord); dist[beginWord] = 0;',
    '    bool found = false;',
    '    while (!q.empty() && !found) {',
    '        int sz = q.size();',
    '        while (sz--) {',
    '            string cur = q.front(); q.pop();',
    '            int curD = dist[cur];',
    '            for (const string& nxt : getNexts(cur, dict)) {',
    '                if (!dist.count(nxt)) { dist[nxt] = curD + 1; q.push(nxt); }',
    '                if (dist[nxt] == curD + 1) nexts[cur].push_back(nxt);',
    '                if (nxt == endWord) found = true;',
    '            }',
    '        }',
    '    }',
    '    vector<string> path = {beginWord};',
    '    dfs(beginWord, endWord, nexts, dist, path, res);',
    '    return res;',
    '}',
  ],
  python: [
    'from collections import deque, defaultdict',
    '',
    '# 单词接龙 II (LeetCode 126) - BFS 分层建图 + DFS 回溯',
    'def findLadders(beginWord: str, endWord: str, wordList: list[str]) -> list[list[str]]:',
    '    dict_set = set(wordList)',
    '    if endWord not in dict_set: return []',
    '    dist = {beginWord: 0}',
    '    nexts = defaultdict(list)',
    '    q = deque([beginWord])',
    '    found = False',
    '    while q and not found:',
    '        for _ in range(len(q)):',
    '            cur = q.popleft()',
    '            cur_d = dist[cur]',
    '            for nxt in get_nexts(cur, dict_set):',
    '                if nxt not in dist:',
    '                    dist[nxt] = cur_d + 1',
    '                    q.append(nxt)',
    '                if dist[nxt] == cur_d + 1: nexts[cur].append(nxt)',
    '                if nxt == endWord: found = True',
    '    res = []',
    '    dfs(beginWord, endWord, nexts, dist, [beginWord], res)',
    '    return res',
  ],
  javascript: [
    '// 单词接龙 II (LeetCode 126) - BFS 分层建图 + DFS 回溯',
    'function findLadders(beginWord, endWord, wordList) {',
    '    const dict = new Set(wordList);',
    '    if (!dict.has(endWord)) return [];',
    '    const dist = new Map([[beginWord, 0]]);',
    '    const nexts = new Map();',
    '    const q = [beginWord];',
    '    let found = false, head = 0;',
    '    while (head < q.length && !found) {',
    '        const size = q.length - head;',
    '        for (let i = 0; i < size; i++) {',
    '            const cur = q[head++];',
    '            const curD = dist.get(cur);',
    '            for (const nxt of getNextWords(cur, dict)) {',
    '                if (!dist.has(nxt)) { dist.set(nxt, curD + 1); q.push(nxt); }',
    '                if (dist.get(nxt) === curD + 1) {',
    '                    if (!nexts.has(cur)) nexts.set(cur, []);',
    '                    nexts.get(cur).push(nxt);',
    '                }',
    '                if (nxt === endWord) found = true;',
    '            }',
    '        }',
    '    }',
    '    const res = [];',
    '    dfs(beginWord, endWord, nexts, dist, [beginWord], res);',
    '    return res;',
    '}',
  ],
};

export const WORD_LADDER_II_062_LINES = {
  entry: { java: 6, cpp: 9, python: 4, javascript: 2 },
  initBfsQueue: { java: 19, cpp: 15, python: 8, javascript: 6 },
  bfsLevelLoop: { java: 24, cpp: 17, python: 11, javascript: 9 },
  expandWordTransitions: { java: 29, cpp: 21, python: 14, javascript: 14 },
  buildDAGGEdge: { java: 33, cpp: 23, python: 18, javascript: 17 },
  startDfsBacktrack: { java: 15, cpp: 28, python: 21, javascript: 24 },
  returnAllShortestPaths: { java: 16, cpp: 29, python: 22, javascript: 25 },
};
