/**
 * Class 067 从递归入手二维动态规划 4-Stage 演化多语言代码库
 * 涵盖全部 6 题的四阶段代码 (Java, C++, Python, JavaScript)
 */

// ==========================================
// 1. Code01 最小路径和 (LeetCode 64)
// ==========================================
// ==========================================
// ==========================================
// 2. Code02 单词搜索 (LeetCode 79)
// ==========================================
export const WORD_SEARCH_STAGE1_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    '// 阶段 1: 暴力四向深度优先递归探索 (带 visited 标记)',
    'public static boolean exist1(char[][] board, String word) {',
    '    int m = board.length, n = board[0].length;',
    '    boolean[][] visited = new boolean[m][n];',
    '    for (int i = 0; i < m; i++) {',
    '        for (int j = 0; j < n; j++) {',
    '            if (dfs1(board, word, i, j, 0, visited)) return true;',
    '        }',
    '    }',
    '    return false;',
    '}',
    'private static boolean dfs1(char[][] b, String w, int i, int j, int k, boolean[][] vis) {',
    '    if (k == w.length()) return true;',
    '    if (i < 0 || i >= b.length || j < 0 || j >= b[0].length) return false;',
    '    if (vis[i][j] || b[i][j] != w.charAt(k)) return false;',
    '    vis[i][j] = true;',
    '    boolean found = dfs1(b, w, i + 1, j, k + 1, vis)   // ⬇️ 向下探索',
    '                 || dfs1(b, w, i - 1, j, k + 1, vis)   // ⬆️ 向上探索',
    '                 || dfs1(b, w, i, j + 1, k + 1, vis)   // ➡️ 向右探索',
    '                 || dfs1(b, w, i, j - 1, k + 1, vis);  // ⬅️ 向左探索',
    '    vis[i][j] = false;',
    '    return found;',
    '}',
  ],
  cpp: [
    '// 阶段 1: 暴力四向深度优先递归探索 (带 visited 标记)',
    'bool exist1(vector<vector<char>>& board, string word) {',
    '    int m = board.size(), n = board[0].size();',
    '    vector<vector<bool>> visited(m, vector<bool>(n, false));',
    '    for (int i = 0; i < m; i++) {',
    '        for (int j = 0; j < n; j++) {',
    '            if (dfs1(board, word, i, j, 0, visited)) return true;',
    '        }',
    '    }',
    '    return false;',
    '}',
    'bool dfs1(vector<vector<char>>& b, const string& w, int i, int j, int k, vector<vector<bool>>& vis) {',
    '    if (k == w.size()) return true;',
    '    if (i < 0 || i >= b.size() || j < 0 || j >= b[0].size()) return false;',
    '    if (vis[i][j] || b[i][j] != w[k]) return false;',
    '    vis[i][j] = true;',
    '    bool found = dfs1(b, w, i + 1, j, k + 1, vis)   // ⬇️ 向下探索',
    '              || dfs1(b, w, i - 1, j, k + 1, vis)   // ⬆️ 向上探索',
    '              || dfs1(b, w, i, j + 1, k + 1, vis)   // ➡️ 向右探索',
    '              || dfs1(b, w, i, j - 1, k + 1, vis);  // ⬅️ 向左探索',
    '    vis[i][j] = false;',
    '    return found;',
    '}',
  ],
  python: [
    '# 阶段 1: 暴力四向深度优先递归探索 (带 visited 标记)',
    'def exist1(board: list[list[str]], word: str) -> bool:',
    '    m, n = len(board), len(board[0])',
    '    visited = [[False] * n for _ in range(m)]',
    '    for i in range(m):',
    '        for j in range(n):',
    '            if dfs1(board, word, i, j, 0, visited): return True',
    '        # end j',
    '    # end i',
    '    return False',
    '# 辅助递归',
    'def dfs1(b, w, i, j, k, vis):',
    '    if k == len(w): return True',
    '    if not (0 <= i < len(b) and 0 <= j < len(b[0])): return False',
    '    if vis[i][j] or b[i][j] != w[k]: return False',
    '    vis[i][j] = True',
    '    found = (dfs1(b, w, i + 1, j, k + 1, vis)   # ⬇️ 向下探索',
    '          or dfs1(b, w, i - 1, j, k + 1, vis)   # ⬆️ 向上探索',
    '          or dfs1(b, w, i, j + 1, k + 1, vis)   # ➡️ 向右探索',
    '          or dfs1(b, w, i, j - 1, k + 1, vis))  # ⬅️ 向左探索',
    '    vis[i][j] = False',
    '    return found',
    '# 结束',
  ],
  javascript: [
    '// 阶段 1: 暴力四向深度优先递归探索 (带 visited 标记)',
    'export function exist1(board, word) {',
    '  const m = board.length, n = board[0].length;',
    '  const visited = Array.from({ length: m }, () => new Array(n).fill(false));',
    '  for (let i = 0; i < m; i++) {',
    '    for (let j = 0; j < n; j++) {',
    '      if (dfs1(board, word, i, j, 0, visited)) return true;',
    '    }',
    '  }',
    '  return false;',
    '}',
    'function dfs1(b, w, i, j, k, vis) {',
    '  if (k === w.length) return true;',
    '  if (i < 0 || i >= b.length || j < 0 || j >= b[0].length) return false;',
    '  if (vis[i][j] || b[i][j] !== w[k]) return false;',
    '  vis[i][j] = true;',
    '  const found = dfs1(b, w, i + 1, j, k + 1, vis)   // ⬇️ 向下探索',
    '             || dfs1(b, w, i - 1, j, k + 1, vis)   // ⬆️ 向上探索',
    '             || dfs1(b, w, i, j + 1, k + 1, vis)   // ➡️ 向右探索',
    '             || dfs1(b, w, i, j - 1, k + 1, vis);  // ⬅️ 向左探索',
    '  vis[i][j] = false;',
    '  return found;',
    '}',
  ],
};

export const WORD_SEARCH_STAGE2_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    '// 阶段 2: 记忆化反例剖析 (尝试 memo[i][j][k] 为何导致致命 Bug)',
    'public static boolean existMemoWrong(char[][] b, String w) {',
    '    Boolean[][][] memo = new Boolean[b.length][b[0].length][w.length()];',
    '    for (int i = 0; i < b.length; i++) {',
    '        for (int j = 0; j < b[0].length; j++) {',
    '            if (dfsMemo(b, w, i, j, 0, memo)) return true;',
    '        }',
    '    }',
    '    return false;',
    '}',
    'private static boolean dfsMemo(char[][] b, String w, int i, int j, int k, Boolean[][][] memo) {',
    '    if (k == w.length()) return true;',
    '    if (i < 0 || i >= b.length || j < 0 || j >= b[0].length || b[i][j] != w.charAt(k)) return false;',
    '    if (memo[i][j][k] != null) return memo[i][j][k]; // ⚠️ 错误复用：忽略了历史路径禁区！',
    '    char tmp = b[i][j]; b[i][j] = 0;',
    '    boolean ans = dfsMemo(b, w, i + 1, j, k + 1, memo) // ⬇️ 向下分支',
    '               || dfsMemo(b, w, i, j + 1, k + 1, memo); // ➡️ 向右分支',
    '    b[i][j] = tmp;',
    '    return memo[i][j][k] = ans; // ⚠️ 污染缓存：此处的 ans 是在特定禁区下测得的，不可全局复用！',
    '}',
  ],
  cpp: [
    '// 阶段 2: 记忆化反例剖析 (尝试 memo[i][j][k] 为何导致致命 Bug)',
    'bool existMemoWrong(vector<vector<char>>& b, string w) {',
    '    vector<vector<vector<int>>> memo(b.size(), vector<vector<int>>(b[0].size(), vector<int>(w.size(), -1)));',
    '    for (int i = 0; i < b.size(); i++) {',
    '        for (int j = 0; j < b[0].size(); j++) {',
    '            if (dfsMemo(b, w, i, j, 0, memo)) return true;',
    '        }',
    '    }',
    '    return false;',
    '}',
    'bool dfsMemo(vector<vector<char>>& b, const string& w, int i, int j, int k, vector<vector<vector<int>>>& memo) {',
    '    if (k == w.size()) return true;',
    '    if (i < 0 || i >= b.size() || j < 0 || j >= b[0].size() || b[i][j] != w[k]) return false;',
    '    if (memo[i][j][k] != -1) return memo[i][j][k]; // ⚠️ 错误复用：忽略了历史路径禁区！',
    '    char tmp = b[i][j]; b[i][j] = 0;',
    '    bool ans = dfsMemo(b, w, i + 1, j, k + 1, memo) // ⬇️ 向下分支',
    '            || dfsMemo(b, w, i, j + 1, k + 1, memo); // ➡️ 向右分支',
    '    b[i][j] = tmp;',
    '    return memo[i][j][k] = ans; // ⚠️ 污染缓存：此处的 ans 是在特定禁区下测得的，不可全局复用！',
    '}',
  ],
  python: [
    '# 阶段 2: 记忆化反例剖析 (尝试 memo[i][j][k] 为何导致致命 Bug)',
    'def existMemoWrong(b: list[list[str]], w: str) -> bool:',
    '    memo = {}',
    '    for i in range(len(b)):',
    '        for j in range(len(b[0])):',
    '            if dfsMemo(b, w, i, j, 0, memo): return True',
    '        # end j',
    '    # end i',
    '    return False',
    '# 辅助递归函数',
    'def dfsMemo(b, w, i, j, k, memo):',
    '    if k == len(w): return True',
    '    if not (0 <= i < len(b) and 0 <= j < len(b[0])) or b[i][j] != w[k]: return False',
    '    if (i, j, k) in memo: return memo[(i, j, k)] # ⚠️ 错误复用：忽略了历史路径禁区！',
    '    tmp = b[i][j]; b[i][j] = 0',
    '    ans = dfsMemo(b, w, i + 1, j, k + 1, memo) \\',
    '       or dfsMemo(b, w, i, j + 1, k + 1, memo) # ⬇️ 向下 / ➡️ 向右分支',
    '    b[i][j] = tmp',
    '    memo[(i, j, k)] = ans; return ans # ⚠️ 污染缓存：此处的 ans 是在特定禁区下测得的，不可全局复用！',
    '# end dfsMemo',
  ],
  javascript: [
    '// 阶段 2: 记忆化反例剖析 (尝试 memo[i][j][k] 为何导致致命 Bug)',
    'export function existMemoWrong(b, w) {',
    '  const memo = new Map();',
    '  for (let i = 0; i < b.length; i++) {',
    '    for (let j = 0; j < b[0].length; j++) {',
    '      if (dfsMemo(b, w, i, j, 0, memo)) return true;',
    '    }',
    '  }',
    '  return false;',
    '}',
    'function dfsMemo(b, w, i, j, k, memo) {',
    '  if (k === w.length) return true;',
    '  if (i < 0 || i >= b.length || j < 0 || j >= b[0].length || b[i][j] !== w[k]) return false;',
    '  if (memo.has(`${i},${j},${k}`)) return memo.get(`${i},${j},${k}`); // ⚠️ 错误复用：忽略了历史路径禁区！',
    '  const tmp = b[i][j]; b[i][j] = 0;',
    '  const ans = dfsMemo(b, w, i + 1, j, k + 1, memo) // ⬇️ 向下分支',
    '           || dfsMemo(b, w, i, j + 1, k + 1, memo); // ➡️ 向右分支',
    '  b[i][j] = tmp;',
    '  memo.set(`${i},${j},${k}`, ans); return ans; // ⚠️ 污染缓存：此处的 ans 是在特定禁区下测得的！',
    '}',
  ],
};

export const WORD_SEARCH_STAGE3_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    '// 阶段 3: 原地修改字符打标与现场恢复 (空间降至 O(1))',
    'public static boolean exist3(char[][] board, String word) {',
    '    char[] w = word.toCharArray();',
    '    for (int i = 0; i < board.length; i++) {',
    '        for (int j = 0; j < board[0].length; j++) {',
    '            if (dfs3(board, w, i, j, 0)) return true;',
    '        }',
    '    }',
    '    return false;',
    '}',
    'private static boolean dfs3(char[][] b, char[] w, int i, int j, int k) {',
    '    if (k == w.length) return true;',
    '    if (i < 0 || i >= b.length || j < 0 || j >= b[0].length || b[i][j] != w[k]) return false;',
    '    char tmp = b[i][j];',
    '    b[i][j] = 0; // 原地打标占位',
    '    boolean found = dfs3(b, w, i + 1, j, k + 1)   // ⬇️ 向下探索',
    '                 || dfs3(b, w, i - 1, j, k + 1)   // ⬆️ 向上探索',
    '                 || dfs3(b, w, i, j + 1, k + 1)   // ➡️ 向右探索',
    '                 || dfs3(b, w, i, j - 1, k + 1);  // ⬅️ 向左探索',
    '    b[i][j] = tmp; // 回溯恢复现场',
    '    return found;',
    '}',
  ],
  cpp: [
    '// 阶段 3: 原地修改字符打标与现场恢复 (空间降至 O(1))',
    'bool exist3(vector<vector<char>>& board, string word) {',
    '    string w = word;',
    '    for (int i = 0; i < board.size(); i++) {',
    '        for (int j = 0; j < board[0].size(); j++) {',
    '            if (dfs3(board, w, i, j, 0)) return true;',
    '        }',
    '    }',
    '    return false;',
    '}',
    'bool dfs3(vector<vector<char>>& b, const string& w, int i, int j, int k) {',
    '    if (k == w.size()) return true;',
    '    if (i < 0 || i >= b.size() || j < 0 || j >= b[0].size() || b[i][j] != w[k]) return false;',
    '    char tmp = b[i][j];',
    '    b[i][j] = 0;',
    '    bool found = dfs3(b, w, i + 1, j, k + 1)   // ⬇️ 向下探索',
    '              || dfs3(b, w, i - 1, j, k + 1)   // ⬆️ 向上探索',
    '              || dfs3(b, w, i, j + 1, k + 1)   // ➡️ 向右探索',
    '              || dfs3(b, w, i, j - 1, k + 1);  // ⬅️ 向左探索',
    '    b[i][j] = tmp;',
    '    return found;',
    '}',
  ],
  python: [
    '# 阶段 3: 原地修改字符打标与现场恢复 (空间降至 O(1))',
    'def exist3(board: list[list[str]], word: str) -> bool:',
    '    w = list(word)',
    '    for i in range(len(board)):',
    '        for j in range(len(board[0])):',
    '            if dfs3(board, w, i, j, 0): return True',
    '        # end j',
    '    # end i',
    '    return False',
    '# 辅助递归',
    'def dfs3(b, w, i, j, k):',
    '    if k == len(w): return True',
    '    if not (0 <= i < len(b) and 0 <= j < len(b[0])) or b[i][j] != w[k]: return False',
    '    tmp = b[i][j]',
    '    b[i][j] = 0',
    '    found = (dfs3(b, w, i + 1, j, k + 1)   # ⬇️ 向下探索',
    '          or dfs3(b, w, i - 1, j, k + 1)   # ⬆️ 向上探索',
    '          or dfs3(b, w, i, j + 1, k + 1)   # ➡️ 向右探索',
    '          or dfs3(b, w, i, j - 1, k + 1))  # ⬅️ 向左探索',
    '    b[i][j] = tmp',
    '    return found',
    '# end dfs3',
  ],
  javascript: [
    '// 阶段 3: 原地修改字符打标与现场恢复 (空间降至 O(1))',
    'export function exist3(board, word) {',
    '  const w = word.split(\'\');',
    '  for (let i = 0; i < board.length; i++) {',
    '    for (let j = 0; j < board[0].length; j++) {',
    '      if (dfs3(board, w, i, j, 0)) return true;',
    '    }',
    '  }',
    '  return false;',
    '}',
    'function dfs3(b, w, i, j, k) {',
    '  if (k === w.length) return true;',
    '  if (i < 0 || i >= b.length || j < 0 || j >= b[0].length || b[i][j] !== w[k]) return false;',
    '  const tmp = b[i][j];',
    '  b[i][j] = 0;',
    '  const found = dfs3(b, w, i + 1, j, k + 1)   // ⬇️ 向下探索',
    '             || dfs3(b, w, i - 1, j, k + 1)   // ⬆️ 向上探索',
    '             || dfs3(b, w, i, j + 1, k + 1)   // ➡️ 向右探索',
    '             || dfs3(b, w, i, j - 1, k + 1);  // ⬅️ 向左探索',
    '  b[i][j] = tmp;',
    '  return found;',
    '}',
  ],
};

export const WORD_SEARCH_STAGE4_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    '// 阶段 4: 词频剪枝与双向/反向搜索优化',
    'public static boolean exist4(char[][] board, String word) {',
    '    int[] count = new int[128];',
    '    for (char[] row : board) for (char c : row) count[c]++;',
    '    char[] w = word.toCharArray();',
    '    for (char c : w) if (--count[c] < 0) return false; // 字母不够直接秒拒',
    '    if (count[w[w.length - 1]] < count[w[0]]) {',
    '        w = new StringBuilder(word).reverse().toString().toCharArray();',
    '    }',
    '    for (int i = 0; i < board.length; i++) {',
    '        for (int j = 0; j < board[0].length; j++) {',
    '            if (dfs4(board, w, i, j, 0)) return true;',
    '        }',
    '    }',
    '    return false;',
    '}',
    'private static boolean dfs4(char[][] b, char[] w, int i, int j, int k) {',
    '    if (k == w.length) return true;',
    '    if (i < 0 || i >= b.length || j < 0 || j >= b[0].length || b[i][j] != w[k]) return false;',
    '    char tmp = b[i][j];',
    '    b[i][j] = 0; // 原地打标占位',
    '    boolean found = dfs4(b, w, i + 1, j, k + 1)   // ⬇️ 向下探索',
    '                 || dfs4(b, w, i - 1, j, k + 1)   // ⬆️ 向上探索',
    '                 || dfs4(b, w, i, j + 1, k + 1)   // ➡️ 向右探索',
    '                 || dfs4(b, w, i, j - 1, k + 1);  // ⬅️ 向左探索',
    '    b[i][j] = tmp; // 回溯恢复现场',
    '    return found;',
    '}',
  ],
  cpp: [
    '// 阶段 4: 词频统计剪枝与方向倒置',
    'bool exist4(vector<vector<char>>& board, string word) {',
    '    vector<int> count(128, 0);',
    '    for (const auto& row : board) for (char c : row) count[c]++;',
    '    string w = word;',
    '    for (char c : w) if (--count[c] < 0) return false;',
    '    if (count[w.back()] < count[w.front()]) {',
    '        reverse(w.begin(), w.end());',
    '    }',
    '    for (int i = 0; i < board.size(); i++) {',
    '        for (int j = 0; j < board[0].size(); j++) {',
    '            if (dfs4(board, w, i, j, 0)) return true;',
    '        }',
    '    }',
    '    return false;',
    '}',
    'bool dfs4(vector<vector<char>>& b, const string& w, int i, int j, int k) {',
    '    if (k == w.size()) return true;',
    '    if (i < 0 || i >= b.size() || j < 0 || j >= b[0].size() || b[i][j] != w[k]) return false;',
    '    char tmp = b[i][j];',
    '    b[i][j] = 0;',
    '    bool found = dfs4(b, w, i + 1, j, k + 1)   // ⬇️ 向下探索',
    '              || dfs4(b, w, i - 1, j, k + 1)   // ⬆️ 向上探索',
    '              || dfs4(b, w, i, j + 1, k + 1)   // ➡️ 向右探索',
    '              || dfs4(b, w, i, j - 1, k + 1);  // ⬅️ 向左探索',
    '    b[i][j] = tmp;',
    '    return found;',
    '}',
  ],
  python: [
    '# 阶段 4: 词频剪枝与双向/反向搜索优化',
    'def exist4(board: list[list[str]], word: str) -> bool:',
    '    count = [0] * 128',
    '    for row in board: [count.__setitem__(ord(c), count[ord(c)] + 1) for c in row]',
    '    w = list(word)',
    '    for c in w: count[ord(c)] -= 1; (count[ord(c)] < 0) and False',
    '    if count[ord(w[-1])] < count[ord(w[0])]:',
    '        w.reverse()',
    '    # 遍历起点',
    '    for i in range(len(board)):',
    '        for j in range(len(board[0])):',
    '            if dfs4(board, w, i, j, 0): return True',
    '        # end j',
    '    # end i',
    '    return False',
    '# 辅助递归',
    'def dfs4(b, w, i, j, k):',
    '    if k == len(w): return True',
    '    if not (0 <= i < len(b) and 0 <= j < len(b[0])) or b[i][j] != w[k]: return False',
    '    tmp = b[i][j]',
    '    b[i][j] = 0',
    '    found = (dfs4(b, w, i + 1, j, k + 1)   # ⬇️ 向下探索',
    '          or dfs4(b, w, i - 1, j, k + 1)   # ⬆️ 向上探索',
    '          or dfs4(b, w, i, j + 1, k + 1)   # ➡️ 向右探索',
    '          or dfs4(b, w, i, j - 1, k + 1))  # ⬅️ 向左探索',
    '    b[i][j] = tmp',
    '    return found',
    '# end dfs4',
  ],
  javascript: [
    '// 阶段 4: 词频统计剪枝与倒序匹配',
    'export function exist4(board, word) {',
    '  const count = new Array(128).fill(0);',
    '  for (const row of board) for (const c of row) count[c.charCodeAt(0)]++;',
    '  let w = word.split(\'\');',
    '  for (const c of w) if (--count[c.charCodeAt(0)] < 0) return false;',
    '  if (count[w[w.length - 1].charCodeAt(0)] < count[w[0].charCodeAt(0)]) {',
    '    w.reverse();',
    '  }',
    '  for (let i = 0; i < board.length; i++) {',
    '    for (let j = 0; j < board[0].length; j++) {',
    '      if (dfs4(board, w, i, j, 0)) return true;',
    '    }',
    '  }',
    '  return false;',
    '}',
    'function dfs4(b, w, i, j, k) {',
    '  if (k === w.length) return true;',
    '  if (i < 0 || i >= b.length || j < 0 || j >= b[0].length || b[i][j] !== w[k]) return false;',
    '  const tmp = b[i][j];',
    '  b[i][j] = 0;',
    '  const found = dfs4(b, w, i + 1, j, k + 1)   // ⬇️ 向下探索',
    '             || dfs4(b, w, i - 1, j, k + 1)   // ⬆️ 向上探索',
    '             || dfs4(b, w, i, j + 1, k + 1)   // ➡️ 向右探索',
    '             || dfs4(b, w, i, j - 1, k + 1);  // ⬅️ 向左探索',
    '  b[i][j] = tmp;',
    '  return found;',
    '}',
  ],
};

// ==========================================
// 3. Code03 最长公共子序列 (LeetCode 1143)
// ==========================================
// ==========================================
// 4. Code04 最长回文子序列 (LeetCode 516)
// ==========================================

// ==========================================
// 5. Code05 二叉树结构数 (牛客网)
// ==========================================
export const TREE_COUNT_STAGE1_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    '// 阶段 1: 暴力递归尝试拆分左右子树节点规模',
    'public static long f1(int n, int m) {',
    '    if (n == 0) return 1; // 空树算一种形态且高度为0',
    '    if (m == 0) return 0; // 节点数>0但高度上限为0，不可行',
    '    long ways = 0;',
    '    for (int k = 0; k < n; k++) { // 枚举左子树节点数k，右子树为n-1-k',
    '        ways = (ways + f1(k, m - 1) * f1(n - 1 - k, m - 1)) % 1000000007;',
    '    }',
    '    return ways;',
    '}',
  ],
  cpp: [
    '// 阶段 1: 暴力递归拆分子树规模',
    'long long f1(int n, int m) {',
    '    if (n == 0) return 1;',
    '    if (m == 0) return 0;',
    '    long long ways = 0;',
    '    for (int k = 0; k < n; ++k) {',
    '        ways = (ways + f1(k, m - 1) * f1(n - 1 - k, m - 1)) % 1000000007;',
    '    }',
    '    return ways;',
    '}',
  ],
  python: [
    '# 阶段 1: 暴力递归',
    'def f1(n: int, m: int) -> int:',
    '    if n == 0: return 1',
    '    if m == 0: return 0',
    '    MOD = 10**9 + 7',
    '    return sum(f1(k, m - 1) * f1(n - 1 - k, m - 1) for k in range(n)) % MOD',
  ],
  javascript: [
    '// 阶段 1: 暴力递归',
    'export function f1(n, m) {',
    '  if (n === 0) return 1;',
    '  if (m === 0) return 0;',
    '  const MOD = 1000000007;',
    '  let ways = 0;',
    '  for (let k = 0; k < n; k++) {',
    '    ways = (ways + f1(k, m - 1) * f1(n - 1 - k, m - 1)) % MOD;',
    '  }',
    '  return ways;',
    '}',
  ],
};

export const TREE_COUNT_STAGE2_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    '// 阶段 2: 记忆化搜索 memo[n][m]',
    'public static long f2(int n, int m, long[][] memo) {',
    '    if (n == 0) return 1;',
    '    if (m == 0) return 0;',
    '    if (memo[n][m] != -1) return memo[n][m];',
    '    long ways = 0, MOD = 1000000007;',
    '    for (int k = 0; k < n; k++) {',
    '        ways = (ways + f2(k, m - 1, memo) * f2(n - 1 - k, m - 1, memo)) % MOD;',
    '    }',
    '    return memo[n][m] = ways;',
    '}',
  ],
  cpp: [
    '// 阶段 2: 记忆化搜索',
    'long long f2(int n, int m, vector<vector<long long>>& memo) {',
    '    if (n == 0) return 1;',
    '    if (m == 0) return 0;',
    '    if (memo[n][m] != -1) return memo[n][m];',
    '    long long ways = 0;',
    '    for (int k = 0; k < n; ++k) {',
    '        ways = (ways + f2(k, m - 1, memo) * f2(n - 1 - k, m - 1, memo)) % 1000000007;',
    '    }',
    '    return memo[n][m] = ways;',
    '}',
  ],
  python: [
    '# 阶段 2: 记忆化搜索',
    'def f2(n: int, m: int, memo: dict) -> int:',
    '    if n == 0: return 1',
    '    if m == 0: return 0',
    '    if (n, m) in memo: return memo[(n, m)]',
    '    MOD = 10**9 + 7',
    '    res = sum(f2(k, m - 1, memo) * f2(n - 1 - k, m - 1, memo) for k in range(n)) % MOD',
    '    memo[(n, m)] = res',
    '    return res',
  ],
  javascript: [
    '// 阶段 2: 记忆化搜索',
    'export function f2(n, m, memo) {',
    '  if (n === 0) return 1;',
    '  if (m === 0) return 0;',
    '  if (memo[n][m] !== -1) return memo[n][m];',
    '  let ways = 0;',
    '  for (let k = 0; k < n; k++) {',
    '    ways = (ways + f2(k, m - 1, memo) * f2(n - 1 - k, m - 1, memo)) % 1000000007;',
    '  }',
    '  return memo[n][m] = ways;',
    '}',
  ],
};

export const TREE_COUNT_STAGE3_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    '// 阶段 3: 严格二维表递推 dp[n][m]',
    'public static int compute3(int n, int m) {',
    '    int MOD = 1000000007;',
    '    long[][] dp = new long[n + 1][m + 1];',
    '    for (int j = 0; j <= m; j++) dp[0][j] = 1;',
    '    for (int j = 1; j <= m; j++) {',
    '        for (int i = 1; i <= n; i++) {',
    '            long sum = 0;',
    '            for (int k = 0; k < i; k++) {',
    '                sum = (sum + dp[k][j - 1] * dp[i - 1 - k][j - 1]) % MOD;',
    '            }',
    '            dp[i][j] = sum;',
    '        }',
    '    }',
    '    return (int) dp[n][m];',
    '}',
  ],
  cpp: [
    '// 阶段 3: 严格二维表递推',
    'int compute3(int n, int m) {',
    '    const int MOD = 1000000007;',
    '    vector<vector<long long>> dp(n + 1, vector<long long>(m + 1, 0));',
    '    for (int j = 0; j <= m; ++j) dp[0][j] = 1;',
    '    for (int j = 1; j <= m; ++j) {',
    '        for (int i = 1; i <= n; ++i) {',
    '            long long sum = 0;',
    '            for (int k = 0; k < i; ++k) {',
    '                sum = (sum + dp[k][j - 1] * dp[i - 1 - k][j - 1]) % MOD;',
    '            }',
    '            dp[i][j] = sum;',
    '        }',
    '    }',
    '    return dp[n][m];',
    '}',
  ],
  python: [
    '# 阶段 3: 严格二维表递推',
    'def compute3(n: int, m: int) -> int:',
    '    MOD = 10**9 + 7',
    '    dp = [[0] * (m + 1) for _ in range(n + 1)]',
    '    for j in range(m + 1): dp[0][j] = 1',
    '    for j in range(1, m + 1):',
    '        for i in range(1, n + 1):',
    '            dp[i][j] = sum(dp[k][j - 1] * dp[i - 1 - k][j - 1] for k in range(i)) % MOD',
    '    return dp[n][m]',
  ],
  javascript: [
    '// 阶段 3: 严格二维表递推',
    'export function compute3(n, m) {',
    '  const MOD = 1000000007;',
    '  const dp = Array.from({ length: n + 1 }, () => new Array(m + 1).fill(0));',
    '  for (let j = 0; j <= m; j++) dp[0][j] = 1;',
    '  for (let j = 1; j <= m; j++) {',
    '    for (let i = 1; i <= n; i++) {',
    '      let sum = 0;',
    '      for (let k = 0; k < i; k++) {',
    '        sum = (sum + dp[k][j - 1] * dp[i - 1 - k][j - 1]) % MOD;',
    '      }',
    '      dp[i][j] = sum;',
    '    }',
    '  }',
    '  return dp[n][m];',
    '}',
  ],
};

export const TREE_COUNT_STAGE4_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    '// 阶段 4: 列空间压缩 (仅保留两列滚动更新)',
    'public static int compute4(int n, int m) {',
    '    int MOD = 1000000007;',
    '    long[] prev = new long[n + 1];',
    '    long[] curr = new long[n + 1];',
    '    prev[0] = 1; // 高度为0时空树算1种',
    '    for (int j = 1; j <= m; j++) {',
    '        curr[0] = 1;',
    '        for (int i = 1; i <= n; i++) {',
    '            long sum = 0;',
    '            for (int k = 0; k < i; k++) sum = (sum + prev[k] * prev[i - 1 - k]) % MOD;',
    '            curr[i] = sum;',
    '        }',
    '        long[] tmp = prev; prev = curr; curr = tmp;',
    '    }',
    '    return (int) prev[n];',
    '}',
  ],
  cpp: [
    '// 阶段 4: 列空间压缩',
    'int compute4(int n, int m) {',
    '    const int MOD = 1000000007;',
    '    vector<long long> prev(n + 1, 0), curr(n + 1, 0);',
    '    prev[0] = 1;',
    '    for (int j = 1; j <= m; ++j) {',
    '        curr[0] = 1;',
    '        for (int i = 1; i <= n; ++i) {',
    '            long long sum = 0;',
    '            for (int k = 0; k < i; ++k) sum = (sum + prev[k] * prev[i - 1 - k]) % MOD;',
    '            curr[i] = sum;',
    '        }',
    '        prev = curr;',
    '    }',
    '    return prev[n];',
    '}',
  ],
  python: [
    '# 阶段 4: 两列滚动空间优化',
    'def compute4(n: int, m: int) -> int:',
    '    MOD = 10**9 + 7',
    '    prev = [1] + [0] * n',
    '    for j in range(1, m + 1):',
    '        curr = [1] + [0] * n',
    '        for i in range(1, n + 1):',
    '            curr[i] = sum(prev[k] * prev[i - 1 - k] for k in range(i)) % MOD',
    '        prev = curr',
    '    return prev[n]',
  ],
  javascript: [
    '// 阶段 4: 两列滚动空间优化',
    'export function compute4(n, m) {',
    '  const MOD = 1000000007;',
    '  let prev = new Array(n + 1).fill(0);',
    '  prev[0] = 1;',
    '  for (let j = 1; j <= m; j++) {',
    '    const curr = new Array(n + 1).fill(0);',
    '    curr[0] = 1;',
    '    for (let i = 1; i <= n; i++) {',
    '      let sum = 0;',
    '      for (let k = 0; k < i; k++) sum = (sum + prev[k] * prev[i - 1 - k]) % MOD;',
    '      curr[i] = sum;',
    '    }',
    '    prev = curr;',
    '  }',
    '  return prev[n];',
    '}',
  ],
};

// ==========================================
// 6. Code06 矩阵中的最长递增路径 (LeetCode 329)
// ==========================================
export const LIP_STAGE1_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    '// 阶段 1: 暴力网格 DFS 路径深度探索',
    'public static int longestIncreasingPath1(int[][] matrix) {',
    '    int m = matrix.length, n = matrix[0].length, max = 0;',
    '    for (int i = 0; i < m; i++) {',
    '        for (int j = 0; j < n; j++) {',
    '            max = Math.max(max, dfs1(matrix, i, j));',
    '        }',
    '    }',
    '    return max;',
    '}',
    'private static int dfs1(int[][] g, int i, int j) {',
    '    int ans = 1, m = g.length, n = g[0].length;',
    '    int[][] dirs = {{-1, 0}, {1, 0}, {0, -1}, {0, 1}};',
    '    for (int[] d : dirs) {',
    '        int ni = i + d[0], nj = j + d[1];',
    '        if (ni >= 0 && ni < m && nj >= 0 && nj < n && g[ni][nj] > g[i][j]) {',
    '            ans = Math.max(ans, 1 + dfs1(g, ni, nj));',
    '        }',
    '    }',
    '    return ans;',
    '}',
  ],
  cpp: [
    '// 阶段 1: 暴力网格 DFS',
    'int dfs1(const vector<vector<int>>& g, int i, int j) {',
    '    int ans = 1, m = g.size(), n = g[0].size();',
    '    int dirs[5] = {-1, 0, 1, 0, -1};',
    '    for (int d = 0; d < 4; ++d) {',
    '        int ni = i + dirs[d], nj = j + dirs[d + 1];',
    '        if (ni >= 0 && ni < m && nj >= 0 && nj < n && g[ni][nj] > g[i][j]) {',
    '            ans = max(ans, 1 + dfs1(g, ni, nj));',
    '        }',
    '    }',
    '    return ans;',
    '}',
  ],
  python: [
    '# 阶段 1: 暴力网格 DFS',
    'def dfs1(g, i, j):',
    '    ans = 1',
    '    for di, dj in ((-1,0), (1,0), (0,-1), (0,1)):',
    '        ni, nj = i + di, j + dj',
    '        if 0 <= ni < len(g) and 0 <= nj < len(g[0]) and g[ni][nj] > g[i][j]:',
    '            ans = max(ans, 1 + dfs1(g, ni, nj))',
    '    return ans',
  ],
  javascript: [
    '// 阶段 1: 暴力网格 DFS',
    'function dfs1(g, i, j) {',
    '  let ans = 1;',
    '  const dirs = [[-1,0], [1,0], [0,-1], [0,1]];',
    '  for (const [di, dj] of dirs) {',
    '    const ni = i + di, nj = j + dj;',
    '    if (ni >= 0 && ni < g.length && nj >= 0 && nj < g[0].length && g[ni][nj] > g[i][j]) {',
    '      ans = Math.max(ans, 1 + dfs1(g, ni, nj));',
    '    }',
    '  }',
    '  return ans;',
    '}',
  ],
};

export const LIP_STAGE2_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    '// 阶段 2: 记忆化搜索 (天然 DAG 无后效性)',
    'public static int longestIncreasingPath2(int[][] matrix) {',
    '    int m = matrix.length, n = matrix[0].length, max = 0;',
    '    int[][] dp = new int[m][n];',
    '    for (int i = 0; i < m; i++) {',
    '        for (int j = 0; j < n; j++) {',
    '            max = Math.max(max, dfs2(matrix, i, j, dp));',
    '        }',
    '    }',
    '    return max;',
    '}',
    'private static int dfs2(int[][] g, int i, int j, int[][] dp) {',
    '    if (dp[i][j] != 0) return dp[i][j];',
    '    int ans = 1, m = g.length, n = g[0].length;',
    '    int[][] dirs = {{-1, 0}, {1, 0}, {0, -1}, {0, 1}};',
    '    for (int[] d : dirs) {',
    '        int ni = i + d[0], nj = j + d[1];',
    '        if (ni >= 0 && ni < m && nj >= 0 && nj < n && g[ni][nj] > g[i][j]) {',
    '            ans = Math.max(ans, 1 + dfs2(g, ni, nj, dp));',
    '        }',
    '    }',
    '    return dp[i][j] = ans;',
    '}',
  ],
  cpp: [
    '// 阶段 2: 记忆化搜索',
    'int dfs2(const vector<vector<int>>& g, int i, int j, vector<vector<int>>& dp) {',
    '    if (dp[i][j]) return dp[i][j];',
    '    int ans = 1, m = g.size(), n = g[0].size();',
    '    int dirs[5] = {-1, 0, 1, 0, -1};',
    '    for (int d = 0; d < 4; ++d) {',
    '        int ni = i + dirs[d], nj = j + dirs[d + 1];',
    '        if (ni >= 0 && ni < m && nj >= 0 && nj < n && g[ni][nj] > g[i][j]) {',
    '            ans = max(ans, 1 + dfs2(g, ni, nj, dp));',
    '        }',
    '    }',
    '    return dp[i][j] = ans;',
    '}',
  ],
  python: [
    '# 阶段 2: 记忆化搜索',
    'def dfs2(g, i, j, dp):',
    '    if dp[i][j]: return dp[i][j]',
    '    ans = 1',
    '    for di, dj in ((-1,0), (1,0), (0,-1), (0,1)):',
    '        ni, nj = i + di, j + dj',
    '        if 0 <= ni < len(g) and 0 <= nj < len(g[0]) and g[ni][nj] > g[i][j]:',
    '            ans = max(ans, 1 + dfs2(g, ni, nj, dp))',
    '    dp[i][j] = ans',
    '    return ans',
  ],
  javascript: [
    '// 阶段 2: 记忆化搜索',
    'function dfs2(g, i, j, dp) {',
    '  if (dp[i][j] !== 0) return dp[i][j];',
    '  let ans = 1;',
    '  const dirs = [[-1,0], [1,0], [0,-1], [0,1]];',
    '  for (const [di, dj] of dirs) {',
    '    const ni = i + di, nj = j + dj;',
    '    if (ni >= 0 && ni < g.length && nj >= 0 && nj < g[0].length && g[ni][nj] > g[i][j]) {',
    '      ans = Math.max(ans, 1 + dfs2(g, ni, nj, dp));',
    '    }',
    '  }',
    '  return dp[i][j] = ans;',
    '}',
  ],
};

export const LIP_STAGE3_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    '// 阶段 3: 拓扑排序/DAG分层推演 (统计出度，从出度为0的汇点反推)',
    'public static int longestIncreasingPath3(int[][] matrix) {',
    '    int m = matrix.length, n = matrix[0].length;',
    '    int[][] outdegree = new int[m][n];',
    '    int[][] dirs = {{-1, 0}, {1, 0}, {0, -1}, {0, 1}};',
    '    for (int i = 0; i < m; i++) {',
    '        for (int j = 0; j < n; j++) {',
    '            for (int[] d : dirs) {',
    '                int ni = i + d[0], nj = j + d[1];',
    '                if (ni >= 0 && ni < m && nj >= 0 && nj < n && matrix[ni][nj] > matrix[i][j]) outdegree[i][j]++;',
    '            }',
    '        }',
    '    }',
    '    Queue<int[]> queue = new LinkedList<>();',
    '    for (int i = 0; i < m; i++) for (int j = 0; j < n; j++) if (outdegree[i][j] == 0) queue.offer(new int[]{i, j});',
    '    int level = 0;',
    '    while (!queue.isEmpty()) {',
    '        level++;',
    '        int size = queue.size();',
    '        for (int s = 0; s < size; s++) {',
    '            int[] cur = queue.poll();',
    '            for (int[] d : dirs) {',
    '                int ni = cur[0] + d[0], nj = cur[1] + d[1];',
    '                if (ni >= 0 && ni < m && nj >= 0 && nj < n && matrix[cur[0]][cur[1]] > matrix[ni][nj]) {',
    '                    if (--outdegree[ni][nj] == 0) queue.offer(new int[]{ni, nj});',
    '                }',
    '            }',
    '        }',
    '    }',
    '    return level;',
    '}',
  ],
  cpp: [
    '// 阶段 3: 拓扑排序推演',
    'int longestIncreasingPath3(vector<vector<int>>& matrix) {',
    '    int m = matrix.size(), n = matrix[0].size();',
    '    vector<vector<int>> outdegree(m, vector<int>(n, 0));',
    '    int dirs[4][2] = {{-1, 0}, {1, 0}, {0, -1}, {0, 1}};',
    '    for (int i = 0; i < m; i++) {',
    '        for (int j = 0; j < n; j++) {',
    '            for (auto& d : dirs) {',
    '                int ni = i + d[0], nj = j + d[1];',
    '                if (ni >= 0 && ni < m && nj >= 0 && nj < n && matrix[ni][nj] > matrix[i][j]) outdegree[i][j]++;',
    '            }',
    '        }',
    '    }',
    '    queue<pair<int, int>> q;',
    '    for (int i = 0; i < m; i++) for (int j = 0; j < n; j++) if (outdegree[i][j] == 0) q.push({i, j});',
    '    int level = 0;',
    '    while (!q.empty()) {',
    '        level++;',
    '        int size = q.size();',
    '        for (int s = 0; s < size; s++) {',
    '            auto cur = q.front(); q.pop();',
    '            for (auto& d : dirs) {',
    '                int ni = cur.first + d[0], nj = cur.second + d[1];',
    '                if (ni >= 0 && ni < m && nj >= 0 && nj < n && matrix[cur.first][cur.second] > matrix[ni][nj]) {',
    '                    if (--outdegree[ni][nj] == 0) q.push({ni, nj});',
    '                }',
    '            }',
    '        }',
    '    }',
    '    return level;',
    '}',
  ],
  python: [
    '# 阶段 3: 拓扑排序推演',
    'def longestIncreasingPath3(matrix: list[list[int]]) -> int:',
    '    m, n = len(matrix), len(matrix[0])',
    '    outdegree = [[0] * n for _ in range(m)]',
    '    dirs = [(-1, 0), (1, 0), (0, -1), (0, 1)]',
    '    for i in range(m):',
    '        for j in range(n):',
    '            for di, dj in dirs:',
    '                ni, nj = i + di, j + dj',
    '                if 0 <= ni < m and 0 <= nj < n and matrix[ni][nj] > matrix[i][j]: outdegree[i][j] += 1',
    '    queue = [(i, j) for i in range(m) for j in range(n) if outdegree[i][j] == 0]',
    '    level = 0',
    '    while queue:',
    '        level += 1',
    '        nxt = []',
    '        for r, c in queue:',
    '            for di, dj in dirs:',
    '                ni, nj = r + di, c + dj',
    '                if 0 <= ni < m and 0 <= nj < n and matrix[r][c] > matrix[ni][nj]:',
    '                    outdegree[ni][nj] -= 1',
    '                    if outdegree[ni][nj] == 0: nxt.append((ni, nj))',
    '        queue = nxt',
    '    return level',
  ],
  javascript: [
    '// 阶段 3: 拓扑排序推演',
    'export function longestIncreasingPath3(matrix) {',
    '  const m = matrix.length, n = matrix[0].length;',
    '  const outdegree = Array.from({ length: m }, () => new Array(n).fill(0));',
    '  const dirs = [[-1, 0], [1, 0], [0, -1], [0, 1]];',
    '  for (let i = 0; i < m; i++) {',
    '    for (let j = 0; j < n; j++) {',
    '      for (const [di, dj] of dirs) {',
    '        const ni = i + di, nj = j + dj;',
    '        if (ni >= 0 && ni < m && nj >= 0 && nj < n && matrix[ni][nj] > matrix[i][j]) outdegree[i][j]++;',
    '      }',
    '    }',
    '  }',
    '  let queue = [];',
    '  for (let i = 0; i < m; i++) for (let j = 0; j < n; j++) if (outdegree[i][j] === 0) queue.push([i, j]);',
    '  let level = 0;',
    '  while (queue.length > 0) {',
    '    level++;',
    '    const nxt = [];',
    '    for (const [r, c] of queue) {',
    '      for (const [di, dj] of dirs) {',
    '        const ni = r + di, nj = c + dj;',
    '        if (ni >= 0 && ni < m && nj >= 0 && nj < n && matrix[r][c] > matrix[ni][nj]) {',
    '          if (--outdegree[ni][nj] === 0) nxt.push([ni, nj]);',
    '        }',
    '      }',
    '    }',
    '    queue = nxt;',
    '  }',
    '  return level;',
    '}',
  ],
};

export const LIP_STAGE4_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    '// 阶段 4: 最长递增路径重构与沙盘追踪',
    'public static List<int[]> reconstructLongestPath(int[][] matrix, int[][] dp) {',
    '    int m = matrix.length, n = matrix[0].length;',
    '    int maxVal = 0, bi = 0, bj = 0;',
    '    for (int i = 0; i < m; i++) {',
    '        for (int j = 0; j < n; j++) {',
    '            if (dp[i][j] > maxVal) { maxVal = dp[i][j]; bi = i; bj = j; }',
    '        }',
    '    }',
    '    List<int[]> path = new ArrayList<>();',
    '    path.add(new int[]{bi, bj});',
    '    int[][] dirs = {{-1, 0}, {1, 0}, {0, -1}, {0, 1}};',
    '    while (dp[bi][bj] > 1) {',
    '        for (int[] d : dirs) {',
    '            int ni = bi + d[0], nj = bj + d[1];',
    '            if (ni >= 0 && ni < m && nj >= 0 && nj < n && matrix[ni][nj] > matrix[bi][bj] && dp[ni][nj] == dp[bi][bj] - 1) {',
    '                bi = ni; bj = nj;',
    '                path.add(new int[]{bi, bj});',
    '                break;',
    '            }',
    '        }',
    '    }',
    '    return path;',
    '}',
  ],
  cpp: [
    '// 阶段 4: 路径重构',
    'vector<pair<int, int>> reconstructPath(const vector<vector<int>>& matrix, const vector<vector<int>>& dp) {',
    '    int m = matrix.size(), n = matrix[0].size();',
    '    int maxVal = 0, bi = 0, bj = 0;',
    '    for (int i = 0; i < m; i++) {',
    '        for (int j = 0; j < n; j++) {',
    '            if (dp[i][j] > maxVal) { maxVal = dp[i][j]; bi = i; bj = j; }',
    '        }',
    '    }',
    '    vector<pair<int, int>> path;',
    '    path.push_back({bi, bj});',
    '    int dirs[4][2] = {{-1, 0}, {1, 0}, {0, -1}, {0, 1}};',
    '    while (dp[bi][bj] > 1) {',
    '        for (auto& d : dirs) {',
    '            int ni = bi + d[0], nj = bj + d[1];',
    '            if (ni >= 0 && ni < m && nj >= 0 && nj < n && matrix[ni][nj] > matrix[bi][bj] && dp[ni][nj] == dp[bi][bj] - 1) {',
    '                bi = ni; bj = nj;',
    '                path.push_back({bi, bj});',
    '                break;',
    '            }',
    '        }',
    '    }',
    '    return path;',
    '}',
  ],
  python: [
    '# 阶段 4: 路径回溯重构',
    'def reconstructPath(matrix, dp):',
    '    m, n = len(matrix), len(matrix[0])',
    '    maxVal, bi, bj = 0, 0, 0',
    '    for i in range(m):',
    '        for j in range(n):',
    '            if dp[i][j] > maxVal: maxVal, bi, bj = dp[i][j], i, j',
    '    path = [(bi, bj)]',
    '    dirs = [(-1, 0), (1, 0), (0, -1), (0, 1)]',
    '    while dp[bi][bj] > 1:',
    '        for di, dj in dirs:',
    '            ni, nj = bi + di, bj + dj',
    '            if 0 <= ni < m and 0 <= nj < n and matrix[ni][nj] > matrix[bi][bj] and dp[ni][nj] == dp[bi][bj] - 1:',
    '                bi, bj = ni, nj',
    '                path.append((bi, bj))',
    '                break',
    '    return path',
  ],
  javascript: [
    '// 阶段 4: 最长路径重构',
    'export function reconstructPath(matrix, dp) {',
    '  const m = matrix.length, n = matrix[0].length;',
    '  let maxVal = 0, bi = 0, bj = 0;',
    '  for (let i = 0; i < m; i++) {',
    '    for (let j = 0; j < n; j++) {',
    '      if (dp[i][j] > maxVal) { maxVal = dp[i][j]; bi = i; bj = j; }',
    '    }',
    '  }',
    '  const path = [[bi, bj]];',
    '  const dirs = [[-1, 0], [1, 0], [0, -1], [0, 1]];',
    '  while (dp[bi][bj] > 1) {',
    '    for (const [di, dj] of dirs) {',
    '      const ni = bi + di, nj = bj + dj;',
    '      if (ni >= 0 && ni < m && nj >= 0 && nj < n && matrix[ni][nj] > matrix[bi][bj] && dp[ni][nj] === dp[bi][bj] - 1) {',
    '        bi = ni; bj = nj;',
    '        path.push([bi, bj]);',
    '        break;',
    '      }',
    '    }',
    '  }',
    '  return path;',
    '}',
  ],
};

// ==========================================
// 语义锚点查找表与解析器
// ==========================================
export type Dp067Kind =
  | 'min-path-sum'
  | 'word-search'
  | 'lcs-forward'
  | 'lps-forward'
  | 'longest-common-subsequence'
  | 'longest-palindromic-subsequence'
  | 'tree-count'
  | 'longest-increasing-path';

export interface ResolvedLineTarget {
  java: number;
  cpp: number;
  python: number;
  javascript: number;
}

const DP067_ANCHOR_MAP: Record<string, ResolvedLineTarget> = {
  // min-path-sum: stage 1
  'min-path-sum:s1:enter': { java: 6, cpp: 2, python: 3, javascript: 3 },
  'min-path-sum:s1:baseOrigin': { java: 7, cpp: 3, python: 4, javascript: 4 },
  'min-path-sum:s1:baseRow0': { java: 8, cpp: 4, python: 5, javascript: 5 },
  'min-path-sum:s1:baseCol0': { java: 9, cpp: 5, python: 6, javascript: 6 },
  'min-path-sum:s1:returnMin': { java: 10, cpp: 6, python: 7, javascript: 7 },

  // min-path-sum: stage 2
  'min-path-sum:s2:init': { java: 6, cpp: 12, python: 12, javascript: 12 },
  'min-path-sum:s2:checkMemo': { java: 9, cpp: 6, python: 5, javascript: 6 },
  'min-path-sum:s2:baseOrigin': { java: 10, cpp: 7, python: 6, javascript: 7 },
  'min-path-sum:s2:baseRow0': { java: 11, cpp: 8, python: 7, javascript: 8 },
  'min-path-sum:s2:baseCol0': { java: 12, cpp: 9, python: 8, javascript: 9 },
  'min-path-sum:s2:memoStore': { java: 14, cpp: 11, python: 10, javascript: 11 },

  // min-path-sum: stage 3
  'min-path-sum:s3:origin': { java: 5, cpp: 5, python: 5, javascript: 5 },
  'min-path-sum:s3:firstRow': { java: 6, cpp: 6, python: 6, javascript: 6 },
  'min-path-sum:s3:firstCol': { java: 7, cpp: 7, python: 7, javascript: 7 },
  'min-path-sum:s3:innerLoop': { java: 10, cpp: 9, python: 9, javascript: 9 },
  'min-path-sum:s3:returnAns': { java: 13, cpp: 12, python: 11, javascript: 12 },

  // min-path-sum: stage 4
  'min-path-sum:s4:init': { java: 5, cpp: 5, python: 5, javascript: 5 },
  'min-path-sum:s4:firstRow': { java: 6, cpp: 6, python: 6, javascript: 6 },
  'min-path-sum:s4:rowLoop': { java: 7, cpp: 7, python: 7, javascript: 7 },
  'min-path-sum:s4:firstCol': { java: 8, cpp: 8, python: 8, javascript: 8 },
  'min-path-sum:s4:colLoop': { java: 10, cpp: 10, python: 10, javascript: 10 },
  'min-path-sum:s4:returnAns': { java: 13, cpp: 13, python: 11, javascript: 13 },

  // word-search: stage 1
  'word-search:s1:entry': { java: 2, cpp: 2, python: 2, javascript: 2 },
  'word-search:s1:dimensions': { java: 3, cpp: 3, python: 3, javascript: 3 },
  'word-search:s1:allocVisited': { java: 4, cpp: 4, python: 4, javascript: 4 },
  'word-search:s1:outerI': { java: 5, cpp: 5, python: 5, javascript: 5 },
  'word-search:s1:outerJ': { java: 6, cpp: 6, python: 6, javascript: 6 },
  'word-search:s1:callDfs': { java: 7, cpp: 7, python: 7, javascript: 7 },
  'word-search:s1:returnFalse': { java: 10, cpp: 10, python: 10, javascript: 10 },
  'word-search:s1:dfsEntry': { java: 12, cpp: 12, python: 12, javascript: 12 },
  'word-search:s1:checkTargetFound': { java: 13, cpp: 13, python: 13, javascript: 13 },
  'word-search:s1:checkBounds': { java: 14, cpp: 14, python: 14, javascript: 14 },
  'word-search:s1:checkVisitedOrMismatch': { java: 15, cpp: 15, python: 15, javascript: 15 },
  'word-search:s1:markVisited': { java: 16, cpp: 16, python: 16, javascript: 16 },
  'word-search:s1:branchDown': { java: 17, cpp: 17, python: 17, javascript: 17 },
  'word-search:s1:branchUp': { java: 18, cpp: 18, python: 18, javascript: 18 },
  'word-search:s1:branchRight': { java: 19, cpp: 19, python: 19, javascript: 19 },
  'word-search:s1:branchLeft': { java: 20, cpp: 20, python: 20, javascript: 20 },
  'word-search:s1:backtrackRestore': { java: 21, cpp: 21, python: 21, javascript: 21 },
  'word-search:s1:returnResult': { java: 22, cpp: 22, python: 22, javascript: 22 },

  // word-search: stage 2
  'word-search:s2:entry': { java: 2, cpp: 2, python: 2, javascript: 2 },
  'word-search:s2:allocMemo': { java: 3, cpp: 3, python: 3, javascript: 3 },
  'word-search:s2:outerI': { java: 4, cpp: 4, python: 4, javascript: 4 },
  'word-search:s2:outerJ': { java: 5, cpp: 5, python: 5, javascript: 5 },
  'word-search:s2:callDfs': { java: 6, cpp: 6, python: 6, javascript: 6 },
  'word-search:s2:returnFalse': { java: 9, cpp: 9, python: 9, javascript: 9 },
  'word-search:s2:dfsEntry': { java: 11, cpp: 11, python: 11, javascript: 11 },
  'word-search:s2:checkTarget': { java: 12, cpp: 12, python: 12, javascript: 12 },
  'word-search:s2:checkBounds': { java: 13, cpp: 13, python: 13, javascript: 13 },
  'word-search:s2:checkMemo': { java: 14, cpp: 14, python: 14, javascript: 14 },
  'word-search:s2:markZero': { java: 15, cpp: 15, python: 15, javascript: 15 },
  'word-search:s2:branchDown': { java: 16, cpp: 16, python: 16, javascript: 16 },
  'word-search:s2:branchRight': { java: 17, cpp: 17, python: 17, javascript: 17 },
  'word-search:s2:restore': { java: 18, cpp: 18, python: 18, javascript: 18 },
  'word-search:s2:writeMemo': { java: 19, cpp: 19, python: 19, javascript: 19 },

  // word-search: stage 3
  'word-search:s3:entry': { java: 2, cpp: 2, python: 2, javascript: 2 },
  'word-search:s3:toCharArray': { java: 3, cpp: 3, python: 3, javascript: 3 },
  'word-search:s3:outerI': { java: 4, cpp: 4, python: 4, javascript: 4 },
  'word-search:s3:outerJ': { java: 5, cpp: 5, python: 5, javascript: 5 },
  'word-search:s3:callDfs': { java: 6, cpp: 6, python: 6, javascript: 6 },
  'word-search:s3:returnFalse': { java: 9, cpp: 9, python: 9, javascript: 9 },
  'word-search:s3:dfsEntry': { java: 11, cpp: 11, python: 11, javascript: 11 },
  'word-search:s3:checkTargetFound': { java: 12, cpp: 12, python: 12, javascript: 12 },
  'word-search:s3:checkBoundsAndMismatch': { java: 13, cpp: 13, python: 13, javascript: 13 },
  'word-search:s3:saveTmpChar': { java: 14, cpp: 14, python: 14, javascript: 14 },
  'word-search:s3:markZero': { java: 15, cpp: 15, python: 15, javascript: 15 },
  'word-search:s3:branchDown': { java: 16, cpp: 16, python: 16, javascript: 16 },
  'word-search:s3:branchUp': { java: 17, cpp: 17, python: 17, javascript: 17 },
  'word-search:s3:branchRight': { java: 18, cpp: 18, python: 18, javascript: 18 },
  'word-search:s3:branchLeft': { java: 19, cpp: 19, python: 19, javascript: 19 },
  'word-search:s3:restoreTmpChar': { java: 20, cpp: 20, python: 20, javascript: 20 },
  'word-search:s3:returnResult': { java: 21, cpp: 21, python: 21, javascript: 21 },

  // word-search: stage 4
  'word-search:s4:entry': { java: 2, cpp: 2, python: 2, javascript: 2 },
  'word-search:s4:allocCount': { java: 3, cpp: 3, python: 3, javascript: 3 },
  'word-search:s4:countBoard': { java: 4, cpp: 4, python: 4, javascript: 4 },
  'word-search:s4:toChars': { java: 5, cpp: 5, python: 5, javascript: 5 },
  'word-search:s4:checkWordCount': { java: 6, cpp: 6, python: 6, javascript: 6 },
  'word-search:s4:checkFreq': { java: 6, cpp: 6, python: 6, javascript: 6 },
  'word-search:s4:compareEnds': { java: 7, cpp: 7, python: 7, javascript: 7 },
  'word-search:s4:decideDirection': { java: 7, cpp: 7, python: 7, javascript: 7 },
  'word-search:s4:reverseWord': { java: 8, cpp: 8, python: 8, javascript: 8 },
  'word-search:s4:outerI': { java: 10, cpp: 10, python: 10, javascript: 10 },
  'word-search:s4:outerJ': { java: 11, cpp: 11, python: 11, javascript: 11 },
  'word-search:s4:callDfs': { java: 12, cpp: 12, python: 12, javascript: 12 },
  'word-search:s4:returnFalse': { java: 15, cpp: 15, python: 15, javascript: 15 },
  'word-search:s4:dfsEntry': { java: 17, cpp: 17, python: 17, javascript: 17 },
  'word-search:s4:baseSuccess': { java: 18, cpp: 18, python: 18, javascript: 18 },
  'word-search:s4:checkTargetFound': { java: 18, cpp: 18, python: 18, javascript: 18 },
  'word-search:s4:boundsCheck': { java: 19, cpp: 19, python: 19, javascript: 19 },
  'word-search:s4:checkBoundsAndMismatch': { java: 19, cpp: 19, python: 19, javascript: 19 },
  'word-search:s4:saveTmpChar': { java: 20, cpp: 20, python: 20, javascript: 20 },
  'word-search:s4:saveChar': { java: 20, cpp: 20, python: 20, javascript: 20 },
  'word-search:s4:markZero': { java: 21, cpp: 21, python: 21, javascript: 21 },
  'word-search:s4:branchDown': { java: 22, cpp: 22, python: 22, javascript: 22 },
  'word-search:s4:branchUp': { java: 23, cpp: 23, python: 23, javascript: 23 },
  'word-search:s4:branchRight': { java: 24, cpp: 24, python: 24, javascript: 24 },
  'word-search:s4:branchLeft': { java: 25, cpp: 25, python: 25, javascript: 25 },
  'word-search:s4:restoreTmpChar': { java: 26, cpp: 26, python: 26, javascript: 26 },
  'word-search:s4:restore': { java: 26, cpp: 26, python: 26, javascript: 26 },
  'word-search:s4:returnResult': { java: 27, cpp: 27, python: 27, javascript: 27 },
  'word-search:s4:returnFound': { java: 27, cpp: 27, python: 27, javascript: 27 },

  // tree-count: stage 1
  'tree-count:s1:entry': { java: 2, cpp: 2, python: 2, javascript: 2 },
  'tree-count:s1:enter': { java: 2, cpp: 2, python: 2, javascript: 2 },
  'tree-count:s1:baseN0': { java: 3, cpp: 3, python: 3, javascript: 3 },
  'tree-count:s1:baseM0': { java: 4, cpp: 4, python: 4, javascript: 4 },
  'tree-count:s1:loopK': { java: 7, cpp: 7, python: 6, javascript: 8 },
  'tree-count:s1:returnSum': { java: 9, cpp: 9, python: 6, javascript: 10 },

  // tree-count: stage 2
  'tree-count:s2:entry': { java: 2, cpp: 2, python: 2, javascript: 2 },
  'tree-count:s2:checkMemo': { java: 5, cpp: 5, python: 5, javascript: 5 },
  'tree-count:s2:enumK': { java: 7, cpp: 7, python: 6, javascript: 8 },
  'tree-count:s2:calcSum': { java: 8, cpp: 8, python: 6, javascript: 9 },
  'tree-count:s2:memoStore': { java: 10, cpp: 10, python: 6, javascript: 11 },

  // tree-count: stage 3
  'tree-count:s3:initBase': { java: 5, cpp: 5, python: 5, javascript: 5 },
  'tree-count:s3:colLoop': { java: 6, cpp: 6, python: 6, javascript: 6 },
  'tree-count:s3:calcCell': { java: 12, cpp: 12, python: 8, javascript: 12 },
  'tree-count:s3:returnAns': { java: 15, cpp: 15, python: 9, javascript: 15 },

  // tree-count: stage 4
  'tree-count:s4:initBase': { java: 6, cpp: 4, python: 4, javascript: 5 },
  'tree-count:s4:colLoop': { java: 7, cpp: 5, python: 5, javascript: 6 },
  'tree-count:s4:calcCell': { java: 10, cpp: 9, python: 8, javascript: 10 },
  'tree-count:s4:swapPrev': { java: 12, cpp: 11, python: 9, javascript: 11 },
  'tree-count:s4:returnAns': { java: 14, cpp: 13, python: 10, javascript: 13 },

  // longest-common-subsequence: stage 1
  'longest-common-subsequence:s1:entry': { java: 2, cpp: 2, python: 2, javascript: 2 },
  'longest-common-subsequence:s1:callEntry': { java: 5, cpp: 3, python: 10, javascript: 12 },
  'longest-common-subsequence:s1:fEntry': { java: 7, cpp: 5, python: 3, javascript: 3 },
  'longest-common-subsequence:s1:baseCheck': { java: 8, cpp: 6, python: 4, javascript: 4 },
  'longest-common-subsequence:s1:baseReturn': { java: 9, cpp: 7, python: 5, javascript: 5 },
  'longest-common-subsequence:s1:charCheck': { java: 11, cpp: 9, python: 6, javascript: 7 },
  'longest-common-subsequence:s1:diagMatchCall': { java: 12, cpp: 10, python: 7, javascript: 8 },
  'longest-common-subsequence:s1:branchUpCall': { java: 14, cpp: 12, python: 8, javascript: 10 },
  'longest-common-subsequence:s1:branchLeftCall': { java: 15, cpp: 13, python: 9, javascript: 11 },
  'longest-common-subsequence:s1:combineMaxReturn': { java: 16, cpp: 14, python: 10, javascript: 12 },
  // longest-common-subsequence: stage 2
  'longest-common-subsequence:s2:entry': { java: 2, cpp: 2, python: 2, javascript: 2 },
  'longest-common-subsequence:s2:allocMemo': { java: 4, cpp: 4, python: 4, javascript: 4 },
  'longest-common-subsequence:s2:callEntry': { java: 6, cpp: 5, python: 17, javascript: 18 },
  'longest-common-subsequence:s2:fEntry': { java: 8, cpp: 7, python: 5, javascript: 5 },
  'longest-common-subsequence:s2:baseCheck': { java: 9, cpp: 8, python: 6, javascript: 6 },
  'longest-common-subsequence:s2:baseReturn': { java: 10, cpp: 9, python: 7, javascript: 7 },
  'longest-common-subsequence:s2:memoCheck': { java: 12, cpp: 11, python: 8, javascript: 9 },
  'longest-common-subsequence:s2:memoHitReturn': { java: 13, cpp: 12, python: 9, javascript: 10 },
  'longest-common-subsequence:s2:charCheck': { java: 15, cpp: 14, python: 10, javascript: 12 },
  'longest-common-subsequence:s2:diagMatchCall': { java: 16, cpp: 15, python: 11, javascript: 13 },
  'longest-common-subsequence:s2:branchUpCall': { java: 18, cpp: 17, python: 13, javascript: 15 },
  'longest-common-subsequence:s2:branchLeftCall': { java: 19, cpp: 18, python: 14, javascript: 16 },
  'longest-common-subsequence:s2:combineStoreReturn': { java: 20, cpp: 19, python: 15, javascript: 17 },
  // longest-common-subsequence: stage 3
  'longest-common-subsequence:s3:entry': { java: 2, cpp: 2, python: 2, javascript: 2 },
  'longest-common-subsequence:s3:allocDp': { java: 4, cpp: 4, python: 4, javascript: 4 },
  'longest-common-subsequence:s3:loopI': { java: 5, cpp: 5, python: 5, javascript: 5 },
  'longest-common-subsequence:s3:loopJ': { java: 6, cpp: 6, python: 6, javascript: 6 },
  'longest-common-subsequence:s3:checkChar': { java: 7, cpp: 7, python: 7, javascript: 7 },
  'longest-common-subsequence:s3:diagMatch': { java: 8, cpp: 8, python: 8, javascript: 8 },
  'longest-common-subsequence:s3:branchMax': { java: 10, cpp: 10, python: 10, javascript: 10 },
  'longest-common-subsequence:s3:returnAns': { java: 14, cpp: 14, python: 11, javascript: 14 },
  // longest-common-subsequence: stage 4
  'longest-common-subsequence:s4:entry': { java: 2, cpp: 2, python: 2, javascript: 2 },
  'longest-common-subsequence:s4:allocDp': { java: 4, cpp: 4, python: 4, javascript: 4 },
  'longest-common-subsequence:s4:loopI': { java: 5, cpp: 5, python: 5, javascript: 5 },
  'longest-common-subsequence:s4:initLeftUp': { java: 6, cpp: 6, python: 6, javascript: 6 },
  'longest-common-subsequence:s4:loopJ': { java: 7, cpp: 7, python: 7, javascript: 7 },
  'longest-common-subsequence:s4:backup': { java: 8, cpp: 8, python: 8, javascript: 8 },
  'longest-common-subsequence:s4:checkMatch': { java: 9, cpp: 9, python: 9, javascript: 9 },
  'longest-common-subsequence:s4:diagMatch': { java: 10, cpp: 10, python: 10, javascript: 10 },
  'longest-common-subsequence:s4:mismatchMax': { java: 12, cpp: 12, python: 12, javascript: 12 },
  'longest-common-subsequence:s4:shiftLeftUp': { java: 14, cpp: 14, python: 13, javascript: 14 },
  'longest-common-subsequence:s4:returnAns': { java: 17, cpp: 17, python: 14, javascript: 17 },
  // lcs-forward: stage 1
  'lcs-forward:s1:entry': { java: 2, cpp: 2, python: 2, javascript: 2 },
  'lcs-forward:s1:callEntry': { java: 5, cpp: 3, python: 11, javascript: 11 },
  'lcs-forward:s1:fEntry': { java: 7, cpp: 5, python: 2, javascript: 2 },
  'lcs-forward:s1:baseCheck': { java: 8, cpp: 6, python: 3, javascript: 3 },
  'lcs-forward:s1:baseReturn': { java: 9, cpp: 7, python: 4, javascript: 4 },
  'lcs-forward:s1:charCheck': { java: 11, cpp: 9, python: 5, javascript: 5 },
  'lcs-forward:s1:diagMatchCall': { java: 12, cpp: 10, python: 6, javascript: 6 },
  'lcs-forward:s1:branchDownCall': { java: 14, cpp: 12, python: 7, javascript: 7 },
  'lcs-forward:s1:branchRightCall': { java: 15, cpp: 13, python: 8, javascript: 8 },
  'lcs-forward:s1:combineMaxReturn': { java: 16, cpp: 14, python: 9, javascript: 9 },
  // lcs-forward: stage 2
  'lcs-forward:s2:entry': { java: 2, cpp: 2, python: 2, javascript: 2 },
  'lcs-forward:s2:allocMemo': { java: 4, cpp: 4, python: 4, javascript: 4 },
  'lcs-forward:s2:callEntry': { java: 5, cpp: 5, python: 12, javascript: 12 },
  'lcs-forward:s2:fEntry': { java: 7, cpp: 7, python: 5, javascript: 5 },
  'lcs-forward:s2:baseCheck': { java: 8, cpp: 8, python: 6, javascript: 6 },
  'lcs-forward:s2:memoCheck': { java: 9, cpp: 9, python: 7, javascript: 7 },
  'lcs-forward:s2:charCheck': { java: 10, cpp: 10, python: 8, javascript: 8 },
  'lcs-forward:s2:diagMatchCall': { java: 11, cpp: 11, python: 9, javascript: 9 },
  'lcs-forward:s2:branchDownCall': { java: 13, cpp: 13, python: 10, javascript: 10 },
  'lcs-forward:s2:branchRightCall': { java: 14, cpp: 14, python: 11, javascript: 11 },
  'lcs-forward:s2:combineReturn': { java: 16, cpp: 16, python: 13, javascript: 13 },
  // lcs-forward: stage 3
  'lcs-forward:s3:entry': { java: 2, cpp: 2, python: 2, javascript: 2 },
  'lcs-forward:s3:allocDp': { java: 4, cpp: 4, python: 4, javascript: 4 },
  'lcs-forward:s3:loopI': { java: 5, cpp: 5, python: 5, javascript: 5 },
  'lcs-forward:s3:loopJ': { java: 6, cpp: 6, python: 6, javascript: 6 },
  'lcs-forward:s3:checkChar': { java: 7, cpp: 7, python: 7, javascript: 7 },
  'lcs-forward:s3:diagMatch': { java: 8, cpp: 8, python: 8, javascript: 8 },
  'lcs-forward:s3:branchMax': { java: 10, cpp: 10, python: 10, javascript: 10 },
  'lcs-forward:s3:returnAns': { java: 14, cpp: 14, python: 11, javascript: 14 },

  // longest-palindromic-subsequence: stage 1（顺推/逆推行号一致，共用默认 kind）
  'longest-palindromic-subsequence:s1:entry': { java: 2, cpp: 2, python: 2, javascript: 2 },
  'longest-palindromic-subsequence:s1:enter': { java: 5, cpp: 2, python: 3, javascript: 3 },
  'longest-palindromic-subsequence:s1:base1': { java: 6, cpp: 3, python: 4, javascript: 4 },
  'longest-palindromic-subsequence:s1:base2': { java: 7, cpp: 4, python: 5, javascript: 5 },
  'longest-palindromic-subsequence:s1:match': { java: 8, cpp: 5, python: 6, javascript: 6 },
  'longest-palindromic-subsequence:s1:mismatch': { java: 9, cpp: 6, python: 7, javascript: 7 },

  // longest-palindromic-subsequence: stage 2（逆推行号）
  'longest-palindromic-subsequence:s2:entry': { java: 2, cpp: 2, python: 2, javascript: 2 },
  'longest-palindromic-subsequence:s2:outOfBounds': { java: 6, cpp: 5, python: 4, javascript: 5 },
  'longest-palindromic-subsequence:s2:baseSingle': { java: 7, cpp: 6, python: 5, javascript: 6 },
  'longest-palindromic-subsequence:s2:cacheHit': { java: 6, cpp: 5, python: 4, javascript: 5 },
  'longest-palindromic-subsequence:s2:match': { java: 9, cpp: 8, python: 7, javascript: 8 },
  'longest-palindromic-subsequence:s2:mismatch': { java: 10, cpp: 9, python: 8, javascript: 9 },

  // longest-palindromic-subsequence: stage 3（逆推行号）
  'longest-palindromic-subsequence:s3:entry': { java: 2, cpp: 2, python: 2, javascript: 2 },
  'longest-palindromic-subsequence:s3:alloc': { java: 4, cpp: 4, python: 4, javascript: 4 },
  'longest-palindromic-subsequence:s3:initDiag': { java: 5, cpp: 5, python: 5, javascript: 5 },
  'longest-palindromic-subsequence:s3:lenLoop': { java: 6, cpp: 6, python: 6, javascript: 6 },
  'longest-palindromic-subsequence:s3:lLoop': { java: 7, cpp: 7, python: 7, javascript: 7 },
  'longest-palindromic-subsequence:s3:calcR': { java: 8, cpp: 8, python: 8, javascript: 8 },
  'longest-palindromic-subsequence:s3:match': { java: 9, cpp: 9, python: 9, javascript: 9 },
  'longest-palindromic-subsequence:s3:mismatch': { java: 10, cpp: 10, python: 10, javascript: 10 },
  'longest-palindromic-subsequence:s3:return': { java: 13, cpp: 13, python: 11, javascript: 13 },

  // longest-palindromic-subsequence: stage 4（顺推/逆推行号一致，共用默认 kind）
  'longest-palindromic-subsequence:s4:entry': { java: 2, cpp: 2, python: 2, javascript: 2 },
  'longest-palindromic-subsequence:s4:allocDp': { java: 4, cpp: 4, python: 4, javascript: 4 },
  'longest-palindromic-subsequence:s4:baseDiag': { java: 6, cpp: 6, python: 6, javascript: 6 },
  'longest-palindromic-subsequence:s4:initLeftDown': { java: 7, cpp: 7, python: 7, javascript: 7 },
  'longest-palindromic-subsequence:s4:backup': { java: 9, cpp: 9, python: 9, javascript: 9 },
  'longest-palindromic-subsequence:s4:match': { java: 10, cpp: 10, python: 10, javascript: 10 },
  'longest-palindromic-subsequence:s4:mismatch': { java: 11, cpp: 11, python: 11, javascript: 11 },
  'longest-palindromic-subsequence:s4:shiftLeftDown': { java: 12, cpp: 12, python: 12, javascript: 12 },
  'longest-palindromic-subsequence:s4:returnAns': { java: 15, cpp: 15, python: 15, javascript: 15 },

  // lps-forward: stage 2（顺推行号）
  'lps-forward:s2:entry': { java: 2, cpp: 2, python: 2, javascript: 2 },
  'lps-forward:s2:outOfBounds': { java: 8, cpp: 6, python: 5, javascript: 6 },
  'lps-forward:s2:baseSingle': { java: 9, cpp: 7, python: 6, javascript: 7 },
  'lps-forward:s2:cacheHit': { java: 10, cpp: 8, python: 7, javascript: 8 },
  'lps-forward:s2:match': { java: 11, cpp: 9, python: 8, javascript: 9 },
  'lps-forward:s2:mismatch': { java: 12, cpp: 10, python: 9, javascript: 10 },

  // lps-forward: stage 3（顺推行号）
  'lps-forward:s3:entry': { java: 2, cpp: 2, python: 2, javascript: 2 },
  'lps-forward:s3:alloc': { java: 5, cpp: 4, python: 4, javascript: 4 },
  'lps-forward:s3:outerLoop': { java: 6, cpp: 5, python: 5, javascript: 5 },
  'lps-forward:s3:initDiag': { java: 7, cpp: 6, python: 6, javascript: 6 },
  'lps-forward:s3:len2Check': { java: 8, cpp: 7, python: 7, javascript: 7 },
  'lps-forward:s3:len2Match': { java: 8, cpp: 7, python: 7, javascript: 7 },
  'lps-forward:s3:len2Mismatch': { java: 8, cpp: 7, python: 7, javascript: 7 },
  'lps-forward:s3:innerLoop': { java: 9, cpp: 8, python: 8, javascript: 8 },
  'lps-forward:s3:match': { java: 10, cpp: 9, python: 9, javascript: 9 },
  'lps-forward:s3:mismatch': { java: 11, cpp: 10, python: 10, javascript: 10 },
  'lps-forward:s3:return': { java: 14, cpp: 13, python: 11, javascript: 13 },

  // longest-increasing-path: stage 1
  'longest-increasing-path:s1:entry': { java: 2, cpp: 2, python: 2, javascript: 2 },
  'longest-increasing-path:s1:enter': { java: 11, cpp: 2, python: 2, javascript: 2 },
  'longest-increasing-path:s1:dirsLoop': { java: 16, cpp: 7, python: 6, javascript: 7 },
  'longest-increasing-path:s1:returnAns': { java: 20, cpp: 11, python: 8, javascript: 11 },

  // longest-increasing-path: stage 2
  'longest-increasing-path:s2:entry': { java: 2, cpp: 2, python: 2, javascript: 2 },
  'longest-increasing-path:s2:checkMemo': { java: 13, cpp: 3, python: 3, javascript: 3 },
  'longest-increasing-path:s2:missExpand': { java: 14, cpp: 4, python: 4, javascript: 4 },
  'longest-increasing-path:s2:memoStore': { java: 22, cpp: 12, python: 9, javascript: 12 },

  // longest-increasing-path: stage 3
  'longest-increasing-path:s3:entry': { java: 2, cpp: 2, python: 2, javascript: 2 },
  'longest-increasing-path:s3:initOut': { java: 4, cpp: 4, python: 3, javascript: 4 },
  'longest-increasing-path:s3:calcOut': { java: 10, cpp: 10, python: 9, javascript: 10 },
  'longest-increasing-path:s3:initQueue': { java: 15, cpp: 15, python: 10, javascript: 15 },
  'longest-increasing-path:s3:whileQueue': { java: 17, cpp: 17, python: 12, javascript: 17 },
  'longest-increasing-path:s3:incLevel': { java: 18, cpp: 18, python: 13, javascript: 18 },
  'longest-increasing-path:s3:pollNode': { java: 21, cpp: 21, python: 16, javascript: 20 },
  'longest-increasing-path:s3:relaxNeighbor': { java: 25, cpp: 25, python: 20, javascript: 24 },
  'longest-increasing-path:s3:returnLevel': { java: 30, cpp: 30, python: 22, javascript: 30 },

  // longest-increasing-path: stage 4
  'longest-increasing-path:s4:entry': { java: 2, cpp: 2, python: 2, javascript: 2 },
  'longest-increasing-path:s4:findMax': { java: 7, cpp: 7, python: 7, javascript: 7 },
  'longest-increasing-path:s4:initPath': { java: 11, cpp: 11, python: 8, javascript: 11 },
  'longest-increasing-path:s4:whileLoop': { java: 13, cpp: 13, python: 10, javascript: 13 },
  'longest-increasing-path:s4:findNext': { java: 16, cpp: 16, python: 13, javascript: 16 },
  'longest-increasing-path:s4:stepNext': { java: 18, cpp: 18, python: 15, javascript: 18 },
  'longest-increasing-path:s4:returnPath': { java: 23, cpp: 23, python: 17, javascript: 23 },
};

export function getDp067Anchor(stage: number, kind: Dp067Kind, anchor: string): ResolvedLineTarget {
  const key = `${kind}:s${stage}:${anchor}`;
  const target = DP067_ANCHOR_MAP[key];
  if (target) return target;
  return { java: 1, cpp: 1, python: 1, javascript: 1 };
}
