/**
 * Class 067 从递归入手二维动态规划 4-Stage 演化多语言代码库
 * 涵盖全部 6 题的四阶段代码 (Java, C++, Python, JavaScript)
 */

// ==========================================
// 1. Code01 最小路径和 (LeetCode 64)
// ==========================================
export const MIN_PATH_SUM_STAGE1_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    '// 阶段 1: 暴力递归',
    'public static int minPathSum1(int[][] grid) {',
    '    return f(grid, grid.length - 1, grid[0].length - 1);',
    '}',
    '// f(i, j): 从(0,0)走到(i,j)的最小路径和',
    'public static int f(int[][] g, int i, int j) {',
    '    if (i == 0 && j == 0) return g[0][0];',
    '    if (i == 0) return f(g, 0, j - 1) + g[0][j];',
    '    if (j == 0) return f(g, i - 1, 0) + g[i][0];',
    '    return g[i][j] + Math.min(f(g, i - 1, j), f(g, i, j - 1));',
    '}',
  ],
  cpp: [
    '// 阶段 1: 暴力递归',
    'int f(const vector<vector<int>>& g, int i, int j) {',
    '    if (i == 0 && j == 0) return g[0][0];',
    '    if (i == 0) return f(g, 0, j - 1) + g[0][j];',
    '    if (j == 0) return f(g, i - 1, 0) + g[i][0];',
    '    return g[i][j] + min(f(g, i - 1, j), f(g, i, j - 1));',
    '}',
  ],
  python: [
    '# 阶段 1: 暴力递归',
    'def minPathSum1(grid: list[list[int]]) -> int:',
    '    def f(i, j):',
    '        if i == 0 and j == 0: return grid[0][0]',
    '        if i == 0: return f(0, j - 1) + grid[0][j]',
    '        if j == 0: return f(i - 1, 0) + grid[i][0]',
    '        return grid[i][j] + min(f(i - 1, j), f(i, j - 1))',
    '    return f(len(grid) - 1, len(grid[0]) - 1)',
  ],
  javascript: [
    '// 阶段 1: 暴力递归',
    'export function minPathSum1(grid) {',
    '  function f(i, j) {',
    '    if (i === 0 && j === 0) return grid[0][0];',
    '    if (i === 0) return f(0, j - 1) + grid[0][j];',
    '    if (j === 0) return f(i - 1, 0) + grid[i][0];',
    '    return grid[i][j] + Math.min(f(i - 1, j), f(i, j - 1));',
    '  }',
    '  return f(grid.length - 1, grid[0].length - 1);',
    '}',
  ],
};

export const MIN_PATH_SUM_STAGE2_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    '// 阶段 2: 记忆化搜索',
    'public static int minPathSum2(int[][] grid) {',
    '    int m = grid.length, n = grid[0].length;',
    '    int[][] memo = new int[m][n];',
    '    for (int[] row : memo) Arrays.fill(row, -1);',
    '    return f(grid, m - 1, n - 1, memo);',
    '}',
    'public static int f(int[][] g, int i, int j, int[][] memo) {',
    '    if (memo[i][j] != -1) return memo[i][j];',
    '    if (i == 0 && j == 0) return memo[i][j] = g[0][0];',
    '    if (i == 0) return memo[i][j] = f(g, 0, j - 1, memo) + g[0][j];',
    '    if (j == 0) return memo[i][j] = f(g, i - 1, 0, memo) + g[i][0];',
    '    return memo[i][j] = g[i][j] + Math.min(f(g, i - 1, j, memo), f(g, i, j - 1, memo));',
    '}',
  ],
  cpp: [
    '// 阶段 2: 记忆化搜索',
    'int minPathSum2(vector<vector<int>>& grid) {',
    '    int m = grid.size(), n = grid[0].size();',
    '    vector<vector<int>> memo(m, vector<int>(n, -1));',
    '    auto f = [&](auto& self, int i, int j) -> int {',
    '        if (memo[i][j] != -1) return memo[i][j];',
    '        if (i == 0 && j == 0) return memo[i][j] = grid[0][0];',
    '        if (i == 0) return memo[i][j] = self(self, 0, j - 1) + grid[0][j];',
    '        if (j == 0) return memo[i][j] = self(self, i - 1, 0) + grid[i][0];',
    '        return memo[i][j] = grid[i][j] + min(self(self, i - 1, j), self(self, i, j - 1));',
    '    };',
    '    return f(f, m - 1, n - 1);',
    '}',
  ],
  python: [
    '# 阶段 2: 记忆化搜索',
    'def minPathSum2(grid: list[list[int]]) -> int:',
    '    memo = {}',
    '    def f(i, j):',
    '        if (i, j) in memo: return memo[(i, j)]',
    '        if i == 0 and j == 0: res = grid[0][0]',
    '        elif i == 0: res = f(0, j - 1) + grid[0][j]',
    '        elif j == 0: res = f(i - 1, 0) + grid[i][0]',
    '        else: res = grid[i][j] + min(f(i - 1, j), f(i, j - 1))',
    '        memo[(i, j)] = res',
    '        return res',
    '    return f(len(grid) - 1, len(grid[0]) - 1)',
  ],
  javascript: [
    '// 阶段 2: 记忆化搜索',
    'export function minPathSum2(grid) {',
    '  const m = grid.length, n = grid[0].length;',
    '  const memo = Array.from({ length: m }, () => new Array(n).fill(-1));',
    '  function f(i, j) {',
    '    if (memo[i][j] !== -1) return memo[i][j];',
    '    if (i === 0 && j === 0) return memo[i][j] = grid[0][0];',
    '    if (i === 0) return memo[i][j] = f(0, j - 1) + grid[0][j];',
    '    if (j === 0) return memo[i][j] = f(i - 1, 0) + grid[i][0];',
    '    return memo[i][j] = grid[i][j] + Math.min(f(i - 1, j), f(i, j - 1));',
    '  }',
    '  return f(m - 1, n - 1);',
    '}',
  ],
};

export const MIN_PATH_SUM_STAGE3_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    '// 阶段 3: 严格二维表递推',
    'public static int minPathSum3(int[][] grid) {',
    '    int m = grid.length, n = grid[0].length;',
    '    int[][] dp = new int[m][n];',
    '    dp[0][0] = grid[0][0];',
    '    for (int j = 1; j < n; j++) dp[0][j] = dp[0][j - 1] + grid[0][j];',
    '    for (int i = 1; i < m; i++) dp[i][0] = dp[i - 1][0] + grid[i][0];',
    '    for (int i = 1; i < m; i++) {',
    '        for (int j = 1; j < n; j++) {',
    '            dp[i][j] = Math.min(dp[i - 1][j], dp[i][j - 1]) + grid[i][j];',
    '        }',
    '    }',
    '    return dp[m - 1][n - 1];',
    '}',
  ],
  cpp: [
    '// 阶段 3: 严格二维表递推',
    'int minPathSum3(vector<vector<int>>& grid) {',
    '    int m = grid.size(), n = grid[0].size();',
    '    vector<vector<int>> dp(m, vector<int>(n, 0));',
    '    dp[0][0] = grid[0][0];',
    '    for (int j = 1; j < n; ++j) dp[0][j] = dp[0][j - 1] + grid[0][j];',
    '    for (int i = 1; i < m; ++i) dp[i][0] = dp[i - 1][0] + grid[i][0];',
    '    for (int i = 1; i < m; ++i) {',
    '        for (int j = 1; j < n; ++j) {',
    '            dp[i][j] = min(dp[i - 1][j], dp[i][j - 1]) + grid[i][j];',
    '        }',
    '    }',
    '    return dp[m - 1][n - 1];',
    '}',
  ],
  python: [
    '# 阶段 3: 严格二维表递推',
    'def minPathSum3(grid: list[list[int]]) -> int:',
    '    m, n = len(grid), len(grid[0])',
    '    dp = [[0] * n for _ in range(m)]',
    '    dp[0][0] = grid[0][0]',
    '    for j in range(1, n): dp[0][j] = dp[0][j - 1] + grid[0][j]',
    '    for i in range(1, m): dp[i][0] = dp[i - 1][0] + grid[i][0]',
    '    for i in range(1, m):',
    '        for j in range(1, n):',
    '            dp[i][j] = min(dp[i - 1][j], dp[i][j - 1]) + grid[i][j]',
    '    return dp[m - 1][n - 1]',
  ],
  javascript: [
    '// 阶段 3: 严格二维表递推',
    'export function minPathSum3(grid) {',
    '  const m = grid.length, n = grid[0].length;',
    '  const dp = Array.from({ length: m }, () => new Array(n).fill(0));',
    '  dp[0][0] = grid[0][0];',
    '  for (let j = 1; j < n; j++) dp[0][j] = dp[0][j - 1] + grid[0][j];',
    '  for (let i = 1; i < m; i++) dp[i][0] = dp[i - 1][0] + grid[i][0];',
    '  for (let i = 1; i < m; i++) {',
    '    for (let j = 1; j < n; j++) {',
    '      dp[i][j] = Math.min(dp[i - 1][j], dp[i][j - 1]) + grid[i][j];',
    '    }',
    '  }',
    '  return dp[m - 1][n - 1];',
    '}',
  ],
};

export const MIN_PATH_SUM_STAGE4_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    '// 阶段 4: 空间压缩版 (一维滚动数组)',
    'public static int minPathSum4(int[][] grid) {',
    '    int m = grid.length, n = grid[0].length;',
    '    int[] dp = new int[n];',
    '    dp[0] = grid[0][0];',
    '    for (int j = 1; j < n; j++) dp[j] = dp[j - 1] + grid[0][j];',
    '    for (int i = 1; i < m; i++) {',
    '        dp[0] += grid[i][0];',
    '        for (int j = 1; j < n; j++) {',
    '            dp[j] = Math.min(dp[j], dp[j - 1]) + grid[i][j];',
    '        }',
    '    }',
    '    return dp[n - 1];',
    '}',
  ],
  cpp: [
    '// 阶段 4: 空间压缩版',
    'int minPathSum4(vector<vector<int>>& grid) {',
    '    int m = grid.size(), n = grid[0].size();',
    '    vector<int> dp(n);',
    '    dp[0] = grid[0][0];',
    '    for (int j = 1; j < n; ++j) dp[j] = dp[j - 1] + grid[0][j];',
    '    for (int i = 1; i < m; ++i) {',
    '        dp[0] += grid[i][0];',
    '        for (int j = 1; j < n; ++j) {',
    '            dp[j] = min(dp[j], dp[j - 1]) + grid[i][j];',
    '        }',
    '    }',
    '    return dp[n - 1];',
    '}',
  ],
  python: [
    '# 阶段 4: 空间压缩版',
    'def minPathSum4(grid: list[list[int]]) -> int:',
    '    m, n = len(grid), len(grid[0])',
    '    dp = [0] * n',
    '    dp[0] = grid[0][0]',
    '    for j in range(1, n): dp[j] = dp[j - 1] + grid[0][j]',
    '    for i in range(1, m):',
    '        dp[0] += grid[i][0]',
    '        for j in range(1, n):',
    '            dp[j] = min(dp[j], dp[j - 1]) + grid[i][j]',
    '    return dp[-1]',
  ],
  javascript: [
    '// 阶段 4: 空间压缩版',
    'export function minPathSum4(grid) {',
    '  const m = grid.length, n = grid[0].length;',
    '  const dp = new Array(n).fill(0);',
    '  dp[0] = grid[0][0];',
    '  for (let j = 1; j < n; j++) dp[j] = dp[j - 1] + grid[0][j];',
    '  for (let i = 1; i < m; i++) {',
    '    dp[0] += grid[i][0];',
    '    for (let j = 1; j < n; j++) {',
    '      dp[j] = Math.min(dp[j], dp[j - 1]) + grid[i][j];',
    '    }',
    '  }',
    '  return dp[n - 1];',
    '}',
  ],
};

// ==========================================
// ==========================================
// 2. Code02 单词搜索 (LeetCode 79)
// ==========================================
export const WORD_SEARCH_STAGE1_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    '// 阶段 1: 暴力四向深度优先递归探索 (带 visited 标记)',
    'public static boolean exist1(char[][] board, String word) {',
    '    int m = board.length, n = board[0].length;',
    '    boolean[][] visited = new boolean[m][n];',
    '    for (int i = 0; i < m; i++) {',
    '        for (int j = 0; j < n; j++) {',
    '            if (dfs1(board, word, i, j, 0, visited)) return true;',
    '        }',
    '    }',
    '    return false;',
    '}',
    'private static boolean dfs1(char[][] b, String w, int i, int j, int k, boolean[][] vis) {',
    '    if (k == w.length()) return true;',
    '    if (i < 0 || i >= b.length || j < 0 || j >= b[0].length) return false;',
    '    if (vis[i][j] || b[i][j] != w.charAt(k)) return false;',
    '    vis[i][j] = true;',
    '    boolean found = dfs1(b, w, i + 1, j, k + 1, vis)   // ⬇️ 向下探索',
    '                 || dfs1(b, w, i - 1, j, k + 1, vis)   // ⬆️ 向上探索',
    '                 || dfs1(b, w, i, j + 1, k + 1, vis)   // ➡️ 向右探索',
    '                 || dfs1(b, w, i, j - 1, k + 1, vis);  // ⬅️ 向左探索',
    '    vis[i][j] = false;',
    '    return found;',
    '}',
  ],
  cpp: [
    '// 阶段 1: 暴力四向深度优先递归探索 (带 visited 标记)',
    'bool exist1(vector<vector<char>>& board, string word) {',
    '    int m = board.size(), n = board[0].size();',
    '    vector<vector<bool>> visited(m, vector<bool>(n, false));',
    '    for (int i = 0; i < m; i++) {',
    '        for (int j = 0; j < n; j++) {',
    '            if (dfs1(board, word, i, j, 0, visited)) return true;',
    '        }',
    '    }',
    '    return false;',
    '}',
    'bool dfs1(vector<vector<char>>& b, const string& w, int i, int j, int k, vector<vector<bool>>& vis) {',
    '    if (k == w.size()) return true;',
    '    if (i < 0 || i >= b.size() || j < 0 || j >= b[0].size()) return false;',
    '    if (vis[i][j] || b[i][j] != w[k]) return false;',
    '    vis[i][j] = true;',
    '    bool found = dfs1(b, w, i + 1, j, k + 1, vis)   // ⬇️ 向下探索',
    '              || dfs1(b, w, i - 1, j, k + 1, vis)   // ⬆️ 向上探索',
    '              || dfs1(b, w, i, j + 1, k + 1, vis)   // ➡️ 向右探索',
    '              || dfs1(b, w, i, j - 1, k + 1, vis);  // ⬅️ 向左探索',
    '    vis[i][j] = false;',
    '    return found;',
    '}',
  ],
  python: [
    '# 阶段 1: 暴力四向深度优先递归探索 (带 visited 标记)',
    'def exist1(board: list[list[str]], word: str) -> bool:',
    '    m, n = len(board), len(board[0])',
    '    visited = [[False] * n for _ in range(m)]',
    '    for i in range(m):',
    '        for j in range(n):',
    '            if dfs1(board, word, i, j, 0, visited): return True',
    '        # end j',
    '    # end i',
    '    return False',
    '# 辅助递归',
    'def dfs1(b, w, i, j, k, vis):',
    '    if k == len(w): return True',
    '    if not (0 <= i < len(b) and 0 <= j < len(b[0])): return False',
    '    if vis[i][j] or b[i][j] != w[k]: return False',
    '    vis[i][j] = True',
    '    found = (dfs1(b, w, i + 1, j, k + 1, vis)   # ⬇️ 向下探索',
    '          or dfs1(b, w, i - 1, j, k + 1, vis)   # ⬆️ 向上探索',
    '          or dfs1(b, w, i, j + 1, k + 1, vis)   # ➡️ 向右探索',
    '          or dfs1(b, w, i, j - 1, k + 1, vis))  # ⬅️ 向左探索',
    '    vis[i][j] = False',
    '    return found',
    '# 结束',
  ],
  javascript: [
    '// 阶段 1: 暴力四向深度优先递归探索 (带 visited 标记)',
    'export function exist1(board, word) {',
    '  const m = board.length, n = board[0].length;',
    '  const visited = Array.from({ length: m }, () => new Array(n).fill(false));',
    '  for (let i = 0; i < m; i++) {',
    '    for (let j = 0; j < n; j++) {',
    '      if (dfs1(board, word, i, j, 0, visited)) return true;',
    '    }',
    '  }',
    '  return false;',
    '}',
    'function dfs1(b, w, i, j, k, vis) {',
    '  if (k === w.length) return true;',
    '  if (i < 0 || i >= b.length || j < 0 || j >= b[0].length) return false;',
    '  if (vis[i][j] || b[i][j] !== w[k]) return false;',
    '  vis[i][j] = true;',
    '  const found = dfs1(b, w, i + 1, j, k + 1, vis)   // ⬇️ 向下探索',
    '             || dfs1(b, w, i - 1, j, k + 1, vis)   // ⬆️ 向上探索',
    '             || dfs1(b, w, i, j + 1, k + 1, vis)   // ➡️ 向右探索',
    '             || dfs1(b, w, i, j - 1, k + 1, vis);  // ⬅️ 向左探索',
    '  vis[i][j] = false;',
    '  return found;',
    '}',
  ],
};

export const WORD_SEARCH_STAGE2_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    '// 阶段 2: 记忆化反例剖析 (尝试 memo[i][j][k] 为何导致致命 Bug)',
    'public static boolean existMemoWrong(char[][] b, String w) {',
    '    Boolean[][][] memo = new Boolean[b.length][b[0].length][w.length()];',
    '    for (int i = 0; i < b.length; i++) {',
    '        for (int j = 0; j < b[0].length; j++) {',
    '            if (dfsMemo(b, w, i, j, 0, memo)) return true;',
    '        }',
    '    }',
    '    return false;',
    '}',
    'private static boolean dfsMemo(char[][] b, String w, int i, int j, int k, Boolean[][][] memo) {',
    '    if (k == w.length()) return true;',
    '    if (i < 0 || i >= b.length || j < 0 || j >= b[0].length || b[i][j] != w.charAt(k)) return false;',
    '    if (memo[i][j][k] != null) return memo[i][j][k]; // ⚠️ 错误复用：忽略了历史路径禁区！',
    '    char tmp = b[i][j]; b[i][j] = 0;',
    '    boolean ans = dfsMemo(b, w, i + 1, j, k + 1, memo) // ⬇️ 向下分支',
    '               || dfsMemo(b, w, i, j + 1, k + 1, memo); // ➡️ 向右分支',
    '    b[i][j] = tmp;',
    '    return memo[i][j][k] = ans; // ⚠️ 污染缓存：此处的 ans 是在特定禁区下测得的，不可全局复用！',
    '}',
  ],
  cpp: [
    '// 阶段 2: 记忆化反例剖析 (尝试 memo[i][j][k] 为何导致致命 Bug)',
    'bool existMemoWrong(vector<vector<char>>& b, string w) {',
    '    vector<vector<vector<int>>> memo(b.size(), vector<vector<int>>(b[0].size(), vector<int>(w.size(), -1)));',
    '    for (int i = 0; i < b.size(); i++) {',
    '        for (int j = 0; j < b[0].size(); j++) {',
    '            if (dfsMemo(b, w, i, j, 0, memo)) return true;',
    '        }',
    '    }',
    '    return false;',
    '}',
    'bool dfsMemo(vector<vector<char>>& b, const string& w, int i, int j, int k, vector<vector<vector<int>>>& memo) {',
    '    if (k == w.size()) return true;',
    '    if (i < 0 || i >= b.size() || j < 0 || j >= b[0].size() || b[i][j] != w[k]) return false;',
    '    if (memo[i][j][k] != -1) return memo[i][j][k]; // ⚠️ 错误复用：忽略了历史路径禁区！',
    '    char tmp = b[i][j]; b[i][j] = 0;',
    '    bool ans = dfsMemo(b, w, i + 1, j, k + 1, memo) // ⬇️ 向下分支',
    '            || dfsMemo(b, w, i, j + 1, k + 1, memo); // ➡️ 向右分支',
    '    b[i][j] = tmp;',
    '    return memo[i][j][k] = ans; // ⚠️ 污染缓存：此处的 ans 是在特定禁区下测得的，不可全局复用！',
    '}',
  ],
  python: [
    '# 阶段 2: 记忆化反例剖析 (尝试 memo[i][j][k] 为何导致致命 Bug)',
    'def existMemoWrong(b: list[list[str]], w: str) -> bool:',
    '    memo = {}',
    '    for i in range(len(b)):',
    '        for j in range(len(b[0])):',
    '            if dfsMemo(b, w, i, j, 0, memo): return True',
    '        # end j',
    '    # end i',
    '    return False',
    '# 辅助递归函数',
    'def dfsMemo(b, w, i, j, k, memo):',
    '    if k == len(w): return True',
    '    if not (0 <= i < len(b) and 0 <= j < len(b[0])) or b[i][j] != w[k]: return False',
    '    if (i, j, k) in memo: return memo[(i, j, k)] # ⚠️ 错误复用：忽略了历史路径禁区！',
    '    tmp = b[i][j]; b[i][j] = 0',
    '    ans = dfsMemo(b, w, i + 1, j, k + 1, memo) \\',
    '       or dfsMemo(b, w, i, j + 1, k + 1, memo) # ⬇️ 向下 / ➡️ 向右分支',
    '    b[i][j] = tmp',
    '    memo[(i, j, k)] = ans; return ans # ⚠️ 污染缓存：此处的 ans 是在特定禁区下测得的，不可全局复用！',
    '# end dfsMemo',
  ],
  javascript: [
    '// 阶段 2: 记忆化反例剖析 (尝试 memo[i][j][k] 为何导致致命 Bug)',
    'export function existMemoWrong(b, w) {',
    '  const memo = new Map();',
    '  for (let i = 0; i < b.length; i++) {',
    '    for (let j = 0; j < b[0].length; j++) {',
    '      if (dfsMemo(b, w, i, j, 0, memo)) return true;',
    '    }',
    '  }',
    '  return false;',
    '}',
    'function dfsMemo(b, w, i, j, k, memo) {',
    '  if (k === w.length) return true;',
    '  if (i < 0 || i >= b.length || j < 0 || j >= b[0].length || b[i][j] !== w[k]) return false;',
    '  if (memo.has(`${i},${j},${k}`)) return memo.get(`${i},${j},${k}`); // ⚠️ 错误复用：忽略了历史路径禁区！',
    '  const tmp = b[i][j]; b[i][j] = 0;',
    '  const ans = dfsMemo(b, w, i + 1, j, k + 1, memo) // ⬇️ 向下分支',
    '           || dfsMemo(b, w, i, j + 1, k + 1, memo); // ➡️ 向右分支',
    '  b[i][j] = tmp;',
    '  memo.set(`${i},${j},${k}`, ans); return ans; // ⚠️ 污染缓存：此处的 ans 是在特定禁区下测得的！',
    '}',
  ],
};

export const WORD_SEARCH_STAGE3_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    '// 阶段 3: 原地修改字符打标与现场恢复 (空间降至 O(1))',
    'public static boolean exist3(char[][] board, String word) {',
    '    char[] w = word.toCharArray();',
    '    for (int i = 0; i < board.length; i++) {',
    '        for (int j = 0; j < board[0].length; j++) {',
    '            if (dfs3(board, w, i, j, 0)) return true;',
    '        }',
    '    }',
    '    return false;',
    '}',
    'private static boolean dfs3(char[][] b, char[] w, int i, int j, int k) {',
    '    if (k == w.length) return true;',
    '    if (i < 0 || i >= b.length || j < 0 || j >= b[0].length || b[i][j] != w[k]) return false;',
    '    char tmp = b[i][j];',
    '    b[i][j] = 0; // 原地打标占位',
    '    boolean found = dfs3(b, w, i + 1, j, k + 1)   // ⬇️ 向下探索',
    '                 || dfs3(b, w, i - 1, j, k + 1)   // ⬆️ 向上探索',
    '                 || dfs3(b, w, i, j + 1, k + 1)   // ➡️ 向右探索',
    '                 || dfs3(b, w, i, j - 1, k + 1);  // ⬅️ 向左探索',
    '    b[i][j] = tmp; // 回溯恢复现场',
    '    return found;',
    '}',
  ],
  cpp: [
    '// 阶段 3: 原地修改字符打标与现场恢复 (空间降至 O(1))',
    'bool exist3(vector<vector<char>>& board, string word) {',
    '    string w = word;',
    '    for (int i = 0; i < board.size(); i++) {',
    '        for (int j = 0; j < board[0].size(); j++) {',
    '            if (dfs3(board, w, i, j, 0)) return true;',
    '        }',
    '    }',
    '    return false;',
    '}',
    'bool dfs3(vector<vector<char>>& b, const string& w, int i, int j, int k) {',
    '    if (k == w.size()) return true;',
    '    if (i < 0 || i >= b.size() || j < 0 || j >= b[0].size() || b[i][j] != w[k]) return false;',
    '    char tmp = b[i][j];',
    '    b[i][j] = 0;',
    '    bool found = dfs3(b, w, i + 1, j, k + 1)   // ⬇️ 向下探索',
    '              || dfs3(b, w, i - 1, j, k + 1)   // ⬆️ 向上探索',
    '              || dfs3(b, w, i, j + 1, k + 1)   // ➡️ 向右探索',
    '              || dfs3(b, w, i, j - 1, k + 1);  // ⬅️ 向左探索',
    '    b[i][j] = tmp;',
    '    return found;',
    '}',
  ],
  python: [
    '# 阶段 3: 原地修改字符打标与现场恢复 (空间降至 O(1))',
    'def exist3(board: list[list[str]], word: str) -> bool:',
    '    w = list(word)',
    '    for i in range(len(board)):',
    '        for j in range(len(board[0])):',
    '            if dfs3(board, w, i, j, 0): return True',
    '        # end j',
    '    # end i',
    '    return False',
    '# 辅助递归',
    'def dfs3(b, w, i, j, k):',
    '    if k == len(w): return True',
    '    if not (0 <= i < len(b) and 0 <= j < len(b[0])) or b[i][j] != w[k]: return False',
    '    tmp = b[i][j]',
    '    b[i][j] = 0',
    '    found = (dfs3(b, w, i + 1, j, k + 1)   # ⬇️ 向下探索',
    '          or dfs3(b, w, i - 1, j, k + 1)   # ⬆️ 向上探索',
    '          or dfs3(b, w, i, j + 1, k + 1)   # ➡️ 向右探索',
    '          or dfs3(b, w, i, j - 1, k + 1))  # ⬅️ 向左探索',
    '    b[i][j] = tmp',
    '    return found',
    '# end dfs3',
  ],
  javascript: [
    '// 阶段 3: 原地修改字符打标与现场恢复 (空间降至 O(1))',
    'export function exist3(board, word) {',
    '  const w = word.split(\'\');',
    '  for (let i = 0; i < board.length; i++) {',
    '    for (let j = 0; j < board[0].length; j++) {',
    '      if (dfs3(board, w, i, j, 0)) return true;',
    '    }',
    '  }',
    '  return false;',
    '}',
    'function dfs3(b, w, i, j, k) {',
    '  if (k === w.length) return true;',
    '  if (i < 0 || i >= b.length || j < 0 || j >= b[0].length || b[i][j] !== w[k]) return false;',
    '  const tmp = b[i][j];',
    '  b[i][j] = 0;',
    '  const found = dfs3(b, w, i + 1, j, k + 1)   // ⬇️ 向下探索',
    '             || dfs3(b, w, i - 1, j, k + 1)   // ⬆️ 向上探索',
    '             || dfs3(b, w, i, j + 1, k + 1)   // ➡️ 向右探索',
    '             || dfs3(b, w, i, j - 1, k + 1);  // ⬅️ 向左探索',
    '  b[i][j] = tmp;',
    '  return found;',
    '}',
  ],
};

export const WORD_SEARCH_STAGE4_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    '// 阶段 4: 词频剪枝与双向/反向搜索优化',
    'public static boolean exist4(char[][] board, String word) {',
    '    int[] count = new int[128];',
    '    for (char[] row : board) for (char c : row) count[c]++;',
    '    char[] w = word.toCharArray();',
    '    for (char c : w) if (--count[c] < 0) return false; // 字母不够直接秒拒',
    '    if (count[w[w.length - 1]] < count[w[0]]) {',
    '        w = new StringBuilder(word).reverse().toString().toCharArray();',
    '    }',
    '    for (int i = 0; i < board.length; i++) {',
    '        for (int j = 0; j < board[0].length; j++) {',
    '            if (dfs4(board, w, i, j, 0)) return true;',
    '        }',
    '    }',
    '    return false;',
    '}',
    'private static boolean dfs4(char[][] b, char[] w, int i, int j, int k) {',
    '    if (k == w.length) return true;',
    '    if (i < 0 || i >= b.length || j < 0 || j >= b[0].length || b[i][j] != w[k]) return false;',
    '    char tmp = b[i][j];',
    '    b[i][j] = 0; // 原地打标占位',
    '    boolean found = dfs4(b, w, i + 1, j, k + 1)   // ⬇️ 向下探索',
    '                 || dfs4(b, w, i - 1, j, k + 1)   // ⬆️ 向上探索',
    '                 || dfs4(b, w, i, j + 1, k + 1)   // ➡️ 向右探索',
    '                 || dfs4(b, w, i, j - 1, k + 1);  // ⬅️ 向左探索',
    '    b[i][j] = tmp; // 回溯恢复现场',
    '    return found;',
    '}',
  ],
  cpp: [
    '// 阶段 4: 词频统计剪枝与方向倒置',
    'bool exist4(vector<vector<char>>& board, string word) {',
    '    vector<int> count(128, 0);',
    '    for (const auto& row : board) for (char c : row) count[c]++;',
    '    string w = word;',
    '    for (char c : w) if (--count[c] < 0) return false;',
    '    if (count[w.back()] < count[w.front()]) {',
    '        reverse(w.begin(), w.end());',
    '    }',
    '    for (int i = 0; i < board.size(); i++) {',
    '        for (int j = 0; j < board[0].size(); j++) {',
    '            if (dfs4(board, w, i, j, 0)) return true;',
    '        }',
    '    }',
    '    return false;',
    '}',
    'bool dfs4(vector<vector<char>>& b, const string& w, int i, int j, int k) {',
    '    if (k == w.size()) return true;',
    '    if (i < 0 || i >= b.size() || j < 0 || j >= b[0].size() || b[i][j] != w[k]) return false;',
    '    char tmp = b[i][j];',
    '    b[i][j] = 0;',
    '    bool found = dfs4(b, w, i + 1, j, k + 1)   // ⬇️ 向下探索',
    '              || dfs4(b, w, i - 1, j, k + 1)   // ⬆️ 向上探索',
    '              || dfs4(b, w, i, j + 1, k + 1)   // ➡️ 向右探索',
    '              || dfs4(b, w, i, j - 1, k + 1);  // ⬅️ 向左探索',
    '    b[i][j] = tmp;',
    '    return found;',
    '}',
  ],
  python: [
    '# 阶段 4: 词频剪枝与双向/反向搜索优化',
    'def exist4(board: list[list[str]], word: str) -> bool:',
    '    count = [0] * 128',
    '    for row in board: [count.__setitem__(ord(c), count[ord(c)] + 1) for c in row]',
    '    w = list(word)',
    '    for c in w: count[ord(c)] -= 1; (count[ord(c)] < 0) and False',
    '    if count[ord(w[-1])] < count[ord(w[0])]:',
    '        w.reverse()',
    '    # 遍历起点',
    '    for i in range(len(board)):',
    '        for j in range(len(board[0])):',
    '            if dfs4(board, w, i, j, 0): return True',
    '        # end j',
    '    # end i',
    '    return False',
    '# 辅助递归',
    'def dfs4(b, w, i, j, k):',
    '    if k == len(w): return True',
    '    if not (0 <= i < len(b) and 0 <= j < len(b[0])) or b[i][j] != w[k]: return False',
    '    tmp = b[i][j]',
    '    b[i][j] = 0',
    '    found = (dfs4(b, w, i + 1, j, k + 1)   # ⬇️ 向下探索',
    '          or dfs4(b, w, i - 1, j, k + 1)   # ⬆️ 向上探索',
    '          or dfs4(b, w, i, j + 1, k + 1)   # ➡️ 向右探索',
    '          or dfs4(b, w, i, j - 1, k + 1))  # ⬅️ 向左探索',
    '    b[i][j] = tmp',
    '    return found',
    '# end dfs4',
  ],
  javascript: [
    '// 阶段 4: 词频统计剪枝与倒序匹配',
    'export function exist4(board, word) {',
    '  const count = new Array(128).fill(0);',
    '  for (const row of board) for (const c of row) count[c.charCodeAt(0)]++;',
    '  let w = word.split(\'\');',
    '  for (const c of w) if (--count[c.charCodeAt(0)] < 0) return false;',
    '  if (count[w[w.length - 1].charCodeAt(0)] < count[w[0].charCodeAt(0)]) {',
    '    w.reverse();',
    '  }',
    '  for (let i = 0; i < board.length; i++) {',
    '    for (let j = 0; j < board[0].length; j++) {',
    '      if (dfs4(board, w, i, j, 0)) return true;',
    '    }',
    '  }',
    '  return false;',
    '}',
    'function dfs4(b, w, i, j, k) {',
    '  if (k === w.length) return true;',
    '  if (i < 0 || i >= b.length || j < 0 || j >= b[0].length || b[i][j] !== w[k]) return false;',
    '  const tmp = b[i][j];',
    '  b[i][j] = 0;',
    '  const found = dfs4(b, w, i + 1, j, k + 1)   // ⬇️ 向下探索',
    '             || dfs4(b, w, i - 1, j, k + 1)   // ⬆️ 向上探索',
    '             || dfs4(b, w, i, j + 1, k + 1)   // ➡️ 向右探索',
    '             || dfs4(b, w, i, j - 1, k + 1);  // ⬅️ 向左探索',
    '  b[i][j] = tmp;',
    '  return found;',
    '}',
  ],
};

// ==========================================
// 3. Code03 最长公共子序列 (LeetCode 1143)
// ==========================================
export const LCS_STAGE1_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    '// 阶段 1: 双串末尾匹配递归 (分支独立分行)',
    'public static int lcs1(String s1, String s2) {',
    '    char[] a = s1.toCharArray();',
    '    char[] b = s2.toCharArray();',
    '    return f(a, b, a.length - 1, b.length - 1);',
    '}',
    'private static int f(char[] a, char[] b, int i, int j) {',
    '    if (i < 0 || j < 0) {',
    '        return 0; // 🛑 边界特判：任一串为空',
    '    }',
    '    if (a[i] == b[j]) {',
    '        return 1 + f(a, b, i - 1, j - 1); // ↖️ 字符匹配：向对角线探索',
    '    }',
    '    int p1 = f(a, b, i - 1, j); // ⬆️ 字符不匹配分支 1：向上探索',
    '    int p2 = f(a, b, i, j - 1); // ⬅️ 字符不匹配分支 2：向左探索',
    '    return Math.max(p1, p2);    // ↩️ 汇总返回两分支最大值',
    '}',
  ],
  cpp: [
    '// 阶段 1: 双串末尾匹配递归 (分支独立分行)',
    'int lcs1(const string& s1, const string& s2) {',
    '    return f(s1, s2, (int)s1.size() - 1, (int)s2.size() - 1);',
    '}',
    'int f(const string& a, const string& b, int i, int j) {',
    '    if (i < 0 || j < 0) {',
    '        return 0; // 🛑 边界特判：任一串为空',
    '    }',
    '    if (a[i] == b[j]) {',
    '        return 1 + f(a, b, i - 1, j - 1); // ↖️ 字符匹配：向对角线探索',
    '    }',
    '    int p1 = f(a, b, i - 1, j); // ⬆️ 字符不匹配分支 1：向上探索',
    '    int p2 = f(a, b, i, j - 1); // ⬅️ 字符不匹配分支 2：向左探索',
    '    return max(p1, p2);         // ↩️ 汇总返回两分支最大值',
    '}',
  ],
  python: [
    '# 阶段 1: 双串末尾匹配递归 (分支独立分行)',
    'def lcs1(s1: str, s2: str) -> int:',
    '    def f(i: int, j: int) -> int:',
    '        if i < 0 or j < 0:',
    '            return 0  # 🛑 边界特判：任一串为空',
    '        if s1[i] == s2[j]:',
    '            return 1 + f(i - 1, j - 1)  # ↖️ 字符匹配：向对角线探索',
    '        p1 = f(i - 1, j)  # ⬆️ 字符不匹配分支 1：向上探索',
    '        p2 = f(i, j - 1)  # ⬅️ 字符不匹配分支 2：向左探索',
    '        return max(p1, p2)  # ↩️ 汇总返回两分支最大值',
    '    return f(len(s1) - 1, len(s2) - 1)',
  ],
  javascript: [
    '// 阶段 1: 双串末尾匹配递归 (分支独立分行)',
    'export function lcs1(s1, s2) {',
    '  function f(i, j) {',
    '    if (i < 0 || j < 0) {',
    '      return 0; // 🛑 边界特判：任一串为空',
    '    }',
    '    if (s1[i] === s2[j]) {',
    '      return 1 + f(i - 1, j - 1); // ↖️ 字符匹配：向对角线探索',
    '    }',
    '    const p1 = f(i - 1, j); // ⬆️ 字符不匹配分支 1：向上探索',
    '    const p2 = f(i, j - 1); // ⬅️ 字符不匹配分支 2：向左探索',
    '    return Math.max(p1, p2); // ↩️ 汇总返回两分支最大值',
    '  }',
    '  return f(s1.length - 1, s2.length - 1);',
    '}',
  ],
};
export const LCS_STAGE1_FORWARD_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    '// 阶段 1: 顺推双串递归探索 (从首字符 f(0,0) 开始)',
    'public static int lcs1Forward(String s1, String s2) {',
    '    char[] a = s1.toCharArray();',
    '    char[] b = s2.toCharArray();',
    '    return f(a, b, 0, 0);',
    '}',
    'private static int f(char[] a, char[] b, int i, int j) {',
    '    if (i >= a.length || j >= b.length) {',
    '        return 0; // 🛑 边界特判：任一串耗尽',
    '    }',
    '    if (a[i] == b[j]) {',
    '        return 1 + f(a, b, i + 1, j + 1); // ↘️ 字符匹配：向右下深入探索',
    '    }',
    '    int p1 = f(a, b, i + 1, j); // ⬇️ 字符不匹配分支 1：向下探索',
    '    int p2 = f(a, b, i, j + 1); // ➡️ 字符不匹配分支 2：向右探索',
    '    return Math.max(p1, p2);    // ↩️ 汇总返回两分支最大值',
    '}',
  ],
  cpp: [
    '// 阶段 1: 顺推双串递归探索 (从首字符 f(0,0) 开始)',
    'int lcs1Forward(const string& s1, const string& s2) {',
    '    return f(s1, s2, 0, 0);',
    '}',
    'int f(const string& a, const string& b, int i, int j) {',
    '    if (i >= (int)a.size() || j >= (int)b.size()) {',
    '        return 0; // 🛑 边界特判：任一串耗尽',
    '    }',
    '    if (a[i] == b[j]) {',
    '        return 1 + f(a, b, i + 1, j + 1); // ↘️ 字符匹配：向右下深入探索',
    '    }',
    '    int p1 = f(a, b, i + 1, j); // ⬇️ 字符不匹配分支 1：向下探索',
    '    int p2 = f(a, b, i, j + 1); // ➡️ 字符不匹配分支 2：向右探索',
    '    return max(p1, p2);         // ↩️ 汇总返回两分支最大值',
    '}',
  ],
  python: [
    '# 阶段 1: 顺推双串递归探索 (从首字符 f(0,0) 开始)',
    'def lcs1Forward(s1: str, s2: str) -> int:',
    '    def f(i: int, j: int) -> int:',
    '        if i >= len(s1) or j >= len(s2):',
    '            return 0  # 🛑 边界特判：任一串耗尽',
    '        if s1[i] == s2[j]:',
    '            return 1 + f(i + 1, j + 1)  # ↘️ 字符匹配：向右下深入探索',
    '        p1 = f(i + 1, j)  # ⬇️ 字符不匹配分支 1：向下探索',
    '        p2 = f(i, j + 1)  # ➡️ 字符不匹配分支 2：向右探索',
    '        return max(p1, p2)  # ↩️ 汇总返回两分支最大值',
    '    return f(0, 0)',
  ],
  javascript: [
    '// 阶段 1: 顺推双串递归探索 (从首字符 f(0,0) 开始)',
    'export function lcs1Forward(s1, s2) {',
    '  function f(i, j) {',
    '    if (i >= s1.length || j >= s2.length) {',
    '      return 0; // 🛑 边界特判：任一串耗尽',
    '    }',
    '    if (s1[i] === s2[j]) {',
    '      return 1 + f(i + 1, j + 1); // ↘️ 字符匹配：向右下深入探索',
    '    }',
    '    const p1 = f(i + 1, j); // ⬇️ 字符不匹配分支 1：向下探索',
    '    const p2 = f(i, j + 1); // ➡️ 字符不匹配分支 2：向右探索',
    '    return Math.max(p1, p2); // ↩️ 汇总返回两分支最大值',
    '  }',
    '  return f(0, 0);',
    '}',
  ],
};

export const LCS_STAGE2_FORWARD_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    '// 阶段 2: 顺推记忆化搜索 (备忘录剪枝)',
    'public static int lcs2Forward(String s1, String s2) {',
    '    int n = s1.length(), m = s2.length();',
    '    int[][] memo = new int[n][m];',
    '    for (int[] row : memo) Arrays.fill(row, -1);',
    '    return f(s1.toCharArray(), s2.toCharArray(), 0, 0, memo);',
    '}',
    'private static int f(char[] a, char[] b, int i, int j, int[][] memo) {',
    '    if (i >= a.length || j >= b.length) {',
    '        return 0; // 🛑 边界特判：任一串耗尽',
    '    }',
    '    if (memo[i][j] != -1) {',
    '        return memo[i][j]; // 🎯 备忘录命中直接剪枝返回',
    '    }',
    '    if (a[i] == b[j]) {',
    '        return memo[i][j] = 1 + f(a, b, i + 1, j + 1, memo); // ↘️ 字符匹配',
    '    }',
    '    int p1 = f(a, b, i + 1, j, memo); // ⬇️ 字符不匹配分支 1：向下探索',
    '    int p2 = f(a, b, i, j + 1, memo); // ➡️ 字符不匹配分支 2：向右探索',
    '    return memo[i][j] = Math.max(p1, p2); // 💾 存入备忘录并返回',
    '}',
  ],
  cpp: [
    '// 阶段 2: 顺推记忆化搜索 (备忘录剪枝)',
    'int lcs2Forward(const string& s1, const string& s2) {',
    '    int n = s1.size(), m = s2.size();',
    '    vector<vector<int>> memo(n, vector<int>(m, -1));',
    '    return f(s1, s2, 0, 0, memo);',
    '}',
    'int f(const string& a, const string& b, int i, int j, vector<vector<int>>& memo) {',
    '    if (i >= (int)a.size() || j >= (int)b.size()) {',
    '        return 0; // 🛑 边界特判：任一串耗尽',
    '    }',
    '    if (memo[i][j] != -1) {',
    '        return memo[i][j]; // 🎯 备忘录命中直接剪枝返回',
    '    }',
    '    if (a[i] == b[j]) {',
    '        return memo[i][j] = 1 + f(a, b, i + 1, j + 1, memo); // ↘️ 字符匹配',
    '    }',
    '    int p1 = f(a, b, i + 1, j, memo); // ⬇️ 字符不匹配分支 1：向下探索',
    '    int p2 = f(a, b, i, j + 1, memo); // ➡️ 字符不匹配分支 2：向右探索',
    '    return memo[i][j] = max(p1, p2);  // 💾 存入备忘录并返回',
    '}',
  ],
  python: [
    '# 阶段 2: 顺推记忆化搜索 (备忘录剪枝)',
    'def lcs2Forward(s1: str, s2: str) -> int:',
    '    n, m = len(s1), len(s2)',
    '    memo = [[-1] * m for _ in range(n)]',
    '    def f(i: int, j: int) -> int:',
    '        if i >= n or j >= m:',
    '            return 0  # 🛑 边界特判：任一串耗尽',
    '        if memo[i][j] != -1:',
    '            return memo[i][j]  # 🎯 备忘录命中直接剪枝返回',
    '        if s1[i] == s2[j]:',
    '            memo[i][j] = 1 + f(i + 1, j + 1)  # ↘️ 字符匹配',
    '            return memo[i][j]',
    '        p1 = f(i + 1, j)  # ⬇️ 字符不匹配分支 1：向下探索',
    '        p2 = f(i, j + 1)  # ➡️ 字符不匹配分支 2：向右探索',
    '        memo[i][j] = max(p1, p2)  # 💾 存入备忘录并返回',
    '        return memo[i][j]',
    '    return f(0, 0)',
  ],
  javascript: [
    '// 阶段 2: 顺推记忆化搜索 (备忘录剪枝)',
    'export function lcs2Forward(s1, s2) {',
    '  const n = s1.length, m = s2.length;',
    '  const memo = Array.from({ length: n }, () => new Array(m).fill(-1));',
    '  function f(i, j) {',
    '    if (i >= n || j >= m) {',
    '      return 0; // 🛑 边界特判：任一串耗尽',
    '    }',
    '    if (memo[i][j] !== -1) {',
    '      return memo[i][j]; // 🎯 备忘录命中直接剪枝返回',
    '    }',
    '    if (s1[i] === s2[j]) {',
    '      return memo[i][j] = 1 + f(i + 1, j + 1); // ↘️ 字符匹配',
    '    }',
    '    const p1 = f(i + 1, j); // ⬇️ 字符不匹配分支 1：向下探索',
    '    const p2 = f(i, j + 1); // ➡️ 字符不匹配分支 2：向右探索',
    '    return memo[i][j] = Math.max(p1, p2); // 💾 存入备忘录并返回',
    '  }',
    '  return f(0, 0);',
    '}',
  ],
};

export const LCS_STAGE3_FORWARD_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    '// 阶段 3: 顺推后缀二维表倒序递推 (目标在 dp[0][0])',
    'public static int lcs3Forward(String s1, String s2) {',
    '    int n = s1.length(), m = s2.length();',
    '    int[][] dp = new int[n + 1][m + 1];',
    '    for (int i = n - 1; i >= 0; i--) {',
    '        for (int j = m - 1; j >= 0; j--) {',
    '            if (s1.charAt(i) == s2.charAt(j)) {',
    '                dp[i][j] = 1 + dp[i + 1][j + 1]; // ↘️ 右下对角线转移',
    '            } else {',
    '                dp[i][j] = Math.max(dp[i + 1][j], dp[i][j + 1]); // ⬇️➡️ 下右选优',
    '            }',
    '        }',
    '    }',
    '    return dp[0][0];',
    '}',
  ],
  cpp: [
    '// 阶段 3: 顺推后缀二维表倒序递推 (目标在 dp[0][0])',
    'int lcs3Forward(string s1, string s2) {',
    '    int n = s1.size(), m = s2.size();',
    '    vector<vector<int>> dp(n + 1, vector<int>(m + 1, 0));',
    '    for (int i = n - 1; i >= 0; i--) {',
    '        for (int j = m - 1; j >= 0; j--) {',
    '            if (s1[i] == s2[j]) {',
    '                dp[i][j] = 1 + dp[i + 1][j + 1]; // ↘️ 右下对角线转移',
    '            } else {',
    '                dp[i][j] = max(dp[i + 1][j], dp[i][j + 1]); // ⬇️➡️ 下右选优',
    '            }',
    '        }',
    '    }',
    '    return dp[0][0];',
    '}',
  ],
  python: [
    '# 阶段 3: 顺推后缀二维表倒序递推 (目标在 dp[0][0])',
    'def lcs3Forward(s1: str, s2: str) -> int:',
    '    n, m = len(s1), len(s2)',
    '    dp = [[0] * (m + 1) for _ in range(n + 1)]',
    '    for i in range(n - 1, -1, -1):',
    '        for j in range(m - 1, -1, -1):',
    '            if s1[i] == s2[j]:',
    '                dp[i][j] = 1 + dp[i + 1][j + 1]  # ↘️ 右下对角线转移',
    '            else:',
    '                dp[i][j] = max(dp[i + 1][j], dp[i][j + 1])  # ⬇️➡️ 下右选优',
    '    return dp[0][0]',
  ],
  javascript: [
    '// 阶段 3: 顺推后缀二维表倒序递推 (目标在 dp[0][0])',
    'export function lcs3Forward(s1, s2) {',
    '  const n = s1.length, m = s2.length;',
    '  const dp = Array.from({ length: n + 1 }, () => new Array(m + 1).fill(0));',
    '  for (let i = n - 1; i >= 0; i--) {',
    '    for (let j = m - 1; j >= 0; j--) {',
    '      if (s1[i] === s2[j]) {',
    '        dp[i][j] = 1 + dp[i + 1][j + 1]; // ↘️ 右下对角线转移',
    '      } else {',
    '        dp[i][j] = Math.max(dp[i + 1][j], dp[i][j + 1]); // ⬇️➡️ 下右选优',
    '      }',
    '    }',
    '  }',
    '  return dp[0][0];',
    '}',
  ],
};

export const LCS_STAGE2_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    '// 阶段 2: 记忆化搜索 (备忘录剪枝)',
    'public static int lcs2(String s1, String s2) {',
    '    int n = s1.length(), m = s2.length();',
    '    int[][] memo = new int[n + 1][m + 1];',
    '    for (int[] row : memo) Arrays.fill(row, -1);',
    '    return f(s1.toCharArray(), s2.toCharArray(), n, m, memo);',
    '}',
    'private static int f(char[] a, char[] b, int i, int j, int[][] memo) {',
    '    if (i == 0 || j == 0) {',
    '        return 0; // 🛑 边界特判：任一串为空',
    '    }',
    '    if (memo[i][j] != -1) {',
    '        return memo[i][j]; // 🎯 备忘录命中直接剪枝返回',
    '    }',
    '    if (a[i - 1] == b[j - 1]) {',
    '        return memo[i][j] = 1 + f(a, b, i - 1, j - 1, memo); // ↖️ 字符匹配',
    '    }',
    '    int p1 = f(a, b, i - 1, j, memo); // ⬆️ 字符不匹配分支 1：向上探索',
    '    int p2 = f(a, b, i, j - 1, memo); // ⬅️ 字符不匹配分支 2：向左探索',
    '    return memo[i][j] = Math.max(p1, p2); // 💾 存入备忘录并返回',
    '}',
  ],
  cpp: [
    '// 阶段 2: 记忆化搜索 (备忘录剪枝)',
    'int lcs2(const string& s1, const string& s2) {',
    '    int n = s1.size(), m = s2.size();',
    '    vector<vector<int>> memo(n + 1, vector<int>(m + 1, -1));',
    '    return f(s1, s2, n, m, memo);',
    '}',
    'int f(const string& a, const string& b, int i, int j, vector<vector<int>>& memo) {',
    '    if (i == 0 || j == 0) {',
    '        return 0; // 🛑 边界特判：任一串为空',
    '    }',
    '    if (memo[i][j] != -1) {',
    '        return memo[i][j]; // 🎯 备忘录命中直接剪枝返回',
    '    }',
    '    if (a[i - 1] == b[j - 1]) {',
    '        return memo[i][j] = 1 + f(a, b, i - 1, j - 1, memo); // ↖️ 字符匹配',
    '    }',
    '    int p1 = f(a, b, i - 1, j, memo); // ⬆️ 字符不匹配分支 1：向上探索',
    '    int p2 = f(a, b, i, j - 1, memo); // ⬅️ 字符不匹配分支 2：向左探索',
    '    return memo[i][j] = max(p1, p2);  // 💾 存入备忘录并返回',
    '}',
  ],
  python: [
    '# 阶段 2: 记忆化搜索 (备忘录剪枝)',
    'def lcs2(s1: str, s2: str) -> int:',
    '    n, m = len(s1), len(s2)',
    '    memo = [[-1] * (m + 1) for _ in range(n + 1)]',
    '    def f(i: int, j: int) -> int:',
    '        if i == 0 or j == 0:',
    '            return 0  # 🛑 边界特判：任一串为空',
    '        if memo[i][j] != -1:',
    '            return memo[i][j]  # 🎯 备忘录命中直接剪枝返回',
    '        if s1[i - 1] == s2[j - 1]:',
    '            memo[i][j] = 1 + f(i - 1, j - 1)  # ↖️ 字符匹配',
    '            return memo[i][j]',
    '        p1 = f(i - 1, j)  # ⬆️ 字符不匹配分支 1：向上探索',
    '        p2 = f(i, j - 1)  # ⬅️ 字符不匹配分支 2：向左探索',
    '        memo[i][j] = max(p1, p2)  # 💾 存入备忘录并返回',
    '        return memo[i][j]',
    '    return f(n, m)',
  ],
  javascript: [
    '// 阶段 2: 记忆化搜索 (备忘录剪枝)',
    'export function lcs2(s1, s2) {',
    '  const n = s1.length, m = s2.length;',
    '  const memo = Array.from({ length: n + 1 }, () => new Array(m + 1).fill(-1));',
    '  function f(i, j) {',
    '    if (i === 0 || j === 0) {',
    '      return 0; // 🛑 边界特判：任一串为空',
    '    }',
    '    if (memo[i][j] !== -1) {',
    '      return memo[i][j]; // 🎯 备忘录命中直接剪枝返回',
    '    }',
    '    if (s1[i - 1] === s2[j - 1]) {',
    '      return memo[i][j] = 1 + f(i - 1, j - 1); // ↖️ 字符匹配',
    '    }',
    '    const p1 = f(i - 1, j); // ⬆️ 字符不匹配分支 1：向上探索',
    '    const p2 = f(i, j - 1); // ⬅️ 字符不匹配分支 2：向左探索',
    '    return memo[i][j] = Math.max(p1, p2); // 💾 存入备忘录并返回',
    '  }',
    '  return f(n, m);',
    '}',
  ],
};

export const LCS_STAGE3_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    '// 阶段 3: 严格二维表递推',
    'public static int lcs3(String s1, String s2) {',
    '    int n = s1.length(), m = s2.length();',
    '    int[][] dp = new int[n + 1][m + 1];',
    '    for (int i = 1; i <= n; i++) {',
    '        for (int j = 1; j <= m; j++) {',
    '            if (s1.charAt(i - 1) == s2.charAt(j - 1)) {',
    '                dp[i][j] = 1 + dp[i - 1][j - 1]; // ↖️ 对角线转移',
    '            } else {',
    '                dp[i][j] = Math.max(dp[i - 1][j], dp[i][j - 1]); // ⬅️⬆️ 上左选优',
    '            }',
    '        }',
    '    }',
    '    return dp[n][m];',
    '}',
  ],
  cpp: [
    '// 阶段 3: 严格二维表递推',
    'int lcs3(string s1, string s2) {',
    '    int n = s1.size(), m = s2.size();',
    '    vector<vector<int>> dp(n + 1, vector<int>(m + 1, 0));',
    '    for (int i = 1; i <= n; ++i) {',
    '        for (int j = 1; j <= m; ++j) {',
    '            if (s1[i - 1] == s2[j - 1]) {',
    '                dp[i][j] = 1 + dp[i - 1][j - 1]; // ↖️ 对角线转移',
    '            } else {',
    '                dp[i][j] = max(dp[i - 1][j], dp[i][j - 1]); // ⬅️⬆️ 上左选优',
    '            }',
    '        }',
    '    }',
    '    return dp[n][m];',
    '}',
  ],
  python: [
    '# 阶段 3: 严格二维表递推',
    'def lcs3(s1: str, s2: str) -> int:',
    '    n, m = len(s1), len(s2)',
    '    dp = [[0] * (m + 1) for _ in range(n + 1)]',
    '    for i in range(1, n + 1):',
    '        for j in range(1, m + 1):',
    '            if s1[i - 1] == s2[j - 1]:',
    '                dp[i][j] = 1 + dp[i - 1][j - 1]  # ↖️ 对角线转移',
    '            else:',
    '                dp[i][j] = max(dp[i - 1][j], dp[i][j - 1])  # ⬅️⬆️ 上左选优',
    '    return dp[n][m]',
  ],
  javascript: [
    '// 阶段 3: 严格二维表递推',
    'export function lcs3(s1, s2) {',
    '  const n = s1.length, m = s2.length;',
    '  const dp = Array.from({ length: n + 1 }, () => new Array(m + 1).fill(0));',
    '  for (let i = 1; i <= n; i++) {',
    '    for (let j = 1; j <= m; j++) {',
    '      if (s1[i - 1] === s2[j - 1]) {',
    '        dp[i][j] = 1 + dp[i - 1][j - 1]; // ↖️ 对角线转移',
    '      } else {',
    '        dp[i][j] = Math.max(dp[i - 1][j], dp[i][j - 1]); // ⬅️⬆️ 上左选优',
    '      }',
    '    }',
    '  }',
    '  return dp[n][m];',
    '}',
  ],
};

export const LCS_STAGE4_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    '// 阶段 4: 空间压缩 + 对角线临时变量备份 (leftUp 暂存)',
    'public static int lcs4(String s1, String s2) {',
    '    int n = s1.length(), m = s2.length();',
    '    int[] dp = new int[m + 1];',
    '    for (int i = 1; i <= n; i++) {',
    '        int leftUp = 0; // 暂存 dp[i-1][j-1]',
    '        for (int j = 1; j <= m; j++) {',
    '            int backup = dp[j]; // 1. 暂存旧值 dp[i-1][j]',
    '            if (s1.charAt(i - 1) == s2.charAt(j - 1)) {',
    '                dp[j] = leftUp + 1; // 2. 转移计算：对角线匹配',
    '            } else {',
    '                dp[j] = Math.max(dp[j], dp[j - 1]); // 2. 转移计算：上下左选优',
    '            }',
    '            leftUp = backup; // 3. 寄存器推移：更新为下一列对角线',
    '        }',
    '    }',
    '    return dp[m];',
    '}',
  ],
  cpp: [
    '// 阶段 4: 空间压缩 + 对角线临时变量备份 (leftUp 暂存)',
    'int lcs4(const string& s1, const string& s2) {',
    '    int n = s1.size(), m = s2.size();',
    '    vector<int> dp(m + 1, 0);',
    '    for (int i = 1; i <= n; ++i) {',
    '        int leftUp = 0; // 暂存 dp[i-1][j-1]',
    '        for (int j = 1; j <= m; ++j) {',
    '            int backup = dp[j]; // 1. 暂存旧值 dp[i-1][j]',
    '            if (s1[i - 1] == s2[j - 1]) {',
    '                dp[j] = leftUp + 1; // 2. 转移计算：对角线匹配',
    '            } else {',
    '                dp[j] = max(dp[j], dp[j - 1]); // 2. 转移计算：上下左选优',
    '            }',
    '            leftUp = backup; // 3. 寄存器推移：更新为下一列对角线',
    '        }',
    '    }',
    '    return dp[m];',
    '}',
  ],
  python: [
    '# 阶段 4: 空间压缩 + 对角线临时变量备份 (leftUp 暂存)',
    'def lcs4(s1: str, s2: str) -> int:',
    '    n, m = len(s1), len(s2)',
    '    dp = [0] * (m + 1)',
    '    for i in range(1, n + 1):',
    '        left_up = 0  # 暂存 dp[i-1][j-1]',
    '        for j in range(1, m + 1):',
    '            backup = dp[j]  # 1. 暂存旧值 dp[i-1][j]',
    '            if s1[i - 1] == s2[j - 1]:',
    '                dp[j] = left_up + 1  # 2. 转移计算：对角线匹配',
    '            else:',
    '                dp[j] = max(dp[j], dp[j - 1])  # 2. 转移计算：上下左选优',
    '            left_up = backup  # 3. 寄存器推移：更新为下一列对角线',
    '    return dp[m]',
  ],
  javascript: [
    '// 阶段 4: 空间压缩 + 对角线临时变量备份 (leftUp 暂存)',
    'export function lcs4(s1, s2) {',
    '  const n = s1.length, m = s2.length;',
    '  const dp = new Array(m + 1).fill(0);',
    '  for (let i = 1; i <= n; i++) {',
    '    let leftUp = 0; // 暂存 dp[i-1][j-1]',
    '    for (let j = 1; j <= m; j++) {',
    '      const backup = dp[j]; // 1. 暂存旧值 dp[i-1][j]',
    '      if (s1[i - 1] === s2[j - 1]) {',
    '        dp[j] = leftUp + 1; // 2. 转移计算：对角线匹配',
    '      } else {',
    '        dp[j] = Math.max(dp[j], dp[j - 1]); // 2. 转移计算：上下左选优',
    '      }',
    '      leftUp = backup; // 3. 寄存器推移：更新为下一列对角线',
    '    }',
    '  }',
    '  return dp[m];',
    '}',
  ],
};

// ==========================================
// 4. Code04 最长回文子序列 (LeetCode 516)
// ==========================================
export const LPS_STAGE1_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    '// 阶段 1: 区间双端匹配递归',
    'public static int lps1(String s) {',
    '    return f(s.toCharArray(), 0, s.length() - 1);',
    '}',
    'private static int f(char[] s, int l, int r) {',
    '    if (l == r) return 1;',
    '    if (l == r - 1) return s[l] == s[r] ? 2 : 1;',
    '    if (s[l] == s[r]) return 2 + f(s, l + 1, r - 1);',
    '    return Math.max(f(s, l + 1, r), f(s, l, r - 1));',
    '}',
  ],
  cpp: [
    '// 阶段 1: 区间递归',
    'int f(const string& s, int l, int r) {',
    '    if (l == r) return 1;',
    '    if (l == r - 1) return s[l] == s[r] ? 2 : 1;',
    '    if (s[l] == s[r]) return 2 + f(s, l + 1, r - 1);',
    '    return max(f(s, l + 1, r), f(s, l, r - 1));',
    '}',
  ],
  python: [
    '# 阶段 1: 区间双端匹配递归',
    'def lps1(s: str) -> int:',
    '    def f(l, r):',
    '        if l == r: return 1',
    '        if l == r - 1: return 2 if s[l] == s[r] else 1',
    '        if s[l] == s[r]: return 2 + f(l + 1, r - 1)',
    '        return max(f(l + 1, r), f(l, r - 1))',
    '    return f(0, len(s) - 1)',
  ],
  javascript: [
    '// 阶段 1: 区间双端匹配递归',
    'export function lps1(s) {',
    '  function f(l, r) {',
    '    if (l === r) return 1;',
    '    if (l === r - 1) return s[l] === s[r] ? 2 : 1;',
    '    if (s[l] === s[r]) return 2 + f(l + 1, r - 1);',
    '    return Math.max(f(l + 1, r), f(l, r - 1));',
    '  }',
    '  return f(0, s.length - 1);',
    '}',
  ],
};

export const LPS_STAGE2_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    '// 阶段 2: 记忆化搜索 (右上三角备忘录)',
    'public static int lps2(String s) {',
    '    int n = s.length();',
    '    int[][] memo = new int[n][n];',
    '    return f(s.toCharArray(), 0, n - 1, memo);',
    '}',
    'private static int f(char[] s, int l, int r, int[][] memo) {',
    '    if (memo[l][r] != 0) return memo[l][r];',
    '    if (l == r) return memo[l][r] = 1;',
    '    if (l == r - 1) return memo[l][r] = s[l] == s[r] ? 2 : 1;',
    '    if (s[l] == s[r]) return memo[l][r] = 2 + f(s, l + 1, r - 1, memo);',
    '    return memo[l][r] = Math.max(f(s, l + 1, r, memo), f(s, l, r - 1, memo));',
    '}',
  ],
  cpp: [
    '// 阶段 2: 记忆化搜索',
    'int lps2(string s) {',
    '    int n = s.size();',
    '    vector<vector<int>> memo(n, vector<int>(n, 0));',
    '    auto f = [&](auto& self, int l, int r) -> int {',
    '        if (memo[l][r]) return memo[l][r];',
    '        if (l == r) return memo[l][r] = 1;',
    '        if (l == r - 1) return memo[l][r] = s[l] == s[r] ? 2 : 1;',
    '        if (s[l] == s[r]) return memo[l][r] = 2 + self(self, l + 1, r - 1);',
    '        return memo[l][r] = max(self(self, l + 1, r), self(self, l, r - 1));',
    '    };',
    '    return f(f, 0, n - 1);',
    '}',
  ],
  python: [
    '# 阶段 2: 记忆化搜索',
    'def lps2(s: str) -> int:',
    '    memo = {}',
    '    def f(l, r):',
    '        if (l, r) in memo: return memo[(l, r)]',
    '        if l == r: res = 1',
    '        elif l == r - 1: res = 2 if s[l] == s[r] else 1',
    '        elif s[l] == s[r]: res = 2 + f(l + 1, r - 1)',
    '        else: res = max(f(l + 1, r), f(l, r - 1))',
    '        memo[(l, r)] = res',
    '        return res',
    '    return f(0, len(s) - 1)',
  ],
  javascript: [
    '// 阶段 2: 记忆化搜索',
    'export function lps2(s) {',
    '  const n = s.length;',
    '  const memo = Array.from({ length: n }, () => new Array(n).fill(0));',
    '  function f(l, r) {',
    '    if (memo[l][r] !== 0) return memo[l][r];',
    '    if (l === r) return memo[l][r] = 1;',
    '    if (l === r - 1) return memo[l][r] = s[l] === s[r] ? 2 : 1;',
    '    if (s[l] === s[r]) return memo[l][r] = 2 + f(l + 1, r - 1);',
    '    return memo[l][r] = Math.max(f(l + 1, r), f(l, r - 1));',
    '  }',
    '  return f(0, n - 1);',
    '}',
  ],
};

export const LPS_STAGE3_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    '// 阶段 3: 严格区间二维表递推 (行自底向上，列从左至右)',
    'public static int lps3(String s) {',
    '    int n = s.length();',
    '    char[] str = s.toCharArray();',
    '    int[][] dp = new int[n][n];',
    '    for (int l = n - 1; l >= 0; l--) {',
    '        dp[l][l] = 1;',
    '        if (l + 1 < n) dp[l][l + 1] = str[l] == str[l + 1] ? 2 : 1;',
    '        for (int r = l + 2; r < n; r++) {',
    '            if (str[l] == str[r]) dp[l][r] = 2 + dp[l + 1][r - 1];',
    '            else dp[l][r] = Math.max(dp[l + 1][r], dp[l][r - 1]);',
    '        }',
    '    }',
    '    return dp[0][n - 1];',
    '}',
  ],
  cpp: [
    '// 阶段 3: 严格区间二维表递推',
    'int lps3(string s) {',
    '    int n = s.size();',
    '    vector<vector<int>> dp(n, vector<int>(n, 0));',
    '    for (int l = n - 1; l >= 0; --l) {',
    '        dp[l][l] = 1;',
    '        if (l + 1 < n) dp[l][l + 1] = s[l] == s[l + 1] ? 2 : 1;',
    '        for (int r = l + 2; r < n; ++r) {',
    '            if (s[l] == s[r]) dp[l][r] = 2 + dp[l + 1][r - 1];',
    '            else dp[l][r] = max(dp[l + 1][r], dp[l][r - 1]);',
    '        }',
    '    }',
    '    return dp[0][n - 1];',
    '}',
  ],
  python: [
    '# 阶段 3: 严格区间二维表递推',
    'def lps3(s: str) -> int:',
    '    n = len(s)',
    '    dp = [[0] * n for _ in range(n)]',
    '    for l in range(n - 1, -1, -1):',
    '        dp[l][l] = 1',
    '        if l + 1 < n: dp[l][l + 1] = 2 if s[l] == s[l + 1] else 1',
    '        for r in range(l + 2, n):',
    '            if s[l] == s[r]: dp[l][r] = 2 + dp[l + 1][r - 1]',
    '            else: dp[l][r] = max(dp[l + 1][r], dp[l][r - 1])',
    '    return dp[0][n - 1]',
  ],
  javascript: [
    '// 阶段 3: 严格区间二维表递推',
    'export function lps3(s) {',
    '  const n = s.length;',
    '  const dp = Array.from({ length: n }, () => new Array(n).fill(0));',
    '  for (let l = n - 1; l >= 0; l--) {',
    '    dp[l][l] = 1;',
    '    if (l + 1 < n) dp[l][l + 1] = s[l] === s[l + 1] ? 2 : 1;',
    '    for (let r = l + 2; r < n; r++) {',
    '      if (s[l] === s[r]) dp[l][r] = 2 + dp[l + 1][r - 1];',
    '      else dp[l][r] = Math.max(dp[l + 1][r], dp[l][r - 1]);',
    '    }',
    '  }',
    '  return dp[0][n - 1];',
    '}',
  ],
};

export const LPS_STAGE4_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    '// 阶段 4: 空间压缩版 (一维滚动数组与左下角备份)',
    'public static int lps4(String s) {',
    '    int n = s.length();',
    '    int[] dp = new int[n];',
    '    for (int l = n - 1; l >= 0; l--) {',
    '        dp[l] = 1;',
    '        int leftDown = 0;',
    '        for (int r = l + 1; r < n; r++) {',
    '            int backup = dp[r];',
    '            if (s.charAt(l) == s.charAt(r)) dp[r] = 2 + leftDown;',
    '            else dp[r] = Math.max(dp[r], dp[r - 1]);',
    '            leftDown = backup;',
    '        }',
    '    }',
    '    return dp[n - 1];',
    '}',
  ],
  cpp: [
    '// 阶段 4: 空间压缩版',
    'int lps4(string s) {',
    '    int n = s.size();',
    '    vector<int> dp(n, 0);',
    '    for (int l = n - 1; l >= 0; --l) {',
    '        dp[l] = 1;',
    '        int leftDown = 0;',
    '        for (int r = l + 1; r < n; ++r) {',
    '            int backup = dp[r];',
    '            if (s[l] == s[r]) dp[r] = 2 + leftDown;',
    '            else dp[r] = max(dp[r], dp[r - 1]);',
    '            leftDown = backup;',
    '        }',
    '    }',
    '    return dp[n - 1];',
    '}',
  ],
  python: [
    '# 阶段 4: 空间压缩版',
    'def lps4(s: str) -> int:',
    '    n = len(s)',
    '    dp = [0] * n',
    '    for l in range(n - 1, -1, -1):',
    '        dp[l] = 1',
    '        leftDown = 0',
    '        for r in range(l + 1, n):',
    '            backup = dp[r]',
    '            if s[l] == s[r]: dp[r] = 2 + leftDown',
    '            else: dp[r] = max(dp[r], dp[r - 1])',
    '            leftDown = backup',
    '        # end r',
    '    # end l',
    '    return dp[n - 1]',
  ],
  javascript: [
    '// 阶段 4: 空间压缩版',
    'export function lps4(s) {',
    '  const n = s.length;',
    '  const dp = new Array(n).fill(0);',
    '  for (let l = n - 1; l >= 0; l--) {',
    '    dp[l] = 1;',
    '    let leftDown = 0;',
    '    for (let r = l + 1; r < n; r++) {',
    '      const backup = dp[r];',
    '      if (s[l] === s[r]) dp[r] = 2 + leftDown;',
    '      else dp[r] = Math.max(dp[r], dp[r - 1]);',
    '      leftDown = backup;',
    '    }',
    '  }',
    '  return dp[n - 1];',
    '}',
  ],
};

// ==========================================
// 5. Code05 二叉树结构数 (牛客网)
// ==========================================
export const TREE_COUNT_STAGE1_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    '// 阶段 1: 暴力递归尝试拆分左右子树节点规模',
    'public static long f1(int n, int m) {',
    '    if (n == 0) return 1; // 空树算一种形态且高度为0',
    '    if (m == 0) return 0; // 节点数>0但高度上限为0，不可行',
    '    long ways = 0;',
    '    for (int k = 0; k < n; k++) { // 枚举左子树节点数k，右子树为n-1-k',
    '        ways = (ways + f1(k, m - 1) * f1(n - 1 - k, m - 1)) % 1000000007;',
    '    }',
    '    return ways;',
    '}',
  ],
  cpp: [
    '// 阶段 1: 暴力递归拆分子树规模',
    'long long f1(int n, int m) {',
    '    if (n == 0) return 1;',
    '    if (m == 0) return 0;',
    '    long long ways = 0;',
    '    for (int k = 0; k < n; ++k) {',
    '        ways = (ways + f1(k, m - 1) * f1(n - 1 - k, m - 1)) % 1000000007;',
    '    }',
    '    return ways;',
    '}',
  ],
  python: [
    '# 阶段 1: 暴力递归',
    'def f1(n: int, m: int) -> int:',
    '    if n == 0: return 1',
    '    if m == 0: return 0',
    '    MOD = 10**9 + 7',
    '    return sum(f1(k, m - 1) * f1(n - 1 - k, m - 1) for k in range(n)) % MOD',
  ],
  javascript: [
    '// 阶段 1: 暴力递归',
    'export function f1(n, m) {',
    '  if (n === 0) return 1;',
    '  if (m === 0) return 0;',
    '  const MOD = 1000000007;',
    '  let ways = 0;',
    '  for (let k = 0; k < n; k++) {',
    '    ways = (ways + f1(k, m - 1) * f1(n - 1 - k, m - 1)) % MOD;',
    '  }',
    '  return ways;',
    '}',
  ],
};

export const TREE_COUNT_STAGE2_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    '// 阶段 2: 记忆化搜索 memo[n][m]',
    'public static long f2(int n, int m, long[][] memo) {',
    '    if (n == 0) return 1;',
    '    if (m == 0) return 0;',
    '    if (memo[n][m] != -1) return memo[n][m];',
    '    long ways = 0, MOD = 1000000007;',
    '    for (int k = 0; k < n; k++) {',
    '        ways = (ways + f2(k, m - 1, memo) * f2(n - 1 - k, m - 1, memo)) % MOD;',
    '    }',
    '    return memo[n][m] = ways;',
    '}',
  ],
  cpp: [
    '// 阶段 2: 记忆化搜索',
    'long long f2(int n, int m, vector<vector<long long>>& memo) {',
    '    if (n == 0) return 1;',
    '    if (m == 0) return 0;',
    '    if (memo[n][m] != -1) return memo[n][m];',
    '    long long ways = 0;',
    '    for (int k = 0; k < n; ++k) {',
    '        ways = (ways + f2(k, m - 1, memo) * f2(n - 1 - k, m - 1, memo)) % 1000000007;',
    '    }',
    '    return memo[n][m] = ways;',
    '}',
  ],
  python: [
    '# 阶段 2: 记忆化搜索',
    'def f2(n: int, m: int, memo: dict) -> int:',
    '    if n == 0: return 1',
    '    if m == 0: return 0',
    '    if (n, m) in memo: return memo[(n, m)]',
    '    MOD = 10**9 + 7',
    '    res = sum(f2(k, m - 1, memo) * f2(n - 1 - k, m - 1, memo) for k in range(n)) % MOD',
    '    memo[(n, m)] = res',
    '    return res',
  ],
  javascript: [
    '// 阶段 2: 记忆化搜索',
    'export function f2(n, m, memo) {',
    '  if (n === 0) return 1;',
    '  if (m === 0) return 0;',
    '  if (memo[n][m] !== -1) return memo[n][m];',
    '  let ways = 0;',
    '  for (let k = 0; k < n; k++) {',
    '    ways = (ways + f2(k, m - 1, memo) * f2(n - 1 - k, m - 1, memo)) % 1000000007;',
    '  }',
    '  return memo[n][m] = ways;',
    '}',
  ],
};

export const TREE_COUNT_STAGE3_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    '// 阶段 3: 严格二维表递推 dp[n][m]',
    'public static int compute3(int n, int m) {',
    '    int MOD = 1000000007;',
    '    long[][] dp = new long[n + 1][m + 1];',
    '    for (int j = 0; j <= m; j++) dp[0][j] = 1;',
    '    for (int j = 1; j <= m; j++) {',
    '        for (int i = 1; i <= n; i++) {',
    '            long sum = 0;',
    '            for (int k = 0; k < i; k++) {',
    '                sum = (sum + dp[k][j - 1] * dp[i - 1 - k][j - 1]) % MOD;',
    '            }',
    '            dp[i][j] = sum;',
    '        }',
    '    }',
    '    return (int) dp[n][m];',
    '}',
  ],
  cpp: [
    '// 阶段 3: 严格二维表递推',
    'int compute3(int n, int m) {',
    '    const int MOD = 1000000007;',
    '    vector<vector<long long>> dp(n + 1, vector<long long>(m + 1, 0));',
    '    for (int j = 0; j <= m; ++j) dp[0][j] = 1;',
    '    for (int j = 1; j <= m; ++j) {',
    '        for (int i = 1; i <= n; ++i) {',
    '            long long sum = 0;',
    '            for (int k = 0; k < i; ++k) {',
    '                sum = (sum + dp[k][j - 1] * dp[i - 1 - k][j - 1]) % MOD;',
    '            }',
    '            dp[i][j] = sum;',
    '        }',
    '    }',
    '    return dp[n][m];',
    '}',
  ],
  python: [
    '# 阶段 3: 严格二维表递推',
    'def compute3(n: int, m: int) -> int:',
    '    MOD = 10**9 + 7',
    '    dp = [[0] * (m + 1) for _ in range(n + 1)]',
    '    for j in range(m + 1): dp[0][j] = 1',
    '    for j in range(1, m + 1):',
    '        for i in range(1, n + 1):',
    '            dp[i][j] = sum(dp[k][j - 1] * dp[i - 1 - k][j - 1] for k in range(i)) % MOD',
    '    return dp[n][m]',
  ],
  javascript: [
    '// 阶段 3: 严格二维表递推',
    'export function compute3(n, m) {',
    '  const MOD = 1000000007;',
    '  const dp = Array.from({ length: n + 1 }, () => new Array(m + 1).fill(0));',
    '  for (let j = 0; j <= m; j++) dp[0][j] = 1;',
    '  for (let j = 1; j <= m; j++) {',
    '    for (let i = 1; i <= n; i++) {',
    '      let sum = 0;',
    '      for (let k = 0; k < i; k++) {',
    '        sum = (sum + dp[k][j - 1] * dp[i - 1 - k][j - 1]) % MOD;',
    '      }',
    '      dp[i][j] = sum;',
    '    }',
    '  }',
    '  return dp[n][m];',
    '}',
  ],
};

export const TREE_COUNT_STAGE4_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    '// 阶段 4: 列空间压缩 (仅保留两列滚动更新)',
    'public static int compute4(int n, int m) {',
    '    int MOD = 1000000007;',
    '    long[] prev = new long[n + 1];',
    '    long[] curr = new long[n + 1];',
    '    prev[0] = 1; // 高度为0时空树算1种',
    '    for (int j = 1; j <= m; j++) {',
    '        curr[0] = 1;',
    '        for (int i = 1; i <= n; i++) {',
    '            long sum = 0;',
    '            for (int k = 0; k < i; k++) sum = (sum + prev[k] * prev[i - 1 - k]) % MOD;',
    '            curr[i] = sum;',
    '        }',
    '        long[] tmp = prev; prev = curr; curr = tmp;',
    '    }',
    '    return (int) prev[n];',
    '}',
  ],
  cpp: [
    '// 阶段 4: 列空间压缩',
    'int compute4(int n, int m) {',
    '    const int MOD = 1000000007;',
    '    vector<long long> prev(n + 1, 0), curr(n + 1, 0);',
    '    prev[0] = 1;',
    '    for (int j = 1; j <= m; ++j) {',
    '        curr[0] = 1;',
    '        for (int i = 1; i <= n; ++i) {',
    '            long long sum = 0;',
    '            for (int k = 0; k < i; ++k) sum = (sum + prev[k] * prev[i - 1 - k]) % MOD;',
    '            curr[i] = sum;',
    '        }',
    '        prev = curr;',
    '    }',
    '    return prev[n];',
    '}',
  ],
  python: [
    '# 阶段 4: 两列滚动空间优化',
    'def compute4(n: int, m: int) -> int:',
    '    MOD = 10**9 + 7',
    '    prev = [1] + [0] * n',
    '    for j in range(1, m + 1):',
    '        curr = [1] + [0] * n',
    '        for i in range(1, n + 1):',
    '            curr[i] = sum(prev[k] * prev[i - 1 - k] for k in range(i)) % MOD',
    '        prev = curr',
    '    return prev[n]',
  ],
  javascript: [
    '// 阶段 4: 两列滚动空间优化',
    'export function compute4(n, m) {',
    '  const MOD = 1000000007;',
    '  let prev = new Array(n + 1).fill(0);',
    '  prev[0] = 1;',
    '  for (let j = 1; j <= m; j++) {',
    '    const curr = new Array(n + 1).fill(0);',
    '    curr[0] = 1;',
    '    for (let i = 1; i <= n; i++) {',
    '      let sum = 0;',
    '      for (let k = 0; k < i; k++) sum = (sum + prev[k] * prev[i - 1 - k]) % MOD;',
    '      curr[i] = sum;',
    '    }',
    '    prev = curr;',
    '  }',
    '  return prev[n];',
    '}',
  ],
};

// ==========================================
// 6. Code06 矩阵中的最长递增路径 (LeetCode 329)
// ==========================================
export const LIP_STAGE1_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    '// 阶段 1: 暴力网格 DFS 路径深度探索',
    'public static int longestIncreasingPath1(int[][] matrix) {',
    '    int m = matrix.length, n = matrix[0].length, max = 0;',
    '    for (int i = 0; i < m; i++) {',
    '        for (int j = 0; j < n; j++) {',
    '            max = Math.max(max, dfs1(matrix, i, j));',
    '        }',
    '    }',
    '    return max;',
    '}',
    'private static int dfs1(int[][] g, int i, int j) {',
    '    int ans = 1, m = g.length, n = g[0].length;',
    '    int[][] dirs = {{-1, 0}, {1, 0}, {0, -1}, {0, 1}};',
    '    for (int[] d : dirs) {',
    '        int ni = i + d[0], nj = j + d[1];',
    '        if (ni >= 0 && ni < m && nj >= 0 && nj < n && g[ni][nj] > g[i][j]) {',
    '            ans = Math.max(ans, 1 + dfs1(g, ni, nj));',
    '        }',
    '    }',
    '    return ans;',
    '}',
  ],
  cpp: [
    '// 阶段 1: 暴力网格 DFS',
    'int dfs1(const vector<vector<int>>& g, int i, int j) {',
    '    int ans = 1, m = g.size(), n = g[0].size();',
    '    int dirs[5] = {-1, 0, 1, 0, -1};',
    '    for (int d = 0; d < 4; ++d) {',
    '        int ni = i + dirs[d], nj = j + dirs[d + 1];',
    '        if (ni >= 0 && ni < m && nj >= 0 && nj < n && g[ni][nj] > g[i][j]) {',
    '            ans = max(ans, 1 + dfs1(g, ni, nj));',
    '        }',
    '    }',
    '    return ans;',
    '}',
  ],
  python: [
    '# 阶段 1: 暴力网格 DFS',
    'def dfs1(g, i, j):',
    '    ans = 1',
    '    for di, dj in ((-1,0), (1,0), (0,-1), (0,1)):',
    '        ni, nj = i + di, j + dj',
    '        if 0 <= ni < len(g) and 0 <= nj < len(g[0]) and g[ni][nj] > g[i][j]:',
    '            ans = max(ans, 1 + dfs1(g, ni, nj))',
    '    return ans',
  ],
  javascript: [
    '// 阶段 1: 暴力网格 DFS',
    'function dfs1(g, i, j) {',
    '  let ans = 1;',
    '  const dirs = [[-1,0], [1,0], [0,-1], [0,1]];',
    '  for (const [di, dj] of dirs) {',
    '    const ni = i + di, nj = j + dj;',
    '    if (ni >= 0 && ni < g.length && nj >= 0 && nj < g[0].length && g[ni][nj] > g[i][j]) {',
    '      ans = Math.max(ans, 1 + dfs1(g, ni, nj));',
    '    }',
    '  }',
    '  return ans;',
    '}',
  ],
};

export const LIP_STAGE2_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    '// 阶段 2: 记忆化搜索 (天然 DAG 无后效性)',
    'public static int longestIncreasingPath2(int[][] matrix) {',
    '    int m = matrix.length, n = matrix[0].length, max = 0;',
    '    int[][] dp = new int[m][n];',
    '    for (int i = 0; i < m; i++) {',
    '        for (int j = 0; j < n; j++) {',
    '            max = Math.max(max, dfs2(matrix, i, j, dp));',
    '        }',
    '    }',
    '    return max;',
    '}',
    'private static int dfs2(int[][] g, int i, int j, int[][] dp) {',
    '    if (dp[i][j] != 0) return dp[i][j];',
    '    int ans = 1, m = g.length, n = g[0].length;',
    '    int[][] dirs = {{-1, 0}, {1, 0}, {0, -1}, {0, 1}};',
    '    for (int[] d : dirs) {',
    '        int ni = i + d[0], nj = j + d[1];',
    '        if (ni >= 0 && ni < m && nj >= 0 && nj < n && g[ni][nj] > g[i][j]) {',
    '            ans = Math.max(ans, 1 + dfs2(g, ni, nj, dp));',
    '        }',
    '    }',
    '    return dp[i][j] = ans;',
    '}',
  ],
  cpp: [
    '// 阶段 2: 记忆化搜索',
    'int dfs2(const vector<vector<int>>& g, int i, int j, vector<vector<int>>& dp) {',
    '    if (dp[i][j]) return dp[i][j];',
    '    int ans = 1, m = g.size(), n = g[0].size();',
    '    int dirs[5] = {-1, 0, 1, 0, -1};',
    '    for (int d = 0; d < 4; ++d) {',
    '        int ni = i + dirs[d], nj = j + dirs[d + 1];',
    '        if (ni >= 0 && ni < m && nj >= 0 && nj < n && g[ni][nj] > g[i][j]) {',
    '            ans = max(ans, 1 + dfs2(g, ni, nj, dp));',
    '        }',
    '    }',
    '    return dp[i][j] = ans;',
    '}',
  ],
  python: [
    '# 阶段 2: 记忆化搜索',
    'def dfs2(g, i, j, dp):',
    '    if dp[i][j]: return dp[i][j]',
    '    ans = 1',
    '    for di, dj in ((-1,0), (1,0), (0,-1), (0,1)):',
    '        ni, nj = i + di, j + dj',
    '        if 0 <= ni < len(g) and 0 <= nj < len(g[0]) and g[ni][nj] > g[i][j]:',
    '            ans = max(ans, 1 + dfs2(g, ni, nj, dp))',
    '    dp[i][j] = ans',
    '    return ans',
  ],
  javascript: [
    '// 阶段 2: 记忆化搜索',
    'function dfs2(g, i, j, dp) {',
    '  if (dp[i][j] !== 0) return dp[i][j];',
    '  let ans = 1;',
    '  const dirs = [[-1,0], [1,0], [0,-1], [0,1]];',
    '  for (const [di, dj] of dirs) {',
    '    const ni = i + di, nj = j + dj;',
    '    if (ni >= 0 && ni < g.length && nj >= 0 && nj < g[0].length && g[ni][nj] > g[i][j]) {',
    '      ans = Math.max(ans, 1 + dfs2(g, ni, nj, dp));',
    '    }',
    '  }',
    '  return dp[i][j] = ans;',
    '}',
  ],
};

export const LIP_STAGE3_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    '// 阶段 3: 拓扑排序/DAG分层推演 (统计出度，从出度为0的汇点反推)',
    'public static int longestIncreasingPath3(int[][] matrix) {',
    '    int m = matrix.length, n = matrix[0].length;',
    '    int[][] outdegree = new int[m][n];',
    '    int[][] dirs = {{-1, 0}, {1, 0}, {0, -1}, {0, 1}};',
    '    for (int i = 0; i < m; i++) {',
    '        for (int j = 0; j < n; j++) {',
    '            for (int[] d : dirs) {',
    '                int ni = i + d[0], nj = j + d[1];',
    '                if (ni >= 0 && ni < m && nj >= 0 && nj < n && matrix[ni][nj] > matrix[i][j]) outdegree[i][j]++;',
    '            }',
    '        }',
    '    }',
    '    Queue<int[]> queue = new LinkedList<>();',
    '    for (int i = 0; i < m; i++) for (int j = 0; j < n; j++) if (outdegree[i][j] == 0) queue.offer(new int[]{i, j});',
    '    int level = 0;',
    '    while (!queue.isEmpty()) {',
    '        level++;',
    '        int size = queue.size();',
    '        for (int s = 0; s < size; s++) {',
    '            int[] cur = queue.poll();',
    '            for (int[] d : dirs) {',
    '                int ni = cur[0] + d[0], nj = cur[1] + d[1];',
    '                if (ni >= 0 && ni < m && nj >= 0 && nj < n && matrix[cur[0]][cur[1]] > matrix[ni][nj]) {',
    '                    if (--outdegree[ni][nj] == 0) queue.offer(new int[]{ni, nj});',
    '                }',
    '            }',
    '        }',
    '    }',
    '    return level;',
    '}',
  ],
  cpp: [
    '// 阶段 3: 拓扑排序推演',
    'int longestIncreasingPath3(vector<vector<int>>& matrix) {',
    '    int m = matrix.size(), n = matrix[0].size();',
    '    vector<vector<int>> outdegree(m, vector<int>(n, 0));',
    '    int dirs[4][2] = {{-1, 0}, {1, 0}, {0, -1}, {0, 1}};',
    '    for (int i = 0; i < m; i++) {',
    '        for (int j = 0; j < n; j++) {',
    '            for (auto& d : dirs) {',
    '                int ni = i + d[0], nj = j + d[1];',
    '                if (ni >= 0 && ni < m && nj >= 0 && nj < n && matrix[ni][nj] > matrix[i][j]) outdegree[i][j]++;',
    '            }',
    '        }',
    '    }',
    '    queue<pair<int, int>> q;',
    '    for (int i = 0; i < m; i++) for (int j = 0; j < n; j++) if (outdegree[i][j] == 0) q.push({i, j});',
    '    int level = 0;',
    '    while (!q.empty()) {',
    '        level++;',
    '        int size = q.size();',
    '        for (int s = 0; s < size; s++) {',
    '            auto cur = q.front(); q.pop();',
    '            for (auto& d : dirs) {',
    '                int ni = cur.first + d[0], nj = cur.second + d[1];',
    '                if (ni >= 0 && ni < m && nj >= 0 && nj < n && matrix[cur.first][cur.second] > matrix[ni][nj]) {',
    '                    if (--outdegree[ni][nj] == 0) q.push({ni, nj});',
    '                }',
    '            }',
    '        }',
    '    }',
    '    return level;',
    '}',
  ],
  python: [
    '# 阶段 3: 拓扑排序推演',
    'def longestIncreasingPath3(matrix: list[list[int]]) -> int:',
    '    m, n = len(matrix), len(matrix[0])',
    '    outdegree = [[0] * n for _ in range(m)]',
    '    dirs = [(-1, 0), (1, 0), (0, -1), (0, 1)]',
    '    for i in range(m):',
    '        for j in range(n):',
    '            for di, dj in dirs:',
    '                ni, nj = i + di, j + dj',
    '                if 0 <= ni < m and 0 <= nj < n and matrix[ni][nj] > matrix[i][j]: outdegree[i][j] += 1',
    '    queue = [(i, j) for i in range(m) for j in range(n) if outdegree[i][j] == 0]',
    '    level = 0',
    '    while queue:',
    '        level += 1',
    '        nxt = []',
    '        for r, c in queue:',
    '            for di, dj in dirs:',
    '                ni, nj = r + di, c + dj',
    '                if 0 <= ni < m and 0 <= nj < n and matrix[r][c] > matrix[ni][nj]:',
    '                    outdegree[ni][nj] -= 1',
    '                    if outdegree[ni][nj] == 0: nxt.append((ni, nj))',
    '        queue = nxt',
    '    return level',
  ],
  javascript: [
    '// 阶段 3: 拓扑排序推演',
    'export function longestIncreasingPath3(matrix) {',
    '  const m = matrix.length, n = matrix[0].length;',
    '  const outdegree = Array.from({ length: m }, () => new Array(n).fill(0));',
    '  const dirs = [[-1, 0], [1, 0], [0, -1], [0, 1]];',
    '  for (let i = 0; i < m; i++) {',
    '    for (let j = 0; j < n; j++) {',
    '      for (const [di, dj] of dirs) {',
    '        const ni = i + di, nj = j + dj;',
    '        if (ni >= 0 && ni < m && nj >= 0 && nj < n && matrix[ni][nj] > matrix[i][j]) outdegree[i][j]++;',
    '      }',
    '    }',
    '  }',
    '  let queue = [];',
    '  for (let i = 0; i < m; i++) for (let j = 0; j < n; j++) if (outdegree[i][j] === 0) queue.push([i, j]);',
    '  let level = 0;',
    '  while (queue.length > 0) {',
    '    level++;',
    '    const nxt = [];',
    '    for (const [r, c] of queue) {',
    '      for (const [di, dj] of dirs) {',
    '        const ni = r + di, nj = c + dj;',
    '        if (ni >= 0 && ni < m && nj >= 0 && nj < n && matrix[r][c] > matrix[ni][nj]) {',
    '          if (--outdegree[ni][nj] === 0) nxt.push([ni, nj]);',
    '        }',
    '      }',
    '    }',
    '    queue = nxt;',
    '  }',
    '  return level;',
    '}',
  ],
};

export const LIP_STAGE4_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    '// 阶段 4: 最长递增路径重构与沙盘追踪',
    'public static List<int[]> reconstructLongestPath(int[][] matrix, int[][] dp) {',
    '    int m = matrix.length, n = matrix[0].length;',
    '    int maxVal = 0, bi = 0, bj = 0;',
    '    for (int i = 0; i < m; i++) {',
    '        for (int j = 0; j < n; j++) {',
    '            if (dp[i][j] > maxVal) { maxVal = dp[i][j]; bi = i; bj = j; }',
    '        }',
    '    }',
    '    List<int[]> path = new ArrayList<>();',
    '    path.add(new int[]{bi, bj});',
    '    int[][] dirs = {{-1, 0}, {1, 0}, {0, -1}, {0, 1}};',
    '    while (dp[bi][bj] > 1) {',
    '        for (int[] d : dirs) {',
    '            int ni = bi + d[0], nj = bj + d[1];',
    '            if (ni >= 0 && ni < m && nj >= 0 && nj < n && matrix[ni][nj] > matrix[bi][bj] && dp[ni][nj] == dp[bi][bj] - 1) {',
    '                bi = ni; bj = nj;',
    '                path.add(new int[]{bi, bj});',
    '                break;',
    '            }',
    '        }',
    '    }',
    '    return path;',
    '}',
  ],
  cpp: [
    '// 阶段 4: 路径重构',
    'vector<pair<int, int>> reconstructPath(const vector<vector<int>>& matrix, const vector<vector<int>>& dp) {',
    '    int m = matrix.size(), n = matrix[0].size();',
    '    int maxVal = 0, bi = 0, bj = 0;',
    '    for (int i = 0; i < m; i++) {',
    '        for (int j = 0; j < n; j++) {',
    '            if (dp[i][j] > maxVal) { maxVal = dp[i][j]; bi = i; bj = j; }',
    '        }',
    '    }',
    '    vector<pair<int, int>> path;',
    '    path.push_back({bi, bj});',
    '    int dirs[4][2] = {{-1, 0}, {1, 0}, {0, -1}, {0, 1}};',
    '    while (dp[bi][bj] > 1) {',
    '        for (auto& d : dirs) {',
    '            int ni = bi + d[0], nj = bj + d[1];',
    '            if (ni >= 0 && ni < m && nj >= 0 && nj < n && matrix[ni][nj] > matrix[bi][bj] && dp[ni][nj] == dp[bi][bj] - 1) {',
    '                bi = ni; bj = nj;',
    '                path.push_back({bi, bj});',
    '                break;',
    '            }',
    '        }',
    '    }',
    '    return path;',
    '}',
  ],
  python: [
    '# 阶段 4: 路径回溯重构',
    'def reconstructPath(matrix, dp):',
    '    m, n = len(matrix), len(matrix[0])',
    '    maxVal, bi, bj = 0, 0, 0',
    '    for i in range(m):',
    '        for j in range(n):',
    '            if dp[i][j] > maxVal: maxVal, bi, bj = dp[i][j], i, j',
    '    path = [(bi, bj)]',
    '    dirs = [(-1, 0), (1, 0), (0, -1), (0, 1)]',
    '    while dp[bi][bj] > 1:',
    '        for di, dj in dirs:',
    '            ni, nj = bi + di, bj + dj',
    '            if 0 <= ni < m and 0 <= nj < n and matrix[ni][nj] > matrix[bi][bj] and dp[ni][nj] == dp[bi][bj] - 1:',
    '                bi, bj = ni, nj',
    '                path.append((bi, bj))',
    '                break',
    '    return path',
  ],
  javascript: [
    '// 阶段 4: 最长路径重构',
    'export function reconstructPath(matrix, dp) {',
    '  const m = matrix.length, n = matrix[0].length;',
    '  let maxVal = 0, bi = 0, bj = 0;',
    '  for (let i = 0; i < m; i++) {',
    '    for (let j = 0; j < n; j++) {',
    '      if (dp[i][j] > maxVal) { maxVal = dp[i][j]; bi = i; bj = j; }',
    '    }',
    '  }',
    '  const path = [[bi, bj]];',
    '  const dirs = [[-1, 0], [1, 0], [0, -1], [0, 1]];',
    '  while (dp[bi][bj] > 1) {',
    '    for (const [di, dj] of dirs) {',
    '      const ni = bi + di, nj = bj + dj;',
    '      if (ni >= 0 && ni < m && nj >= 0 && nj < n && matrix[ni][nj] > matrix[bi][bj] && dp[ni][nj] === dp[bi][bj] - 1) {',
    '        bi = ni; bj = nj;',
    '        path.push([bi, bj]);',
    '        break;',
    '      }',
    '    }',
    '  }',
    '  return path;',
    '}',
  ],
};
