/**
 * Class 053: 单调栈（下）四语言真实源码与精准 1-based 相对行号映射
 *
 * 严格准则：
 * 1. 数组第 1 项为行号 1；
 * 2. 集中定义 lines 映射，使用点只引用键名；
 * 3. Java / C++ / Python / JS 四语言语义严格对齐，严禁行号超界。
 */

// ==========================================
// 1. Code01: 统计全 1 子矩形数量 (LeetCode 1504)
// ==========================================
export const COUNT_SUBMATRICES_CODES = {
  java: [
    'public static int numSubmat(int[][] mat) {',
    '    if (mat.length == 0 || mat[0].length == 0) return 0;',
    '    int m = mat.length, n = mat[0].length, ans = 0;',
    '    int[] heights = new int[n];',
    '    int[] stack = new int[n];',
    '    for (int i = 0; i < m; i++) {',
    '        for (int j = 0; j < n; j++) heights[j] = mat[i][j] == 1 ? heights[j] + 1 : 0;',
    '        int r = 0;',
    '        for (int j = 0; j < n; j++) {',
    '            while (r > 0 && heights[stack[r - 1]] >= heights[j]) {',
    '                int cur = stack[--r];',
    '                if (heights[cur] > heights[j]) {',
    '                    int left = r > 0 ? stack[r - 1] : -1;',
    '                    int w = j - left - 1;',
    '                    int down = Math.max(left >= 0 ? heights[left] : 0, heights[j]);',
    '                    ans += (heights[cur] - down) * (w * (w + 1) / 2);',
    '                }',
    '            }',
    '            stack[r++] = j;',
    '        }',
    '        while (r > 0) {',
    '            int cur = stack[--r];',
    '            int left = r > 0 ? stack[r - 1] : -1;',
    '            int w = n - left - 1;',
    '            int down = left >= 0 ? heights[left] : 0;',
    '            ans += (heights[cur] - down) * (w * (w + 1) / 2);',
    '        }',
    '    }',
    '    return ans;',
    '}',
  ],
  cpp: [
    'int numSubmat(const vector<vector<int>>& mat) {',
    '    if (mat.empty() || mat[0].empty()) return 0;',
    '    int m = mat.size(), n = mat[0].size(), ans = 0;',
    '    vector<int> heights(n, 0), st;',
    '    for (int i = 0; i < m; i++) {',
    '        for (int j = 0; j < n; j++) heights[j] = mat[i][j] == 1 ? heights[j] + 1 : 0;',
    '        st.clear();',
    '        for (int j = 0; j < n; j++) {',
    '            while (!st.empty() && heights[st.back()] >= heights[j]) {',
    '                int cur = st.back(); st.pop_back();',
    '                if (heights[cur] > heights[j]) {',
    '                    int left = !st.empty() ? st.back() : -1;',
    '                    int w = j - left - 1;',
    '                    int down = max(left >= 0 ? heights[left] : 0, heights[j]);',
    '                    ans += (heights[cur] - down) * (w * (w + 1) / 2);',
    '                }',
    '            }',
    '            st.push_back(j);',
    '        }',
    '        while (!st.empty()) {',
    '            int cur = st.back(); st.pop_back();',
    '            int left = !st.empty() ? st.back() : -1;',
    '            int w = n - left - 1;',
    '            int down = left >= 0 ? heights[left] : 0;',
    '            ans += (heights[cur] - down) * (w * (w + 1) / 2);',
    '        }',
    '    }',
    '    return ans;',
    '}',
  ],
  python: [
    'def num_submat(mat):',
    '    if not mat or not mat[0]: return 0',
    '    m, n, ans = len(mat), len(mat[0]), 0',
    '    heights = [0] * n',
    '    for i in range(m):',
    '        for j in range(n): heights[j] = heights[j] + 1 if mat[i][j] == 1 else 0',
    '        stack = []',
    '        for j in range(n):',
    '            while stack and heights[stack[-1]] >= heights[j]:',
    '                cur = stack.pop()',
    '                if heights[cur] > heights[j]:',
    '                    left = stack[-1] if stack else -1',
    '                    w = j - left - 1',
    '                    down = max(heights[left] if left >= 0 else 0, heights[j])',
    '                    ans += (heights[cur] - down) * (w * (w + 1) // 2)',
    '            stack.append(j)',
    '        while stack:',
    '            cur = stack.pop()',
    '            left = stack[-1] if stack else -1',
    '            w = n - left - 1',
    '            down = heights[left] if left >= 0 else 0',
    '            ans += (heights[cur] - down) * (w * (w + 1) // 2)',
    '    return ans',
  ],
  javascript: [
    'function numSubmat(mat) {',
    '  if (!mat.length || !mat[0].length) return 0;',
    '  const m = mat.length, n = mat[0].length;',
    '  let ans = 0;',
    '  const heights = new Array(n).fill(0);',
    '  for (let i = 0; i < m; i++) {',
    '    for (let j = 0; j < n; j++) heights[j] = mat[i][j] === 1 ? heights[j] + 1 : 0;',
    '    const stack = [];',
    '    for (let j = 0; j < n; j++) {',
    '      while (stack.length > 0 && heights[stack[stack.length - 1]] >= heights[j]) {',
    '        const cur = stack.pop();',
    '        if (heights[cur] > heights[j]) {',
    '          const left = stack.length > 0 ? stack[stack.length - 1] : -1;',
    '          const w = j - left - 1;',
    '          const down = Math.max(left >= 0 ? heights[left] : 0, heights[j]);',
    '          ans += (heights[cur] - down) * ((w * (w + 1)) / 2);',
    '        }',
    '      }',
    '      stack.push(j);',
    '    }',
    '    while (stack.length > 0) {',
    '      const cur = stack.pop();',
    '      const left = stack.length > 0 ? stack[stack.length - 1] : -1;',
    '      const w = n - left - 1;',
    '      const down = left >= 0 ? heights[left] : 0;',
    '      ans += (heights[cur] - down) * ((w * (w + 1)) / 2);',
    '    }',
    '  }',
    '  return ans;',
    '}',
  ],
};

export const COUNT_SUBMATRICES_LINES = {
  entry: { java: 1, cpp: 1, python: 1, javascript: 1 },
  updateRow: { java: 7, cpp: 6, python: 6, javascript: 7 },
  whileCheck: { java: 10, cpp: 9, python: 9, javascript: 10 },
  popCalc: { java: 11, cpp: 10, python: 10, javascript: 11 },
  push: { java: 19, cpp: 18, python: 16, javascript: 19 },
  clearPop: { java: 22, cpp: 21, python: 18, javascript: 22 },
  returnAns: { java: 29, cpp: 28, python: 23, javascript: 29 },
};

// ==========================================
// 2. Code02: 大鱼吃小鱼问题
// ==========================================
export const BIG_FISH_EAT_CODES = {
  java: [
    'public static int totalTurns(int[] arr) {',
    '    int n = arr.length, ans = 0;',
    '    int[][] stack = new int[n][2]; // [0]:鱼体重, [1]:吃掉需要的轮数',
    '    int r = 0;',
    '    for (int i = 0; i < n; i++) {',
    '        int curTurns = 0;',
    '        while (r > 0 && stack[r - 1][0] <= arr[i]) {',
    '            curTurns = Math.max(curTurns, stack[--r][1]);',
    '        }',
    '        curTurns = r > 0 ? curTurns + 1 : 0;',
    '        ans = Math.max(ans, curTurns);',
    '        stack[r][0] = arr[i]; stack[r++][1] = curTurns;',
    '    }',
    '    return ans;',
    '}',
  ],
  cpp: [
    'int totalTurns(const vector<int>& arr) {',
    '    int n = arr.size(), ans = 0;',
    '    vector<pair<int, int>> st; // {体重, 轮数}',
    '    for (int i = 0; i < n; i++) {',
    '        int curTurns = 0;',
    '        while (!st.empty() && st.back().first <= arr[i]) {',
    '            curTurns = max(curTurns, st.back().second);',
    '            st.pop_back();',
    '        }',
    '        curTurns = !st.empty() ? curTurns + 1 : 0;',
    '        ans = max(ans, curTurns);',
    '        st.push_back({arr[i], curTurns});',
    '    }',
    '    return ans;',
    '}',
  ],
  python: [
    'def total_turns(arr):',
    '    n, ans = len(arr), 0',
    '    stack = []  # (体重, 轮数)',
    '    for val in arr:',
    '        cur_turns = 0',
    '        while stack and stack[-1][0] <= val:',
    '            cur_turns = max(cur_turns, stack.pop()[1])',
    '        cur_turns = cur_turns + 1 if stack else 0',
    '        ans = max(ans, cur_turns)',
    '        stack.append((val, cur_turns))',
    '    return ans',
  ],
  javascript: [
    'function totalTurns(arr) {',
    '  const n = arr.length;',
    '  let ans = 0;',
    '  const stack = []; // [val, turns]',
    '  for (let i = 0; i < n; i++) {',
    '    let curTurns = 0;',
    '    while (stack.length > 0 && stack[stack.length - 1][0] <= arr[i]) {',
    '      curTurns = Math.max(curTurns, stack.pop()[1]);',
    '    }',
    '    curTurns = stack.length > 0 ? curTurns + 1 : 0;',
    '    ans = Math.max(ans, curTurns);',
    '    stack.push([arr[i], curTurns]);',
    '  }',
    '  return ans;',
    '}',
  ],
};

export const BIG_FISH_EAT_LINES = {
  entry: { java: 1, cpp: 1, python: 1, javascript: 1 },
  init: { java: 3, cpp: 3, python: 3, javascript: 4 },
  forLoop: { java: 5, cpp: 4, python: 4, javascript: 5 },
  whileEat: { java: 7, cpp: 6, python: 6, javascript: 7 },
  updateTurns: { java: 10, cpp: 10, python: 8, javascript: 10 },
  push: { java: 12, cpp: 12, python: 10, javascript: 12 },
  returnAns: { java: 14, cpp: 14, python: 11, javascript: 14 },
};

// ==========================================
// 3. Code03: 移掉 K 位数字 (LeetCode 402)
// ==========================================
export const REMOVE_K_DIGITS_CODES = {
  java: [
    'public static String removeKdigits(String num, int k) {',
    '    if (num.length() <= k) return "0";',
    '    char[] stack = new char[num.length()];',
    '    int top = 0;',
    '    for (int i = 0; i < num.length(); i++) {',
    '        char c = num.charAt(i);',
    '        while (k > 0 && top > 0 && stack[top - 1] > c) {',
    '            top--; k--; // 弹出逆序高位峰值',
    '        }',
    '        stack[top++] = c;',
    '    }',
    '    top -= k; // 若 k 仍有剩余，从末尾削减',
    '    int idx = 0;',
    '    while (idx < top && stack[idx] == "0") idx++; // 去前导 0',
    '    return idx == top ? "0" : new String(stack, idx, top - idx);',
    '}',
  ],
  cpp: [
    'string removeKdigits(string num, int k) {',
    '    if (num.length() <= k) return "0";',
    '    string st = "";',
    '    for (char c : num) {',
    '        while (k > 0 && !st.empty() && st.back() > c) {',
    '            st.pop_back(); k--;',
    '        }',
    '        st.push_back(c);',
    '    }',
    '    while (k > 0) { st.pop_back(); k--; }',
    '    int idx = 0;',
    '    while (idx < st.size() && st[idx] == "0") idx++;',
    '    string ans = st.substr(idx);',
    '    return ans.empty() ? "0" : ans;',
    '}',
  ],
  python: [
    'def remove_kdigits(num, k):',
    '    if len(num) <= k: return "0"',
    '    stack = []',
    '    for c in num:',
    '        while k > 0 and stack and stack[-1] > c:',
    '            stack.pop()',
    '            k -= 1',
    '        stack.append(c)',
    '    final_stack = stack[:-k] if k > 0 else stack',
    '    res = "".join(final_stack).lstrip("0")',
    '    return res if res else "0"',
  ],
  javascript: [
    'function removeKdigits(num, k) {',
    '  if (num.length <= k) return "0";',
    '  const stack = [];',
    '  for (let i = 0; i < num.length; i++) {',
    '    const c = num[i];',
    '    while (k > 0 && stack.length > 0 && stack[stack.length - 1] > c) {',
    '      stack.pop(); k--;',
    '    }',
    '    stack.push(c);',
    '  }',
    '  while (k > 0) { stack.pop(); k--; }',
    '  let idx = 0;',
    '  while (idx < stack.length && stack[idx] === "0") idx++;',
    '  const res = stack.slice(idx).join("");',
    '  return res.length === 0 ? "0" : res;',
    '}',
  ],
};

export const REMOVE_K_DIGITS_LINES = {
  entry: { java: 1, cpp: 1, python: 1, javascript: 1 },
  init: { java: 3, cpp: 3, python: 3, javascript: 3 },
  forLoop: { java: 5, cpp: 4, python: 4, javascript: 4 },
  whilePop: { java: 7, cpp: 5, python: 5, javascript: 6 },
  push: { java: 10, cpp: 8, python: 8, javascript: 9 },
  trimK: { java: 12, cpp: 10, python: 9, javascript: 11 },
  returnAns: { java: 15, cpp: 14, python: 11, javascript: 15 },
};

// ==========================================
// 4. Code04: 去除重复字母 (LeetCode 316 / 1081)
// ==========================================
export const REMOVE_DUP_LETTERS_CODES = {
  java: [
    'public static String removeDuplicateLetters(String s) {',
    '    int[] count = new int[26];',
    '    boolean[] inStack = new boolean[26];',
    '    char[] stack = new char[s.length()];',
    '    int top = 0;',
    '    for (int i = 0; i < s.length(); i++) count[s.charAt(i) - "a"]++;',
    '    for (int i = 0; i < s.length(); i++) {',
    '        char c = s.charAt(i);',
    '        count[c - "a"]--;',
    '        if (inStack[c - "a"]) continue; // 已在栈中直接跳过',
    '        while (top > 0 && stack[top - 1] > c && count[stack[top - 1] - "a"] > 0) {',
    '            inStack[stack[--top] - "a"] = false; // 后续还会出现，弹出让位',
    '        }',
    '        stack[top++] = c;',
    '        inStack[c - "a"] = true;',
    '    }',
    '    return new String(stack, 0, top);',
    '}',
  ],
  cpp: [
    'string removeDuplicateLetters(string s) {',
    '    vector<int> count(26, 0);',
    '    vector<bool> inStack(26, false);',
    '    string st = "";',
    '    for (char c : s) count[c - "a"]++;',
    '    for (char c : s) {',
    '        count[c - "a"]--;',
    '        if (inStack[c - "a"]) continue;',
    '        while (!st.empty() && st.back() > c && count[st.back() - "a"] > 0) {',
    '            inStack[st.back() - "a"] = false;',
    '            st.pop_back();',
    '        }',
    '        st.push_back(c);',
    '        inStack[c - "a"] = true;',
    '    }',
    '    return st;',
    '}',
  ],
  python: [
    'def remove_duplicate_letters(s):',
    '    count = {c: s.count(c) for c in set(s)}',
    '    in_stack, stack = set(), []',
    '    for c in s:',
    '        count[c] -= 1',
    '        if c in in_stack: continue',
    '        while stack and stack[-1] > c and count[stack[-1]] > 0:',
    '            in_stack.remove(stack.pop())',
    '        stack.append(c)',
    '        in_stack.add(c)',
    '    return "".join(stack)',
  ],
  javascript: [
    'function removeDuplicateLetters(s) {',
    '  const count = {};',
    '  for (const c of s) count[c] = (count[c] || 0) + 1;',
    '  const inStack = new Set();',
    '  const stack = [];',
    '  for (let i = 0; i < s.length; i++) {',
    '    const c = s[i];',
    '    count[c]--;',
    '    if (inStack.has(c)) continue;',
    '    while (stack.length > 0 && stack[stack.length - 1] > c && count[stack[stack.length - 1]] > 0) {',
    '      inStack.delete(stack.pop());',
    '    }',
    '    stack.push(c);',
    '    inStack.add(c);',
    '  }',
    '  return stack.join("");',
    '}',
  ],
};

export const REMOVE_DUP_LETTERS_LINES = {
  entry: { java: 1, cpp: 1, python: 1, javascript: 1 },
  countFreq: { java: 6, cpp: 5, python: 2, javascript: 3 },
  forLoop: { java: 7, cpp: 6, python: 4, javascript: 6 },
  skipInStack: { java: 10, cpp: 8, python: 6, javascript: 9 },
  whilePop: { java: 11, cpp: 9, python: 7, javascript: 10 },
  push: { java: 14, cpp: 13, python: 9, javascript: 13 },
  returnAns: { java: 17, cpp: 16, python: 11, javascript: 16 },
};

// ==========================================
// 5. Code05: 表现良好的最长时间段 (LeetCode 1124)
// ==========================================
export const LONGEST_WPI_CODES = {
  java: [
    'public static int longestWPI(int[] hours) {',
    '    int n = hours.length, maxLen = 0;',
    '    int[] prefix = new int[n + 1];',
    '    for (int i = 0; i < n; i++) prefix[i + 1] = prefix[i] + (hours[i] > 8 ? 1 : -1);',
    '    int[] stack = new int[n + 1];',
    '    int r = 0;',
    '    for (int i = 0; i <= n; i++) {',
    '        if (r == 0 || prefix[stack[r - 1]] > prefix[i]) stack[r++] = i; // 严格单调递减栈',
    '    }',
    '    for (int j = n; j >= 0; j--) { // 倒序寻找最大跨度',
    '        while (r > 0 && prefix[j] > prefix[stack[r - 1]]) {',
    '            maxLen = Math.max(maxLen, j - stack[--r]);',
    '        }',
    '    }',
    '    return maxLen;',
    '}',
  ],
  cpp: [
    'int longestWPI(const vector<int>& hours) {',
    '    int n = hours.size(), maxLen = 0;',
    '    vector<int> prefix(n + 1, 0), st;',
    '    for (int i = 0; i < n; i++) prefix[i + 1] = prefix[i] + (hours[i] > 8 ? 1 : -1);',
    '    for (int i = 0; i <= n; i++) {',
    '        if (st.empty() || prefix[st.back()] > prefix[i]) st.push_back(i);',
    '    }',
    '    for (int j = n; j >= 0; j--) {',
    '        while (!st.empty() && prefix[j] > prefix[st.back()]) {',
    '            maxLen = max(maxLen, j - st.back());',
    '            st.pop_back();',
    '        }',
    '    }',
    '    return maxLen;',
    '}',
  ],
  python: [
    'def longest_wpi(hours):',
    '    n, max_len = len(hours), 0',
    '    prefix = [0] * (n + 1)',
    '    for i, h in enumerate(hours): prefix[i + 1] = prefix[i] + (1 if h > 8 else -1)',
    '    stack = []',
    '    for i in range(n + 1):',
    '        if not stack or prefix[stack[-1]] > prefix[i]: stack.append(i)',
    '    for j in range(n, -1, -1):',
    '        while stack and prefix[j] > prefix[stack[-1]]:',
    '            max_len = max(max_len, j - stack.pop())',
    '    return max_len',
  ],
  javascript: [
    'function longestWPI(hours) {',
    '  const n = hours.length;',
    '  let maxLen = 0;',
    '  const prefix = new Array(n + 1).fill(0);',
    '  for (let i = 0; i < n; i++) prefix[i + 1] = prefix[i] + (hours[i] > 8 ? 1 : -1);',
    '  const stack = [];',
    '  for (let i = 0; i <= n; i++) {',
    '    if (stack.length === 0 || prefix[stack[stack.length - 1]] > prefix[i]) stack.push(i);',
    '  }',
    '  for (let j = n; j >= 0; j--) {',
    '    while (stack.length > 0 && prefix[j] > prefix[stack[stack.length - 1]]) {',
    '      maxLen = Math.max(maxLen, j - stack.pop());',
    '    }',
    '  }',
    '  return maxLen;',
    '}',
  ],
};

export const LONGEST_WPI_LINES = {
  entry: { java: 1, cpp: 1, python: 1, javascript: 1 },
  calcPrefix: { java: 4, cpp: 4, python: 4, javascript: 5 },
  buildStack: { java: 7, cpp: 5, python: 6, javascript: 7 },
  reverseLoop: { java: 10, cpp: 8, python: 8, javascript: 10 },
  updateMaxLen: { java: 11, cpp: 9, python: 9, javascript: 11 },
  returnAns: { java: 15, cpp: 14, python: 11, javascript: 15 },
};

// ==========================================
// 6. Code06: 子数组最小乘积的最大值 (LeetCode 1856)
// ==========================================
export const MAX_SUBARRAY_MIN_PROD_CODES = {
  java: [
    'public static int maxSumMinProduct(int[] nums) {',
    '    int n = nums.length;',
    '    long[] prefix = new long[n + 1];',
    '    for (int i = 0; i < n; i++) prefix[i + 1] = prefix[i] + nums[i];',
    '    int[] stack = new int[n];',
    '    int r = 0;',
    '    long maxProd = 0;',
    '    for (int i = 0; i < n; i++) {',
    '        while (r > 0 && nums[stack[r - 1]] >= nums[i]) {',
    '            int cur = stack[--r];',
    '            int left = r > 0 ? stack[r - 1] : -1;',
    '            long sum = prefix[i] - prefix[left + 1];',
    '            maxProd = Math.max(maxProd, sum * nums[cur]);',
    '        }',
    '        stack[r++] = i;',
    '    }',
    '    while (r > 0) {',
    '        int cur = stack[--r];',
    '        int left = r > 0 ? stack[r - 1] : -1;',
    '        long sum = prefix[n] - prefix[left + 1];',
    '        maxProd = Math.max(maxProd, sum * nums[cur]);',
    '    }',
    '    return (int) (maxProd % 1000000007);',
    '}',
  ],
  cpp: [
    'int maxSumMinProduct(const vector<int>& nums) {',
    '    int n = nums.size();',
    '    vector<long long> prefix(n + 1, 0);',
    '    for (int i = 0; i < n; i++) prefix[i + 1] = prefix[i] + nums[i];',
    '    vector<int> st;',
    '    long long maxProd = 0;',
    '    for (int i = 0; i < n; i++) {',
    '        while (!st.empty() && nums[st.back()] >= nums[i]) {',
    '            int cur = st.back(); st.pop_back();',
    '            int left = !st.empty() ? st.back() : -1;',
    '            long long sum = prefix[i] - prefix[left + 1];',
    '            maxProd = max(maxProd, sum * nums[cur]);',
    '        }',
    '        st.push_back(i);',
    '    }',
    '    while (!st.empty()) {',
    '        int cur = st.back(); st.pop_back();',
    '        int left = !st.empty() ? st.back() : -1;',
    '        long long sum = prefix[n] - prefix[left + 1];',
    '        maxProd = max(maxProd, sum * nums[cur]);',
    '    }',
    '    return maxProd % 1000000007;',
    '}',
  ],
  python: [
    'def max_sum_min_product(nums):',
    '    n = len(nums)',
    '    prefix = [0] * (n + 1)',
    '    for i in range(n): prefix[i + 1] = prefix[i] + nums[i]',
    '    stack = []',
    '    max_prod = 0',
    '    for i in range(n):',
    '        while stack and nums[stack[-1]] >= nums[i]:',
    '            cur = stack.pop()',
    '            left = stack[-1] if stack else -1',
    '            total = prefix[i] - prefix[left + 1]',
    '            max_prod = max(max_prod, total * nums[cur])',
    '        stack.append(i)',
    '    while stack:',
    '        cur = stack.pop()',
    '        left = stack[-1] if stack else -1',
    '        total = prefix[n] - prefix[left + 1]',
    '        max_prod = max(max_prod, total * nums[cur])',
    '    return max_prod % 1000000007',
  ],
  javascript: [
    'function maxSumMinProduct(nums) {',
    '  const n = nums.length;',
    '  const prefix = new BigInt64Array(n + 1);',
    '  for (let i = 0; i < n; i++) prefix[i + 1] = prefix[i] + BigInt(nums[i]);',
    '  const stack = [];',
    '  let maxProd = 0n;',
    '  for (let i = 0; i < n; i++) {',
    '    while (stack.length > 0 && nums[stack[stack.length - 1]] >= nums[i]) {',
    '      const cur = stack.pop();',
    '      const left = stack.length > 0 ? stack[stack.length - 1] : -1;',
    '      const sum = prefix[i] - prefix[left + 1];',
    '      const prod = sum * BigInt(nums[cur]);',
    '      if (prod > maxProd) maxProd = prod;',
    '    }',
    '    stack.push(i);',
    '  }',
    '  while (stack.length > 0) {',
    '    const cur = stack.pop();',
    '    const left = stack.length > 0 ? stack[stack.length - 1] : -1;',
    '    const sum = prefix[n] - prefix[left + 1];',
    '    const prod = sum * BigInt(nums[cur]);',
    '    if (prod > maxProd) maxProd = prod;',
    '  }',
    '  return Number(maxProd % 1000000007n);',
    '}',
  ],
};

export const MAX_SUBARRAY_MIN_PROD_LINES = {
  entry: { java: 1, cpp: 1, python: 1, javascript: 1 },
  calcPrefix: { java: 4, cpp: 4, python: 4, javascript: 4 },
  forLoop: { java: 8, cpp: 7, python: 7, javascript: 7 },
  whilePop: { java: 9, cpp: 8, python: 8, javascript: 8 },
  push: { java: 15, cpp: 14, python: 13, javascript: 15 },
  clearPop: { java: 18, cpp: 17, python: 15, javascript: 18 },
  returnAns: { java: 23, cpp: 23, python: 19, javascript: 25 },
};

export const BIG_FISH_CODES = BIG_FISH_EAT_CODES;
export const BIG_FISH_LINES = BIG_FISH_EAT_LINES;

