/**
 * 左程云 Class 066 四语言核心算法实现与 1-based 行号字典映射
 * Java / C++ / Python / JavaScript
 */

export const MIN_COST_TICKETS_066_CODES: Record<string, string[]> = {
  java: [
    'package class066;',
    'import java.util.Arrays;',
    '',
    '// 最低票价 (LeetCode 983)',
    'public class Code02_MinimumCostForTickets {',
    '    public static int mincostTickets(int[] days, int[] costs) {',
    '        int n = days.length;',
    '        int[] dp = new int[n + 1];',
    '        int[] duration = {1, 7, 30};',
    '        for (int i = n - 1; i >= 0; i--) {',
    '            int ans = Integer.MAX_VALUE;',
    '            for (int k = 0, j = i; k < 3; k++) {',
    '                while (j < n && days[j] < days[i] + duration[k]) {',
    '                    j++;',
    '                }',
    '                ans = Math.min(ans, costs[k] + dp[j]);',
    '            }',
    '            dp[i] = ans;',
    '        }',
    '        return dp[0];',
    '    }',
    '}',
  ],
  cpp: [
    '#include <vector>',
    '#include <algorithm>',
    'using namespace std;',
    '',
    '// 最低票价 (LeetCode 983)',
    'class Solution {',
    'public:',
    '    int mincostTickets(vector<int>& days, vector<int>& costs) {',
    '        int n = days.size();',
    '        vector<int> dp(n + 1, 0);',
    '        int duration[3] = {1, 7, 30};',
    '        for (int i = n - 1; i >= 0; i--) {',
    '            int ans = 1e9;',
    '            for (int k = 0, j = i; k < 3; k++) {',
    '                while (j < n && days[j] < days[i] + duration[k]) j++;',
    '                ans = min(ans, costs[k] + dp[j]);',
    '            }',
    '            dp[i] = ans;',
    '        }',
    '        return dp[0];',
    '    }',
    '};',
  ],
  python: [
    'class Solution:',
    '    def mincostTickets(self, days: list[int], costs: list[int]) -> int:',
    '        n = len(days)',
    '        dp = [0] * (n + 1)',
    '        durations = [1, 7, 30]',
    '        for i in range(n - 1, -1, -1):',
    '            ans = float("inf")',
    '            j = i',
    '            for k in range(3):',
    '                while j < n and days[j] < days[i] + durations[k]:',
    '                    j += 1',
    '                ans = min(ans, costs[k] + dp[j])',
    '            dp[i] = ans',
    '        return dp[0]',
  ],
  javascript: [
    '// 最低票价 (LeetCode 983)',
    'function mincostTickets(days, costs) {',
    '    const n = days.length;',
    '    const dp = new Array(n + 1).fill(0);',
    '    const durations = [1, 7, 30];',
    '    for (let i = n - 1; i >= 0; i--) {',
    '        let ans = Infinity;',
    '        let j = i;',
    '        for (let k = 0; k < 3; k++) {',
    '            while (j < n && days[j] < days[i] + durations[k]) {',
    '                j++;',
    '            }',
    '            ans = Math.min(ans, costs[k] + dp[j]);',
    '        }',
    '        dp[i] = ans;',
    '    }',
    '    return dp[0];',
    '}',
  ],
};

export const MIN_COST_TICKETS_066_LINES = {
  entry: { java: 6, cpp: 8, python: 2, javascript: 2 },
  initDp: { java: 8, cpp: 10, python: 4, javascript: 4 },
  outerLoop: { java: 10, cpp: 12, python: 6, javascript: 6 },
  branchLoop: { java: 12, cpp: 14, python: 9, javascript: 9 },
  skipDays: { java: 13, cpp: 15, python: 10, javascript: 10 },
  updateAns: { java: 16, cpp: 16, python: 12, javascript: 13 },
  saveDp: { java: 18, cpp: 18, python: 13, javascript: 15 },
  returnAns: { java: 20, cpp: 20, python: 14, javascript: 17 },
};

export const DECODE_WAYS_II_066_CODES: Record<string, string[]> = {
  java: [
    'package class066;',
    '',
    '// 解码方法 II (LeetCode 639)',
    'public class Code04_DecodeWaysII {',
    '    public static int numDecodings(String s) {',
    '        final int MOD = 1000000007;',
    '        char[] str = s.toCharArray();',
    '        int n = str.length;',
    '        long next2 = 0, next1 = 1, cur = 0;',
    '        for (int i = n - 1; i >= 0; i--) {',
    '            char c = str[i];',
    '            if (c == \'*\') {',
    '                cur = 9 * next1;',
    '            } else if (c != \'0\') {',
    '                cur = next1;',
    '            } else {',
    '                cur = 0;',
    '            }',
    '            if (i + 1 < n) {',
    '                char nxt = str[i + 1];',
    '                if (c == \'*\') {',
    '                    if (nxt == \'*\') cur += 15 * next2;',
    '                    else if (nxt <= \'6\') cur += 2 * next2;',
    '                    else cur += next2;',
    '                } else if (c == \'1\') {',
    '                    cur += (nxt == \'*\') ? 9 * next2 : next2;',
    '                } else if (c == \'2\') {',
    '                    if (nxt == \'*\') cur += 6 * next2;',
    '                    else if (nxt <= \'6\') cur += next2;',
    '                }',
    '            }',
    '            cur %= MOD;',
    '            next2 = next1;',
    '            next1 = cur;',
    '        }',
    '        return (int) next1;',
    '    }',
    '}',
  ],
  cpp: [
    '#include <string>',
    'using namespace std;',
    '',
    '// 解码方法 II (LeetCode 639)',
    'class Solution {',
    'public:',
    '    int numDecodings(string s) {',
    '        const int MOD = 1e9 + 7;',
    '        int n = s.size();',
    '        long long next2 = 0, next1 = 1, cur = 0;',
    '        for (int i = n - 1; i >= 0; i--) {',
    '            char c = s[i];',
    '            if (c == \'*\') cur = 9 * next1;',
    '            else if (c != \'0\') cur = next1;',
    '            else cur = 0;',
    '            if (i + 1 < n) {',
    '                char nxt = s[i + 1];',
    '                if (c == \'*\') {',
    '                    if (nxt == \'*\') cur += 15 * next2;',
    '                    else if (nxt <= \'6\') cur += 2 * next2;',
    '                    else cur += next2;',
    '                } else if (c == \'1\') {',
    '                    cur += (nxt == \'*\') ? 9 * next2 : next2;',
    '                } else if (c == \'2\') {',
    '                    if (nxt == \'*\') cur += 6 * next2;',
    '                    else if (nxt <= \'6\') cur += next2;',
    '                }',
    '            }',
    '            cur %= MOD;',
    '            next2 = next1;',
    '            next1 = cur;',
    '        }',
    '        return next1;',
    '    }',
    '};',
  ],
  python: [
    'class Solution:',
    '    def numDecodings(self, s: str) -> int:',
    '        MOD = 10**9 + 7',
    '        n = len(s)',
    '        next2, next1 = 0, 1',
    '        for i in range(n - 1, -1, -1):',
    '            c = s[i]',
    '            cur = (9 * next1) if c == "*" else (next1 if c != "0" else 0)',
    '            if i + 1 < n:',
    '                nxt = s[i + 1]',
    '                if c == "*":',
    '                    if nxt == "*": cur += 15 * next2',
    '                    elif nxt <= "6": cur += 2 * next2',
    '                    else: cur += next2',
    '                elif c == "1":',
    '                    cur += (9 * next2) if nxt == "*" else next2',
    '                elif c == "2":',
    '                    if nxt == "*": cur += 6 * next2',
    '                    elif nxt <= "6": cur += next2',
    '            cur %= MOD',
    '            next2, next1 = next1, cur',
    '        return next1',
  ],
  javascript: [
    '// 解码方法 II (LeetCode 639)',
    'function numDecodings(s) {',
    '    const MOD = 1000000007n;',
    '    const n = s.length;',
    '    let next2 = 0n, next1 = 1n, cur = 0n;',
    '    for (let i = n - 1; i >= 0; i--) {',
    '        const c = s[i];',
    '        if (c === "*") cur = 9n * next1;',
    '        else if (c !== "0") cur = next1;',
    '        else cur = 0n;',
    '        if (i + 1 < n) {',
    '            const nxt = s[i + 1];',
    '            if (c === "*") {',
    '                if (nxt === "*") cur += 15n * next2;',
    '                else if (nxt <= "6") cur += 2n * next2;',
    '                else cur += next2;',
    '            } else if (c === "1") {',
    '                cur += (nxt === "*") ? 9n * next2 : next2;',
    '            } else if (c === "2") {',
    '                if (nxt === "*") cur += 6n * next2;',
    '                else if (nxt <= "6") cur += next2;',
    '            }',
    '        }',
    '        cur %= MOD;',
    '        next2 = next1;',
    '        next1 = cur;',
    '    }',
    '    return Number(next1);',
    '}',
  ],
};

export const DECODE_WAYS_II_066_LINES = {
  entry: { java: 5, cpp: 7, python: 2, javascript: 2 },
  initVars: { java: 9, cpp: 10, python: 5, javascript: 5 },
  loopScan: { java: 10, cpp: 11, python: 6, javascript: 6 },
  singleChar: { java: 12, cpp: 13, python: 8, javascript: 8 },
  doubleChar: { java: 19, cpp: 18, python: 11, javascript: 13 },
  shiftRolling: { java: 30, cpp: 27, python: 20, javascript: 24 },
  returnAns: { java: 33, cpp: 30, python: 21, javascript: 27 },
};

export const UGLY_NUMBER_II_066_CODES: Record<string, string[]> = {
  java: [
    'package class066;',
    '',
    '// 丑数 II (LeetCode 264)',
    'public class Code05_UglyNumberII {',
    '    public static int nthUglyNumber(int n) {',
    '        int[] dp = new int[n + 1];',
    '        dp[1] = 1;',
    '        int i2 = 1, i3 = 1, i5 = 1;',
    '        for (int i = 2; i <= n; i++) {',
    '            int a = dp[i2] * 2;',
    '            int b = dp[i3] * 3;',
    '            int c = dp[i5] * 5;',
    '            int cur = Math.min(a, Math.min(b, c));',
    '            if (cur == a) i2++;',
    '            if (cur == b) i3++;',
    '            if (cur == c) i5++;',
    '            dp[i] = cur;',
    '        }',
    '        return dp[n];',
    '    }',
    '}',
  ],
  cpp: [
    '#include <vector>',
    '#include <algorithm>',
    'using namespace std;',
    '',
    '// 丑数 II (LeetCode 264)',
    'class Solution {',
    'public:',
    '    int nthUglyNumber(int n) {',
    '        vector<int> dp(n + 1, 0);',
    '        dp[1] = 1;',
    '        int i2 = 1, i3 = 1, i5 = 1;',
    '        for (int i = 2; i <= n; i++) {',
    '            int a = dp[i2] * 2, b = dp[i3] * 3, c = dp[i5] * 5;',
    '            int cur = min({a, b, c});',
    '            if (cur == a) i2++;',
    '            if (cur == b) i3++;',
    '            if (cur == c) i5++;',
    '            dp[i] = cur;',
    '        }',
    '        return dp[n];',
    '    }',
    '};',
  ],
  python: [
    'class Solution:',
    '    def nthUglyNumber(self, n: int) -> int:',
    '        dp = [0] * (n + 1)',
    '        dp[1] = 1',
    '        i2 = i3 = i5 = 1',
    '        for i in range(2, n + 1):',
    '            a, b, c = dp[i2] * 2, dp[i3] * 3, dp[i5] * 5',
    '            cur = min(a, b, c)',
    '            if cur == a: i2 += 1',
    '            if cur == b: i3 += 1',
    '            if cur == c: i5 += 1',
    '            dp[i] = cur',
    '        return dp[n]',
  ],
  javascript: [
    '// 丑数 II (LeetCode 264)',
    'function nthUglyNumber(n) {',
    '    const dp = new Array(n + 1).fill(0);',
    '    dp[1] = 1;',
    '    let i2 = 1, i3 = 1, i5 = 1;',
    '    for (let i = 2; i <= n; i++) {',
    '        const a = dp[i2] * 2;',
    '        const b = dp[i3] * 3;',
    '        const c = dp[i5] * 5;',
    '        const cur = Math.min(a, b, c);',
    '        if (cur === a) i2++;',
    '        if (cur === b) i3++;',
    '        if (cur === c) i5++;',
    '        dp[i] = cur;',
    '    }',
    '    return dp[n];',
    '}',
  ],
};

export const UGLY_NUMBER_II_066_LINES = {
  entry: { java: 5, cpp: 8, python: 2, javascript: 2 },
  initPointers: { java: 8, cpp: 10, python: 5, javascript: 5 },
  loopN: { java: 9, cpp: 11, python: 6, javascript: 6 },
  computeMultiples: { java: 10, cpp: 12, python: 7, javascript: 7 },
  pickMin: { java: 13, cpp: 13, python: 8, javascript: 10 },
  advancePointers: { java: 14, cpp: 14, python: 9, javascript: 11 },
  saveDp: { java: 17, cpp: 17, python: 12, javascript: 14 },
  returnAns: { java: 19, cpp: 19, python: 13, javascript: 16 },
};

export const UNIQUE_SUBSTRINGS_WRAPAROUND_066_CODES: Record<string, string[]> = {
  java: [
    'package class066;',
    '',
    '// 环绕字符串中唯一的子字符串 (LeetCode 467)',
    'public class Code07_UniqueSubstringsInWraparoundString {',
    '    public static int findSubstringInWraproundString(String s) {',
    '        char[] str = s.toCharArray();',
    '        int n = str.length;',
    '        int[] dp = new int[26];',
    '        dp[str[0] - \'a\'] = 1;',
    '        for (int i = 1, cur = 1; i < n; i++) {',
    '            char pre = str[i - 1];',
    '            char c = str[i];',
    '            if ((pre == \'z\' && c == \'a\') || pre + 1 == c) {',
    '                cur++;',
    '            } else {',
    '                cur = 1;',
    '            }',
    '            dp[c - \'a\'] = Math.max(dp[c - \'a\'], cur);',
    '        }',
    '        int ans = 0;',
    '        for (int x : dp) ans += x;',
    '        return ans;',
    '    }',
    '}',
  ],
  cpp: [
    '#include <string>',
    '#include <vector>',
    '#include <numeric>',
    '#include <algorithm>',
    'using namespace std;',
    '',
    '// 环绕字符串中唯一的子字符串 (LeetCode 467)',
    'class Solution {',
    'public:',
    '    int findSubstringInWraproundString(string s) {',
    '        int n = s.size();',
    '        vector<int> dp(26, 0);',
    '        dp[s[0] - \'a\'] = 1;',
    '        for (int i = 1, cur = 1; i < n; i++) {',
    '            char pre = s[i - 1], c = s[i];',
    '            if ((pre == \'z\' && c == \'a\') || pre + 1 == c) cur++;',
    '            else cur = 1;',
    '            dp[c - \'a\'] = max(dp[c - \'a\'], cur);',
    '        }',
    '        return accumulate(dp.begin(), dp.end(), 0);',
    '    }',
    '};',
  ],
  python: [
    'class Solution:',
    '    def findSubstringInWraproundString(self, s: str) -> int:',
    '        n = len(s)',
    '        dp = [0] * 26',
    '        dp[ord(s[0]) - ord("a")] = 1',
    '        cur = 1',
    '        for i in range(1, n):',
    '            pre, c = s[i - 1], s[i]',
    '            if (pre == "z" and c == "a") or (ord(pre) + 1 == ord(c)):',
    '                cur += 1',
    '            else:',
    '                cur = 1',
    '            idx = ord(c) - ord("a")',
    '            dp[idx] = max(dp[idx], cur)',
    '        return sum(dp)',
  ],
  javascript: [
    '// 环绕字符串中唯一的子字符串 (LeetCode 467)',
    'function findSubstringInWraproundString(s) {',
    '    const n = s.length;',
    '    const dp = new Array(26).fill(0);',
    '    dp[s.charCodeAt(0) - 97] = 1;',
    '    let cur = 1;',
    '    for (let i = 1; i < n; i++) {',
    '        const preCode = s.charCodeAt(i - 1);',
    '        const curCode = s.charCodeAt(i);',
    '        if ((preCode === 122 && curCode === 97) || preCode + 1 === curCode) {',
    '            cur++;',
    '        } else {',
    '            cur = 1;',
    '        }',
    '        const idx = curCode - 97;',
    '        dp[idx] = Math.max(dp[idx], cur);',
    '    }',
    '    return dp.reduce((a, b) => a + b, 0);',
    '}',
  ],
};

export const UNIQUE_SUBSTRINGS_WRAPAROUND_066_LINES = {
  entry: { java: 5, cpp: 9, python: 2, javascript: 2 },
  initDp: { java: 8, cpp: 12, python: 4, javascript: 4 },
  scanString: { java: 10, cpp: 14, python: 6, javascript: 6 },
  checkConsecutive: { java: 13, cpp: 16, python: 8, javascript: 9 },
  updateMaxLen: { java: 18, cpp: 18, python: 13, javascript: 15 },
  sumAns: { java: 21, cpp: 20, python: 14, javascript: 17 },
};
