/**
 * 左神算法通关课 第 097 课 - 质数、筛法与质因数分解代码与相对行号映射
 */

// 1. 试除法判素数
export const SMALL_PRIME_CODES: Record<string, string[]> = {
  java: [
    'public class SmallPrime {',
    '    public static boolean isPrime(long n) {',
    '        if (n <= 1) return false;',
    '        if (n == 2 || n == 3) return true;',
    '        if (n % 2 == 0 || n % 3 == 0) return false;',
    '        for (long i = 5; i * i <= n; i += 6) {',
    '            if (n % i == 0 || n % (i + 2) == 0) return false;',
    '        }',
    '        return true;',
    '    }',
    '}',
  ],
  cpp: [
    'bool isPrime(long long n) {',
    '    if (n <= 1) return false;',
    '    if (n == 2 || n == 3) return true;',
    '    if (n % 2 == 0 || n % 3 == 0) return false;',
    '    for (long long i = 5; i * i <= n; i += 6) {',
    '        if (n % i == 0 || n % (i + 2) == 0) return false;',
    '    }',
    '    return true;',
    '}',
  ],
  python: [
    'def is_prime(n: int) -> bool:',
    '    if n <= 1:',
    '        return False',
    '    if n <= 3:',
    '        return True',
    '    if n % 2 == 0 or n % 3 == 0:',
    '        return False',
    '    i = 5',
    '    while i * i <= n:',
    '        if n % i == 0 or n % (i + 2) == 0:',
    '            return False',
    '        i += 6',
    '    return True',
  ],
  javascript: [
    'function isPrime(n) {',
    '    if (n <= 1) return false;',
    '    if (n === 2 || n === 3) return true;',
    '    if (n % 2 === 0 || n % 3 === 0) return false;',
    '    for (let i = 5; i * i <= n; i += 6) {',
    '        if (n % i === 0 || n % (i + 2) === 0) return false;',
    '    }',
    '    return true;',
    '}',
  ],
};

export const SMALL_PRIME_LINES = {
  entry: { java: 2, cpp: 1, python: 1, javascript: 1 },
  guardSmall: { java: 3, cpp: 2, python: 2, javascript: 2 },
  guardTwoThree: { java: 4, cpp: 3, python: 4, javascript: 3 },
  guardMod23: { java: 5, cpp: 4, python: 6, javascript: 4 },
  loopStep: { java: 6, cpp: 5, python: 9, javascript: 5 },
  foundFactor: { java: 7, cpp: 6, python: 10, javascript: 6 },
  returnPrime: { java: 9, cpp: 8, python: 13, javascript: 8 },
};

// 2. Miller-Rabin 大素数测试
export const LARGE_PRIME_CODES: Record<string, string[]> = {
  java: [
    'public class MillerRabin {',
    '    public static boolean isPrime(long n) {',
    '        if (n <= 1) return false;',
    '        if (n <= 3) return true;',
    '        if ((n & 1) == 0) return false;',
    '        long d = n - 1;',
    '        int s = 0;',
    '        while ((d & 1) == 0) { d >>= 1; s++; }',
    '        long[] bases = {2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37};',
    '        for (long a : bases) {',
    '            if (n <= a) break;',
    '            if (!checkComposite(n, a, d, s)) return false;',
    '        }',
    '        return true;',
    '    }',
    '}',
  ],
  cpp: [
    'bool millerRabin(long long n) {',
    '    if (n <= 1) return false;',
    '    if (n <= 3) return true;',
    '    if ((n & 1) == 0) return false;',
    '    long long d = n - 1;',
    '    int s = 0;',
    '    while ((d & 1) == 0) { d >>= 1; s++; }',
    '    long long bases[] = {2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37};',
    '    for (long long a : bases) {',
    '        if (n <= a) break;',
    '        if (!checkComposite(n, a, d, s)) return false;',
    '    }',
    '    return true;',
    '}',
  ],
  python: [
    'def miller_rabin(n: int) -> bool:',
    '    if n <= 1:',
    '        return False',
    '    if n <= 3:',
    '        return True',
    '    if n % 2 == 0:',
    '        return False',
    '    d, s = n - 1, 0',
    '    while d % 2 == 0:',
    '        d //= 2',
    '        s += 1',
    '    bases = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37]',
    '    for a in bases:',
    '        if n <= a:',
    '            break',
    '        if not check_composite(n, a, d, s):',
    '            return False',
    '    return True',
  ],
  javascript: [
    'function millerRabin(n) {',
    '    if (n <= 1) return false;',
    '    if (n <= 3) return true;',
    '    if ((n & 1) === 0) return false;',
    '    let d = n - 1;',
    '    let s = 0;',
    '    while ((d & 1) === 0) { d >>= 1; s++; }',
    '    const bases = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37];',
    '    for (const a of bases) {',
    '        if (n <= a) break;',
    '        if (!checkComposite(n, a, d, s)) return false;',
    '    }',
    '    return true;',
    '}',
  ],
};

export const LARGE_PRIME_LINES = {
  entry: { java: 2, cpp: 1, python: 1, javascript: 1 },
  guard: { java: 5, cpp: 4, python: 6, javascript: 4 },
  decompose: { java: 8, cpp: 7, python: 10, javascript: 7 },
  testBase: { java: 10, cpp: 9, python: 13, javascript: 9 },
  checkFails: { java: 12, cpp: 11, python: 17, javascript: 11 },
  returnTrue: { java: 14, cpp: 13, python: 18, javascript: 13 },
};

// 3. 质因数分解
export const PRIME_FACTORS_CODES: Record<string, string[]> = {
  java: [
    'public class PrimeFactors {',
    '    public static Map<Long, Integer> getFactors(long n) {',
    '        Map<Long, Integer> factors = new LinkedHashMap<>();',
    '        for (long i = 2; i * i <= n; i++) {',
    '            if (n % i == 0) {',
    '                int count = 0;',
    '                while (n % i == 0) { count++; n /= i; }',
    '                factors.put(i, count);',
    '            }',
    '        }',
    '        if (n > 1) factors.put(n, 1);',
    '        return factors;',
    '    }',
    '}',
  ],
  cpp: [
    'map<long long, int> getFactors(long long n) {',
    '    map<long long, int> factors;',
    '    for (long long i = 2; i * i <= n; i++) {',
    '        if (n % i == 0) {',
    '            int count = 0;',
    '            while (n % i == 0) { count++; n /= i; }',
    '            factors[i] = count;',
    '        }',
    '    }',
    '    if (n > 1) factors[n] = 1;',
    '    return factors;',
    '}',
  ],
  python: [
    'def get_factors(n: int) -> dict[int, int]:',
    '    factors = {}',
    '    i = 2',
    '    while i * i <= n:',
    '        if n % i == 0:',
    '            count = 0',
    '            while n % i == 0:',
    '                count += 1',
    '                n //= i',
    '            factors[i] = count',
    '        i += 1',
    '    if n > 1:',
    '        factors[n] = 1',
    '    return factors',
  ],
  javascript: [
    'function getFactors(n) {',
    '    const factors = new Map();',
    '    for (let i = 2; i * i <= n; i++) {',
    '        if (n % i === 0) {',
    '            let count = 0;',
    '            while (n % i === 0) { count++; n /= i; }',
    '            factors.set(i, count);',
    '        }',
    '    }',
    '    if (n > 1) factors.set(n, 1);',
    '    return factors;',
    '}',
  ],
};

export const PRIME_FACTORS_LINES = {
  entry: { java: 2, cpp: 1, python: 1, javascript: 1 },
  init: { java: 3, cpp: 2, python: 2, javascript: 2 },
  loopHeader: { java: 4, cpp: 3, python: 4, javascript: 3 },
  extractFactor: { java: 7, cpp: 6, python: 8, javascript: 6 },
  saveFactor: { java: 8, cpp: 7, python: 10, javascript: 7 },
  remainderPrime: { java: 11, cpp: 10, python: 13, javascript: 10 },
  returnAns: { java: 12, cpp: 11, python: 14, javascript: 11 },
};

// 4. 埃氏筛与欧拉线性筛
export const EHRLICH_EULER_CODES: Record<string, string[]> = {
  java: [
    'public class EulerSieve {',
    '    public static List<Integer> eulerSieve(int n) {',
    '        boolean[] isPrime = new boolean[n + 1];',
    '        Arrays.fill(isPrime, true);',
    '        List<Integer> primes = new ArrayList<>();',
    '        for (int i = 2; i <= n; i++) {',
    '            if (isPrime[i]) primes.add(i);',
    '            for (int p : primes) {',
    '                if (i * p > n) break;',
    '                isPrime[i * p] = false;',
    '                if (i % p == 0) break;',
    '            }',
    '        }',
    '        return primes;',
    '    }',
    '}',
  ],
  cpp: [
    'vector<int> eulerSieve(int n) {',
    '    vector<bool> isPrime(n + 1, true);',
    '    vector<int> primes;',
    '    for (int i = 2; i <= n; i++) {',
    '        if (isPrime[i]) primes.push_back(i);',
    '        for (int p : primes) {',
    '            if (i * p > n) break;',
    '            isPrime[i * p] = false;',
    '            if (i % p == 0) break;',
    '        }',
    '    }',
    '    return primes;',
    '}',
  ],
  python: [
    'def euler_sieve(n: int) -> list[int]:',
    '    is_prime = [True] * (n + 1)',
    '    primes = []',
    '    for i in range(2, n + 1):',
    '        if is_prime[i]:',
    '            primes.append(i)',
    '        for p in primes:',
    '            if i * p > n:',
    '                break',
    '            is_prime[i * p] = False',
    '            if i % p == 0:',
    '                break',
    '    return primes',
  ],
  javascript: [
    'function eulerSieve(n) {',
    '    const isPrime = new Array(n + 1).fill(true);',
    '    const primes = [];',
    '    for (let i = 2; i <= n; i++) {',
    '        if (isPrime[i]) primes.push(i);',
    '        for (const p of primes) {',
    '            if (i * p > n) break;',
    '            isPrime[i * p] = false;',
    '            if (i % p === 0) break;',
    '        }',
    '    }',
    '    return primes;',
    '}',
  ],
};

export const EHRLICH_EULER_LINES = {
  entry: { java: 2, cpp: 1, python: 1, javascript: 1 },
  initArray: { java: 4, cpp: 2, python: 2, javascript: 2 },
  outerLoop: { java: 6, cpp: 4, python: 4, javascript: 4 },
  foundPrime: { java: 7, cpp: 5, python: 6, javascript: 5 },
  markComposite: { java: 10, cpp: 8, python: 10, javascript: 8 },
  eulerBreak: { java: 11, cpp: 9, python: 12, javascript: 9 },
  returnPrimes: { java: 14, cpp: 13, python: 13, javascript: 13 },
};
