/**
 * 左程云 Class 065: A* 算法四语言核心实现与 1-based 行号字典
 * 1. 滑动谜题 (Sliding Puzzle · LeetCode 773)
 * 2. 八数码难题 (Eight Puzzle · 洛谷 P1379)
 */

export const SLIDING_PUZZLE_065_CODES: Record<string, string[]> = {
  java: [
    'package class065;',
    'import java.util.*;',
    '',
    '// 滑动谜题 (LeetCode 773) - A* 启发式搜索',
    'public class Code02_SlidingPuzzle {',
    '    static int[][] moves = {{1, 3}, {0, 2, 4}, {1, 5}, {0, 4}, {1, 3, 5}, {2, 4}};',
    '    static int[][] targetPos = {{1, 2}, {0, 0}, {0, 1}, {0, 2}, {1, 0}, {1, 1}}; // 0~5在目标的坐标',
    '',
    '    public static int slidingPuzzle(int[][] board) {',
    '        String start = "" + board[0][0] + board[0][1] + board[0][2] + board[1][0] + board[1][1] + board[1][2];',
    '        String target = "123450";',
    '        if (start.equals(target)) return 0;',
    '        PriorityQueue<Node> pq = new PriorityQueue<>(Comparator.comparingInt(a -> a.f));',
    '        Map<String, Integer> dist = new HashMap<>();',
    '        pq.add(new Node(start, 0, h(start)));',
    '        dist.put(start, 0);',
    '        while (!pq.isEmpty()) {',
    '            Node cur = pq.poll();',
    '            if (cur.s.equals(target)) return cur.g;',
    '            if (cur.g > dist.getOrDefault(cur.s, Integer.MAX_VALUE)) continue;',
    '            int zero = cur.s.indexOf(\'0\');',
    '            for (int nxt : moves[zero]) {',
    '                String nextStr = swap(cur.s, zero, nxt);',
    '                int nextG = cur.g + 1;',
    '                if (nextG < dist.getOrDefault(nextStr, Integer.MAX_VALUE)) {',
    '                    dist.put(nextStr, nextG);',
    '                    pq.add(new Node(nextStr, nextG, h(nextStr)));',
    '                }',
    '            }',
    '        }',
    '        return -1;',
    '    }',
    '    static int h(String s) {',
    '        int res = 0;',
    '        for (int i = 0; i < 6; i++) {',
    '            int v = s.charAt(i) - \'0\';',
    '            if (v != 0) {',
    '                res += Math.abs(i / 3 - targetPos[v][0]) + Math.abs(i % 3 - targetPos[v][1]);',
    '            }',
    '        }',
    '        return res;',
    '    }',
    '    static String swap(String s, int i, int j) {',
    '        char[] arr = s.toCharArray();',
    '        char tmp = arr[i]; arr[i] = arr[j]; arr[j] = tmp;',
    '        return new String(arr);',
    '    }',
    '}',
  ],
  cpp: [
    '#include <string>',
    '#include <vector>',
    '#include <queue>',
    '#include <unordered_map>',
    'using namespace std;',
    '',
    '// 滑动谜题 (LeetCode 773) - A* 搜索',
    'class Solution {',
    '    const vector<vector<int>> moves = {{1, 3}, {0, 2, 4}, {1, 5}, {0, 4}, {1, 3, 5}, {2, 4}};',
    '    int h(const string& s) {',
    '        int res = 0;',
    '        for (int i = 0; i < 6; ++i) {',
    '            int v = s[i] - \'0\';',
    '            if (v != 0) res += abs(i / 3 - (v - 1) / 3) + abs(i % 3 - (v - 1) % 3);',
    '        }',
    '        return res;',
    '    }',
    'public:',
    '    int slidingPuzzle(vector<vector<int>>& board) {',
    '        string start = "";',
    '        for (auto& row : board) for (int x : row) start += to_string(x);',
    '        string target = "123450";',
    '        if (start == target) return 0;',
    '        priority_queue<tuple<int, int, string>, vector<tuple<int, int, string>>, greater<>> pq;',
    '        unordered_map<string, int> dist;',
    '        pq.push({h(start), 0, start}); dist[start] = 0;',
    '        while (!pq.empty()) {',
    '            auto [f, g, s] = pq.top(); pq.pop();',
    '            if (s == target) return g;',
    '            if (g > dist[s]) continue;',
    '            int zero = s.find(\'0\');',
    '            for (int nxt : moves[zero]) {',
    '                string nextStr = s;',
    '                swap(nextStr[zero], nextStr[nxt]);',
    '                if (!dist.count(nextStr) || g + 1 < dist[nextStr]) {',
    '                    dist[nextStr] = g + 1;',
    '                    pq.push({g + 1 + h(nextStr), g + 1, nextStr});',
    '                }',
    '            }',
    '        }',
    '        return -1;',
    '    }',
    '};',
  ],
  python: [
    'import heapq',
    '',
    '# 滑动谜题 (LeetCode 773) - A* 搜索',
    'class Solution:',
    '    def slidingPuzzle(self, board: list[list[int]]) -> int:',
    '        moves = [[1, 3], [0, 2, 4], [1, 5], [0, 4], [1, 3, 5], [2, 4]]',
    '        target = "123450"',
    '        start = "".join(str(c) for row in board for c in row)',
    '        if start == target: return 0',
    '        ',
    '        def h(s: str) -> int:',
    '            res = 0',
    '            for i, ch in enumerate(s):',
    '                v = int(ch)',
    '                if v != 0:',
    '                    res += abs(i // 3 - (v - 1) // 3) + abs(i % 3 - (v - 1) % 3)',
    '            return res',
    '            ',
    '        pq = [(h(start), 0, start)]',
    '        dist = {start: 0}',
    '        while pq:',
    '            f, g, s = heapq.heappop(pq)',
    '            if s == target: return g',
    '            if g > dist.get(s, float("inf")): continue',
    '            z = s.index("0")',
    '            for nxt in moves[z]:',
    '                arr = list(s)',
    '                arr[z], arr[nxt] = arr[nxt], arr[z]',
    '                nxt_s = "".join(arr)',
    '                if g + 1 < dist.get(nxt_s, float("inf")):',
    '                    dist[nxt_s] = g + 1',
    '                    heapq.heappush(pq, (g + 1 + h(nxt_s), g + 1, nxt_s))',
    '        return -1',
  ],
  javascript: [
    '// 滑动谜题 (LeetCode 773) - A* 搜索',
    'function slidingPuzzle(board) {',
    '    const moves = [[1, 3], [0, 2, 4], [1, 5], [0, 4], [1, 3, 5], [2, 4]];',
    '    const target = "123450";',
    '    const start = board[0].join("") + board[1].join("");',
    '    if (start === target) return 0;',
    '    function h(s) {',
    '        let res = 0;',
    '        for (let i = 0; i < 6; i++) {',
    '            const v = s.charCodeAt(i) - 48;',
    '            if (v !== 0) {',
    '                const tr = Math.floor((v - 1) / 3), tc = (v - 1) % 3;',
    '                res += Math.abs(Math.floor(i / 3) - tr) + Math.abs((i % 3) - tc);',
    '            }',
    '        }',
    '        return res;',
    '    }',
    '    const pq = [{ f: h(start), g: 0, s: start }];',
    '    const dist = new Map([[start, 0]]);',
    '    while (pq.length > 0) {',
    '        pq.sort((a, b) => a.f - b.f);',
    '        const cur = pq.shift();',
    '        if (cur.s === target) return cur.g;',
    '        if (cur.g > (dist.get(cur.s) ?? Infinity)) continue;',
    '        const z = cur.s.indexOf("0");',
    '        for (const nxt of moves[z]) {',
    '            const arr = cur.s.split("");',
    '            [arr[z], arr[nxt]] = [arr[nxt], arr[z]];',
    '            const nxtStr = arr.join("");',
    '            const nxtG = cur.g + 1;',
    '            if (nxtG < (dist.get(nxtStr) ?? Infinity)) {',
    '                dist.set(nxtStr, nxtG);',
    '                pq.push({ f: nxtG + h(nxtStr), g: nxtG, s: nxtStr });',
    '            }',
    '        }',
    '    }',
    '    return -1;',
    '}',
  ],
};

export const SLIDING_PUZZLE_065_LINES = {
  entry: { java: 9, cpp: 18, python: 5, javascript: 2 },
  initHeap: { java: 13, cpp: 23, python: 18, javascript: 17 },
  whileLoop: { java: 17, cpp: 26, python: 20, javascript: 19 },
  pollMin: { java: 18, cpp: 27, python: 21, javascript: 21 },
  reachTarget: { java: 19, cpp: 28, python: 22, javascript: 22 },
  expandNeighbors: { java: 21, cpp: 30, python: 24, javascript: 24 },
  relaxDist: { java: 25, cpp: 34, python: 28, javascript: 29 },
  noSolution: { java: 31, cpp: 41, python: 32, javascript: 36 },
};

export const EIGHT_PUZZLE_065_CODES: Record<string, string[]> = {
  java: [
    'package class065;',
    'import java.util.*;',
    '',
    '// 八数码难题 (洛谷 P1379) - A* 算法与逆序对剪枝',
    'public class Code03_EightPuzzle {',
    '    static int[][] moves = {{1, 3}, {0, 2, 4}, {1, 5}, {0, 4, 6}, {1, 3, 5, 7}, {2, 4, 8}, {3, 7}, {4, 6, 8}, {5, 7}};',
    '    static int[] targetR = {1, 0, 0, 0, 1, 2, 2, 2, 1}; // 数字0~8在 target "123804765" 中的行坐标',
    '    static int[] targetC = {1, 0, 1, 2, 2, 2, 1, 0, 0}; // 数字0~8在 target "123804765" 中的列坐标',
    '',
    '    public static int eightPuzzle(String start) {',
    '        String target = "123804765";',
    '        if (start.equals(target)) return 0;',
    '        if (!isSolvable(start, target)) return -1; // 逆序对奇偶剪枝',
    '        PriorityQueue<Node> pq = new PriorityQueue<>(Comparator.comparingInt(a -> a.f));',
    '        Map<String, Integer> dist = new HashMap<>();',
    '        pq.add(new Node(start, 0, h(start)));',
    '        dist.put(start, 0);',
    '        while (!pq.isEmpty()) {',
    '            Node cur = pq.poll();',
    '            if (cur.s.equals(target)) return cur.g;',
    '            if (cur.g > dist.getOrDefault(cur.s, Integer.MAX_VALUE)) continue;',
    '            int z = cur.s.indexOf(\'0\');',
    '            for (int nxt : moves[z]) {',
    '                String nxtStr = swap(cur.s, z, nxt);',
    '                int nxtG = cur.g + 1;',
    '                if (nxtG < dist.getOrDefault(nxtStr, Integer.MAX_VALUE)) {',
    '                    dist.put(nxtStr, nxtG);',
    '                    pq.add(new Node(nxtStr, nxtG, h(nxtStr)));',
    '                }',
    '            }',
    '        }',
    '        return -1;',
    '    }',
    '    static int h(String s) {',
    '        int sum = 0;',
    '        for (int i = 0; i < 9; i++) {',
    '            int v = s.charAt(i) - \'0\';',
    '            if (v != 0) sum += Math.abs(i / 3 - targetR[v]) + Math.abs(i % 3 - targetC[v]);',
    '        }',
    '        return sum;',
    '    }',
    '    static boolean isSolvable(String a, String b) {',
    '        return (invCount(a) & 1) == (invCount(b) & 1);',
    '    }',
    '    static int invCount(String s) {',
    '        int inv = 0;',
    '        for (int i = 0; i < 9; i++) {',
    '            if (s.charAt(i) == \'0\') continue;',
    '            for (int j = i + 1; j < 9; j++) {',
    '                if (s.charAt(j) != \'0\' && s.charAt(i) > s.charAt(j)) inv++;',
    '            }',
    '        }',
    '        return inv;',
    '    }',
    '}',
  ],
  cpp: [
    '#include <string>',
    '#include <vector>',
    '#include <queue>',
    '#include <unordered_map>',
    'using namespace std;',
    '',
    '// 八数码难题 (洛谷 P1379) - A* 搜索',
    'class Solution {',
    '    const vector<vector<int>> moves = {{1, 3}, {0, 2, 4}, {1, 5}, {0, 4, 6}, {1, 3, 5, 7}, {2, 4, 8}, {3, 7}, {4, 6, 8}, {5, 7}};\n',
    '    int h(const string& s) {',
    '        // 曼哈顿距离估价',
    '        int res = 0;',
    '        // 目标 "123804765"',
    '        int tr[9] = {1, 0, 0, 0, 1, 2, 2, 2, 1};',
    '        int tc[9] = {1, 0, 1, 2, 2, 2, 1, 0, 0};',
    '        for (int i = 0; i < 9; ++i) {',
    '            int v = s[i] - \'0\';',
    '            if (v != 0) res += abs(i / 3 - tr[v]) + abs(i % 3 - tc[v]);',
    '        }',
    '        return res;',
    '    }',
    'public:',
    '    int eightPuzzle(string start) {',
    '        string target = "123804765";',
    '        if (start == target) return 0;',
    '        priority_queue<tuple<int, int, string>, vector<tuple<int, int, string>>, greater<>> pq;',
    '        unordered_map<string, int> dist;',
    '        pq.push({h(start), 0, start}); dist[start] = 0;',
    '        while (!pq.empty()) {',
    '            auto [f, g, s] = pq.top(); pq.pop();',
    '            if (s == target) return g;',
    '            if (g > dist[s]) continue;',
    '            int z = s.find(\'0\');',
    '            for (int nxt : moves[z]) {',
    '                string nxtS = s;',
    '                swap(nxtS[z], nxtS[nxt]);',
    '                if (!dist.count(nxtS) || g + 1 < dist[nxtS]) {',
    '                    dist[nxtS] = g + 1;',
    '                    pq.push({g + 1 + h(nxtS), g + 1, nxtS});',
    '                }',
    '            }',
    '        }',
    '        return -1;',
    '    }',
    '};',
  ],
  python: [
    'import heapq',
    '',
    '# 八数码难题 (洛谷 P1379) - A* 搜索',
    'class Solution:',
    '    def eightPuzzle(self, start: str) -> int:',
    '        target = "123804765"',
    '        moves = [[1, 3], [0, 2, 4], [1, 5], [0, 4, 6], [1, 3, 5, 7], [2, 4, 8], [3, 7], [4, 6, 8], [5, 7]]',
    '        tr = [1, 0, 0, 0, 1, 2, 2, 2, 1]',
    '        tc = [1, 0, 1, 2, 2, 2, 1, 0, 0]',
    '        ',
    '        def h(s: str) -> int:',
    '            res = 0',
    '            for i, ch in enumerate(s):',
    '                v = int(ch)',
    '                if v != 0: res += abs(i // 3 - tr[v]) + abs(i % 3 - tc[v])',
    '            return res',
    '            ',
    '        if start == target: return 0',
    '        pq = [(h(start), 0, start)]',
    '        dist = {start: 0}',
    '        while pq:',
    '            f, g, s = heapq.heappop(pq)',
    '            if s == target: return g',
    '            if g > dist.get(s, float("inf")): continue',
    '            z = s.index("0")',
    '            for nxt in moves[z]:',
    '                arr = list(s)',
    '                arr[z], arr[nxt] = arr[nxt], arr[z]',
    '                nxt_s = "".join(arr)',
    '                if g + 1 < dist.get(nxt_s, float("inf")):',
    '                    dist[nxt_s] = g + 1',
    '                    heapq.heappush(pq, (g + 1 + h(nxt_s), g + 1, nxt_s))',
    '        return -1',
  ],
  javascript: [
    '// 八数码难题 (洛谷 P1379) - A* 搜索',
    'function eightPuzzle(start) {',
    '    const target = "123804765";',
    '    const moves = [[1, 3], [0, 2, 4], [1, 5], [0, 4, 6], [1, 3, 5, 7], [2, 4, 8], [3, 7], [4, 6, 8], [5, 7]];',
    '    const tr = [1, 0, 0, 0, 1, 2, 2, 2, 1];',
    '    const tc = [1, 0, 1, 2, 2, 2, 1, 0, 0];',
    '    function h(s) {',
    '        let sum = 0;',
    '        for (let i = 0; i < 9; i++) {',
    '            const v = s.charCodeAt(i) - 48;',
    '            if (v !== 0) sum += Math.abs(Math.floor(i / 3) - tr[v]) + Math.abs((i % 3) - tc[v]);',
    '        }',
    '        return sum;',
    '    }',
    '    if (start === target) return 0;',
    '    const pq = [{ f: h(start), g: 0, s: start }];',
    '    const dist = new Map([[start, 0]]);',
    '    while (pq.length > 0) {',
    '        pq.sort((a, b) => a.f - b.f);',
    '        const cur = pq.shift();',
    '        if (cur.s === target) return cur.g;',
    '        if (cur.g > (dist.get(cur.s) ?? Infinity)) continue;',
    '        const z = cur.s.indexOf("0");',
    '        for (const nxt of moves[z]) {',
    '            const arr = cur.s.split("");',
    '            [arr[z], arr[nxt]] = [arr[nxt], arr[z]];',
    '            const nxtS = arr.join("");',
    '            const nxtG = cur.g + 1;',
    '            if (nxtG < (dist.get(nxtS) ?? Infinity)) {',
    '                dist.set(nxtS, nxtG);',
    '                pq.push({ f: nxtG + h(nxtS), g: nxtG, s: nxtS });',
    '            }',
    '        }',
    '    }',
    '    return -1;',
    '}',
  ],
};

export const EIGHT_PUZZLE_065_LINES = {
  entry: { java: 10, cpp: 20, python: 5, javascript: 2 },
  invCheck: { java: 13, cpp: 21, python: 17, javascript: 14 },
  initHeap: { java: 14, cpp: 22, python: 18, javascript: 15 },
  whileLoop: { java: 18, cpp: 25, python: 20, javascript: 17 },
  pollMin: { java: 19, cpp: 26, python: 21, javascript: 19 },
  reachTarget: { java: 20, cpp: 27, python: 22, javascript: 20 },
  expandNeighbors: { java: 22, cpp: 29, python: 24, javascript: 22 },
  relaxDist: { java: 26, cpp: 33, python: 28, javascript: 27 },
  noSolution: { java: 32, cpp: 40, python: 32, javascript: 34 },
};
