/**
 * 左程云算法通关课 Class 064: Dijkstra 算法及其扩展
 * Java / C++ / Python / JavaScript 四语言代码与 1-based 精准行号映射
 */

// ==========================================
// 1. Code01: 网络延迟时间 (LeetCode 743)
// ==========================================
export const NETWORK_DELAY_064_CODES = {
  cpp: [
    '#include <vector>',
    '#include <queue>',
    '#include <algorithm>',
    'using namespace std;',
    '',
    'class Solution {',
    'public:',
    '    int networkDelayTime(vector<vector<int>>& times, int n, int k) {',
    '        vector<vector<pair<int, int>>> adj(n + 1);',
    '        for (const auto& t : times) {',
    '            adj[t[0]].push_back({t[1], t[2]});',
    '        }',
    '        vector<int> dist(n + 1, 1e9);',
    '        vector<bool> visited(n + 1, false);',
    '        priority_queue<pair<int, int>, vector<pair<int, int>>, greater<>> pq;',
    '        dist[k] = 0;',
    '        pq.push({0, k});',
    '        while (!pq.empty()) {',
    '            auto [d, u] = pq.top(); pq.pop();',
    '            if (visited[u]) continue;',
    '            visited[u] = true;',
    '            for (const auto& [v, w] : adj[u]) {',
    '                if (dist[u] + w < dist[v]) {',
    '                    dist[v] = dist[u] + w;',
    '                    pq.push({dist[v], v});',
    '                }',
    '            }',
    '        }',
    '        int ans = 0;',
    '        for (int i = 1; i <= n; ++i) {',
    '            if (dist[i] == 1e9) return -1;',
    '            ans = max(ans, dist[i]);',
    '        }',
    '        return ans;',
    '    }',
    '};',
  ],
  java: [
    'package class064;',
    'import java.util.*;',
    '',
    'public class Code01_NetworkDelayTime {',
    '    public static int networkDelayTime(int[][] times, int n, int k) {',
    '        List<List<int[]>> adj = new ArrayList<>();',
    '        for (int i = 0; i <= n; i++) adj.add(new ArrayList<>());',
    '        for (int[] t : times) adj.get(t[0]).add(new int[]{t[1], t[2]});',
    '        int[] dist = new int[n + 1];',
    '        Arrays.fill(dist, Integer.MAX_VALUE);',
    '        boolean[] visited = new boolean[n + 1];',
    '        PriorityQueue<int[]> pq = new PriorityQueue<>((a, b) -> a[1] - b[1]);',
    '        dist[k] = 0;',
    '        pq.offer(new int[]{k, 0});',
    '        while (!pq.isEmpty()) {',
    '            int[] cur = pq.poll();',
    '            int u = cur[0];',
    '            if (visited[u]) continue;',
    '            visited[u] = true;',
    '            for (int[] edge : adj.get(u)) {',
    '                int v = edge[0], w = edge[1];',
    '                if (dist[u] + w < dist[v]) {',
    '                    dist[v] = dist[u] + w;',
    '                    pq.offer(new int[]{v, dist[v]});',
    '                }',
    '            }',
    '        }',
    '        int ans = 0;',
    '        for (int i = 1; i <= n; i++) {',
    '            if (dist[i] == Integer.MAX_VALUE) return -1;',
    '            ans = Math.max(ans, dist[i]);',
    '        }',
    '        return ans;',
    '    }',
    '}',
  ],
  python: [
    'import heapq',
    '',
    'class Solution:',
    '    def networkDelayTime(self, times: list[list[int]], n: int, k: int) -> int:',
    '        adj = {i: [] for i in range(1, n + 1)}',
    '        for u, v, w in times:',
    '            adj[u].append((v, w))',
    '        dist = {i: float("inf") for i in range(1, n + 1)}',
    '        visited = set()',
    '        pq = [(0, k)]',
    '        dist[k] = 0',
    '        while pq:',
    '            d, u = heapq.heappop(pq)',
    '            if u in visited:',
    '                continue',
    '            visited.add(u)',
    '            for v, w in adj[u]:',
    '                if dist[u] + w < dist[v]:',
    '                    dist[v] = dist[u] + w',
    '                    heapq.heappush(pq, (dist[v], v))',
    '        ans = max(dist.values())',
    '        return ans if ans < float("inf") else -1',
  ],
  javascript: [
    'function networkDelayTime(times, n, k) {',
    '  const adj = Array.from({ length: n + 1 }, () => []);',
    '  for (const [u, v, w] of times) adj[u].push([v, w]);',
    '  const dist = new Array(n + 1).fill(Infinity);',
    '  const visited = new Array(n + 1).fill(false);',
    '  dist[k] = 0;',
    '  const pq = [[0, k]];',
    '  while (pq.length > 0) {',
    '    pq.sort((a, b) => a[0] - b[0]);',
    '    const [d, u] = pq.shift();',
    '    if (visited[u]) continue;',
    '    visited[u] = true;',
    '    for (const [v, w] of adj[u]) {',
    '      if (dist[u] + w < dist[v]) {',
    '        dist[v] = dist[u] + w;',
    '        pq.push([dist[v], v]);',
    '      }',
    '    }',
    '  }',
    '  let ans = 0;',
    '  for (let i = 1; i <= n; i++) {',
    '    if (dist[i] === Infinity) return -1;',
    '    ans = Math.max(ans, dist[i]);',
    '  }',
    '  return ans;',
    '}',
  ],
};

export const NETWORK_DELAY_064_LINES = {
  init: { cpp: 13, java: 9, python: 8, javascript: 4 },
  pushSrc: { cpp: 17, java: 14, python: 11, javascript: 7 },
  whilePq: { cpp: 18, java: 15, python: 12, javascript: 8 },
  pollNode: { cpp: 19, java: 16, python: 13, javascript: 10 },
  skipVisited: { cpp: 20, java: 18, python: 14, javascript: 11 },
  markVisited: { cpp: 21, java: 19, python: 16, javascript: 12 },
  relaxEdge: { cpp: 23, java: 22, python: 18, javascript: 14 },
  pushPq: { cpp: 25, java: 24, python: 20, javascript: 16 },
  calcAns: { cpp: 29, java: 28, python: 21, javascript: 20 },
  returnResult: { cpp: 33, java: 33, python: 22, javascript: 24 },
};

// ==========================================
// 2. Code02: 最小体力消耗路径 (LeetCode 1631)
// ==========================================
export const PATH_MIN_EFFORT_064_CODES = {
  cpp: [
    '#include <vector>',
    '#include <queue>',
    '#include <cmath>',
    'using namespace std;',
    '',
    'class Solution {',
    'public:',
    '    int minimumEffortPath(vector<vector<int>>& heights) {',
    '        int m = heights.length(), n = heights[0].size();',
    '        vector<vector<int>> dist(m, vector<int>(n, 1e9));',
    '        priority_queue<tuple<int, int, int>, vector<tuple<int, int, int>>, greater<>> pq;',
    '        dist[0][0] = 0;',
    '        pq.push({0, 0, 0});',
    '        int dirs[4][2] = {{-1, 0}, {1, 0}, {0, -1}, {0, 1}};',
    '        while (!pq.empty()) {',
    '            auto [d, r, c] = pq.top(); pq.pop();',
    '            if (r == m - 1 && c == n - 1) return d;',
    '            if (d > dist[r][c]) continue;',
    '            for (auto& dir : dirs) {',
    '                int nr = r + dir[0], nc = c + dir[1];',
    '                if (nr >= 0 && nr < m && nc >= 0 && nc < n) {',
    '                    int effort = max(d, abs(heights[r][c] - heights[nr][nc]));',
    '                    if (effort < dist[nr][nc]) {',
    '                        dist[nr][nc] = effort;',
    '                        pq.push({effort, nr, nc});',
    '                    }',
    '                }',
    '            }',
    '        }',
    '        return 0;',
    '    }',
    '};',
  ],
  java: [
    'package class064;',
    'import java.util.*;',
    '',
    'public class Code02_PathWithMinimumEffort {',
    '    public static int minimumEffortPath(int[][] heights) {',
    '        int m = heights.length, n = heights[0].length;',
    '        int[][] dist = new int[m][n];',
    '        for (int[] row : dist) Arrays.fill(row, Integer.MAX_VALUE);',
    '        dist[0][0] = 0;',
    '        PriorityQueue<int[]> pq = new PriorityQueue<>((a, b) -> a[2] - b[2]);',
    '        pq.offer(new int[]{0, 0, 0});',
    '        int[][] dirs = {{-1, 0}, {1, 0}, {0, -1}, {0, 1}};',
    '        while (!pq.isEmpty()) {',
    '            int[] cur = pq.poll();',
    '            int r = cur[0], c = cur[1], d = cur[2];',
    '            if (r == m - 1 && c == n - 1) return d;',
    '            if (d > dist[r][c]) continue;',
    '            for (int[] dir : dirs) {',
    '                int nr = r + dir[0], nc = c + dir[1];',
    '                if (nr >= 0 && nr < m && nc >= 0 && nc < n) {',
    '                    int effort = Math.max(d, Math.abs(heights[r][c] - heights[nr][nc]));',
    '                    if (effort < dist[nr][nc]) {',
    '                        dist[nr][nc] = effort;',
    '                        pq.offer(new int[]{nr, nc, effort});',
    '                    }',
    '                }',
    '            }',
    '        }',
    '        return 0;',
    '    }',
    '}',
  ],
  python: [
    'import heapq',
    '',
    'class Solution:',
    '    def minimumEffortPath(self, heights: list[list[int]]) -> int:',
    '        m, n = len(heights), len(heights[0])',
    '        dist = [[float("inf")] * n for _ in range(m)]',
    '        dist[0][0] = 0',
    '        pq = [(0, 0, 0)]',
    '        dirs = [(-1, 0), (1, 0), (0, -1), (0, 1)]',
    '        while pq:',
    '            d, r, c = heapq.heappop(pq)',
    '            if r == m - 1 and c == n - 1:',
    '                return d',
    '            if d > dist[r][c]:',
    '                continue',
    '            for dr, dc in dirs:',
    '                nr, nc = r + dr, c + dc',
    '                if 0 <= nr < m and 0 <= nc < n:',
    '                    effort = max(d, abs(heights[r][c] - heights[nr][nc]))',
    '                    if effort < dist[nr][nc]:',
    '                        dist[nr][nc] = effort',
    '                        heapq.heappush(pq, (effort, nr, nc))',
    '        return 0',
  ],
  javascript: [
    'function minimumEffortPath(heights) {',
    '  const m = heights.length, n = heights[0].length;',
    '  const dist = Array.from({ length: m }, () => new Array(n).fill(Infinity));',
    '  dist[0][0] = 0;',
    '  const pq = [[0, 0, 0]];',
    '  const dirs = [[-1, 0], [1, 0], [0, -1], [0, 1]];',
    '  while (pq.length > 0) {',
    '    pq.sort((a, b) => a[2] - b[2]);',
    '    const [r, c, d] = pq.shift();',
    '    if (r === m - 1 && c === n - 1) return d;',
    '    if (d > dist[r][c]) continue;',
    '    for (const [dr, dc] of dirs) {',
    '      const nr = r + dr, nc = c + dc;',
    '      if (nr >= 0 && nr < m && nc >= 0 && nc < n) {',
    '        const effort = Math.max(d, Math.abs(heights[r][c] - heights[nr][nc]));',
    '        if (effort < dist[nr][nc]) {',
    '          dist[nr][nc] = effort;',
    '          pq.push([nr, nc, effort]);',
    '        }',
    '      }',
    '    }',
    '  }',
    '  return 0;',
    '}',
  ],
};

export const PATH_MIN_EFFORT_064_LINES = {
  initDist: { cpp: 10, java: 8, python: 6, javascript: 3 },
  pushStart: { cpp: 13, java: 11, python: 8, javascript: 5 },
  whilePq: { cpp: 15, java: 13, python: 10, javascript: 7 },
  pollCell: { cpp: 16, java: 14, python: 11, javascript: 9 },
  checkTarget: { cpp: 17, java: 16, python: 12, javascript: 10 },
  calcEffort: { cpp: 22, java: 21, python: 18, javascript: 15 },
  relaxGrid: { cpp: 23, java: 22, python: 19, javascript: 16 },
  pushNext: { cpp: 25, java: 24, python: 21, javascript: 18 },
};

// ==========================================
// 3. Code03: 水位上升泳池中游泳 (LeetCode 778)
// ==========================================
export const SWIM_IN_WATER_064_CODES = {
  cpp: [
    '#include <vector>',
    '#include <queue>',
    '#include <algorithm>',
    'using namespace std;',
    '',
    'class Solution {',
    'public:',
    '    int swimInWater(vector<vector<int>>& grid) {',
    '        int n = grid.size();',
    '        vector<vector<int>> dist(n, vector<int>(n, 1e9));',
    '        priority_queue<tuple<int, int, int>, vector<tuple<int, int, int>>, greater<>> pq;',
    '        dist[0][0] = grid[0][0];',
    '        pq.push({grid[0][0], 0, 0});',
    '        int dirs[4][2] = {{-1, 0}, {1, 0}, {0, -1}, {0, 1}};',
    '        while (!pq.empty()) {',
    '            auto [t, r, c] = pq.top(); pq.pop();',
    '            if (r == n - 1 && c == n - 1) return t;',
    '            if (t > dist[r][c]) continue;',
    '            for (auto& dir : dirs) {',
    '                int nr = r + dir[0], nc = c + dir[1];',
    '                if (nr >= 0 && nr < n && nc >= 0 && nc < n) {',
    '                    int nextT = max(t, grid[nr][nc]);',
    '                    if (nextT < dist[nr][nc]) {',
    '                        dist[nr][nc] = nextT;',
    '                        pq.push({nextT, nr, nc});',
    '                    }',
    '                }',
    '            }',
    '        }',
    '        return 0;',
    '    }',
    '};',
  ],
  java: [
    'package class064;',
    'import java.util.*;',
    '',
    'public class Code03_SwimInRisingWater {',
    '    public static int swimInWater(int[][] grid) {',
    '        int n = grid.length;',
    '        int[][] dist = new int[n][n];',
    '        for (int[] row : dist) Arrays.fill(row, Integer.MAX_VALUE);',
    '        dist[0][0] = grid[0][0];',
    '        PriorityQueue<int[]> pq = new PriorityQueue<>((a, b) -> a[2] - b[2]);',
    '        pq.offer(new int[]{0, 0, grid[0][0]});',
    '        int[][] dirs = {{-1, 0}, {1, 0}, {0, -1}, {0, 1}};',
    '        while (!pq.isEmpty()) {',
    '            int[] cur = pq.poll();',
    '            int r = cur[0], c = cur[1], t = cur[2];',
    '            if (r == n - 1 && c == n - 1) return t;',
    '            if (t > dist[r][c]) continue;',
    '            for (int[] dir : dirs) {',
    '                int nr = r + dir[0], nc = c + dir[1];',
    '                if (nr >= 0 && nr < n && nc >= 0 && nc < n) {',
    '                    int nextT = Math.max(t, grid[nr][nc]);',
    '                    if (nextT < dist[nr][nc]) {',
    '                        dist[nr][nc] = nextT;',
    '                        pq.offer(new int[]{nr, nc, nextT});',
    '                    }',
    '                }',
    '            }',
    '        }',
    '        return 0;',
    '    }',
    '}',
  ],
  python: [
    'import heapq',
    '',
    'class Solution:',
    '    def swimInWater(self, grid: list[list[int]]) -> int:',
    '        n = len(grid)',
    '        dist = [[float("inf")] * n for _ in range(n)]',
    '        dist[0][0] = grid[0][0]',
    '        pq = [(grid[0][0], 0, 0)]',
    '        dirs = [(-1, 0), (1, 0), (0, -1), (0, 1)]',
    '        while pq:',
    '            t, r, c = heapq.heappop(pq)',
    '            if r == n - 1 and c == n - 1:',
    '                return t',
    '            if t > dist[r][c]:',
    '                continue',
    '            for dr, dc in dirs:',
    '                nr, nc = r + dr, c + dc',
    '                if 0 <= nr < n and 0 <= nc < n:',
    '                    nextT = max(t, grid[nr][nc])',
    '                    if nextT < dist[nr][nc]:',
    '                        dist[nr][nc] = nextT',
    '                        heapq.heappush(pq, (nextT, nr, nc))',
    '        return 0',
  ],
  javascript: [
    'function swimInWater(grid) {',
    '  const n = grid.length;',
    '  const dist = Array.from({ length: n }, () => new Array(n).fill(Infinity));',
    '  dist[0][0] = grid[0][0];',
    '  const pq = [[0, 0, grid[0][0]]];',
    '  const dirs = [[-1, 0], [1, 0], [0, -1], [0, 1]];',
    '  while (pq.length > 0) {',
    '    pq.sort((a, b) => a[2] - b[2]);',
    '    const [r, c, t] = pq.shift();',
    '    if (r === n - 1 && c === n - 1) return t;',
    '    if (t > dist[r][c]) continue;',
    '    for (const [dr, dc] of dirs) {',
    '      const nr = r + dr, nc = c + dc;',
    '      if (nr >= 0 && nr < n && nc >= 0 && nc < n) {',
    '        const nextT = Math.max(t, grid[nr][nc]);',
    '        if (nextT < dist[nr][nc]) {',
    '          dist[nr][nc] = nextT;',
    '          pq.push([nr, nc, nextT]);',
    '        }',
    '      }',
    '    }',
    '  }',
    '  return 0;',
    '}',
  ],
};

export const SWIM_IN_WATER_064_LINES = {
  init: { cpp: 10, java: 8, python: 6, javascript: 3 },
  pushOrigin: { cpp: 13, java: 11, python: 8, javascript: 5 },
  whilePq: { cpp: 15, java: 13, python: 10, javascript: 7 },
  pollCell: { cpp: 16, java: 14, python: 11, javascript: 9 },
  hitTarget: { cpp: 17, java: 16, python: 12, javascript: 10 },
  calcWater: { cpp: 22, java: 21, python: 18, javascript: 15 },
  relaxCell: { cpp: 23, java: 22, python: 19, javascript: 16 },
  pushWater: { cpp: 25, java: 24, python: 21, javascript: 18 },
};

// ==========================================
// 4. Code04: 飞行路线分层图 (洛谷 P4568)
// ==========================================
export const LAYERED_DIJKSTRA_064_CODES = {
  cpp: [
    '#include <vector>',
    '#include <queue>',
    '#include <algorithm>',
    'using namespace std;',
    '',
    'int flightRoutes(int n, int k, int s, int t, vector<vector<int>>& edges) {',
    '    vector<vector<pair<int, int>>> adj(n);',
    '    for (auto& e : edges) {',
    '        adj[e[0]].push_back({e[1], e[2]});',
    '        adj[e[1]].push_back({e[0], e[2]});',
    '    }',
    '    vector<vector<int>> dist(n, vector<int>(k + 1, 1e9));',
    '    priority_queue<tuple<int, int, int>, vector<tuple<int, int, int>>, greater<>> pq;',
    '    dist[s][0] = 0;',
    '    pq.push({0, s, 0});',
    '    while (!pq.empty()) {',
    '        auto [d, u, used] = pq.top(); pq.pop();',
    '        if (d > dist[u][used]) continue;',
    '        if (u == t) return d;',
    '        for (auto& [v, w] : adj[u]) {',
    '            if (dist[u][used] + w < dist[v][used]) {',
    '                dist[v][used] = dist[u][used] + w;',
    '                pq.push({dist[v][used], v, used});',
    '            }',
    '            if (used < k && dist[u][used] < dist[v][used + 1]) {',
    '                dist[v][used + 1] = dist[u][used];',
    '                pq.push({dist[v][used + 1], v, used + 1});',
    '            }',
    '        }',
    '    }',
    '    int ans = 1e9;',
    '    for (int i = 0; i <= k; ++i) ans = min(ans, dist[t][i]);',
    '    return ans;',
    '}',
  ],
  java: [
    'package class064;',
    'import java.util.*;',
    '',
    'public class Code04_FlightRoutes {',
    '    public static int flightRoutes(int n, int k, int s, int t, int[][] edges) {',
    '        List<List<int[]>> adj = new ArrayList<>();',
    '        for (int i = 0; i < n; i++) adj.add(new ArrayList<>());',
    '        for (int[] e : edges) {',
    '            adj.get(e[0]).add(new int[]{e[1], e[2]});',
    '            adj.get(e[1]).add(new int[]{e[0], e[2]});',
    '        }',
    '        int[][] dist = new int[n][k + 1];',
    '        for (int[] row : dist) Arrays.fill(row, Integer.MAX_VALUE);',
    '        dist[s][0] = 0;',
    '        PriorityQueue<int[]> pq = new PriorityQueue<>((a, b) -> a[0] - b[0]);',
    '        pq.offer(new int[]{0, s, 0});',
    '        while (!pq.isEmpty()) {',
    '            int[] cur = pq.poll();',
    '            int d = cur[0], u = cur[1], used = cur[2];',
    '            if (d > dist[u][used]) continue;',
    '            if (u == t) return d;',
    '            for (int[] edge : adj.get(u)) {',
    '                int v = edge[0], w = edge[1];',
    '                if (dist[u][used] + w < dist[v][used]) {',
    '                    dist[v][used] = dist[u][used] + w;',
    '                    pq.offer(new int[]{dist[v][used], v, used});',
    '                }',
    '                if (used < k && dist[u][used] < dist[v][used + 1]) {',
    '                    dist[v][used + 1] = dist[u][used];',
    '                    pq.offer(new int[]{dist[v][used + 1], v, used + 1});',
    '                }',
    '            }',
    '        }',
    '        int ans = Integer.MAX_VALUE;',
    '        for (int i = 0; i <= k; i++) ans = Math.min(ans, dist[t][i]);',
    '        return ans;',
    '    }',
    '}',
  ],
  python: [
    'import heapq',
    '',
    'def flightRoutes(n: int, k: int, s: int, t: int, edges: list[list[int]]) -> int:',
    '    adj = {i: [] for i in range(n)}',
    '    for u, v, w in edges:',
    '        adj[u].append((v, w))',
    '        adj[v].append((u, w))',
    '    dist = [[float("inf")] * (k + 1) for _ in range(n)]',
    '    dist[s][0] = 0',
    '    pq = [(0, s, 0)]',
    '    while pq:',
    '        d, u, used = heapq.heappop(pq)',
    '        if d > dist[u][used]:',
    '            continue',
    '        if u == t:',
    '            return d',
    '        for v, w in adj[u]:',
    '            if dist[u][used] + w < dist[v][used]:',
    '                dist[v][used] = dist[u][used] + w',
    '                heapq.heappush(pq, (dist[v][used], v, used))',
    '            if used < k and dist[u][used] < dist[v][used + 1]:',
    '                dist[v][used + 1] = dist[u][used]',
    '                heapq.heappush(pq, (dist[v][used + 1], v, used + 1))',
    '    return min(dist[t])',
  ],
  javascript: [
    'function flightRoutes(n, k, s, t, edges) {',
    '  const adj = Array.from({ length: n }, () => []);',
    '  for (const [u, v, w] of edges) {',
    '    adj[u].push([v, w]);',
    '    adj[v].push([u, w]);',
    '  }',
    '  const dist = Array.from({ length: n }, () => new Array(k + 1).fill(Infinity));',
    '  dist[s][0] = 0;',
    '  const pq = [[0, s, 0]];',
    '  while (pq.length > 0) {',
    '    pq.sort((a, b) => a[0] - b[0]);',
    '    const [d, u, used] = pq.shift();',
    '    if (d > dist[u][used]) continue;',
    '    if (u === t) return d;',
    '    for (const [v, w] of adj[u]) {',
    '      if (dist[u][used] + w < dist[v][used]) {',
    '        dist[v][used] = dist[u][used] + w;',
    '        pq.push([dist[v][used], v, used]);',
    '      }',
    '      if (used < k && dist[u][used] < dist[v][used + 1]) {',
    '        dist[v][used + 1] = dist[u][used];',
    '        pq.push([dist[v][used + 1], v, used + 1]);',
    '      }',
    '    }',
    '  }',
    '  return Math.min(...dist[t]);',
    '}',
  ],
};

export const LAYERED_DIJKSTRA_064_LINES = {
  init: { cpp: 12, java: 12, python: 8, javascript: 6 },
  pushSrc: { cpp: 15, java: 15, python: 10, javascript: 8 },
  whilePq: { cpp: 16, java: 16, python: 11, javascript: 9 },
  pollNode: { cpp: 17, java: 17, python: 12, javascript: 11 },
  hitTarget: { cpp: 19, java: 19, python: 15, javascript: 13 },
  sameLayerRelax: { cpp: 22, java: 23, python: 19, javascript: 16 },
  freeLayerRelax: { cpp: 26, java: 27, python: 22, javascript: 20 },
  returnAns: { cpp: 32, java: 34, python: 24, javascript: 26 },
};

// ==========================================
// 5. Code05: 电动车游历城市 (LeetCode LCP 35)
// ==========================================
export const EV_CHARGE_064_CODES = {
  cpp: [
    '#include <vector>',
    '#include <queue>',
    '#include <algorithm>',
    'using namespace std;',
    '',
    'int electricCarPlan(vector<vector<int>>& paths, int cnt, int start, int end, vector<int>& charge) {',
    '    int n = charge.size();',
    '    vector<vector<pair<int, int>>> adj(n);',
    '    for (auto& p : paths) {',
    '        adj[p[0]].push_back({p[1], p[2]});',
    '        adj[p[1]].push_back({p[0], p[2]});',
    '    }',
    '    vector<vector<int>> dist(n, vector<int>(cnt + 1, 1e9));',
    '    priority_queue<tuple<int, int, int>, vector<tuple<int, int, int>>, greater<>> pq;',
    '    dist[start][0] = 0;',
    '    pq.push({0, start, 0});',
    '    while (!pq.empty()) {',
    '        auto [time, u, power] = pq.top(); pq.pop();',
    '        if (time > dist[u][power]) continue;',
    '        if (u == end) return time;',
    '        if (power < cnt && time + charge[u] < dist[u][power + 1]) {',
    '            dist[u][power + 1] = time + charge[u];',
    '            pq.push({dist[u][power + 1], u, power + 1});',
    '        }',
    '        for (auto& [v, w] : adj[u]) {',
    '            if (power >= w && time + w < dist[v][power - w]) {',
    '                dist[v][power - w] = time + w;',
    '                pq.push({dist[v][power - w], v, power - w});',
    '            }',
    '        }',
    '    }',
    '    return -1;',
    '}',
  ],
  java: [
    'package class064;',
    'import java.util.*;',
    '',
    'public class Code05_ElectricCarPlan {',
    '    public static int electricCarPlan(int[][] paths, int cnt, int start, int end, int[] charge) {',
    '        int n = charge.length;',
    '        List<List<int[]>> adj = new ArrayList<>();',
    '        for (int i = 0; i < n; i++) adj.add(new ArrayList<>());',
    '        for (int[] p : paths) {',
    '            adj.get(p[0]).add(new int[]{p[1], p[2]});',
    '            adj.get(p[1]).add(new int[]{p[0], p[2]});',
    '        }',
    '        int[][] dist = new int[n][cnt + 1];',
    '        for (int[] row : dist) Arrays.fill(row, Integer.MAX_VALUE);',
    '        dist[start][0] = 0;',
    '        PriorityQueue<int[]> pq = new PriorityQueue<>((a, b) -> a[0] - b[0]);',
    '        pq.offer(new int[]{0, start, 0});',
    '        while (!pq.isEmpty()) {',
    '            int[] cur = pq.poll();',
    '            int time = cur[0], u = cur[1], power = cur[2];',
    '            if (time > dist[u][power]) continue;',
    '            if (u == end) return time;',
    '            if (power < cnt && time + charge[u] < dist[u][power + 1]) {',
    '                dist[u][power + 1] = time + charge[u];',
    '                pq.offer(new int[]{dist[u][power + 1], u, power + 1});',
    '            }',
    '            for (int[] edge : adj.get(u)) {',
    '                int v = edge[0], w = edge[1];',
    '                if (power >= w && time + w < dist[v][power - w]) {',
    '                    dist[v][power - w] = time + w;',
    '                    pq.offer(new int[]{dist[v][power - w], v, power - w});',
    '                }',
    '            }',
    '        }',
    '        return -1;',
    '    }',
    '}',
  ],
  python: [
    'import heapq',
    '',
    'def electricCarPlan(paths: list[list[int]], cnt: int, start: int, end: int, charge: list[int]) -> int:',
    '    n = len(charge)',
    '    adj = {i: [] for i in range(n)}',
    '    for u, v, w in paths:',
    '        adj[u].append((v, w))',
    '        adj[v].append((u, w))',
    '    dist = [[float("inf")] * (cnt + 1) for _ in range(n)]',
    '    dist[start][0] = 0',
    '    pq = [(0, start, 0)]',
    '    while pq:',
    '        time, u, power = heapq.heappop(pq)',
    '        if time > dist[u][power]:',
    '            continue',
    '        if u == end:',
    '            return time',
    '        if power < cnt and time + charge[u] < dist[u][power + 1]:',
    '            dist[u][power + 1] = time + charge[u]',
    '            heapq.heappush(pq, (dist[u][power + 1], u, power + 1))',
    '        for v, w in adj[u]:',
    '            if power >= w and time + w < dist[v][power - w]:',
    '                dist[v][power - w] = time + w',
    '                heapq.heappush(pq, (dist[v][power - w], v, power - w))',
    '    return -1',
  ],
  javascript: [
    'function electricCarPlan(paths, cnt, start, end, charge) {',
    '  const n = charge.length;',
    '  const adj = Array.from({ length: n }, () => []);',
    '  for (const [u, v, w] of paths) {',
    '    adj[u].push([v, w]);',
    '    adj[v].push([u, w]);',
    '  }',
    '  const dist = Array.from({ length: n }, () => new Array(cnt + 1).fill(Infinity));',
    '  dist[start][0] = 0;',
    '  const pq = [[0, start, 0]];',
    '  while (pq.length > 0) {',
    '    pq.sort((a, b) => a[0] - b[0]);',
    '    const [time, u, power] = pq.shift();',
    '    if (time > dist[u][power]) continue;',
    '    if (u === end) return time;',
    '    if (power < cnt && time + charge[u] < dist[u][power + 1]) {',
    '      dist[u][power + 1] = time + charge[u];',
    '      pq.push([dist[u][power + 1], u, power + 1]);',
    '    }',
    '    for (const [v, w] of adj[u]) {',
    '      if (power >= w && time + w < dist[v][power - w]) {',
    '        dist[v][power - w] = time + w;',
    '        pq.push([dist[v][power - w], v, power - w]);',
    '      }',
    '    }',
    '  }',
    '  return -1;',
    '}',
  ],
};

export const EV_CHARGE_064_LINES = {
  init: { cpp: 13, java: 13, python: 9, javascript: 7 },
  pushSrc: { cpp: 15, java: 15, python: 11, javascript: 9 },
  whilePq: { cpp: 16, java: 16, python: 12, javascript: 10 },
  pollState: { cpp: 17, java: 17, python: 13, javascript: 12 },
  hitEnd: { cpp: 19, java: 19, python: 16, javascript: 14 },
  chargeOption: { cpp: 20, java: 20, python: 18, javascript: 15 },
  moveOption: { cpp: 24, java: 25, python: 22, javascript: 19 },
};

// ==========================================
// 6. Code06: 状态压缩最短路 (LeetCode 847)
// ==========================================
export const STATE_COMP_064_CODES = {
  cpp: [
    '#include <vector>',
    '#include <queue>',
    'using namespace std;',
    '',
    'class Solution {',
    'public:',
    '    int shortestPathLength(vector<vector<int>>& graph) {',
    '        int n = graph.size();',
    '        int targetMask = (1 << n) - 1;',
    '        vector<vector<bool>> visited(n, vector<bool>(1 << n, false));',
    '        queue<tuple<int, int, int>> q;',
    '        for (int i = 0; i < n; ++i) {',
    '            q.push({i, 1 << i, 0});',
    '            visited[i][1 << i] = true;',
    '        }',
    '        while (!q.empty()) {',
    '            auto [u, mask, dist] = q.front(); q.pop();',
    '            if (mask == targetMask) return dist;',
    '            for (int v : graph[u]) {',
    '                int nextMask = mask | (1 << v);',
    '                if (!visited[v][nextMask]) {',
    '                    visited[v][nextMask] = true;',
    '                    q.push({v, nextMask, dist + 1});',
    '                }',
    '            }',
    '        }',
    '        return 0;',
    '    }',
    '};',
  ],
  java: [
    'package class064;',
    'import java.util.*;',
    '',
    'public class Code06_ShortestPathAllNodes {',
    '    public static int shortestPathLength(int[][] graph) {',
    '        int n = graph.length;',
    '        int targetMask = (1 << n) - 1;',
    '        boolean[][] visited = new boolean[n][1 << n];',
    '        Queue<int[]> q = new LinkedList<>();',
    '        for (int i = 0; i < n; i++) {',
    '            q.offer(new int[]{i, 1 << i, 0});',
    '            visited[i][1 << i] = true;',
    '        }',
    '        while (!q.isEmpty()) {',
    '            int[] cur = q.poll();',
    '            int u = cur[0], mask = cur[1], dist = cur[2];',
    '            if (mask == targetMask) return dist;',
    '            for (int v : graph[u]) {',
    '                int nextMask = mask | (1 << v);',
    '                if (!visited[v][nextMask]) {',
    '                    visited[v][nextMask] = true;',
    '                    q.offer(new int[]{v, nextMask, dist + 1});',
    '                }',
    '            }',
    '        }',
    '        return 0;',
    '    }',
    '}',
  ],
  python: [
    'from collections import deque',
    '',
    'class Solution:',
    '    def shortestPathLength(self, graph: list[list[int]]) -> int:',
    '        n = len(graph)',
    '        targetMask = (1 << n) - 1',
    '        visited = set()',
    '        q = deque()',
    '        for i in range(n):',
    '            q.append((i, 1 << i, 0))',
    '            visited.add((i, 1 << i))',
    '        while q:',
    '            u, mask, dist = q.popleft()',
    '            if mask == targetMask:',
    '                return dist',
    '            for v in graph[u]:',
    '                nextMask = mask | (1 << v)',
    '                if (v, nextMask) not in visited:',
    '                    visited.add((v, nextMask))',
    '                    q.append((v, nextMask, dist + 1))',
    '        return 0',
  ],
  javascript: [
    'function shortestPathLength(graph) {',
    '  const n = graph.length;',
    '  const targetMask = (1 << n) - 1;',
    '  const visited = Array.from({ length: n }, () => new Array(1 << n).fill(false));',
    '  const q = [];',
    '  for (let i = 0; i < n; i++) {',
    '    q.push([i, 1 << i, 0]);',
    '    visited[i][1 << i] = true;',
    '  }',
    '  while (q.length > 0) {',
    '    const [u, mask, dist] = q.shift();',
    '    if (mask === targetMask) return dist;',
    '    for (const v of graph[u]) {',
    '      const nextMask = mask | (1 << v);',
    '      if (!visited[v][nextMask]) {',
    '        visited[v][nextMask] = true;',
    '        q.push([v, nextMask, dist + 1]);',
    '      }',
    '    }',
    '  }',
    '  return 0;',
    '}',
  ],
};

export const STATE_COMP_064_LINES = {
  initTarget: { cpp: 9, java: 7, python: 6, javascript: 3 },
  multiSourceQueue: { cpp: 12, java: 10, python: 9, javascript: 6 },
  whileQueue: { cpp: 16, java: 14, python: 12, javascript: 10 },
  pollNode: { cpp: 17, java: 15, python: 13, javascript: 11 },
  checkComplete: { cpp: 18, java: 16, python: 14, javascript: 12 },
  maskTransition: { cpp: 20, java: 18, python: 17, javascript: 14 },
  pushNext: { cpp: 23, java: 21, python: 19, javascript: 17 },
};
