/**
 * 背包 073 四阶段演化多语言代码模板库
 * 从各 evolution 文件中提取的模板常量，供 knapsack-073-stage-codes.ts 注册使用。
 * 使用 @step:anchor 语义锚点标注，由 CodeStepIndexer 在编译期自动
 * 解析为 Java / C++ / Python / JavaScript 四语种 1-based 物理行号。
 */

export const DEPENDENT_STAGE1_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    'package class073;',
    '',
    '// 阶段 1: 暴力递归 (主附组合互斥展开为分组背包分治)',
    'public class Code05_DependentKnapsackRecursion {',
    '    public static int dfs(int[][] cost, int[][] val, int[] size, int g, int rem) { // @step:callRoot // @step:fnEnter',
    '        if (g == size.length || rem <= 0) return 0; // @step:baseCheck // @step:baseCheck',
    '        int ans = dfs(cost, val, size, g + 1, rem); // @step:branchNoPick',
    '        for (int k = 0; k < size[g]; k++) { // @step:loopCombo // @step:loopCombo',
    '            if (rem >= cost[g][k]) {',
    '                ans = Math.max(ans, dfs(cost, val, size, g + 1, rem - cost[g][k]) + val[g][k]); // @step:branchPick',
    '            }',
    '        }',
    '        return ans # @step:returnMax; // @step:returnMax // @step:returnMax',
    '    }',
    '}',
  ],
  cpp: [
    '#include <vector>',
    '#include <algorithm>',
    'using namespace std;',
    '',
    '// 阶段 1: 暴力递归',
    'int dfs(const vector<vector<int>>& cost, const vector<vector<int>>& val, int g, int rem) { // @step:callRoot // @step:fnEnter',
    '    if (g == (int)cost.size() || rem <= 0) return 0; // @step:baseCheck // @step:baseCheck',
    '    int ans = dfs(cost, val, g + 1, rem); // @step:branchNoPick',
    '    for (size_t k = 0; k < cost[g].size(); ++k) { // @step:loopCombo // @step:loopCombo',
    '        if (rem >= cost[g][k]) {',
    '            ans = max(ans, dfs(cost, val, g + 1, rem - cost[g][k]) + val[g][k]); // @step:branchPick',
    '        }',
    '    }',
    '    return ans; // @step:returnMax',
    '}',
  ],
  python: [
    '# 阶段 1: 暴力递归',
    'def dfs(cost: list[list[int]], val: list[list[int]], g: int, rem: int) -> int: # @step:callRoot // @step:fnEnter',
    '    if g == len(cost) or rem <= 0: # @step:baseCheck # @step:baseCheck',
    '        return 0',
    '    ans = dfs(cost, val, g + 1, rem) # @step:branchNoPick',
    '    for c, v in zip(cost[g], val[g]): # @step:loopCombo # @step:loopCombo',
    '        if rem >= c:',
    '            ans = max(ans, dfs(cost, val, g + 1, rem - c) + v) # @step:branchPick',
    '    return ans',
  ],
  javascript: [
    '// 阶段 1: 暴力递归',
    'export function dfs(cost, val, g, rem) { // @step:callRoot // @step:fnEnter',
    '  if (g === cost.length || rem <= 0) return 0; // @step:baseCheck // @step:baseCheck',
    '  let ans = dfs(cost, val, g + 1, rem); // @step:branchNoPick',
    '  for (let k = 0; k < cost[g].length; k++) { // @step:loopCombo // @step:loopCombo',
    '    if (rem >= cost[g][k]) {',
    '      ans = Math.max(ans, dfs(cost, val, g + 1, rem - cost[g][k]) + val[g][k]); // @step:branchPick',
    '    }',
    '  }',
    '  return ans;',
    '}',
  ],
};


export const DEPENDENT_STAGE2_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    'package class073;',
    'import java.util.Arrays;',
    '',
    '// 阶段 2: 记忆化搜索',
    'public class Code05_DependentKnapsackMemo {',
    '    public static int dfs(int[][] cost, int[][] val, int[] size, int g, int rem, int[][] memo) { // @step:callRoot // @step:fnEnter',
    '        if (g == size.length || rem <= 0) return 0;',
    '        if (memo[g][rem] != -1) return memo[g][rem]; // @step:memoCheck // @step:memoCheck',
    '        int ans = dfs(cost, val, size, g + 1, rem, memo); // @step:branchNoPick',
    '        for (int k = 0; k < size[g]; k++) {',
    '            if (rem >= cost[g][k]) {',
    '                ans = Math.max(ans, dfs(cost, val, size, g + 1, rem - cost[g][k], memo) + val[g][k]); // @step:branchPick',
    '            }',
    '        }',
    '        return memo[g][rem] = ans; // @step:memoStore // @step:memoStore',
    '    }',
    '}',
  ],
  cpp: [
    '#include <vector>',
    '#include <algorithm>',
    'using namespace std;',
    '',
    '// 阶段 2: 记忆化搜索',
    'int dfs(const vector<vector<int>>& cost, const vector<vector<int>>& val, int g, int rem, vector<vector<int>>& memo) { // @step:callRoot // @step:fnEnter',
    '    if (g == (int)cost.size() || rem <= 0) return 0;',
    '    if (memo[g][rem] != -1) return memo[g][rem];',
    '    int ans = dfs(cost, val, g + 1, rem, memo); // @step:branchNoPick',
    '    for (size_t k = 0; k < cost[g].size(); ++k) {',
    '        if (rem >= cost[g][k]) {',
    '            ans = max(ans, dfs(cost, val, g + 1, rem - cost[g][k], memo) + val[g][k]); // @step:branchPick',
    '        }',
    '    }',
    '    return memo[g][rem] = ans;',
    '}',
  ],
  python: [
    '# 阶段 2: 记忆化搜索',
    'def dfs(cost: list[list[int]], val: list[list[int]], g: int, rem: int, memo: list[list[int]]) -> int: # @step:callRoot // @step:fnEnter',
    '    if g == len(cost) or rem <= 0:',
    '        return 0',
    '    if memo[g][rem] != -1: # @step:memoCheck',
    '        return memo[g][rem]',
    '    ans = dfs(cost, val, g + 1, rem, memo) # @step:branchNoPick',
    '    for c, v in zip(cost[g], val[g]):',
    '        if rem >= c:',
    '            ans = max(ans, dfs(cost, val, g + 1, rem - c, memo) + v) # @step:branchPick',
    '    memo[g][rem] = ans # @step:memoStore',
    '    return ans',
  ],
  javascript: [
    '// 阶段 2: 记忆化搜索',
    'export function dfs(cost, val, g, rem, memo) { // @step:callRoot // @step:fnEnter',
    '  if (g === cost.length || rem <= 0) return 0;',
    '  if (memo[g][rem] !== -1) return memo[g][rem]; // @step:memoCheck',
    '  let ans = dfs(cost, val, g + 1, rem, memo); // @step:branchNoPick',
    '  for (let k = 0; k < cost[g].length; k++) {',
    '    if (rem >= cost[g][k]) {',
    '      ans = Math.max(ans, dfs(cost, val, g + 1, rem - cost[g][k], memo) + val[g][k]); // @step:branchPick',
    '    }',
    '  }',
    '  return (memo[g][rem] = ans); // @step:memoStore',
    '}',
  ],
};


export const DEPENDENT_STAGE3_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    'package class073;',
    '',
    '// 阶段 3: 严格二维位置依赖动态规划',
    'public class Code05_DependentKnapsack2D {',
    '    public static int compute2D(int[][] cost, int[][] val, int[] size, int groupCount, int budget) {',
    '        int[][] dp = new int[groupCount + 1][budget + 1]; // @step:initDp',
    '        for (int g = 1; g <= groupCount; g++) { // @step:outerLoopG',
    '            int kCount = size[g - 1];',
    '            for (int j = 0; j <= budget; j++) { // @step:innerLoopJ',
    '                dp[g][j] = dp[g - 1][j] # @step:inheritNoPick; // @step:inheritNoPick // @step:inheritNoPick',
    '                for (int k = 0; k < kCount; k++) { // @step:loopCombo',
    '                    int c = cost[g - 1][k];',
    '                    int v = val[g - 1][k];',
    '                    if (j >= c) {',
    '                        dp[g][j] = Math.max(dp[g][j], dp[g - 1][j - c] + v); // @step:updatePick',
    '                    }',
    '                }',
    '            }',
    '        }',
    '        return dp[groupCount][budget]; // @step:returnAns',
    '    }',
    '}',
  ],
  cpp: [
    '#include <vector>',
    '#include <algorithm>',
    'using namespace std;',
    '',
    '// 阶段 3: 严格二维动态规划',
    'int compute2D(const vector<vector<int>>& cost, const vector<vector<int>>& val, int budget) {',
    '    int G = cost.size();',
    '    vector<vector<int>> dp(G + 1, vector<int>(budget + 1, 0)); // @step:initDp',
    '    for (int g = 1; g <= G; ++g) { // @step:outerLoopG',
    '        for (int j = 0; j <= budget; ++j) { // @step:innerLoopJ',
    '            dp[g][j] = dp[g - 1][j]; // @step:inheritNoPick',
    '            for (size_t k = 0; k < cost[g - 1].size(); ++k) { // @step:loopCombo',
    '                int c = cost[g - 1][k], v = val[g - 1][k];',
    '                if (j >= c) dp[g][j] = max(dp[g][j], dp[g - 1][j - c] + v); // @step:updatePick',
    '            }',
    '        }',
    '    }',
    '    return dp[G][budget] # @step:returnAns; // @step:returnAns',
    '}',
  ],
  python: [
    '# 阶段 3: 严格二维动态规划',
    'def compute_2d(cost: list[list[int]], val: list[list[int]], budget: int) -> int:',
    '    G = len(cost)',
    '    dp = [[0] * (budget + 1) for _ in range(G + 1)] # @step:initDp',
    '    for g in range(1, G + 1): # @step:outerLoopG',
    '        for j in range(budget + 1): # @step:innerLoopJ',
    '            dp[g][j] = dp[g - 1][j]',
    '            for c, v in zip(cost[g - 1], val[g - 1]): # @step:loopCombo',
    '                if j >= c:',
    '                    dp[g][j] = max(dp[g][j], dp[g - 1][j - c] + v) # @step:updatePick',
    '    return dp[G][budget]',
  ],
  javascript: [
    '// 阶段 3: 严格二维动态规划',
    'export function compute2D(cost, val, budget) {',
    '  const G = cost.length;',
    '  const dp = Array.from({ length: G + 1 }, () => new Array(budget + 1).fill(0)); // @step:initDp',
    '  for (let g = 1; g <= G; g++) { // @step:outerLoopG',
    '    for (let j = 0; j <= budget; j++) { // @step:innerLoopJ',
    '      dp[g][j] = dp[g - 1][j];',
    '      for (let k = 0; k < cost[g - 1].length; k++) { // @step:loopCombo',
    '        const c = cost[g - 1][k], v = val[g - 1][k];',
    '        if (j >= c) dp[g][j] = Math.max(dp[g][j], dp[g - 1][j - c] + v); // @step:updatePick',
    '      }',
    '    }',
    '  }',
    '  return dp[G][budget]; // @step:returnAns',
    '}',
  ],
};


export const LAST_STONE_STAGE1_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    'package class073;',
    '',
    '// 阶段 1: 暴力递归 (选出最接近 sum/2 的子集最大重量)',
    'public class Code04_LastStoneWeightIIRecursion {',
    '    public static int lastStoneWeightII(int[] stones) { // @step:callRoot',
    '        int sum = 0;',
    '        for (int s : stones) sum += s;',
    '        int t = sum / 2;',
    '        int near = dfs(stones, 0, t); // @step:fnEnter',
    '        return sum - 2 * near;',
    '    }',
    '    public static int dfs(int[] stones, int i, int remCap) { // @step:fnEnter',
    '        if (i == stones.length || remCap <= 0) return 0; // @step:baseCheck',
    '        int p1 = dfs(stones, i + 1, remCap); // @step:branch1',
    '        int p2 = (remCap >= stones[i]) ? dfs(stones, i + 1, remCap - stones[i]) + stones[i] : 0; // @step:branch2',
    '        return Math.max(p1, p2); // @step:returnMax',
    '    }',
    '}',
  ],
  cpp: [
    '#include <vector>',
    '#include <numeric>',
    '#include <algorithm>',
    'using namespace std;',
    '',
    '// 阶段 1: 暴力递归',
    'int dfs(const vector<int>& stones, int i, int remCap) { // @step:fnEnter',
    '    if (i == (int)stones.size() || remCap <= 0) return 0; // @step:baseCheck',
    '    int p1 = dfs(stones, i + 1, remCap); // @step:branch1',
    '    int p2 = (remCap >= stones[i]) ? dfs(stones, i + 1, remCap - stones[i]) + stones[i] : 0; // @step:branch2',
    '    return max(p1, p2); // @step:returnMax',
    '}',
    'int lastStoneWeightII(vector<int>& stones) {',
    '    int sum = 0;',
    '    for (int s : stones) sum += s;',
    '    int near = dfs(stones, 0, sum / 2); // @step:callRoot',
    '    return sum - 2 * near;',
    '}',
  ],
  python: [
    '# 阶段 1: 暴力递归',
    'def last_stone_weight_ii(stones: list[int]) -> int: # @step:callRoot',
    '    s = sum(stones)',
    '    t = s // 2',
    '    def dfs(i: int, rem_cap: int) -> int: # @step:fnEnter',
    '        if i == len(stones) or rem_cap <= 0: # @step:baseCheck',
    '            return 0',
    '        p1 = dfs(i + 1, rem_cap) # @step:branch1',
    '        p2 = dfs(i + 1, rem_cap - stones[i]) + stones[i] if rem_cap >= stones[i] else 0 # @step:branch2',
    '        return max(p1, p2) # @step:returnMax',
    '    near = dfs(0, t) # @step:callRoot',
    '    return s - 2 * near',
  ],
  javascript: [
    '// 阶段 1: 暴力递归',
    'export function lastStoneWeightII(stones) { // @step:callRoot',
    '  const sum = stones.reduce((a, b) => a + b, 0);',
    '  const t = Math.floor(sum / 2);',
    '  function dfs(i, remCap) { // @step:fnEnter',
    '    if (i === stones.length || remCap <= 0) return 0; // @step:baseCheck',
    '    const p1 = dfs(i + 1, remCap); // @step:branch1',
    '    const p2 = remCap >= stones[i] ? dfs(i + 1, remCap - stones[i]) + stones[i] : 0; // @step:branch2',
    '    return Math.max(p1, p2); // @step:returnMax',
    '  }',
    '  const near = dfs(0, t); // @step:callRoot',
    '  return sum - 2 * near;',
    '}',
  ],
};


export const LAST_STONE_STAGE2_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    'package class073;',
    'import java.util.Arrays;',
    '',
    '// 阶段 2: 记忆化搜索',
    'public class Code04_LastStoneWeightIIMemo {',
    '    public static int lastStoneWeightII(int[] stones) { // @step:callRoot',
    '        int sum = 0;',
    '        for (int s : stones) sum += s;',
    '        int t = sum / 2;',
    '        int[][] memo = new int[stones.length + 1][t + 1]; // @step:memoInit',
    '        for (int[] row : memo) Arrays.fill(row, -1);',
    '        int near = dfs(stones, 0, t, memo); // @step:fnEnter',
    '        return sum - 2 * near;',
    '    }',
    '    public static int dfs(int[] stones, int i, int remCap, int[][] memo) { // @step:fnEnter',
    '        if (i == stones.length || remCap <= 0) return 0; // @step:baseCheck',
    '        if (memo[i][remCap] != -1) return memo[i][remCap]; // @step:memoCheck',
    '        int p1 = dfs(stones, i + 1, remCap, memo); // @step:branch1',
    '        int p2 = (remCap >= stones[i]) ? dfs(stones, i + 1, remCap - stones[i], memo) + stones[i] : 0; // @step:branch2',
    '        return memo[i][remCap] = Math.max(p1, p2); // @step:memoStore',
    '    }',
    '}',
  ],
  cpp: [
    '#include <vector>',
    '#include <numeric>',
    '#include <algorithm>',
    'using namespace std;',
    '',
    '// 阶段 2: 记忆化搜索',
    'int dfs(const vector<int>& stones, int i, int remCap, vector<vector<int>>& memo) { // @step:fnEnter',
    '    if (i == (int)stones.size() || remCap <= 0) return 0; // @step:baseCheck',
    '    if (memo[i][remCap] != -1) return memo[i][remCap]; // @step:memoCheck',
    '    int p1 = dfs(stones, i + 1, remCap, memo); // @step:branch1',
    '    int p2 = (remCap >= stones[i]) ? dfs(stones, i + 1, remCap - stones[i], memo) + stones[i] : 0; // @step:branch2',
    '    return memo[i][remCap] = max(p1, p2); // @step:memoStore',
    '}',
    'int lastStoneWeightII(vector<int>& stones) {',
    '    int sum = 0;',
    '    for (int s : stones) sum += s;',
    '    int t = sum / 2;',
    '    vector<vector<int>> memo(stones.size() + 1, vector<int>(t + 1, -1));',
    '    int near = dfs(stones, 0, t, memo); // @step:fnEnter',
    '    return sum - 2 * near;',
    '}',
  ],
  python: [
    '# 阶段 2: 记忆化搜索',
    'def last_stone_weight_ii(stones: list[int]) -> int:',
    '    s = sum(stones)',
    '    t = s // 2',
    '    memo = [[-1] * (t + 1) for _ in range(len(stones) + 1)]',
    '    def dfs(i: int, rem_cap: int) -> int:',
    '        if i == len(stones) or rem_cap <= 0: # @step:baseCheck',
    '            return 0',
    '        if memo[i][rem_cap] != -1: # @step:memoCheck',
    '            return memo[i][rem_cap]',
    '        p1 = dfs(i + 1, rem_cap)',
    '        p2 = dfs(i + 1, rem_cap - stones[i]) + stones[i] if rem_cap >= stones[i] else 0',
    '        memo[i][rem_cap] = max(p1, p2) # @step:memoStore',
    '        return memo[i][rem_cap]',
    '    near = dfs(0, t)',
    '    return s - 2 * near',
  ],
  javascript: [
    '// 阶段 2: 记忆化搜索',
    'export function lastStoneWeightII(stones) {',
    '  const sum = stones.reduce((a, b) => a + b, 0);',
    '  const t = Math.floor(sum / 2);',
    '  const memo = Array.from({ length: stones.length + 1 }, () => new Array(t + 1).fill(-1));',
    '  function dfs(i, remCap) {',
    '    if (i === stones.length || remCap <= 0) return 0; // @step:baseCheck',
    '    if (memo[i][remCap] !== -1) return memo[i][remCap]; // @step:memoCheck',
    '    const p1 = dfs(i + 1, remCap);',
    '    const p2 = remCap >= stones[i] ? dfs(i + 1, remCap - stones[i]) + stones[i] : 0; // @step:branch2',
    '    return (memo[i][remCap] = Math.max(p1, p2)); // @step:memoStore',
    '  }',
    '  const near = dfs(0, t);',
    '  return sum - 2 * near;',
    '}',
  ],
};


export const LAST_STONE_STAGE3_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    'package class073;',
    '',
    '// 阶段 3: 严格二维位置依赖动态规划',
    'public class Code04_LastStoneWeightII2D {',
    '    public static int lastStoneWeightII(int[] stones) {',
    '        int sum = 0;',
    '        for (int s : stones) sum += s;',
    '        int t = sum / 2;',
    '        int n = stones.length;',
    '        int[][] dp = new int[n + 1][t + 1]; // @step:initDp',
    '        for (int i = 1; i <= n; i++) { // @step:outerLoopI',
    '            int weight = stones[i - 1];',
    '            for (int j = 0; j <= t; j++) { // @step:innerLoopJ',
    '                dp[i][j] = dp[i - 1][j]; // @step:inheritNoPick',
    '                if (j >= weight) {',
    '                    dp[i][j] = Math.max(dp[i][j], dp[i - 1][j - weight] + weight); // @step:updatePick',
    '                }',
    '            }',
    '        }',
    '        return sum - 2 * dp[n][t];',
    '    }',
    '}',
  ],
  cpp: [
    '#include <vector>',
    '#include <numeric>',
    '#include <algorithm>',
    'using namespace std;',
    '',
    '// 阶段 3: 严格二维动态规划',
    'int lastStoneWeightII(vector<int>& stones) {',
    '    int sum = 0;',
    '    for (int s : stones) sum += s;',
    '    int t = sum / 2;',
    '    int n = stones.size();',
    '    vector<vector<int>> dp(n + 1, vector<int>(t + 1, 0)); // @step:initDp',
    '    for (int i = 1; i <= n; ++i) { // @step:outerLoopI',
    '        int weight = stones[i - 1];',
    '        for (int j = 0; j <= t; ++j) { // @step:innerLoopJ',
    '            dp[i][j] = dp[i - 1][j]; // @step:inheritNoPick',
    '            if (j >= weight) dp[i][j] = max(dp[i][j], dp[i - 1][j - weight] + weight); // @step:updatePick',
    '        }',
    '    }',
    '    return sum - 2 * dp[n][t];',
    '}',
  ],
  python: [
    '# 阶段 3: 严格二维动态规划',
    'def last_stone_weight_ii(stones: list[int]) -> int:',
    '    s = sum(stones)',
    '    t = s // 2',
    '    n = len(stones)',
    '    dp = [[0] * (t + 1) for _ in range(n + 1)] # @step:initDp',
    '    for i in range(1, n + 1): # @step:outerLoopI',
    '        w = stones[i - 1]',
    '        for j in range(t + 1): # @step:innerLoopJ',
    '            dp[i][j] = dp[i - 1][j] # @step:inheritNoPick',
    '            if j >= w:',
    '                dp[i][j] = max(dp[i][j], dp[i - 1][j - w] + w) # @step:updatePick',
    '    return s - 2 * dp[n][t]',
  ],
  javascript: [
    '// 阶段 3: 严格二维动态规划',
    'export function lastStoneWeightII(stones) {',
    '  const sum = stones.reduce((a, b) => a + b, 0);',
    '  const t = Math.floor(sum / 2);',
    '  const n = stones.length;',
    '  const dp = Array.from({ length: n + 1 }, () => new Array(t + 1).fill(0)); // @step:initDp',
    '  for (let i = 1; i <= n; i++) { // @step:outerLoopI',
    '    const w = stones[i - 1];',
    '    for (let j = 0; j <= t; j++) { // @step:innerLoopJ',
    '      dp[i][j] = dp[i - 1][j]; // @step:inheritNoPick',
    '      if (j >= w) dp[i][j] = Math.max(dp[i][j], dp[i - 1][j - w] + w); // @step:updatePick',
    '    }',
    '  }',
    '  return sum - 2 * dp[n][t];',
    '}',
  ],
};


export const TARGET_SUM_STAGE1_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    'package class073;',
    '',
    '// 阶段 1: 暴力递归 (目标和转子集和分治)',
    'public class Code03_TargetSumRecursion {',
    '    public static int findTargetSumWays(int[] nums, int target) { // @step:callRoot',
    '        int sum = 0;',
    '        for (int n : nums) sum += n;',
    '        if (sum < Math.abs(target) || ((target + sum) & 1) != 0) return 0;',
    '        int t = (target + sum) >> 1;',
    '        return dfs(nums, 0, t);',
    '    }',
    '    public static int dfs(int[] nums, int i, int rem) {',
    '        if (i == nums.length) return rem == 0 ? 1 : 0; // @step:baseCheck',
    '        int p1 = dfs(nums, i + 1, rem);',
    '        int p2 = (rem >= nums[i]) ? dfs(nums, i + 1, rem - nums[i]) : 0;',
    '        return p1 + p2;',
    '    }',
    '}',
  ],
  cpp: [
    '#include <vector>',
    '#include <cmath>',
    'using namespace std;',
    '',
    '// 阶段 1: 暴力递归',
    'int dfs(const vector<int>& nums, int i, int rem) {',
    '    if (i == (int)nums.size()) return rem == 0 ? 1 : 0;',
    '    int p1 = dfs(nums, i + 1, rem);',
    '    int p2 = (rem >= nums[i]) ? dfs(nums, i + 1, rem - nums[i]) : 0;',
    '    return p1 + p2;',
    '}',
    'int findTargetSumWays(vector<int>& nums, int target) {',
    '    int sum = 0;',
    '    for (int x : nums) sum += x;',
    '    if (sum < abs(target) || ((target + sum) & 1)) return 0;',
    '    return dfs(nums, 0, (target + sum) / 2);',
    '}',
  ],
  python: [
    '# 阶段 1: 暴力递归',
    'def find_target_sum_ways(nums: list[int], target: int) -> int: # @step:callRoot',
    '    s = sum(nums)',
    '    if s < abs(target) or (s + target) % 2 != 0:',
    '        return 0',
    '    t = (s + target) // 2',
    '    def dfs(i: int, rem: int) -> int:',
    '        if i == len(nums): # @step:baseCheck',
    '            return 1 if rem == 0 else 0',
    '        p1 = dfs(i + 1, rem)',
    '        p2 = dfs(i + 1, rem - nums[i]) if rem >= nums[i] else 0',
    '        return p1 + p2',
    '    return dfs(0, t)',
  ],
  javascript: [
    '// 阶段 1: 暴力递归',
    'export function findTargetSumWays(nums, target) { // @step:callRoot',
    '  const sum = nums.reduce((a, b) => a + b, 0);',
    '  if (sum < Math.abs(target) || (sum + target) % 2 !== 0) return 0;',
    '  const t = Math.floor((sum + target) / 2);',
    '  function dfs(i, rem) {',
    '    if (i === nums.length) return rem === 0 ? 1 : 0; // @step:baseCheck',
    '    const p1 = dfs(i + 1, rem);',
    '    const p2 = rem >= nums[i] ? dfs(i + 1, rem - nums[i]) : 0;',
    '    return p1 + p2;',
    '  }',
    '  return dfs(0, t);',
    '}',
  ],
};


export const TARGET_SUM_STAGE2_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    'package class073;',
    'import java.util.Arrays;',
    '',
    '// 阶段 2: 记忆化搜索',
    'public class Code03_TargetSumMemo {',
    '    public static int findTargetSumWays(int[] nums, int target) {',
    '        int sum = 0;',
    '        for (int n : nums) sum += n;',
    '        if (sum < Math.abs(target) || ((target + sum) & 1) != 0) return 0;',
    '        int t = (target + sum) >> 1;',
    '        int[][] memo = new int[nums.length + 1][t + 1];',
    '        for (int[] row : memo) Arrays.fill(row, -1);',
    '        return dfs(nums, 0, t, memo);',
    '    }',
    '    public static int dfs(int[] nums, int i, int rem, int[][] memo) {',
    '        if (i == nums.length) return rem == 0 ? 1 : 0; // @step:baseCheck',
    '        if (memo[i][rem] != -1) return memo[i][rem];',
    '        int p1 = dfs(nums, i + 1, rem, memo);',
    '        int p2 = (rem >= nums[i]) ? dfs(nums, i + 1, rem - nums[i], memo) : 0;',
    '        return memo[i][rem] = p1 + p2;',
    '    }',
    '}',
  ],
  cpp: [
    '#include <vector>',
    '#include <cmath>',
    'using namespace std;',
    '',
    '// 阶段 2: 记忆化搜索',
    'int dfs(const vector<int>& nums, int i, int rem, vector<vector<int>>& memo) {',
    '    if (i == (int)nums.size()) return rem == 0 ? 1 : 0;',
    '    if (memo[i][rem] != -1) return memo[i][rem];',
    '    int p1 = dfs(nums, i + 1, rem, memo);',
    '    int p2 = (rem >= nums[i]) ? dfs(nums, i + 1, rem - nums[i], memo) : 0;',
    '    return memo[i][rem] = p1 + p2;',
    '}',
    'int findTargetSumWays(vector<int>& nums, int target) {',
    '    int sum = 0;',
    '    for (int x : nums) sum += x;',
    '    if (sum < abs(target) || ((target + sum) & 1)) return 0;',
    '    int t = (target + sum) / 2;',
    '    vector<vector<int>> memo(nums.size() + 1, vector<int>(t + 1, -1));',
    '    return dfs(nums, 0, t, memo);',
    '}',
  ],
  python: [
    '# 阶段 2: 记忆化搜索',
    'def find_target_sum_ways(nums: list[int], target: int) -> int:',
    '    s = sum(nums)',
    '    if s < abs(target) or (s + target) % 2 != 0:',
    '        return 0',
    '    t = (s + target) // 2',
    '    memo = [[-1] * (t + 1) for _ in range(len(nums) + 1)]',
    '    def dfs(i: int, rem: int) -> int:',
    '        if i == len(nums): # @step:baseCheck',
    '            return 1 if rem == 0 else 0',
    '        if memo[i][rem] != -1:',
    '            return memo[i][rem]',
    '        p1 = dfs(i + 1, rem)',
    '        p2 = dfs(i + 1, rem - nums[i]) if rem >= nums[i] else 0',
    '        memo[i][rem] = p1 + p2',
    '        return memo[i][rem]',
    '    return dfs(0, t)',
  ],
  javascript: [
    '// 阶段 2: 记忆化搜索',
    'export function findTargetSumWays(nums, target) {',
    '  const sum = nums.reduce((a, b) => a + b, 0);',
    '  if (sum < Math.abs(target) || (sum + target) % 2 !== 0) return 0;',
    '  const t = Math.floor((sum + target) / 2);',
    '  const memo = Array.from({ length: nums.length + 1 }, () => new Array(t + 1).fill(-1));',
    '  function dfs(i, rem) {',
    '    if (i === nums.length) return rem === 0 ? 1 : 0; // @step:baseCheck',
    '    if (memo[i][rem] !== -1) return memo[i][rem];',
    '    const p1 = dfs(i + 1, rem);',
    '    const p2 = rem >= nums[i] ? dfs(i + 1, rem - nums[i]) : 0;',
    '    return (memo[i][rem] = p1 + p2);',
    '  }',
    '  return dfs(0, t);',
    '}',
  ],
};


export const TARGET_SUM_STAGE3_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    'package class073;',
    '',
    '// 阶段 3: 严格二维位置依赖动态规划',
    'public class Code03_TargetSum2D {',
    '    public static int findTargetSumWays(int[] nums, int target) {',
    '        int sum = 0;',
    '        for (int n : nums) sum += n;',
    '        if (sum < Math.abs(target) || ((target + sum) & 1) != 0) return 0;',
    '        int t = (target + sum) >> 1;',
    '        int n = nums.length;',
    '        int[][] dp = new int[n + 1][t + 1];',
    '        dp[0][0] = 1;',
    '        for (int i = 1; i <= n; i++) { // @step:outerLoopI',
    '            int num = nums[i - 1];',
    '            for (int j = 0; j <= t; j++) {',
    '                dp[i][j] = dp[i - 1][j]; // @step:inheritNoPick',
    '                if (j >= num) {',
    '                    dp[i][j] += dp[i - 1][j - num]; // @step:updatePick',
    '                }',
    '            }',
    '        }',
    '        return dp[n][t];',
    '    }',
    '}',
  ],
  cpp: [
    '#include <vector>',
    '#include <cmath>',
    'using namespace std;',
    '',
    '// 阶段 3: 严格二维动态规划',
    'int findTargetSumWays(vector<int>& nums, int target) {',
    '    int sum = 0;',
    '    for (int x : nums) sum += x;',
    '    if (sum < abs(target) || ((target + sum) & 1)) return 0;',
    '    int t = (target + sum) / 2;',
    '    int n = nums.size();',
    '    vector<vector<int>> dp(n + 1, vector<int>(t + 1, 0)); // @step:initDp',
    '    dp[0][0] = 1;',
    '    for (int i = 1; i <= n; ++i) { // @step:outerLoopI',
    '        int num = nums[i - 1];',
    '        for (int j = 0; j <= t; ++j) {',
    '            dp[i][j] = dp[i - 1][j]; // @step:inheritNoPick',
    '            if (j >= num) dp[i][j] += dp[i - 1][j - num]; // @step:updatePick',
    '        }',
    '    }',
    '    return dp[n][t];',
    '}',
  ],
  python: [
    '# 阶段 3: 严格二维动态规划',
    'def find_target_sum_ways(nums: list[int], target: int) -> int:',
    '    s = sum(nums)',
    '    if s < abs(target) or (s + target) % 2 != 0:',
    '        return 0',
    '    t = (s + target) // 2',
    '    n = len(nums)',
    '    dp = [[0] * (t + 1) for _ in range(n + 1)] # @step:initDp',
    '    dp[0][0] = 1',
    '    for i in range(1, n + 1): # @step:outerLoopI',
    '        num = nums[i - 1]',
    '        for j in range(t + 1):',
    '            dp[i][j] = dp[i - 1][j] # @step:inheritNoPick',
    '            if j >= num:',
    '                dp[i][j] += dp[i - 1][j - num] # @step:updatePick',
    '    return dp[n][t]',
  ],
  javascript: [
    '// 阶段 3: 严格二维动态规划',
    'export function findTargetSumWays(nums, target) {',
    '  const sum = nums.reduce((a, b) => a + b, 0);',
    '  if (sum < Math.abs(target) || (sum + target) % 2 !== 0) return 0;',
    '  const t = Math.floor((sum + target) / 2);',
    '  const n = nums.length;',
    '  const dp = Array.from({ length: n + 1 }, () => new Array(t + 1).fill(0)); // @step:initDp',
    '  dp[0][0] = 1;',
    '  for (let i = 1; i <= n; i++) { // @step:outerLoopI',
    '    const num = nums[i - 1];',
    '    for (let j = 0; j <= t; j++) {',
    '      dp[i][j] = dp[i - 1][j]; // @step:inheritNoPick',
    '      if (j >= num) dp[i][j] += dp[i - 1][j - num]; // @step:updatePick',
    '    }',
    '  }',
    '  return dp[n][t];',
    '}',
  ],
};


export const BUY_GOODS_STAGE1_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    'package class073;',
    '',
    '// 阶段 1: 暴力递归 (贪心过滤必买后对普通游戏分治)',
    'public class Code02_BuyGoodsRecursion {',
    '    public static int maxHappy(int[] a, int[] b, int[] w, int budget) {',
    '        int greedyHappy = 0;',
    '        int curBudget = budget;',
    '        int m = a.length;',
    '        int[] cost = new int[m];',
    '        int[] val = new int[m];',
    '        int normalCount = 0;',
    '        for (int i = 0; i < m; i++) {',
    '            int well = a[i] - 2 * b[i];',
    '            if (well >= 0) {',
    '                greedyHappy += w[i];',
    '                curBudget += well;',
    '            } else {',
    '                cost[normalCount] = -well;',
    '                val[normalCount++] = w[i];',
    '            }',
    '        }',
    '        return greedyHappy + dfs(cost, val, normalCount, 0, curBudget);',
    '    }',
    '    public static int dfs(int[] cost, int[] val, int n, int i, int rem) {',
    '        if (i == n || rem <= 0) return 0;',
    '        int p1 = dfs(cost, val, n, i + 1, rem);',
    '        int p2 = (rem >= cost[i]) ? dfs(cost, val, n, i + 1, rem - cost[i]) + val[i] : 0;',
    '        return Math.max(p1, p2); // @step:returnMax',
    '    }',
    '}',
  ],
  cpp: [
    '#include <vector>',
    '#include <algorithm>',
    'using namespace std;',
    '',
    '// 阶段 1: 暴力递归',
    'int dfs(const vector<int>& cost, const vector<int>& val, int i, int rem) {',
    '    if (i == (int)cost.size() || rem <= 0) return 0;',
    '    int p1 = dfs(cost, val, i + 1, rem);',
    '    int p2 = (rem >= cost[i]) ? dfs(cost, val, i + 1, rem - cost[i]) + val[i] : 0;',
    '    return max(p1, p2); // @step:returnMax',
    '}',
    'int maxHappy(const vector<int>& a, const vector<int>& b, const vector<int>& w, int budget) {',
    '    int happy = 0;',
    '    vector<int> cost, val;',
    '    for (size_t i = 0; i < a.size(); ++i) {',
    '        int well = a[i] - 2 * b[i];',
    '        if (well >= 0) { happy += w[i]; budget += well; }',
    '        else { cost.push_back(-well); val.push_back(w[i]); }',
    '    }',
    '    return happy + dfs(cost, val, 0, budget);',
    '}',
  ],
  python: [
    '# 阶段 1: 暴力递归',
    'def max_happy(a: list[int], b: list[int], w: list[int], budget: int) -> int:',
    '    happy = 0',
    '    cost, val = [], []',
    '    for orig, disc, h in zip(a, b, w):',
    '        well = orig - 2 * disc',
    '        if well >= 0:',
    '            happy += h',
    '            budget += well',
    '        else:',
    '            cost.append(-well)',
    '            val.append(h)',
    '    def dfs(i: int, rem: int) -> int:',
    '        if i == len(cost) or rem <= 0:',
    '            return 0',
    '        p1 = dfs(i + 1, rem)',
    '        p2 = dfs(i + 1, rem - cost[i]) + val[i] if rem >= cost[i] else 0',
    '        return max(p1, p2) # @step:returnMax',
    '    return happy + dfs(0, budget)',
  ],
  javascript: [
    '// 阶段 1: 暴力递归',
    'export function maxHappy(a, b, w, budget) {',
    '  let happy = 0;',
    '  const cost = [], val = [];',
    '  for (let i = 0; i < a.length; i++) {',
    '    const well = a[i] - 2 * b[i];',
    '    if (well >= 0) { happy += w[i]; budget += well; }',
    '    else { cost.push(-well); val.push(w[i]); }',
    '  }',
    '  function dfs(i, rem) {',
    '    if (i === cost.length || rem <= 0) return 0;',
    '    const p1 = dfs(i + 1, rem);',
    '    const p2 = rem >= cost[i] ? dfs(i + 1, rem - cost[i]) + val[i] : 0;',
    '    return Math.max(p1, p2); // @step:returnMax',
    '  }',
    '  return happy + dfs(0, budget);',
    '}',
  ],
};


export const BUY_GOODS_STAGE2_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    'package class073;',
    'import java.util.Arrays;',
    '',
    '// 阶段 2: 记忆化搜索',
    'public class Code02_BuyGoodsMemo {',
    '    public static int maxHappy(int[] a, int[] b, int[] w, int budget) {',
    '        int greedyHappy = 0;',
    '        int curBudget = budget;',
    '        int m = a.length;',
    '        int[] cost = new int[m];',
    '        int[] val = new int[m];',
    '        int normalCount = 0;',
    '        for (int i = 0; i < m; i++) {',
    '            int well = a[i] - 2 * b[i];',
    '            if (well >= 0) {',
    '                greedyHappy += w[i];',
    '                curBudget += well;',
    '            } else {',
    '                cost[normalCount] = -well;',
    '                val[normalCount++] = w[i];',
    '            }',
    '        }',
    '        int[][] memo = new int[normalCount + 1][curBudget + 1];',
    '        for (int[] row : memo) Arrays.fill(row, -1);',
    '        return greedyHappy + dfs(cost, val, normalCount, 0, curBudget, memo);',
    '    }',
    '    public static int dfs(int[] cost, int[] val, int n, int i, int rem, int[][] memo) {',
    '        if (i == n || rem <= 0) return 0;',
    '        if (memo[i][rem] != -1) return memo[i][rem];',
    '        int p1 = dfs(cost, val, n, i + 1, rem, memo);',
    '        int p2 = (rem >= cost[i]) ? dfs(cost, val, n, i + 1, rem - cost[i], memo) + val[i] : 0;',
    '        return memo[i][rem] = Math.max(p1, p2);',
    '    }',
    '}',
  ],
  cpp: [
    '#include <vector>',
    '#include <algorithm>',
    'using namespace std;',
    '',
    '// 阶段 2: 记忆化搜索',
    'int dfs(const vector<int>& cost, const vector<int>& val, int i, int rem, vector<vector<int>>& memo) {',
    '    if (i == (int)cost.size() || rem <= 0) return 0;',
    '    if (memo[i][rem] != -1) return memo[i][rem];',
    '    int p1 = dfs(cost, val, i + 1, rem, memo);',
    '    int p2 = (rem >= cost[i]) ? dfs(cost, val, i + 1, rem - cost[i], memo) + val[i] : 0;',
    '    return memo[i][rem] = max(p1, p2);',
    '}',
    'int maxHappy(const vector<int>& a, const vector<int>& b, const vector<int>& w, int budget) {',
    '    int happy = 0;',
    '    vector<int> cost, val;',
    '    for (size_t i = 0; i < a.size(); ++i) {',
    '        int well = a[i] - 2 * b[i];',
    '        if (well >= 0) { happy += w[i]; budget += well; }',
    '        else { cost.push_back(-well); val.push_back(w[i]); }',
    '    }',
    '    vector<vector<int>> memo(cost.size() + 1, vector<int>(budget + 1, -1));',
    '    return happy + dfs(cost, val, 0, budget, memo);',
    '}',
  ],
  python: [
    '# 阶段 2: 记忆化搜索',
    'def max_happy(a: list[int], b: list[int], w: list[int], budget: int) -> int:',
    '    happy = 0',
    '    cost, val = [], []',
    '    for orig, disc, h in zip(a, b, w):',
    '        well = orig - 2 * disc',
    '        if well >= 0:',
    '            happy += h',
    '            budget += well',
    '        else:',
    '            cost.append(-well)',
    '            val.append(h)',
    '    memo = [[-1] * (budget + 1) for _ in range(len(cost) + 1)]',
    '    def dfs(i: int, rem: int) -> int:',
    '        if i == len(cost) or rem <= 0:',
    '            return 0',
    '        if memo[i][rem] != -1:',
    '            return memo[i][rem]',
    '        p1 = dfs(i + 1, rem)',
    '        p2 = dfs(i + 1, rem - cost[i]) + val[i] if rem >= cost[i] else 0',
    '        memo[i][rem] = max(p1, p2)',
    '        return memo[i][rem]',
    '    return happy + dfs(0, budget)',
  ],
  javascript: [
    '// 阶段 2: 记忆化搜索',
    'export function maxHappy(a, b, w, budget) {',
    '  let happy = 0;',
    '  const cost = [], val = [];',
    '  for (let i = 0; i < a.length; i++) {',
    '    const well = a[i] - 2 * b[i];',
    '    if (well >= 0) { happy += w[i]; budget += well; }',
    '    else { cost.push(-well); val.push(w[i]); }',
    '  }',
    '  const memo = Array.from({ length: cost.length + 1 }, () => new Array(budget + 1).fill(-1));',
    '  function dfs(i, rem) {',
    '    if (i === cost.length || rem <= 0) return 0;',
    '    if (memo[i][rem] !== -1) return memo[i][rem];',
    '    const p1 = dfs(i + 1, rem);',
    '    const p2 = rem >= cost[i] ? dfs(i + 1, rem - cost[i]) + val[i] : 0;',
    '    return (memo[i][rem] = Math.max(p1, p2));',
    '  }',
    '  return happy + dfs(0, budget);',
    '}',
  ],
};


export const BUY_GOODS_STAGE3_CODE_LANGUAGES: Record<string, string[]> = {
  java: [
    'package class073;',
    '',
    '// 阶段 3: 严格二维位置依赖动态规划',
    'public class Code02_BuyGoods2D {',
    '    public static int maxHappy(int[] a, int[] b, int[] w, int budget) {',
    '        int happy = 0;',
    '        int curBudget = budget;',
    '        int m = a.length;',
    '        int[] cost = new int[m];',
    '        int[] val = new int[m];',
    '        int n = 0;',
    '        for (int i = 0; i < m; i++) {',
    '            int well = a[i] - 2 * b[i];',
    '            if (well >= 0) {',
    '                happy += w[i];',
    '                curBudget += well;',
    '            } else {',
    '                cost[n] = -well;',
    '                val[n++] = w[i];',
    '            }',
    '        }',
    '        int[][] dp = new int[n + 1][curBudget + 1];',
    '        for (int i = 1; i <= n; i++) { // @step:outerLoopI',
    '            int c = cost[i - 1];',
    '            int v = val[i - 1];',
    '            for (int j = 0; j <= curBudget; j++) {',
    '                dp[i][j] = dp[i - 1][j]; // @step:inheritNoPick',
    '                if (j >= c) {',
    '                    dp[i][j] = Math.max(dp[i][j], dp[i - 1][j - c] + v); // @step:updatePick',
    '                }',
    '            }',
    '        }',
    '        return happy + dp[n][curBudget];',
    '    }',
    '}',
  ],
  cpp: [
    '#include <vector>',
    '#include <algorithm>',
    'using namespace std;',
    '',
    '// 阶段 3: 严格二维动态规划',
    'int maxHappy(const vector<int>& a, const vector<int>& b, const vector<int>& w, int budget) {',
    '    int happy = 0;',
    '    vector<int> cost, val;',
    '    for (size_t i = 0; i < a.size(); ++i) {',
    '        int well = a[i] - 2 * b[i];',
    '        if (well >= 0) { happy += w[i]; budget += well; }',
    '        else { cost.push_back(-well); val.push_back(w[i]); }',
    '    }',
    '    int n = cost.size();',
    '    vector<vector<int>> dp(n + 1, vector<int>(budget + 1, 0));',
    '    for (int i = 1; i <= n; ++i) { // @step:outerLoopI',
    '        int c = cost[i - 1], v = val[i - 1];',
    '        for (int j = 0; j <= budget; ++j) {',
    '            dp[i][j] = dp[i - 1][j]; // @step:inheritNoPick',
    '            if (j >= c) dp[i][j] = max(dp[i][j], dp[i - 1][j - c] + v); // @step:updatePick',
    '        }',
    '    }',
    '    return happy + dp[n][budget];',
    '}',
  ],
  python: [
    '# 阶段 3: 严格二维动态规划',
    'def max_happy(a: list[int], b: list[int], w: list[int], budget: int) -> int:',
    '    happy = 0',
    '    cost, val = [], []',
    '    for orig, disc, h in zip(a, b, w):',
    '        well = orig - 2 * disc',
    '        if well >= 0:',
    '            happy += h',
    '            budget += well',
    '        else:',
    '            cost.append(-well)',
    '            val.append(h)',
    '    n = len(cost)',
    '    dp = [[0] * (budget + 1) for _ in range(n + 1)] # @step:initDp',
    '    for i in range(1, n + 1): # @step:outerLoopI',
    '        c, v = cost[i - 1], val[i - 1]',
    '        for j in range(budget + 1):',
    '            dp[i][j] = dp[i - 1][j] # @step:inheritNoPick',
    '            if j >= c:',
    '                dp[i][j] = max(dp[i][j], dp[i - 1][j - c] + v) # @step:updatePick',
    '    return happy + dp[n][budget]',
  ],
  javascript: [
    '// 阶段 3: 严格二维动态规划',
    'export function maxHappy(a, b, w, budget) {',
    '  let happy = 0;',
    '  const cost = [], val = [];',
    '  for (let i = 0; i < a.length; i++) {',
    '    const well = a[i] - 2 * b[i];',
    '    if (well >= 0) { happy += w[i]; budget += well; }',
    '    else { cost.push(-well); val.push(w[i]); }',
    '  }',
    '  const n = cost.length;',
    '  const dp = Array.from({ length: n + 1 }, () => new Array(budget + 1).fill(0)); // @step:initDp',
    '  for (let i = 1; i <= n; i++) { // @step:outerLoopI',
    '    const c = cost[i - 1], v = val[i - 1];',
    '    for (let j = 0; j <= budget; j++) {',
    '      dp[i][j] = dp[i - 1][j]; // @step:inheritNoPick',
    '      if (j >= c) dp[i][j] = Math.max(dp[i][j], dp[i - 1][j - c] + v); // @step:updatePick',
    '    }',
    '  }',
    '  return happy + dp[n][budget];',
    '}',
  ],
};


