/**
 * 第 91 课：左神贪心算法专题 3 - 多语言源代码片段与 1-based 相对行号字典
 * 涵盖 Java, C++, Python, JavaScript
 */

// ==========================================
// 1. 最短无序连续子数组 (LeetCode 581)
// ==========================================
export const SHORTEST_UNSORTED_CODES: Record<string, string[]> = {
  java: [
    'public int findUnsortedSubarray(int[] nums) {',
    '    int n = nums.length;',
    '    int right = -1, max = Integer.MIN_VALUE;',
    '    for (int i = 0; i < n; i++) {',
    '        if (max > nums[i]) right = i;',
    '        else max = nums[i];',
    '    }',
    '    int left = n, min = Integer.MAX_VALUE;',
    '    for (int i = n - 1; i >= 0; i--) {',
    '        if (min < nums[i]) left = i;',
    '        else min = nums[i];',
    '    }',
    '    return right == -1 ? 0 : right - left + 1;',
    '}',
  ],
  cpp: [
    'int findUnsortedSubarray(vector<int>& nums) {',
    '    int n = nums.size();',
    '    int right = -1, maxVal = INT_MIN;',
    '    for (int i = 0; i < n; i++) {',
    '        if (maxVal > nums[i]) right = i;',
    '        else maxVal = nums[i];',
    '    }',
    '    int left = n, minVal = INT_MAX;',
    '    for (int i = n - 1; i >= 0; i--) {',
    '        if (minVal < nums[i]) left = i;',
    '        else minVal = nums[i];',
    '    }',
    '    return right == -1 ? 0 : right - left + 1;',
    '}',
  ],
  python: [
    'def findUnsortedSubarray(nums: List[int]) -> int:',
    '    n = len(nums)',
    '    right, max_val = -1, float("-inf")',
    '    for i in range(n):',
    '        if max_val > nums[i]: right = i',
    '        else: max_val = nums[i]',
    '    left, min_val = n, float("inf")',
    '    for i in range(n - 1, -1, -1):',
    '        if min_val < nums[i]: left = i',
    '        else: min_val = nums[i]',
    '    return 0 if right == -1 else right - left + 1',
  ],
  javascript: [
    'function findUnsortedSubarray(nums) {',
    '    const n = nums.length;',
    '    let right = -1, max = -Infinity;',
    '    for (let i = 0; i < n; i++) {',
    '        if (max > nums[i]) right = i;',
    '        else max = nums[i];',
    '    }',
    '    let left = n, min = Infinity;',
    '    for (let i = n - 1; i >= 0; i--) {',
    '        if (min < nums[i]) left = i;',
    '        else min = nums[i];',
    '    }',
    '    return right === -1 ? 0 : right - left + 1;',
    '}',
  ],
};

export const SHORTEST_UNSORTED_LINES = {
  entry:     { java: 1, cpp: 1, python: 1, javascript: 1 },
  initRight: { java: 3, cpp: 3, python: 3, javascript: 3 },
  scanRight: { java: 5, cpp: 5, python: 5, javascript: 5 },
  initLeft:  { java: 8, cpp: 8, python: 7, javascript: 8 },
  scanLeft:  { java: 10, cpp: 10, python: 9, javascript: 10 },
  done:      { java: 13, cpp: 13, python: 11, javascript: 13 },
};

// ==========================================
// 2. 最小区间 (LeetCode 632)
// ==========================================
export const SMALLEST_RANGE_CODES: Record<string, string[]> = {
  java: [
    'public int[] smallestRange(List<List<Integer>> nums) {',
    '    PriorityQueue<int[]> minHeap = new PriorityQueue<>((a, b) -> a[0] - b[0]);',
    '    int maxVal = Integer.MIN_VALUE;',
    '    for (int i = 0; i < nums.size(); i++) {',
    '        minHeap.offer(new int[]{nums.get(i).get(0), i, 0});',
    '        maxVal = Math.max(maxVal, nums.get(i).get(0));',
    '    }',
    '    int ansL = 0, ansR = Integer.MAX_VALUE;',
    '    while (minHeap.size() == nums.size()) {',
    '        int[] cur = minHeap.poll();',
    '        if (maxVal - cur[0] < ansR - ansL) {',
    '            ansL = cur[0]; ansR = maxVal;',
    '        }',
    '        if (cur[2] + 1 < nums.get(cur[1]).size()) {',
    '            int nextVal = nums.get(cur[1]).get(cur[2] + 1);',
    '            minHeap.offer(new int[]{nextVal, cur[1], cur[2] + 1});',
    '            maxVal = Math.max(maxVal, nextVal);',
    '        }',
    '    }',
    '    return new int[]{ansL, ansR};',
    '}',
  ],
  cpp: [
    'vector<int> smallestRange(vector<vector<int>>& nums) {',
    '    auto cmp = [](const vector<int>& a, const vector<int>& b){ return a[0] > b[0]; };',
    '    priority_queue<vector<int>, vector<vector<int>>, decltype(cmp)> minHeap(cmp);',
    '    int maxVal = INT_MIN;',
    '    for (int i = 0; i < nums.size(); i++) {',
    '        minHeap.push({nums[i][0], i, 0});',
    '        maxVal = max(maxVal, nums[i][0]);',
    '    }',
    '    int ansL = 0, ansR = INT_MAX;',
    '    while (minHeap.size() == nums.size()) {',
    '        auto cur = minHeap.top(); minHeap.pop();',
    '        if (maxVal - cur[0] < ansR - ansL) { ansL = cur[0]; ansR = maxVal; }',
    '        if (cur[2] + 1 < nums[cur[1]].size()) {',
    '            int nextVal = nums[cur[1]][cur[2] + 1];',
    '            minHeap.push({nextVal, cur[1], cur[2] + 1});',
    '            maxVal = max(maxVal, nextVal);',
    '        }',
    '    }',
    '    return {ansL, ansR};',
    '}',
  ],
  python: [
    'def smallestRange(nums: List[List[int]]) -> List[int]:',
    '    min_heap = []',
    '    max_val = float("-inf")',
    '    for i in range(len(nums)):',
    '        heapq.heappush(min_heap, (nums[i][0], i, 0))',
    '        max_val = max(max_val, nums[i][0])',
    '    ans_l, ans_r = 0, float("inf")',
    '    while len(min_heap) == len(nums):',
    '        v, i, j = heapq.heappop(min_heap)',
    '        if max_val - v < ans_r - ans_l:',
    '            ans_l, ans_r = v, max_val',
    '        if j + 1 < len(nums[i]):',
    '            next_v = nums[i][j + 1]',
    '            heapq.heappush(min_heap, (next_v, i, j + 1))',
    '            max_val = max(max_val, next_v)',
    '    return [ans_l, ans_r]',
  ],
  javascript: [
    'function smallestRange(nums) {',
    '    const heap = [];',
    '    let maxVal = -Infinity;',
    '    for (let i = 0; i < nums.length; i++) {',
    '        heap.push([nums[i][0], i, 0]);',
    '        maxVal = Math.max(maxVal, nums[i][0]);',
    '    }',
    '    let ansL = 0, ansR = Infinity;',
    '    while (heap.length === nums.length) {',
    '        heap.sort((a, b) => a[0] - b[0]);',
    '        const [v, i, j] = heap.shift();',
    '        if (maxVal - v < ansR - ansL) { ansL = v; ansR = maxVal; }',
    '        if (j + 1 < nums[i].length) {',
    '            const nextVal = nums[i][j + 1];',
    '            heap.push([nextVal, i, j + 1]);',
    '            maxVal = Math.max(maxVal, nextVal);',
    '        }',
    '    }',
    '    return [ansL, ansR];',
    '}',
  ],
};

export const SMALLEST_RANGE_LINES = {
  entry:     { java: 1, cpp: 1, python: 1, javascript: 1 },
  initHeap:  { java: 5, cpp: 6, python: 5, javascript: 5 },
  popMin:    { java: 10, cpp: 11, python: 9, javascript: 11 },
  checkAns:  { java: 11, cpp: 12, python: 10, javascript: 12 },
  pushNext:  { java: 16, cpp: 15, python: 14, javascript: 15 },
  done:      { java: 20, cpp: 19, python: 16, javascript: 19 },
};

// ==========================================
// 3. 组团买票问题 (Group Buy Tickets)
// ==========================================
export const GROUP_BUY_TICKETS_CODES: Record<string, string[]> = {
  java: [
    'public int enough(int n, int[][] games) {',
    '    PriorityQueue<int[]> maxHeap = new PriorityQueue<>((a, b) -> b[0] - a[0]);',
    '    for (int[] g : games) {',
    '        int delta1 = g[1] - g[0];',
    '        if (delta1 > 0) maxHeap.offer(new int[]{delta1, 0, g[0], g[1]});',
    '    }',
    '    int totalCost = 0;',
    '    for (int step = 0; step < n && !maxHeap.isEmpty(); step++) {',
    '        int[] cur = maxHeap.poll();',
    '        totalCost += cur[0];',
    '        int nextX = cur[1] + 1;',
    '        int nextDelta = cur[3] - cur[2] * (2 * nextX + 1);',
    '        if (nextDelta > 0) maxHeap.offer(new int[]{nextDelta, nextX, cur[2], cur[3]});',
    '    }',
    '    return totalCost;',
    '}',
  ],
  cpp: [
    'int enough(int n, vector<vector<int>>& games) {',
    '    priority_queue<vector<int>> maxHeap;',
    '    for (auto& g : games) {',
    '        int delta1 = g[1] - g[0];',
    '        if (delta1 > 0) maxHeap.push({delta1, 0, g[0], g[1]});',
    '    }',
    '    int totalCost = 0;',
    '    for (int step = 0; step < n && !maxHeap.empty(); step++) {',
    '        auto cur = maxHeap.top(); maxHeap.pop();',
    '        totalCost += cur[0];',
    '        int nextX = cur[1] + 1;',
    '        int nextDelta = cur[3] - cur[2] * (2 * nextX + 1);',
    '        if (nextDelta > 0) maxHeap.push({nextDelta, nextX, cur[2], cur[3]});',
    '    }',
    '    return totalCost;',
    '}',
  ],
  python: [
    'def enough(n: int, games: List[List[int]]) -> int:',
    '    max_heap = []',
    '    for k, b in games:',
    '        delta1 = b - k',
    '        if delta1 > 0: heapq.heappush(max_heap, (-delta1, 0, k, b))',
    '    total_cost = 0',
    '    for _ in range(n):',
    '        if not max_heap: break',
    '        neg_delta, x, k, b = heapq.heappop(max_heap)',
    '        total_cost += (-neg_delta)',
    '        next_x = x + 1',
    '        next_delta = b - k * (2 * next_x + 1)',
    '        if next_delta > 0: heapq.heappush(max_heap, (-next_delta, next_x, k, b))',
    '    return total_cost',
  ],
  javascript: [
    'function enough(n, games) {',
    '    const heap = [];',
    '    for (const [k, b] of games) {',
    '        const delta1 = b - k;',
    '        if (delta1 > 0) heap.push([delta1, 0, k, b]);',
    '    }',
    '    let totalCost = 0;',
    '    for (let step = 0; step < n && heap.length > 0; step++) {',
    '        heap.sort((a, b) => b[0] - a[0]);',
    '        const [delta, x, k, b] = heap.shift();',
    '        totalCost += delta;',
    '        const nextX = x + 1;',
    '        const nextDelta = b - k * (2 * nextX + 1);',
    '        if (nextDelta > 0) heap.push([nextDelta, nextX, k, b]);',
    '    }',
    '    return totalCost;',
    '}',
  ],
};

export const GROUP_BUY_TICKETS_LINES = {
  entry:     { java: 1, cpp: 1, python: 1, javascript: 1 },
  initHeap:  { java: 5, cpp: 5, python: 5, javascript: 5 },
  popDelta:  { java: 9, cpp: 9, python: 9, javascript: 9 },
  addCost:   { java: 10, cpp: 10, python: 10, javascript: 10 },
  pushNext:  { java: 13, cpp: 13, python: 13, javascript: 14 },
  done:      { java: 15, cpp: 15, python: 14, javascript: 16 },
};

// ==========================================
// 4. 平均值最小累加和 (Split Minimum Average Sum)
// ==========================================
export const SPLIT_MIN_AVG_SUM_CODES: Record<string, string[]> = {
  java: [
    'public int minAverageSum(int[] arr, int k) {',
    '    Arrays.sort(arr);',
    '    int ans = 0;',
    '    for (int i = 0; i < k - 1; i++) {',
    '        ans += arr[i];',
    '    }',
    '    long sum = 0;',
    '    for (int i = k - 1; i < arr.length; i++) {',
    '        sum += arr[i];',
    '    }',
    '    ans += (int)(sum / (arr.length - k + 1));',
    '    return ans;',
    '}',
  ],
  cpp: [
    'int minAverageSum(vector<int>& arr, int k) {',
    '    sort(arr.begin(), arr.end());',
    '    int ans = 0;',
    '    for (int i = 0; i < k - 1; i++) {',
    '        ans += arr[i];',
    '    }',
    '    long long sum = 0;',
    '    for (int i = k - 1; i < arr.size(); i++) {',
    '        sum += arr[i];',
    '    }',
    '    ans += (int)(sum / (arr.size() - k + 1));',
    '    return ans;',
    '}',
  ],
  python: [
    'def minAverageSum(arr: List[int], k: int) -> int:',
    '    arr.sort()',
    '    ans = sum(arr[:k - 1])',
    '    last_sum = sum(arr[k - 1:])',
    '    ans += last_sum // (len(arr) - k + 1)',
    '    return ans',
  ],
  javascript: [
    'function minAverageSum(arr, k) {',
    '    arr.sort((a, b) => a - b);',
    '    let ans = 0;',
    '    for (let i = 0; i < k - 1; i++) {',
    '        ans += arr[i];',
    '    }',
    '    let sum = 0;',
    '    for (let i = k - 1; i < arr.length; i++) {',
    '        sum += arr[i];',
    '    }',
    '    ans += Math.floor(sum / (arr.length - k + 1));',
    '    return ans;',
    '}',
  ],
};

export const SPLIT_MIN_AVG_SUM_LINES = {
  entry:     { java: 1, cpp: 1, python: 1, javascript: 1 },
  sortArr:   { java: 2, cpp: 2, python: 2, javascript: 2 },
  singleSets:{ java: 5, cpp: 5, python: 3, javascript: 5 },
  diluteSet: { java: 11, cpp: 11, python: 5, javascript: 11 },
  done:      { java: 12, cpp: 12, python: 6, javascript: 12 },
};

// ==========================================
// 5. 完成所有任务的最少初始能量 (LeetCode 1665)
// ==========================================
export const MINIMAL_BATTERY_POWER_CODES: Record<string, string[]> = {
  java: [
    'public int minimumEffort(int[][] tasks) {',
    '    Arrays.sort(tasks, (a, b) -> (b[1] - b[0]) - (a[1] - a[0]));',
    '    int ans = 0;',
    '    for (int[] task : tasks) {',
    '        ans = Math.max(ans + task[0], task[1]);',
    '    }',
    '    return ans;',
    '}',
  ],
  cpp: [
    'int minimumEffort(vector<vector<int>>& tasks) {',
    '    sort(tasks.begin(), tasks.end(), [](const vector<int>& a, const vector<int>& b) {',
    '        return (b[1] - b[0]) < (a[1] - a[0]);',
    '    });',
    '    int ans = 0;',
    '    for (const auto& task : tasks) {',
    '        ans = max(ans + task[0], task[1]);',
    '    }',
    '    return ans;',
    '}',
  ],
  python: [
    'def minimumEffort(tasks: List[List[int]]) -> int:',
    '    tasks.sort(key=lambda t: t[1] - t[0], reverse=True)',
    '    ans = 0',
    '    for actual, minimum in tasks:',
    '        ans = max(ans + actual, minimum)',
    '    return ans',
  ],
  javascript: [
    'function minimumEffort(tasks) {',
    '    tasks.sort((a, b) => (b[1] - b[0]) - (a[1] - a[0]));',
    '    let ans = 0;',
    '    for (const [actual, minimum] of tasks) {',
    '        ans = Math.max(ans + actual, minimum);',
    '    }',
    '    return ans;',
    '}',
  ],
};

export const MINIMAL_BATTERY_POWER_LINES = {
  entry:     { java: 1, cpp: 1, python: 1, javascript: 1 },
  sortTasks: { java: 2, cpp: 2, python: 2, javascript: 2 },
  process:   { java: 5, cpp: 7, python: 5, javascript: 5 },
  done:      { java: 7, cpp: 9, python: 6, javascript: 7 },
};

// ==========================================
// 6. 两个 0 和 1 数量相等区间的最大长度
// ==========================================
export const LONGEST_SAME_ZEROS_ONES_CODES: Record<string, string[]> = {
  java: [
    'public int maxEqualIntervalLength(int[] arr) {',
    '    int n = arr.length;',
    '    if (n <= 1) return 0;',
    '    if (n == 2) return arr[0] == arr[1] ? 1 : 0;',
    '    if (arr[0] == arr[n - 1]) {',
    '        return n - 1;',
    '    }',
    '    return n - 2;',
    '}',
  ],
  cpp: [
    'int maxEqualIntervalLength(vector<int>& arr) {',
    '    int n = arr.size();',
    '    if (n <= 1) return 0;',
    '    if (n == 2) return arr[0] == arr[1] ? 1 : 0;',
    '    if (arr[0] == arr[n - 1]) {',
    '        return n - 1;',
    '    }',
    '    return n - 2;',
    '}',
  ],
  python: [
    'def maxEqualIntervalLength(arr: List[int]) -> int:',
    '    n = len(arr)',
    '    if n <= 1: return 0',
    '    if n == 2: return 1 if arr[0] == arr[1] else 0',
    '    if arr[0] == arr[n - 1]:',
    '        return n - 1',
    '    return n - 2',
  ],
  javascript: [
    'function maxEqualIntervalLength(arr) {',
    '    const n = arr.length;',
    '    if (n <= 1) return 0;',
    '    if (n === 2) return arr[0] === arr[1] ? 1 : 0;',
    '    if (arr[0] === arr[n - 1]) {',
    '        return n - 1;',
    '    }',
    '    return n - 2;',
    '}',
  ],
};

export const LONGEST_SAME_ZEROS_ONES_LINES = {
  entry:     { java: 1, cpp: 1, python: 1, javascript: 1 },
  guardSmall:{ java: 3, cpp: 3, python: 3, javascript: 3 },
  checkEnds: { java: 5, cpp: 5, python: 5, javascript: 5 },
  returnNMinus1: { java: 6, cpp: 6, python: 6, javascript: 6 },
  returnNMinus2: { java: 8, cpp: 8, python: 7, javascript: 8 },
};
