/**
 * 动态点分治与点分树 (Dynamic Centroid Decomposition / Centroid Tree)
 * 进阶树论: 重心递归分治建树、树高严格 O(log n)、点分树向上跳跃维护距离 (洛谷 P6329 / SPOJ QTREE5)
 */

export const CENTROID_TREE_CODE_LANGUAGES: Record<string, string[]> = {
  cpp: [
    '#include <iostream>',
    '#include <vector>',
    '#include <algorithm>',
    'using namespace std;',
    '',
    '// 动态点分树 (洛谷 P6329 【模板】点分树 / 震波)',
    '// 核心：重心连边成树，点分树高度 <= log2(n)，向上跳祖先 O(log n) 统计距离',
    'class CentroidTree {',
    'public:',
    '    int n, rootCentroid = 0;',
    '    vector<vector<int>> origAdj, ctreeAdj;',
    '    vector<int> sz, maxSubtree, parentCTree;',
    '    vector<bool> vis;',
    '    ',
    '    CentroidTree(int n) : n(n), origAdj(n + 1), ctreeAdj(n + 1),',
    '                          sz(n + 1, 0), maxSubtree(n + 1, 0),',
    '                          parentCTree(n + 1, 0), vis(n + 1, false) {}',
    '    ',
    '    void addEdge(int u, int v) {',
    '        origAdj[u].push_back(v);',
    '        origAdj[v].push_back(u);',
    '    }',
    '    ',
    '    // 1. 获取子树大小与最大子树',
    '    void getSubtreeSize(int u, int fa, int totalNodes, int& centroid) {',
    '        sz[u] = 1;',
    '        maxSubtree[u] = 0;',
    '        for (int v : origAdj[u]) {',
    '            if (v == fa || vis[v]) continue;',
    '            getSubtreeSize(v, u, totalNodes, centroid);',
    '            sz[u] += sz[v];',
    '            maxSubtree[u] = max(maxSubtree[u], sz[v]);',
    '        }',
    '        maxSubtree[u] = max(maxSubtree[u], totalNodes - sz[u]);',
    '        if (centroid == 0 || maxSubtree[u] < maxSubtree[centroid]) {',
    '            centroid = u;',
    '        }',
    '    }',
    '    ',
    '    // 2. 递归构建点分树',
    '    int buildCentroidTree(int u, int totalNodes) {',
    '        int centroid = 0;',
    '        getSubtreeSize(u, 0, totalNodes, centroid);',
    '        vis[centroid] = true;',
    '        ',
    '        for (int v : origAdj[centroid]) {',
    '            if (vis[v]) continue;',
    '            // 计算子树的真实大小',
    '            int nextTotal = (sz[v] > sz[centroid]) ? (totalNodes - sz[centroid]) : sz[v];',
    '            int childCentroid = buildCentroidTree(v, nextTotal);',
    '            ctreeAdj[centroid].push_back(childCentroid);',
    '            parentCTree[childCentroid] = centroid;',
    '        }',
    '        return centroid;',
    '    }',
    '    ',
    '    void init() {',
    '        rootCentroid = buildCentroidTree(1, n);',
    '    }',
    '};',
  ],
  java: [
    'package advanced_tree;',
    '',
    'import java.util.*;',
    '',
    '/**',
    ' * 动态点分树标准实现 - 重心分治递归构建与 O(log n) 祖先跳跃',
    ' * 时间复杂度: 建树 O(N log N)，单次跳跃操作 O(log N)',
    ' * 空间复杂度: O(N)',
    ' */',
    'public class Code01_CentroidTree {',
    '    public static class CentroidTree {',
    '        public int n, rootCentroid;',
    '        public ArrayList<ArrayList<Integer>> origAdj, ctreeAdj;',
    '        public int[] sz, maxSubtree, parentCTree;',
    '        public boolean[] vis;',
    '        ',
    '        public CentroidTree(int n) {',
    '            this.n = n;',
    '            this.origAdj = new ArrayList<>();',
    '            this.ctreeAdj = new ArrayList<>();',
    '            for (int i = 0; i <= n; i++) {',
    '                origAdj.add(new ArrayList<>());',
    '                ctreeAdj.add(new ArrayList<>());',
    '            }',
    '            this.sz = new int[n + 1];',
    '            this.maxSubtree = new int[n + 1];',
    '            this.parentCTree = new int[n + 1];',
    '            this.vis = new boolean[n + 1];',
    '        }',
    '        ',
    '        public void addEdge(int u, int v) {',
    '            origAdj.get(u).add(v);',
    '            origAdj.get(v).add(u);',
    '        }',
    '        ',
    '        // 1. 获取子树大小并寻找重心 (最大子树尺寸最小的节点)',
    '        public void getSubtreeSize(int u, int fa, int totalNodes, int[] centroidRef) {',
    '            sz[u] = 1;',
    '            maxSubtree[u] = 0;',
    '            for (int v : origAdj.get(u)) {',
    '                if (v == fa || vis[v]) continue;',
    '                getSubtreeSize(v, u, totalNodes, centroidRef);',
    '                sz[u] += sz[v];',
    '                maxSubtree[u] = Math.max(maxSubtree[u], sz[v]);',
    '            }',
    '            maxSubtree[u] = Math.max(maxSubtree[u], totalNodes - sz[u]);',
    '            if (centroidRef[0] == 0 || maxSubtree[u] < maxSubtree[centroidRef[0]]) {',
    '                centroidRef[0] = u;',
    '            }',
    '        }',
    '        ',
    '        // 2. 递归构建点分树，返回当前子树重心',
    '        public int build(int u, int totalNodes) {',
    '            int[] centroidRef = new int[1];',
    '            getSubtreeSize(u, 0, totalNodes, centroidRef);',
    '            int c = centroidRef[0];',
    '            vis[c] = true;',
    '            ',
    '            for (int v : origAdj.get(c)) {',
    '                if (vis[v]) continue;',
    '                int nextTotal = (sz[v] > sz[c]) ? (totalNodes - sz[c]) : sz[v];',
    '                int childCentroid = build(v, nextTotal);',
    '                ctreeAdj.get(c).add(childCentroid);',
    '                parentCTree[childCentroid] = c;',
    '            }',
    '            return c;',
    '        }',
    '        ',
    '        public void init() {',
    '            rootCentroid = build(1, n);',
    '        }',
    '    }',
    '}',
  ],
  python: [
    '# 动态点分树 (Python 标准实现)',
    '# 核心原理: 重心分治 + 递归连边形成树高严格 O(log N) 的重构树',
    '# 时间复杂度: 建树 O(N log N)，空间复杂度: O(N)',
    'import sys',
    'sys.setrecursionlimit(200000)',
    '',
    'class CentroidTree:',
    '    def __init__(self, n: int):',
    '        self.n = n',
    '        self.root_centroid = 0',
    '        self.orig_adj = [[] for _ in range(n + 1)]',
    '        self.ctree_adj = [[] for _ in range(n + 1)]',
    '        self.sz = [0] * (n + 1)',
    '        self.max_subtree = [0] * (n + 1)',
    '        self.parent_ctree = [0] * (n + 1)',
    '        self.vis = [False] * (n + 1)',
    '        ',
    '    def add_edge(self, u: int, v: int):',
    '        self.orig_adj[u].append(v)',
    '        self.orig_adj[v].append(u)',
    '        ',
    '    def get_subtree_size(self, u: int, fa: int, total: int, centroid_ref: list[int]):',
    '        self.sz[u] = 1',
    '        self.max_subtree[u] = 0',
    '        for v in self.orig_adj[u]:',
    '            if v == fa or self.vis[v]:',
    '                continue',
    '            self.get_subtree_size(v, u, total, centroid_ref)',
    '            self.sz[u] += self.sz[v]',
    '            self.max_subtree[u] = max(self.max_subtree[u], self.sz[v])',
    '        self.max_subtree[u] = max(self.max_subtree[u], total - self.sz[u])',
    '        if centroid_ref[0] == 0 or self.max_subtree[u] < self.max_subtree[centroid_ref[0]]:',
    '            centroid_ref[0] = u',
    '            ',
    '    def build(self, u: int, total: int) -> int:',
    '        centroid_ref = [0]',
    '        self.get_subtree_size(u, 0, total, centroid_ref)',
    '        c = centroid_ref[0]',
    '        self.vis[c] = True',
    '        ',
    '        for v in self.orig_adj[c]:',
    '            if self.vis[v]:',
    '                continue',
    '            next_total = (total - self.sz[c]) if self.sz[v] > self.sz[c] else self.sz[v]',
    '            child = self.build(v, next_total)',
    '            self.ctree_adj[c].append(child)',
    '            self.parent_ctree[child] = c',
    '        return c',
    '        ',
    '    def init(self):',
    '        self.root_centroid = self.build(1, self.n)',
  ],
  javascript: [
    '/**',
    ' * 动态点分树 (JavaScript 版)',
    ' * 递归提取树的重心重构点分树，保证树高严格 O(log N)',
    ' */',
    'class CentroidTree {',
    '  constructor(n) {',
    '    this.n = n;',
    '    this.rootCentroid = 0;',
    '    this.origAdj = Array.from({ length: n + 1 }, () => []);',
    '    this.ctreeAdj = Array.from({ length: n + 1 }, () => []);',
    '    this.sz = Array(n + 1).fill(0);',
    '    this.maxSubtree = Array(n + 1).fill(0);',
    '    this.parentCTree = Array(n + 1).fill(0);',
    '    this.vis = Array(n + 1).fill(false);',
    '  }',
    '  ',
    '  addEdge(u, v) {',
    '    this.origAdj[u].push(v);',
    '    this.origAdj[v].push(u);',
    '  }',
    '  ',
    '  getSubtreeSize(u, fa, total, centroidRef) {',
    '    this.sz[u] = 1;',
    '    this.maxSubtree[u] = 0;',
    '    for (const v of this.origAdj[u]) {',
    '      if (v === fa || this.vis[v]) continue;',
    '      this.getSubtreeSize(v, u, total, centroidRef);',
    '      this.sz[u] += this.sz[v];',
    '      this.maxSubtree[u] = Math.max(this.maxSubtree[u], this.sz[v]);',
    '    }',
    '    this.maxSubtree[u] = Math.max(this.maxSubtree[u], total - this.sz[u]);',
    '    if (centroidRef[0] === 0 || this.maxSubtree[u] < this.maxSubtree[centroidRef[0]]) {',
    '      centroidRef[0] = u;',
    '    }',
    '  }',
    '  ',
    '  build(u, total) {',
    '    const centroidRef = [0];',
    '    this.getSubtreeSize(u, 0, total, centroidRef);',
    '    const c = centroidRef[0];',
    '    this.vis[c] = true;',
    '    ',
    '    for (const v of this.origAdj[c]) {',
    '      if (this.vis[v]) continue;',
    '      const nextTotal = this.sz[v] > this.sz[c] ? total - this.sz[c] : this.sz[v];',
    '      const child = this.build(v, nextTotal);',
    '      this.ctreeAdj[c].push(child);',
    '      this.parentCTree[child] = c;',
    '    }',
    '    return c;',
    '  }',
    '  ',
    '  init() {',
    '    this.rootCentroid = this.build(1, this.n);',
    '  }',
    '}',
  ],
};

export const CENTROID_TREE_PROBLEM_HTML = `
  <div style="font-size: 13px; line-height: 1.6; color: #334155;">
    <h3 style="margin-top: 0; color: #0f172a; font-size: 15px; font-weight: 800;">🌲 动态点分树 (Centroid Tree)</h3>
    <p>
      将树上重心点分治的递归过程保存下来：每层子树的重心连向下一层子树的重心，构建出的一棵全新树结构称为<b>点分树</b>（洛谷 P6329 【模板】点分树 / SPOJ QTREE5）。
    </p>

    <div style="background: #f8fafc; border-left: 4px solid #3b82f6; padding: 8px 12px; margin: 10px 0; border-radius: 0 6px 6px 0;">
      <div style="font-weight: 700; color: #1e40af; margin-bottom: 4px;">👑 核心高度上界定理</div>
      <div style="font-size: 11.5px; color: #334155;">
        无论原树形态如何严重退化（即使是单链 $O(n)$ 深度），<b>点分树的树高严格不超过 $\\lfloor \\log_2 n \\rfloor + 1$</b>！
      </div>
    </div>
  </div>
`;

export const CENTROID_TREE_ANALYSIS_HTML = `
  <div style="font-size: 13px; line-height: 1.6; color: #334155;">
    <h3 style="margin-top: 0; color: #0f172a; font-size: 15px; font-weight: 800;">💡 点分树如何支持动态修改与路径统计？</h3>

    <div style="background: #eff6ff; border: 1px solid #bfdbfe; border-radius: 6px; padding: 10px; margin-bottom: 12px;">
      <div style="font-weight: 700; color: #1e3a8a; margin-bottom: 4px;">1. 祖先路径全覆盖性质</div>
      <div style="font-size: 12px; color: #1e40af;">
        原树中任意两点 $u, v$ 的路径，必然恰好在点分树上它们的最近公共祖先 $\\text{LCA}_{\\text{CTree}}(u, v)$ 处被拆解和统计！
      </div>
    </div>

    <div style="background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 6px; padding: 10px;">
      <div style="font-weight: 700; color: #166534; margin-bottom: 4px;">2. O(log n) 向上跳跃修改</div>
      <div style="font-size: 12px; color: #15803d;">
        单点点权修改或距离询问时，只需沿着点分树父指针向上跳 $O(\\log n)$ 层，更新/查询祖先节点挂载的动态开点线段树，单次操作复杂度为 $O(\\log^2 n)$！
      </div>
    </div>
  </div>
`;
