/**
 * 弦图判定与最大势算法 MCS (Chordal Graph & MCS)
 * 进阶图论: 完美消除序列 (PEO)、最大势算法 (Maximum Cardinality Search - O(V+E))、极大团计数 (Maximal Clique)
 */

export const CHORDAL_GRAPH_CODE_LANGUAGES: Record<string, string[]> = {
  cpp: [
    '#include <iostream>',
    '#include <vector>',
    '#include <algorithm>',
    'using namespace std;',
    '',
    '// 弦图判定与极大团计数 - 最大势算法 MCS (O(V + E))',
    '// 定理：无向图 G 是弦图 <=> G 存在完美消除序列 (PEO)',
    'class ChordalGraph {',
    'public:',
    '    int n;',
    '    vector<vector<int>> adj;',
    '    vector<int> label, peo, rankOrder;',
    '    ',
    '    ChordalGraph(int n) : n(n), adj(n + 1), label(n + 1, 0),',
    '                          peo(n + 1, 0), rankOrder(n + 1, 0) {}',
    '    ',
    '    void addEdge(int u, int v) {',
    '        adj[u].push_back(v);',
    '        adj[v].push_back(u);',
    '    }',
    '    ',
    '    // 1. MCS 最大势搜索构造 PEO 候选序列',
    '    void mcs() {',
    '        vector<bool> vis(n + 1, false);',
    '        for (int i = n; i >= 1; --i) {',
    '            int maxNode = 0, maxLabel = -1;',
    '            for (int u = 1; u <= n; ++u) {',
    '                if (!vis[u] && label[u] > maxLabel) {',
    '                    maxLabel = label[u];',
    '                    maxNode = u;',
    '                }',
    '            }',
    '            peo[i] = maxNode;',
    '            rankOrder[maxNode] = i;',
    '            vis[maxNode] = true;',
    '            for (int v : adj[maxNode]) {',
    '                if (!vis[v]) label[v]++;',
    '            }',
    '        }',
    '    }',
    '    ',
    '    // 2. 验证 PEO 是否为完美消除序列',
    '    bool verifyPEO() {',
    '        vector<vector<bool>> hasEdge(n + 1, vector<bool>(n + 1, false));',
    '        for (int u = 1; u <= n; ++u) {',
    '            for (int v : adj[u]) hasEdge[u][v] = true;',
    '        }',
    '        for (int i = 1; i <= n; ++i) {',
    '            int u = peo[i];',
    '            int firstNext = 0, minRank = n + 2;',
    '            vector<int> higher;',
    '            for (int v : adj[u]) {',
    '                if (rankOrder[v] > rankOrder[u]) {',
    '                    higher.push_back(v);',
    '                    if (rankOrder[v] < minRank) {',
    '                        minRank = rankOrder[v];',
    '                        firstNext = v;',
    '                    }',
    '                }',
    '            }',
    '            for (int v : higher) {',
    '                if (v != firstNext && !hasEdge[firstNext][v]) return false;',
    '            }',
    '        }',
    '        return true;',
    '    }',
    '    ',
    '    bool isChordal() {',
    '        mcs();',
    '        return verifyPEO();',
    '    }',
    '};',
  ],
  java: [
    'package advanced_graph;',
    '',
    'import java.util.*;',
    '',
    '// 弦图判定与极大团计数 - 最大势算法 MCS (O(V + E))',
    '// 定理：无向图 G 是弦图 <=> G 存在完美消除序列 (PEO)',
    '// 1. MCS 从后往前贪心构造候选 PEO',
    '// 2. 检验每个点的后继邻居在最早邻居处是否形成团',
    'public class Code02_ChordalGraphMCS {',
    '',
    '    public static int n;',
    '    public static ArrayList<ArrayList<Integer>> adj;',
    '    public static int[] peo;       // peo[1..n]',
    '    public static int[] rankOrder; // rankOrder[u] = 位置 1..n',
    '    public static int[] label;     // label[u] = 已标号邻居数',
    '    public static boolean[] vis;',
    '',
    '    public static void init(int numNodes) {',
    '        n = numNodes;',
    '        adj = new ArrayList<>();',
    '        for (int i = 0; i <= n; i++) adj.add(new ArrayList<>());',
    '        peo = new int[n + 1];',
    '        rankOrder = new int[n + 1];',
    '        label = new int[n + 1];',
    '        vis = new boolean[n + 1];',
    '    }',
    '',
    '    public static void addEdge(int u, int v) {',
    '        adj.get(u).add(v);',
    '        adj.get(v).add(u);',
    '    }',
    '',
    '    // 1. MCS 最大势搜索逆序生成 PEO 候选序列',
    '    public static void mcs() {',
    '        Arrays.fill(label, 0);',
    '        Arrays.fill(vis, false);',
    '',
    '        for (int i = n; i >= 1; i--) {',
    '            int maxNode = 0;',
    '            int maxLabel = -1;',
    '            for (int u = 1; u <= n; u++) {',
    '                if (!vis[u] && label[u] > maxLabel) {',
    '                    maxLabel = label[u];',
    '                    maxNode = u;',
    '                }',
    '            }',
    '            peo[i] = maxNode;',
    '            rankOrder[maxNode] = i;',
    '            vis[maxNode] = true;',
    '',
    '            for (int v : adj.get(maxNode)) {',
    '                if (!vis[v]) {',
    '                    label[v]++;',
    '                }',
    '            }',
    '        }',
    '    }',
    '',
    '    // 2. 验证 PEO 是否为完美消除序列',
    '    public static boolean verifyPEO() {',
    '        boolean[][] hasEdge = new boolean[n + 1][n + 1];',
    '        for (int u = 1; u <= n; u++) {',
    '            for (int v : adj.get(u)) {',
    '                hasEdge[u][v] = true;',
    '            }',
    '        }',
    '',
    '        for (int i = 1; i <= n; i++) {',
    '            int u = peo[i];',
    '            int firstNext = 0;',
    '            int minRank = n + 2;',
    '            List<Integer> higherNeighbors = new ArrayList<>();',
    '',
    '            for (int v : adj.get(u)) {',
    '                if (rankOrder[v] > rankOrder[u]) {',
    '                    higherNeighbors.add(v);',
    '                    if (rankOrder[v] < minRank) {',
    '                        minRank = rankOrder[v];',
    '                        firstNext = v;',
    '                    }',
    '                }',
    '            }',
    '',
    '            for (int v : higherNeighbors) {',
    '                if (v != firstNext && !hasEdge[firstNext][v]) {',
    '                    return false;',
    '                }',
    '            }',
    '        }',
    '        return true;',
    '    }',
    '',
    '    // 完整判断入口',
    '    public static boolean isChordal(int numNodes, int[][] edges) {',
    '        init(numNodes);',
    '        for (int[] e : edges) {',
    '            addEdge(e[0], e[1]);',
    '        }',
    '        mcs();',
    '        return verifyPEO();',
    '    }',
    '}',
  ],
  python: [
    '# 弦图判定与 MCS 算法 (Python 完整版)',
    'def is_chordal_graph(n: int, edges: list[tuple[int, int]]) -> tuple[bool, list[int]]:',
    '    adj = [[] for _ in range(n + 1)]',
    '    has_edge = [[False] * (n + 1) for _ in range(n + 1)]',
    '    for u, v in edges:',
    '        adj[u].append(v)',
    '        adj[v].append(u)',
    '        has_edge[u][v] = has_edge[v][u] = True',
    '    ',
    '    # 1. MCS 最大势搜索',
    '    label = [0] * (n + 1)',
    '    vis = [False] * (n + 1)',
    '    peo = [0] * (n + 1)',
    '    rank_order = [0] * (n + 1)',
    '    ',
    '    for i in range(n, 0, -1):',
    '        max_node = 0',
    '        max_label = -1',
    '        for u in range(1, n + 1):',
    '            if not vis[u] and label[u] > max_label:',
    '                max_label = label[u]',
    '                max_node = u',
    '        peo[i] = max_node',
    '        rank_order[max_node] = i',
    '        vis[max_node] = True',
    '        for v in adj[max_node]:',
    '            if not vis[v]:',
    '                label[v] += 1',
    '    ',
    '    # 2. 验证 PEO 完美消除序列',
    '    for i in range(1, n + 1):',
    '        u = peo[i]',
    '        first_next = 0',
    '        min_rank = n + 2',
    '        higher = []',
    '        for v in adj[u]:',
    '            if rank_order[v] > rank_order[u]:',
    '                higher.append(v)',
    '                if rank_order[v] < min_rank:',
    '                    min_rank = rank_order[v]',
    '                    first_next = v',
    '        for v in higher:',
    '            if v != first_next and not has_edge[first_next][v]:',
    '                return False, peo[1:]',
    '    ',
    '    return True, peo[1:]',
  ],
  javascript: [
    '// 弦图判定与 MCS 最大势搜索 (JavaScript 完整版)',
    'function isChordalGraph(n, edges) {',
    '  const adj = Array.from({ length: n + 1 }, () => []);',
    '  const hasEdge = Array.from({ length: n + 1 }, () => new Array(n + 1).fill(false));',
    '  for (const [u, v] of edges) {',
    '    adj[u].push(v);',
    '    adj[v].push(u);',
    '    hasEdge[u][v] = hasEdge[v][u] = true;',
    '  }',
    '  ',
    '  // 1. MCS 最大势搜索逆序生成 PEO 候选',
    '  const label = new Array(n + 1).fill(0);',
    '  const vis = new Array(n + 1).fill(false);',
    '  const peo = new Array(n + 1).fill(0);',
    '  const rankOrder = new Array(n + 1).fill(0);',
    '  ',
    '  for (let i = n; i >= 1; i--) {',
    '    let maxNode = 0;',
    '    let maxLabel = -1;',
    '    for (let u = 1; u <= n; u++) {',
    '      if (!vis[u] && label[u] > maxLabel) {',
    '        maxLabel = label[u];',
    '        maxNode = u;',
    '      }',
    '    }',
    '    peo[i] = maxNode;',
    '    rankOrder[maxNode] = i;',
    '    vis[maxNode] = true;',
    '    for (const v of adj[maxNode]) {',
    '      if (!vis[v]) label[v]++;',
    '    }',
    '  }',
    '  ',
    '  // 2. 验证 PEO 完美消除序列',
    '  for (let i = 1; i <= n; i++) {',
    '    const u = peo[i];',
    '    let firstNext = 0;',
    '    let minRank = n + 2;',
    '    const higher = [];',
    '    for (const v of adj[u]) {',
    '      if (rankOrder[v] > rankOrder[u]) {',
    '        higher.push(v);',
    '        if (rankOrder[v] < minRank) {',
    '          minRank = rankOrder[v];',
    '          firstNext = v;',
    '        }',
    '      }',
    '    }',
    '    for (const v of higher) {',
    '      if (v !== firstNext && !hasEdge[firstNext][v]) {',
    '        return { isChordal: false, peo: peo.slice(1) };',
    '      }',
    '    }',
    '  }',
    '  return { isChordal: true, peo: peo.slice(1) };',
    '}',
  ],
};

export const CHORDAL_GRAPH_PROBLEM_HTML = `
  <div style="font-size: 13px; line-height: 1.6; color: #334155;">
    <h3 style="margin-top: 0; color: #0f172a; font-size: 15px; font-weight: 800;">🎻 弦图判定与最大势算法 (Chordal Graph - MCS)</h3>
    <p>
      无向图中如果任意长度 $\\ge 4$ 的环都至少包含一条连接非相邻顶点的“弦”（Chord），则称该图为<b>弦图</b>。弦图判定与极大团计数在区间图调度、编译寄存器分配中具有关键应用。
    </p>

    <div style="background: #f8fafc; border-left: 4px solid #3b82f6; padding: 8px 12px; margin: 10px 0; border-radius: 0 6px 6px 0;">
      <div style="font-weight: 700; color: #1e40af; margin-bottom: 4px;">👑 完美消除序列 (PEO) 与 MCS 算法</div>
      <div style="font-size: 11.5px; color: #334155;">
        1. <b>判定定理</b>：无向图 $G$ 是弦图 $\\iff G$ 存在完美消除序列 (PEO)；<br/>
        2. <b>MCS 最大势搜索</b>：维护每个未访问节点的“势”（与已访问邻居数），贪心倒序选取势最大的点，以严格 $O(V + E)$ 线性构造候选 PEO！<br/>
        3. <b>极大团上界</b>：弦图的极大团总数不超过 $V$ 个，多项式时间内可全部求出！
      </div>
    </div>
  </div>
`;

export const CHORDAL_GRAPH_ANALYSIS_HTML = `
  <div style="font-size: 13px; line-height: 1.6; color: #334155;">
    <h3 style="margin-top: 0; color: #0f172a; font-size: 15px; font-weight: 800;">💡 弦图上的经典 NP-Hard 问题多项式解法</h3>

    <div style="background: #eff6ff; border: 1px solid #bfdbfe; border-radius: 6px; padding: 10px; margin-bottom: 12px;">
      <div style="font-weight: 700; color: #1e3a8a; margin-bottom: 4px;">1. 最大独立集与最小染色</div>
      <div style="font-size: 12px; color: #1e40af;">
        在一般图上，最大团、最大独立集与最小染色数均为 NP-Hard；但在弦图上，顺着 PEO 序列直接贪心，即可在 $O(V + E)$ 内精确求解！
      </div>
    </div>

    <div style="background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 6px; padding: 10px;">
      <div style="font-weight: 700; color: #166534; margin-bottom: 4px;">2. 团树 (Clique Tree) 树分解</div>
      <div style="font-size: 12px; color: #15803d;">
        弦图的极大团可组织成一棵团树，具有树宽 (Treewidth) 结构性质，是图论树形动态规划的核心基石！
      </div>
    </div>
  </div>
`;
