/**
 * 反向索引堆优化 Dijkstra (Dijkstra with Index Min-Heap)
 * 参考左程云《算法通关课》【必备篇】class061: 原地 decreaseKey、反向索引映射 where[] 与堆空间常数优化 (洛谷 P4779)
 */

export const DIJKSTRA_INDEX_HEAP_CODE_LANGUAGES: Record<string, string[]> = {
  cpp: [
    '#include <iostream>',
    '#include <vector>',
    '#include <algorithm>',
    'using namespace std;',
    '',
    '// 反向索引堆优化的 Dijkstra (洛谷 P4779 / 左程云 class061)',
    '// 核心：where[i] 记录节点 i 在堆中的实时位置，支持 O(log V) 原地 decreaseKey',
    'class IndexMinHeap {',
    'public:',
    '    vector<int> heap, where, dist;',
    '    int size;',
    '    ',
    '    IndexMinHeap(int n) : heap(n + 1), where(n + 1, -1), dist(n + 1, 1e9), size(0) {}',
    '    ',
    '    bool isEmpty() const { return size == 0; }',
    '    ',
    '    void swapNode(int i, int j) {',
    '        where[heap[i]] = j;',
    '        where[heap[j]] = i;',
    '        swap(heap[i], heap[j]);',
    '    }',
    '    ',
    '    void heapInsert(int i) {',
    '        while (dist[heap[i]] < dist[heap[(i - 1) / 2]]) {',
    '            swapNode(i, (i - 1) / 2);',
    '            i = (i - 1) / 2;',
    '        }',
    '    }',
    '    ',
    '    void heapify(int i) {',
    '        int l = i * 2 + 1;',
    '        while (l < size) {',
    '            int best = (l + 1 < size && dist[heap[l + 1]] < dist[heap[l]]) ? l + 1 : l;',
    '            best = dist[heap[best]] < dist[heap[i]] ? best : i;',
    '            if (best == i) break;',
    '            swapNode(best, i);',
    '            i = best;',
    '            l = i * 2 + 1;',
    '        }',
    '    }',
    '    ',
    '    void addOrUpdateOrIgnore(int u, int d) {',
    '        if (where[u] == -1) { // 首次入堆',
    '            heap[size] = u;',
    '            where[u] = size;',
    '            dist[u] = d;',
    '            heapInsert(size++);',
    '        } else if (where[u] >= 0) { // 在堆中，松弛更新',
    '            if (d < dist[u]) {',
    '                dist[u] = d;',
    '                heapInsert(where[u]);',
    '            }',
    '        }',
    '    }',
    '    ',
    '    int pop() {',
    '        int ans = heap[0];',
    '        swapNode(0, --size);',
    '        heapify(0);',
    '        where[ans] = -2; // 标记已弹出锁定',
    '        return ans;',
    '    }',
    '};',
  ],
  java: [
    'package class061;',
    '',
    'import java.util.*;',
    '',
    '// 反向索引堆优化的 Dijkstra - 左程云标准模板',
    'public class Code01_DijkstraLuogu {',
    '    public static class Heap {',
    '        public int[] heap, where, distance;',
    '        public int size;',
    '        ',
    '        public Heap(int n) {',
    '            heap = new int[n + 1];',
    '            where = new int[n + 1];',
    '            Arrays.fill(where, -1);',
    '            distance = new int[n + 1];',
    '            size = 0;',
    '        }',
    '        ',
    '        public boolean isEmpty() { return size == 0; }',
    '        ',
    '        public void swap(int i, int j) {',
    '            where[heap[i]] = j;',
    '            where[heap[j]] = i;',
    '            int tmp = heap[i];',
    '            heap[i] = heap[j];',
    '            heap[j] = tmp;',
    '        }',
    '        ',
    '        public void heapInsert(int i) {',
    '            while (distance[heap[i]] < distance[heap[(i - 1) / 2]]) {',
    '                swap(i, (i - 1) / 2);',
    '                i = (i - 1) / 2;',
    '            }',
    '        }',
    '        ',
    '        public void heapify(int i) {',
    '            int l = i * 2 + 1;',
    '            while (l < size) {',
    '                int best = (l + 1 < size && distance[heap[l + 1]] < distance[heap[l]]) ? l + 1 : l;',
    '                best = distance[heap[best]] < distance[heap[i]] ? best : i;',
    '                if (best == i) break;',
    '                swap(best, i);',
    '                i = best;',
    '                l = i * 2 + 1;',
    '            }',
    '        }',
    '        ',
    '        public void addOrUpdateOrIgnore(int u, int d) {',
    '            if (where[u] == -1) {',
    '                heap[size] = u;',
    '                where[u] = size;',
    '                distance[u] = d;',
    '                heapInsert(size++);',
    '            } else if (where[u] >= 0) {',
    '                if (d < distance[u]) {',
    '                    distance[u] = d;',
    '                    heapInsert(where[u]);',
    '                }',
    '            }',
    '        }',
    '        ',
    '        public int pop() {',
    '            int ans = heap[0];',
    '            swap(0, --size);',
    '            heapify(0);',
    '            where[ans] = -2;',
    '            return ans;',
    '        }',
    '    }',
    '}',
  ],
  python: [
    'class IndexMinHeap:',
    '    def __init__(self, n: int):',
    '        self.heap = [0] * (n + 1)',
    '        self.where = [-1] * (n + 1)',
    '        self.dist = [float("inf")] * (n + 1)',
    '        self.size = 0',
    '        ',
    '    def is_empty(self):',
    '        return self.size == 0',
    '        ',
    '    def swap(self, i, j):',
    '        self.where[self.heap[i]] = j',
    '        self.where[self.heap[j]] = i',
    '        self.heap[i], self.heap[j] = self.heap[j], self.heap[i]',
    '        ',
    '    def heap_insert(self, i):',
    '        while self.dist[self.heap[i]] < self.dist[self.heap[(i - 1) // 2]]:',
    '            self.swap(i, (i - 1) // 2)',
    '            i = (i - 1) // 2',
    '            ',
    '    def heapify(self, i):',
    '        l = i * 2 + 1',
    '        while l < self.size:',
    '            best = l + 1 if l + 1 < self.size and self.dist[self.heap[l + 1]] < self.dist[self.heap[l]] else l',
    '            best = best if self.dist[self.heap[best]] < self.dist[self.heap[i]] else i',
    '            if best == i: break',
    '            self.swap(best, i)',
    '            i = best',
    '            l = i * 2 + 1',
    '            ',
    '    def add_or_update(self, u, d):',
    '        if self.where[u] == -1:',
    '            self.heap[self.size] = u',
    '            self.where[u] = self.size',
    '            self.dist[u] = d',
    '            self.heap_insert(self.size)',
    '            self.size += 1',
    '        elif self.where[u] >= 0:',
    '            if d < self.dist[u]:',
    '                self.dist[u] = d',
    '                self.heap_insert(self.where[u])',
    '                ',
    '    def pop(self):',
    '        ans = self.heap[0]',
    '        self.size -= 1',
    '        self.swap(0, self.size)',
    '        self.heapify(0)',
    '        self.where[ans] = -2',
    '        return ans',
  ],
  javascript: [
    '// 反向索引堆优化 Dijkstra (JavaScript 版)',
    'class IndexMinHeap {',
    '  constructor(n) {',
    '    this.heap = Array(n + 1).fill(0);',
    '    this.where = Array(n + 1).fill(-1);',
    '    this.dist = Array(n + 1).fill(Infinity);',
    '    this.size = 0;',
    '  }',
    '  ',
    '  isEmpty() { return this.size === 0; }',
    '  ',
    '  swap(i, j) {',
    '    this.where[this.heap[i]] = j;',
    '    this.where[this.heap[j]] = i;',
    '    const tmp = this.heap[i];',
    '    this.heap[i] = this.heap[j];',
    '    this.heap[j] = tmp;',
    '  }',
    '  ',
    '  heapInsert(i) {',
    '    while (this.dist[this.heap[i]] < this.dist[this.heap[Math.floor((i - 1) / 2)]]) {',
    '      const p = Math.floor((i - 1) / 2);',
    '      this.swap(i, p);',
    '      i = p;',
    '    }',
    '  }',
    '  ',
    '  heapify(i) {',
    '    let l = i * 2 + 1;',
    '    while (l < this.size) {',
    '      let best = (l + 1 < this.size && this.dist[this.heap[l + 1]] < this.dist[this.heap[l]]) ? l + 1 : l;',
    '      best = this.dist[this.heap[best]] < this.dist[this.heap[i]] ? best : i;',
    '      if (best === i) break;',
    '      this.swap(best, i);',
    '      i = best;',
    '      l = i * 2 + 1;',
    '    }',
    '  }',
    '  ',
    '  addOrUpdate(u, d) {',
    '    if (this.where[u] === -1) {',
    '      this.heap[this.size] = u;',
    '      this.where[u] = this.size;',
    '      this.dist[u] = d;',
    '      this.heapInsert(this.size++);',
    '    } else if (this.where[u] >= 0) {',
    '      if (d < this.dist[u]) {',
    '        this.dist[u] = d;',
    '        this.heapInsert(this.where[u]);',
    '      }',
    '    }',
    '  }',
    '  ',
    '  pop() {',
    '    const ans = this.heap[0];',
    '    this.swap(0, --this.size);',
    '    this.heapify(0);',
    '    this.where[ans] = -2;',
    '    return ans;',
    '  }',
    '}',
  ],
};

export const DIJKSTRA_INDEX_HEAP_PROBLEM_HTML = `
  <div style="font-size: 13px; line-height: 1.6; color: #334155;">
    <h3 style="margin-top: 0; color: #0f172a; font-size: 15px; font-weight: 800;">⚡ 反向索引堆优化 Dijkstra (洛谷 P4779)</h3>
    <p>
      标准优先队列 Dijkstra 在松弛出更短路径时，由于无法修改队列中已有的元素，只能重复压入 <code>(node, newDist)</code> 元组，
      导致堆内存在大量无效的冗余记录，空间占用膨胀到 $O(E)$，常数巨大。
    </p>
    <p>
      <b>反向索引小根堆 (Index Min-Heap)</b> 通过维护 <code>where[u]</code> 记录节点在堆中的实时下标：
    </p>
    <ul>
      <li><code>where[u] == -1</code>：从未入堆（首次加入，<code>heapInsert</code> 上浮）</li>
      <li><code>where[u] &ge; 0</code>：已在堆中（距离变短时<b>原地 $O(\log V)$ 上浮修改</b>，无需插入新记录）</li>
      <li><code>where[u] == -2</code>：已从堆中弹出并锁定最短路（直接忽略，无需额外 <code>visited</code> 数组）</li>
    </ul>

    <div style="background: #f8fafc; border-left: 4px solid #3b82f6; padding: 8px 12px; margin: 10px 0; border-radius: 0 6px 6px 0;">
      <div style="font-weight: 700; color: #1e40af; margin-bottom: 4px;">🚀 极限性能优势</div>
      <div style="font-size: 11.5px; color: #334155;">
        堆内元素总数恒定 $\le V$，空间复杂度严格 $O(V)$，彻底消除冗余节点出队，是打比赛与高并发路由系统的终极武器！
      </div>
    </div>
  </div>
`;

export const DIJKSTRA_INDEX_HEAP_ANALYSIS_HTML = `
  <div style="font-size: 13px; line-height: 1.6; color: #334155;">
    <h3 style="margin-top: 0; color: #0f172a; font-size: 15px; font-weight: 800;">💡 左程云反向索引堆状态机与 swap 双向同步解析</h3>

    <div style="background: #eff6ff; border: 1px solid #bfdbfe; border-radius: 6px; padding: 10px; margin-bottom: 12px;">
      <div style="font-weight: 700; color: #1e3a8a; margin-bottom: 4px;">1. 双向映射 swapNode</div>
      <div style="font-size: 12px; color: #1e40af;">
        在堆调整时，交换 <code>heap[i]</code> 与 <code>heap[j]</code> 的同时必须立即同步更新 <code>where[heap[i]] = j</code> 与 <code>where[heap[j]] = i</code>！
        确保随时可以通过节点编号 $u$ 在 $O(1)$ 时间定位到它在堆中的位置 <code>where[u]</code>。
      </div>
    </div>

    <div style="background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 6px; padding: 10px;">
      <div style="font-weight: 700; color: #166534; margin-bottom: 4px;">2. 三态状态机简化逻辑</div>
      <div style="font-size: 12px; color: #15803d;">
        <code>where[]</code> 数组一专多能：既是指针映射表，又是访问标记表（-2 代表已确定最短路），完美省去额外的布尔数组。
      </div>
    </div>
  </div>
`;
