/**
 * Dinic 网络最大流与残量网络 (Dinic Max Flow & Residual Graph)
 * 参考左程云《算法通关课》【必备篇】class071: 增广路、成对反向弧退流、BFS 层次图、当前弧优化与多路增广 (洛谷 P3376)
 */

export const DINIC_MAX_FLOW_CODE_LANGUAGES: Record<string, string[]> = {
  cpp: [
    '#include <iostream>',
    '#include <vector>',
    '#include <queue>',
    '#include <algorithm>',
    'using namespace std;',
    '',
    '// Dinic 网络最大流 (洛谷 P3376 / 左程云 class071)',
    '// 核心：BFS 构建分层图 depth[] + DFS 当前弧优化 cur[] 与多路增广',
    'struct Edge {',
    '    int to, cap, flow, rev;',
    '};',
    '',
    'class Dinic {',
    'public:',
    '    int n, s, t;',
    '    vector<vector<Edge>> adj;',
    '    vector<int> depth, cur;',
    '    ',
    '    Dinic(int n, int s, int t) : n(n), s(s), t(t), adj(n + 1), depth(n + 1), cur(n + 1) {}',
    '    ',
    '    void addEdge(int u, int v, int cap) {',
    '        adj[u].push_back({v, cap, 0, (int)adj[v].size()});',
    '        adj[v].push_back({u, 0, 0, (int)adj[u].size() - 1}); // 反向边初始容量为 0',
    '    }',
    '    ',
    '    // 1. BFS 划分层次图',
    '    bool bfs() {',
    '        fill(depth.begin(), depth.end(), 0);',
    '        queue<int> q;',
    '        q.push(s);',
    '        depth[s] = 1;',
    '        ',
    '        while (!q.empty()) {',
    '            int u = q.front(); q.pop();',
    '            for (const auto& e : adj[u]) {',
    '                if (e.cap - e.flow > 0 && depth[e.to] == 0) {',
    '                    depth[e.to] = depth[u] + 1;',
    '                    q.push(e.to);',
    '                }',
    '            }',
    '        }',
    '        return depth[t] > 0; // 汇点可达',
    '    }',
    '    ',
    '    // 2. DFS 多路增广与当前弧优化',
    '    int dfs(int u, int limit) {',
    '        if (u == t || limit == 0) return limit;',
    '        int flow = 0;',
    '        ',
    '        for (int& i = cur[u]; i < (int)adj[u].size(); ++i) {',
    '            Edge& e = adj[u][i];',
    '            if (depth[e.to] == depth[u] + 1 && e.cap - e.flow > 0) {',
    '                int pushed = dfs(e.to, min(limit - flow, e.cap - e.flow));',
    '                if (pushed > 0) {',
    '                    e.flow += pushed;',
    '                    adj[e.to][e.rev].flow -= pushed; // 反向边退流抵消',
    '                    flow += pushed;',
    '                    if (flow == limit) break;',
    '                }',
    '            }',
    '        }',
    '        return flow;',
    '    }',
    '    ',
    '    int maxFlow() {',
    '        int total = 0;',
    '        while (bfs()) {',
    '            fill(cur.begin(), cur.end(), 0); // 重置当前弧',
    '            total += dfs(s, 1e9);',
    '        }',
    '        return total;',
    '    }',
    '};',
  ],
  java: [
    'package class071;',
    '',
    'import java.util.*;',
    '',
    '// Dinic 网络最大流 - 左程云标准模板',
    'public class Code01_DinicLuogu {',
    '    public static class Edge {',
    '        public int to, cap, flow, rev;',
    '        public Edge(int to, int cap, int rev) {',
    '            this.to = to; this.cap = cap; this.flow = 0; this.rev = rev;',
    '        }',
    '    }',
    '    ',
    '    public static List<Edge>[] graph;',
    '    public static int[] depth, cur;',
    '    ',
    '    public static boolean bfs(int s, int t, int n) {',
    '        Arrays.fill(depth, 0);',
    '        Queue<Integer> queue = new LinkedList<>();',
    '        queue.add(s);',
    '        depth[s] = 1;',
    '        ',
    '        while (!queue.isEmpty()) {',
    '            int u = queue.poll();',
    '            for (Edge e : graph[u]) {',
    '                if (e.cap - e.flow > 0 && depth[e.to] == 0) {',
    '                    depth[e.to] = depth[u] + 1;',
    '                    queue.add(e.to);',
    '                }',
    '            }',
    '        }',
    '        return depth[t] > 0;',
    '    }',
    '    ',
    '    public static int dfs(int u, int t, int limit) {',
    '        if (u == t || limit == 0) return limit;',
    '        int flow = 0;',
    '        for (int i = cur[u]; i < graph[u].size(); i++) {',
    '            cur[u] = i;',
    '            Edge e = graph[u].get(i);',
    '            if (depth[e.to] == depth[u] + 1 && e.cap - e.flow > 0) {',
    '                int pushed = dfs(e.to, t, Math.min(limit - flow, e.cap - e.flow));',
    '                if (pushed > 0) {',
    '                    e.flow += pushed;',
    '                    graph[e.to].get(e.rev).flow -= pushed;',
    '                    flow += pushed;',
    '                    if (flow == limit) break;',
    '                }',
    '            }',
    '        }',
    '        return flow;',
    '    }',
    '}',
  ],
  python: [
    'from collections import deque',
    '',
    'class Dinic:',
    '    def __init__(self, n: int, s: int, t: int):',
    '        self.n, self.s, self.t = n, s, t',
    '        self.graph = [[] for _ in range(n + 1)]',
    '        self.depth = [0] * (n + 1)',
    '        self.cur = [0] * (n + 1)',
    '        ',
    '    def add_edge(self, u: int, v: int, cap: int):',
    '        self.graph[u].append([v, cap, 0, len(self.graph[v])])',
    '        self.graph[v].append([u, 0, 0, len(self.graph[u]) - 1])',
    '        ',
    '    def bfs(self) -> bool:',
    '        self.depth = [0] * (self.n + 1)',
    '        q = deque([self.s])',
    '        self.depth[self.s] = 1',
    '        ',
    '        while q:',
    '            u = q.popleft()',
    '            for v, cap, flow, rev in self.graph[u]:',
    '                if cap - flow > 0 and self.depth[v] == 0:',
    '                    self.depth[v] = self.depth[u] + 1',
    '                    q.append(v)',
    '        return self.depth[self.t] > 0',
    '        ',
    '    def dfs(self, u: int, limit: int) -> int:',
    '        if u == self.t or limit == 0:',
    '            return limit',
    '        flow = 0',
    '        for i in range(self.cur[u], len(self.graph[u])):',
    '            self.cur[u] = i',
    '            v, cap, f, rev = self.graph[u][i]',
    '            if self.depth[v] == self.depth[u] + 1 and cap - f > 0:',
    '                pushed = self.dfs(v, min(limit - flow, cap - f))',
    '                if pushed > 0:',
    '                    self.graph[u][i][2] += pushed',
    '                    self.graph[v][rev][2] -= pushed',
    '                    flow += pushed',
    '                    if flow == limit:',
    '                        break',
    '        return flow',
    '        ',
    '    def max_flow(self) -> int:',
    '        total = 0',
    '        while self.bfs():',
    '            self.cur = [0] * (self.n + 1)',
    '            total += self.dfs(self.s, float("inf"))',
    '        return total',
  ],
  javascript: [
    '// Dinic 网络最大流 (JavaScript 版)',
    'class Dinic {',
    '  constructor(n, s, t) {',
    '    this.n = n; this.s = s; this.t = t;',
    '    this.graph = Array.from({ length: n + 1 }, () => []);',
    '    this.depth = Array(n + 1).fill(0);',
    '    this.cur = Array(n + 1).fill(0);',
    '  }',
    '  ',
    '  addEdge(u, v, cap) {',
    '    this.graph[u].push({ to: v, cap, flow: 0, rev: this.graph[v].length });',
    '    this.graph[v].push({ to: u, cap: 0, flow: 0, rev: this.graph[u].length - 1 });',
    '  }',
    '  ',
    '  bfs() {',
    '    this.depth.fill(0);',
    '    const q = [this.s];',
    '    this.depth[this.s] = 1;',
    '    ',
    '    while (q.length > 0) {',
    '      const u = q.shift();',
    '      for (const e of this.graph[u]) {',
    '        if (e.cap - e.flow > 0 && this.depth[e.to] === 0) {',
    '          this.depth[e.to] = this.depth[u] + 1;',
    '          q.push(e.to);',
    '        }',
    '      }',
    '    }',
    '    return this.depth[this.t] > 0;',
    '  }',
    '  ',
    '  dfs(u, limit) {',
    '    if (u === this.t || limit === 0) return limit;',
    '    let flow = 0;',
    '    for (let i = this.cur[u]; i < this.graph[u].length; i++) {',
    '      this.cur[u] = i;',
    '      const e = this.graph[u][i];',
    '      if (this.depth[e.to] === this.depth[u] + 1 && e.cap - e.flow > 0) {',
    '        const pushed = this.dfs(e.to, Math.min(limit - flow, e.cap - e.flow));',
    '        if (pushed > 0) {',
    '          e.flow += pushed;',
    '          this.graph[e.to][e.rev].flow -= pushed;',
    '          flow += pushed;',
    '          if (flow === limit) break;',
    '        }',
    '      }',
    '    }',
    '    return flow;',
    '  }',
    '  ',
    '  maxFlow() {',
    '    let total = 0;',
    '    while (this.bfs()) {',
    '      this.cur.fill(0);',
    '      total += this.dfs(this.s, Infinity);',
    '    }',
    '    return total;',
    '  }',
    '}',
  ],
};

export const DINIC_MAX_FLOW_PROBLEM_HTML = `
  <div style="font-size: 13px; line-height: 1.6; color: #334155;">
    <h3 style="margin-top: 0; color: #0f172a; font-size: 15px; font-weight: 800;">🌊 Dinic 网络最大流与残量网络 (洛谷 P3376)</h3>
    <p>
      给定一个网络拓扑，源点为 $S$，汇点为 $T$，每条有向管道具有最大流通容量 $C(u, v)$。
      求在不超出管道容量上限且节点流量守恒（流入量 = 流出量）的前提下，从源点 $S$ 流向汇点 $T$ 的<b>最大可能总流量 (Maximum Flow)</b>。
    </p>

    <div style="background: #f8fafc; border-left: 4px solid #3b82f6; padding: 8px 12px; margin: 10px 0; border-radius: 0 6px 6px 0;">
      <div style="font-weight: 700; color: #1e40af; margin-bottom: 4px;">🏆 Dinic 算法两大核心武器</div>
      <div style="font-size: 11.5px; color: #334155;">
        <b>1. BFS 分层图 (Level Graph)</b>：按照最短步数划分层级 <code>depth[u]</code>，增广时只允许向下一层推进，杜绝死循环走回路！<br/>
        <b>2. 当前弧优化 (Current Arc Optimization)</b>：通过 <code>cur[u]</code> 记录当前遍历到的出边，避开已流满或无法到达汇点的废边，实现单次极速多路增广！
      </div>
    </div>
  </div>
`;

export const DINIC_MAX_FLOW_ANALYSIS_HTML = `
  <div style="font-size: 13px; line-height: 1.6; color: #334155;">
    <h3 style="margin-top: 0; color: #0f172a; font-size: 15px; font-weight: 800;">💡 左程云成对反向弧退流与最大流最小割定理</h3>

    <div style="background: #eff6ff; border: 1px solid #bfdbfe; border-radius: 6px; padding: 10px; margin-bottom: 12px;">
      <div style="font-weight: 700; color: #1e3a8a; margin-bottom: 4px;">1. 反向边退流（后悔机制）</div>
      <div style="font-size: 12px; color: #1e40af;">
        正向边增广 $f$ 流量的同时，反向弧残量自动增加 $f$！<br/>
        若后续增广流沿着反向弧推进，物理上等价于<b>将先前推错的流量退回并重定向到其他更优通道</b>，从数学上严格保证了贪心增广能收敛到全局最大流。
      </div>
    </div>

    <div style="background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 6px; padding: 10px;">
      <div style="font-weight: 700; color: #166534; margin-bottom: 4px;">2. 最大流最小割定理 (Max-Flow Min-Cut)</div>
      <div style="font-size: 12px; color: #15803d;">
        当网络中再也无法通过 BFS 找到一条残量大于 0 的增广路径时，当前流量总和必然严格等于将 $S$ 与 $T$ 割开所需的最小管道容量和！
      </div>
    </div>
  </div>
`;
