/**
 * DAG 支配树与编译控制流分析 (Dominator Tree on DAG)
 * 进阶图论: 控制流图支配关系 (idom)、DAG 前驱节点支配树 LCA 定理、增量倍增构建 (洛谷 P5180)
 */

export const DOMINATOR_TREE_CODE_LANGUAGES: Record<string, string[]> = {
  cpp: [
    '#include <iostream>',
    '#include <vector>',
    '#include <queue>',
    '#include <algorithm>',
    'using namespace std;',
    '',
    '// DAG 支配树构建 (洛谷 P5180 / 编译原理 SSA 形式)',
    '// 核心：拓扑排序 + 前驱节点在支配树上的 LCA 定理：idom[u] = LCA_tree(pred[1], pred[2]...)',
    'class DAGDominatorTree {',
    'public:',
    '    int n, root, maxDepth = 18;',
    '    vector<vector<int>> adj, revAdj, domTreeAdj;',
    '    vector<int> inDegree, topoOrder, depth, idom;',
    '    vector<vector<int>> up;',
    '    ',
    '    DAGDominatorTree(int n, int root = 1) : n(n), root(root), adj(n + 1),',
    '                                            revAdj(n + 1), domTreeAdj(n + 1),',
    '                                            inDegree(n + 1, 0), depth(n + 1, 0),',
    '                                            idom(n + 1, 0), up(n + 1, vector<int>(19, 0)) {}',
    '    ',
    '    void addEdge(int u, int v) {',
    '        adj.get(u).push_back(v);',
    '        revAdj[v].push_back(u);',
    '        inDegree[v]++;',
    '    }',
    '    ',
    '    int getLCA(int u, int v) {',
    '        if (depth[u] < depth[v]) swap(u, v);',
    '        for (int i = maxDepth; i >= 0; --i) {',
    '            if (depth[u] - (1 << i) >= depth[v]) u = up[u][i];',
    '        }',
    '        if (u == v) return u;',
    '        for (int i = maxDepth; i >= 0; --i) {',
    '            if (up[u][i] != up[v][i]) {',
    '                u = up[u][i];',
    '                v = up[v][i];',
    '            }',
    '        }',
    '        return up[u][0];',
    '    }',
    '    ',
    '    void buildDominatorTree() {',
    '        queue<int> q;',
    '        q.push(root);',
    '        depth[root] = 1;',
    '        ',
    '        while (!q.empty()) {',
    '            int u = q.front(); q.pop();',
    '            topoOrder.push_back(u);',
    '            ',
    '            if (u != root) {',
    '                // idom[u] = 所有前驱节点在支配树上的 LCA',
    '                int pLCA = revAdj[u][0];',
    '                for (size_t i = 1; i < revAdj[u].size(); ++i) {',
    '                    pLCA = getLCA(pLCA, revAdj[u][i]);',
    '                }',
    '                idom[u] = pLCA;',
    '                domTreeAdj[pLCA].push_back(u);',
    '                depth[u] = depth[pLCA] + 1;',
    '                up[u][0] = pLCA;',
    '                for (int i = 1; i <= maxDepth; ++i) up[u][i] = up[up[u][i - 1]][i - 1];',
    '            }',
    '            ',
    '            for (int v : adj[u]) {',
    '                if (--inDegree[v] == 0) q.push(v);',
    '            }',
    '        }',
    '    }',
    '};',
  ],
  java: [
    'package advanced_graph;',
    '',
    'import java.util.*;',
    '',
    '/**',
    ' * DAG 支配树 (Dominator Tree) 标准实现',
    ' * 核心定理: idom[u] = LCA_DomTree(pred_1, pred_2, ..., pred_k)',
    ' * 时间复杂度: O((V + E) log V)，空间复杂度: O(V + E)',
    ' */',
    'public class Code01_DAGDominatorTree {',
    '    public static class DominatorTree {',
    '        public int n, root, maxDepth = 18;',
    '        public ArrayList<ArrayList<Integer>> adj, revAdj, domTreeAdj;',
    '        public int[] inDegree, depth, idom;',
    '        public int[][] up;',
    '        ',
    '        public DominatorTree(int n, int root) {',
    '            this.n = n;',
    '            this.root = root;',
    '            adj = new ArrayList<>();',
    '            revAdj = new ArrayList<>();',
    '            domTreeAdj = new ArrayList<>();',
    '            for (int i = 0; i <= n; i++) {',
    '                adj.add(new ArrayList<>());',
    '                revAdj.add(new ArrayList<>());',
    '                domTreeAdj.add(new ArrayList<>());',
    '            }',
    '            inDegree = new int[n + 1];',
    '            depth = new int[n + 1];',
    '            idom = new int[n + 1];',
    '            up = new int[n + 1][19];',
    '        }',
    '        ',
    '        public void addEdge(int u, int v) {',
    '            adj.get(u).add(v);',
    '            revAdj[v].add(u);',
    '            inDegree[v]++;',
    '        }',
    '        ',
    '        public int getLCA(int u, int v) {',
    '            if (depth[u] < depth[v]) { int t = u; u = v; v = t; }',
    '            for (int i = maxDepth; i >= 0; i--) {',
    '                if (depth[u] - (1 << i) >= depth[v]) u = up[u][i];',
    '            }',
    '            if (u == v) return u;',
    '            for (int i = maxDepth; i >= 0; i--) {',
    '                if (up[u][i] != up[v][i]) { u = up[u][i]; v = up[v][i]; }',
    '            }',
    '            return up[u][0];',
    '        }',
    '        ',
    '        public void build() {',
    '            Queue<Integer> q = new ArrayDeque<>();',
    '            q.add(root);',
    '            depth[root] = 1;',
    '            ',
    '            while (!q.isEmpty()) {',
    '                int u = q.poll();',
    '                if (u != root && !revAdj[u].isEmpty()) {',
    '                    int pLCA = revAdj[u].get(0);',
    '                    for (int i = 1; i < revAdj[u].size(); i++) {',
    '                        pLCA = getLCA(pLCA, revAdj[u].get(i));',
    '                    }',
    '                    idom[u] = pLCA;',
    '                    domTreeAdj.get(pLCA).add(u);',
    '                    depth[u] = depth[pLCA] + 1;',
    '                    up[u][0] = pLCA;',
    '                    for (int i = 1; i <= maxDepth; i++) up[u][i] = up[up[u][i - 1]][i - 1];',
    '                }',
    '                for (int v : adj.get(u)) {',
    '                    if (--inDegree[v] == 0) q.add(v);',
    '                }',
    '            }',
    '        }',
    '    }',
    '}',
  ],
  python: [
    '# DAG 支配树 (Python 标准实现)',
    '# 核心原理: 拓扑排序 + 前驱节点在支配树上的 LCA 定理',
    '# 时间复杂度: O((V + E) log V)，空间复杂度: O(V + E)',
    'from collections import deque',
    'import sys',
    'sys.setrecursionlimit(200000)',
    '',
    'class DAGDominatorTree:',
    '    def __init__(self, n: int, root: int = 1):',
    '        self.n = n',
    '        self.root = root',
    '        self.max_depth = 18',
    '        self.adj = [[] for _ in range(n + 1)]',
    '        self.rev_adj = [[] for _ in range(n + 1)]',
    '        self.dom_tree_adj = [[] for _ in range(n + 1)]',
    '        self.in_degree = [0] * (n + 1)',
    '        self.depth = [0] * (n + 1)',
    '        self.idom = [0] * (n + 1)',
    '        self.up = [[0] * 19 for _ in range(n + 1)]',
    '        ',
    '    def add_edge(self, u: int, v: int):',
    '        self.adj[u].append(v)',
    '        self.rev_adj[v].append(u)',
    '        self.in_degree[v] += 1',
    '        ',
    '    def get_lca(self, u: int, v: int) -> int:',
    '        if self.depth[u] < self.depth[v]:',
    '            u, v = v, u',
    '        for i in range(self.max_depth, -1, -1):',
    '            if self.depth[u] - (1 << i) >= self.depth[v]:',
    '                u = self.up[u][i]',
    '        if u == v: return u',
    '        for i in range(self.max_depth, -1, -1):',
    '            if self.up[u][i] != self.up[v][i]:',
    '                u = self.up[u][i]',
    '                v = self.up[v][i]',
    '        return self.up[u][0]',
    '        ',
    '    def build(self):',
    '        q = deque([self.root])',
    '        self.depth[self.root] = 1',
    '        while q:',
    '            u = q.popleft()',
    '            if u != self.root and self.rev_adj[u]:',
    '                p_lca = self.rev_adj[u][0]',
    '                for p in self.rev_adj[u][1:]:',
    '                    p_lca = self.get_lca(p_lca, p)',
    '                self.idom[u] = p_lca',
    '                self.dom_tree_adj[p_lca].append(u)',
    '                self.depth[u] = self.depth[p_lca] + 1',
    '                self.up[u][0] = p_lca',
    '                for i in range(1, self.max_depth + 1):',
    '                    self.up[u][i] = self.up[self.up[u][i - 1]][i - 1]',
    '            for v in self.adj[u]:',
    '                self.in_degree[v] -= 1',
    '                if self.in_degree[v] == 0:',
    '                    q.append(v)',
  ],
  javascript: [
    '/**',
    ' * DAG 支配树 (JavaScript 版)',
    ' * 编译原理控制流 SSA 支配边界核心算法',
    ' */',
    'class DAGDominatorTree {',
    '  constructor(n, root = 1) {',
    '    this.n = n;',
    '    this.root = root;',
    '    this.maxDepth = 18;',
    '    this.adj = Array.from({ length: n + 1 }, () => []);',
    '    this.revAdj = Array.from({ length: n + 1 }, () => []);',
    '    this.domTreeAdj = Array.from({ length: n + 1 }, () => []);',
    '    this.inDegree = Array(n + 1).fill(0);',
    '    this.depth = Array(n + 1).fill(0);',
    '    this.idom = Array(n + 1).fill(0);',
    '    this.up = Array.from({ length: n + 1 }, () => Array(19).fill(0));',
    '  }',
    '  ',
    '  addEdge(u, v) {',
    '    this.adj[u].push(v);',
    '    this.revAdj[v].push(u);',
    '    this.inDegree[v]++;',
    '  }',
    '  ',
    '  getLCA(u, v) {',
    '    if (this.depth[u] < this.depth[v]) { const t = u; u = v; v = t; }',
    '    for (let i = this.maxDepth; i >= 0; i--) {',
    '      if (this.depth[u] - (1 << i) >= this.depth[v]) u = this.up[u][i];',
    '    }',
    '    if (u === v) return u;',
    '    for (let i = this.maxDepth; i >= 0; i--) {',
    '      if (this.up[u][i] !== this.up[v][i]) { u = this.up[u][i]; v = this.up[v][i]; }',
    '    }',
    '    return this.up[u][0];',
    '  }',
    '  ',
    '  build() {',
    '    const q = [this.root];',
    '    this.depth[this.root] = 1;',
    '    while (q.length > 0) {',
    '      const u = q.shift();',
    '      if (u !== this.root && this.revAdj[u].length > 0) {',
    '        let pLCA = this.revAdj[u][0];',
    '        for (let i = 1; i < this.revAdj[u].length; i++) {',
    '          pLCA = this.getLCA(pLCA, this.revAdj[u][i]);',
    '        }',
    '        this.idom[u] = pLCA;',
    '        this.domTreeAdj[pLCA].push(u);',
    '        this.depth[u] = this.depth[pLCA] + 1;',
    '        this.up[u][0] = pLCA;',
    '        for (let i = 1; i <= this.maxDepth; i++) {',
    '          this.up[u][i] = this.up[this.up[u][i - 1]][i - 1];',
    '        }',
    '      }',
    '      for (const v of this.adj[u]) {',
    '        if (--this.inDegree[v] === 0) q.push(v);',
    '      }',
    '    }',
    '  }',
    '}',
  ],
};

export const DOMINATOR_TREE_PROBLEM_HTML = `
  <div style="font-size: 13px; line-height: 1.6; color: #334155;">
    <h3 style="margin-top: 0; color: #0f172a; font-size: 15px; font-weight: 800;">🏛️ 支配树 (Dominator Tree)</h3>
    <p>
      在有向流图 $G=(V, E, r)$ 中，若从源点 $r$ 到点 $w$ 的<b>每一条路径</b>都必须经过点 $d$，则称 $d$ <b>支配</b> $w$。每个点离它最近的严格支配者称为<b>直接支配点 (idom)</b>，所有直接支配边构成一棵以源点为根的<b>支配树</b>（洛谷 P5180 / 编译原理 SSA 支配边界）。
    </p>

    <div style="background: #f8fafc; border-left: 4px solid #3b82f6; padding: 8px 12px; margin: 10px 0; border-radius: 0 6px 6px 0;">
      <div style="font-weight: 700; color: #1e40af; margin-bottom: 4px;">📐 DAG 支配树 LCA 定理</div>
      <div style="font-size: 11.5px; color: #334155;">
        在 DAG 上，节点 $u$ 的直接支配点等于其<b>所有直接前驱节点在支配树上的最近公共祖先</b>：<br/>
        $\\text{idom}[u] = \\text{LCA}_{\\text{DomTree}}(\\text{pred}_1, \\text{pred}_2, \\dots, \\text{pred}_k)$
      </div>
    </div>
  </div>
`;

export const DOMINATOR_TREE_ANALYSIS_HTML = `
  <div style="font-size: 13px; line-height: 1.6; color: #334155;">
    <h3 style="margin-top: 0; color: #0f172a; font-size: 15px; font-weight: 800;">💡 支配树在工业界的核心应用</h3>

    <div style="background: #eff6ff; border: 1px solid #bfdbfe; border-radius: 6px; padding: 10px; margin-bottom: 12px;">
      <div style="font-weight: 700; color: #1e3a8a; margin-bottom: 4px;">1. 编译器底层优化 (LLVM / GCC)</div>
      <div style="font-size: 12px; color: #1e40af;">
        支配树是编译器构建<b>静态单赋值形式 (SSA Form)</b>、插入 $\\phi$ 函数（支配边界 Dominance Frontier）、循环不变代码外提 (LICM) 与死代码消除的基础基石！
      </div>
    </div>

    <div style="background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 6px; padding: 10px;">
      <div style="font-weight: 700; color: #166534; margin-bottom: 4px;">2. 关键节点与网络咽喉评估</div>
      <div style="font-size: 12px; color: #15803d;">
        在支配树中，节点 $u$ 的子树大小即为：如果 $u$ 故障瘫痪，网络中将有多少个节点彻底失去与根节点的连通性！
      </div>
    </div>
  </div>
`;
