/**
 * 树上启发式合并 (DSU on Tree - Heavy-Light Merge on Trees)
 * 进阶树论: 重儿子保留计数桶 (keep=true)、轻儿子统计后清空 (keep=false)、轻边跳跃不超过 O(log n) 次 (CF600E / 洛谷 U41492)
 */

export const DSU_ON_TREE_CODE_LANGUAGES: Record<string, string[]> = {
  cpp: [
    '#include <iostream>',
    '#include <vector>',
    'using namespace std;',
    '',
    '// 树上启发式合并 DSU on Tree (CF600E / 洛谷 U41492)',
    '// 核心：重儿子保留贡献，轻儿子清空贡献，总复杂度严格 O(N log N)',
    'class DSUOnTree {',
    'public:',
    '    int n;',
    '    vector<vector<int>> adj;',
    '    vector<int> col, sz, son, cnt, ans;',
    '    int distinctCount = 0;',
    '    ',
    '    DSUOnTree(int n) : n(n), adj(n + 1), col(n + 1, 0), sz(n + 1, 0),',
    '                       son(n + 1, 0), cnt(n + 1, 0), ans(n + 1, 0) {}',
    '    ',
    '    void addEdge(int u, int v) {',
    '        adj[u].push_back(v);',
    '        adj[v].push_back(u);',
    '    }',
    '    ',
    '    // 1. 第一次 DFS：求重儿子与子树大小',
    '    void dfsInit(int u, int fa) {',
    '        sz[u] = 1;',
    '        for (int v : adj[u]) {',
    '            if (v == fa) continue;',
    '            dfsInit(v, u);',
    '            sz[u] += sz[v];',
    '            if (sz[v] > sz[son[u]]) son[u] = v;',
    '        }',
    '    }',
    '    ',
    '    // 2. 添加/删除子树贡献',
    '    void updateSubtree(int u, int fa, int val, int skipSon) {',
    '        if (cnt[col[u]] == 0 && val == 1) distinctCount++;',
    '        cnt[col[u]] += val;',
    '        if (cnt[col[u]] == 0 && val == -1) distinctCount--;',
    '        ',
    '        for (int v : adj[u]) {',
    '            if (v != fa && v != skipSon) updateSubtree(v, u, val, skipSon);',
    '        }',
    '    }',
    '    ',
    '    // 3. 第二次 DFS：启发式合并',
    '    void dfsSolve(int u, int fa, bool keep) {',
    '        // 先处理所有轻儿子 (不保留数据)',
    '        for (int v : adj[u]) {',
    '            if (v != fa && v != son[u]) dfsSolve(v, u, false);',
    '        }',
    '        // 再处理重儿子 (保留数据)',
    '        if (son[u]) dfsSolve(son[u], u, true);',
    '        ',
    '        // 暴力将轻儿子及当前节点贡献加入',
    '        updateSubtree(u, fa, 1, son[u]);',
    '        ans[u] = distinctCount;',
    '        ',
    '        // 若为轻儿子，清空本子树贡献',
    '        if (!keep) {',
    '            updateSubtree(u, fa, -1, 0);',
    '        }',
    '    }',
    '};',
  ],
  java: [
    'package advanced_tree;',
    '',
    'import java.util.*;',
    '',
    '/**',
    ' * 树上启发式合并 (DSU on Tree) 标准实现',
    ' * 时间复杂度: O(N log N)，空间复杂度: O(N)',
    ' * 核心思想: 重儿子子树数据保留 (keep=true)，轻儿子清空重算 (keep=false)',
    ' */',
    'public class Code01_DSUOnTree {',
    '    public static class Solver {',
    '        public int n, distinctCount = 0;',
    '        public ArrayList<ArrayList<Integer>> adj;',
    '        public int[] col, sz, son, cnt, ans;',
    '        ',
    '        public Solver(int n) {',
    '            this.n = n;',
    '            this.adj = new ArrayList<>();',
    '            for (int i = 0; i <= n; i++) adj.add(new ArrayList<>());',
    '            this.col = new int[n + 1];',
    '            this.sz = new int[n + 1];',
    '            this.son = new int[n + 1];',
    '            this.cnt = new int[n + 1];',
    '            this.ans = new int[n + 1];',
    '        }',
    '        ',
    '        public void addEdge(int u, int v) {',
    '            adj.get(u).add(v);',
    '            adj.get(v).add(u);',
    '        }',
    '        ',
    '        // 1. 第一次 DFS：预处理子树大小与重儿子',
    '        public void dfsInit(int u, int fa) {',
    '            sz[u] = 1;',
    '            for (int v : adj.get(u)) {',
    '                if (v == fa) continue;',
    '                dfsInit(v, u);',
    '                sz[u] += sz[v];',
    '                if (sz[v] > sz[son[u]]) son[u] = v;',
    '            }',
    '        }',
    '        ',
    '        // 2. 添加/删除子树贡献',
    '        public void update(int u, int fa, int val, int skipSon) {',
    '            if (cnt[col[u]] == 0 && val == 1) distinctCount++;',
    '            cnt[col[u]] += val;',
    '            if (cnt[col[u]] == 0 && val == -1) distinctCount--;',
    '            for (int v : adj.get(u)) {',
    '                if (v != fa && v != skipSon) update(v, u, val, skipSon);',
    '            }',
    '        }',
    '        ',
    '        // 3. 启发式合并求解',
    '        public void dfsSolve(int u, int fa, boolean keep) {',
    '            // 先递归处理所有轻儿子 (不保留数据)',
    '            for (int v : adj.get(u)) {',
    '                if (v != fa && v != son[u]) dfsSolve(v, u, false);',
    '            }',
    '            // 再递归重儿子 (保留数据)',
    '            if (son[u] != 0) dfsSolve(son[u], u, true);',
    '            ',
    '            // 暴力合并轻子树贡献与自身',
    '            update(u, fa, 1, son[u]);',
    '            ans[u] = distinctCount;',
    '            ',
    '            // 若当前为轻儿子，清空本子树贡献',
    '            if (!keep) {',
    '                update(u, fa, -1, 0);',
    '            }',
    '        }',
    '    }',
    '}',
  ],
  python: [
    '# 树上启发式合并 DSU on Tree (Python 标准实现)',
    '# 核心原理: 重链剖分划分重轻子树，重儿子保留全局计数桶，轻儿子统计后清空',
    '# 时间复杂度: O(N log N)，空间复杂度: O(N)',
    'import sys',
    'sys.setrecursionlimit(200000)',
    '',
    'class DSUOnTree:',
    '    def __init__(self, n: int):',
    '        self.n = n',
    '        self.adj = [[] for _ in range(n + 1)]',
    '        self.col = [0] * (n + 1)',
    '        self.son = [0] * (n + 1)',
    '        self.sz = [0] * (n + 1)',
    '        self.cnt = [0] * (n + 1)',
    '        self.ans = [0] * (n + 1)',
    '        self.distinct_count = 0',
    '        ',
    '    def add_edge(self, u: int, v: int):',
    '        self.adj[u].append(v)',
    '        self.adj[v].append(u)',
    '        ',
    '    def dfs_init(self, u: int, fa: int):',
    '        self.sz[u] = 1',
    '        for v in self.adj[u]:',
    '            if v == fa: continue',
    '            self.dfs_init(v, u)',
    '            self.sz[u] += self.sz[v]',
    '            if self.sz[v] > self.sz[self.son[u]]:',
    '                self.son[u] = v',
    '                ',
    '    def update(self, u: int, fa: int, val: int, skip_son: int):',
    '        c = self.col[u]',
    '        if self.cnt[c] == 0 and val == 1: self.distinct_count += 1',
    '        self.cnt[c] += val',
    '        if self.cnt[c] == 0 and val == -1: self.distinct_count -= 1',
    '        for v in self.adj[u]:',
    '            if v != fa and v != skip_son:',
    '                self.update(v, u, val, skip_son)',
    '                ',
    '    def dfs_solve(self, u: int, fa: int, keep: bool):',
    '        for v in self.adj[u]:',
    '            if v != fa and v != self.son[u]:',
    '                self.dfs_solve(v, u, False)',
    '        if self.son[u] != 0:',
    '            self.dfs_solve(self.son[u], u, True)',
    '            ',
    '        self.update(u, fa, 1, self.son[u])',
    '        self.ans[u] = self.distinct_count',
    '        if not keep:',
    '            self.update(u, fa, -1, 0)',
  ],
  javascript: [
    '/**',
    ' * 树上启发式合并 DSU on Tree (JavaScript 版)',
    ' * 静态树上重链分治算法',
    ' */',
    'class DSUOnTree {',
    '  constructor(n) {',
    '    this.n = n;',
    '    this.adj = Array.from({ length: n + 1 }, () => []);',
    '    this.col = Array(n + 1).fill(0);',
    '    this.son = Array(n + 1).fill(0);',
    '    this.sz = Array(n + 1).fill(0);',
    '    this.cnt = Array(n + 1).fill(0);',
    '    this.ans = Array(n + 1).fill(0);',
    '    this.distinctCount = 0;',
    '  }',
    '  ',
    '  addEdge(u, v) {',
    '    this.adj[u].push(v);',
    '    this.adj[v].push(u);',
    '  }',
    '  ',
    '  dfsInit(u, fa) {',
    '    this.sz[u] = 1;',
    '    for (const v of this.adj[u]) {',
    '      if (v === fa) continue;',
    '      this.dfsInit(v, u);',
    '      this.sz[u] += this.sz[v];',
    '      if (this.sz[v] > this.sz[this.son[u]]) this.son[u] = v;',
    '    }',
    '  }',
    '  ',
    '  update(u, fa, val, skipSon) {',
    '    const c = this.col[u];',
    '    if (this.cnt[c] === 0 && val === 1) this.distinctCount++;',
    '    this.cnt[c] += val;',
    '    if (this.cnt[c] === 0 && val === -1) this.distinctCount--;',
    '    for (const v of this.adj[u]) {',
    '      if (v !== fa && v !== skipSon) this.update(v, u, val, skipSon);',
    '    }',
    '  }',
    '  ',
    '  dfsSolve(u, fa, keep) {',
    '    for (const v of this.adj[u]) {',
    '      if (v !== fa && v !== this.son[u]) this.dfsSolve(v, u, false);',
    '    }',
    '    if (this.son[u] !== 0) this.dfsSolve(this.son[u], u, true);',
    '    ',
    '    this.update(u, fa, 1, this.son[u]);',
    '    this.ans[u] = this.distinctCount;',
    '    if (!keep) {',
    '      this.update(u, fa, -1, 0);',
    '    }',
    '  }',
    '}',
  ],
};

export const DSU_ON_TREE_PROBLEM_HTML = `
  <div style="font-size: 13px; line-height: 1.6; color: #334155;">
    <h3 style="margin-top: 0; color: #0f172a; font-size: 15px; font-weight: 800;">🌲 树上启发式合并 (DSU on Tree)</h3>
    <p>
      给定一棵包含 $n$ 个节点的树，每个节点具有某种属性（如颜色 $col[u]$）。需要查询以每个节点为根的子树内某种特征统计（如不同颜色数量、众数和等）。利用重链剖分的轻重儿子划分思想，实现静态全局计数桶复用（CF600E / 洛谷 U41492）。
    </p>

    <div style="background: #f8fafc; border-left: 4px solid #3b82f6; padding: 8px 12px; margin: 10px 0; border-radius: 0 6px 6px 0;">
      <div style="font-weight: 700; color: #1e40af; margin-bottom: 4px;">👑 核心合并准则</div>
      <div style="font-size: 11.5px; color: #334155;">
        1. <b>轻儿子不保留</b>：先递归所有轻儿子，跑完后清空全局计数桶 (keep = false)；<br/>
        2. <b>重儿子保留</b>：最后递归重儿子，跑完后<b>保留</b>全局计数桶 (keep = true)；<br/>
        3. <b>暴力合并轻子树</b>：将轻儿子子树的节点逐一加入计数桶，记录本节点答案。
      </div>
    </div>
  </div>
`;

export const DSU_ON_TREE_ANALYSIS_HTML = `
  <div style="font-size: 13px; line-height: 1.6; color: #334155;">
    <h3 style="margin-top: 0; color: #0f172a; font-size: 15px; font-weight: 800;">💡 严格 O(n log n) 复杂度证明</h3>

    <div style="background: #eff6ff; border: 1px solid #bfdbfe; border-radius: 6px; padding: 10px; margin-bottom: 12px;">
      <div style="font-weight: 700; color: #1e3a8a; margin-bottom: 4px;">1. 轻边跳跃上限引理</div>
      <div style="font-size: 12px; color: #1e40af;">
        每个节点到树根的路径上，至多经过 $\\lfloor \\log_2 n \\rfloor$ 条轻边。一个节点只有在其所属子树作为轻儿子被暴力扫描时才会被访问一次，故每个节点在整个算法生命周期中最多被访问 $O(\\log n)$ 次！
      </div>
    </div>

    <div style="background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 6px; padding: 10px;">
      <div style="font-weight: 700; color: #166534; margin-bottom: 4px;">2. 空间零额外开销</div>
      <div style="font-size: 12px; color: #15803d;">
        无需动态开点线段树或线段树合并的多余内存指针，仅需一个全局一维数组 <code>cnt[]</code> 即可完成所有统计，常数极小且极度节省空间！
      </div>
    </div>
  </div>
`;
