/**
 * 电动车充放电分层图最短路 (Electric Vehicle Minimum Cost - Charge Layered Dijkstra)
 * 左程云算法通关课 Class 064 Code05 (LeetCode LCP 35)
 * 核心：状态空间 (u, charge)、原地充电转移与道路行驶转移、分层图 Dijkstra 优先队列
 */

export const EV_CHARGE_CODE_LANGUAGES: Record<string, string[]> = {
  cpp: [
    '#include <iostream>',
    '#include <vector>',
    '#include <queue>',
    'using namespace std;',
    '',
    '// 电动车游历城市最小费用 (LeetCode LCP 35 / 左程云 Class064 Code05)',
    '// 核心：(u, power) 二元状态空间，原地充电转移 + 行驶放电转移',
    'class Solution {',
    'public:',
    '    struct Node {',
    '        int city, power, cost;',
    '        bool operator>(const Node& other) const {',
    '            return cost > other.cost;',
    '        }',
    '    };',
    '    ',
    '    int electricCarPlan(vector<vector<int>>& paths, int cnt, int start, int end, vector<int>& charge) {',
    '        int n = charge.size();',
    '        vector<vector<pair<int, int>>> adj(n);',
    '        for (auto& p : paths) {',
    '            adj[p[0]].push_back({p[1], p[2]});',
    '            adj[p[1]].push_back({p[0], p[2]});',
    '        }',
    '        ',
    '        // dist[u][power] = 到达城市 u 且剩余电量为 power 的最小总时间/费用',
    '        vector<vector<int>> dist(n, vector<int>(cnt + 1, 1e9));',
    '        vector<vector<bool>> vis(n, vector<bool>(cnt + 1, false));',
    '        priority_queue<Node, vector<Node>, greater<Node>> pq;',
    '        ',
    '        dist[start][0] = 0;',
    '        pq.push({start, 0, 0});',
    '        ',
    '        while (!pq.empty()) {',
    '            Node cur = pq.top(); pq.pop();',
    '            int u = cur.city, p = cur.power, cost = cur.cost;',
    '            if (vis[u][p]) continue;',
    '            vis[u][p] = true;',
    '            if (u == end) return cost;',
    '            ',
    '            // 决策 1: 原地充 1 格电 (花费 charge[u] 单位时间)',
    '            if (p < cnt && !vis[u][p + 1] && cost + charge[u] < dist[u][p + 1]) {',
    '                dist[u][p + 1] = cost + charge[u];',
    '                pq.push({u, p + 1, cost + charge[u]});',
    '            }',
    '            ',
    '            // 决策 2: 驾车行驶到相邻城市 (耗电 w, 耗时 w)',
    '            for (auto& edge : adj[u]) {',
    '                int v = edge.first, w = edge.second;',
    '                if (p >= w && !vis[v][p - w] && cost + w < dist[v][p - w]) {',
    '                    dist[v][p - w] = cost + w;',
    '                    pq.push({v, p - w, cost + w});',
    '                }',
    '            }',
    '        }',
    '        return -1;',
    '    }',
    '};',
  ],
  java: [
    'package class064;',
    '',
    'import java.util.*;',
    '',
    '/**',
    ' * 电动车游历城市最小费用 (LeetCode LCP 35 / 左程云 Class064 Code05)',
    ' * 核心：二维状态 (city, power) 分层图最短路 + Dijkstra 堆优化',
    ' * 时间复杂度: O((M + N*cnt) * log(N*cnt))，空间复杂度: O(N*cnt)',
    ' */',
    'public class Code05_VisitCityMinCost {',
    '    public static class Node {',
    '        public int city;',
    '        public int power;',
    '        public int cost;',
    '        ',
    '        public Node(int c, int p, int w) {',
    '            city = c;',
    '            power = p;',
    '            cost = w;',
    '        }',
    '    }',
    '    ',
    '    public static int electricCarPlan(int[][] paths, int cnt, int start, int end, int[] charge) {',
    '        int n = charge.length;',
    '        ArrayList<ArrayList<int[]>> adj = new ArrayList<>();',
    '        for (int i = 0; i < n; i++) adj.add(new ArrayList<>());',
    '        for (int[] p : paths) {',
    '            adj.get(p[0]).add(new int[]{p[1], p[2]});',
    '            adj.get(p[1]).add(new int[]{p[0], p[2]});',
    '        }',
    '        ',
    '        int[][] dist = new int[n][cnt + 1];',
    '        for (int i = 0; i < n; i++) Arrays.fill(dist[i], Integer.MAX_VALUE);',
    '        boolean[][] vis = new boolean[n][cnt + 1];',
    '        PriorityQueue<Node> pq = new PriorityQueue<>((a, b) -> a.cost - b.cost);',
    '        ',
    '        dist[start][0] = 0;',
    '        pq.offer(new Node(start, 0, 0));',
    '        ',
    '        while (!pq.isEmpty()) {',
    '            Node cur = pq.poll();',
    '            int u = cur.city, p = cur.power, c = cur.cost;',
    '            if (vis[u][p]) continue;',
    '            vis[u][p] = true;',
    '            if (u == end) return c;',
    '            ',
    '            // 决策 1: 原地充 1 格电',
    '            if (p < cnt && !vis[u][p + 1] && c + charge[u] < dist[u][p + 1]) {',
    '                dist[u][p + 1] = c + charge[u];',
    '                pq.offer(new Node(u, p + 1, c + charge[u]));',
    '            }',
    '            ',
    '            // 决策 2: 沿公路行驶放电',
    '            for (int[] edge : adj.get(u)) {',
    '                int v = edge[0], w = edge[1];',
    '                if (p >= w && !vis[v][p - w] && c + w < dist[v][p - w]) {',
    '                    dist[v][p - w] = c + w;',
    '                    pq.offer(new Node(v, p - w, c + w));',
    '                }',
    '            }',
    '        }',
    '        return -1;',
    '    }',
    '}',
  ],
  python: [
    '# 电动车游历城市最小费用 (LeetCode LCP 35 / Python 标准实现)',
    '# 核心思想: 二维状态 (city, power) 分层图最短路',
    'import heapq',
    '',
    'class Solution:',
    '    def electricCarPlan(self, paths: list[list[int]], cnt: int, start: int, end: int, charge: list[int]) -> int:',
    '        n = len(charge)',
    '        adj = [[] for _ in range(n)]',
    '        for u, v, w in paths:',
    '            adj[u].append((v, w))',
    '            adj[v].append((u, w))',
    '            ',
    '        # dist[u][p] = 最小耗时/总费用',
    '        dist = [[float("inf")] * (cnt + 1) for _ in range(n)]',
    '        vis = [[False] * (cnt + 1) for _ in range(n)]',
    '        pq = []',
    '        ',
    '        dist[start][0] = 0',
    '        heapq.heappush(pq, (0, start, 0))  # (cost, city, power)',
    '        ',
    '        while pq:',
    '            cost, u, p = heapq.heappop(pq)',
    '            if vis[u][p]:',
    '                continue',
    '            vis[u][p] = True',
    '            if u == end:',
    '                return cost',
    '                ',
    '            # 决策 1: 原地充 1 格电',
    '            if p < cnt and not vis[u][p + 1] and cost + charge[u] < dist[u][p + 1]:',
    '                dist[u][p + 1] = cost + charge[u]',
    '                heapq.heappush(pq, (cost + charge[u], u, p + 1))',
    '                ',
    '            # 决策 2: 沿公路行驶放电',
    '            for v, w in adj[u]:',
    '                if p >= w and not vis[v][p - w] and cost + w < dist[v][p - w]:',
    '                    dist[v][p - w] = cost + w',
    '                    heapq.heappush(pq, (cost + w, v, p - w))',
    '                    ',
    '        return -1',
  ],
  javascript: [
    '/**',
    ' * 电动车充放电分层图最短路 (JavaScript 版)',
    ' * LeetCode LCP 35 标程',
    ' */',
    'function electricCarPlan(paths, cnt, start, end, charge) {',
    '  const n = charge.length;',
    '  const adj = Array.from({ length: n }, () => []);',
    '  for (const [u, v, w] of paths) {',
    '    adj[u].push([v, w]);',
    '    adj[v].push([u, w]);',
    '  }',
    '  ',
    '  const dist = Array.from({ length: n }, () => Array(cnt + 1).fill(Infinity));',
    '  const vis = Array.from({ length: n }, () => Array(cnt + 1).fill(false));',
    '  ',
    '  // 优先队列节点: [cost, city, power]',
    '  const pq = [[0, start, 0]];',
    '  dist[start][0] = 0;',
    '  ',
    '  while (pq.length > 0) {',
    '    pq.sort((a, b) => a[0] - b[0]);',
    '    const [cost, u, p] = pq.shift();',
    '    if (vis[u][p]) continue;',
    '    vis[u][p] = true;',
    '    if (u === end) return cost;',
    '    ',
    '    // 决策 1: 原地充 1 格电',
    '    if (p < cnt && !vis[u][p + 1] && cost + charge[u] < dist[u][p + 1]) {',
    '      dist[u][p + 1] = cost + charge[u];',
    '      pq.push([cost + charge[u], u, p + 1]);',
    '    }',
    '    ',
    '    // 决策 2: 沿公路行驶放电',
    '    for (const [v, w] of adj[u]) {',
    '      if (p >= w && !vis[v][p - w] && cost + w < dist[v][p - w]) {',
    '        dist[v][p - w] = cost + w;',
    '        pq.push([cost + w, v, p - w]);',
    '      }',
    '    }',
    '  }',
    '  return -1;',
    '}',
  ],
};

export const EV_CHARGE_PROBLEM_HTML = `
  <div style="font-size: 13px; line-height: 1.6; color: #334155;">
    <h3 style="margin-top: 0; color: #0f172a; font-size: 15px; font-weight: 800;">⚡ 电动车游历城市最小费用 (Electric Car Plan)</h3>
    <p>
      小明驾驶一辆最大电池容量为 $\\text{cnt}$ 的电动车从城市 $\\text{start}$ 出发前往 $\\text{end}$。在每个城市 $u$ 每充 1 格电需要耗时 $\\text{charge}[u]$，在道路 $(u, v, w)$ 行驶消耗 $w$ 格电且耗时 $w$。求到达终点的最短总时间（左程云 Class064 Code05 / LeetCode LCP 35）。
    </p>

    <div style="background: #f8fafc; border-left: 4px solid #3b82f6; padding: 8px 12px; margin: 10px 0; border-radius: 0 6px 6px 0;">
      <div style="font-weight: 700; color: #1e40af; margin-bottom: 4px;">🔋 $(u, \\text{power})$ 状态图分层松弛</div>
      <div style="font-size: 11.5px; color: #334155;">
        1. <b>原地充电转移</b>：$(u, p) \\xrightarrow{+\\text{charge}[u]} (u, p+1)$；<br/>
        2. <b>道路行驶转移</b>：$(u, p) \\xrightarrow{+w} (v, p-w)$（要求 $p \\ge w$）。
      </div>
    </div>
  </div>
`;

export const EV_CHARGE_ANALYSIS_HTML = `
  <div style="font-size: 13px; line-height: 1.6; color: #334155;">
    <h3 style="margin-top: 0; color: #0f172a; font-size: 15px; font-weight: 800;">💡 分层图模型在资源约束下的泛化</h3>

    <div style="background: #eff6ff; border: 1px solid #bfdbfe; border-radius: 6px; padding: 10px; margin-bottom: 12px;">
      <div style="font-weight: 700; color: #1e3a8a; margin-bottom: 4px;">1. 状态空间几何展开</div>
      <div style="font-size: 12px; color: #1e40af;">
        将每个物理城市拓展为 $\\text{cnt}+1$ 层（分别对应电量 $0 \\dots \\text{cnt}$）。充电是层内垂直上升边，行驶是跨城市的斜向下降边，从而将复杂的充放电决策转化为纯粹的静态最短路！
      </div>
    </div>

    <div style="background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 6px; padding: 10px;">
      <div style="font-weight: 700; color: #166534; margin-bottom: 4px;">2. 复杂度精细评估</div>
      <div style="font-size: 12px; color: #15803d;">
        总状态数 $V = N \\times (\\text{cnt}+1)$，总边数 $E = N \\times \\text{cnt} + M \\times (\\text{cnt}+1)$，优先队列 Dijkstra 运行时间为 $O(E \\log V)$，极速收敛！
      </div>
    </div>
  </div>
`;
