/**
 * 网络流最大权闭合子图 (Max-Weight Closure of Directed Graph)
 * 进阶网络流: 正权点连源点 S、负权点连汇点 T、依赖边容量无穷大、最大权 = 正权和 - 最小割 (洛谷 P2762)
 */

export const MAX_WEIGHT_CLOSURE_CODE_LANGUAGES: Record<string, string[]> = {
  cpp: [
    '#include <iostream>',
    '#include <vector>',
    '#include <queue>',
    '#include <numeric>',
    'using namespace std;',
    '',
    '// 最大权闭合子图 (洛谷 P2762 太空飞行计划问题)',
    '// 核心：S -> 正权点(收益)，负权点(成本) -> T，依赖边 inf，最大收益 = 总正权和 - 最小割',
    'class MaxWeightClosure {',
    'public:',
    '    struct Edge {',
    '        int to, cap, flow, rev;',
    '    };',
    '    ',
    '    int n, S, T;',
    '    vector<vector<Edge>> adj;',
    '    vector<int> level, cur;',
    '    int totalPositiveWeight = 0;',
    '    ',
    '    MaxWeightClosure(int n) : n(n), S(0), T(n + 1), adj(n + 2),',
    '                              level(n + 2, -1), cur(n + 2, 0) {}',
    '    ',
    '    void addEdge(int u, int v, int cap) {',
    '        int idxU = adj[u].size();',
    '        int idxV = adj[v].size();',
    '        adj[u].push_back({v, cap, 0, idxV});',
    '        adj[v].push_back({u, 0, 0, idxU});',
    '    }',
    '    ',
    '    void addNode(int u, int weight) {',
    '        if (weight > 0) {',
    '            totalPositiveWeight += weight;',
    '            addEdge(S, u, weight); // 正权点：连 S，容量为收益',
    '        } else if (weight < 0) {',
    '            addEdge(u, T, -weight); // 负权点：连 T，容量为成本',
    '        }',
    '    }',
    '    ',
    '    void addDependency(int u, int v) {',
    '        addEdge(u, v, 1e9); // 依赖关系：容量为无穷大 (不可割断)',
    '    }',
    '    ',
    '    bool bfs() {',
    '        fill(level.begin(), level.end(), -1);',
    '        queue<int> q;',
    '        q.push(S);',
    '        level[S] = 0;',
    '        while (!q.empty()) {',
    '            int u = q.front(); q.pop();',
    '            for (const auto& e : adj[u]) {',
    '                if (e.cap > e.flow && level[e.to] == -1) {',
    '                    level[e.to] = level[u] + 1;',
    '                    q.push(e.to);',
    '                }',
    '            }',
    '        }',
    '        return level[T] != -1;',
    '    }',
    '    ',
    '    int dfs(int u, int pushed) {',
    '        if (u == T || pushed == 0) return pushed;',
    '        for (int& cid = cur[u]; cid < (int)adj[u].size(); ++cid) {',
    '            auto& e = adj[u][cid];',
    '            int tr = e.to;',
    '            if (level[u] + 1 != level[tr] || e.cap <= e.flow) continue;',
    '            int trPushed = dfs(tr, min(pushed, e.cap - e.flow));',
    '            if (trPushed == 0) continue;',
    '            e.flow += trPushed;',
    '            adj[tr][e.rev].flow -= trPushed;',
    '            return trPushed;',
    '        }',
    '        return 0;',
    '    }',
    '    ',
    '    pair<int, vector<int>> solve() {',
    '        int minCut = 0;',
    '        while (bfs()) {',
    '            fill(cur.begin(), cur.end(), 0);',
    '            while (int pushed = dfs(S, 1e9)) minCut += pushed;',
    '        }',
    '        int maxProfit = totalPositiveWeight - minCut;',
    '        ',
    '        // 残量网络中与 S 连通的点即为闭合子图所选节点',
    '        vector<bool> vis(n + 2, false);',
    '        queue<int> q;',
    '        q.push(S);',
    '        vis[S] = true;',
    '        vector<int> chosenNodes;',
    '        while (!q.empty()) {',
    '            int u = q.front(); q.pop();',
    '            if (u >= 1 && u <= n) chosenNodes.push_back(u);',
    '            for (const auto& e : adj[u]) {',
    '                if (e.cap > e.flow && !vis[e.to]) {',
    '                    vis[e.to] = true;',
    '                    q.push(e.to);',
    '                }',
    '            }',
    '        }',
    '        return {maxProfit, chosenNodes};',
    '    }',
    '};',
  ],
  java: [
    'package advanced_flow;',
    '',
    'import java.util.*;',
    '',
    '// 最大权闭合子图标准实现 - Dinic 最小割与方案输出 (洛谷 P2762)',
    'public class Code01_MaxWeightClosure {',
    '    public static class Edge {',
    '        public int to, cap, flow, rev;',
    '        public Edge(int to, int cap, int flow, int rev) {',
    '            this.to = to;',
    '            this.cap = cap;',
    '            this.flow = flow;',
    '            this.rev = rev;',
    '        }',
    '    }',
    '',
    '    public static int n, S, T;',
    '    public static int totalPositiveWeight;',
    '    public static ArrayList<ArrayList<Edge>> adj;',
    '    public static int[] level, cur;',
    '',
    '    public static void init(int numNodes) {',
    '        n = numNodes;',
    '        S = 0;',
    '        T = n + 1;',
    '        totalPositiveWeight = 0;',
    '        adj = new ArrayList<>();',
    '        for (int i = 0; i < n + 2; i++) adj.add(new ArrayList<>());',
    '        level = new int[n + 2];',
    '        cur = new int[n + 2];',
    '    }',
    '',
    '    public static void addEdge(int u, int v, int cap) {',
    '        int idxU = adj.get(u).size();',
    '        int idxV = adj.get(v).size();',
    '        adj.get(u).add(new Edge(v, cap, 0, idxV));',
    '        adj.get(v).add(new Edge(u, 0, 0, idxU));',
    '    }',
    '',
    '    public static void addNode(int u, int weight) {',
    '        if (weight > 0) {',
    '            totalPositiveWeight += weight;',
    '            addEdge(S, u, weight); // 正权点：连 S，容量为收益',
    '        } else if (weight < 0) {',
    '            addEdge(u, T, -weight); // 负权点：连 T，容量为成本',
    '        }',
    '    }',
    '',
    '    public static void addDependency(int u, int v) {',
    '        addEdge(u, v, 1000000000); // 依赖关系：容量为无穷大 (不可割断)',
    '    }',
    '',
    '    public static boolean bfs() {',
    '        Arrays.fill(level, -1);',
    '        Queue<Integer> q = new LinkedList<>();',
    '        q.offer(S);',
    '        level[S] = 0;',
    '        while (!q.isEmpty()) {',
    '            int u = q.poll();',
    '            for (Edge e : adj.get(u)) {',
    '                if (e.cap > e.flow && level[e.to] == -1) {',
    '                    level[e.to] = level[u] + 1;',
    '                    q.offer(e.to);',
    '                }',
    '            }',
    '        }',
    '        return level[T] != -1;',
    '    }',
    '',
    '    public static int dfs(int u, int pushed) {',
    '        if (u == T || pushed == 0) return pushed;',
    '        for (int cid = cur[u]; cid < adj.get(u).size(); cid++) {',
    '            cur[u] = cid;',
    '            Edge e = adj.get(u).get(cid);',
    '            int tr = e.to;',
    '            if (level[u] + 1 != level[tr] || e.cap <= e.flow) continue;',
    '            int trPushed = dfs(tr, Math.min(pushed, e.cap - e.flow));',
    '            if (trPushed == 0) continue;',
    '            e.flow += trPushed;',
    '            adj.get(tr).get(e.rev).flow -= trPushed;',
    '            return trPushed;',
    '        }',
    '        return 0;',
    '    }',
    '',
    '    public static int solve() {',
    '        int minCut = 0;',
    '        while (bfs()) {',
    '            Arrays.fill(cur, 0);',
    '            int pushed;',
    '            while ((pushed = dfs(S, 1000000000)) > 0) {',
    '                minCut += pushed;',
    '            }',
    '        }',
    '        return totalPositiveWeight - minCut;',
    '    }',
    '',
    '    public static List<Integer> getChosenNodes() {',
    '        boolean[] vis = new boolean[n + 2];',
    '        Queue<Integer> q = new LinkedList<>();',
    '        q.offer(S);',
    '        vis[S] = true;',
    '        List<Integer> chosen = new ArrayList<>();',
    '        while (!q.isEmpty()) {',
    '            int u = q.poll();',
    '            if (u >= 1 && u <= n) chosen.add(u);',
    '            for (Edge e : adj.get(u)) {',
    '                if (e.cap > e.flow && !vis[e.to]) {',
    '                    vis[e.to] = true;',
    '                    q.offer(e.to);',
    '                }',
    '            }',
    '        }',
    '        return chosen;',
    '    }',
    '}',
  ],
  python: [
    'from collections import deque',
    '',
    'class MaxWeightClosure:',
    '    def __init__(self, n: int):',
    '        self.n = n',
    '        self.S = 0',
    '        self.T = n + 1',
    '        self.adj = [[] for _ in range(n + 2)]',
    '        self.level = [-1] * (n + 2)',
    '        self.cur = [0] * (n + 2)',
    '        self.total_positive = 0',
    '',
    '    def add_edge(self, u: int, v: int, cap: int):',
    '        idx_u = len(self.adj[u])',
    '        idx_v = len(self.adj[v])',
    '        self.adj[u].append([v, cap, 0, idx_v])',
    '        self.adj[v].append([u, 0, 0, idx_u])',
    '',
    '    def add_node(self, u: int, weight: int):',
    '        if weight > 0:',
    '            self.total_positive += weight',
    '            self.add_edge(self.S, u, weight)',
    '        elif weight < 0:',
    '            self.add_edge(u, self.T, -weight)',
    '',
    '    def add_dependency(self, u: int, v: int):',
    '        self.add_edge(u, v, float("inf"))',
    '',
    '    def bfs(self) -> bool:',
    '        self.level = [-1] * (self.n + 2)',
    '        self.level[self.S] = 0',
    '        q = deque([self.S])',
    '        while q:',
    '            u = q.popleft()',
    '            for to, cap, flow, _ in self.adj[u]:',
    '                if cap > flow and self.level[to] == -1:',
    '                    self.level[to] = self.level[u] + 1',
    '                    q.append(to)',
    '        return self.level[self.T] != -1',
    '',
    '    def dfs(self, u: int, pushed: float) -> float:',
    '        if u == self.T or pushed == 0:',
    '            return pushed',
    '        for cid in range(self.cur[u], len(self.adj.get(u))):',
    '            self.cur[u] = cid',
    '            to, cap, flow, rev = self.adj.get(u)[cid]',
    '            if self.level[u] + 1 != self.level[to] or cap <= flow:',
    '                continue',
    '            tr_pushed = self.dfs(to, min(pushed, cap - flow))',
    '            if tr_pushed == 0:',
    '                continue',
    '            self.adj.get(u)[cid][2] += tr_pushed',
    '            self.adj.get(to)[rev][2] -= tr_pushed',
    '            return tr_pushed',
    '        return 0',
    '',
    '    def solve(self) -> tuple[int, list[int]]:',
    '        min_cut = 0',
    '        while self.bfs():',
    '            self.cur = [0] * (self.n + 2)',
    '            while True:',
    '                pushed = self.dfs(self.S, float("inf"))',
    '                if pushed == 0:',
    '                    break',
    '                min_cut += pushed',
    '',
    '        max_profit = self.total_positive - min_cut',
    '        vis = [False] * (self.n + 2)',
    '        vis[self.S] = True',
    '        q = deque([self.S])',
    '        chosen = []',
    '        while q:',
    '            u = q.popleft()',
    '            if 1 <= u <= self.n:',
    '                chosen.append(u)',
    '            for to, cap, flow, _ in self.adj.get(u):',
    '                if cap > flow and not vis[to]:',
    '                    vis[to] = True',
    '                    q.append(to)',
    '        return max_profit, chosen',
  ],
  javascript: [
    '// 最大权闭合子图 (JavaScript 版) - Dinic 最小割建模',
    'class MaxWeightClosure {',
    '  constructor(n) {',
    '    this.n = n;',
    '    this.S = 0;',
    '    this.T = n + 1;',
    '    this.adj = Array.from({ length: n + 2 }, () => []);',
    '    this.level = Array(n + 2).fill(-1);',
    '    this.cur = Array(n + 2).fill(0);',
    '    this.totalPositive = 0;',
    '  }',
    '',
    '  addEdge(u, v, cap) {',
    '    const idxU = this.adj[u].length;',
    '    const idxV = this.adj[v].length;',
    '    this.adj[u].push({ to: v, cap, flow: 0, rev: idxV });',
    '    this.adj[v].push({ to: u, cap: 0, flow: 0, rev: idxU });',
    '  }',
    '',
    '  addNode(u, weight) {',
    '    if (weight > 0) {',
    '      this.totalPositive += weight;',
    '      this.addEdge(this.S, u, weight);',
    '    } else if (weight < 0) {',
    '      this.addEdge(u, this.T, -weight);',
    '    }',
    '  }',
    '',
    '  addDependency(u, v) {',
    '    this.addEdge(u, v, Infinity);',
    '  }',
    '',
    '  bfs() {',
    '    this.level.fill(-1);',
    '    this.level[this.S] = 0;',
    '    const q = [this.S];',
    '    while (q.length > 0) {',
    '      const u = q.shift();',
    '      for (const e of this.adj[u]) {',
    '        if (e.cap > e.flow && this.level[e.to] === -1) {',
    '          this.level[e.to] = this.level[u] + 1;',
    '          q.push(e.to);',
    '        }',
    '      } ',
    '    }',
    '    return this.level[this.T] !== -1;',
    '  }',
    '',
    '  dfs(u, pushed) {',
    '    if (u === this.T || pushed === 0) return pushed;',
    '    for (let cid = this.cur[u]; cid < this.adj[u].length; cid++) {',
    '      this.cur[u] = cid;',
    '      const e = this.adj[u][cid];',
    '      const tr = e.to;',
    '      if (this.level[u] + 1 !== this.level[tr] || e.cap <= e.flow) continue;',
    '      const trPushed = this.dfs(tr, Math.min(pushed, e.cap - e.flow));',
    '      if (trPushed === 0) continue;',
    '      e.flow += trPushed;',
    '      this.adj[tr][e.rev].flow -= trPushed;',
    '      return trPushed;',
    '    }',
    '    return 0;',
    '  }',
    '',
    '  solve() {',
    '    let minCut = 0;',
    '    while (this.bfs()) {',
    '      this.cur.fill(0);',
    '      let pushed;',
    '      while ((pushed = this.dfs(this.S, Infinity)) > 0) {',
    '        minCut += pushed;',
    '      }',
    '    }',
    '    const maxProfit = this.totalPositive - minCut;',
    '    const vis = Array(this.n + 2).fill(false);',
    '    vis[this.S] = true;',
    '    const q = [this.S];',
    '    const chosen = [];',
    '    while (q.length > 0) {',
    '      const u = q.shift();',
    '      if (u >= 1 && u <= this.n) chosen.push(u);',
    '      for (const e of this.adj[u]) {',
    '        if (e.cap > e.flow && !vis[e.to]) {',
    '          vis[e.to] = true;',
    '          q.push(e.to);',
    '        }',
    '      } ',
    '    }',
    '    return { maxProfit, chosen };',
    '  }',
    '}',
  ],
};

export const MAX_WEIGHT_CLOSURE_PROBLEM_HTML = `
  <div style="font-size: 13px; line-height: 1.6; color: #334155;">
    <h3 style="margin-top: 0; color: #0f172a; font-size: 15px; font-weight: 800;">💰 最大权闭合子图 (Max-Weight Closure)</h3>
    <p>
      有向图 $G=(V, E)$ 的<b>闭合子图</b>是指一个点集 $S \subseteq V$，若 $u \in S$ 且存在有向依赖边 $u \to v$，则必有 $v \in S$。求所有闭合子图中点权和的最大值（洛谷 P2762 太空飞行计划问题）。
    </p>

    <div style="background: #f8fafc; border-left: 4px solid #3b82f6; padding: 8px 12px; margin: 10px 0; border-radius: 0 6px 6px 0;">
      <div style="font-weight: 700; color: #1e40af; margin-bottom: 4px;">📐 最小割经典建图模型</div>
      <div style="font-size: 11.5px; color: #334155;">
        1. 建立超级源点 $S$ 和超级汇点 $T$；<br/>
        2. 对正权点 $u$ ($w_u > 0$)：连边 $S \to u$，容量为 $w_u$（割断代表放弃该收益）；<br/>
        3. 对负权点 $v$ ($w_v < 0$)：连边 $v \to T$，容量为 $-w_v$（割断代表支付该成本）；<br/>
        4. 对原图依赖边 $u \to v$：连边 $u \to v$，容量为 $\\infty$（强依赖不可割断）。
      </div>
    </div>
  </div>
`;

export const MAX_WEIGHT_CLOSURE_ANALYSIS_HTML = `
  <div style="font-size: 13px; line-height: 1.6; color: #334155;">
    <h3 style="margin-top: 0; color: #0f172a; font-size: 15px; font-weight: 800;">💡 最大净收益定理与最优方案提取</h3>

    <div style="background: #eff6ff; border: 1px solid #bfdbfe; border-radius: 6px; padding: 10px; margin-bottom: 12px;">
      <div style="font-weight: 700; color: #1e3a8a; margin-bottom: 4px;">1. 最大权计算公式</div>
      <div style="font-size: 12px; color: #1e40af;">
        $$\\text{MaxProfit} = \\sum_{w_u > 0} w_u - \\text{MinCut}$$
        最小割恰好对应了“放弃的所有正权收益 + 支付的所有负权成本”的最小值！
      </div>
    </div>

    <div style="background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 6px; padding: 10px;">
      <div style="font-weight: 700; color: #166534; margin-bottom: 4px;">2. 方案提取定理</div>
      <div style="font-size: 12px; color: #15803d;">
        在最终残量网络中，从源点 $S$ 出发沿着还有正向剩余容量 $(cap > flow)$ 的边能够访问到的所有节点集合，恰好构成全局最优闭合子图！
      </div>
    </div>
  </div>
`;
