/**
 * 最小均值回路与分数规划 (Minimum Mean Weight Cycle - Karp's Algorithm)
 * 进阶图论: 0-1 分数规划、边权重赋权 w'(e) = w(e) - lambda、SPFA 负环判定、二分逼近 (洛谷 P2868)
 */

export const MIN_MEAN_CYCLE_CODE_LANGUAGES: Record<string, string[]> = {
  cpp: [
    '#include <iostream>',
    '#include <vector>',
    '#include <queue>',
    'using namespace std;',
    '',
    '// 最小均值回路 (0-1 分数规划 + SPFA 判负环)',
    '// 核心：二分均值 lambda，边权赋为 w - lambda，检测负权回路',
    'class MinMeanCycle {',
    'public:',
    '    struct Edge { int to; double w; };',
    '    int n;',
    '    vector<vector<Edge>> adj;',
    '    ',
    '    MinMeanCycle(int n) : n(n), adj(n + 1) {}',
    '    ',
    '    void addEdge(int u, int v, double w) {',
    '        adj[u].push_back({v, w});',
    '    }',
    '    ',
    '    // 检查当均值为 lambda 时是否存在负环',
    '    bool hasNegativeCycle(double lambda) {',
    '        vector<double> dist(n + 1, 0);',
    '        vector<int> count(n + 1, 0);',
    '        vector<bool> inQueue(n + 1, true);',
    '        queue<int> q;',
    '        ',
    '        for (int i = 1; i <= n; ++i) q.push(i);',
    '        ',
    '        while (!q.empty()) {',
    '            int u = q.front(); q.pop();',
    '            inQueue[u] = false;',
    '            ',
    '            for (const auto& edge : adj[u]) {',
    '                int v = edge.to;',
    '                double newW = edge.w - lambda;',
    '                if (dist[u] + newW < dist[v]) {',
    '                    dist[v] = dist[u] + newW;',
    '                    count[v] = count[u] + 1;',
    '                    if (count[v] >= n) return true; // 存在负环',
    '                    if (!inQueue[v]) {',
    '                        q.push(v);',
    '                        inQueue[v] = true;',
    '                    }',
    '                }',
    '            }',
    '        }',
    '        return false;',
    '    }',
    '    ',
    '    double findMinMeanCycle() {',
    '        double l = -1e4, r = 1e4;',
    '        for (int iter = 0; iter < 60; ++iter) {',
    '            double mid = (l + r) / 2.0;',
    '            if (hasNegativeCycle(mid)) {',
    '                r = mid; // 存在负环，说明最小均值 <= mid',
    '            } else {',
    '                l = mid;',
    '            }',
    '        }',
    '        return l;',
    '    }',
    '};',
  ],
  java: [
    'package advanced_graph;',
    '',
    'import java.util.*;',
    '',
    '// 最小均值回路 (0-1 分数规划 + SPFA 判负环)',
    '// 核心思想：二分猜测平均权值 lambda，边权重赋权 w\'(e) = w(e) - lambda',
    '// 若重权图存在负权回路，说明真实最小均值 <= lambda，收缩右界；否则提高左界。',
    'public class Code01_MinMeanCycle {',
    '',
    '    static class Edge {',
    '        int to;',
    '        double w;',
    '        Edge(int to, double w) { this.to = to; this.w = w; }',
    '    }',
    '',
    '    public static int n;',
    '    public static List<List<Edge>> adj;',
    '',
    '    // SPFA 检验当二分均值为 lambda 时，图中是否存在负权回路',
    '    public static boolean hasNegativeCycle(double lambda) {',
    '        double[] dist = new double[n + 1];',
    '        int[] count = new int[n + 1];',
    '        boolean[] inQueue = new boolean[n + 1];',
    '        Queue<Integer> queue = new ArrayDeque<>();',
    '',
    '        // 超级源点初始化：全部节点入队',
    '        for (int i = 1; i <= n; i++) {',
    '            queue.offer(i);',
    '            inQueue[i] = true;',
    '        }',
    '',
    '        while (!queue.isEmpty()) {',
    '            int u = queue.poll();',
    '            inQueue[u] = false;',
    '',
    '            for (Edge e : adj.get(u)) {',
    '                int v = e.to;',
    '                double newW = e.w - lambda;',
    '                if (dist[u] + newW < dist[v] - 1e-9) {',
    '                    dist[v] = dist[u] + newW;',
    '                    count[v] = count[u] + 1;',
    '                    if (count[v] >= n) {',
    '                        return true; // 存在负权回路',
    '                    }',
    '                    if (!inQueue[v]) {',
    '                        queue.offer(v);',
    '                        inQueue[v] = true;',
    '                    }',
    '                }',
    '            }',
    '        }',
    '        return false;',
    '    }',
    '',
    '    // 二分搜索最小均值回路的平均边权',
    '    public static double findMinMeanCycle(int numNodes, double[][] edges) {',
    '        n = numNodes;',
    '        adj = new ArrayList<>();',
    '        for (int i = 0; i <= n; i++) adj.add(new ArrayList<>());',
    '        for (double[] e : edges) {',
    '            adj.get((int) e[0]).add(new Edge((int) e[1], e[2]));',
    '        }',
    '',
    '        double l = 0.0, r = 5.0;',
    '        for (int iter = 0; iter < 40; iter++) {',
    '            double mid = (l + r) / 2.0;',
    '            if (hasNegativeCycle(mid)) {',
    '                r = mid; // 存在负环，说明真实最小均值 <= mid',
    '            } else {',
    '                l = mid; // 无负环，说明真实最小均值 >= mid',
    '            }',
    '        }',
    '        return l;',
    '    }',
    '}',
  ],
  python: [
    'from collections import deque',
    '',
    '# 最小均值回路 (0-1 分数规划 + SPFA Python 版)',
    'def has_negative_cycle(n, adj, lmbda):',
    '    dist = [0.0] * (n + 1)',
    '    count = [0] * (n + 1)',
    '    in_q = [True] * (n + 1)',
    '    q = deque(range(1, n + 1))',
    '    while q:',
    '        u = q.popleft()',
    '        in_q[u] = False',
    '        for v, w in adj[u]:',
    '            new_w = w - lmbda',
    '            if dist[u] + new_w < dist[v] - 1e-9:',
    '                dist[v] = dist[u] + new_w',
    '                count[v] = count[u] + 1',
    '                if count[v] >= n: return True',
    '                if not in_q[v]:',
    '                    q.append(v)',
    '                    in_q[v] = True',
    '    return False',
    '',
    'def min_mean_cycle(n, edges):',
    '    adj = [[] for _ in range(n + 1)]',
    '    for u, v, w in edges: adj[u].append((v, w))',
    '    l, r = 0.0, 5.0',
    '    for _ in range(40):',
    '        mid = (l + r) / 2.0',
    '        if has_negative_cycle(n, adj, mid): r = mid',
    '        else: l = mid',
    '    return l',
  ],
  javascript: [
    '// 最小均值回路 (0-1 分数规划 + SPFA JavaScript 版)',
    'function hasNegativeCycle(n, adj, lambda) {',
    '  const dist = new Array(n + 1).fill(0);',
    '  const count = new Array(n + 1).fill(0);',
    '  const inQueue = new Array(n + 1).fill(true);',
    '  const q = [];',
    '  for (let i = 1; i <= n; i++) q.push(i);',
    '  while (q.length > 0) {',
    '    const u = q.shift();',
    '    inQueue[u] = false;',
    '    for (const [v, w] of adj[u]) {',
    '      const newW = w - lambda;',
    '      if (dist[u] + newW < dist[v] - 1e-9) {',
    '        dist[v] = dist[u] + newW;',
    '        count[v] = count[u] + 1;',
    '        if (count[v] >= n) return true;',
    '        if (!inQueue[v]) { q.push(v); inQueue[v] = true; }',
    '      }',
    '    }',
    '  }',
    '  return false;',
    '}',
    '',
    'function minMeanCycle(n, edges) {',
    '  const adj = Array.from({ length: n + 1 }, () => []);',
    '  edges.forEach(([u, v, w]) => adj[u].push([v, w]));',
    '  let l = 0.0, r = 5.0;',
    '  for (let iter = 0; iter < 40; iter++) {',
    '    const mid = (l + r) / 2.0;',
    '    if (hasNegativeCycle(n, adj, mid)) r = mid;',
    '    else l = mid;',
    '  }',
    '  return l;',
    '}',
  ],
};

export const MIN_MEAN_CYCLE_PROBLEM_HTML = `
  <div style="font-size: 13px; line-height: 1.6; color: #334155;">
    <h3 style="margin-top: 0; color: #0f172a; font-size: 15px; font-weight: 800;">🔄 最小均值回路 (Minimum Mean Weight Cycle)</h3>
    <p>
      给定带权有向图 $G = (V, E)$，在图中寻找一个有向环 $C$，使其平均边权 $\\frac{\\sum_{e \\in C} w(e)}{|C|}$ 达到全局最小 $\\lambda^*$（0-1 分数规划 / 洛谷 P2868）。
    </p>

    <div style="background: #f8fafc; border-left: 4px solid #3b82f6; padding: 8px 12px; margin: 10px 0; border-radius: 0 6px 6px 0;">
      <div style="font-weight: 700; color: #1e40af; margin-bottom: 4px;">⚡ 0-1 分数规划转化</div>
      <div style="font-size: 11.5px; color: #334155;">
        $$\\frac{\\sum w(e)}{|C|} < \\lambda \\iff \\sum_{e \\in C} (w(e) - \\lambda) < 0$$
        将每条边的权值重新映射为 $w'(e) = w(e) - \\lambda$，原问题等价于判断新图上是否存在<b>负权回路（Negative Cycle）</b>！
      </div>
    </div>
  </div>
`;

export const MIN_MEAN_CYCLE_ANALYSIS_HTML = `
  <div style="font-size: 13px; line-height: 1.6; color: #334155;">
    <h3 style="margin-top: 0; color: #0f172a; font-size: 15px; font-weight: 800;">💡 二分单调性与负环收敛</h3>

    <div style="background: #eff6ff; border: 1px solid #bfdbfe; border-radius: 6px; padding: 10px; margin-bottom: 12px;">
      <div style="font-weight: 700; color: #1e3a8a; margin-bottom: 4px;">1. 单调判别性</div>
      <div style="font-size: 12px; color: #1e40af;">
        若当猜测值为 $\\lambda$ 时存在负环，说明图中必定存在平均权值更小的回路（$\\lambda^* < \\lambda$），于是将搜索上界收缩为 $\\lambda$；若无负环，则提高下界。
      </div>
    </div>

    <div style="background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 6px; padding: 10px;">
      <div style="font-weight: 700; color: #166534; margin-bottom: 4px;">2. 严格多项式 Karp 算法扩展</div>
      <div style="font-size: 12px; color: #15803d;">
        除了 0-1 分数规划二分外，Karp 算法利用动态规划记录 $k$ 条边的最短路矩阵 $F_k(v)$，可在严格 $O(V \\cdot E)$ 时间内精确求出最小均值回路。
      </div>
    </div>
  </div>
`;
