/**
 * 混合图欧拉回路与网络流定向 (Mixed Graph Eulerian Circuit - POJ 1637)
 * 进阶网络流建模: 任意初始定向、度数差额 D[u]=in[u]-out[u]、Dinic 最大流调整方向、满流判定 (POJ 1637)
 */

export const MIXED_EULER_CODE_LANGUAGES: Record<string, string[]> = {
  cpp: [
    '#include <iostream>',
    '#include <vector>',
    '#include <queue>',
    '#include <algorithm>',
    'using namespace std;',
    '',
    '// 混合图欧拉回路 (POJ 1637 Sightseeing tour / Dinic 最大流建模)',
    '// 核心：任意初始定向无向边，计算出入度差额 D[u] = in[u] - out[u]',
    'class MixedGraphEulerian {',
    'public:',
    '    struct Edge { int to, cap, flow, rev, id; };',
    '    int n, S, T;',
    '    vector<vector<Edge>> adj;',
    '    vector<int> level, ptr, degIn, degOut;',
    '    ',
    '    MixedGraphEulerian(int n) : n(n), S(0), T(n + 1),',
    '                                adj(n + 2), level(n + 2), ptr(n + 2),',
    '                                degIn(n + 1, 0), degOut(n + 1, 0) {}',
    '    ',
    '    void addDirectedEdge(int u, int v) {',
    '        degOut[u]++; degIn[v]++;',
    '    }',
    '    ',
    '    void addUndirectedEdge(int u, int v, int edgeId) {',
    '        degOut[u]++; degIn[v]++;',
    '        adj[u].push_back({v, 1, 0, (int)adj[v].size(), edgeId});',
    '        adj[v].push_back({u, 0, 0, (int)adj[u].size() - 1, -1});',
    '    }',
    '    ',
    '    bool bfs() {',
    '        fill(level.begin(), level.end(), -1);',
    '        level[S] = 0;',
    '        queue<int> q;',
    '        q.push(S);',
    '        while (!q.empty()) {',
    '            int u = q.front(); q.pop();',
    '            for (const auto& e : adj[u]) {',
    '                if (e.cap - e.flow > 0 && level[e.to] == -1) {',
    '                    level[e.to] = level[u] + 1;',
    '                    q.push(e.to);',
    '                }',
    '            }',
    '        }',
    '        return level[T] != -1;',
    '    }',
    '    ',
    '    int dfs(int u, int pushed) {',
    '        if (pushed == 0 || u == T) return pushed;',
    '        for (int& cid = ptr[u]; cid < (int)adj[u].size(); ++cid) {',
    '            auto& e = adj[u][cid];',
    '            if (level[e.to] == level[u] + 1 && e.cap - e.flow > 0) {',
    '                int tr = dfs(e.to, min(pushed, e.cap - e.flow));',
    '                if (tr > 0) {',
    '                    e.flow += tr;',
    '                    adj[e.to][e.rev].flow -= tr;',
    '                    return tr;',
    '                }',
    '            }',
    '        }',
    '        return 0;',
    '    }',
    '    ',
    '    int dinic() {',
    '        int flow = 0;',
    '        while (bfs()) {',
    '            fill(ptr.begin(), ptr.end(), 0);',
    '            while (int pushed = dfs(S, 1e9)) flow += pushed;',
    '        }',
    '        return flow;',
    '    }',
    '    ',
    '    bool solveEulerCircuit() {',
    '        int sumFlowNeed = 0;',
    '        for (int u = 1; u <= n; ++u) {',
    '            int diff = degIn[u] - degOut[u];',
    '            if (diff % 2 != 0) return false; // 奇偶性不符，必无解',
    '            if (diff > 0) {',
    '                adj[S].push_back({u, diff / 2, 0, (int)adj[u].size(), -1});',
    '                adj[u].push_back({S, 0, 0, (int)adj[S].size() - 1, -1});',
    '                sumFlowNeed += diff / 2;',
    '            } else if (diff < 0) {',
    '                adj[u].push_back({T, -diff / 2, 0, (int)adj[T].size(), -1});',
    '                adj[T].push_back({u, 0, 0, (int)adj[u].size() - 1, -1});',
    '            }',
    '        }',
    '        return dinic() == sumFlowNeed;',
    '    }',
    '};',
  ],
  java: [
    'package advanced_network_flow;',
    '',
    'import java.util.*;',
    '',
    '// 混合图欧拉回路 (POJ 1637 Sightseeing tour)',
    '// 网络流建模：任意初始定向无向边，计算度数差额 D[u] = in[u] - out[u]',
    '// 若存在 D[u] % 2 != 0 则直接无解；',
    '// D[u] > 0 时建源边 S -> u (容量 D[u] / 2)；D[u] < 0 时建汇边 u -> T (容量 -D[u] / 2)',
    '// 对每条可反向边连容量 1 的网络流边，Dinic 求解最大流判断是否满流。',
    'public class Code01_MixedGraphEulerian {',
    '',
    '    public static class Edge {',
    '        public int to;',
    '        public int cap;',
    '        public int flow;',
    '        public int rev;',
    '        public int originalEdgeId;',
    '',
    '        public Edge(int to, int cap, int rev, int originalEdgeId) {',
    '            this.to = to;',
    '            this.cap = cap;',
    '            this.flow = 0;',
    '            this.rev = rev;',
    '            this.originalEdgeId = originalEdgeId;',
    '        }',
    '    }',
    '',
    '    public static int n;',
    '    public static int S, T;',
    '    public static List<List<Edge>> adj;',
    '    public static int[] level;',
    '    public static int[] ptr;',
    '    public static int[] degIn;',
    '    public static int[] degOut;',
    '',
    '    public static void addEdge(int from, int to, int cap, int edgeId) {',
    '        Edge a = new Edge(to, cap, adj.get(to).size(), edgeId);',
    '        Edge b = new Edge(from, 0, adj.get(from).size(), -1);',
    '        adj.get(from).add(a);',
    '        adj.get(to).add(b);',
    '    }',
    '',
    '    public static boolean bfs() {',
    '        Arrays.fill(level, -1);',
    '        level[S] = 0;',
    '        Queue<Integer> q = new ArrayDeque<>();',
    '        q.offer(S);',
    '',
    '        while (!q.isEmpty()) {',
    '            int u = q.poll();',
    '            for (Edge e : adj.get(u)) {',
    '                if (e.cap - e.flow > 0 && level[e.to] == -1) {',
    '                    level[e.to] = level[u] + 1;',
    '                    q.offer(e.to);',
    '                }',
    '            }',
    '        }',
    '        return level[T] != -1;',
    '    }',
    '',
    '    public static int dfs(int u, int pushed) {',
    '        if (pushed == 0 || u == T) return pushed;',
    '        for (; ptr[u] < adj.get(u).size(); ptr[u]++) {',
    '            Edge e = adj.get(u).get(ptr[u]);',
    '            if (level[e.to] == level[u] + 1 && e.cap - e.flow > 0) {',
    '                int tr = dfs(e.to, Math.min(pushed, e.cap - e.flow));',
    '                if (tr > 0) {',
    '                    e.flow += tr;',
    '                    adj.get(e.to).get(e.rev).flow -= tr;',
    '                    return tr;',
    '                }',
    '            }',
    '        }',
    '        return 0;',
    '    }',
    '',
    '    public static int dinic() {',
    '        int flow = 0;',
    '        while (bfs()) {',
    '            Arrays.fill(ptr, 0);',
    '            while (true) {',
    '                int pushed = dfs(S, Integer.MAX_VALUE);',
    '                if (pushed == 0) break;',
    '                flow += pushed;',
    '            }',
    '        }',
    '        return flow;',
    '    }',
    '',
    '    // 求解混合图是否存在欧拉回路',
    '    public static boolean solve(int numNodes, int[][] directedEdges, int[][] undirectedEdges) {',
    '        n = numNodes;',
    '        S = 0;',
    '        T = n + 1;',
    '        adj = new ArrayList<>();',
    '        for (int i = 0; i <= T; i++) adj.add(new ArrayList<>());',
    '        level = new int[T + 1];',
    '        ptr = new int[T + 1];',
    '        degIn = new int[n + 1];',
    '        degOut = new int[n + 1];',
    '',
    '        // 1. 统计有向边',
    '        for (int[] e : directedEdges) {',
    '            degOut[e[0]]++;',
    '            degIn[e[1]]++;',
    '        }',
    '',
    '        // 2. 任意初始定向无向边 u -> v 并加网络流边',
    '        int edgeId = 0;',
    '        for (int[] e : undirectedEdges) {',
    '            degOut[e[0]]++;',
    '            degIn[e[1]]++;',
    '            addEdge(e[0], e[1], 1, edgeId++);',
    '        }',
    '',
    '        // 3. 计算度数差额并向源汇连边',
    '        int sumFlowNeed = 0;',
    '        for (int u = 1; u <= n; u++) {',
    '            int diff = degIn[u] - degOut[u];',
    '            if (diff % 2 != 0) return false;',
    '            if (diff > 0) {',
    '                addEdge(S, u, diff / 2, -1);',
    '                sumFlowNeed += diff / 2;',
    '            } else if (diff < 0) {',
    '                addEdge(u, T, -diff / 2, -1);',
    '            }',
    '        }',
    '',
    '        // 4. 跑 Dinic 求解最大流',
    '        int maxFlow = dinic();',
    '        return maxFlow == sumFlowNeed;',
    '    }',
    '}',
  ],
  python: [
    '# 混合图欧拉回路 (POJ 1637 Dinic 网络流版)',
    'from collections import deque',
    '',
    'def check_mixed_euler(n, directed_edges, undirected_edges):',
    '    S = 0',
    '    T = n + 1',
    '    adj = [[] for _ in range(T + 1)]',
    '    deg_in = [0] * (n + 1)',
    '    deg_out = [0] * (n + 1)',
    '    ',
    '    def add_edge(u, v, cap):',
    '        adj[u].append([v, cap, 0, len(adj[v])])',
    '        adj[v].append([u, 0, 0, len(adj[u]) - 1])',
    '    ',
    '    for u, v in directed_edges:',
    '        deg_out[u] += 1',
    '        deg_in[v] += 1',
    '    ',
    '    for u, v in undirected_edges:',
    '        deg_out[u] += 1',
    '        deg_in[v] += 1',
    '        add_edge(u, v, 1)',
    '    ',
    '    sum_flow_need = 0',
    '    for u in range(1, n + 1):',
    '        diff = deg_in[u] - deg_out[u]',
    '        if diff % 2 != 0:',
    '            return False',
    '        if diff > 0:',
    '            add_edge(S, u, diff // 2)',
    '            sum_flow_need += diff // 2',
    '        elif diff < 0:',
    '            add_edge(u, T, -diff // 2)',
    '    ',
    '    def bfs(level):',
    '        for i in range(T + 1): level[i] = -1',
    '        level[S] = 0',
    '        q = deque([S])',
    '        while q:',
    '            u = q.popleft()',
    '            for to, cap, flow, rev in adj[u]:',
    '                if cap - flow > 0 and level[to] == -1:',
    '                    level[to] = level[u] + 1',
    '                    q.append(to)',
    '        return level[T] != -1',
    '    ',
    '    def dfs(u, pushed, level, ptr):',
    '        if pushed == 0 or u == T: return pushed',
    '        while ptr[u] < len(adj[u]):',
    '            e = adj[u][ptr[u]]',
    '            to, cap, flow, rev = e',
    '            if level[to] == level[u] + 1 and cap - flow > 0:',
    '                tr = dfs(to, min(pushed, cap - flow), level, ptr)',
    '                if tr > 0:',
    '                    e[2] += tr',
    '                    adj[to][rev][2] -= tr',
    '                    return tr',
    '            ptr[u] += 1',
    '        return 0',
    '    ',
    '    level = [-1] * (T + 1)',
    '    total_flow = 0',
    '    while bfs(level):',
    '        ptr = [0] * (T + 1)',
    '        while True:',
    '            pushed = dfs(S, float("inf"), level, ptr)',
    '            if pushed == 0: break',
    '            total_flow += pushed',
    '    ',
    '    return total_flow == sum_flow_need',
  ],
  javascript: [
    '// 混合图欧拉回路 (JavaScript Dinic 版)',
    'function checkMixedEuler(n, directedEdges, undirectedEdges) {',
    '  const S = 0, T = n + 1;',
    '  const adj = Array.from({ length: T + 1 }, () => []);',
    '  const degIn = new Array(n + 1).fill(0);',
    '  const degOut = new Array(n + 1).fill(0);',
    '  ',
    '  function addEdge(u, v, cap) {',
    '    adj[u].push({ to: v, cap, flow: 0, rev: adj[v].length });',
    '    adj[v].push({ to: u, cap: 0, flow: 0, rev: adj[u].length - 1 });',
    '  }',
    '  ',
    '  for (const [u, v] of directedEdges) {',
    '    degOut[u]++; degIn[v]++;',
    '  }',
    '  for (const [u, v] of undirectedEdges) {',
    '    degOut[u]++; degIn[v]++;',
    '    addEdge(u, v, 1);',
    '  }',
    '  ',
    '  let sumFlowNeed = 0;',
    '  for (let u = 1; u <= n; u++) {',
    '    const diff = degIn[u] - degOut[u];',
    '    if (diff % 2 !== 0) return false;',
    '    if (diff > 0) {',
    '      addEdge(S, u, Math.floor(diff / 2));',
    '      sumFlowNeed += Math.floor(diff / 2);',
    '    } else if (diff < 0) {',
    '      addEdge(u, T, Math.floor(-diff / 2));',
    '    }',
    '  }',
    '  ',
    '  const level = new Array(T + 1);',
    '  function bfs() {',
    '    level.fill(-1);',
    '    level[S] = 0;',
    '    const q = [S];',
    '    while (q.length > 0) {',
    '      const u = q.shift();',
    '      for (const e of adj[u]) {',
    '        if (e.cap - e.flow > 0 && level[e.to] === -1) {',
    '          level[e.to] = level[u] + 1;',
    '          q.push(e.to);',
    '        }',
    '      }',
    '    }',
    '    return level[T] !== -1;',
    '  }',
    '  ',
    '  const ptr = new Array(T + 1);',
    '  function dfs(u, pushed) {',
    '    if (pushed === 0 || u === T) return pushed;',
    '    for (; ptr[u] < adj[u].length; ptr[u]++) {',
    '      const e = adj[u][ptr[u]];',
    '      if (level[e.to] === level[u] + 1 && e.cap - e.flow > 0) {',
    '        const tr = dfs(e.to, Math.min(pushed, e.cap - e.flow));',
    '        if (tr > 0) {',
    '          e.flow += tr;',
    '          adj[e.to][e.rev].flow -= tr;',
    '          return tr;',
    '        }',
    '      }',
    '    }',
    '    return 0;',
    '  }',
    '  ',
    '  let totalFlow = 0;',
    '  while (bfs()) {',
    '    ptr.fill(0);',
    '    while (true) {',
    '      const pushed = dfs(S, Infinity);',
    '      if (pushed === 0) break;',
    '      totalFlow += pushed;',
    '    }',
    '  }',
    '  return totalFlow === sumFlowNeed;',
    '}',
  ],
};

export const MIXED_EULER_PROBLEM_HTML = `
  <div style="font-size: 13px; line-height: 1.6; color: #334155;">
    <h3 style="margin-top: 0; color: #0f172a; font-size: 15px; font-weight: 800;">🔄 混合图欧拉回路 (Mixed Graph Eulerian Circuit)</h3>
    <p>
      在混合图中，既包含固定方向的<b>有向边</b>，又包含可自由定向的<b>无向边</b>。要求为每条无向边确定一个合法方向，使得整张图存在一条遍历所有边且方向严格一致的<b>欧拉回路</b>（POJ 1637 Sightseeing tour）。
    </p>

    <div style="background: #f8fafc; border-left: 4px solid #3b82f6; padding: 8px 12px; margin: 10px 0; border-radius: 0 6px 6px 0;">
      <div style="font-weight: 700; color: #1e40af; margin-bottom: 4px;">⚡ 网络流转化三部曲</div>
      <div style="font-size: 11.5px; color: #334155;">
        1. <b>任意初始定向</b>：将无向边 $u - v$ 假定为 $u \\to v$；<br/>
        2. <b>差额与奇偶判定</b>：若存在 $D[u] = in[u] - out[u]$ 为奇数，直接无解；<br/>
        3. <b>最大流分配</b>：$D[u]>0$ 连 $S \\to u$ 容量 $D/2$；$D[u]<0$ 连 $u \\to T$ 容量 $-D/2$。若满流则欧拉回路存在！
      </div>
    </div>
  </div>
`;

export const MIXED_EULER_ANALYSIS_HTML = `
  <div style="font-size: 13px; line-height: 1.6; color: #334155;">
    <h3 style="margin-top: 0; color: #0f172a; font-size: 15px; font-weight: 800;">💡 为什么一条边反向改变度数差 2？</h3>

    <div style="background: #eff6ff; border: 1px solid #bfdbfe; border-radius: 6px; padding: 10px; margin-bottom: 12px;">
      <div style="font-weight: 700; color: #1e3a8a; margin-bottom: 4px;">1. 翻转效应</div>
      <div style="font-size: 12px; color: #1e40af;">
        将一条原本 $u \\to v$ 的边翻转为 $v \\to u$ 时：$u$ 点出度 $-1$、入度 $+1$，差额 $D[u] = in[u]-out[u]$ 增加 $+2$；同时 $D[v]$ 减少 $-2$。每次网络流单位流量流动，恰好对应一次边反转！
      </div>
    </div>

    <div style="background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 6px; padding: 10px;">
      <div style="font-weight: 700; color: #166534; margin-bottom: 4px;">2. 完美闭环判定</div>
      <div style="font-size: 12px; color: #15803d;">
        当最大流等于所有正差额之和 $\\sum_{D[u]>0} \\frac{D[u]}{2}$ 时，所有节点入度与出度被完全调平（$in[u] = out[u]$），欧拉回路必定存在！
      </div>
    </div>
  </div>
`;
