/**
 * 前缀优化建图与线性边数压缩 (Prefix Optimization Graph Building)
 * 进阶图论: 至多选一限制、朴素 O(k^2) 边数爆炸、前缀链辅助点、O(k) 线性边数极致压缩 (洛谷 P6378 [PA2010] Riddle)
 */

export const PREFIX_OPT_CODE_LANGUAGES: Record<string, string[]> = {
  cpp: [
    '#include <iostream>',
    '#include <vector>',
    'using namespace std;',
    '',
    '// 前缀优化建图 (Prefix Optimization Graph Building)',
    '// 解决区间至多选一 / 区间连边时的 O(k^2) 边数爆炸问题',
    '// 核心思想：引入前缀辅助链 P_1 -> P_2 -> ... -> P_n，将两两连边压缩至严格 O(k) 线性边数',
    'class PrefixOptimizationGraph {',
    'public:',
    '    int n;             // 实体节点数',
    '    int totalNodes;    // 实体节点 + 前缀虚点总数',
    '    vector<vector<int>> adj;',
    '    int edgeCount = 0;',
    '    ',
    '    PrefixOptimizationGraph(int n) : n(n), totalNodes(2 * n), adj(2 * n + 1) {}',
    '    ',
    '    void addDirectedEdge(int u, int v) {',
    '        adj[u].push_back(v);',
    '        edgeCount++;',
    '    }',
    '    ',
    '    // 1. 建立前缀辅助链 (编号: 实体点 1..n, 前缀点 P_i 为 n + i)',
    '    void buildPrefixChain() {',
    '        for (int i = 1; i <= n; ++i) {',
    '            int pi = n + i;',
    '            // P_i -> u_i: 前缀虚点向对应实体点连边 (下垂透传)',
    '            addDirectedEdge(pi, i);',
    '            // P_i -> P_{i-1}: 前缀级联边 (向左前向覆盖)',
    '            if (i > 1) {',
    '                addDirectedEdge(pi, pi - 1);',
    '            }',
    '        }',
    '    }',
    '    ',
    '    // 2. 区间优化连边: 外部节点 src 向区间 [1, r] 连边',
    '    // 朴素建图需要 r 条边，优化后仅需连接 1 条边: src -> P_r',
    '    void addRangeEdge(int src, int r) {',
    '        if (r >= 1 && r <= n) {',
    '            int pr = n + r;',
    '            addDirectedEdge(src, pr);',
    '        }',
    '    }',
    '    ',
    '    // 3. 2-SAT 经典至多选一约束 (At Most One True)',
    '    // vars 为布尔变量列表，通过前缀链实现 O(k) 边数的两两互斥限制',
    '    void buildAtMostOne2SAT(const vector<int>& vars, const vector<int>& pre) {',
    '        int k = vars.size();',
    '        for (int i = 0; i < k; ++i) {',
    '            int u = vars[i];',
    '            addDirectedEdge(u, pre[i]);',
    '            if (i > 0) {',
    '                addDirectedEdge(pre[i - 1], pre[i]);',
    '                addDirectedEdge(u, pre[i - 1] ^ 1); // 选 u 则前缀全不能选',
    '            }',
    '        }',
    '    }',
    '};',
  ],
  java: [
    'package advanced_graph;',
    '',
    'import java.util.*;',
    '',
    '// 前缀优化建图 (Prefix Optimization Graph Building)',
    '// 解决区间至多选一 / 区间连边时的 O(k^2) 边数爆炸问题',
    '// 核心思想：引入前缀辅助链 P_1 -> P_2 -> ... -> P_n，将两两连边压缩至严格 O(k) 线性边数',
    'public class Code02_PrefixOptimizationGraph {',
    '    public static class PrefixGraph {',
    '        public int n;          // 实体节点数',
    '        public int totalNodes; // 实体节点 + 前缀虚点总数',
    '        public ArrayList<ArrayList<Integer>> adj;',
    '        public int edgeCount = 0;',
    '        ',
    '        public PrefixGraph(int n) {',
    '            this.n = n;',
    '            this.totalNodes = 2 * n;',
    '            this.adj = new ArrayList<>();',
    '            for (int i = 0; i <= totalNodes; i++) {',
    '                adj.add(new ArrayList<>());',
    '            }',
    '        }',
    '        ',
    '        public void addDirectedEdge(int u, int v) {',
    '            adj.get(u).add(v);',
    '            edgeCount++;',
    '        }',
    '        ',
    '        // 1. 建立前缀辅助链 (实体节点 1..n, 前缀虚点 P_i 为 n + i)',
    '        public void buildPrefixChain() {',
    '            for (int i = 1; i <= n; i++) {',
    '                int pi = n + i;',
    '                // P_i -> u_i: 前缀虚点向对应实体节点连边',
    '                addDirectedEdge(pi, i);',
    '                // P_i -> P_{i-1}: 前缀链级联传递边',
    '                if (i > 1) {',
    '                    addDirectedEdge(pi, pi - 1);',
    '                }',
    '            }',
    '        }',
    '        ',
    '        // 2. 区间优化连边: 节点 src 向前缀区间 [1, r] 连边',
    '        // 仅需连接一条有向边 src -> P_r 即可级联覆盖',
    '        public void addRangeEdge(int src, int r) {',
    '            if (r >= 1 && r <= n) {',
    '                int pr = n + r;',
    '                addDirectedEdge(src, pr);',
    '            }',
    '        }',
    '        ',
    '        // 3. 2-SAT 至多选一约束构造器',
    '        public void buildAtMostOne(int[] vars, int[] pre) {',
    '            int k = vars.length;',
    '            for (int i = 0; i < k; i++) {',
    '                int u = vars[i];',
    '                addDirectedEdge(u, pre[i]);',
    '                if (i > 0) {',
    '                    addDirectedEdge(pre[i - 1], pre[i]);',
    '                    addDirectedEdge(u, pre[i - 1] ^ 1);',
    '                }',
    '            }',
    '        }',
    '    }',
    '}',
  ],
  python: [
    '# 前缀优化建图 (Python 3)',
    '# 解决区间至多选一 / 区间连边时的 O(k^2) 边数爆炸问题',
    '# 核心思想：引入前缀辅助链 P_1 -> P_2 -> ... -> P_n，将两两连边压缩至严格 O(k) 线性边数',
    'class PrefixOptimizationGraph:',
    '    def __init__(self, n: int):',
    '        self.n = n',
    '        self.total_nodes = 2 * n',
    '        self.adj = [[] for _ in range(self.total_nodes + 1)]',
    '        self.edge_count = 0',
    '        ',
    '    def add_directed_edge(self, u: int, v: int):',
    '        self.adj[u].append(v)',
    '        self.edge_count += 1',
    '        ',
    '    # 1. 建立前缀辅助链 (P_i 编号为 n + i)',
    '    def build_prefix_chain(self):',
    '        for i in range(1, self.n + 1):',
    '            pi = self.n + i',
    '            # P_i -> u_i: 前缀虚点向实体点连边',
    '            self.add_directed_edge(pi, i)',
    '            # P_i -> P_{i-1}: 前缀级联覆盖边',
    '            if i > 1:',
    '                self.add_directed_edge(pi, pi - 1)',
    '                ',
    '    # 2. 区间优化连边: src 向区间 [1, r] 连边 (单条边 O(1) 代替 O(r))',
    '    def add_range_edge(self, src: int, r: int):',
    '        if 1 <= r <= self.n:',
    '            pr = self.n + r',
    '            self.add_directed_edge(src, pr)',
    '            ',
    '    # 3. 2-SAT 至多选一约束构造器',
    '    def build_at_most_one(self, vars: list[int], pre: list[int]):',
    '        k = len(vars)',
    '        for i in range(k):',
    '            u = vars[i]',
    '            self.add_directed_edge(u, pre[i])',
    '            if i > 0:',
    '                self.add_directed_edge(pre[i - 1], pre[i])',
    '                self.add_directed_edge(u, pre[i - 1] ^ 1)',
  ],
  javascript: [
    '// 前缀优化建图 (JavaScript ES6+)',
    '// 解决区间至多选一 / 区间连边时的 O(k^2) 边数爆炸问题',
    '// 核心思想：引入前缀辅助链 P_1 -> P_2 -> ... -> P_n，将两两连边压缩至严格 O(k) 线性边数',
    'class PrefixOptimizationGraph {',
    '  constructor(n) {',
    '    this.n = n;',
    '    this.totalNodes = 2 * n;',
    '    this.adj = Array.from({ length: this.totalNodes + 1 }, () => []);',
    '    this.edgeCount = 0;',
    '  }',
    '  ',
    '  addDirectedEdge(u, v) {',
    '    this.adj[u].push(v);',
    '    this.edgeCount++;',
    '  }',
    '  ',
    '  // 1. 建立前缀辅助链 (P_i 编号为 n + i)',
    '  buildPrefixChain() {',
    '    for (let i = 1; i <= this.n; i++) {',
    '      const pi = this.n + i;',
    '      // P_i -> u_i: 前缀虚点向实体点连边',
    '      this.addDirectedEdge(pi, i);',
    '      // P_i -> P_{i-1}: 前缀级联覆盖边',
    '      if (i > 1) {',
    '        this.addDirectedEdge(pi, pi - 1);',
    '      }',
    '    }',
    '  }',
    '  ',
    '  // 2. 区间优化连边: src 向区间 [1, r] 连边',
    '  addRangeEdge(src, r) {',
    '    if (r >= 1 && r <= this.n) {',
    '      const pr = this.n + r;',
    '      this.addDirectedEdge(src, pr);',
    '    }',
    '  }',
    '  ',
    '  // 3. 2-SAT 至多选一约束构造器',
    '  buildAtMostOne(vars, pre) {',
    '    const k = vars.length;',
    '    for (let i = 0; i < k; i++) {',
    '      const u = vars[i];',
    '      this.addDirectedEdge(u, pre[i]);',
    '      if (i > 0) {',
    '        this.addDirectedEdge(pre[i - 1], pre[i]);',
    '        this.addDirectedEdge(u, pre[i - 1] ^ 1);',
    '      }',
    '    }',
    '  }',
    '}',
  ],
};

export const PREFIX_OPT_PROBLEM_HTML = `
  <div style="font-size: 13px; line-height: 1.6; color: #334155;">
    <h3 style="margin-top: 0; color: #0f172a; font-size: 15px; font-weight: 800;">🌐 前缀优化建图 (Prefix Optimization Graph Building)</h3>
    <p>
      在图论与 2-SAT 建模中，经常遇到约束条件：<b>“某集合中的 $k$ 个元素至多只能选一个”</b>。若使用朴素两两连边，边数将达到 $O(k^2)$，当 $k = 10^5$ 时图将彻底爆炸。通过引入<b>前缀辅助点链</b>，可以将边数压缩至严格 $O(k)$（洛谷 P6378 [PA2010] Riddle）。
    </p>

    <div style="background: #f8fafc; border-left: 4px solid #3b82f6; padding: 8px 12px; margin: 10px 0; border-radius: 0 6px 6px 0;">
      <div style="font-weight: 700; color: #1e40af; margin-bottom: 4px;">⚡ 前缀链三原则</div>
      <div style="font-size: 11.5px; color: #334155;">
        1. <b>当前激活前缀</b>：$u_i \\to Pre_i$；<br/>
        2. <b>前缀继承链</b>：$Pre_{i-1} \\to Pre_i$；<br/>
        3. <b>逆向禁止</b>：$u_i \\to \\neg Pre_{i-1}$（若选 $u_i$，则前缀中不允许有任何节点被选）。
      </div>
    </div>
  </div>
`;

export const PREFIX_OPT_ANALYSIS_HTML = `
  <div style="font-size: 13px; line-height: 1.6; color: #334155;">
    <h3 style="margin-top: 0; color: #0f172a; font-size: 15px; font-weight: 800;">💡 线性边数压缩的数学本质</h3>

    <div style="background: #eff6ff; border: 1px solid #bfdbfe; border-radius: 6px; padding: 10px; margin-bottom: 12px;">
      <div style="font-weight: 700; color: #1e3a8a; margin-bottom: 4px;">1. 边数从 O(k²) 降为 3k 条</div>
      <div style="font-size: 12px; color: #1e40af;">
        每个实体变量仅产生 3 条有向边，总边数严格为 $3k - 2$ 条！即使 $k = 10^5$，边数也仅有约 $3 \\times 10^5$ 条，内存占用极低。
      </div>
    </div>

    <div style="background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 6px; padding: 10px;">
      <div style="font-weight: 700; color: #166534; margin-bottom: 4px;">2. 树状数组 / 线段树优化建图拓展</div>
      <div style="font-size: 12px; color: #15803d;">
        前缀优化建图是一维区间的特例。若要求任意区间 $[l, r]$ 连边，可用线段树节点作为虚拟中继，将边数压缩至 $O(m \\log n)$！
      </div>
    </div>
  </div>
`;
