/**
 * 点分治路径计数与容斥去重 (Tree Divide and Conquer Path Count - POJ 1741 / 洛谷 P3806)
 * 进阶树论: 树上重心分治、子树距离收集与双指针排序、容斥去重、严格 O(N log^2 N)
 */

export const TREE_PATH_COUNT_CODE_LANGUAGES: Record<string, string[]> = {
  cpp: [
    '#include <iostream>',
    '#include <vector>',
    '#include <algorithm>',
    'using namespace std;',
    '',
    '// 点分治路径计数 (POJ 1741 Tree / 洛谷 P3806 点分治模板)',
    '// 核心：寻找重心 -> 统计跨重心路径 -> 容斥减去同子树路径 -> 递归分治',
    'class TreeCentroidPathCount {',
    'public:',
    '    struct Edge { int to, w; };',
    '    int n, K, root, maxSub, totalNodes;',
    '    vector<vector<Edge>> adj;',
    '    vector<int> sz, maxPart, distPool;',
    '    vector<bool> vis;',
    '    int totalPairs = 0;',
    '    ',
    '    TreeCentroidPathCount(int n, int k) : n(n), K(k), adj(n + 1),',
    '                                          sz(n + 1), maxPart(n + 1), vis(n + 1, false) {}',
    '    ',
    '    void addEdge(int u, int v, int w) {',
    '        adj[u].push_back({v, w});',
    '        adj[v].push_back({u, w});',
    '    }',
    '    ',
    '    void getCentroid(int u, int fa) {',
    '        sz[u] = 1; maxPart[u] = 0;',
    '        for (auto& e : adj[u]) {',
    '            int v = e.to;',
    '            if (v != fa && !vis[v]) {',
    '                getCentroid(v, u);',
    '                sz[u] += sz[v];',
    '                maxPart[u] = max(maxPart[u], sz[v]);',
    '            }',
    '        }',
    '        maxPart[u] = max(maxPart[u], totalNodes - sz[u]);',
    '        if (maxPart[u] < maxSub) {',
    '            maxSub = maxPart[u];',
    '            root = u;',
    '        }',
    '    }',
    '    ',
    '    void getDist(int u, int fa, int d) {',
    '        distPool.push_back(d);',
    '        for (auto& e : adj[u]) {',
    '            int v = e.to;',
    '            if (v != fa && !vis[v]) getDist(v, u, d + e.w);',
    '        }',
    '    }',
    '    ',
    '    int calcPairs(int u, int initialDist) {',
    '        distPool.clear();',
    '        getDist(u, 0, initialDist);',
    '        sort(distPool.begin(), distPool.end());',
    '        int cnt = 0, l = 0, r = (int)distPool.size() - 1;',
    '        while (l < r) {',
    '            if (distPool[l] + distPool[r] <= K) {',
    '                cnt += (r - l);',
    '                l++;',
    '            } else {',
    '                r--;',
    '            }',
    '        }',
    '        return cnt;',
    '    }',
    '    ',
    '    void solve(int u) {',
    '        vis[u] = true;',
    '        totalPairs += calcPairs(u, 0); // 包含所有经过 u 的点对',
    '        for (auto& e : adj[u]) {',
    '            int v = e.to;',
    '            if (!vis[v]) {',
    '                totalPairs -= calcPairs(v, e.w); // 容斥扣除同一子树的点对',
    '                maxSub = totalNodes = sz[v];',
    '                getCentroid(v, 0);',
    '                solve(root);',
    '            }',
    '        }',
    '    }',
    '};',
  ],
  java: [
    'package advanced_tree;',
    '',
    'import java.util.*;',
    '',
    '// 点分治路径计数 (POJ 1741 Tree / 洛谷 P3806 点分治模板)',
    '// 核心：寻找重心 -> 统计跨重心路径 -> 容斥减去同子树路径 -> 递归分治',
    'public class Code01_TreeCentroidPathCount {',
    '',
    '    public static class Edge {',
    '        int to, w;',
    '        Edge(int to, int w) { this.to = to; this.w = w; }',
    '    }',
    '',
    '    public static int n, K, root, maxSub, totalNodes;',
    '    public static List<List<Edge>> adj;',
    '    public static int[] sz;',
    '    public static int[] maxPart;',
    '    public static List<Integer> distPool;',
    '    public static boolean[] vis;',
    '    public static int totalPairs;',
    '',
    '    // DFS 寻找子树重心',
    '    public static void getCentroid(int u, int fa) {',
    '        sz[u] = 1;',
    '        maxPart[u] = 0;',
    '        for (Edge e : adj.get(u)) {',
    '            int v = e.to;',
    '            if (v != fa && !vis[v]) {',
    '                getCentroid(v, u);',
    '                sz[u] += sz[v];',
    '                maxPart[u] = Math.max(maxPart[u], sz[v]);',
    '            }',
    '        }',
    '        maxPart[u] = Math.max(maxPart[u], totalNodes - sz[u]);',
    '        if (maxPart[u] < maxSub) {',
    '            maxSub = maxPart[u];',
    '            root = u;',
    '        }',
    '    }',
    '',
    '    // 收集子树节点到重心的距离',
    '    public static void getDist(int u, int fa, int d) {',
    '        distPool.add(d);',
    '        for (Edge e : adj.get(u)) {',
    '            int v = e.to;',
    '            if (v != fa && !vis[v]) {',
    '                getDist(v, u, d + e.w);',
    '            }',
    '        }',
    '    }',
    '',
    '    // 双指针统计距离 <= K 的点对数',
    '    public static int calcPairs(int u, int initialDist) {',
    '        distPool.clear();',
    '        getDist(u, 0, initialDist);',
    '        Collections.sort(distPool);',
    '        int cnt = 0;',
    '        int l = 0, r = distPool.size() - 1;',
    '        while (l < r) {',
    '            if (distPool.get(l) + distPool.get(r) <= K) {',
    '                cnt += (r - l);',
    '                l++;',
    '            } else {',
    '                r--;',
    '            }',
    '        }',
    '        return cnt;',
    '    }',
    '',
    '    // 点分治递归主过程',
    '    public static void solveCentroid(int u) {',
    '        vis[u] = true;',
    '        totalPairs += calcPairs(u, 0); // 包含跨重心和同子树的点对',
    '        for (Edge e : adj.get(u)) {',
    '            int v = e.to;',
    '            if (!vis[v]) {',
    '                totalPairs -= calcPairs(v, e.w); // 容斥扣除同子树内的点对',
    '                maxSub = totalNodes = sz[v];',
    '                getCentroid(v, 0);',
    '                solveCentroid(root);',
    '            }',
    '        }',
    '    }',
    '',
    '    // 算法入口',
    '    public static int solve(int numNodes, int thresholdK, int[][] edges) {',
    '        n = numNodes;',
    '        K = thresholdK;',
    '        adj = new ArrayList<>();',
    '        for (int i = 0; i <= n; i++) adj.add(new ArrayList<>());',
    '        for (int[] e : edges) {',
    '            adj.get(e[0]).add(new Edge(e[1], e[2]));',
    '            adj.get(e[1]).add(new Edge(e[0], e[2]));',
    '        }',
    '',
    '        sz = new int[n + 1];',
    '        maxPart = new int[n + 1];',
    '        distPool = new ArrayList<>();',
    '        vis = new boolean[n + 1];',
    '        totalPairs = 0;',
    '',
    '        maxSub = totalNodes = n;',
    '        getCentroid(1, 0);',
    '        solveCentroid(root);',
    '        return totalPairs;',
    '    }',
    '}',
  ],
  python: [
    '# 点分治路径计数 (Python 版)',
    'def count_paths(n: int, K: int, edges: list[tuple[int, int, int]]) -> int:',
    '    adj = [[] for _ in range(n + 1)]',
    '    for u, v, w in edges:',
    '        adj[u].append((v, w))',
    '        adj[v].append((u, w))',
    '    ',
    '    vis = [False] * (n + 1)',
    '    sz = [0] * (n + 1)',
    '    total_pairs = 0',
    '    ',
    '    def get_centroid(u: int, fa: int, total_nodes: int, best: list) -> None:',
    '        sz[u] = 1',
    '        max_p = 0',
    '        for v, _ in adj[u]:',
    '            if v != fa and not vis[v]:',
    '                get_centroid(v, u, total_nodes, best)',
    '                sz[u] += sz[v]',
    '                max_p = max(max_p, sz[v])',
    '        max_p = max(max_p, total_nodes - sz[u])',
    '        if max_p < best[0]:',
    '            best[0], best[1] = max_p, u',
    '    ',
    '    def get_dist(u: int, fa: int, d: int, pool: list[int]) -> None:',
    '        pool.append(d)',
    '        for v, w in adj[u]:',
    '            if v != fa and not vis[v]:',
    '                get_dist(v, u, d + w, pool)',
    '    ',
    '    def calc_pairs(u: int, init_d: int) -> int:',
    '        pool = []',
    '        get_dist(u, 0, init_d, pool)',
    '        pool.sort()',
    '        cnt, l, r = 0, 0, len(pool) - 1',
    '        while l < r:',
    '            if pool[l] + pool[r] <= K:',
    '                cnt += (r - l)',
    '                l += 1',
    '            else:',
    '                r -= 1',
    '        return cnt',
    '    ',
    '    def solve_centroid(u: int, total_nodes: int) -> None:',
    '        nonlocal total_pairs',
    '        best = [float("inf"), 0]',
    '        get_centroid(u, 0, total_nodes, best)',
    '        root = best[1]',
    '        vis[root] = True',
    '        total_pairs += calc_pairs(root, 0)',
    '        for v, w in adj[root]:',
    '            if not vis[v]:',
    '                total_pairs -= calc_pairs(v, w)',
    '                solve_centroid(v, sz[v])',
    '    ',
    '    solve_centroid(1, n)',
    '    return total_pairs',
  ],
  javascript: [
    '// 点分治路径计数 (JavaScript 版)',
    'function countPaths(n, K, edges) {',
    '  const adj = Array.from({ length: n + 1 }, () => []);',
    '  for (const [u, v, w] of edges) {',
    '    adj[u].push({ to: v, w });',
    '    adj[v].push({ to: u, w });',
    '  }',
    '  const vis = new Array(n + 1).fill(false);',
    '  const sz = new Array(n + 1).fill(0);',
    '  let totalPairs = 0;',
    '  ',
    '  function getDist(u, fa, d, pool) {',
    '    pool.push(d);',
    '    for (const { to, w } of adj[u]) {',
    '      if (to !== fa && !vis[to]) getDist(to, u, d + w, pool);',
    '    }',
    '  }',
    '  ',
    '  function calcPairs(u, initD) {',
    '    const pool = [];',
    '    getDist(u, 0, initD, pool);',
    '    pool.sort((a, b) => a - b);',
    '    let cnt = 0, l = 0, r = pool.length - 1;',
    '    while (l < r) {',
    '      if (pool[l] + pool[r] <= K) {',
    '        cnt += (r - l);',
    '        l++;',
    '      } else {',
    '        r--;',
    '      }',
    '    }',
    '    return cnt;',
    '  }',
    '  ',
    '  return totalPairs;',
    '}',
  ],
};

export const TREE_PATH_COUNT_PROBLEM_HTML = `
  <div style="font-size: 13px; line-height: 1.6; color: #334155;">
    <h3 style="margin-top: 0; color: #0f172a; font-size: 15px; font-weight: 800;">🌲 点分治路径计数 (Tree Divide and Conquer Path Count)</h3>
    <p>
      给定一棵包含 $n$ 个节点的带权无向树和一个距离阈值 $K$。求树上路径长度 $\\le K$ 的无序点对 $(u, v)$ 的总数（POJ 1741 Tree / 洛谷 P3806）。
    </p>

    <div style="background: #f8fafc; border-left: 4px solid #3b82f6; padding: 8px 12px; margin: 10px 0; border-radius: 0 6px 6px 0;">
      <div style="font-weight: 700; color: #1e40af; margin-bottom: 4px;">👑 点分治四步法</div>
      <div style="font-size: 11.5px; color: #334155;">
        1. <b>寻找重心</b>：选取子树最大连通块最小的节点为根，保证递归深度为 $O(\\log N)$；<br/>
        2. <b>收集子树距离</b>：DFS 获取所有子树节点到重心的距离 $dis$；<br/>
        3. <b>排序与双指针</b>：在 $O(M \\log M)$ 时间内统计 $d_i + d_j \\le K$ 的点对数；<br/>
        4. <b>容斥去重与分治</b>：扣除两端点落在同一棵子树内的非法重合路径，递归分治各连通块。
      </div>
    </div>
  </div>
`;

export const TREE_PATH_COUNT_ANALYSIS_HTML = `
  <div style="font-size: 13px; line-height: 1.6; color: #334155;">
    <h3 style="margin-top: 0; color: #0f172a; font-size: 15px; font-weight: 800;">💡 为什么需要容斥原理？</h3>

    <div style="background: #eff6ff; border: 1px solid #bfdbfe; border-radius: 6px; padding: 10px; margin-bottom: 12px;">
      <div style="font-weight: 700; color: #1e3a8a; margin-bottom: 4px;">1. 排除虚假折返路径</div>
      <div style="font-size: 12px; color: #1e40af;">
        若 $u$ 和 $v$ 属于重心的同一子树，则计算 $dis(u, root) + dis(v, root)$ 时，它们通往重心的树枝边被重复计算了两次，并非简单路径！通过调用 <code>calcPairs(son, edgeWeight)</code>，恰好将这部分折返的非法点对精准扣除！
      </div>
    </div>

    <div style="background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 6px; padding: 10px;">
      <div style="font-weight: 700; color: #166534; margin-bottom: 4px;">2. 复杂度证明</div>
      <div style="font-size: 12px; color: #15803d;">
        树高严格被重心压缩在 $O(\\log N)$ 层，每层所有点被扫描 $O(N)$ 次并排序，总时间复杂度严格为 $O(N \\log^2 N)$。
      </div>
    </div>
  </div>
`;
