/**
 * 虚树与多次关键点树形 DP (Virtual Tree / Auxiliary Tree)
 * 进阶树论: 关键点按 DFN 排序、单调栈维护 LCA 关键链、O(K log N) 虚树构建与极速 DP (洛谷 P2495 [SDOI2011] 消耗战)
 */

export const VIRTUAL_TREE_CODE_LANGUAGES: Record<string, string[]> = {
  cpp: [
    '#include <iostream>',
    '#include <vector>',
    '#include <algorithm>',
    '#include <stack>',
    'using namespace std;',
    '',
    '// 虚树 (Virtual Tree) 构建与关键点 DP (洛谷 P2495 [SDOI2011] 消耗战)',
    '// 核心：按 DFN 序排序，单调栈维护最右链并插入 LCA，节点规模从 O(N) 压缩至 <= 2K',
    'class VirtualTree {',
    'public:',
    '    int n, dfnClock = 0;',
    '    vector<vector<pair<int, int>>> origAdj;',
    '    vector<vector<pair<int, int>>> vtreeAdj;',
    '    vector<int> dfn, depth;',
    '    vector<vector<int>> up;',
    '    vector<bool> isKeyNode;',
    '    ',
    '    VirtualTree(int n) : n(n), origAdj(n + 1), vtreeAdj(n + 1),',
    '                         dfn(n + 1, 0), depth(n + 1, 0),',
    '                         up(n + 1, vector<int>(19, 0)), isKeyNode(n + 1, false) {}',
    '    ',
    '    void addOrigEdge(int u, int v, int w) {',
    '        origAdj[u].push_back({v, w});',
    '        origAdj[v].push_back({u, w});',
    '    }',
    '    ',
    '    void dfsInit(int u, int fa, int d) {',
    '        dfn[u] = ++dfnClock;',
    '        depth[u] = d;',
    '        up[u][0] = fa;',
    '        for (int i = 1; i <= 18; ++i) up[u][i] = up[up[u][i - 1]][i - 1];',
    '        for (auto& edge : origAdj[u]) {',
    '            if (edge.first != fa) dfsInit(edge.first, u, d + 1);',
    '        }',
    '    }',
    '    ',
    '    int getLCA(int u, int v) {',
    '        if (depth[u] < depth[v]) swap(u, v);',
    '        for (int i = 18; i >= 0; --i) {',
    '            if (depth[u] - (1 << i) >= depth[v]) u = up[u][i];',
    '        }',
    '        if (u == v) return u;',
    '        for (int i = 18; i >= 0; --i) {',
    '            if (up[u][i] != up[v][i]) {',
    '                u = up[u][i];',
    '                v = up[v][i];',
    '            }',
    '        }',
    '        return up[u][0];',
    '    }',
    '    ',
    '    // 构建虚树 (严格 O(K log N))',
    '    void buildVirtualTree(vector<int>& keyNodes) {',
    '        // 1. 按 DFN 序升序排序',
    '        sort(keyNodes.begin(), keyNodes.end(), [&](int a, int b) {',
    '            return dfn[a] < dfn[b];',
    '        });',
    '        ',
    '        vector<int> stk;',
    '        stk.push_back(1); // 确保根节点在虚树中',
    '        vtreeAdj[1].clear();',
    '        ',
    '        for (int u : keyNodes) {',
    '            if (u == 1) continue;',
    '            int lca = getLCA(u, stk.back());',
    '            if (lca != stk.back()) {',
    '                while (stk.size() >= 2 && depth[stk[stk.size() - 2]] >= depth[lca]) {',
    '                    int top = stk.back(); stk.pop_back();',
    '                    vtreeAdj[stk.back()].push_back({top, 0});',
    '                }',
    '                if (stk.back() != lca) {',
    '                    vtreeAdj[lca].clear();',
    '                    int top = stk.back(); stk.pop_back();',
    '                    vtreeAdj[lca].push_back({top, 0});',
    '                    stk.push_back(lca);',
    '                }',
    '            }',
    '            vtreeAdj[u].clear();',
    '            stk.push_back(u);',
    '        }',
    '        while (stk.size() >= 2) {',
    '            int top = stk.back(); stk.pop_back();',
    '            vtreeAdj[stk.back()].push_back({top, 0});',
    '        }',
    '    }',
    '};',
  ],
  java: [
    'package advanced_tree;',
    '',
    'import java.util.*;',
    '',
    '/**',
    ' * 虚树 (Virtual Tree) 标准实现与关键点树形 DP',
    ' * 时间复杂度: 构建 O(K log N)，DP 求解 O(K)',
    ' * 空间复杂度: O(N)',
    ' */',
    'public class Code01_VirtualTree {',
    '    public static class VirtualTree {',
    '        public int n, dfnClock = 0;',
    '        public ArrayList<ArrayList<int[]>> origAdj, vtreeAdj;',
    '        public int[] dfn, depth;',
    '        public int[][] up;',
    '        public boolean[] isKey;',
    '        ',
    '        public VirtualTree(int n) {',
    '            this.n = n;',
    '            origAdj = new ArrayList<>();',
    '            vtreeAdj = new ArrayList<>();',
    '            for (int i = 0; i <= n; i++) {',
    '                origAdj.add(new ArrayList<>());',
    '                vtreeAdj.add(new ArrayList<>());',
    '            }',
    '            dfn = new int[n + 1];',
    '            depth = new int[n + 1];',
    '            up = new int[n + 1][19];',
    '            isKey = new boolean[n + 1];',
    '        }',
    '        ',
    '        public void addOrigEdge(int u, int v, int w) {',
    '            origAdj.get(u).add(new int[]{v, w});',
    '            origAdj.get(v).add(new int[]{u, w});',
    '        }',
    '        ',
    '        public void dfsInit(int u, int fa, int d) {',
    '            dfn[u] = ++dfnClock;',
    '            depth[u] = d;',
    '            up[u][0] = fa;',
    '            for (int i = 1; i <= 18; i++) up[u][i] = up[up[u][i - 1]][i - 1];',
    '            for (int[] e : origAdj.get(u)) {',
    '                if (e[0] != fa) dfsInit(e[0], u, d + 1);',
    '            }',
    '        }',
    '        ',
    '        public int getLCA(int u, int v) {',
    '            if (depth[u] < depth[v]) { int t = u; u = v; v = t; }',
    '            for (int i = 18; i >= 0; i--) {',
    '                if (depth[u] - (1 << i) >= depth[v]) u = up[u][i];',
    '            }',
    '            if (u == v) return u;',
    '            for (int i = 18; i >= 0; i--) {',
    '                if (up[u][i] != up[v][i]) { u = up[u][i]; v = up[v][i]; }',
    '            }',
    '            return up[u][0];',
    '        }',
    '        ',
    '        // 单调栈构建虚树 (<= 2K 个节点)',
    '        public void buildVirtualTree(List<Integer> keyNodes) {',
    '            keyNodes.sort(Comparator.comparingInt(a -> dfn[a]));',
    '            List<Integer> stk = new ArrayList<>();',
    '            stk.add(1);',
    '            vtreeAdj.get(1).clear();',
    '            ',
    '            for (int u : keyNodes) {',
    '                if (u == 1) continue;',
    '                int lca = getLCA(u, stk.get(stk.size() - 1));',
    '                if (lca != stk.get(stk.size() - 1)) {',
    '                    while (stk.size() >= 2 && depth[stk.get(stk.size() - 2)] >= depth[lca]) {',
    '                        int top = stk.remove(stk.size() - 1);',
    '                        vtreeAdj.get(stk.get(stk.size() - 1)).add(new int[]{top, 0});',
    '                    }',
    '                    if (stk.get(stk.size() - 1) != lca) {',
    '                        vtreeAdj.get(lca).clear();',
    '                        int top = stk.remove(stk.size() - 1);',
    '                        vtreeAdj.get(lca).add(new int[]{top, 0});',
    '                        stk.add(lca);',
    '                    }',
    '                }',
    '                vtreeAdj.get(u).clear();',
    '                stk.add(u);',
    '            }',
    '            while (stk.size() >= 2) {',
    '                int top = stk.remove(stk.size() - 1);',
    '                vtreeAdj.get(stk.get(stk.size() - 1)).add(new int[]{top, 0});',
    '            }',
    '        }',
    '    }',
    '}',
  ],
  python: [
    '# 虚树 (Python 标准实现)',
    '# 核心原理: 关键点按 DFN 序排序 + 单调栈维护最右链 + 树形 DP',
    '# 时间复杂度: 构建 O(K log N)，空间复杂度: O(N)',
    'import sys',
    'sys.setrecursionlimit(200000)',
    '',
    'class VirtualTree:',
    '    def __init__(self, n: int):',
    '        self.n = n',
    '        self.dfn_clock = 0',
    '        self.orig_adj = [[] for _ in range(n + 1)]',
    '        self.vtree_adj = [[] for _ in range(n + 1)]',
    '        self.dfn = [0] * (n + 1)',
    '        self.depth = [0] * (n + 1)',
    '        self.up = [[0] * 19 for _ in range(n + 1)]',
    '        ',
    '    def add_orig_edge(self, u: int, v: int, w: int):',
    '        self.orig_adj[u].append((v, w))',
    '        self.orig_adj[v].append((u, w))',
    '        ',
    '    def dfs_init(self, u: int, fa: int, d: int):',
    '        self.dfn_clock += 1',
    '        self.dfn[u] = self.dfn_clock',
    '        self.depth[u] = d',
    '        self.up[u][0] = fa',
    '        for i in range(1, 19):',
    '            self.up[u][i] = self.up[self.up[u][i - 1]][i - 1]',
    '        for v, w in self.orig_adj[u]:',
    '            if v != fa:',
    '                self.dfs_init(v, u, d + 1)',
    '                ',
    '    def get_lca(self, u: int, v: int) -> int:',
    '        if self.depth[u] < self.depth[v]:',
    '            u, v = v, u',
    '        for i in range(18, -1, -1):',
    '            if self.depth[u] - (1 << i) >= self.depth[v]:',
    '                u = self.up[u][i]',
    '        if u == v: return u',
    '        for i in range(18, -1, -1):',
    '            if self.up[u][i] != self.up[v][i]:',
    '                u = self.up[u][i]',
    '                v = self.up[v][i]',
    '        return self.up[u][0]',
    '        ',
    '    def build_virtual_tree(self, key_nodes: list[int]):',
    '        key_nodes.sort(key=lambda x: self.dfn[x])',
    '        stk = [1]',
    '        self.vtree_adj[1].clear()',
    '        for u in key_nodes:',
    '            if u == 1: continue',
    '            lca = self.get_lca(u, stk[-1])',
    '            if lca != stk[-1]:',
    '                while len(stk) >= 2 and self.depth[stk[-2]] >= self.depth[lca]:',
    '                    top = stk.pop()',
    '                    self.vtree_adj[stk[-1]].append((top, 0))',
    '                if stk[-1] != lca:',
    '                    self.vtree_adj[lca].clear()',
    '                    top = stk.pop()',
    '                    self.vtree_adj[lca].append((top, 0))',
    '                    stk.append(lca)',
    '            self.vtree_adj[u].clear()',
    '            stk.append(u)',
    '        while len(stk) >= 2:',
    '            top = stk.pop()',
    '            self.vtree_adj[stk[-1]].append((top, 0))',
  ],
  javascript: [
    '/**',
    ' * 虚树 (Virtual Tree) 构建 (JavaScript 版)',
    ' * 利用单调栈在线性 O(K log N) 时间内浓缩关键点树形结构',
    ' */',
    'class VirtualTree {',
    '  constructor(n) {',
    '    this.n = n;',
    '    this.dfnClock = 0;',
    '    this.origAdj = Array.from({ length: n + 1 }, () => []);',
    '    this.vtreeAdj = Array.from({ length: n + 1 }, () => []);',
    '    this.dfn = Array(n + 1).fill(0);',
    '    this.depth = Array(n + 1).fill(0);',
    '    this.up = Array.from({ length: n + 1 }, () => Array(19).fill(0));',
    '  }',
    '  ',
    '  addOrigEdge(u, v, w) {',
    '    this.origAdj[u].push([v, w]);',
    '    this.origAdj[v].push([u, w]);',
    '  }',
    '  ',
    '  dfsInit(u, fa, d) {',
    '    this.dfn[u] = ++this.dfnClock;',
    '    this.depth[u] = d;',
    '    this.up[u][0] = fa;',
    '    for (let i = 1; i <= 18; i++) this.up[u][i] = this.up[this.up[u][i - 1]][i - 1];',
    '    for (const [v, w] of this.origAdj[u]) {',
    '      if (v !== fa) this.dfsInit(v, u, d + 1);',
    '    }',
    '  }',
    '  ',
    '  getLCA(u, v) {',
    '    if (this.depth[u] < this.depth[v]) { const t = u; u = v; v = t; }',
    '    for (let i = 18; i >= 0; i--) {',
    '      if (this.depth[u] - (1 << i) >= this.depth[v]) u = this.up[u][i];',
    '    }',
    '    if (u === v) return u;',
    '    for (let i = 18; i >= 0; i--) {',
    '      if (this.up[u][i] !== this.up[v][i]) { u = this.up[u][i]; v = this.up[v][i]; }',
    '    }',
    '    return this.up[u][0];',
    '  }',
    '  ',
    '  buildVirtualTree(keyNodes) {',
    '    keyNodes.sort((a, b) => this.dfn[a] - this.dfn[b]);',
    '    const stk = [1];',
    '    this.vtreeAdj[1] = [];',
    '    for (const u of keyNodes) {',
    '      if (u === 1) continue;',
    '      const lca = this.getLCA(u, stk[stk.length - 1]);',
    '      if (lca !== stk[stk.length - 1]) {',
    '        while (stk.length >= 2 && this.depth[stk[stk.length - 2]] >= this.depth[lca]) {',
    '          const top = stk.pop();',
    '          this.vtreeAdj[stk[stk.length - 1]].push([top, 0]);',
    '        }',
    '        if (stk[stk.length - 1] !== lca) {',
    '          this.vtreeAdj[lca] = [];',
    '          const top = stk.pop();',
    '          this.vtreeAdj[lca].push([top, 0]);',
    '          stk.push(lca);',
    '        }',
    '      }',
    '      this.vtreeAdj[u] = [];',
    '      stk.push(u);',
    '    }',
    '    while (stk.length >= 2) {',
    '      const top = stk.pop();',
    '      this.vtreeAdj[stk[stk.length - 1]].push([top, 0]);',
    '    }',
    '  }',
    '}',
  ],
};

export const VIRTUAL_TREE_PROBLEM_HTML = `
  <div style="font-size: 13px; line-height: 1.6; color: #334155;">
    <h3 style="margin-top: 0; color: #0f172a; font-size: 15px; font-weight: 800;">🌲 虚树 (Virtual Tree / Auxiliary Tree)</h3>
    <p>
      当大树规模很大（$N=10^5$），每次询问仅涉及 $K$ 个关键点且 $\\sum K$ 较小时，如果每次都遍历整棵树做 DP 将导致 $O(N \\cdot Q)$ 超时。<b>虚树</b>通过仅提取关键点及其两两之间的 LCA，将树规模压缩至 $\\le 2K$（洛谷 P2495 [SDOI2011] 消耗战）。
    </p>

    <div style="background: #f8fafc; border-left: 4px solid #3b82f6; padding: 8px 12px; margin: 10px 0; border-radius: 0 6px 6px 0;">
      <div style="font-weight: 700; color: #1e40af; margin-bottom: 4px;">🧱 单调栈单遍构建算法</div>
      <div style="font-size: 11.5px; color: #334155;">
        1. 关键点按原树 <b>DFN 序升序排序</b>；<br/>
        2. 维护单调栈记录虚树最右链；<br/>
        3. 插入新点 $u$ 时求 $\\text{LCA}(stack.top(), u)$，根据深度弹栈并连边，插入必要的 LCA 汇聚点。
      </div>
    </div>
  </div>
`;

export const VIRTUAL_TREE_ANALYSIS_HTML = `
  <div style="font-size: 13px; line-height: 1.6; color: #334155;">
    <h3 style="margin-top: 0; color: #0f172a; font-size: 15px; font-weight: 800;">💡 虚树的关键性质与极速复杂度</h3>

    <div style="background: #eff6ff; border: 1px solid #bfdbfe; border-radius: 6px; padding: 10px; margin-bottom: 12px;">
      <div style="font-weight: 700; color: #1e3a8a; margin-bottom: 4px;">1. 规模严格上界 $\\le 2K$</div>
      <div style="font-size: 12px; color: #1e40af;">
        $K$ 个关键点两两之间至多产生 $K-1$ 个不同的 LCA 节点，故虚树总结点数严格不超过 $2K - 1$！
      </div>
    </div>

    <div style="background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 6px; padding: 10px;">
      <div style="font-weight: 700; color: #166534; margin-bottom: 4px;">2. 复杂度由 O(N) 降为 O(K log N)</div>
      <div style="font-size: 12px; color: #15803d;">
        单次询问在虚树上执行树形 DP 仅消耗 $O(K)$ 时间，总时间复杂度为 $O(\\sum K \\log N)$，轻松通过海量关键点多组询问！
      </div>
    </div>
  </div>
`;
