/**
 * 左程云 Class 063 四语言核心算法实现与 1-based 行号字典映射
 * Java / C++ / Python / JavaScript
 */

export const WORD_LADDER_063_CODES: Record<string, string[]> = {
  java: [
    'package class063;',
    'import java.util.HashSet;',
    'import java.util.List;',
    '',
    '// 单词接龙 - 双向广搜 (LeetCode 127)',
    'public class Code01_WordLadder {',
    '    public static int ladderLength(String begin, String end, List<String> wordList) {',
    '        HashSet<String> dict = new HashSet<>(wordList);',
    '        if (!dict.contains(end)) return 0;',
    '        HashSet<String> smallLevel = new HashSet<>();',
    '        HashSet<String> bigLevel = new HashSet<>();',
    '        HashSet<String> nextLevel = new HashSet<>();',
    '        smallLevel.add(begin);',
    '        bigLevel.add(end);',
    '        for (int len = 2; !smallLevel.isEmpty(); len++) {',
    '            for (String w : smallLevel) {',
    '                char[] ch = w.toCharArray();',
    '                for (int i = 0; i < ch.length; i++) {',
    '                    char old = ch[i];',
    '                    for (char c = \'a\'; c <= \'z\'; c++) {',
    '                        ch[i] = c;',
    '                        String str = String.valueOf(ch);',
    '                        if (bigLevel.contains(str)) return len;',
    '                        if (dict.contains(str)) {',
    '                            dict.remove(str);',
    '                            nextLevel.add(str);',
    '                        }',
    '                    }',
    '                    ch[i] = old;',
    '                }',
    '            }',
    '            if (nextLevel.size() <= bigLevel.size()) {',
    '                smallLevel = nextLevel;',
    '            } else {',
    '                smallLevel = bigLevel;',
    '                bigLevel = nextLevel;',
    '            }',
    '            nextLevel = new HashSet<>();',
    '        }',
    '        return 0;',
    '    }',
    '}',
  ],
  cpp: [
    '#include <vector>',
    '#include <string>',
    '#include <unordered_set>',
    'using namespace std;',
    '',
    '// 单词接龙 - 双向广搜 (LeetCode 127)',
    'class Solution {',
    'public:',
    '    int ladderLength(string begin, string end, vector<string>& wordList) {',
    '        unordered_set<string> dict(wordList.begin(), wordList.end());',
    '        if (!dict.count(end)) return 0;',
    '        unordered_set<string> smallLevel, bigLevel, nextLevel;',
    '        smallLevel.insert(begin);',
    '        bigLevel.insert(end);',
    '        for (int len = 2; !smallLevel.empty(); len++) {',
    '            for (string w : smallLevel) {',
    '                for (int i = 0; i < (int)w.size(); i++) {',
    '                    char old = w[i];',
    '                    for (char c = \'a\'; c <= \'z\'; c++) {',
    '                        w[i] = c;',
    '                        if (bigLevel.count(w)) return len;',
    '                        if (dict.count(w)) {',
    '                            dict.erase(w);',
    '                            nextLevel.insert(w);',
    '                        }',
    '                    }',
    '                    w[i] = old;',
    '                }',
    '            }',
    '            if (nextLevel.size() <= bigLevel.size()) {',
    '                smallLevel = move(nextLevel);',
    '            } else {',
    '                smallLevel = move(bigLevel);',
    '                bigLevel = move(nextLevel);',
    '            }',
    '            nextLevel.clear();',
    '        }',
    '        return 0;',
    '    }',
    '};',
  ],
  python: [
    'class Solution:',
    '    def ladderLength(self, begin: str, end: str, wordList: list[str]) -> int:',
    '        dict_words = set(wordList)',
    '        if end not in dict_words:',
    '            return 0',
    '        small_level = {begin}',
    '        big_level = {end}',
    '        length = 2',
    '        while small_level:',
    '            next_level = set()',
    '            for w in small_level:',
    '                chars = list(w)',
    '                for i in range(len(chars)):',
    '                    old = chars[i]',
    '                    for c in "abcdefghijklmnopqrstuvwxyz":',
    '                        chars[i] = c',
    '                        nxt = "".join(chars)',
    '                        if nxt in big_level:',
    '                            return length',
    '                        if nxt in dict_words:',
    '                            dict_words.remove(nxt)',
    '                            next_level.add(nxt)',
    '                    chars[i] = old',
    '            if len(next_level) <= len(big_level):',
    '                small_level = next_level',
    '            else:',
    '                small_level, big_level = big_level, next_level',
    '            length += 1',
    '        return 0',
  ],
  javascript: [
    '// 单词接龙 - 双向广搜 (LeetCode 127)',
    'function ladderLength(begin, end, wordList) {',
    '    const dict = new Set(wordList);',
    '    if (!dict.has(end)) return 0;',
    '    let smallLevel = new Set([begin]);',
    '    let bigLevel = new Set([end]);',
    '    let len = 2;',
    '    while (smallLevel.size > 0) {',
    '        const nextLevel = new Set();',
    '        for (const w of smallLevel) {',
    '            const ch = w.split("");',
    '            for (let i = 0; i < ch.length; i++) {',
    '                const old = ch[i];',
    '                for (let c = 97; c <= 122; c++) {',
    '                    ch[i] = String.fromCharCode(c);',
    '                    const nxt = ch.join("");',
    '                    if (bigLevel.has(nxt)) return len;',
    '                    if (dict.has(nxt)) {',
    '                        dict.delete(nxt);',
    '                        nextLevel.add(nxt);',
    '                    }',
    '                }',
    '                ch[i] = old;',
    '            }',
    '        }',
    '        if (nextLevel.size <= bigLevel.size) {',
    '            smallLevel = nextLevel;',
    '        } else {',
    '            smallLevel = bigLevel;',
    '            bigLevel = nextLevel;',
    '        }',
    '        len++;',
    '    }',
    '    return 0;',
    '}',
  ],
};

export const WORD_LADDER_063_LINES = {
  entry: { java: 7, cpp: 9, python: 2, javascript: 2 },
  checkEndInDict: { java: 9, cpp: 11, python: 4, javascript: 4 },
  initSets: { java: 13, cpp: 13, python: 6, javascript: 5 },
  whileLoop: { java: 15, cpp: 15, python: 9, javascript: 8 },
  forWord: { java: 16, cpp: 16, python: 11, javascript: 10 },
  mutateChar: { java: 21, cpp: 20, python: 16, javascript: 14 },
  checkMeet: { java: 23, cpp: 22, python: 18, javascript: 16 },
  addNext: { java: 26, cpp: 25, python: 21, javascript: 19 },
  swapCheck: { java: 32, cpp: 30, python: 23, javascript: 24 },
  returnZero: { java: 40, cpp: 37, python: 28, javascript: 31 },
};

export const SNACKS_WAYS_063_CODES: Record<string, string[]> = {
  java: [
    'package class063;',
    'import java.util.Arrays;',
    '',
    '// 牛牛的背包问题 / 世界冰球锦标赛 (洛谷 P4799)',
    'public class Code02_SnacksWaysBuyTickets {',
    '    public static long ways(long[] v, long w) {',
    '        int n = v.length;',
    '        int mid = n >> 1;',
    '        long[] lsum = new long[1 << mid];',
    '        long[] rsum = new long[1 << (n - mid)];',
    '        int lsize = dfs(v, 0, mid, 0, w, lsum, 0);',
    '        int rsize = dfs(v, mid, n, 0, w, rsum, 0);',
    '        Arrays.sort(rsum, 0, rsize);',
    '        long ans = 0;',
    '        for (int i = 0; i < lsize; i++) {',
    '            ans += countLE(rsum, rsize, w - lsum[i]);',
    '        }',
    '        return ans;',
    '    }',
    '    private static int dfs(long[] v, int i, int end, long sum, long w, long[] arr, int fill) {',
    '        if (sum > w) return fill;',
    '        if (i == end) { arr[fill++] = sum; return fill; }',
    '        fill = dfs(v, i + 1, end, sum, w, arr, fill);',
    '        fill = dfs(v, i + 1, end, sum + v[i], w, arr, fill);',
    '        return fill;',
    '    }',
    '    private static int countLE(long[] arr, int size, long target) {',
    '        int l = 0, r = size - 1, ans = 0;',
    '        while (l <= r) {',
    '            int m = (l + r) >> 1;',
    '            if (arr[m] <= target) { ans = m + 1; l = m + 1; }',
    '            else { r = m - 1; }',
    '        }',
    '        return ans;',
    '    }',
    '}',
  ],
  cpp: [
    '#include <vector>',
    '#include <algorithm>',
    'using namespace std;',
    '',
    '// 牛牛的背包问题 / 冰球锦标赛 (洛谷 P4799)',
    'class Solution {',
    'public:',
    '    long long ways(vector<long long>& v, long long w) {',
    '        int n = v.size(), mid = n / 2;',
    '        vector<long long> lsum, rsum;',
    '        dfs(v, 0, mid, 0, w, lsum);',
    '        dfs(v, mid, n, 0, w, rsum);',
    '        sort(rsum.begin(), rsum.end());',
    '        long long ans = 0;',
    '        for (long long s : lsum) {',
    '            auto it = upper_bound(rsum.begin(), rsum.end(), w - s);',
    '            ans += (it - rsum.begin());',
    '        }',
    '        return ans;',
    '    }',
    '    void dfs(vector<long long>& v, int i, int end, long long sum, long long w, vector<long long>& res) {',
    '        if (sum > w) return;',
    '        if (i == end) { res.push_back(sum); return; }',
    '        dfs(v, i + 1, end, sum, w, res);',
    '        dfs(v, i + 1, end, sum + v[i], w, res);',
    '    }',
    '};',
  ],
  python: [
    'import bisect',
    '',
    'class Solution:',
    '    def ways(self, v: list[int], w: int) -> int:',
    '        n = len(v)',
    '        mid = n // 2',
    '        lsum, rsum = [], []',
    '        def dfs(i, end, cur, res):',
    '            if cur > w: return',
    '            if i == end: res.append(cur); return',
    '            dfs(i + 1, end, cur, res)',
    '            dfs(i + 1, end, cur + v[i], res)',
    '        dfs(0, mid, 0, lsum)',
    '        dfs(mid, n, 0, rsum)',
    '        rsum.sort()',
    '        ans = 0',
    '        for s in lsum:',
    '            idx = bisect.bisect_right(rsum, w - s)',
    '            ans += idx',
    '        return ans',
  ],
  javascript: [
    '// 牛牛的背包问题 - 折半搜索 (洛谷 P4799)',
    'function ways(v, w) {',
    '    const n = v.length;',
    '    const mid = Math.floor(n / 2);',
    '    const lsum = [], rsum = [];',
    '    function dfs(i, end, sum, res) {',
    '        if (sum > w) return;',
    '        if (i === end) { res.push(sum); return; }',
    '        dfs(i + 1, end, sum, res);',
    '        dfs(i + 1, end, sum + v[i], res);',
    '    }',
    '    dfs(0, mid, 0, lsum);',
    '    dfs(mid, n, 0, rsum);',
    '    rsum.sort((a, b) => a - b);',
    '    let ans = 0;',
    '    for (const s of lsum) {',
    '        let l = 0, r = rsum.length - 1, count = 0;',
    '        while (l <= r) {',
    '            const m = (l + r) >> 1;',
    '            if (rsum[m] <= w - s) { count = m + 1; l = m + 1; }',
    '            else { r = m - 1; }',
    '        }',
    '        ans += count;',
    '    }',
    '    return ans;',
    '}',
  ],
};

export const SNACKS_WAYS_063_LINES = {
  entry: { java: 6, cpp: 8, python: 4, javascript: 2 },
  divide: { java: 8, cpp: 9, python: 5, javascript: 3 },
  dfsLeft: { java: 11, cpp: 11, python: 13, javascript: 11 },
  dfsRight: { java: 12, cpp: 12, python: 14, javascript: 12 },
  sortRight: { java: 13, cpp: 13, python: 15, javascript: 13 },
  queryLoop: { java: 15, cpp: 15, python: 17, javascript: 15 },
  bisect: { java: 16, cpp: 16, python: 18, javascript: 19 },
  returnAns: { java: 18, cpp: 19, python: 20, javascript: 23 },
};

export const CLOSEST_SUBSEQUENCE_SUM_063_CODES: Record<string, string[]> = {
  java: [
    'package class063;',
    'import java.util.Arrays;',
    '',
    '// 最接近目标值的子序列和 (LeetCode 1755)',
    'public class Code03_ClosestSubsequenceSum {',
    '    public static int minAbsDifference(int[] nums, int goal) {',
    '        int n = nums.length, mid = n >> 1;',
    '        int[] lsum = new int[1 << mid];',
    '        int[] rsum = new int[1 << (n - mid)];',
    '        int lsize = dfs(nums, 0, mid, 0, lsum, 0);',
    '        int rsize = dfs(nums, mid, n, 0, rsum, 0);',
    '        Arrays.sort(lsum, 0, lsize);',
    '        Arrays.sort(rsum, 0, rsize);',
    '        int i = 0, j = rsize - 1, ans = Math.abs(goal);',
    '        while (i < lsize && j >= 0) {',
    '            int cur = lsum[i] + rsum[j];',
    '            ans = Math.min(ans, Math.abs(cur - goal));',
    '            if (cur > goal) j--;',
    '            else if (cur < goal) i++;',
    '            else return 0;',
    '        }',
    '        return ans;',
    '    }',
    '    private static int dfs(int[] nums, int i, int end, int sum, int[] arr, int fill) {',
    '        if (i == end) { arr[fill++] = sum; return fill; }',
    '        fill = dfs(nums, i + 1, end, sum, arr, fill);',
    '        fill = dfs(nums, i + 1, end, sum + nums[i], arr, fill);',
    '        return fill;',
    '    }',
    '}',
  ],
  cpp: [
    '#include <vector>',
    '#include <cmath>',
    '#include <algorithm>',
    'using namespace std;',
    '',
    '// 最接近目标值的子序列和 (LeetCode 1755)',
    'class Solution {',
    'public:',
    '    int minAbsDifference(vector<int>& nums, int goal) {',
    '        int n = nums.size(), mid = n / 2;',
    '        vector<int> lsum, rsum;',
    '        dfs(nums, 0, mid, 0, lsum);',
    '        dfs(nums, mid, n, 0, rsum);',
    '        sort(lsum.begin(), lsum.end());',
    '        sort(rsum.begin(), rsum.end());',
    '        int i = 0, j = (int)rsum.size() - 1, ans = abs(goal);',
    '        while (i < (int)lsum.size() && j >= 0) {',
    '            int cur = lsum[i] + rsum[j];',
    '            ans = min(ans, abs(cur - goal));',
    '            if (cur > goal) j--;',
    '            else if (cur < goal) i++;',
    '            else return 0;',
    '        }',
    '        return ans;',
    '    }',
    '    void dfs(vector<int>& nums, int i, int end, int sum, vector<int>& res) {',
    '        if (i == end) { res.push_back(sum); return; }',
    '        dfs(nums, i + 1, end, sum, res);',
    '        dfs(nums, i + 1, end, sum + nums[i], res);',
    '    }',
    '};',
  ],
  python: [
    'class Solution:',
    '    def minAbsDifference(self, nums: list[int], goal: int) -> int:',
    '        n = len(nums)',
    '        mid = n // 2',
    '        lsum, rsum = [], []',
    '        def dfs(i, end, s, arr):',
    '            if i == end: arr.append(s); return',
    '            dfs(i + 1, end, s, arr)',
    '            dfs(i + 1, end, s + nums[i], arr)',
    '        dfs(0, mid, 0, lsum)',
    '        dfs(mid, n, 0, rsum)',
    '        lsum.sort()',
    '        rsum.sort()',
    '        i, j = 0, len(rsum) - 1',
    '        ans = abs(goal)',
    '        while i < len(lsum) and j >= 0:',
    '            cur = lsum[i] + rsum[j]',
    '            ans = min(ans, abs(cur - goal))',
    '            if cur > goal: j -= 1',
    '            elif cur < goal: i += 1',
    '            else: return 0',
    '        return ans',
  ],
  javascript: [
    '// 最接近目标值的子序列和 (LeetCode 1755)',
    'function minAbsDifference(nums, goal) {',
    '    const n = nums.length, mid = Math.floor(n / 2);',
    '    const lsum = [], rsum = [];',
    '    function dfs(i, end, sum, res) {',
    '        if (i === end) { res.push(sum); return; }',
    '        dfs(i + 1, end, sum, res);',
    '        dfs(i + 1, end, sum + nums[i], res);',
    '    }',
    '    dfs(0, mid, 0, lsum);',
    '    dfs(mid, n, 0, rsum);',
    '    lsum.sort((a, b) => a - b);',
    '    rsum.sort((a, b) => a - b);',
    '    let i = 0, j = rsum.length - 1, ans = Math.abs(goal);',
    '    while (i < lsum.length && j >= 0) {',
    '        const cur = lsum[i] + rsum[j];',
    '        ans = Math.min(ans, Math.abs(cur - goal));',
    '        if (cur > goal) j--;',
    '        else if (cur < goal) i++;',
    '        else return 0;',
    '    }',
    '    return ans;',
    '}',
  ],
};

export const CLOSEST_SUBSEQUENCE_SUM_063_LINES = {
  entry: { java: 6, cpp: 8, python: 2, javascript: 2 },
  dfsGen: { java: 10, cpp: 11, python: 11, javascript: 9 },
  sortBoth: { java: 12, cpp: 13, python: 13, javascript: 11 },
  twoPtrInit: { java: 14, cpp: 15, python: 15, javascript: 13 },
  twoPtrLoop: { java: 15, cpp: 16, python: 17, javascript: 14 },
  updateAns: { java: 17, cpp: 18, python: 19, javascript: 16 },
  moveRight: { java: 18, cpp: 19, python: 20, javascript: 17 },
  moveLeft: { java: 19, cpp: 20, python: 21, javascript: 18 },
  returnAns: { java: 22, cpp: 23, python: 23, javascript: 21 },
};

export const PARTITION_MIN_DIFF_063_CODES: Record<string, string[]> = {
  java: [
    'package class063;',
    'import java.util.ArrayList;',
    'import java.util.Collections;',
    '',
    '// 分割数组使数组和的差最小 (LeetCode 2035)',
    'public class Code04_PartitionMinimizeDifference {',
    '    public static int minimumDifference(int[] nums) {',
    '        int n = nums.length >> 1, sum = 0;',
    '        for (int x : nums) sum += x;',
    '        ArrayList<Integer>[] lsum = new ArrayList[n + 1];',
    '        ArrayList<Integer>[] rsum = new ArrayList[n + 1];',
    '        for (int k = 0; k <= n; k++) {',
    '            lsum[k] = new ArrayList<>();',
    '            rsum[k] = new ArrayList<>();',
    '        }',
    '        dfs(nums, 0, n, 0, 0, lsum);',
    '        dfs(nums, n, n << 1, 0, 0, rsum);',
    '        for (int k = 0; k <= n; k++) Collections.sort(rsum[k]);',
    '        int ans = Integer.MAX_VALUE;',
    '        for (int k = 0; k <= n; k++) {',
    '            ArrayList<Integer> leftList = lsum[k];',
    '            ArrayList<Integer> rightList = rsum[n - k];',
    '            for (int a : leftList) {',
    '                int target = (sum >> 1) - a;',
    '                int idx = bisect(rightList, target);',
    '                if (idx < rightList.size()) ans = Math.min(ans, Math.abs(sum - 2 * (a + rightList.get(idx))));',
    '                if (idx > 0) ans = Math.min(ans, Math.abs(sum - 2 * (a + rightList.get(idx - 1))));',
    '            }',
    '        }',
    '        return ans;',
    '    }',
    '    private static void dfs(int[] nums, int i, int end, int k, int cur, ArrayList<Integer>[] map) {',
    '        if (i == end) { map[k].add(cur); return; }',
    '        dfs(nums, i + 1, end, k, cur, map);',
    '        dfs(nums, i + 1, end, k + 1, cur + nums[i], map);',
    '    }',
    '    private static int bisect(ArrayList<Integer> list, int target) {',
    '        int l = 0, r = list.size() - 1, res = list.size();',
    '        while (l <= r) {',
    '            int m = (l + r) >> 1;',
    '            if (list.get(m) >= target) { res = m; r = m - 1; }',
    '            else l = m + 1;',
    '        }',
    '        return res;',
    '    }',
    '}',
  ],
  cpp: [
    '#include <vector>',
    '#include <cmath>',
    '#include <algorithm>',
    'using namespace std;',
    '',
    '// 分割数组使数组和的差最小 (LeetCode 2035)',
    'class Solution {',
    'public:',
    '    int minimumDifference(vector<int>& nums) {',
    '        int n = nums.size() / 2, sum = 0;',
    '        for (int x : nums) sum += x;',
    '        vector<vector<int>> lsum(n + 1), rsum(n + 1);',
    '        dfs(nums, 0, n, 0, 0, lsum);',
    '        dfs(nums, n, 2 * n, 0, 0, rsum);',
    '        for (int k = 0; k <= n; k++) sort(rsum[k].begin(), rsum[k].end());',
    '        int ans = 1e9;',
    '        for (int k = 0; k <= n; k++) {',
    '            int targetK = n - k;',
    '            for (int a : lsum[k]) {',
    '                int target = (sum / 2) - a;',
    '                auto it = lower_bound(rsum[targetK].begin(), rsum[targetK].end(), target);',
    '                if (it != rsum[targetK].end()) ans = min(ans, abs(sum - 2 * (a + *it)));',
    '                if (it != rsum[targetK].begin()) ans = min(ans, abs(sum - 2 * (a + *prev(it))));',
    '            }',
    '        }',
    '        return ans;',
    '    }',
    '    void dfs(vector<int>& nums, int i, int end, int k, int cur, vector<vector<int>>& map) {',
    '        if (i == end) { map[k].push_back(cur); return; }',
    '        dfs(nums, i + 1, end, k, cur, map);',
    '        dfs(nums, i + 1, end, k + 1, cur + nums[i], map);',
    '    }',
    '};',
  ],
  python: [
    'import bisect',
    '',
    'class Solution:',
    '    def minimumDifference(self, nums: list[int]) -> int:',
    '        n = len(nums) // 2',
    '        total = sum(nums)',
    '        lsum = [[] for _ in range(n + 1)]',
    '        rsum = [[] for _ in range(n + 1)]',
    '        def dfs(i, end, k, cur, bucket):',
    '            if i == end: bucket[k].append(cur); return',
    '            dfs(i + 1, end, k, cur, bucket)',
    '            dfs(i + 1, end, k + 1, cur + nums[i], bucket)',
    '        dfs(0, n, 0, 0, lsum)',
    '        dfs(n, 2 * n, 0, 0, rsum)',
    '        for k in range(n + 1): rsum[k].sort()',
    '        ans = float("inf")',
    '        for k in range(n + 1):',
    '            for a in lsum[k]:',
    '                target = (total // 2) - a',
    '                idx = bisect.bisect_left(rsum[n - k], target)',
    '                if idx < len(rsum[n - k]): ans = min(ans, abs(total - 2 * (a + rsum[n - k][idx])))',
    '                if idx > 0: ans = min(ans, abs(total - 2 * (a + rsum[n - k][idx - 1])))',
    '        return ans',
  ],
  javascript: [
    '// 分割数组使和差最小 (LeetCode 2035)',
    'function minimumDifference(nums) {',
    '    const n = nums.length >> 1;',
    '    const sum = nums.reduce((a, b) => a + b, 0);',
    '    const lsum = Array.from({ length: n + 1 }, () => []);',
    '    const rsum = Array.from({ length: n + 1 }, () => []);',
    '    function dfs(i, end, k, cur, bucket) {',
    '        if (i === end) { bucket[k].push(cur); return; }',
    '        dfs(i + 1, end, k, cur, bucket);',
    '        dfs(i + 1, end, k + 1, cur + nums[i], bucket);',
    '    }',
    '    dfs(0, n, 0, 0, lsum);',
    '    dfs(n, 2 * n, 0, 0, rsum);',
    '    for (let k = 0; k <= n; k++) rsum[k].sort((a, b) => a - b);',
    '    let ans = Infinity;',
    '    for (let k = 0; k <= n; k++) {',
    '        for (const a of lsum[k]) {',
    '            const target = Math.floor(sum / 2) - a;',
    '            const list = rsum[n - k];',
    '            let l = 0, r = list.length - 1, idx = list.length;',
    '            while (l <= r) {',
    '                const m = (l + r) >> 1;',
    '                if (list[m] >= target) { idx = m; r = m - 1; }',
    '                else l = m + 1;',
    '            }',
    '            if (idx < list.length) ans = Math.min(ans, Math.abs(sum - 2 * (a + list[idx])));',
    '            if (idx > 0) ans = Math.min(ans, Math.abs(sum - 2 * (a + list[idx - 1])));',
    '        }',
    '    }',
    '    return ans;',
    '}',
  ],
};

export const PARTITION_MIN_DIFF_063_LINES = {
  entry: { java: 6, cpp: 8, python: 4, javascript: 2 },
  initBuckets: { java: 11, cpp: 10, python: 6, javascript: 4 },
  dfsLeftCount: { java: 14, cpp: 11, python: 12, javascript: 11 },
  dfsRightCount: { java: 15, cpp: 12, python: 13, javascript: 12 },
  sortBuckets: { java: 16, cpp: 13, python: 14, javascript: 13 },
  pairLoop: { java: 18, cpp: 15, python: 16, javascript: 15 },
  bisectBucket: { java: 22, cpp: 19, python: 19, javascript: 18 },
  returnAns: { java: 27, cpp: 24, python: 22, javascript: 28 },
};
