/**
 * Class 056: 并查集·上 四语言完整工业级源码与精准 1-based 行号映射
 */

import { HighlightTarget } from '../../../../core/renderers/dark-code-terminal-presenter';

export interface CodeMapping {
  java: number;
  cpp: number;
  python: number;
  javascript: number;
}

// -------------------------------------------------------------
// Code01/02: 并查集模版与路径压缩 (Union-Find Template)
// -------------------------------------------------------------
export const CODE01_UNION_FIND_CODES: Record<string, string[]> = {
  java: [
    'public class UnionFindLuogu {',
    '    public static int MAXN = 10001;',
    '    public static int[] father = new int[MAXN];',
    '    public static void build(int n) {',
    '        for (int i = 1; i <= n; i++) father[i] = i;',
    '    }',
    '    // 路径压缩：向上攀爬后将沿途所有节点直接挂载到根代表元下方',
    '    public static int find(int i) {',
    '        if (i != father[i]) {',
    '            father[i] = find(father[i]);',
    '        }',
    '        return father[i];',
    '    }',
    '    public static boolean isSameSet(int x, int y) {',
    '        return find(x) == find(y);',
    '    }',
    '    public static void union(int x, int y) {',
    '        father[find(x)] = find(y);',
    '    }',
    '}',
  ],
  cpp: [
    'class UnionFind {',
    '    vector<int> father;',
    'public:',
    '    UnionFind(int n) : father(n + 1) {',
    '        for (int i = 1; i <= n; i++) father[i] = i;',
    '    }',
    '    int find(int i) {',
    '        if (i != father[i]) father[i] = find(father[i]);',
    '        return father[i];',
    '    }',
    '    bool isSameSet(int x, int y) { return find(x) == find(y); }',
    '    void unionSet(int x, int y) { father[find(x)] = find(y); }',
    '};',
  ],
  python: [
    'class UnionFind:',
    '    def __init__(self, n: int):',
    '        self.father = list(range(n + 1))',
    '',
    '    def find(self, i: int) -> int:',
    '        if i != self.father[i]:',
    '            self.father[i] = self.find(self.father[i])',
    '        return self.father[i]',
    '',
    '    def is_same_set(self, x: int, y: int) -> bool:',
    '        return self.find(x) == self.find(y)',
    '',
    '    def union(self, x: int, y: int) -> None:',
    '        self.father[self.find(x)] = self.find(y)',
  ],
  javascript: [
    'class UnionFind {',
    '    constructor(n) {',
    '        this.father = Array.from({ length: n + 1 }, (_, i) => i);',
    '    }',
    '    find(i) {',
    '        if (i !== this.father[i]) {',
    '            this.father[i] = this.find(this.father[i]);',
    '        }',
    '        return this.father[i];',
    '    }',
    '    isSameSet(x, y) { return this.find(x) === this.find(y); }',
    '    union(x, y) { this.father[this.find(x)] = this.find(y); }',
    '}',
  ],
};

export const CODE01_UNION_FIND_LINES: Record<string, CodeMapping> = {
  build:      { java: 4, cpp: 4, python: 2, javascript: 2 },
  find:       { java: 8, cpp: 7, python: 5, javascript: 5 },
  compress:   { java: 10, cpp: 8, python: 7, javascript: 7 },
  isSame:     { java: 14, cpp: 11, python: 10, javascript: 11 },
  union:      { java: 17, cpp: 12, python: 13, javascript: 12 },
};

// -------------------------------------------------------------
// Code03: 情侣牵手与置换环定理 (Couples Holding Hands)
// -------------------------------------------------------------
export const CODE03_COUPLES_CODES: Record<string, string[]> = {
  java: [
    'public class CouplesHoldingHands {',
    '    public static int[] father;',
    '    public static int sets;',
    '    public static int minSwapsCouples(int[] row) {',
    '        int n = row.length / 2;',
    '        father = new int[n];',
    '        for (int i = 0; i < n; i++) father[i] = i;',
    '        sets = n;',
    '        for (int i = 0; i < row.length; i += 2) {',
    '            union(row[i] / 2, row[i + 1] / 2); // 相邻情侣对连边',
    '        }',
    '        return n - sets; // 置换环定理: 交换次数 = N - Sets',
    '    }',
    '    public static int find(int i) {',
    '        if (i != father[i]) father[i] = find(father[i]);',
    '        return father[i];',
    '    }',
    '    public static void union(int x, int y) {',
    '        int fx = find(x), fy = find(y);',
    '        if (fx != fy) { father[fx] = fy; sets--; }',
    '    }',
    '}',
  ],
  cpp: [
    'class Solution {',
    '    vector<int> father; int sets;',
    '    int find(int i) {',
    '        if (i != father[i]) father[i] = find(father[i]);',
    '        return father[i];',
    '    }',
    '    void unionSet(int x, int y) {',
    '        int fx = find(x), fy = find(y);',
    '        if (fx != fy) { father[fx] = fy; sets--; }',
    '    }',
    'public:',
    '    int minSwapsCouples(vector<int>& row) {',
    '        int n = row.size() / 2; sets = n; father.resize(n);',
    '        for (int i = 0; i < n; i++) father[i] = i;',
    '        for (int i = 0; i < row.size(); i += 2) {',
    '            unionSet(row[i] / 2, row[i + 1] / 2);',
    '        }',
    '        return n - sets;',
    '    }',
    '};',
  ],
  python: [
    'class Solution:',
    '    def minSwapsCouples(self, row: list[int]) -> int:',
    '        n = len(row) // 2',
    '        father = list(range(n))',
    '        sets = n',
    '',
    '        def find(i: int) -> int:',
    '            if i != father[i]:',
    '                father[i] = find(father[i])',
    '            return father[i]',
    '',
    '        def union(x: int, y: int):',
    '            nonlocal sets',
    '            fx, fy = find(x), find(y)',
    '            if fx != fy:',
    '                father[fx] = fy',
    '                sets -= 1',
    '',
    '        for i in range(0, len(row), 2):',
    '            union(row[i] // 2, row[i + 1] // 2)',
    '        return n - sets',
  ],
  javascript: [
    'function minSwapsCouples(row) {',
    '    const n = row.length / 2;',
    '    const father = Array.from({ length: n }, (_, i) => i);',
    '    let sets = n;',
    '    function find(i) {',
    '        if (i !== father[i]) father[i] = find(father[i]);',
    '        return father[i];',
    '    }',
    '    function union(x, y) {',
    '        const fx = find(x), fy = find(y);',
    '        if (fx !== fy) { father[fx] = fy; sets--; }',
    '    }',
    '    for (let i = 0; i < row.length; i += 2) {',
    '        union(Math.floor(row[i] / 2), Math.floor(row[i + 1] / 2));',
    '    }',
    '    return n - sets;',
    '}',
  ],
};

export const CODE03_COUPLES_LINES: Record<string, CodeMapping> = {
  entry:      { java: 4, cpp: 13, python: 2, javascript: 1 },
  build:      { java: 7, cpp: 15, python: 4, javascript: 3 },
  loopCouples:{ java: 9, cpp: 16, python: 19, javascript: 13 },
  union:      { java: 10, cpp: 17, python: 20, javascript: 14 },
  returnAns:  { java: 12, cpp: 19, python: 21, javascript: 16 },
};

// -------------------------------------------------------------
// Code04: 相似字符串组 (Similar String Groups)
// -------------------------------------------------------------
export const CODE04_SIMILAR_STRINGS_CODES: Record<string, string[]> = {
  java: [
    'public class SimilarStringGroups {',
    '    public static int[] father;',
    '    public static int sets;',
    '    public static int numSimilarGroups(String[] strs) {',
    '        int n = strs.length, m = strs[0].length();',
    '        father = new int[n]; sets = n;',
    '        for (int i = 0; i < n; i++) father[i] = i;',
    '        for (int i = 0; i < n; i++) {',
    '            for (int j = i + 1; j < n; j++) {',
    '                if (find(i) != find(j) && isSimilar(strs[i], strs[j], m)) {',
    '                    union(i, j);',
    '                }',
    '            }',
    '        }',
    '        return sets;',
    '    }',
    '    private static boolean isSimilar(String a, String b, int m) {',
    '        int diff = 0;',
    '        for (int i = 0; i < m && diff <= 2; i++) {',
    '            if (a.charAt(i) != b.charAt(i)) diff++;',
    '        }',
    '        return diff == 0 || diff == 2; // 0处或2处不同为相似',
    '    }',
    '    private static int find(int i) {',
    '        if (i != father[i]) father[i] = find(father[i]);',
    '        return father[i];',
    '    }',
    '    private static void union(int x, int y) {',
    '        father[find(x)] = find(y); sets--;',
    '    }',
    '}',
  ],
  cpp: [
    'class Solution {',
    '    vector<int> father; int sets;',
    '    int find(int i) {',
    '        if (i != father[i]) father[i] = find(father[i]);',
    '        return father[i];',
    '    }',
    '    bool isSimilar(const string& a, const string& b) {',
    '        int diff = 0;',
    '        for (int i = 0; i < a.size() && diff <= 2; i++) {',
    '            if (a[i] != b[i]) diff++;',
    '        }',
    '        return diff == 0 || diff == 2;',
    '    }',
    'public:',
    '    int numSimilarGroups(vector<string>& strs) {',
    '        int n = strs.size(); sets = n; father.resize(n);',
    '        for (int i = 0; i < n; i++) father[i] = i;',
    '        for (int i = 0; i < n; i++) {',
    '            for (int j = i + 1; j < n; j++) {',
    '                if (find(i) != find(j) && isSimilar(strs[i], strs[j])) {',
    '                    father[find(i)] = find(j); sets--;',
    '                }',
    '            }',
    '        }',
    '        return sets;',
    '    }',
    '};',
  ],
  python: [
    'class Solution:',
    '    def numSimilarGroups(self, strs: list[str]) -> int:',
    '        n, m = len(strs), len(strs[0])',
    '        father = list(range(n))',
    '        sets = n',
    '',
    '        def find(i: int) -> int:',
    '            if i != father[i]:',
    '                father[i] = find(father[i])',
    '            return father[i]',
    '',
    '        def is_similar(a: str, b: str) -> bool:',
    '            diff = sum(ca != cb for ca, cb in zip(a, b))',
    '            return diff == 0 or diff == 2',
    '',
    '        for i in range(n):',
    '            for j in range(i + 1, n):',
    '                if find(i) != find(j) and is_similar(strs[i], strs[j]):',
    '                    father[find(i)] = find(j)',
    '                    sets -= 1',
    '        return sets',
  ],
  javascript: [
    'function numSimilarGroups(strs) {',
    '    const n = strs.length, m = strs[0].length;',
    '    const father = Array.from({ length: n }, (_, i) => i);',
    '    let sets = n;',
    '    function find(i) {',
    '        if (i !== father[i]) father[i] = find(father[i]);',
    '        return father[i];',
    '    }',
    '    function isSimilar(a, b) {',
    '        let diff = 0;',
    '        for (let i = 0; i < m && diff <= 2; i++) {',
    '            if (a[i] !== b[i]) diff++;',
    '        }',
    '        return diff === 0 || diff === 2;',
    '    }',
    '    for (let i = 0; i < n; i++) {',
    '        for (let j = i + 1; j < n; j++) {',
    '            if (find(i) !== find(j) && isSimilar(strs[i], strs[j])) {',
    '                father[find(i)] = find(j); sets--;',
    '            }',
    '        }',
    '    }',
    '    return sets;',
    '}',
  ],
};

export const CODE04_SIMILAR_STRINGS_LINES: Record<string, CodeMapping> = {
  entry:       { java: 4, cpp: 16, python: 2, javascript: 1 },
  build:       { java: 7, cpp: 18, python: 4, javascript: 3 },
  pairLoop:    { java: 8, cpp: 19, python: 16, javascript: 14 },
  checkSimilar:{ java: 17, cpp: 7, python: 13, javascript: 8 },
  union:       { java: 11, cpp: 21, python: 19, javascript: 16 },
  returnAns:   { java: 15, cpp: 26, python: 21, javascript: 20 },
};

// -------------------------------------------------------------
// Code05: 岛屿数量并查集二维合并 (Number of Islands)
// -------------------------------------------------------------
export const CODE05_ISLANDS_UF_CODES: Record<string, string[]> = {
  java: [
    'public class NumberOfIslandsUnionFind {',
    '    public static int[] father;',
    '    public static int sets;',
    '    public static int numIslands(char[][] grid) {',
    '        int n = grid.length, m = grid[0].length;',
    '        father = new int[n * m]; sets = 0;',
    '        for (int r = 0; r < n; r++) {',
    '            for (int c = 0; c < m; c++) {',
    '                if (grid[r][c] == \'1\') {',
    '                    int id = r * m + c;',
    '                    father[id] = id; sets++;',
    '                }',
    '            }',
    '        }',
    '        for (int r = 0; r < n; r++) {',
    '            for (int c = 0; c < m; c++) {',
    '                if (grid[r][c] == \'1\') {',
    '                    if (c > 0 && grid[r][c - 1] == \'1\') union(r * m + c, r * m + c - 1); // 向左连',
    '                    if (r > 0 && grid[r - 1][c] == \'1\') union(r * m + c, (r - 1) * m + c); // 向上连',
    '                }',
    '            }',
    '        }',
    '        return sets;',
    '    }',
    '    private static int find(int i) {',
    '        if (i != father[i]) father[i] = find(father[i]);',
    '        return father[i];',
    '    }',
    '    private static void union(int x, int y) {',
    '        int fx = find(x), fy = find(y);',
    '        if (fx != fy) { father[fx] = fy; sets--; }',
    '    }',
    '}',
  ],
  cpp: [
    'class Solution {',
    '    vector<int> father; int sets = 0;',
    '    int find(int i) {',
    '        if (i != father[i]) father[i] = find(father[i]);',
    '        return father[i];',
    '    }',
    '    void unionSet(int x, int y) {',
    '        int fx = find(x), fy = find(y);',
    '        if (fx != fy) { father[fx] = fy; sets--; }',
    '    }',
    'public:',
    '    int numIslands(vector<vector<char>>& grid) {',
    '        int n = grid.size(), m = grid[0].size();',
    '        father.resize(n * m);',
    '        for (int r = 0; r < n; r++) {',
    '            for (int c = 0; c < m; c++) {',
    '                if (grid[r][c] == \'1\') {',
    '                    int id = r * m + c; father[id] = id; sets++;',
    '                }',
    '            }',
    '        }',
    '        for (int r = 0; r < n; r++) {',
    '            for (int c = 0; c < m; c++) {',
    '                if (grid[r][c] == \'1\') {',
    '                    if (c > 0 && grid[r][c - 1] == \'1\') unionSet(r * m + c, r * m + c - 1);',
    '                    if (r > 0 && grid[r - 1][c] == \'1\') unionSet(r * m + c, (r - 1) * m + c);',
    '                }',
    '            }',
    '        }',
    '        return sets;',
    '    }',
    '};',
  ],
  python: [
    'class Solution:',
    '    def numIslands(self, grid: list[list[str]]) -> int:',
    '        n, m = len(grid), len(grid[0])',
    '        father = list(range(n * m))',
    '        sets = 0',
    '',
    '        def find(i: int) -> int:',
    '            if i != father[i]:',
    '                father[i] = find(father[i])',
    '            return father[i]',
    '',
    '        def union(x: int, y: int):',
    '            nonlocal sets',
    '            fx, fy = find(x), find(y)',
    '            if fx != fy:',
    '                father[fx] = fy',
    '                sets -= 1',
    '',
    '        for r in range(n):',
    '            for c in range(m):',
    '                if grid[r][c] == "1":',
    '                    sets += 1',
    '',
    '        for r in range(n):',
    '            for c in range(m):',
    '                if grid[r][c] == "1":',
    '                    if c > 0 and grid[r][c - 1] == "1":',
    '                        union(r * m + c, r * m + c - 1)',
    '                    if r > 0 and grid[r - 1][c] == "1":',
    '                        union(r * m + c, (r - 1) * m + c)',
    '        return sets',
  ],
  javascript: [
    'function numIslands(grid) {',
    '    const n = grid.length, m = grid[0].length;',
    '    const father = new Array(n * m);',
    '    let sets = 0;',
    '    for (let r = 0; r < n; r++) {',
    '        for (let c = 0; c < m; c++) {',
    '            if (grid[r][c] === "1") {',
    '                const id = r * m + c; father[id] = id; sets++;',
    '            }',
    '        }',
    '    }',
    '    function find(i) {',
    '        if (i !== father[i]) father[i] = find(father[i]);',
    '        return father[i];',
    '    }',
    '    function union(x, y) {',
    '        const fx = find(x), fy = find(y);',
    '        if (fx !== fy) { father[fx] = fy; sets--; }',
    '    }',
    '    for (let r = 0; r < n; r++) {',
    '        for (let c = 0; c < m; c++) {',
    '            if (grid[r][c] === "1") {',
    '                if (c > 0 && grid[r][c - 1] === "1") union(r * m + c, r * m + c - 1);',
    '                if (r > 0 && grid[r - 1][c] === "1") union(r * m + c, (r - 1) * m + c);',
    '            }',
    '        }',
    '    }',
    '    return sets;',
    '}',
  ],
};

export const CODE05_ISLANDS_UF_LINES: Record<string, CodeMapping> = {
  entry:       { java: 4, cpp: 13, python: 2, javascript: 1 },
  initLands:   { java: 11, cpp: 19, python: 22, javascript: 8 },
  scanGrid:    { java: 16, cpp: 23, python: 25, javascript: 18 },
  unionLeft:   { java: 18, cpp: 25, python: 28, javascript: 20 },
  unionUp:     { java: 19, cpp: 26, python: 30, javascript: 21 },
  returnAns:   { java: 23, cpp: 30, python: 31, javascript: 24 },
};
