/**
 * 左程云算法通关课 Class 061: 最短路全解专题
 * Java / C++ / Python / JavaScript 四语言代码与 1-based 精准行号映射
 */

// ==========================================
// 1. Code01: 朴素 Dijkstra (O(V²))
// ==========================================
export const DIJKSTRA_BASIC_061_CODES = {
  cpp: [
    '#include <vector>',
    '#include <algorithm>',
    'using namespace std;',
    '',
    'vector<int> dijkstraBasic(int n, int s, vector<vector<pair<int, int>>>& adj) {',
    '    vector<int> dist(n, 1e9);',
    '    vector<bool> visited(n, false);',
    '    dist[s] = 0;',
    '    for (int i = 0; i < n; ++i) {',
    '        int u = -1;',
    '        for (int j = 0; j < n; ++j) {',
    '            if (!visited[j] && (u == -1 || dist[j] < dist[u])) {',
    '                u = j;',
    '            }',
    '        }',
    '        if (u == -1 || dist[u] == 1e9) break;',
    '        visited[u] = true;',
    '        for (auto& [v, w] : adj[u]) {',
    '            if (dist[u] + w < dist[v]) {',
    '                dist[v] = dist[u] + w;',
    '            }',
    '        }',
    '    }',
    '    return dist;',
    '}',
  ],
  java: [
    'package class061;',
    'import java.util.*;',
    '',
    'public class Code01_DijkstraBasic {',
    '    public static int[] dijkstraBasic(int n, int s, List<List<int[]>> adj) {',
    '        int[] dist = new int[n];',
    '        Arrays.fill(dist, Integer.MAX_VALUE);',
    '        boolean[] visited = new boolean[n];',
    '        dist[s] = 0;',
    '        for (int i = 0; i < n; i++) {',
    '            int u = -1;',
    '            for (int j = 0; j < n; j++) {',
    '                if (!visited[j] && (u == -1 || dist[j] < dist[u])) {',
    '                    u = j;',
    '                }',
    '            }',
    '            if (u == -1 || dist[u] == Integer.MAX_VALUE) break;',
    '            visited[u] = true;',
    '            for (int[] edge : adj.get(u)) {',
    '                int v = edge[0], w = edge[1];',
    '                if (dist[u] + w < dist[v]) {',
    '                    dist[v] = dist[u] + w;',
    '                }',
    '            }',
    '        }',
    '        return dist;',
    '    }',
    '}',
  ],
  python: [
    'def dijkstra_basic(n: int, s: int, adj: dict) -> list[int]:',
    '    dist = [float("inf")] * n',
    '    visited = [False] * n',
    '    dist[s] = 0',
    '    for _ in range(n):',
    '        u = -1',
    '        for j in range(n):',
    '            if not visited[j] and (u == -1 or dist[j] < dist[u]):',
    '                u = j',
    '        if u == -1 or dist[u] == float("inf"):',
    '            break',
    '        visited[u] = True',
    '        for v, w in adj.get(u, []):',
    '            if dist[u] + w < dist[v]:',
    '                dist[v] = dist[u] + w',
    '    return dist',
  ],
  javascript: [
    'function dijkstraBasic(n, s, adj) {',
    '  const dist = new Array(n).fill(Infinity);',
    '  const visited = new Array(n).fill(false);',
    '  dist[s] = 0;',
    '  for (let i = 0; i < n; i++) {',
    '    let u = -1;',
    '    for (let j = 0; j < n; j++) {',
    '      if (!visited[j] && (u === -1 || dist[j] < dist[u])) {',
    '        u = j;',
    '      }',
    '    }',
    '    if (u === -1 || dist[u] === Infinity) break;',
    '    visited[u] = true;',
    '    for (const [v, w] of adj[u]) {',
    '      if (dist[u] + w < dist[v]) {',
    '        dist[v] = dist[u] + w;',
    '      }',
    '    }',
    '  }',
    '  return dist;',
    '}',
  ],
};

export const DIJKSTRA_BASIC_061_LINES = {
  init: { cpp: 6, java: 6, python: 2, javascript: 2 },
  findMin: { cpp: 10, java: 11, python: 6, javascript: 6 },
  lockNode: { cpp: 17, java: 18, python: 12, javascript: 13 },
  relaxEdge: { cpp: 19, java: 21, python: 14, javascript: 15 },
  returnDist: { cpp: 24, java: 26, python: 17, javascript: 20 },
};

// ==========================================
// 2. Code02: 堆优化 Dijkstra (O(E log V))
// ==========================================
export const DIJKSTRA_HEAP_061_CODES = {
  cpp: [
    '#include <vector>',
    '#include <queue>',
    'using namespace std;',
    '',
    'vector<int> dijkstraHeap(int n, int s, vector<vector<pair<int, int>>>& adj) {',
    '    vector<int> dist(n, 1e9);',
    '    vector<bool> visited(n, false);',
    '    priority_queue<pair<int, int>, vector<pair<int, int>>, greater<>> pq;',
    '    dist[s] = 0;',
    '    pq.push({0, s});',
    '    while (!pq.empty()) {',
    '        auto [d, u] = pq.top(); pq.pop();',
    '        if (visited[u]) continue;',
    '        visited[u] = true;',
    '        for (auto& [v, w] : adj[u]) {',
    '            if (dist[u] + w < dist[v]) {',
    '                dist[v] = dist[u] + w;',
    '                pq.push({dist[v], v});',
    '            }',
    '        }',
    '    }',
    '    return dist;',
    '}',
  ],
  java: [
    'package class061;',
    'import java.util.*;',
    '',
    'public class Code02_DijkstraHeap {',
    '    public static int[] dijkstraHeap(int n, int s, List<List<int[]>> adj) {',
    '        int[] dist = new int[n];',
    '        Arrays.fill(dist, Integer.MAX_VALUE);',
    '        boolean[] visited = new boolean[n];',
    '        PriorityQueue<int[]> pq = new PriorityQueue<>((a, b) -> a[0] - b[0]);',
    '        dist[s] = 0;',
    '        pq.offer(new int[]{0, s});',
    '        while (!pq.isEmpty()) {',
    '            int[] cur = pq.poll();',
    '            int d = cur[0], u = cur[1];',
    '            if (visited[u]) continue;',
    '            visited[u] = true;',
    '            for (int[] edge : adj.get(u)) {',
    '                int v = edge[0], w = edge[1];',
    '                if (dist[u] + w < dist[v]) {',
    '                    dist[v] = dist[u] + w;',
    '                    pq.offer(new int[]{dist[v], v});',
    '                }',
    '            }',
    '        }',
    '        return dist;',
    '    }',
    '}',
  ],
  python: [
    'import heapq',
    '',
    'def dijkstra_heap(n: int, s: int, adj: dict) -> list[int]:',
    '    dist = [float("inf")] * n',
    '    visited = [False] * n',
    '    dist[s] = 0',
    '    pq = [(0, s)]',
    '    while pq:',
    '        d, u = heapq.heappop(pq)',
    '        if visited[u]:',
    '            continue',
    '        visited[u] = True',
    '        for v, w in adj.get(u, []):',
    '            if dist[u] + w < dist[v]:',
    '                dist[v] = dist[u] + w',
    '                heapq.heappush(pq, (dist[v], v))',
    '    return dist',
  ],
  javascript: [
    'function dijkstraHeap(n, s, adj) {',
    '  const dist = new Array(n).fill(Infinity);',
    '  const visited = new Array(n).fill(false);',
    '  dist[s] = 0;',
    '  const pq = [[0, s]];',
    '  while (pq.length > 0) {',
    '    pq.sort((a, b) => a[0] - b[0]);',
    '    const [d, u] = pq.shift();',
    '    if (visited[u]) continue;',
    '    visited[u] = true;',
    '    for (const [v, w] of adj[u]) {',
    '      if (dist[u] + w < dist[v]) {',
    '        dist[v] = dist[u] + w;',
    '        pq.push([dist[v], v]);',
    '      }',
    '    }',
    '  }',
    '  return dist;',
    '}',
  ],
};

export const DIJKSTRA_HEAP_061_LINES = {
  init: { cpp: 6, java: 6, python: 4, javascript: 2 },
  pollNode: { cpp: 12, java: 13, python: 9, javascript: 8 },
  skipVisited: { cpp: 13, java: 15, python: 10, javascript: 9 },
  lockNode: { cpp: 14, java: 16, python: 12, javascript: 10 },
  relaxEdge: { cpp: 16, java: 19, python: 14, javascript: 12 },
  returnDist: { cpp: 22, java: 25, python: 17, javascript: 18 },
};

// ==========================================
// 3. Code03: Bellman-Ford 算法 (全边 V-1 轮松弛)
// ==========================================
export const BELLMAN_FORD_061_CODES = {
  cpp: [
    '#include <vector>',
    '#include <algorithm>',
    'using namespace std;',
    '',
    'vector<int> bellmanFord(int n, int s, vector<vector<int>>& edges) {',
    '    vector<int> dist(n, 1e9);',
    '    dist[s] = 0;',
    '    for (int k = 1; k < n; ++k) {',
    '        bool updated = false;',
    '        for (auto& e : edges) {',
    '            int u = e[0], v = e[1], w = e[2];',
    '            if (dist[u] != 1e9 && dist[u] + w < dist[v]) {',
    '                dist[v] = dist[u] + w;',
    '                updated = true;',
    '            }',
    '        }',
    '        if (!updated) break;',
    '    }',
    '    return dist;',
    '}',
  ],
  java: [
    'package class061;',
    'import java.util.*;',
    '',
    'public class Code03_BellmanFord {',
    '    public static int[] bellmanFord(int n, int s, int[][] edges) {',
    '        int[] dist = new int[n];',
    '        Arrays.fill(dist, Integer.MAX_VALUE);',
    '        dist[s] = 0;',
    '        for (int k = 1; k < n; k++) {',
    '            boolean updated = false;',
    '            for (int[] e : edges) {',
    '                int u = e[0], v = e[1], w = e[2];',
    '                if (dist[u] != Integer.MAX_VALUE && dist[u] + w < dist[v]) {',
    '                    dist[v] = dist[u] + w;',
    '                    updated = true;',
    '                }',
    '            }',
    '            if (!updated) break;',
    '        }',
    '        return dist;',
    '    }',
    '}',
  ],
  python: [
    'def bellman_ford(n: int, s: int, edges: list[list[int]]) -> list[int]:',
    '    dist = [float("inf")] * n',
    '    dist[s] = 0',
    '    for _ in range(1, n):',
    '        updated = False',
    '        for u, v, w in edges:',
    '            if dist[u] != float("inf") and dist[u] + w < dist[v]:',
    '                dist[v] = dist[u] + w',
    '                updated = True',
    '        if not updated:',
    '            break',
    '    return dist',
  ],
  javascript: [
    'function bellmanFord(n, s, edges) {',
    '  const dist = new Array(n).fill(Infinity);',
    '  dist[s] = 0;',
    '  for (let k = 1; k < n; k++) {',
    '    let updated = false;',
    '    for (const [u, v, w] of edges) {',
    '      if (dist[u] !== Infinity && dist[u] + w < dist[v]) {',
    '        dist[v] = dist[u] + w;',
    '        updated = true;',
    '      }',
    '    }',
    '    if (!updated) break;',
    '  }',
    '  return dist;',
    '}',
  ],
};

export const BELLMAN_FORD_061_LINES = {
  init: { cpp: 6, java: 6, python: 2, javascript: 2 },
  roundLoop: { cpp: 8, java: 9, python: 4, javascript: 4 },
  relaxEdge: { cpp: 12, java: 13, python: 7, javascript: 7 },
  earlyBreak: { cpp: 17, java: 18, python: 10, javascript: 12 },
  returnDist: { cpp: 19, java: 20, python: 12, javascript: 14 },
};

// ==========================================
// 4. Code04: SPFA 算法 (队列优化)
// ==========================================
export const SPFA_061_CODES = {
  cpp: [
    '#include <vector>',
    '#include <queue>',
    'using namespace std;',
    '',
    'vector<int> spfa(int n, int s, vector<vector<pair<int, int>>>& adj) {',
    '    vector<int> dist(n, 1e9);',
    '    vector<bool> inQueue(n, false);',
    '    queue<int> q;',
    '    dist[s] = 0;',
    '    q.push(s);',
    '    inQueue[s] = true;',
    '    while (!q.empty()) {',
    '        int u = q.front(); q.pop();',
    '        inQueue[u] = false;',
    '        for (auto& [v, w] : adj[u]) {',
    '            if (dist[u] + w < dist[v]) {',
    '                dist[v] = dist[u] + w;',
    '                if (!inQueue[v]) {',
    '                    q.push(v);',
    '                    inQueue[v] = true;',
    '                }',
    '            }',
    '        }',
    '    }',
    '    return dist;',
    '}',
  ],
  java: [
    'package class061;',
    'import java.util.*;',
    '',
    'public class Code04_SPFA {',
    '    public static int[] spfa(int n, int s, List<List<int[]>> adj) {',
    '        int[] dist = new int[n];',
    '        Arrays.fill(dist, Integer.MAX_VALUE);',
    '        boolean[] inQueue = new boolean[n];',
    '        Queue<Integer> q = new LinkedList<>();',
    '        dist[s] = 0;',
    '        q.offer(s);',
    '        inQueue[s] = true;',
    '        while (!q.isEmpty()) {',
    '            int u = q.poll();',
    '            inQueue[u] = false;',
    '            for (int[] edge : adj.get(u)) {',
    '                int v = edge[0], w = edge[1];',
    '                if (dist[u] + w < dist[v]) {',
    '                    dist[v] = dist[u] + w;',
    '                    if (!inQueue[v]) {',
    '                        q.offer(v);',
    '                        inQueue[v] = true;',
    '                    }',
    '                }',
    '            }',
    '        }',
    '        return dist;',
    '    }',
    '}',
  ],
  python: [
    'from collections import deque',
    '',
    'def spfa(n: int, s: int, adj: dict) -> list[int]:',
    '    dist = [float("inf")] * n',
    '    in_queue = [False] * n',
    '    dist[s] = 0',
    '    q = deque([s])',
    '    in_queue[s] = True',
    '    while q:',
    '        u = q.popleft()',
    '        in_queue[u] = False',
    '        for v, w in adj.get(u, []):',
    '            if dist[u] + w < dist[v]:',
    '                dist[v] = dist[u] + w',
    '                if not in_queue[v]:',
    '                    q.append(v)',
    '                    in_queue[v] = True',
    '    return dist',
  ],
  javascript: [
    'function spfa(n, s, adj) {',
    '  const dist = new Array(n).fill(Infinity);',
    '  const inQueue = new Array(n).fill(false);',
    '  dist[s] = 0;',
    '  const q = [s];',
    '  inQueue[s] = true;',
    '  while (q.length > 0) {',
    '    const u = q.shift();',
    '    inQueue[u] = false;',
    '    for (const [v, w] of adj[u]) {',
    '      if (dist[u] + w < dist[v]) {',
    '        dist[v] = dist[u] + w;',
    '        if (!inQueue[v]) {',
    '          q.push(v);',
    '          inQueue[v] = true;',
    '        }',
    '      }',
    '    }',
    '  }',
    '  return dist;',
    '}',
  ],
};

export const SPFA_061_LINES = {
  init: { cpp: 6, java: 6, python: 3, javascript: 2 },
  pollNode: { cpp: 13, java: 14, python: 9, javascript: 8 },
  relaxEdge: { cpp: 16, java: 18, python: 12, javascript: 11 },
  pushQueue: { cpp: 18, java: 20, python: 14, javascript: 13 },
  returnDist: { cpp: 24, java: 27, python: 17, javascript: 21 },
};

// ==========================================
// 5. Code05: Floyd-Warshall (全源最短路 O(V³))
// ==========================================
export const FLOYD_061_CODES = {
  cpp: [
    '#include <vector>',
    '#include <algorithm>',
    'using namespace std;',
    '',
    'vector<vector<int>> floydWarshall(int n, vector<vector<int>>& graph) {',
    '    vector<vector<int>> dp = graph;',
    '    for (int k = 0; k < n; ++k) {',
    '        for (int i = 0; i < n; ++i) {',
    '            for (int j = 0; j < n; ++j) {',
    '                if (dp[i][k] != 1e9 && dp[k][j] != 1e9) {',
    '                    dp[i][j] = min(dp[i][j], dp[i][k] + dp[k][j]);',
    '                }',
    '            }',
    '        }',
    '    }',
    '    return dp;',
    '}',
  ],
  java: [
    'package class061;',
    'import java.util.*;',
    '',
    'public class Code05_FloydWarshall {',
    '    public static int[][] floydWarshall(int n, int[][] graph) {',
    '        int[][] dp = new int[n][n];',
    '        for (int i = 0; i < n; i++) dp[i] = graph[i].clone();',
    '        for (int k = 0; k < n; k++) {',
    '            for (int i = 0; i < n; i++) {',
    '                for (int j = 0; j < n; j++) {',
    '                    if (dp[i][k] != 1e9 && dp[k][j] != 1e9) {',
    '                        dp[i][j] = Math.min(dp[i][j], dp[i][k] + dp[k][j]);',
    '                    }',
    '                }',
    '            }',
    '        }',
    '        return dp;',
    '    }',
    '}',
  ],
  python: [
    'def floyd_warshall(n: int, graph: list[list[int]]) -> list[list[int]]:',
    '    dp = [row[:] for row in graph]',
    '    for k in range(n):',
    '        for i in range(n):',
    '            for j in range(n):',
    '                if dp[i][k] != float("inf") and dp[k][j] != float("inf"):',
    '                    dp[i][j] = min(dp[i][j], dp[i][k] + dp[k][j])',
    '    return dp',
  ],
  javascript: [
    'function floydWarshall(n, graph) {',
    '  const dp = graph.map((row) => row.slice());',
    '  for (let k = 0; k < n; k++) {',
    '    for (let i = 0; i < n; i++) {',
    '      for (let j = 0; j < n; j++) {',
    '        if (dp[i][k] !== Infinity && dp[k][j] !== Infinity) {',
    '          dp[i][j] = Math.min(dp[i][j], dp[i][k] + dp[k][j]);',
    '        }',
    '      }',
    '    }',
    '  }',
    '  return dp;',
    '}',
  ],
};

export const FLOYD_061_LINES = {
  init: { cpp: 6, java: 6, python: 2, javascript: 2 },
  kLoop: { cpp: 7, java: 8, python: 3, javascript: 3 },
  transition: { cpp: 11, java: 12, python: 7, javascript: 7 },
  returnDp: { cpp: 16, java: 17, python: 9, javascript: 11 },
};

// ==========================================
// 6. Code06: 负权环判定 (洛谷 P3385)
// ==========================================
export const NEGATIVE_CYCLE_061_CODES = {
  cpp: [
    '#include <vector>',
    '#include <queue>',
    'using namespace std;',
    '',
    'bool hasNegativeCycle(int n, vector<vector<pair<int, int>>>& adj) {',
    '    vector<int> dist(n, 0);',
    '    vector<int> count(n, 0);',
    '    vector<bool> inQueue(n, true);',
    '    queue<int> q;',
    '    for (int i = 0; i < n; ++i) q.push(i);',
    '    while (!q.empty()) {',
    '        int u = q.front(); q.pop();',
    '        inQueue[u] = false;',
    '        for (auto& [v, w] : adj[u]) {',
    '            if (dist[u] + w < dist[v]) {',
    '                dist[v] = dist[u] + w;',
    '                count[v] = count[u] + 1;',
    '                if (count[v] >= n) return true; // 负权环存在',
    '                if (!inQueue[v]) {',
    '                    q.push(v);',
    '                    inQueue[v] = true;',
    '                }',
    '            }',
    '        }',
    '    }',
    '    return false;',
    '}',
  ],
  java: [
    'package class061;',
    'import java.util.*;',
    '',
    'public class Code06_NegativeCycle {',
    '    public static boolean hasNegativeCycle(int n, List<List<int[]>> adj) {',
    '        int[] dist = new int[n];',
    '        int[] count = new int[n];',
    '        boolean[] inQueue = new boolean[n];',
    '        Queue<Integer> q = new LinkedList<>();',
    '        for (int i = 0; i < n; i++) {',
    '            q.offer(i);',
    '            inQueue[i] = true;',
    '        }',
    '        while (!q.isEmpty()) {',
    '            int u = q.poll();',
    '            inQueue[u] = false;',
    '            for (int[] edge : adj.get(u)) {',
    '                int v = edge[0], w = edge[1];',
    '                if (dist[u] + w < dist[v]) {',
    '                    dist[v] = dist[u] + w;',
    '                    count[v] = count[u] + 1;',
    '                    if (count[v] >= n) return true;',
    '                    if (!inQueue[v]) {',
    '                        q.offer(v);',
    '                        inQueue[v] = true;',
    '                    }',
    '                }',
    '            }',
    '        }',
    '        return false;',
    '    }',
    '}',
  ],
  python: [
    'from collections import deque',
    '',
    'def has_negative_cycle(n: int, adj: dict) -> bool:',
    '    dist = [0] * n',
    '    count = [0] * n',
    '    in_queue = [True] * n',
    '    q = deque(range(n))',
    '    while q:',
    '        u = q.popleft()',
    '        in_queue[u] = False',
    '        for v, w in adj.get(u, []):',
    '            if dist[u] + w < dist[v]:',
    '                dist[v] = dist[u] + w',
    '                count[v] = count[u] + 1',
    '                if count[v] >= n:',
    '                    return True',
    '                if not in_queue[v]:',
    '                    q.append(v)',
    '                    in_queue[v] = True',
    '    return False',
  ],
  javascript: [
    'function hasNegativeCycle(n, adj) {',
    '  const dist = new Array(n).fill(0);',
    '  const count = new Array(n).fill(0);',
    '  const inQueue = new Array(n).fill(true);',
    '  const q = Array.from({ length: n }, (_, i) => i);',
    '  while (q.length > 0) {',
    '    const u = q.shift();',
    '    inQueue[u] = false;',
    '    for (const [v, w] of adj[u]) {',
    '      if (dist[u] + w < dist[v]) {',
    '        dist[v] = dist[u] + w;',
    '        count[v] = count[u] + 1;',
    '        if (count[v] >= n) return true;',
    '        if (!inQueue[v]) {',
    '          q.push(v);',
    '          inQueue[v] = true;',
    '        }',
    '      }',
    '    }',
    '  }',
    '  return false;',
    '}',
  ],
};

export const NEGATIVE_CYCLE_061_LINES = {
  init: { cpp: 6, java: 6, python: 3, javascript: 2 },
  pollNode: { cpp: 12, java: 14, python: 9, javascript: 8 },
  relaxEdge: { cpp: 15, java: 18, python: 12, javascript: 11 },
  detectCycle: { cpp: 18, java: 21, python: 14, javascript: 13 },
  returnResult: { cpp: 25, java: 29, python: 19, javascript: 22 },
};
