/**
 * Class 055: 单调队列·下 四语言完整工业级源码与精准 1-based 行号映射
 */

import { HighlightTarget } from '../../../../core/renderers/dark-code-terminal-presenter';

export interface CodeMapping {
  java: number;
  cpp: number;
  python: number;
  javascript: number;
}

// -------------------------------------------------------------
// Code01: 和至少为 K 的最短子数组 (Shortest Subarray with Sum at Least K)
// -------------------------------------------------------------
export const CODE01_SHORTEST_SUBARRAY_CODES: Record<string, string[]> = {
  java: [
    'public class ShortestSubarrayWithSumAtLeastK {',
    '    public static int MAXN = 100001;',
    '    public static long[] sum = new long[MAXN];',
    '    public static int[] deque = new int[MAXN];',
    '    public static int h, t;',
    '    public static int shortestSubarray(int[] arr, int K) {',
    '        int n = arr.length;',
    '        for (int i = 0; i < n; i++) {',
    '            sum[i + 1] = sum[i] + arr[i]; // 计算前缀和',
    '        }',
    '        h = t = 0;',
    '        int ans = Integer.MAX_VALUE;',
    '        for (int i = 0; i <= n; i++) {',
    '            // 1. 队头尝试满足 sum[i] - sum[deque[h]] >= K 结算答案',
    '            while (h != t && sum[i] - sum[deque[h]] >= K) {',
    '                ans = Math.min(ans, i - deque[h++]);',
    '            }',
    '            // 2. 队尾淘汰劣质大前缀和，维护单调递增队列',
    '            while (h != t && sum[deque[t - 1]] >= sum[i]) {',
    '                t--;',
    '            }',
    '            deque[t++] = i;',
    '        }',
    '        return ans != Integer.MAX_VALUE ? ans : -1;',
    '    }',
    '}',
  ],
  cpp: [
    'class Solution {',
    'public:',
    '    int shortestSubarray(vector<int>& arr, int k) {',
    '        int n = arr.size();',
    '        vector<long long> sum(n + 1, 0);',
    '        for (int i = 0; i < n; i++) sum[i + 1] = sum[i] + arr[i];',
    '        deque<int> dq;',
    '        int ans = INT_MAX;',
    '        for (int i = 0; i <= n; i++) {',
    '            while (!dq.empty() && sum[i] - sum[dq.front()] >= k) {',
    '                ans = min(ans, i - dq.front());',
    '                dq.pop_front();',
    '            }',
    '            while (!dq.empty() && sum[dq.back()] >= sum[i]) {',
    '                dq.pop_back();',
    '            }',
    '            dq.push_back(i);',
    '        }',
    '        return ans == INT_MAX ? -1 : ans;',
    '    }',
    '};',
  ],
  python: [
    'from collections import deque',
    '',
    'class Solution:',
    '    def shortestSubarray(self, arr: list[int], k: int) -> int:',
    '        n = len(arr)',
    '        prefix_sum = [0] * (n + 1)',
    '        for i in range(n):',
    '            prefix_sum[i + 1] = prefix_sum[i] + arr[i]',
    '        dq = deque()',
    '        ans = float("inf")',
    '        for i in range(n + 1):',
    '            while dq and prefix_sum[i] - prefix_sum[dq[0]] >= k:',
    '                ans = min(ans, i - dq.popleft())',
    '            while dq and prefix_sum[dq[-1]] >= prefix_sum[i]:',
    '                dq.pop()',
    '            dq.append(i)',
    '        return -1 if ans == float("inf") else ans',
  ],
  javascript: [
    'function shortestSubarray(arr, k) {',
    '    const n = arr.length;',
    '    const sum = new Array(n + 1).fill(0);',
    '    for (let i = 0; i < n; i++) sum[i + 1] = sum[i] + arr[i];',
    '    const dq = [];',
    '    let ans = Infinity;',
    '    for (let i = 0; i <= n; i++) {',
    '        while (dq.length > 0 && sum[i] - sum[dq[0]] >= k) {',
    '            ans = Math.min(ans, i - dq.shift());',
    '        }',
    '        while (dq.length > 0 && sum[dq[dq.length - 1]] >= sum[i]) {',
    '            dq.pop();',
    '        }',
    '        dq.push(i);',
    '    }',
    '    return ans === Infinity ? -1 : ans;',
    '}',
  ],
};

export const CODE01_SHORTEST_SUBARRAY_LINES: Record<string, CodeMapping> = {
  entry:       { java: 6, cpp: 3, python: 4, javascript: 1 },
  prefixSum:   { java: 9, cpp: 6, python: 8, javascript: 4 },
  loopI:       { java: 13, cpp: 9, python: 11, javascript: 7 },
  popHead:     { java: 16, cpp: 11, python: 13, javascript: 9 },
  popTail:     { java: 20, cpp: 15, python: 15, javascript: 12 },
  pushTail:    { java: 22, cpp: 17, python: 16, javascript: 14 },
  returnAns:   { java: 24, cpp: 19, python: 17, javascript: 16 },
};

// -------------------------------------------------------------
// Code02: 满足不等式的最大值 (Max Value of Equation)
// -------------------------------------------------------------
export const CODE02_MAX_EQUATION_CODES: Record<string, string[]> = {
  java: [
    'public class MaxValueOfEquation {',
    '    public static int MAXN = 100001;',
    '    public static int[][] deque = new int[MAXN][2];',
    '    public static int h, t;',
    '    public static int findMaxValueOfEquation(int[][] points, int k) {',
    '        h = t = 0;',
    '        int n = points.length, ans = Integer.MIN_VALUE;',
    '        for (int i = 0; i < n; i++) {',
    '            int x = points[i][0], y = points[i][1];',
    '            // 1. 队头超出跨度 k 限制过期出队',
    '            while (h < t && deque[h][0] + k < x) {',
    '                h++;',
    '            }',
    '            // 2. 队头即为满足距离条件中 y - x 最大的前置点',
    '            if (h < t) {',
    '                ans = Math.max(ans, x + y + deque[h][1] - deque[h][0]);',
    '            }',
    '            // 3. 维护 y - x 从大到小单调递减',
    '            while (h < t && deque[t - 1][1] - deque[t - 1][0] <= y - x) {',
    '                t--;',
    '            }',
    '            deque[t][0] = x;',
    '            deque[t++][1] = y;',
    '        }',
    '        return ans;',
    '    }',
    '}',
  ],
  cpp: [
    'class Solution {',
    'public:',
    '    int findMaxValueOfEquation(vector<vector<int>>& points, int k) {',
    '        deque<pair<int, int>> dq; // pair<x, y - x>',
    '        int ans = INT_MIN;',
    '        for (const auto& p : points) {',
    '            int x = p[0], y = p[1];',
    '            while (!dq.empty() && dq.front().first + k < x) dq.pop_front();',
    '            if (!dq.empty()) {',
    '                ans = max(ans, x + y + dq.front().second);',
    '            }',
    '            while (!dq.empty() && dq.back().second <= y - x) dq.pop_back();',
    '            dq.push_back({x, y - x});',
    '        }',
    '        return ans;',
    '    }',
    '};',
  ],
  python: [
    'from collections import deque',
    '',
    'class Solution:',
    '    def findMaxValueOfEquation(self, points: list[list[int]], k: int) -> int:',
    '        dq = deque()  # (x, y - x)',
    '        ans = float("-inf")',
    '        for x, y in points:',
    '            while dq and dq[0][0] + k < x:',
    '                dq.popleft()',
    '            if dq:',
    '                ans = max(ans, x + y + dq[0][1])',
    '            while dq and dq[-1][1] <= y - x:',
    '                dq.pop()',
    '            dq.append((x, y - x))',
    '        return ans',
  ],
  javascript: [
    'function findMaxValueOfEquation(points, k) {',
    '    const dq = []; // [x, y - x]',
    '    let ans = -Infinity;',
    '    for (const [x, y] of points) {',
    '        while (dq.length > 0 && dq[0][0] + k < x) {',
    '            dq.shift();',
    '        }',
    '        if (dq.length > 0) {',
    '            ans = Math.max(ans, x + y + dq[0][1]);',
    '        }',
    '        while (dq.length > 0 && dq[dq.length - 1][1] <= y - x) {',
    '            dq.pop();',
    '        }',
    '        dq.push([x, y - x]);',
    '    }',
    '    return ans;',
    '}',
  ],
};

export const CODE02_MAX_EQUATION_LINES: Record<string, CodeMapping> = {
  entry:       { java: 5, cpp: 3, python: 4, javascript: 1 },
  loopPoint:   { java: 8, cpp: 6, python: 7, javascript: 4 },
  expireHead:  { java: 11, cpp: 8, python: 8, javascript: 5 },
  updateAns:   { java: 16, cpp: 10, python: 11, javascript: 8 },
  popTail:     { java: 20, cpp: 12, python: 13, javascript: 11 },
  pushCur:     { java: 22, cpp: 13, python: 14, javascript: 13 },
  returnAns:   { java: 25, cpp: 16, python: 15, javascript: 15 },
};

// -------------------------------------------------------------
// Code03: 你可以安排的最多任务数目 (Maximum Number of Tasks You Can Assign)
// -------------------------------------------------------------
export const CODE03_TASKS_ASSIGN_CODES: Record<string, string[]> = {
  java: [
    'import java.util.Arrays;',
    '',
    'public class MaximumNumberOfTasksYouCanAssign {',
    '    public static int maxTaskAssign(int[] tasks, int[] workers, int pills, int strength) {',
    '        Arrays.sort(tasks);',
    '        Arrays.sort(workers);',
    '        int l = 0, r = Math.min(tasks.length, workers.length), ans = 0;',
    '        while (l <= r) {',
    '            int m = (l + r) / 2;',
    '            if (canFinish(tasks, workers, m, pills, strength)) {',
    '                ans = m;',
    '                l = m + 1;',
    '            } else {',
    '                r = m - 1;',
    '            }',
    '        }',
    '        return ans;',
    '    }',
    '    private static boolean canFinish(int[] tasks, int[] workers, int m, int pills, int s) {',
    '        int[] dq = new int[m];',
    '        int h = 0, t = 0, cnt = 0, j = 0, wStart = workers.length - m;',
    '        for (int i = wStart; i < workers.length; i++) {',
    '            for (; j < m && tasks[j] <= workers[i]; j++) dq[t++] = j;',
    '            if (h < t && tasks[dq[h]] <= workers[i]) {',
    '                h++; // 不吃药让最弱合格工人做最简单任务',
    '            } else {',
    '                for (; j < m && tasks[j] <= workers[i] + s; j++) dq[t++] = j;',
    '                if (h < t) { cnt++; t--; } else return false;',
    '            }',
    '        }',
    '        return cnt <= pills;',
    '    }',
    '}',
  ],
  cpp: [
    'class Solution {',
    'public:',
    '    int maxTaskAssign(vector<int>& tasks, vector<int>& workers, int pills, int strength) {',
    '        sort(tasks.begin(), tasks.end());',
    '        sort(workers.begin(), workers.end());',
    '        int l = 0, r = min(tasks.size(), workers.size()), ans = 0;',
    '        while (l <= r) {',
    '            int m = (l + r) / 2;',
    '            if (check(tasks, workers, m, pills, strength)) {',
    '                ans = m; l = m + 1;',
    '            } else { r = m - 1; }',
    '        }',
    '        return ans;',
    '    }',
    '    bool check(vector<int>& tasks, vector<int>& workers, int m, int pills, int s) {',
    '        deque<int> dq; int cnt = 0, j = 0, wStart = workers.size() - m;',
    '        for (int i = wStart; i < workers.size(); i++) {',
    '            for (; j < m && tasks[j] <= workers[i]; j++) dq.push_back(j);',
    '            if (!dq.empty() && tasks[dq.front()] <= workers[i]) {',
    '                dq.pop_front();',
    '            } else {',
    '                for (; j < m && tasks[j] <= workers[i] + s; j++) dq.push_back(j);',
    '                if (!dq.empty()) { cnt++; dq.pop_back(); } else return false;',
    '            }',
    '        }',
    '        return cnt <= pills;',
    '    }',
    '};',
  ],
  python: [
    'from collections import deque',
    '',
    'class Solution:',
    '    def maxTaskAssign(self, tasks: list[int], workers: list[int], pills: int, strength: int) -> int:',
    '        tasks.sort()',
    '        workers.sort()',
    '        l, r, ans = 0, min(len(tasks), len(workers)), 0',
    '        while l <= r:',
    '            m = (l + r) // 2',
    '            if self.check(tasks, workers, m, pills, strength):',
    '                ans = m',
    '                l = m + 1',
    '            else:',
    '                r = m - 1',
    '        return ans',
    '',
    '    def check(self, tasks, workers, m, pills, s) -> bool:',
    '        dq, cnt, j = deque(), 0, 0',
    '        for w in workers[len(workers) - m:]:',
    '            while j < m and tasks[j] <= w:',
    '                dq.append(j)',
    '                j += 1',
    '            if dq and tasks[dq[0]] <= w:',
    '                dq.popleft()',
    '            else:',
    '                while j < m and tasks[j] <= w + s:',
    '                    dq.append(j)',
    '                    j += 1',
    '                if dq:',
    '                    cnt += 1',
    '                    dq.pop()',
    '                else:',
    '                    return False',
    '        return cnt <= pills',
  ],
  javascript: [
    'function maxTaskAssign(tasks, workers, pills, strength) {',
    '    tasks.sort((a, b) => a - b);',
    '    workers.sort((a, b) => a - b);',
    '    let l = 0, r = Math.min(tasks.length, workers.length), ans = 0;',
    '    while (l <= r) {',
    '        const m = Math.floor((l + r) / 2);',
    '        if (check(tasks, workers, m, pills, strength)) {',
    '            ans = m;',
    '            l = m + 1;',
    '        } else {',
    '            r = m - 1;',
    '        }',
    '    }',
    '    return ans;',
    '',
    '    function check(tasks, workers, m, pills, s) {',
    '        const dq = [];',
    '        let cnt = 0, j = 0;',
    '        const wSlice = workers.slice(workers.length - m);',
    '        for (const w of wSlice) {',
    '            for (; j < m && tasks[j] <= w; j++) dq.push(j);',
    '            if (dq.length > 0 && tasks[dq[0]] <= w) {',
    '                dq.shift();',
    '            } else {',
    '                for (; j < m && tasks[j] <= w + s; j++) dq.push(j);',
    '                if (dq.length > 0) {',
    '                    cnt++;',
    '                    dq.pop();',
    '                } else return false;',
    '            }',
    '        }',
    '        return cnt <= pills;',
    '    }',
    '}',
  ],
};

export const CODE03_TASKS_ASSIGN_LINES: Record<string, CodeMapping> = {
  entry:       { java: 4, cpp: 3, python: 4, javascript: 1 },
  sortBoth:    { java: 6, cpp: 5, python: 6, javascript: 3 },
  binaryLoop:  { java: 8, cpp: 7, python: 8, javascript: 5 },
  unlockFree:  { java: 22, cpp: 16, python: 20, javascript: 20 },
  pickFree:    { java: 23, cpp: 17, python: 23, javascript: 21 },
  unlockPill:  { java: 26, cpp: 20, python: 25, javascript: 24 },
  pickPill:    { java: 27, cpp: 21, python: 28, javascript: 26 },
  returnAns:   { java: 17, cpp: 12, python: 14, javascript: 13 },
};
