/**
 * 算法轻量级元数据列表（用于首页快速渲染与导航，零模板与零代码引入）
 * 包含全部 218 个算法的基本信息
 */

import type { AlgorithmMetadata } from './registry';

export const ALL_ALGORITHM_METADATA: AlgorithmMetadata[] = [
  {
    "id": "bracket",
    "name": "括号匹配",
    "viewId": "algo-bracket-view",
    "category": "stack",
    "description": "使用栈验证括号字符串的有效性",
    "icon": "📚",
    "difficulty": 1,
    "levelOrder": 1,
    "learningGoal": "掌握用栈匹配括号对的基础模型"
  },
  {
    "id": "stack-queue-theory",
    "name": "栈与队列理论基础",
    "viewId": "algo-stack-queue-theory-view",
    "category": "stack",
    "description": "栈（LIFO）和队列（FIFO）的核心概念与应用",
    "icon": "📖",
    "difficulty": 1,
    "levelOrder": 0,
    "learningGoal": "理解栈和队列的原理、操作和应用场景"
  },
  {
    "id": "implement-queue-using-stack",
    "name": "用栈实现队列",
    "viewId": "algo-implement-queue-using-stack-view",
    "category": "stack",
    "description": "双栈架构：输入栈 inStack 处理 push，输出栈 outStack 为空时一次性倾倒反转实现 FIFO",
    "icon": "🔄",
    "difficulty": 1,
    "levelOrder": 1,
    "learningGoal": "掌握双栈组合出 FIFO 队列的精妙架构，理解均摊时间复杂度 O(1) 的倒栈触发准则"
  },
  {
    "id": "implement-stack-using-queue",
    "name": "用队列实现栈",
    "viewId": "algo-implement-stack-using-queue-view",
    "category": "stack",
    "description": "单队列循环旋转法：push 入队后将前面 size - 1 个元素出队再入队，保持队头为栈顶",
    "icon": "🥞",
    "difficulty": 1,
    "levelOrder": 2,
    "learningGoal": "掌握单队列通过自环旋转实现 LIFO 栈的精简思想，实现真正的 O(1) Pop 与 Top 查询"
  },
  {
    "id": "bracket",
    "name": "有效的括号",
    "viewId": "algo-bracket-view",
    "category": "stack",
    "description": "遇左括号压入对应右括号，遇右括号只需 O(1) 比对并弹出栈顶元素",
    "icon": "🎯",
    "difficulty": 1,
    "levelOrder": 3,
    "learningGoal": "掌握经典栈匹配思想与“遇左压右”简化比对逻辑的巧妙设计技巧"
  },
  {
    "id": "remove-adjacent-duplicates",
    "name": "删除相邻重复项",
    "viewId": "algo-remove-adjacent-duplicates-view",
    "category": "stack",
    "description": "栈消消乐模型：栈顶即当前前驱，遇到相同字符直接出栈对消，形成连锁反应",
    "icon": "✨",
    "difficulty": 1,
    "levelOrder": 4,
    "learningGoal": "理解栈在消除相邻元素中的经典应用，掌握利用栈顶作为动态前驱消除递归连锁重复项的设计范式"
  },
  {
    "id": "eval-rpn",
    "name": "逆波兰表达式求值",
    "viewId": "algo-eval-rpn-view",
    "category": "stack",
    "description": "用栈求解后缀（逆波兰）表达式",
    "icon": "🧮",
    "difficulty": 2,
    "levelOrder": 5,
    "learningGoal": "掌握用栈处理后缀表达式的思路"
  },
  {
    "id": "sliding-window-max",
    "name": "滑动窗口最大值（单调队列）",
    "viewId": "algo-sliding-window-max-view",
    "category": "stack",
    "description": "用单调队列求每个滑动窗口的最大值",
    "icon": "📊",
    "difficulty": 2,
    "levelOrder": 6,
    "learningGoal": "掌握用单调队列维护滑动窗口最大值"
  },
  {
    "id": "top-k-frequent",
    "name": "前K个高频元素（桶排序）",
    "viewId": "algo-top-k-frequent-view",
    "category": "stack",
    "description": "用桶排序求数组中出现最频繁的 k 个元素",
    "icon": "🏆",
    "difficulty": 2,
    "levelOrder": 7,
    "learningGoal": "掌握频率统计 + 桶排序的高效方法"
  },
  {
    "id": "array-theory",
    "name": "数组理论基础",
    "viewId": "algo-array-theory-view",
    "category": "array",
    "description": "数组的内存布局、基本操作和时间复杂度",
    "icon": "📖",
    "difficulty": 1,
    "levelOrder": 0,
    "learningGoal": "理解数组的连续内存特性和基本操作"
  },
  {
    "id": "remove-element",
    "name": "移除元素（双指针）",
    "viewId": "algo-remove-element-view",
    "category": "array",
    "description": "快慢指针原地移除指定值的元素",
    "icon": "🧹",
    "difficulty": 1,
    "levelOrder": 1,
    "learningGoal": "掌握快慢双指针原地修改数组的思路"
  },
  {
    "id": "sorted-squares",
    "name": "有序数组的平方（双指针）",
    "viewId": "algo-sorted-squares-view",
    "category": "array",
    "description": "首尾双指针从大到小填入结果数组",
    "icon": "²",
    "difficulty": 1,
    "levelOrder": 3,
    "learningGoal": "掌握利用有序性用双指针避免排序"
  },
  {
    "id": "min-subarray-len",
    "name": "长度最小的子数组（滑动窗口）",
    "viewId": "algo-min-subarray-len-view",
    "category": "array",
    "description": "滑动窗口求和≥target的最短子数组",
    "icon": "🪟",
    "difficulty": 2,
    "levelOrder": 2,
    "learningGoal": "理解滑动窗口如何高效维护子数组和"
  },
  {
    "id": "spiral-matrix-ii",
    "name": "螺旋矩阵 II（模拟）",
    "viewId": "algo-spiral-matrix-ii-view",
    "category": "array",
    "description": "顺时针螺旋填充 n×n 矩阵",
    "icon": "🌀",
    "difficulty": 2,
    "levelOrder": 3,
    "learningGoal": "学会按方向模拟遍历矩阵的思维"
  },
  {
    "id": "range-sum",
    "name": "区间和（前缀和）",
    "viewId": "algo-range-sum-view",
    "category": "array",
    "description": "预处理前缀和数组，O(1) 回答区间查询",
    "icon": "Σ",
    "difficulty": 1,
    "levelOrder": 6,
    "learningGoal": "掌握前缀和思想与区间查询技巧"
  },
  {
    "id": "buy-land",
    "name": "开发商购买土地（二维前缀和）",
    "viewId": "algo-buy-land-view",
    "category": "array",
    "description": "在矩阵中寻找和 ≤ 预算的最大面积连续区域",
    "icon": "🏞️",
    "difficulty": 2,
    "levelOrder": 7,
    "learningGoal": "掌握二维前缀和与子矩阵枚举"
  },
  {
    "id": "array-summary",
    "name": "数组专题总结篇",
    "viewId": "algo-array-summary-view",
    "category": "array",
    "description": "回顾数组专题所有核心技巧",
    "icon": "📝",
    "difficulty": 1,
    "levelOrder": 8,
    "learningGoal": "系统梳理数组专题的核心思想与解题套路"
  },
  {
    "id": "reverse-linked-list",
    "name": "反转链表（双指针）",
    "viewId": "algo-reverse-linked-list-view",
    "category": "linked-list",
    "description": "pre/cur 双指针逐个反转链表指针，含 next 缓存动画",
    "icon": "🔁",
    "difficulty": 1,
    "levelOrder": 1,
    "learningGoal": "掌握链表反转的经典三指针法"
  },
  {
    "id": "remove-nth-from-end",
    "name": "删除链表的倒数第 N 个节点（快慢指针）",
    "viewId": "algo-remove-nth-from-end-view",
    "category": "linked-list",
    "description": "快慢指针一次遍历，fast 冲刺后锁步删除倒数第 n 个节点",
    "icon": "🗑️",
    "difficulty": 1,
    "levelOrder": 2,
    "learningGoal": "学会快慢指针找倒数第 N 个节点"
  },
  {
    "id": "linked-list-cycle-ii",
    "name": "环形链表 II（快慢指针）",
    "viewId": "algo-linked-list-cycle-ii-view",
    "category": "linked-list",
    "description": "快慢指针相遇后找入环口",
    "icon": "🔄",
    "difficulty": 2,
    "levelOrder": 3,
    "learningGoal": "理解快慢指针检测环 + 找入环点的数学原理"
  },
  {
    "id": "design-linked-list",
    "name": "设计链表（MyLinkedList）",
    "viewId": "algo-design-linked-list-view",
    "category": "linked-list",
    "description": "亲手实现单链表五种操作 + 节点飞入/抖动/脉冲动画",
    "icon": "🔗",
    "difficulty": 1,
    "levelOrder": 4,
    "learningGoal": "从零实现链表，深入理解节点与指针操作"
  },
  {
    "id": "intersection-linked-list",
    "name": "相交链表（双指针）",
    "viewId": "algo-intersection-linked-list-view",
    "category": "linked-list",
    "description": "双指针遍历 A+B 与 B+A，相交时必在交点相遇",
    "icon": "✂️",
    "difficulty": 2,
    "levelOrder": 5,
    "learningGoal": "掌握双链表长度差对齐的交汇点检测"
  },
  {
    "id": "merge-sorted-array",
    "name": "合并两个有序数组（双指针）",
    "viewId": "algo-merge-sorted-array-view",
    "category": "linked-list",
    "description": "双指针从后向前填充，O(m+n) 时间 O(1) 额外空间",
    "icon": "🔀",
    "difficulty": 1,
    "levelOrder": 6,
    "learningGoal": "学会从后向前的双指针合并排序数组"
  },
  {
    "id": "move-zeroes",
    "name": "移动零（双指针）",
    "viewId": "algo-move-zeroes-view",
    "category": "linked-list",
    "description": "快慢指针将非零元素前移，O(n) 时间 O(1) 额外空间",
    "icon": "🎯",
    "difficulty": 1,
    "levelOrder": 7,
    "learningGoal": "运用双指针将零移到数组末尾"
  },
  {
    "id": "two-sum",
    "name": "两数之和（哈希表）",
    "viewId": "algo-two-sum-view",
    "category": "hash-table",
    "description": "哈希表一次遍历求两数之和",
    "icon": "🔗",
    "difficulty": 1,
    "levelOrder": 1,
    "learningGoal": "理解哈希表如何替代暴力枚举降低时间复杂度"
  },
  {
    "id": "three-sum",
    "name": "三数之和（排序+双指针）",
    "viewId": "algo-three-sum-view",
    "category": "hash-table",
    "description": "排序后双指针求和为0的三元组",
    "icon": "🎯",
    "difficulty": 3,
    "levelOrder": 2,
    "learningGoal": "掌握排序 + 双指针 + 去重的三数求和技巧"
  },
  {
    "id": "four-sum",
    "name": "四数之和（排序+双指针）",
    "viewId": "algo-four-sum-view",
    "category": "hash-table",
    "description": "排序后固定 i/j 再双指针求和为 target 的四元组",
    "icon": "🎯",
    "difficulty": 3,
    "levelOrder": 3,
    "learningGoal": "掌握嵌套双指针 + 多层去重的四数求和技巧"
  },
  {
    "id": "anagram",
    "name": "有效的字母异位词（哈希计数）",
    "viewId": "algo-anagram-view",
    "category": "hash-table",
    "description": "长度26数组统计频次判断异位词",
    "icon": "🔤",
    "difficulty": 1,
    "levelOrder": 3,
    "learningGoal": "用字符频次统计判断字母异位词"
  },
  {
    "id": "four-sum-ii",
    "name": "四数相加II（分组哈希）",
    "viewId": "algo-four-sum-ii-view",
    "category": "hash-table",
    "description": "将四数组分为两组，用哈希表统计和为0的元组数",
    "icon": "🧮",
    "difficulty": 2,
    "levelOrder": 4,
    "learningGoal": "掌握分组降维 + 哈希表计数优化四重循环"
  },
  {
    "id": "happy-number",
    "name": "快乐数（哈希集合判环）",
    "viewId": "algo-happy-number-view",
    "category": "hash-table",
    "description": "用哈希集合检测平方和循环，判断快乐数",
    "icon": "😊",
    "difficulty": 1,
    "levelOrder": 2,
    "learningGoal": "掌握用 Set 检测循环的方法"
  },
  {
    "id": "intersection-arrays",
    "name": "两个数组的交集（哈希集合）",
    "viewId": "algo-intersection-arrays-view",
    "category": "hash-table",
    "description": "用哈希集合求两个数组的交集元素",
    "icon": "🔀",
    "difficulty": 1,
    "levelOrder": 1,
    "learningGoal": "掌握用 Set 去重后高效求交集的思路"
  },
  {
    "id": "hash-table-theory",
    "name": "哈希表理论基础",
    "viewId": "algo-hash-table-theory-view",
    "category": "hash-table",
    "description": "哈希表的核心概念、哈希函数与冲突处理",
    "icon": "📖",
    "difficulty": 1,
    "levelOrder": 0,
    "learningGoal": "理解哈希表的原理、哈希函数和冲突处理方法"
  },
  {
    "id": "ransom-note",
    "name": "赎金信（字符计数）",
    "viewId": "algo-ransom-note-view",
    "category": "hash-table",
    "description": "用字符频率表判断赎金信能否由杂志构造",
    "icon": "📰",
    "difficulty": 1,
    "levelOrder": 5,
    "learningGoal": "掌握用 Map 统计字符频率的方法"
  },
  {
    "id": "reverse-string",
    "name": "反转字符串（双指针）",
    "viewId": "algo-reverse-string-view",
    "category": "string",
    "description": "首尾双指针原地反转字符数组",
    "icon": "↔️",
    "difficulty": 1,
    "levelOrder": 1,
    "learningGoal": "掌握原地反转字符串的双指针法"
  },
  {
    "id": "reverse-string-ii",
    "name": "反转字符串II（分段反转）",
    "viewId": "algo-reverse-string-ii-view",
    "category": "string",
    "description": "每隔 2k 个字符反转前 k 个字符",
    "icon": "🔁",
    "difficulty": 1,
    "levelOrder": 2,
    "learningGoal": "掌握分段处理 + 边界条件的双指针反转"
  },
  {
    "id": "reverse-words",
    "name": "翻转字符串里的单词（双指针）",
    "viewId": "algo-reverse-words-view",
    "category": "string",
    "description": "移除多余空格并倒序拼接单词",
    "icon": "🔃",
    "difficulty": 1,
    "levelOrder": 2,
    "learningGoal": "学会分割-反转-重组的字符串处理模式"
  },
  {
    "id": "longest-common-prefix",
    "name": "最长公共前缀（逐列扫描）",
    "viewId": "algo-longest-common-prefix-view",
    "category": "string",
    "description": "以第一个字符串为基准，逐列比对找公共前缀",
    "icon": "📖",
    "difficulty": 1,
    "levelOrder": 3,
    "learningGoal": "理解逐字符纵向比较求公共前缀的思路"
  },
  {
    "id": "replace-digits",
    "name": "替换数字（单指针遍历）",
    "viewId": "algo-replace-digits-view",
    "category": "string",
    "description": "遍历字符串，将数字字符替换为指定内容",
    "icon": "🔢",
    "difficulty": 1,
    "levelOrder": 2,
    "learningGoal": "掌握字符串遍历中条件替换的逻辑"
  },
  {
    "id": "right-rotate-string",
    "name": "右旋转字符串（三次反转）",
    "viewId": "algo-right-rotate-view",
    "category": "string",
    "description": "通过三次反转实现字符串右旋转 k 位",
    "icon": "🔄",
    "difficulty": 1,
    "levelOrder": 5,
    "learningGoal": "掌握通过分段反转实现字符串旋转的技巧"
  },
  {
    "id": "str-str",
    "name": "实现strStr()（KMP算法）",
    "viewId": "algo-str-str-view",
    "category": "string",
    "description": "用 KMP 算法在 haystack 中查找 needle 的首次位置",
    "icon": "🔍",
    "difficulty": 2,
    "levelOrder": 6,
    "learningGoal": "掌握 KMP 算法的 next 数组与状态转移"
  },
  {
    "id": "repeated-substring",
    "name": "重复的子字符串",
    "viewId": "algo-repeated-substring-view",
    "category": "string",
    "description": "判断字符串是否可由重复子串构成",
    "icon": "🔁",
    "difficulty": 2,
    "levelOrder": 7,
    "learningGoal": "掌握枚举因子长度 + 分块匹配的方法"
  },
  {
    "id": "daily-temperatures",
    "name": "每日温度（单调栈）",
    "viewId": "algo-daily-temperatures-view",
    "category": "monotonic-stack",
    "description": "单调递减栈求下一个更高温度",
    "icon": "🌡️",
    "difficulty": 2,
    "levelOrder": 1,
    "learningGoal": "理解单调栈如何找下一个更大元素"
  },
  {
    "id": "next-greater-element-i",
    "name": "下一个更大元素I",
    "viewId": "algo-next-greater-element-i-view",
    "category": "monotonic-stack",
    "description": "单调栈求 nums1 中每个元素在 nums2 中的下一个更大值",
    "icon": "🔍",
    "difficulty": 2,
    "levelOrder": 2,
    "learningGoal": "理解单调栈如何找下一个更大元素"
  },
  {
    "id": "next-greater-element-ii",
    "name": "下一个更大元素II",
    "viewId": "algo-next-greater-element-ii-view",
    "category": "monotonic-stack",
    "description": "单调栈处理循环数组，找下一个更大元素",
    "icon": "🔄",
    "difficulty": 2,
    "levelOrder": 3,
    "learningGoal": "理解单调栈如何处理循环数组"
  },
  {
    "id": "trapping-rain-water",
    "name": "接雨水（双指针）",
    "viewId": "algo-trapping-rain-water-view",
    "category": "monotonic-stack",
    "description": "左右双指针维护两侧最大值，逐列累加雨水",
    "icon": "💧",
    "difficulty": 3,
    "levelOrder": 2,
    "learningGoal": "运用单调栈求解接雨水问题"
  },
  {
    "id": "largest-rectangle-histogram",
    "name": "柱状图中最大的矩形",
    "viewId": "algo-largest-rectangle-histogram-view",
    "category": "monotonic-stack",
    "description": "用单调栈找直方图中的最大矩形面积",
    "icon": "📊",
    "difficulty": 3,
    "levelOrder": 5,
    "learningGoal": "理解单调栈如何计算最大矩形面积"
  },
  {
    "id": "islands",
    "name": "岛屿数量（DFS 网格）",
    "viewId": "algo-islands-view",
    "category": "graph",
    "description": "DFS 遍历网格标记连通陆地，统计岛屿数量",
    "icon": "🏝️",
    "difficulty": 2,
    "levelOrder": 1,
    "learningGoal": "掌握 DFS/BFS 遍历网格求连通分量"
  },
  {
    "id": "islands-bfs",
    "name": "孤岛计数 · 广搜版（BFS）",
    "viewId": "algo-islands-bfs-view",
    "category": "graph",
    "description": "BFS 逐层扩展探索岛屿，统计连通分量数量",
    "icon": "🔍",
    "difficulty": 2,
    "levelOrder": 5,
    "learningGoal": "掌握 BFS 遍历网格求连通分量"
  },
  {
    "id": "max-island-area",
    "name": "最大岛屿面积",
    "viewId": "algo-max-island-area-view",
    "category": "graph",
    "description": "DFS 计算每座岛屿面积，追踪最大值",
    "icon": "📐",
    "difficulty": 2,
    "levelOrder": 6,
    "learningGoal": "掌握 DFS 计算连通分量大小并追踪极值"
  },
  {
    "id": "total-island-area",
    "name": "孤岛总面积",
    "viewId": "algo-total-island-area-view",
    "category": "graph",
    "description": "DFS/BFS 找出所有岛屿并累计总面积",
    "icon": "📊",
    "difficulty": 2,
    "levelOrder": 7,
    "learningGoal": "掌握遍历网格累计各连通分量大小的技巧"
  },
  {
    "id": "sink-islands",
    "name": "沉没孤岛",
    "viewId": "algo-sink-islands-view",
    "category": "graph",
    "description": "DFS 遍历所有岛屿并逐一沉没（陆地→水域）",
    "icon": "🌊",
    "difficulty": 2,
    "levelOrder": 8,
    "learningGoal": "掌握 DFS 遍历并修改网格的操作"
  },
  {
    "id": "graph-theory",
    "name": "图论理论基础",
    "viewId": "algo-graph-theory-view",
    "category": "graph",
    "description": "图的表示方法：邻接矩阵、邻接表、有向/无向、加权/无权",
    "icon": "📖",
    "difficulty": 1,
    "levelOrder": 1,
    "learningGoal": "掌握图的基本表示方法及适用场景"
  },
  {
    "id": "forward-star",
    "name": "链式前向星",
    "viewId": "algo-forward-star-view",
    "category": "graph",
    "description": "静态链表存图法，通过 head[] 与 edge[cnt].next 实现 O(1) 头插法建图与快速出边遍历",
    "icon": "🕸️",
    "difficulty": 2,
    "levelOrder": 2,
    "learningGoal": "彻底掌握图论中最经典的静态链表存图法，理解 head[] 表头与 next 前驱指针的头插法跃迁逻辑"
  },
  {
    "id": "dfs-theory",
    "name": "深度优先搜索理论基础",
    "viewId": "algo-dfs-theory-view",
    "category": "graph",
    "description": "DFS 递归遍历图，递归栈与回溯过程可视化",
    "icon": "🔍",
    "difficulty": 1,
    "levelOrder": 2,
    "learningGoal": "理解 DFS 的递归深入与回溯机制"
  },
  {
    "id": "bfs-theory",
    "name": "广度优先搜索理论基础",
    "viewId": "algo-bfs-theory-view",
    "category": "graph",
    "description": "BFS 层序遍历图，队列驱动与逐层扩展可视化",
    "icon": "🌊",
    "difficulty": 1,
    "levelOrder": 4,
    "learningGoal": "理解 BFS 的队列机制和层序遍历特性"
  },
  {
    "id": "reachable-paths",
    "name": "可达路径",
    "viewId": "algo-reachable-paths-view",
    "category": "graph",
    "description": "从源节点出发用 DFS 找有向图中所有可达节点",
    "icon": "🎯",
    "difficulty": 2,
    "levelOrder": 3,
    "learningGoal": "掌握图的可达性分析与 DFS 应用"
  },
  {
    "id": "coastline",
    "name": "海岸线计算",
    "viewId": "algo-coastline-view",
    "category": "graph",
    "description": "统计所有岛屿的总周长（暴露边数量）",
    "icon": "🌊",
    "difficulty": 3,
    "levelOrder": 11,
    "learningGoal": "掌握网格图逐边计数法"
  },
  {
    "id": "make-largest-island",
    "name": "建造最大人工岛",
    "viewId": "algo-make-largest-island-view",
    "category": "graph",
    "description": "改变一个水域为陆地，使岛屿面积最大化",
    "icon": "🏝️",
    "difficulty": 3,
    "levelOrder": 10,
    "learningGoal": "掌握岛屿标记与枚举优化算法"
  },
  {
    "id": "water-flow",
    "name": "高山流水",
    "viewId": "algo-water-flow-view",
    "category": "graph",
    "description": "找出所有水流能同时到达左上和右下水域的格子",
    "icon": "💧",
    "difficulty": 3,
    "levelOrder": 9,
    "learningGoal": "掌握反向 BFS 求解水流可达性问题"
  },
  {
    "id": "string-migration",
    "name": "字符串迁移",
    "viewId": "algo-string-migration-view",
    "category": "graph",
    "description": "判断字符串能否通过循环移位变换为目标串",
    "icon": "🔄",
    "difficulty": 2,
    "levelOrder": 12,
    "learningGoal": "掌握拼接+滑动窗口检测循环移位"
  },
  {
    "id": "strongly-connected",
    "name": "完全连通性",
    "viewId": "algo-strongly-connected-view",
    "category": "graph",
    "description": "检测有向图中所有节点是否能互相到达（强连通）",
    "icon": "🔗",
    "difficulty": 3,
    "levelOrder": 13,
    "learningGoal": "掌握强连通性检测与 BFS 遍历"
  },
  {
    "id": "union-find-theory",
    "name": "并查集理论基础",
    "viewId": "algo-union-find-theory-view",
    "category": "graph",
    "description": "Union-Find 路径压缩与按秩合并可视化",
    "icon": "🔗",
    "difficulty": 1,
    "levelOrder": 14,
    "learningGoal": "理解并查集的 find 和 union 操作，以及路径压缩和按秩合并优化"
  },
  {
    "id": "find-route",
    "name": "寻找存在的路线",
    "viewId": "algo-find-route-view",
    "category": "graph",
    "description": "BFS 判断图中两节点间是否存在路径",
    "icon": "🛤️",
    "difficulty": 2,
    "levelOrder": 15,
    "learningGoal": "理解使用 BFS/DFS 判断图的连通性"
  },
  {
    "id": "redundant-edge",
    "name": "多余的边",
    "viewId": "algo-redundant-edge-view",
    "category": "graph",
    "description": "LeetCode 684: 用并查集检测环，找到多余的边",
    "icon": "✂️",
    "difficulty": 2,
    "levelOrder": 16,
    "learningGoal": "掌握用并查集检测图中的环"
  },
  {
    "id": "redundant-edge-ii",
    "name": "多余的边 II",
    "viewId": "algo-redundant-edge-ii-view",
    "category": "graph",
    "description": "LeetCode 685: 有向图中找出多余的边",
    "icon": "🔀",
    "difficulty": 3,
    "levelOrder": 17,
    "learningGoal": "掌握有向图中检测冲突节点和环的方法"
  },
  {
    "id": "mst-prim",
    "name": "最小生成树之 Prim 算法",
    "viewId": "algo-mst-prim-view",
    "category": "graph",
    "description": "Prim 贪心构建最小生成树可视化",
    "icon": "🌳",
    "difficulty": 3,
    "levelOrder": 18,
    "learningGoal": "理解 Prim 算法的贪心策略和 dist 数组的作用"
  },
  {
    "id": "mst-kruskal",
    "name": "最小生成树之 Kruskal 算法",
    "viewId": "algo-mst-kruskal-view",
    "category": "graph",
    "description": "Kruskal 贪心构建最小生成树，使用并查集判环",
    "icon": "🌲",
    "difficulty": 3,
    "levelOrder": 19,
    "learningGoal": "理解 Kruskal 算法的贪心策略和并查集在判环中的应用"
  },
  {
    "id": "topological-sort",
    "name": "拓扑排序",
    "viewId": "algo-topological-sort-view",
    "category": "graph",
    "description": "Kahn 算法：计算入度，反复移除入度为 0 的节点得到 DAG 拓扑序",
    "icon": "📐",
    "difficulty": 3,
    "levelOrder": 20,
    "learningGoal": "理解 Kahn 算法中入度计算和零入度节点队列的处理过程"
  },
  {
    "id": "dijkstra-basic",
    "name": "Dijkstra 朴素版",
    "viewId": "algo-dijkstra-basic-view",
    "category": "graph",
    "description": "数组-based O(V^2) 单源最短路径，每次选 dist 最小未访问节点",
    "icon": "📏",
    "difficulty": 3,
    "levelOrder": 21,
    "learningGoal": "理解 Dijkstra 算法中贪心选最小距离节点和边松弛的过程"
  },
  {
    "id": "dijkstra-heap",
    "name": "Dijkstra 堆优化版",
    "viewId": "algo-dijkstra-heap-view",
    "category": "graph",
    "description": "优先队列 O((V+E)logV) 单源最短路径",
    "icon": "🔮",
    "difficulty": 3,
    "levelOrder": 22,
    "learningGoal": "理解堆优化如何将选最小节点的操作从 O(V) 降到 O(logV)"
  },
  {
    "id": "bellman-ford",
    "name": "Bellman-Ford 算法",
    "viewId": "algo-bellman-ford-view",
    "category": "graph",
    "description": "松弛所有边 V-1 轮，支持负权边的单源最短路径",
    "icon": "🔄",
    "difficulty": 3,
    "levelOrder": 23,
    "learningGoal": "理解 Bellman-Ford 的逐轮松弛思想和负权边处理能力"
  },
  {
    "id": "spfa",
    "name": "SPFA 算法",
    "viewId": "algo-spfa-view",
    "category": "graph",
    "description": "Bellman-Ford 的队列优化版本，仅松弛队列中节点的出边",
    "icon": "⚡",
    "difficulty": 3,
    "levelOrder": 24,
    "learningGoal": "理解 SPFA 中队列优化如何避免不必要的松弛操作"
  },
  {
    "id": "negative-cycle",
    "name": "Bellman-Ford之判断负权回路",
    "viewId": "algo-negative-cycle-view",
    "category": "graph",
    "description": "通过 V-1 轮松弛后检查第 V 轮是否仍能更新来判断负权环",
    "icon": "⚠️",
    "difficulty": 3,
    "levelOrder": 25,
    "learningGoal": "理解 Bellman-Ford 算法检测负权回路的原理"
  },
  {
    "id": "floyd",
    "name": "Floyd算法",
    "viewId": "algo-floyd-view",
    "category": "graph",
    "description": "动态规划求解所有节点对之间的最短路径",
    "icon": "🔮",
    "difficulty": 3,
    "levelOrder": 26,
    "learningGoal": "理解 Floyd-Warshall 动态规划求解全源最短路"
  },
  {
    "id": "a-star",
    "name": "A*算法",
    "viewId": "algo-a-star-view",
    "category": "graph",
    "description": "启发式搜索 A* 寻路算法，f(n) = g(n) + h(n)",
    "icon": "⭐",
    "difficulty": 3,
    "levelOrder": 27,
    "learningGoal": "理解 A* 算法的启发式搜索策略和最优性保证"
  },
  {
    "id": "limited-shortest-path",
    "name": "Bellman-Ford之单源有限最短路",
    "viewId": "algo-limited-shortest-path-view",
    "category": "graph",
    "description": "限制最多经过 k 条边的单源最短路径",
    "icon": "🔗",
    "difficulty": 3,
    "levelOrder": 28,
    "learningGoal": "理解 Bellman-Ford 迭代次数与边数限制的关系"
  },
  {
    "id": "shortest-path-summary",
    "name": "最短路问题总结篇",
    "viewId": "algo-shortest-path-summary-view",
    "category": "graph",
    "description": "对比 Dijkstra、Bellman-Ford、SPFA、Floyd、A* 五大最短路算法",
    "icon": "📊",
    "difficulty": 1,
    "levelOrder": 29,
    "learningGoal": "理解五大最短路算法的适用场景和复杂度差异"
  },
  {
    "id": "graph-summary",
    "name": "图论总结篇",
    "viewId": "algo-graph-summary-view",
    "category": "graph",
    "description": "图论算法全景：遍历搜索、并查集、最小生成树、拓扑排序、最短路径",
    "icon": "🗺️",
    "difficulty": 1,
    "levelOrder": 30,
    "learningGoal": "掌握图论五大核心领域及其经典算法"
  },
  {
    "id": "tree-traversal",
    "name": "二叉树前中后序遍历",
    "viewId": "algo-tree-traversal-view",
    "category": "tree",
    "description": "递归实现前序/中序/后序遍历，对比三种访问顺序",
    "icon": "🌳",
    "difficulty": 1,
    "levelOrder": 1,
    "learningGoal": "掌握二叉树的前/中/后序遍历递归与非递归写法"
  },
  {
    "id": "tree-depth",
    "name": "二叉树最大深度",
    "viewId": "algo-tree-depth-view",
    "category": "tree",
    "description": "后序遍历求高度：max(左,右)+1",
    "icon": "📏",
    "difficulty": 1,
    "levelOrder": 2,
    "learningGoal": "理解递归求树深度的分治思想"
  },
  {
    "id": "valid-bst",
    "name": "验证二叉搜索树",
    "viewId": "algo-valid-bst-view",
    "category": "tree",
    "description": "中序遍历检查序列是否严格递增",
    "icon": "🔍",
    "difficulty": 2,
    "levelOrder": 3,
    "learningGoal": "理解 BST 的中序遍历序列必为有序"
  },
  {
    "id": "binary-tree-level",
    "name": "二叉树层序遍历（BFS）",
    "viewId": "algo-binary-tree-level-view",
    "category": "tree",
    "description": "队列逐层遍历，返回每层节点值列表",
    "icon": "🌲",
    "difficulty": 2,
    "levelOrder": 4,
    "learningGoal": "掌握 BFS 层序遍历队列模型"
  },
  {
    "id": "lca",
    "name": "最近公共祖先",
    "viewId": "algo-lca-view",
    "category": "tree",
    "description": "查找二叉树中两个节点的最近公共祖先",
    "icon": "🌳",
    "difficulty": 3,
    "levelOrder": 5,
    "learningGoal": "学会递归找二叉树最近公共祖先"
  },
  {
    "id": "tree-invert",
    "name": "二叉树翻转",
    "viewId": "algo-tree-invert-view",
    "category": "tree",
    "description": "递归翻转二叉树的左右子树",
    "icon": "🔄",
    "difficulty": 1,
    "levelOrder": 6,
    "learningGoal": "掌握递归翻转二叉树的自底向上方法"
  },
  {
    "id": "tree-symmetric",
    "name": "对称二叉树",
    "viewId": "algo-tree-symmetric-view",
    "category": "tree",
    "description": "判断二叉树是否镜像对称（左子树镜像 = 右子树）",
    "icon": "🪞",
    "difficulty": 2,
    "levelOrder": 7,
    "learningGoal": "掌握递归对比二叉树镜像对称性的技巧"
  },
  {
    "id": "path-sum",
    "name": "路径总和",
    "viewId": "algo-path-sum-view",
    "category": "tree",
    "description": "判断是否存在根到叶子的路径，路径和等于目标值",
    "icon": "🛤️",
    "difficulty": 2,
    "levelOrder": 8,
    "learningGoal": "掌握递归回溯求解根到叶子路径总和的技巧"
  },
  {
    "id": "build-tree",
    "name": "构造二叉树（先序+中序）",
    "viewId": "algo-build-tree-view",
    "category": "tree",
    "description": "从先序和中序遍历序列重建二叉树，理解分治构建",
    "icon": "🏗️",
    "difficulty": 3,
    "levelOrder": 9,
    "learningGoal": "掌握通过先序定位根、中序分割左右子树的构建方法"
  },
  {
    "id": "bst-search",
    "name": "二叉搜索树中的搜索",
    "viewId": "algo-bst-search-view",
    "category": "tree",
    "description": "利用 BST 性质在 O(log n) 时间内查找目标节点",
    "icon": "🔍",
    "difficulty": 1,
    "levelOrder": 10,
    "learningGoal": "理解 BST 的左小右大性质及高效搜索方法"
  },
  {
    "id": "min-depth",
    "name": "二叉树最小深度",
    "viewId": "algo-min-depth-view",
    "category": "tree",
    "description": "从根节点到最近叶子节点的最短路径上的节点数量",
    "icon": "📏",
    "difficulty": 1,
    "levelOrder": 11,
    "learningGoal": "理解最小深度与最大深度的区别，注意只有单侧子树的情况"
  },
  {
    "id": "balanced",
    "name": "平衡二叉树",
    "viewId": "algo-balanced-view",
    "category": "tree",
    "description": "判断二叉树是否为平衡二叉树（任意节点左右子树高度差不超过1）",
    "icon": "⚖️",
    "difficulty": 1,
    "levelOrder": 12,
    "learningGoal": "理解平衡二叉树的定义，掌握递归判断方法"
  },
  {
    "id": "left-leaves",
    "name": "左叶子之和",
    "viewId": "algo-left-leaves-view",
    "category": "tree",
    "description": "计算二叉树中所有左叶子节点的值之和",
    "icon": "🍃",
    "difficulty": 1,
    "levelOrder": 13,
    "learningGoal": "理解左叶子的定义，掌握递归时传递方向信息的方法"
  },
  {
    "id": "all-paths",
    "name": "二叉树所有路径",
    "viewId": "algo-all-paths-view",
    "category": "tree",
    "description": "返回所有从根节点到叶子节点的路径",
    "icon": "🛤️",
    "difficulty": 1,
    "levelOrder": 14,
    "learningGoal": "掌握回溯法收集路径的技巧"
  },
  {
    "id": "count-nodes",
    "name": "完全二叉树节点个数",
    "viewId": "algo-count-nodes-view",
    "category": "tree",
    "description": "计算完全二叉树的节点总数",
    "icon": "🔢",
    "difficulty": 1,
    "levelOrder": 15,
    "learningGoal": "理解完全二叉树的性质，掌握递归计数方法"
  },
  {
    "id": "bottom-left",
    "name": "找树左下角的值",
    "viewId": "algo-bottom-left-view",
    "category": "tree",
    "description": "找出二叉树最底层最左边节点的值",
    "icon": "🎯",
    "difficulty": 1,
    "levelOrder": 16,
    "learningGoal": "掌握通过深度比较找到最底层最左节点的方法"
  },
  {
    "id": "max-tree",
    "name": "最大二叉树",
    "viewId": "algo-max-tree-view",
    "category": "tree",
    "description": "根据数组构建最大二叉树：最大值作为根，递归构建左右子树",
    "icon": "🌲",
    "difficulty": 2,
    "levelOrder": 17,
    "learningGoal": "理解递归构建树的思想，找到最大值作为根节点"
  },
  {
    "id": "merge-trees",
    "name": "合并二叉树",
    "viewId": "algo-merge-trees-view",
    "category": "tree",
    "description": "合并两棵二叉树，对应节点值相加",
    "icon": "🤝",
    "difficulty": 1,
    "levelOrder": 18,
    "learningGoal": "理解递归合并两棵树的方法"
  },
  {
    "id": "build-tree-2",
    "name": "中序+后序构造二叉树",
    "viewId": "algo-build-tree-2-view",
    "category": "tree",
    "description": "从中序和后序遍历序列构造二叉树",
    "icon": "🔨",
    "difficulty": 2,
    "levelOrder": 19,
    "learningGoal": "理解后序遍历的特点，最后一个元素是根"
  },
  {
    "id": "bst-lca",
    "name": "BST最近公共祖先",
    "viewId": "algo-bst-lca-view",
    "category": "tree",
    "description": "利用BST性质找最近公共祖先",
    "icon": "🔗",
    "difficulty": 2,
    "levelOrder": 20,
    "learningGoal": "利用BST性质优化LCA查找"
  },
  {
    "id": "bst-insert",
    "name": "BST插入操作",
    "viewId": "algo-bst-insert-view",
    "category": "tree",
    "description": "向BST中插入新节点",
    "icon": "➕",
    "difficulty": 1,
    "levelOrder": 21,
    "learningGoal": "掌握BST插入的递归实现"
  },
  {
    "id": "bst-min-diff",
    "name": "BST最小绝对差",
    "viewId": "algo-bst-min-diff-view",
    "category": "tree",
    "description": "BST中任意两节点的最小差值",
    "icon": "📏",
    "difficulty": 1,
    "levelOrder": 22,
    "learningGoal": "利用BST中序遍历的有序性"
  },
  {
    "id": "bst-modes",
    "name": "BST中的众数",
    "viewId": "algo-bst-modes-view",
    "category": "tree",
    "description": "找出BST中出现次数最多的节点值",
    "icon": "📊",
    "difficulty": 1,
    "levelOrder": 23,
    "learningGoal": "中序遍历统计节点频率"
  },
  {
    "id": "bst-delete",
    "name": "删除BST节点",
    "viewId": "algo-bst-delete-view",
    "category": "tree",
    "description": "从BST中删除指定值的节点",
    "icon": "🗑️",
    "difficulty": 2,
    "levelOrder": 24,
    "learningGoal": "掌握BST删除的三种情况"
  },
  {
    "id": "bst-trim",
    "name": "修剪BST",
    "viewId": "algo-bst-trim-view",
    "category": "tree",
    "description": "修剪BST使所有节点值在[low, high]范围内",
    "icon": "✂️",
    "difficulty": 2,
    "levelOrder": 25,
    "learningGoal": "理解BST修剪的递归逻辑"
  },
  {
    "id": "sorted-array-to-bst",
    "name": "有序数组转BST",
    "viewId": "algo-sorted-array-to-bst-view",
    "category": "tree",
    "description": "将有序数组转换为高度平衡的BST",
    "icon": "🔄",
    "difficulty": 1,
    "levelOrder": 26,
    "learningGoal": "分治构建平衡BST"
  },
  {
    "id": "bst-to-gst",
    "name": "BST转累加树",
    "viewId": "algo-bst-to-gst-view",
    "category": "tree",
    "description": "将BST转换为累加树（右根左遍历）",
    "icon": "💰",
    "difficulty": 2,
    "levelOrder": 27,
    "learningGoal": "掌握反向中序遍历（右根左）"
  },
  {
    "id": "binary-search",
    "name": "二分查找",
    "viewId": "algo-binary-search-view",
    "category": "search",
    "description": "在有序数组中以 O(log n) 时间定位目标",
    "icon": "🔍",
    "difficulty": 1,
    "levelOrder": 1,
    "learningGoal": "掌握二分搜索的标准写法与边界处理"
  },
  {
    "id": "bubble-sort",
    "name": "冒泡排序",
    "viewId": "algo-bubble-sort-view",
    "category": "sort",
    "description": "逐步演示冒泡排序：相邻元素比较、交换、冒泡到位",
    "icon": "🌪️",
    "difficulty": 1,
    "levelOrder": 2,
    "learningGoal": "理解冒泡排序的相邻比较和元素冒泡过程"
  },
  {
    "id": "insertion-sort",
    "name": "插入排序",
    "viewId": "algo-insertion-sort-view",
    "category": "sort",
    "description": "逐步演示插入排序：key 元素飞起漂浮、比较、移位、落入",
    "icon": "📊",
    "difficulty": 1,
    "levelOrder": 1,
    "learningGoal": "理解插入排序的原地排序过程"
  },
  {
    "id": "merge-sort",
    "name": "归并排序",
    "viewId": "algo-merge-sort-view",
    "category": "sort",
    "description": "递归拆分 + 指针合并，演示分治思想的完整过程",
    "icon": "🌿",
    "difficulty": 2,
    "levelOrder": 5,
    "learningGoal": "理解归并排序的分治递归结构与双指针合并过程"
  },
  {
    "id": "quick-sort",
    "name": "快速排序",
    "viewId": "algo-quick-sort-view",
    "category": "sort",
    "description": "逐步演示快速排序：选择 pivot、分区、递归左右子数组",
    "icon": "⚡",
    "difficulty": 2,
    "levelOrder": 4,
    "learningGoal": "理解快速排序的分治递归和分区过程"
  },
  {
    "id": "selection-sort",
    "name": "选择排序",
    "viewId": "algo-selection-sort-view",
    "category": "sort",
    "description": "逐步演示选择排序：扫描找最小值、标记、交换到已排序区末尾",
    "icon": "🎯",
    "difficulty": 1,
    "levelOrder": 3,
    "learningGoal": "理解选择排序的选最小-交换过程"
  },
  {
    "id": "heap-sort",
    "name": "堆排序",
    "viewId": "algo-heap-sort-view",
    "category": "sort",
    "description": "利用最大堆性质反复提取最大值，柱状图 + 树形结构双视图",
    "icon": "🌲",
    "difficulty": 3,
    "levelOrder": 6,
    "learningGoal": "理解堆排序的建堆与排序过程，掌握堆化的下沉机制"
  },
  {
    "id": "shell-sort",
    "name": "希尔排序",
    "viewId": "algo-shell-sort-view",
    "category": "sort",
    "description": "按间隔分组进行插入排序，逐步缩小间隔至完成排序",
    "icon": "📏",
    "difficulty": 2,
    "levelOrder": 7,
    "learningGoal": "理解希尔排序的分组插入排序思想"
  },
  {
    "id": "radix-sort",
    "name": "基数排序",
    "viewId": "algo-radix-sort-view",
    "category": "sort",
    "description": "按位（个/十/百...）分配到 0-9 号桶再收集，从最低位开始",
    "icon": "🔟",
    "difficulty": 2,
    "levelOrder": 9,
    "learningGoal": "理解 LSD 基数排序的按位分配与收集过程"
  },
  {
    "id": "counting-sort",
    "name": "计数排序",
    "viewId": "algo-counting-sort-view",
    "category": "sort",
    "description": "非比较排序：统计频次 → 前缀和定位 → 反向放入输出数组",
    "icon": "🔢",
    "difficulty": 2,
    "levelOrder": 8,
    "learningGoal": "理解计数排序的非比较排序原理和前缀和定位方法"
  },
  {
    "id": "bucket-sort",
    "name": "桶排序",
    "viewId": "algo-bucket-sort-view",
    "category": "sort",
    "description": "将元素分配到多个桶中，桶内排序后合并得到有序序列",
    "icon": "🪣",
    "difficulty": 3,
    "levelOrder": 10,
    "learningGoal": "理解桶排序的分治思想：分桶 → 桶内排序 → 合并"
  },
  {
    "id": "greedy-theory",
    "name": "贪心算法理论基础",
    "viewId": "algo-greedy-theory-view",
    "category": "greedy",
    "description": "贪心算法的适用条件、证明方法与通用解题流程",
    "icon": "📘",
    "difficulty": 1,
    "levelOrder": 0
  },
  {
    "id": "assign-cookies",
    "name": "分发饼干",
    "viewId": "algo-assign-cookies-view",
    "category": "greedy",
    "description": "LeetCode 455：贪心算法，分配饼干满足尽可能多的孩子",
    "icon": "🍪",
    "difficulty": 1,
    "levelOrder": 1,
    "learningGoal": "理解贪心算法的局部最优推导全局最优思想"
  },
  {
    "id": "wiggle-subsequence",
    "name": "摆动序列",
    "viewId": "algo-wiggle-subsequence-view",
    "category": "greedy",
    "description": "LeetCode 376：贪心算法，找到最长摆动子序列的长度",
    "icon": "🌊",
    "difficulty": 1,
    "levelOrder": 2,
    "learningGoal": "掌握摆动序列的贪心策略"
  },
  {
    "id": "max-subarray",
    "name": "最大子序和",
    "viewId": "algo-max-subarray-view",
    "category": "greedy",
    "description": "LeetCode 53：贪心算法，找到具有最大和的连续子数组",
    "icon": "📊",
    "difficulty": 1,
    "levelOrder": 3,
    "learningGoal": "理解最大子数组和的贪心选择"
  },
  {
    "id": "greedy-week-summary",
    "name": "贪心周总结",
    "viewId": "algo-greedy-week-summary-view",
    "category": "greedy",
    "description": "按分配、序列、覆盖、区间、树形贪心整理专题套路",
    "icon": "🧭",
    "difficulty": 1,
    "levelOrder": 50
  },
  {
    "id": "best-time-stock",
    "name": "买卖股票的最佳时机 II",
    "viewId": "algo-best-time-stock-view",
    "category": "greedy",
    "description": "LeetCode 122：贪心算法，收集所有正收益，最大化利润",
    "icon": "📈",
    "difficulty": 1,
    "levelOrder": 4,
    "learningGoal": "掌握只允许一次交易的贪心策略"
  },
  {
    "id": "can-jump",
    "name": "跳跃游戏 I",
    "viewId": "algo-can-jump-view",
    "category": "greedy",
    "description": "LeetCode 55：贪心算法，判断是否可以跳到数组末尾",
    "icon": "🦘",
    "difficulty": 1,
    "levelOrder": 5,
    "learningGoal": "理解跳跃可行性判断的贪心覆盖范围"
  },
  {
    "id": "jump-game",
    "name": "跳跃游戏 II",
    "viewId": "algo-jump-game-view",
    "category": "greedy",
    "description": "LeetCode 45：贪心算法，找到到达数组末尾的最少跳跃次数",
    "icon": "🦘",
    "difficulty": 2,
    "levelOrder": 6,
    "learningGoal": "掌握求最少跳跃次数的贪心策略"
  },
  {
    "id": "maximize-sum-k",
    "name": "K次取反后最大化的数组和",
    "viewId": "algo-maximize-sum-k-view",
    "category": "greedy",
    "description": "LeetCode 1005：贪心算法，K次操作后使数组和最大化",
    "icon": "🔄",
    "difficulty": 1,
    "levelOrder": 7,
    "learningGoal": "理解 K 次取反后最大化的贪心选择"
  },
  {
    "id": "greedy-week-summary-2",
    "name": "贪心周总结",
    "viewId": "algo-greedy-week-summary-2-view",
    "category": "greedy",
    "description": "贪心覆盖类题目阶段总结：股票、跳跃游戏、K 次取反与加油站",
    "icon": "🧭",
    "difficulty": 1,
    "levelOrder": 51
  },
  {
    "id": "gas-station",
    "name": "加油站",
    "viewId": "algo-gas-station-view",
    "category": "greedy",
    "description": "LeetCode 134：贪心算法，从某个加油站出发，绕环路一圈返回起点",
    "icon": "⛽",
    "difficulty": 2,
    "levelOrder": 8,
    "learningGoal": "掌握加油站可行起点的贪心推导"
  },
  {
    "id": "candy",
    "name": "分发糖果",
    "viewId": "algo-candy-view",
    "category": "greedy",
    "description": "LeetCode 135：贪心算法，每个孩子至少一个糖果，评分更高的孩子必须比相邻孩子糖果多",
    "icon": "🍬",
    "difficulty": 3,
    "levelOrder": 9,
    "learningGoal": "理解两次遍历的糖果分配策略"
  },
  {
    "id": "lemonade",
    "name": "柠檬水找零",
    "viewId": "algo-lemonade-view",
    "category": "greedy",
    "description": "LeetCode 860：贪心算法，每杯柠檬水 $5，顾客用 $5/$10/$20 购买，判断能否成功找零",
    "icon": "🍋",
    "difficulty": 1,
    "levelOrder": 10,
    "learningGoal": "掌握找零模拟的贪心计数"
  },
  {
    "id": "reconstruct-queue",
    "name": "根据身高重建队列",
    "viewId": "algo-reconstruct-queue-view",
    "category": "greedy",
    "description": "LeetCode 406：贪心算法，根据身高和k值构建队列",
    "icon": "👥",
    "difficulty": 3,
    "levelOrder": 11,
    "learningGoal": "理解排序加按身高位置插入的贪心策略"
  },
  {
    "id": "greedy-week-summary-3",
    "name": "贪心周总结",
    "viewId": "algo-greedy-week-summary-3-view",
    "category": "greedy",
    "description": "贪心区间类题目阶段总结：队列重建、射箭、无重叠区间、划分字母与合并区间",
    "icon": "🧭",
    "difficulty": 1,
    "levelOrder": 52
  },
  {
    "id": "queue-vector-explained",
    "name": "根据身高重建队列（vector原理讲解）",
    "viewId": "algo-queue-vector-explained-view",
    "category": "greedy",
    "description": "解释按身高降序、按 k 插入的 vector/数组重建队列原理",
    "icon": "📚",
    "difficulty": 3,
    "levelOrder": 12
  },
  {
    "id": "min-arrows",
    "name": "用最少数量的箭引爆气球",
    "viewId": "algo-min-arrows-view",
    "category": "greedy",
    "description": "LeetCode 452：贪心算法，用最少数量的箭引爆所有气球",
    "icon": "🎯",
    "difficulty": 2,
    "levelOrder": 13,
    "learningGoal": "掌握区间交集贪心求最少箭数"
  },
  {
    "id": "non-overlapping",
    "name": "无重叠区间",
    "viewId": "algo-non-overlapping-view",
    "category": "greedy",
    "description": "LeetCode 435：贪心算法，找到最少的区间数量使得剩余区间不重叠",
    "icon": "📐",
    "difficulty": 2,
    "levelOrder": 14,
    "learningGoal": "理解区间排序加贪心求不重叠数量"
  },
  {
    "id": "partition-labels",
    "name": "划分字母区间",
    "viewId": "algo-partition-labels-view",
    "category": "greedy",
    "description": "LeetCode 763：贪心算法，将字符串划分为尽可能多的片段",
    "icon": "🔤",
    "difficulty": 2,
    "levelOrder": 15,
    "learningGoal": "掌握字母区间分割的贪心思路"
  },
  {
    "id": "merge-intervals",
    "name": "合并区间",
    "viewId": "algo-merge-intervals-view",
    "category": "greedy",
    "description": "LeetCode 56：贪心算法，排序后逐个合并重叠区间",
    "icon": "🧩",
    "difficulty": 2,
    "levelOrder": 16,
    "learningGoal": "理解区间合并的排序加贪心策略"
  },
  {
    "id": "greedy-week-summary-4",
    "name": "贪心周总结",
    "viewId": "algo-greedy-week-summary-4-view",
    "category": "greedy",
    "description": "贪心收尾阶段总结：合并区间、单调递增数字与二叉树摄像头",
    "icon": "🧭",
    "difficulty": 1,
    "levelOrder": 53
  },
  {
    "id": "monotone-digits",
    "name": "单调递增的数字",
    "viewId": "algo-monotone-digits-view",
    "category": "greedy",
    "description": "LeetCode 738：贪心算法，找到小于等于 n 的最大单调递增数字",
    "icon": "🔢",
    "difficulty": 3,
    "levelOrder": 17,
    "learningGoal": "掌握构造单调递增数字的贪心方法"
  },
  {
    "id": "tree-cameras",
    "name": "监控二叉树",
    "viewId": "algo-tree-cameras-view",
    "category": "greedy",
    "description": "LeetCode 968：贪心算法，计算监控二叉树所需的最少摄像头数量",
    "icon": "📹",
    "difficulty": 3,
    "levelOrder": 18,
    "learningGoal": "理解树形贪心加状态机的最少监控覆盖"
  },
  {
    "id": "greedy-final-summary",
    "name": "贪心算法总结篇",
    "viewId": "algo-greedy-final-summary-view",
    "category": "greedy",
    "description": "贪心专题最终复盘：排序、覆盖、贡献、局部约束四类套路",
    "icon": "🏁",
    "difficulty": 1,
    "levelOrder": 54
  },
  {
    "id": "backtracking-theory",
    "name": "回溯算法理论基础",
    "viewId": "algo-backtracking-theory-view",
    "category": "backtracking",
    "description": "回溯算法的递归模板、搜索树与剪枝方法",
    "icon": "📘",
    "difficulty": 1,
    "levelOrder": 0
  },
  {
    "id": "combination",
    "name": "组合问题（回溯）",
    "viewId": "algo-combination-view",
    "category": "backtracking",
    "description": "使用回溯算法生成所有组合",
    "icon": "🎯",
    "difficulty": 1,
    "levelOrder": 1,
    "learningGoal": "掌握回溯法的基础框架：选择、递归、撤销，理解决策树结构"
  },
  {
    "id": "combination-optimized",
    "name": "组合（优化）",
    "viewId": "algo-combination-optimized-view",
    "category": "backtracking",
    "description": "剪枝优化：i <= n - (k - path.length) + 1",
    "icon": "✂️",
    "difficulty": 1,
    "levelOrder": 2,
    "learningGoal": "学会用剪枝优化回溯搜索"
  },
  {
    "id": "combination-sum-iii",
    "name": "组合总和 III",
    "viewId": "algo-combination-sum-iii-view",
    "category": "backtracking",
    "description": "LeetCode 216 · 1-9 选 k 个不重复，和为 n",
    "icon": "🎯",
    "difficulty": 2,
    "levelOrder": 3,
    "learningGoal": "理解在回溯中结合求和约束与数量约束的决策树结构"
  },
  {
    "id": "phone-letters",
    "name": "电话号码字母组合",
    "viewId": "algo-phone-letters-view",
    "category": "backtracking",
    "description": "LeetCode 17：回溯算法，给定数字字符串，返回所有可能的字母组合",
    "icon": "📞",
    "difficulty": 2,
    "levelOrder": 4,
    "learningGoal": "掌握多组字符组合的回溯展开"
  },
  {
    "id": "backtracking-week-summary-1",
    "name": "回溯周末总结（一）",
    "viewId": "algo-backtracking-week-summary-1-view",
    "category": "backtracking",
    "description": "组合类题目的 startIndex、剪枝与复用边界总结",
    "icon": "🧭",
    "difficulty": 1,
    "levelOrder": 5
  },
  {
    "id": "combination-sum",
    "name": "组合总和（回溯）",
    "viewId": "algo-combination-sum-view",
    "category": "backtracking",
    "description": "元素可重复使用，回溯 + 剪枝求所有组合",
    "icon": "🎯",
    "difficulty": 2,
    "levelOrder": 6,
    "learningGoal": "理解无限重复选择的回溯搜索与决策树结构"
  },
  {
    "id": "combination-sum-ii",
    "name": "组合总和 II",
    "viewId": "algo-combination-sum-ii-view",
    "category": "backtracking",
    "description": "LeetCode 40 · 排序 + 同层去重，每个元素只用一次",
    "icon": "🎯",
    "difficulty": 2,
    "levelOrder": 7,
    "learningGoal": "掌握含重复元素组合去重的回溯方法与决策树结构"
  },
  {
    "id": "palindrome-partition",
    "name": "分割回文串",
    "viewId": "algo-palindrome-partition-view",
    "category": "backtracking",
    "description": "LeetCode 131：回溯算法，通过回溯枚举所有回文切割方案",
    "icon": "🪟",
    "difficulty": 2,
    "levelOrder": 8,
    "learningGoal": "理解回文分割的回溯搜索策略"
  },
  {
    "id": "restore-ip",
    "name": "复原IP地址",
    "viewId": "algo-restore-ip-view",
    "category": "backtracking",
    "description": "LeetCode 93 · 字符串切 3 个点，每段 0–255",
    "icon": "🌐",
    "difficulty": 3,
    "levelOrder": 9,
    "learningGoal": "掌握 IP 地址分割的回溯加合法性校验"
  },
  {
    "id": "subset",
    "name": "子集（回溯）",
    "viewId": "algo-subset-view",
    "category": "backtracking",
    "description": "使用回溯算法生成所有子集",
    "icon": "📦",
    "difficulty": 1,
    "levelOrder": 10,
    "learningGoal": "理解子集生成的回溯方法（每层都收集）"
  },
  {
    "id": "backtracking-week-summary-2",
    "name": "回溯周末总结（二）",
    "viewId": "algo-backtracking-week-summary-2-view",
    "category": "backtracking",
    "description": "切割、子集与同层去重的阶段性总结",
    "icon": "🧭",
    "difficulty": 1,
    "levelOrder": 11
  },
  {
    "id": "subsets-ii",
    "name": "子集II",
    "viewId": "algo-subsets-ii-view",
    "category": "backtracking",
    "description": "LeetCode 90 · 排序 + 同层去重求不重复子集",
    "icon": "🧩",
    "difficulty": 2,
    "levelOrder": 12,
    "learningGoal": "掌握含重复元素子集去重的回溯策略"
  },
  {
    "id": "increasing-subsequences",
    "name": "递增子序列",
    "viewId": "algo-increasing-subsequences-view",
    "category": "backtracking",
    "description": "LeetCode 491 · 每层 Set 去重，收集长度 >= 2",
    "icon": "📈",
    "difficulty": 2,
    "levelOrder": 13,
    "learningGoal": "理解递增子序列的去重回溯"
  },
  {
    "id": "permutation",
    "name": "全排列·决策树",
    "viewId": "algo-permutation-view",
    "category": "backtracking",
    "description": "决策树视角：可视化回溯生成所有排列",
    "icon": "🔀",
    "difficulty": 1,
    "levelOrder": 14,
    "learningGoal": "掌握全排列的回溯生成方法"
  },
  {
    "id": "permutation-ii",
    "name": "全排列II",
    "viewId": "algo-permutation-ii-view",
    "category": "backtracking",
    "description": "LeetCode 47 · 排序 + used + 同层去重",
    "icon": "🔀",
    "difficulty": 2,
    "levelOrder": 16,
    "learningGoal": "理解含重复元素的全排列去重回溯"
  },
  {
    "id": "backtracking-week-summary-3",
    "name": "回溯周末总结（三）",
    "viewId": "algo-backtracking-week-summary-3-view",
    "category": "backtracking",
    "description": "递增子序列、排列与棋盘问题总结",
    "icon": "🧭",
    "difficulty": 1,
    "levelOrder": 17
  },
  {
    "id": "backtracking-dedup-alt",
    "name": "回溯算法去重问题的另一种写法",
    "viewId": "algo-backtracking-dedup-alt-view",
    "category": "backtracking",
    "description": "从 used 数组与本层集合两个角度理解回溯去重",
    "icon": "♻️",
    "difficulty": 2,
    "levelOrder": 18,
    "learningGoal": "掌握另一种回溯去重思路"
  },
  {
    "id": "nqueen",
    "name": "N皇后",
    "viewId": "algo-nqueen-view",
    "category": "backtracking",
    "description": "逐行放置皇后，检查列与两条对角线冲突",
    "icon": "👑",
    "difficulty": 3,
    "levelOrder": 19,
    "learningGoal": "掌握 N 皇后问题中约束检查的回溯框架"
  },
  {
    "id": "sudoku",
    "name": "解数独",
    "viewId": "algo-sudoku-view",
    "category": "backtracking",
    "description": "LeetCode 37 · 找空格、试数字、合法递归、失败回溯",
    "icon": "🔢",
    "difficulty": 3,
    "levelOrder": 20,
    "learningGoal": "理解数独求解中行/列/宫三维约束的回溯"
  },
  {
    "id": "backtracking-final-summary",
    "name": "回溯法总结篇",
    "viewId": "algo-backtracking-final-summary-view",
    "category": "backtracking",
    "description": "回溯专题的题型、模板、剪枝和去重总复盘",
    "icon": "🏁",
    "difficulty": 1,
    "levelOrder": 50
  },
  {
    "id": "unique-paths",
    "name": "不同路径",
    "viewId": "unique-paths",
    "category": "dynamic-programming",
    "description": "网格路径数（LeetCode 62）：从左上角到右下角，只能向下或向右移动，空间复杂度优化至一维 O(n)。",
    "icon": "🧭",
    "difficulty": 2,
    "levelOrder": 5,
    "learningGoal": "掌握二维网格路径模型与一维空间压缩优化技巧"
  },
  {
    "id": "dp-theory",
    "name": "动态规划理论基础",
    "viewId": "dp-theory",
    "category": "dynamic-programming",
    "description": "动态规划五部曲、状态定义、递推公式与遍历顺序。",
    "icon": "📘",
    "difficulty": 1,
    "levelOrder": 1
  },
  {
    "id": "fibonacci",
    "name": "斐波那契数",
    "viewId": "fibonacci",
    "category": "dynamic-programming",
    "description": "dp[i] = dp[i-1] + dp[i-2]，动态规划经典入门。",
    "icon": "🔢",
    "difficulty": 1,
    "levelOrder": 2
  },
  {
    "id": "climb-stairs",
    "name": "爬楼梯",
    "viewId": "climb-stairs",
    "category": "dynamic-programming",
    "description": "每次爬 1 或 2 阶，方案数来自前两阶。",
    "icon": "🪜",
    "difficulty": 1,
    "levelOrder": 3
  },
  {
    "id": "min-cost-climbing-stairs",
    "name": "使用最小花费爬楼梯",
    "viewId": "min-cost-climbing-stairs",
    "category": "dynamic-programming",
    "description": "到达当前台阶的最小花费来自前一阶或前两阶。",
    "icon": "💰",
    "difficulty": 1,
    "levelOrder": 4
  },
  {
    "id": "dp-week-summary-1",
    "name": "动规周总结（一）",
    "viewId": "dp-week-summary-1",
    "category": "dynamic-programming",
    "description": "一维基础 DP：斐波那契、爬楼梯、最小花费。",
    "icon": "🧭",
    "difficulty": 1,
    "levelOrder": 5
  },
  {
    "id": "unique-paths-ii",
    "name": "不同路径II",
    "viewId": "unique-paths-ii",
    "category": "dynamic-programming",
    "description": "带障碍网格路径数：障碍格路径数为 0。",
    "icon": "🚧",
    "difficulty": 1,
    "levelOrder": 6
  },
  {
    "id": "decode-ways",
    "name": "解码方法",
    "viewId": "decode-ways",
    "category": "dynamic-programming",
    "description": "数字串翻译方案数（LeetCode 91）：取 1 位或 2 位数字映射为 A-Z。",
    "icon": "🔢",
    "difficulty": 1,
    "levelOrder": 7
  },
  {
    "id": "integer-break",
    "name": "整数拆分",
    "viewId": "integer-break",
    "category": "dynamic-programming",
    "description": "将正整数拆分为至少两个正整数的和，使乘积最大。",
    "icon": "✂️",
    "difficulty": 1,
    "levelOrder": 8
  },
  {
    "id": "unique-bst",
    "name": "不同的二叉搜索树",
    "viewId": "unique-bst",
    "category": "dynamic-programming",
    "description": "以不同根节点切分左右子树方案数乘积。",
    "icon": "🌲",
    "difficulty": 1,
    "levelOrder": 9
  },
  {
    "id": "dp-week-summary-2",
    "name": "动规周总结（二）",
    "viewId": "dp-week-summary-2",
    "category": "dynamic-programming",
    "description": "路径问题、整数拆分、不同 BST 的阶段总结。",
    "icon": "🧭",
    "difficulty": 1,
    "levelOrder": 10
  },
  {
    "id": "knapsack-01-theory-1",
    "name": "0-1背包理论基础（一）",
    "viewId": "knapsack-01-theory-1",
    "category": "dynamic-programming",
    "description": "二维 0/1 背包：物品和容量两维状态。",
    "icon": "🎒",
    "difficulty": 1,
    "levelOrder": 11
  },
  {
    "id": "knapsack-01-2d",
    "name": "0-1背包问题（二维）",
    "viewId": "knapsack-01-2d",
    "category": "dynamic-programming",
    "description": "每个物品只能使用一次：dp[i][j] 表示前 i 件物品在容量 j 下的最大价值。",
    "icon": "🎒",
    "difficulty": 1,
    "levelOrder": 12
  },
  {
    "id": "knapsack-01-theory-2",
    "name": "0-1背包理论基础（二）",
    "viewId": "knapsack-01-theory-2",
    "category": "dynamic-programming",
    "description": "一维滚动数组：容量倒序遍历避免重复使用物品。",
    "icon": "🎒",
    "difficulty": 1,
    "levelOrder": 13
  },
  {
    "id": "knapsack-01-1d",
    "name": "0-1背包问题（一维）",
    "viewId": "knapsack-01-1d",
    "category": "dynamic-programming",
    "description": "滚动数组空间压缩：容量 j 必须从大到小倒序遍历，避免同件物品被重复选入。",
    "icon": "🎒",
    "difficulty": 1,
    "levelOrder": 14
  },
  {
    "id": "partition-equal-subset-sum",
    "name": "分割等和子集",
    "viewId": "partition-equal-subset-sum",
    "category": "dynamic-programming",
    "description": "判断是否能将数组划分为两个和相等的子集（转化为容量为 sum/2 的 0/1 背包）。",
    "icon": "⚖️",
    "difficulty": 1,
    "levelOrder": 15
  },
  {
    "id": "last-stone-weight-ii",
    "name": "最后一块石头的重量 II",
    "viewId": "last-stone-weight-ii",
    "category": "dynamic-programming",
    "description": "两两粉碎等价于将石头分成总重最接近的两堆（0/1 背包）。",
    "icon": "🪨",
    "difficulty": 1,
    "levelOrder": 16
  },
  {
    "id": "target-sum",
    "name": "目标和",
    "viewId": "target-sum",
    "category": "dynamic-programming",
    "description": "添加正负号凑出 target（转化为 0/1 背包求解装满容量为 (sum+target)/2 的方案数）。",
    "icon": "🎯",
    "difficulty": 1,
    "levelOrder": 17
  },
  {
    "id": "ones-and-zeroes",
    "name": "一和零",
    "viewId": "ones-and-zeroes",
    "category": "dynamic-programming",
    "description": "二维费用 0-1 背包：最多含有 m 个 0 和 n 个 1 的最大子集大小。",
    "icon": "0️⃣",
    "difficulty": 1,
    "levelOrder": 18
  },
  {
    "id": "dp-week-summary-3",
    "name": "动规周总结（三）",
    "viewId": "dp-week-summary-3",
    "category": "dynamic-programming",
    "description": "0/1 背包应用题总结。",
    "icon": "🧭",
    "difficulty": 1,
    "levelOrder": 19
  },
  {
    "id": "complete-knapsack-theory",
    "name": "完全背包理论基础",
    "viewId": "complete-knapsack-theory",
    "category": "dynamic-programming",
    "description": "完全背包：每件物品可以使用无限次，容量正序遍历。",
    "icon": "🧺",
    "difficulty": 1,
    "levelOrder": 20
  },
  {
    "id": "complete-knapsack",
    "name": "完全背包问题",
    "viewId": "complete-knapsack",
    "category": "dynamic-programming",
    "description": "每种物品有无限件可用：容量 j 正序遍历，允许同种物品累加。",
    "icon": "🧺",
    "difficulty": 1,
    "levelOrder": 21
  },
  {
    "id": "coin-change-ii",
    "name": "零钱兑换 II",
    "viewId": "coin-change-ii",
    "category": "dynamic-programming",
    "description": "求凑成总金额的组合数：外层遍历硬币、内层正序遍历金额。",
    "icon": "🪙",
    "difficulty": 1,
    "levelOrder": 22
  },
  {
    "id": "combination-sum-iv",
    "name": "组合总和 Ⅳ",
    "viewId": "combination-sum-iv",
    "category": "dynamic-programming",
    "description": "排列数完全背包：外层正序遍历容量、内层遍历物品。",
    "icon": "🔢",
    "difficulty": 1,
    "levelOrder": 23
  },
  {
    "id": "climb-stairs-advanced",
    "name": "爬楼梯（进阶完全背包）",
    "viewId": "climb-stairs-advanced",
    "category": "dynamic-programming",
    "description": "一步可上 1..m 阶，等价于容量为 n 的排列数完全背包。",
    "icon": "🪜",
    "difficulty": 1,
    "levelOrder": 24
  },
  {
    "id": "dp-week-summary-4",
    "name": "动规周总结（四）",
    "viewId": "dp-week-summary-4",
    "category": "dynamic-programming",
    "description": "完全背包组合数问题总结。",
    "icon": "🧭",
    "difficulty": 1,
    "levelOrder": 25
  },
  {
    "id": "coin-change",
    "name": "零钱兑换",
    "viewId": "coin-change",
    "category": "dynamic-programming",
    "description": "凑成目标金额所需的最少硬币数（完全背包求最小值）。",
    "icon": "🪙",
    "difficulty": 1,
    "levelOrder": 26
  },
  {
    "id": "perfect-squares",
    "name": "完全平方数",
    "viewId": "perfect-squares",
    "category": "dynamic-programming",
    "description": "和为 n 的完全平方数的最少数量（完全背包）。",
    "icon": "🟩",
    "difficulty": 1,
    "levelOrder": 27
  },
  {
    "id": "word-break",
    "name": "单词拆分",
    "viewId": "word-break",
    "category": "dynamic-programming",
    "description": "能否由字典单词拼接出目标字符串 s（排列型完全背包）。",
    "icon": "🔤",
    "difficulty": 1,
    "levelOrder": 28
  },
  {
    "id": "dp-week-summary-5",
    "name": "动规周总结（五）",
    "viewId": "dp-week-summary-5",
    "category": "dynamic-programming",
    "description": "完全背包最值问题与单词拆分总结。",
    "icon": "🧭",
    "difficulty": 1,
    "levelOrder": 29
  },
  {
    "id": "multiple-knapsack-theory",
    "name": "多重背包理论基础",
    "viewId": "multiple-knapsack-theory",
    "category": "dynamic-programming",
    "description": "有限件物品的背包问题，可展开为多个 0/1 物品。",
    "icon": "📦",
    "difficulty": 1,
    "levelOrder": 30
  },
  {
    "id": "multiple-knapsack",
    "name": "多重背包理论基础",
    "viewId": "multiple-knapsack",
    "category": "dynamic-programming",
    "description": "每种物品有有限数量上限，可展开为 0-1 背包或二进制拆分。",
    "icon": "📦",
    "difficulty": 1,
    "levelOrder": 31
  },
  {
    "id": "knapsack-summary",
    "name": "背包问题总结篇",
    "viewId": "knapsack-summary",
    "category": "dynamic-programming",
    "description": "0/1、完全、多重背包及组合/排列/最值类公式汇总。",
    "icon": "🏁",
    "difficulty": 1,
    "levelOrder": 32
  },
  {
    "id": "house-robber",
    "name": "打家劫舍",
    "viewId": "house-robber",
    "category": "dynamic-programming",
    "description": "不相邻房屋最大金额：dp[i] = max(dp[i-1], dp[i-2] + nums[i])。",
    "icon": "🏠",
    "difficulty": 1,
    "levelOrder": 33
  },
  {
    "id": "house-robber-ii",
    "name": "打家劫舍 II",
    "viewId": "house-robber-ii",
    "category": "dynamic-programming",
    "description": "环形房屋破圈为双区间：[0..n-2] 与 [1..n-1] 取最大值。",
    "icon": "🏘️",
    "difficulty": 1,
    "levelOrder": 34
  },
  {
    "id": "house-robber-iii",
    "name": "打家劫舍 III",
    "viewId": "house-robber-iii",
    "category": "dynamic-programming",
    "description": "二叉树树形 DP：后序遍历返回 [不偷当前节点, 偷当前节点] 状态二元组。",
    "icon": "🌳",
    "difficulty": 1,
    "levelOrder": 35
  },
  {
    "id": "best-time-to-buy-and-sell-stock",
    "name": "买卖股票的最佳时机",
    "viewId": "best-time-to-buy-and-sell-stock",
    "category": "dynamic-programming",
    "description": "只能买卖一次：维护历史最低买入价与当日卖出最大差价。",
    "icon": "📈",
    "difficulty": 1,
    "levelOrder": 36
  },
  {
    "id": "best-time-to-buy-and-sell-stock-ii",
    "name": "买卖股票的最佳时机 II",
    "viewId": "best-time-to-buy-and-sell-stock-ii",
    "category": "dynamic-programming",
    "description": "可以进行多次交易：只要今天比昨天价格高就累加正收益。",
    "icon": "📊",
    "difficulty": 1,
    "levelOrder": 37
  },
  {
    "id": "dp-week-summary-6",
    "name": "动规周总结（六）",
    "viewId": "dp-week-summary-6",
    "category": "dynamic-programming",
    "description": "打家劫舍与股票入门状态机总结。",
    "icon": "🧭",
    "difficulty": 1,
    "levelOrder": 38
  },
  {
    "id": "best-time-to-buy-and-sell-stock-iii",
    "name": "买卖股票的最佳时机 III",
    "viewId": "best-time-to-buy-and-sell-stock-iii",
    "category": "dynamic-programming",
    "description": "最多可以完成两笔交易：构建五状态有限状态机。",
    "icon": "📉",
    "difficulty": 1,
    "levelOrder": 39
  },
  {
    "id": "best-time-to-buy-and-sell-stock-iv",
    "name": "买卖股票的最佳时机 IV",
    "viewId": "best-time-to-buy-and-sell-stock-iv",
    "category": "dynamic-programming",
    "description": "最多可以完成 k 笔交易：构建 2k+1 状态有限状态机。",
    "icon": "💹",
    "difficulty": 1,
    "levelOrder": 40
  },
  {
    "id": "best-time-to-buy-and-sell-stock-with-cooldown",
    "name": "买卖股票的最佳时机含冷冻期",
    "viewId": "best-time-to-buy-and-sell-stock-with-cooldown",
    "category": "dynamic-programming",
    "description": "卖出股票后有一天冷冻期：构建持有、冷冻、自由三状态机。",
    "icon": "🧊",
    "difficulty": 1,
    "levelOrder": 41
  },
  {
    "id": "best-time-to-buy-and-sell-stock-with-transaction-fee",
    "name": "买卖股票的最佳时机含手续费",
    "viewId": "best-time-to-buy-and-sell-stock-with-transaction-fee",
    "category": "dynamic-programming",
    "description": "每次交易产生手续费：卖出套现时扣减手续费。",
    "icon": "💳",
    "difficulty": 1,
    "levelOrder": 42
  },
  {
    "id": "dp-week-summary-7",
    "name": "动规周总结（七）",
    "viewId": "dp-week-summary-7",
    "category": "dynamic-programming",
    "description": "多交易、冷冻期、手续费股票题总结。",
    "icon": "🧭",
    "difficulty": 1,
    "levelOrder": 43
  },
  {
    "id": "stock-summary",
    "name": "股票问题总结篇",
    "viewId": "stock-summary",
    "category": "dynamic-programming",
    "description": "股票 DP 的持有/不持有、多次交易、冷冻期和手续费状态总结。",
    "icon": "📈",
    "difficulty": 1,
    "levelOrder": 44
  },
  {
    "id": "longest-increasing-subsequence",
    "name": "最长递增子序列",
    "viewId": "longest-increasing-subsequence",
    "category": "dynamic-programming",
    "description": "dp[i] 表示以 nums[i] 结尾的最长严格递增子序列长度。",
    "icon": "📈",
    "difficulty": 1,
    "levelOrder": 45
  },
  {
    "id": "longest-continuous-increasing-subsequence",
    "name": "最长连续递增序列",
    "viewId": "longest-continuous-increasing-subsequence",
    "category": "dynamic-programming",
    "description": "要求严格相邻连续：只需向前看一位 dp[i] = dp[i-1] + 1。",
    "icon": "📏",
    "difficulty": 1,
    "levelOrder": 46
  },
  {
    "id": "longest-repeated-subarray",
    "name": "最长重复子数组",
    "viewId": "longest-repeated-subarray",
    "category": "dynamic-programming",
    "description": "两数组中连续公共子数组的最长长度：相等时仅从左上角对角线累加。",
    "icon": "🧩",
    "difficulty": 1,
    "levelOrder": 47
  },
  {
    "id": "longest-common-subsequence",
    "name": "最长公共子序列",
    "viewId": "longest-common-subsequence",
    "category": "dynamic-programming",
    "description": "不要求连续的最长公共子序列：相等时对角线加1，不等时取左方和上方较大值。",
    "icon": "🧬",
    "difficulty": 1,
    "levelOrder": 48
  },
  {
    "id": "uncrossed-lines",
    "name": "不相交的线",
    "viewId": "uncrossed-lines",
    "category": "dynamic-programming",
    "description": "连线不相交等价于两数组的最长公共子序列 (LCS)。",
    "icon": "🧶",
    "difficulty": 1,
    "levelOrder": 49
  },
  {
    "id": "max-subarray-dp",
    "name": "最大子数组和",
    "viewId": "max-subarray-dp",
    "category": "dynamic-programming",
    "description": "连续子数组最大和：dp[i] = max(nums[i], dp[i-1] + nums[i])。",
    "icon": "➕",
    "difficulty": 1,
    "levelOrder": 50
  },
  {
    "id": "is-subsequence",
    "name": "判断子序列",
    "viewId": "is-subsequence",
    "category": "dynamic-programming",
    "description": "双指针或 DP 判定 s 是否为 t 的子序列。",
    "icon": "🔍",
    "difficulty": 1,
    "levelOrder": 51
  },
  {
    "id": "distinct-subsequences",
    "name": "不同的子序列",
    "viewId": "distinct-subsequences",
    "category": "dynamic-programming",
    "description": "在字符串 s 的子序列中 t 出现的次数。",
    "icon": "🧮",
    "difficulty": 1,
    "levelOrder": 52
  },
  {
    "id": "delete-operation-for-two-strings",
    "name": "两个字符串的删除操作",
    "viewId": "delete-operation-for-two-strings",
    "category": "dynamic-programming",
    "description": "使两字符串相同所需的最小删除步数：直接 DP 或 word1.len + word2.len - 2*LCS。",
    "icon": "🗑️",
    "difficulty": 1,
    "levelOrder": 53
  },
  {
    "id": "edit-distance",
    "name": "编辑距离",
    "viewId": "edit-distance",
    "category": "dynamic-programming",
    "description": "将 word1 转换成 word2 所使用的最少操作数（插入、删除、替换）。",
    "icon": "✏️",
    "difficulty": 1,
    "levelOrder": 54
  },
  {
    "id": "edit-distance-summary",
    "name": "编辑距离总结篇",
    "viewId": "edit-distance-summary",
    "category": "dynamic-programming",
    "description": "判断子序列、不同子序列、删除操作、编辑距离的状态转移对比。",
    "icon": "✍️",
    "difficulty": 1,
    "levelOrder": 55
  },
  {
    "id": "palindromic-substrings",
    "name": "回文子串",
    "viewId": "palindromic-substrings",
    "category": "dynamic-programming",
    "description": "统计字符串中回文子串的总数目（区间 DP 从下往上遍历）。",
    "icon": "🪞",
    "difficulty": 1,
    "levelOrder": 56
  },
  {
    "id": "longest-palindromic-subsequence",
    "name": "最长回文子序列",
    "viewId": "longest-palindromic-subsequence",
    "category": "dynamic-programming",
    "description": "找出字符串中最长的回文子序列长度（区间 DP 向内收缩）。",
    "icon": "👑",
    "difficulty": 1,
    "levelOrder": 57
  },
  {
    "id": "dp-final-summary",
    "name": "动态规划总结篇",
    "viewId": "dp-final-summary",
    "category": "dynamic-programming",
    "description": "动态规划专题总复盘：状态、转移、遍历顺序和题型地图。",
    "icon": "🏁",
    "difficulty": 1,
    "levelOrder": 58
  },
  {
    "id": "clash-of-algorithms",
    "name": "部落冲突·战术攻防沙盘",
    "viewId": "algo-clash-of-algorithms-view",
    "category": "game",
    "description": "还原《部落冲突》核心玩法：兵种 A* 寻路偏好、开孔引导阵破障权衡与防御塔索敌机制",
    "icon": "⚔️",
    "difficulty": 3,
    "levelOrder": 1,
    "learningGoal": "通过策略游戏直观理解工业级 A* 寻路权重配置、目标过滤剪枝与空间索敌算法"
  },
  {
    "id": "knapsack-dungeon",
    "name": "背包商人·地牢探险",
    "viewId": "algo-knapsack-dungeon-view",
    "category": "game",
    "description": "动态规划冒险游戏：地牢搜刮神兵利刃、实时 DP 矩阵求解最优配装、大战地牢守关魔王",
    "icon": "🎒",
    "difficulty": 3,
    "levelOrder": 2,
    "learningGoal": "通过地牢配装与 Boss 决战，彻底掌握 0-1 背包与完全背包的状态转移方程与最优子结构"
  },
  {
    "id": "maze-defense",
    "name": "迷宫塔防·寻路破坏者",
    "viewId": "algo-maze-defense-view",
    "category": "game",
    "description": "图论塔防游戏：建造石墙改变网格拓扑、怪兽 Dijkstra 最短路逃逸、打造蛇形迷宫全歼敌军",
    "icon": "🏰",
    "difficulty": 3,
    "levelOrder": 3,
    "learningGoal": "掌握动态图最短路径算法（Dijkstra / BFS）、拓扑连通性与最小割阻断对抗原理"
  },
  {
    "id": "nqueen-battle",
    "name": "国际象棋·N皇后对弈",
    "viewId": "algo-nqueen-battle-view",
    "category": "game",
    "description": "回溯算法棋盘游戏：放置皇后投射激光射线、人机对弈与 92 组解全景画廊速览",
    "icon": "👑",
    "difficulty": 3,
    "levelOrder": 4,
    "learningGoal": "透视约束满足问题（CSP）在对角线、行、列的剪枝原理与回溯算法状态空间搜索"
  },
  {
    "id": "lava-parkour",
    "name": "熔岩跑酷·单调栈跳跃者",
    "viewId": "algo-lava-parkour-view",
    "category": "game",
    "description": "单调栈物理跑酷游戏：60 FPS 抛物线跳跃、动态熔岩上涨躲避、实时单调递减栈透视与下一个更大元素求解",
    "icon": "🌋",
    "difficulty": 3,
    "levelOrder": 5,
    "learningGoal": "通过熔岩逃逸飞跃实战，彻底掌握单调递减栈的入栈、出栈与下一个更大元素（NGE）计算规律"
  },
  {
    "id": "gas-station-rally",
    "name": "极速加油站·环岛拉力赛",
    "viewId": "algo-gas-station-view",
    "category": "game",
    "description": "经典贪心算法游戏：环形霓虹赛道、实时剩余油量表盘、局部透支跳跃剪枝与 360° 胜利巡游",
    "icon": "🏎️",
    "difficulty": 3,
    "levelOrder": 6,
    "learningGoal": "通过环形赛车与油量补给实战，彻底掌握贪心算法中的局部透支排除法与全局可行性充要条件"
  },
  {
    "id": "lemonade-tycoon",
    "name": "柠檬水摊贩·贪心收银大亨",
    "viewId": "algo-lemonade-tycoon-view",
    "category": "game",
    "description": "经典贪心经营游戏：海滩柠檬水小摊、实时钞票抽屉、$20 找零贪心权衡与一键自动收银推演",
    "icon": "🍹",
    "difficulty": 2,
    "levelOrder": 7,
    "learningGoal": "掌握贪心选择性质（Greedy Choice Property）在硬币找零与资源通用性权衡中的关键作用"
  },
  {
    "id": "cookie-feeder",
    "name": "萌宠餐厅·饼干大派送",
    "viewId": "algo-cookie-feeder-view",
    "category": "game",
    "description": "双指针贪心算法游戏：萌宠餐厅、香脆饼干托盘、抛物线咀嚼投喂动画与双序列最优匹配",
    "icon": "🍪",
    "difficulty": 2,
    "levelOrder": 8,
    "learningGoal": "掌握双排序 + 双指针贪心算法在双序列容量与需求匹配中的核心应用"
  },
  {
    "id": "sudoku-cipher",
    "name": "数独神偷·密码解构者",
    "viewId": "algo-sudoku-cipher-view",
    "category": "game",
    "description": "回溯算法数独游戏：9x9 赛博密码矩阵、实时十字线冲突扫描、动态量子回溯求解与世界难题挑战",
    "icon": "🧩",
    "difficulty": 3,
    "levelOrder": 9,
    "learningGoal": "透视经典回溯与约束满足问题（CSP）在二维空间中的试探、冲突检测与撤销回溯机制"
  },
  {
    "id": "sliding-snake",
    "name": "贪吃蛇·滑动窗口大吞噬",
    "viewId": "algo-sliding-snake-view",
    "category": "game",
    "description": "滑动窗口双指针游戏：赛博贪吃蛇身躯伸缩、符文排异机制、实时哈希映射与无重复最长子串求解",
    "icon": "🐍",
    "difficulty": 2,
    "levelOrder": 10,
    "learningGoal": "通过贪吃蛇身躯伸缩实战，彻底掌握滑动窗口右边界主动探索、左边界被动收缩与哈希去重的时空优化"
  }
];
