/**
 * 算法图标多级解析器 (Catalog Icons Deep Utility)
 * 职责：
 * 统筹全库算法图标解析，建立明确的三级回退流水线：
 * 1. 算法 Manifest/Meta 声明的专属 emoji 图标
 * 2. 经典题目 ID 映射词典 (ALGORITHM_EXPLICIT_ICONS)
 * 3. 算法所属分类预设图标 (CATEGORY_CONFIG[category].icon)
 * 4. 兜底通用图标 '📄'
 */

import { CATEGORY_CONFIG } from '../category-config';
import type { AlgorithmMetadata } from '../registry';

export const ALGORITHM_EXPLICIT_ICONS: Record<string, string> = {
  lca: '🌳',
  'tree-invert': '🔄',
  'insertion-sort': '📊',
  'quick-sort': '⚡',
  'binary-search': '🔍',
  'jump-game': '🦘',
  combination: '🎯',
  candy: '🍬',
  'phone-letters': '📞',
  lemonade: '🥤',
  permutation: '🔀',
  'gas-station': '⛽',
  subset: '🗂️',
  interval: '📏',
  nqueen: '👑',
  fibonacci: '🔢',
  'merge-intervals': '🧩',
  'climb-stairs': '🪜',
  'palindrome-partition': '🪞',
  'greedy-theory': '📘',
  'greedy-week-summary': '🧭',
  'greedy-week-summary-2': '🧭',
  'greedy-week-summary-3': '🧭',
  'greedy-week-summary-4': '🧭',
  'greedy-final-summary': '🏁',
  'assign-cookies': '🍪',
  'wiggle-subsequence': '📈',
  'max-subarray': '📊',
  'best-time-stock': '📈',
  'can-jump': '🏃',
  'maximize-sum-k': '➖',
  'reconstruct-queue': '👥',
  'queue-vector-explained': '📚',
  'min-arrows': '🏹',
  'non-overlapping': '📐',
  'partition-labels': '🔤',
  'monotone-digits': '9️⃣',
  'tree-cameras': '📹',
  'tree-symmetric': '🪞',
  'path-sum': '🛤️',
  'build-tree': '🏗️',
  'bst-search': '🔍',
  'min-depth': '📏',
  'balanced': '⚖️',
  'left-leaves': '🍃',
  'all-paths': '🛤️',
  'count-nodes': '🔢',
  'bottom-left': '🎯',
  'max-tree': '🌲',
  'merge-trees': '🤝',
  'build-tree-2': '🔨',
  'bst-lca': '🔗',
  'bst-insert': '➕',
  'bst-min-diff': '📏',
  'bst-modes': '📊',
  'bst-delete': '🗑️',
  'bst-trim': '✂️',
  'sorted-array-to-bst': '🔄',
  'bst-to-gst': '💰',
  'replace-digits': '🔢',
  'four-sum': '🎯',
  'hash-table-theory': '📖',
  'intersection-arrays': '🔀',
  'happy-number': '😊',
  'four-sum-ii': '🧮',
  'ransom-note': '📰',
  'reverse-string-ii': '🔁',
  'right-rotate-string': '🔄',
  'str-str': '🔍',
  'repeated-substring': '🔁',
  'stack-queue-theory': '📖',
  'implement-queue-using-stack': '🔄',
  'implement-stack-using-queue': '🥞',
  bracket: '🎯',
  'remove-adjacent-duplicates': '✨',
  'eval-rpn': '🧮',
  'sliding-window-max': '📊',
  'top-k-frequent': '🏆',
  'array-theory': '📖',
  'sorted-squares': '²',
  'range-sum': 'Σ',
  'buy-land': '🏞️',
  'array-summary': '📝',
  'next-greater-element-i': '🔍',
  'next-greater-element-ii': '🔄',
  'largest-rectangle-histogram': '📊',
  'graph-theory': '📖',
  'forward-star': '🕸️',
  'dfs-theory': '🔍',
  'bfs-theory': '🌊',
  'reachable-paths': '🛤️',
  'islands-bfs': '🏝️',
  'max-island-area': '📐',
  'total-island-area': 'Σ',
  'sink-islands': '🌊',
  'water-flow': '💧',
  'make-largest-island': '🏗️',
  'coastline': '🌊',
  'string-migration': '🔄',
  'strongly-connected': '🔗',
  'union-find-theory': '🌲',
  'find-route': '🗺️',
  'redundant-edge': '✂️',
  'redundant-edge-ii': '✂️',
  'mst-prim': '🌿',
  'mst-kruskal': '🔗',
  'topological-sort': '📐',
  'dijkstra-basic': '📏',
  'dijkstra-heap': '🔮',
  'bellman-ford': '🔄',
  spfa: '⚡',
  'negative-cycle': '⚠️',
  floyd: '🧮',
  'a-star': '⭐',
  'limited-shortest-path': '🔢',
  'shortest-path-summary': '📝',
  'graph-summary': '🗺️',
  'clash-of-algorithms': '⚔️',
  'knapsack-dungeon': '🎒',
  'maze-defense': '🏰',
  'nqueen-battle': '👑',
  'lava-parkour': '🌋',
  'gas-station-rally': '🏎️',
  'lemonade-tycoon': '🍹',
  'cookie-feeder': '🍪',
  'sudoku-cipher': '🧩',
  'sliding-snake': '🐍',
  'candy-kingdom': '🍬',
  'palindrome-ninja': '🗡️',
  'jump-quest': '🦘',
  'spy-dial': '📞',
  'interval-warp': '🛸',
  'arrow-balloon': '🎯',
  'heist-robber': '🥷',
  'stock-trader': '📈',
  'binary-sonar': '📡',
  'layered-dijkstra': '🛫',
  'bfs-01': '🧱',
  'bi-bfs': '🔤',
  'topo-dp': '🎓',
  'alien-dict': '👽',
  'trapping-water-ii': '🌊',
  'a-star-journey': '🧭',
  'couples-holding-hands': '💑',
  'people-secret': '🕵️',
  'hungarian-matching': '💘',
  'tarjan-bridge': '✂️',
  'diff-constraints': '⚖️',
  'state-compression-bfs': '🧭',
  'eulerian-circuit': '🎨',
  'good-paths': '🛤️',
  'malware-spread-ii': '🦠',
  'tarjan-scc-dag': '🔄',
  'dijkstra-index-heap': '⚡',
  'dinic-max-flow': '🌊',
  'kruskal-reconstruction-tree': '🌲',
  'min-cost-max-flow': '💰',
  'km-algorithm': '💘',
  'heavy-light-decomposition': '🎋',
  'tree-centroid-decomposition': '👑',
  'konig-min-vertex-cover': '🛡️',
  'lca-binary-lifting': '🌲',
  'pseudotree-dp': '🎡',
  'two-sat-problem': '⚖️',
  'stable-marriage': '💍',
  'block-cut-tree': '🌵',
  'tree-difference': '🌲',
  'second-mst': '🌲',
  'k-shortest-path': '🚀',
  'cycle-counting': '🔺',
  'bipartite-game': '♟️',
  'prufer-sequence': '📼',
  'dominator-tree': '🏛️',
  'bounded-flow': '🌊',
  'centroid-tree': '🌲',
  'max-weight-closure': '💰',
  'virtual-tree': '🌲',
  'path-min-effort': '⛰️',
  'ev-charge-dijkstra': '⚡',
  'dsu-on-tree': '🌲',
  'planar-graph-dual': '🌐',
  'min-path-cover': '🚀',
  'chordal-graph': '🎻',
  'network-delay-time': '📡',
  'tree-path-intersection': '🌲',
  'prefix-opt-graph': '🌐',
  'tree-dominant-color': '👑',
  'mixed-eulerian-circuit': '🔄',
  'tree-centroid-path-count': '🌲',
  'min-mean-cycle': '🔄',
  'tree-knapsack-dp': '🎒',
  'convex-hull-3d': '🌐',
  'swim-in-rising-water': '🏊',
  'knapsack-01-standard': '🎒',
  'buy-goods-discount': '🏷️',
  'target-sum-standard': '🎯',
  'last-stone-weight-ii-standard': '🪨',
  'dependent-knapsack-standard': '🛒',
  'top-k-subsequence-sum': '🌳',
  'find-kth-sum': '🪞',
  'partitioned-knapsack-standard': '🗂️',
  'coins-from-piles': '🪙',
  'unbounded-knapsack-standard': '🌿',
  'regex-matching': '🔤',
  'wildcard-matching': '🃏',
  'buying-hay-min-cost': '🌾',
};

/**
 * 解析算法对应的呈现图标
 */
export function resolveAlgorithmIcon(algo: Partial<AlgorithmMetadata> | null | undefined): string {
  if (!algo) return '📄';

  // 1. 如果自身显式声明了非 FontAwesome 的 emoji 字符
  if (algo.icon && !algo.icon.startsWith('fa-')) {
    return algo.icon;
  }

  // 2. 匹配显式映射表
  if (algo.id && ALGORITHM_EXPLICIT_ICONS[algo.id]) {
    return ALGORITHM_EXPLICIT_ICONS[algo.id];
  }

  // 3. 匹配所属分类的默认图标
  if (algo.category && CATEGORY_CONFIG[algo.category]?.icon) {
    return CATEGORY_CONFIG[algo.category].icon;
  }

  // 4. 兜底
  return '📄';
}
