/**
 * 背包四阶段演化多语言代码模板库 (Knapsack Stage Code Templates)
 *
 * 使用 @step:anchor 语义锚点标注，由 CodeStepIndexer 在编译期自动
 * 解析为 Java / C++ / Python / JavaScript 四语种 1-based 物理行号。
 * 彻底消除 knapsack-stage-evolution.ts 中 ~400 行手动 STAGE_LINE_MAPS 常量。
 *
 * 模板结构严格对齐 knapsack-073/074-problem-content.ts 中的原始代码，
 * 确保 anchor 解析行号与原有手动常量 100% 一致。
 */

import { createStageCodeRegistry, type StageCodeMap, type ResolvedAnchorTarget } from '../stage-code-registry';
import type { HighlightTarget } from './dark-code-terminal-presenter';
import type { KnapsackKind } from './knapsack-stage-evolution';

// ==========================================
// 1. 阶段 1: DFS 递归暴力搜索
//    对齐 knapsack-074 UNBOUNDED / knapsack-073 01 / knapsack-074 PARTITIONED
// ==========================================

const S1_UNBOUNDED: Record<string, string[]> = {
  java: [
    'package class074;',
    '',
    '// 阶段 1: 暴力递归完全背包',
    'public class Code03_UnboundedKnapsackStage1 {',
    '    public static long compute(int t, int m, int[] cost, int[] val) { // @step:callRoot',
    '        return dfs(0, t, m, cost, val);',
    '    }',
    '    private static long dfs(int i, int remCap, int m, int[] cost, int[] val) { // @step:fnEnter',
    '        if (i >= m || remCap <= 0) return 0; // @step:baseCheck',
    '        long p1 = dfs(i + 1, remCap, m, cost, val); // @step:branch1',
    '        long p2 = 0; // @step:initP2',
    '        if (remCap >= cost[i]) { // @step:checkFit',
    '            p2 = dfs(i, remCap - cost[i], m, cost, val) + val[i]; // @step:branch2',
    '        }',
    '        return Math.max(p1, p2); // @step:returnMax',
    '    }',
    '}',
  ],
  cpp: [
    '#include <iostream>',
    '#include <vector>',
    '#include <algorithm>',
    'using namespace std;',
    '',
    '// 阶段 1: 暴力递归完全背包',
    '// 每种草药可选无限次：若选当前草药，停留在第 i 种继续选；若不选，跳到第 i + 1 种',
    'long long dfs(int i, int remCap, int m, const vector<int>& cost, const vector<int>& val) { // @step:callRoot',
    '    if (i >= m || remCap <= 0) return 0; // @step:fnEnter',
    '    // 分支 1: 不选当前草药，考察下一个物种',
    '    long long p1 = dfs(i + 1, remCap, m, cost, val); // @step:baseCheck',
    '    // 分支 2: 选入当前草药，容量扣减，依然停留在第 i 种（支持无限次累选）',
    '    long long p2 = 0; // @step:branch1',
    '    if (remCap >= cost[i]) { // @step:initP2',
    '        p2 = dfs(i, remCap - cost[i], m, cost, val) + val[i]; // @step:checkFit',
    '    }',
    '    return max(p1, p2); // @step:branch2',
    '}',
  ],
  python: [
    'def dfs_unbounded(i: int, rem_cap: int, cost: list[int], val: list[int]) -> int: // @step:callRoot',
    '    """阶段 1: 暴力递归完全背包"""',
    '    if i >= len(cost) or rem_cap <= 0: // @step:fnEnter',
    '        return 0 // @step:baseCheck',
    '    p1 = dfs_unbounded(i + 1, rem_cap, cost, val) // @step:branch1',
    '    p2 = 0 // @step:initP2',
    '    if rem_cap >= cost[i]: // @step:checkFit',
    '        p2 = dfs_unbounded(i, rem_cap - cost[i], cost, val) + val[i] // @step:branch2',
    '    return max(p1, p2) // @step:returnMax',
  ],
  javascript: [
    '// 阶段 1: 暴力递归完全背包',
    'export function dfsUnbounded(i, remCap, cost, val) { // @step:callRoot',
    '  if (i >= cost.length || remCap <= 0) return 0; // @step:fnEnter',
    '  const p1 = dfsUnbounded(i + 1, remCap, cost, val); // @step:baseCheck',
    '  let p2 = 0; // @step:branch1',
    '  if (remCap >= cost[i]) { // @step:initP2',
    '    p2 = dfsUnbounded(i, remCap - cost[i], cost, val) + val[i]; // @step:checkFit',
    '  }',
    '  return Math.max(p1, p2); // @step:branch2',
    '}',
  ],
};

const S1_01: Record<string, string[]> = {
  java: [
    'package class073;',
    '',
    '// 阶段 1: 01背包暴力递归',
    'public class Code01_01KnapsackStage1 {',
    '    public static int compute(int t, int m, int[] cost, int[] val) { // @step:callRoot',
    '        return dfs(0, t, m, cost, val);',
    '    }',
    '    private static int dfs(int i, int remCap, int m, int[] cost, int[] val) { // @step:fnEnter',
    '        if (i >= m || remCap <= 0) return 0; // @step:baseCheck',
    '        int p1 = dfs(i + 1, remCap, m, cost, val); // @step:branch1',
    '        int p2 = 0; // @step:initP2',
    '        if (remCap >= cost[i]) { // @step:checkFit',
    '            p2 = dfs(i + 1, remCap - cost[i], m, cost, val) + val[i]; // @step:branch2',
    '        }',
    '        return Math.max(p1, p2); // @step:returnMax',
    '    }',
    '}',
  ],
  cpp: [
    '#include <iostream>',
    '#include <vector>',
    '#include <algorithm>',
    'using namespace std;',
    '',
    '// 阶段 1: 01背包暴力递归 (每件物品选或不选，均推进至 i + 1)',
    'int dfs(int i, int remCap, int m, const vector<int>& cost, const vector<int>& val) { // @step:callRoot',
    '    if (i >= m || remCap <= 0) return 0; // @step:fnEnter',
    '    // 分支 1: 不选当前物品',
    '    int p1 = dfs(i + 1, remCap, m, cost, val); // @step:baseCheck',
    '    // 分支 2: 选入当前物品（消耗容量，推进至下一件物品）',
    '    int p2 = 0; // @step:branch1',
    '    if (remCap >= cost[i]) { // @step:initP2',
    '        p2 = dfs(i + 1, remCap - cost[i], m, cost, val) + val[i]; // @step:checkFit',
    '    }',
    '    return max(p1, p2); // @step:branch2',
    '}',
  ],
  python: [
    'def dfs_01(i: int, rem_cap: int, cost: list[int], val: list[int]) -> int: // @step:callRoot',
    '    """阶段 1: 01背包暴力递归"""',
    '    if i >= len(cost) or rem_cap <= 0: // @step:fnEnter',
    '        return 0 // @step:baseCheck',
    '    p1 = dfs_01(i + 1, rem_cap, cost, val) // @step:branch1',
    '    p2 = 0 // @step:initP2',
    '    if rem_cap >= cost[i]: // @step:checkFit',
    '        p2 = dfs_01(i + 1, rem_cap - cost[i], cost, val) + val[i] // @step:branch2',
    '    return max(p1, p2) // @step:returnMax',
  ],
  javascript: [
    '// 阶段 1: 01背包暴力递归',
    'export function dfs01Knapsack(i, remCap, cost, val) { // @step:callRoot',
    '  if (i >= cost.length || remCap <= 0) return 0; // @step:fnEnter',
    '  const p1 = dfs01Knapsack(i + 1, remCap, cost, val); // @step:baseCheck',
    '  let p2 = 0; // @step:branch1',
    '  if (remCap >= cost[i]) { // @step:initP2',
    '    p2 = dfs01Knapsack(i + 1, remCap - cost[i], cost, val) + val[i]; // @step:checkFit',
    '  }',
    '  return Math.max(p1, p2); // @step:branch2',
    '}',
  ],
};

// partitioned stage1 保持原有逻辑
const S1_PARTITIONED: Record<string, string[]> = {
  java: [
    'class Solution {',
    '    // 分组背包：每组最多选 1 种',
    '    public int solve(int[][] groups, int[] values, int[] weights, int n, int capacity) { // @step:callRoot',
    '        return dfs(0, capacity, groups, values, weights, n);',
    '    }',
    '    private int dfs(int idx, int remCap, int[][] groups, int[] values, int[] weights, int n) { // @step:fnEnter',
    '        if (idx >= n || remCap <= 0) return 0; // @step:baseCheck',
    '        int best = dfs(idx + 1, remCap, groups, values, weights, n); // @step:branch1',
    '        for (int choice : groups[idx]) { // @step:loopGroup',
    '            int itemW = weights[choice];',
    '            if (itemW <= remCap) { // @step:checkFit',
    '                int val = values[choice] + dfs(idx + 1, remCap - itemW, groups, values, weights, n); // @step:branch2',
    '                best = Math.max(best, val); // @step:returnMax',
    '            }',
    '        }',
    '        return best; // @step:returnMax',
    '    }',
    '}',
  ],
  cpp: [
    '#include <vector>',
    '#include <algorithm>',
    'using namespace std;',
    '',
    '// 分组背包：每组最多选 1 种',
    'class Solution {',
    'public:',
    '    int solve(vector<vector<int>>& groups, vector<int>& values, vector<int>& weights, int n, int capacity) { // @step:callRoot',
    '        return dfs(0, capacity, groups, values, weights, n);',
    '    }',
    '    int dfs(int idx, int remCap, vector<vector<int>>& groups, vector<int>& values, vector<int>& weights, int n) { // @step:fnEnter',
    '        if (idx >= n || remCap <= 0) return 0; // @step:baseCheck',
    '        int best = dfs(idx + 1, remCap, groups, values, weights, n); // @step:branch1',
    '        for (int choice : groups[idx]) { // @step:loopGroup',
    '            int itemW = weights[choice];',
    '            if (itemW <= remCap) { // @step:checkFit',
    '                int val = values[choice] + dfs(idx + 1, remCap - itemW, groups, values, weights, n); // @step:branch2',
    '                best = max(best, val); // @step:returnMax',
    '            }',
    '        }',
    '        return best; // @step:returnMax',
    '    }',
    '};',
  ],
  python: [
    'def solve(groups, values, weights, n, capacity): # @step:callRoot',
    '    # 分组背包：每组最多选 1 种',
    '    def dfs(idx, rem_cap): # @step:fnEnter',
    '        if idx >= n or rem_cap <= 0: # @step:baseCheck',
    '            return 0',
    '        best = dfs(idx + 1, rem_cap) # @step:branch1',
    '        for choice in groups[idx]: # @step:loopGroup',
    '            item_w = weights[choice]',
    '            if item_w <= rem_cap: # @step:checkFit',
    '                val = values[choice] + dfs(idx + 1, rem_cap - item_w) # @step:branch2',
    '                best = max(best, val) # @step:returnMax',
    '        return best # @step:returnMax',
    '    return dfs(0, capacity)',
  ],
  javascript: [
    'export function solve(groups, values, weights, n, capacity) { // @step:callRoot',
    '  // 分组背包：每组最多选 1 种',
    '  function dfs(idx, remCap) { // @step:fnEnter',
    '    if (idx >= n || remCap <= 0) return 0; // @step:baseCheck',
    '    let best = dfs(idx + 1, remCap); // @step:branch1',
    '    for (const choice of groups[idx]) { // @step:loopGroup',
    '      const itemW = weights[choice];',
    '      if (itemW <= remCap) { // @step:checkFit',
    '        const val = values[choice] + dfs(idx + 1, remCap - itemW); // @step:branch2',
    '        best = Math.max(best, val); // @step:returnMax',
    '      }',
    '    }',
    '    return best; // @step:returnMax',
    '  }',
    '  return dfs(0, capacity);',
    '}',
  ],
};

// ==========================================
// 2. 阶段 2: 记忆化搜索
// ==========================================

const S2_UNBOUNDED: Record<string, string[]> = {
  java: [
    'package class074;',
    '',
    'import java.util.Arrays;',
    '',
    '// 阶段 2: 记忆化搜索完全背包',
    'public class Code03_UnboundedKnapsackStage2 {',
    '    public static long compute(int t, int m, int[] cost, int[] val) { // @step:callRoot',
    '        long[][] memo = new long[m][t + 1]; // @step:memoInit',
    '        for (long[] row : memo) Arrays.fill(row, -1); // @step:memoFill',
    '        return dfsMemo(0, t, m, cost, val, memo);',
    '    }',
    '    private static long dfsMemo(int i, int remCap, int m, int[] cost, int[] val, long[][] memo) { // @step:fnEnter',
    '        if (i >= m || remCap <= 0) return 0; // @step:baseCheck',
    '        if (memo[i][remCap] != -1) return memo[i][remCap]; // @step:memoCheck',
    '        long p1 = dfsMemo(i + 1, remCap, m, cost, val, memo); // @step:branch1',
    '        long p2 = 0; // @step:initP2',
    '        if (remCap >= cost[i]) { // @step:checkFit',
    '            p2 = dfsMemo(i, remCap - cost[i], m, cost, val, memo) + val[i]; // @step:branch2',
    '        }',
    '        return memo[i][remCap] = Math.max(p1, p2); // @step:memoStore',
    '    }',
    '}',
  ],
  cpp: [
    '#include <iostream>',
    '#include <vector>',
    '#include <algorithm>',
    'using namespace std;',
    '',
    '// 阶段 2: 记忆化搜索完全背包 memo[i][remCap]',
    'long long dfsMemo(int i, int remCap, int m, const vector<int>& cost, const vector<int>& val, vector<vector<long long>>& memo) { // @step:callRoot',
    '    if (i >= m || remCap <= 0) return 0; // @step:fnEnter',
    '    if (memo[i][remCap] != -1) return memo[i][remCap]; // @step:baseCheck',
    '    long long p1 = dfsMemo(i + 1, remCap, m, cost, val, memo); // @step:memoCheck',
    '    long long p2 = 0; // @step:branch1',
    '    if (remCap >= cost[i]) { // @step:initP2',
    '        p2 = dfsMemo(i, remCap - cost[i], m, cost, val, memo) + val[i]; // @step:checkFit',
    '    }',
    '    return memo[i][remCap] = max(p1, p2); // @step:branch2',
    '}',
  ],
  python: [
    'def unbounded_knapsack_memo(t: int, m: int, cost: list[int], val: list[int]) -> int: // @step:callRoot',
    '    """阶段 2: 记忆化搜索完全背包"""',
    '    memo = [[-1] * (t + 1) for _ in range(m)] // @step:memoInit',
    '    def dfs(i: int, rem_cap: int) -> int: // @step:fnEnter',
    '        if i >= m or rem_cap <= 0: // @step:baseCheck',
    '            return 0',
    '        if memo[i][rem_cap] != -1: // @step:memoCheck',
    '            return memo[i][rem_cap]',
    '        p1 = dfs(i + 1, rem_cap) // @step:branch1',
    '        p2 = dfs(i, rem_cap - cost[i]) + val[i] if rem_cap >= cost[i] else 0 // @step:initP2',
    '        memo[i][rem_cap] = max(p1, p2) // @step:checkFit',
    '        return memo[i][rem_cap] // @step:branch2',
    '    return dfs(0, t) // @step:memoStore',
  ],
  javascript: [
    '// 阶段 2: 记忆化搜索完全背包',
    'export function unboundedKnapsackMemo(t, m, cost, val) { // @step:callRoot',
    '  const memo = Array.from({ length: m }, () => new Array(t + 1).fill(-1)); // @step:memoInit',
    '  function dfs(i, remCap) { // @step:fnEnter',
    '    if (i >= m || remCap <= 0) return 0; // @step:baseCheck',
    '    if (memo[i][remCap] !== -1) return memo[i][remCap]; // @step:memoCheck',
    '    const p1 = dfs(i + 1, remCap); // @step:branch1',
    '    const p2 = remCap >= cost[i] ? dfs(i, remCap - cost[i]) + val[i] : 0; // @step:initP2',
    '    return (memo[i][remCap] = Math.max(p1, p2)); // @step:checkFit',
    '  }',
    '  return dfs(0, t); // @step:branch2',
    '}',
  ],
};

const S2_01: Record<string, string[]> = {
  java: [
    'package class073;',
    '',
    'import java.util.Arrays;',
    '',
    '// 阶段 2: 01背包记忆化搜索',
    'public class Code01_01KnapsackStage2 {',
    '    public static int compute(int t, int m, int[] cost, int[] val) { // @step:callRoot',
    '        int[][] memo = new int[m][t + 1]; // @step:memoInit',
    '        for (int[] row : memo) Arrays.fill(row, -1); // @step:memoFill',
    '        return dfsMemo(0, t, m, cost, val, memo);',
    '    }',
    '    private static int dfsMemo(int i, int remCap, int m, int[] cost, int[] val, int[][] memo) { // @step:fnEnter',
    '        if (i >= m || remCap <= 0) return 0; // @step:baseCheck',
    '        if (memo[i][remCap] != -1) return memo[i][remCap]; // @step:memoCheck',
    '        int p1 = dfsMemo(i + 1, remCap, m, cost, val, memo); // @step:branch1',
    '        int p2 = 0; // @step:initP2',
    '        if (remCap >= cost[i]) { // @step:checkFit',
    '            p2 = dfsMemo(i + 1, remCap - cost[i], m, cost, val, memo) + val[i]; // @step:branch2',
    '        }',
    '        return memo[i][remCap] = Math.max(p1, p2); // @step:memoStore',
    '    }',
    '}',
  ],
  cpp: [
    '#include <iostream>',
    '#include <vector>',
    '#include <algorithm>',
    'using namespace std;',
    '',
    '// 阶段 2: 01背包记忆化搜索 memo[i][remCap]',
    'int dfsMemo(int i, int remCap, int m, const vector<int>& cost, const vector<int>& val, vector<vector<int>>& memo) { // @step:callRoot',
    '    if (i >= m || remCap <= 0) return 0; // @step:fnEnter',
    '    if (memo[i][remCap] != -1) return memo[i][remCap]; // @step:baseCheck',
    '    int p1 = dfsMemo(i + 1, remCap, m, cost, val, memo); // @step:memoCheck',
    '    int p2 = 0; // @step:branch1',
    '    if (remCap >= cost[i]) { // @step:initP2',
    '        p2 = dfsMemo(i + 1, remCap - cost[i], m, cost, val, memo) + val[i]; // @step:checkFit',
    '    }',
    '    return memo[i][remCap] = max(p1, p2); // @step:branch2',
    '}',
  ],
  python: [
    'def knapsack_01_memo(t: int, m: int, cost: list[int], val: list[int]) -> int: // @step:callRoot',
    '    """阶段 2: 01背包记忆化搜索"""',
    '    memo = [[-1] * (t + 1) for _ in range(m)] // @step:memoInit',
    '    def dfs(i: int, rem_cap: int) -> int: // @step:fnEnter',
    '        if i >= m or rem_cap <= 0: // @step:baseCheck',
    '            return 0',
    '        if memo[i][rem_cap] != -1: // @step:memoCheck',
    '            return memo[i][rem_cap]',
    '        p1 = dfs(i + 1, rem_cap) // @step:branch1',
    '        p2 = dfs(i + 1, rem_cap - cost[i]) + val[i] if rem_cap >= cost[i] else 0 // @step:initP2',
    '        memo[i][rem_cap] = max(p1, p2) // @step:checkFit',
    '        return memo[i][rem_cap] // @step:branch2',
    '    return dfs(0, t) // @step:memoStore',
  ],
  javascript: [
    '// 阶段 2: 01背包记忆化搜索',
    'export function knapsack01Memo(t, m, cost, val) { // @step:callRoot',
    '  const memo = Array.from({ length: m }, () => new Array(t + 1).fill(-1)); // @step:memoInit',
    '  function dfs(i, remCap) { // @step:fnEnter',
    '    if (i >= m || remCap <= 0) return 0; // @step:baseCheck',
    '    if (memo[i][remCap] !== -1) return memo[i][remCap]; // @step:memoCheck',
    '    const p1 = dfs(i + 1, remCap); // @step:branch1',
    '    const p2 = remCap >= cost[i] ? dfs(i + 1, remCap - cost[i]) + val[i] : 0; // @step:initP2',
    '    return (memo[i][remCap] = Math.max(p1, p2)); // @step:checkFit',
    '  }',
    '  return dfs(0, t); // @step:branch2',
    '}',
  ],
};

const S2_PARTITIONED: Record<string, string[]> = {
  java: [
    'class Solution {',
    '    // 分组背包记忆化搜索',
    '    public int solve(int[][] groups, int[] values, int[] weights, int n, int capacity) { // @step:callRoot',
    '        int[][] memo = new int[n][capacity + 1]; // @step:memoInit',
    '        for (int[] row : memo) Arrays.fill(row, -1);',
    '        return dfs(0, capacity, groups, values, weights, n, memo);',
    '    }',
    '    private int dfs(int idx, int remCap, int[][] groups, int[] values, int[] weights, int n, int[][] memo) { // @step:fnEnter',
    '        if (idx >= n || remCap <= 0) return 0; // @step:baseCheck',
    '        if (memo[idx][remCap] != -1) return memo[idx][remCap]; // @step:memoCheck',
    '        int best = dfs(idx + 1, remCap, groups, values, weights, n, memo); // @step:branch1',
    '        for (int choice : groups[idx]) { // @step:loopGroup',
    '            int itemW = weights[choice];',
    '            if (itemW <= remCap) { // @step:checkFit',
    '                int val = values[choice] + dfs(idx + 1, remCap - itemW, groups, values, weights, n, memo); // @step:branch2',
    '                best = Math.max(best, val);',
    '            }',
    '        }',
    '        memo[idx][remCap] = best; // @step:memoStore',
    '        return best;',
    '    }',
    '}',
  ],
  cpp: [
    '#include <vector>',
    '#include <algorithm>',
    'using namespace std;',
    '',
    '// 分组背包记忆化搜索',
    'class Solution {',
    'public:',
    '    int solve(vector<vector<int>>& groups, vector<int>& values, vector<int>& weights, int n, int capacity) { // @step:callRoot',
    '        vector<vector<int>> memo(n, vector<int>(capacity + 1, -1)); // @step:memoInit',
    '        return dfs(0, capacity, groups, values, weights, n, memo);',
    '    }',
    '    int dfs(int idx, int remCap, vector<vector<int>>& groups, vector<int>& values, vector<int>& weights, int n, vector<vector<int>>& memo) { // @step:fnEnter',
    '        if (idx >= n || remCap <= 0) return 0; // @step:baseCheck',
    '        if (memo[idx][remCap] != -1) return memo[idx][remCap]; // @step:memoCheck',
    '        int best = dfs(idx + 1, remCap, groups, values, weights, n, memo); // @step:branch1',
    '        for (int choice : groups[idx]) { // @step:loopGroup',
    '            int itemW = weights[choice];',
    '            if (itemW <= remCap) { // @step:checkFit',
    '                int val = values[choice] + dfs(idx + 1, remCap - itemW, groups, values, weights, n, memo); // @step:branch2',
    '                best = max(best, val);',
    '            }',
    '        }',
    '        memo[idx][remCap] = best; // @step:memoStore',
    '        return best;',
    '    }',
    '};',
  ],
  python: [
    'def solve(groups, values, weights, n, capacity): # @step:callRoot',
    '    # 分组背包记忆化搜索',
    '    memo = [[-1] * (capacity + 1) for _ in range(n)] # @step:memoInit',
    '    def dfs(idx, rem_cap): # @step:fnEnter',
    '        if idx >= n or rem_cap <= 0: # @step:baseCheck',
    '            return 0',
    '        if memo[idx][rem_cap] != -1: # @step:memoCheck',
    '            return memo[idx][rem_cap]',
    '        best = dfs(idx + 1, rem_cap) # @step:branch1',
    '        for choice in groups[idx]: # @step:loopGroup',
    '            item_w = weights[choice]',
    '            if item_w <= rem_cap: # @step:checkFit',
    '                val = values[choice] + dfs(idx + 1, rem_cap - item_w) # @step:branch2',
    '                best = max(best, val)',
    '        memo[idx][rem_cap] = best # @step:memoStore',
    '        return best',
    '    return dfs(0, capacity)',
  ],
  javascript: [
    'export function solve(groups, values, weights, n, capacity) { // @step:callRoot',
    '  // 分组背包记忆化搜索',
    '  const memo = Array.from({ length: n }, () => new Array(capacity + 1).fill(-1)); // @step:memoInit',
    '  function dfs(idx, remCap) { // @step:fnEnter',
    '    if (idx >= n || remCap <= 0) return 0; // @step:baseCheck',
    '    if (memo[idx][remCap] !== -1) return memo[idx][remCap]; // @step:memoCheck',
    '    let best = dfs(idx + 1, remCap); // @step:branch1',
    '    for (const choice of groups[idx]) { // @step:loopGroup',
    '      const itemW = weights[choice];',
    '      if (itemW <= remCap) { // @step:checkFit',
    '        const val = values[choice] + dfs(idx + 1, remCap - itemW); // @step:branch2',
    '        best = Math.max(best, val);',
    '      }',
    '    }',
    '    memo[idx][remCap] = best; // @step:memoStore',
    '    return best;',
    '  }',
    '  return dfs(0, capacity);',
    '}',
  ],
};

// ==========================================
// 3. 阶段 3: 二维动态规划递推
// ==========================================

const S3_UNBOUNDED: Record<string, string[]> = {
  java: [
    'package class074;',
    '',
    '// 阶段 3: 完全背包二维 DP',
    'public class Code03_UnboundedKnapsackStage3 {',
    '    public static long compute(int t, int m, int[] cost, int[] val) {',
    '        long[][] dp = new long[m + 1][t + 1]; // @step:initDp',
    '        for (int i = 1; i <= m; i++) { // @step:outerLoop',
    '            for (int j = 0; j <= t; j++) { // @step:capLoop',
    '                dp[i][j] = dp[i - 1][j]; // @step:inherit',
    '                if (j >= cost[i - 1]) { // @step:checkFit',
    '                    dp[i][j] = Math.max(dp[i][j], dp[i][j - cost[i - 1]] + val[i - 1]); // @step:update',
    '                }',
    '            }',
    '        }',
    '        return dp[m][t]; // @step:returnAns',
    '    }',
    '}',
  ],
  cpp: [
    '#include <iostream>',
    '#include <vector>',
    '#include <algorithm>',
    'using namespace std;',
    '',
    '// 阶段 3: 完全背包二维 DP',
    '// 每种草药可选无限次：dp[i][j] 依赖【同行左侧】dp[i][j - cost]',
    'long long compute2D(int m, int t, const vector<int>& cost, const vector<int>& val) {',
    '    vector<vector<long long>> dp(m + 1, vector<long long>(t + 1, 0)); // @step:initDp',
    '    for (int i = 1; i <= m; ++i) { // @step:outerLoop',
    '        for (int j = 0; j <= t; ++j) { // @step:capLoop',
    '            dp[i][j] = dp[i - 1][j]; // @step:inherit',
    '            if (j >= cost[i - 1]) { // @step:checkFit',
    '                dp[i][j] = max(dp[i][j], dp[i][j - cost[i - 1]] + val[i - 1]); // @step:update',
    '            }',
    '        }',
    '    }',
    '    return dp[m][t]; // @step:returnAns',
    '}',
  ],
  python: [
    'def unbounded_knapsack_2d(t: int, m: int, cost: list[int], val: list[int]) -> int:',
    '    """阶段 3: 完全背包二维 DP"""',
    '    dp = [[0] * (t + 1) for _ in range(m + 1)] // @step:initDp',
    '    for i in range(1, m + 1): // @step:outerLoop',
    '        for j in range(t + 1): // @step:capLoop',
    '            dp[i][j] = dp[i - 1][j] // @step:inherit',
    '            if j >= cost[i - 1]: // @step:checkFit',
    '                dp[i][j] = max(dp[i][j], dp[i][j - cost[i - 1]] + val[i - 1]) // @step:update',
    '    return dp[m][t] // @step:returnAns',
  ],
  javascript: [
    '// 阶段 3: 完全背包二维 DP',
    'export function computeUnbounded2D(t, m, cost, val) {',
    '  const dp = Array.from({ length: m + 1 }, () => new Array(t + 1).fill(0)); // @step:initDp',
    '  for (let i = 1; i <= m; i++) { // @step:outerLoop',
    '    for (let j = 0; j <= t; j++) { // @step:capLoop',
    '      dp[i][j] = dp[i - 1][j]; // @step:inherit',
    '      if (j >= cost[i - 1]) { // @step:checkFit',
    '        dp[i][j] = Math.max(dp[i][j], dp[i][j - cost[i - 1]] + val[i - 1]); // @step:update',
    '      }',
    '    }',
    '  }',
    '  return dp[m][t]; // @step:returnAns',
    '}',
  ],
};

const S3_01: Record<string, string[]> = {
  java: [
    'package class073;',
    '',
    '// 阶段 3: 严格二维动态规划 01背包',
    'public class Code01_01KnapsackStage3 {',
    '    public static int compute(int t, int m, int[] cost, int[] val) {',
    '        int[][] dp = new int[m + 1][t + 1]; // @step:initDp',
    '        for (int i = 1; i <= m; i++) { // @step:outerLoop',
    '            for (int j = 0; j <= t; j++) { // @step:capLoop',
    '                dp[i][j] = dp[i - 1][j]; // @step:inherit',
    '                if (j >= cost[i - 1]) { // @step:checkFit',
    '                    dp[i][j] = Math.max(dp[i][j], dp[i - 1][j - cost[i - 1]] + val[i - 1]); // @step:update',
    '                }',
    '            }',
    '        }',
    '        return dp[m][t]; // @step:returnAns',
    '    }',
    '}',
  ],
  cpp: [
    '#include <iostream>',
    '#include <vector>',
    '#include <algorithm>',
    'using namespace std;',
    '',
    '// 阶段 3: 严格二维动态规划 01背包',
    'int compute2D(int t, int m, const vector<int>& cost, const vector<int>& val) {',
    '    vector<vector<int>> dp(m + 1, vector<int>(t + 1, 0)); // @step:initDp',
    '    for (int i = 1; i <= m; ++i) { // @step:outerLoop',
    '        for (int j = 0; j <= t; ++j) { // @step:capLoop',
    '            dp[i][j] = dp[i - 1][j]; // @step:inherit',
    '            // 不选当前物品: 继承上一行同列',
    '            // 选入当前物品: 依赖【上一行】左侧 (确保物品仅被选择一次)',
    '            if (j >= cost[i - 1]) { // @step:checkFit',
    '                dp[i][j] = max(dp[i][j], dp[i - 1][j - cost[i - 1]] + val[i - 1]); // @step:update',
    '            }',
    '        }',
    '    }',
    '    return dp[m][t]; // @step:returnAns',
    '}',
  ],
  python: [
    'def knapsack_01_2d(t: int, m: int, cost: list[int], val: list[int]) -> int:',
    '    """阶段 3: 严格二维动态规划 01背包"""',
    '    dp = [[0] * (t + 1) for _ in range(m + 1)] // @step:initDp',
    '    for i in range(1, m + 1): // @step:outerLoop',
    '        for j in range(t + 1): // @step:capLoop',
    '            dp[i][j] = dp[i - 1][j] // @step:inherit',
    '            if j >= cost[i - 1]: // @step:checkFit',
    '                dp[i][j] = max(dp[i][j], dp[i - 1][j - cost[i - 1]] + val[i - 1]) // @step:update',
    '    return dp[m][t] // @step:returnAns',
  ],
  javascript: [
    '// 阶段 3: 严格二维动态规划 01背包',
    'export function compute01Knapsack2D(t, m, cost, val) {',
    '  const dp = Array.from({ length: m + 1 }, () => new Array(t + 1).fill(0)); // @step:initDp',
    '  for (let i = 1; i <= m; i++) { // @step:outerLoop',
    '    for (let j = 0; j <= t; j++) { // @step:capLoop',
    '      dp[i][j] = dp[i - 1][j]; // @step:inherit',
    '      if (j >= cost[i - 1]) { // @step:checkFit',
    '        dp[i][j] = Math.max(dp[i][j], dp[i - 1][j - cost[i - 1]] + val[i - 1]); // @step:update',
    '      }',
    '    }',
    '  }',
    '  return dp[m][t]; // @step:returnAns',
    '}',
  ],
};

const S3_PARTITIONED: Record<string, string[]> = {
  java: [
    'package class074;',
    '',
    '// 阶段 3: 分组背包二维 DP',
    'public class Code01_PartitionedKnapsackStage3 {',
    '    public static int compute(int t, int m, int[] cost, int[] val, int[] group) {',
    '        int[][] dp = new int[m + 1][t + 1]; // @step:initDp',
    '        for (int i = 1; i <= m; i++) { // @step:outerLoop',
    '            for (int j = 0; j <= t; j++) { // @step:capLoop',
    '                dp[i][j] = dp[i - 1][j]; // @step:inherit',
    '                for (int k = 0; k < m; k++) { // @step:loopGroup',
    '                    if (group[k] == i && j >= cost[k]) { // @step:checkFit',
    '                        dp[i][j] = Math.max(dp[i][j], dp[i - 1][j - cost[k]] + val[k]); // @step:update',
    '                    }',
    '                }',
    '            }',
    '        }',
    '        return dp[m][t]; // @step:returnAns',
    '    }',
    '}',
  ],
  cpp: [
    '#include <iostream>',
    '#include <vector>',
    '#include <algorithm>',
    'using namespace std;',
    '',
    '// 阶段 3: 分组背包二维 DP',
    'int compute2D(int t, int m, vector<int>& cost, vector<int>& val, vector<int>& group) {',
    '    vector<vector<int>> dp(m + 1, vector<int>(t + 1, 0)); // @step:initDp',
    '    for (int i = 1; i <= m; ++i) { // @step:outerLoop',
    '        for (int j = 0; j <= t; ++j) { // @step:capLoop',
    '            dp[i][j] = dp[i - 1][j]; // @step:inherit',
    '            for (int k = 0; k < m; ++k) { // @step:loopGroup',
    '                if (group[k] == i && j >= cost[k]) { // @step:checkFit',
    '                    dp[i][j] = max(dp[i][j], dp[i - 1][j - cost[k]] + val[k]); // @step:update',
    '                }',
    '            }',
    '        }',
    '    }',
    '    return dp[m][t]; // @step:returnAns',
    '}',
  ],
  python: [
    'def partitioned_knapsack_2d(t: int, m: int, cost: list[int], val: list[int], group: list[int]) -> int:',
    '    """阶段 3: 分组背包二维 DP"""',
    '    dp = [[0] * (t + 1) for _ in range(m + 1)] // @step:initDp',
    '    for i in range(1, m + 1): // @step:outerLoop',
    '        for j in range(t + 1): // @step:capLoop',
    '            dp[i][j] = dp[i - 1][j] // @step:inherit',
    '            for k in range(m): // @step:loopGroup',
    '                if group[k] == i and j >= cost[k]: // @step:checkFit',
    '                    dp[i][j] = max(dp[i][j], dp[i - 1][j - cost[k]] + val[k]) // @step:update',
    '    return dp[m][t] // @step:returnAns',
  ],
  javascript: [
    '// 阶段 3: 分组背包二维 DP',
    'export function computePartitioned2D(t, m, cost, val, group) {',
    '  const dp = Array.from({ length: m + 1 }, () => new Array(t + 1).fill(0)); // @step:initDp',
    '  for (let i = 1; i <= m; i++) { // @step:outerLoop',
    '    for (let j = 0; j <= t; j++) { // @step:capLoop',
    '      dp[i][j] = dp[i - 1][j]; // @step:inherit',
    '      for (let k = 0; k < m; k++) { // @step:loopGroup',
    '        if (group[k] === i && j >= cost[k]) { // @step:checkFit',
    '          dp[i][j] = Math.max(dp[i][j], dp[i - 1][j - cost[k]] + val[k]); // @step:update',
    '        }',
    '      }',
    '    }',
    '  }',
    '  return dp[m][t]; // @step:returnAns',
    '}',
  ],
};

// ==========================================
// 4. 模板注册表与自动注册
// ==========================================

const STAGE_TEMPLATES: StageCodeMap = {
  'unbounded:s1': S1_UNBOUNDED,
  '01:s1': S1_01,
  'partitioned:s1': S1_PARTITIONED,
  'unbounded:s2': S2_UNBOUNDED,
  '01:s2': S2_01,
  'partitioned:s2': S2_PARTITIONED,
  'unbounded:s3': S3_UNBOUNDED,
  '01:s3': S3_01,
  'partitioned:s3': S3_PARTITIONED,
};

const registry = createStageCodeRegistry<KnapsackKind>('knapsack', STAGE_TEMPLATES);
registry.register();

export const registerKnapsackTemplates = registry.register;

/**
 * 查询背包算法某阶段某 kind 的 anchor 在 4 语言中的物理行号
 * 替代原有的 STAGE1_LINE_MAPS[kind][action] 手动常量查找
 */
export const getKnapsackAnchor: (
  stage: number,
  kind: KnapsackKind,
  anchor: string,
) => ResolvedAnchorTarget = registry.getAnchor;
