/**
 * 字符串 DP 四阶段演化多语言代码模板库 (String DP Stage Code Templates)
 *
 * 使用 @step:anchor 语义锚点标注，由 CodeStepIndexer 在编译期自动
 * 解析为 Java / C++ / Python / JavaScript 四语种 1-based 物理行号。
 * 彻底消除 string-dp-stage-evolution.ts 中 ~95 行手动行号常量。
 */

import { createStageCodeRegistry, type StageCodeMap } from '../stage-code-registry';
import type { HighlightTarget } from './dark-code-terminal-presenter';
import type { StringDpKind } from './string-dp-stage-evolution';

// ==========================================
// 1. 正则表达式匹配 (Regex Matching)
// ==========================================

const REGEX_S1: Record<string, string[]> = {
  java: [
    '// 阶段 1: 暴力递归',
    'public static boolean isMatch(String s, String p) {',
    '    return dfs(s.toCharArray(), p.toCharArray(), 0, 0); // @step:callRoot',
    '}',
    'private static boolean dfs(char[] s, char[] p, int i, int j) { // @step:fnEnter',
    '    if (j == p.length) return i == s.length; // @step:baseCheck',
    '    boolean first = i < s.length && (s[i] == p[j] || p[j] == \'.\'); // @step:firstMatch',
    '    if (j + 1 < p.length && p[j + 1] == \'*\') { // @step:starCheck',
    '        return dfs(s, p, i, j + 2) // @step:starBranch0',
    '            || (first && dfs(s, p, i + 1, j)); // @step:starBranch1',
    '    }',
    '    return first && dfs(s, p, i + 1, j + 1); // @step:charBranch',
    '}',
  ],
  cpp: [
    '// 阶段 1: 暴力递归',
    'bool isMatch(string s, string p) {',
    '    return dfs(s, p, 0, 0); // @step:callRoot',
    '}',
    'bool dfs(const string& s, const string& p, int i, int j) { // @step:fnEnter',
    '    if (j == p.length()) return i == s.length(); // @step:baseCheck',
    '    bool first = i < s.length() && (s[i] == p[j] || p[j] == \'.\'); // @step:firstMatch',
    '    if (j + 1 < p.length() && p[j + 1] == \'*\') { // @step:starCheck',
    '        return dfs(s, p, i, j + 2) // @step:starBranch0',
    '            || (first && dfs(s, p, i + 1, j)); // @step:starBranch1',
    '    }',
    '    return first && dfs(s, p, i + 1, j + 1); // @step:charBranch',
    '}',
  ],
  python: [
    '# 阶段 1: 暴力递归',
    'def is_match_stage1(s: str, p: str) -> bool:',
    '    return dfs(s, p, 0, 0) # @step:callRoot',
    '# end is_match',
    'def dfs(s: str, p: str, i: int, j: int) -> bool: # @step:fnEnter',
    '    if j == len(p): return i == len(s) # @step:baseCheck',
    '    first = i < len(s) and (s[i] == p[j] or p[j] == ".") # @step:firstMatch',
    '    if j + 1 < len(p) and p[j + 1] == "*": # @step:starCheck',
    '        return dfs(s, p, i, j + 2) \\ # @step:starBranch0',
    '            or (first and dfs(s, p, i + 1, j)) # @step:starBranch1',
    '    # end if',
    '    return first and dfs(s, p, i + 1, j + 1) # @step:charBranch',
    '# end dfs',
  ],
  javascript: [
    '// 阶段 1: 暴力递归',
    'export function isMatchStage1(s, p) {',
    '  return dfs(s, p, 0, 0); // @step:callRoot',
    '}',
    'function dfs(s, p, i, j) { // @step:fnEnter',
    '  if (j === p.length) return i === s.length; // @step:baseCheck',
    '  const first = i < s.length && (s[i] === p[j] || p[j] === "."); // @step:firstMatch',
    '  if (j + 1 < p.length && p[j + 1] === "*") { // @step:starCheck',
    '    return dfs(s, p, i, j + 2) // @step:starBranch0',
    '        || (first && dfs(s, p, i + 1, j)); // @step:starBranch1',
    '  }',
    '  return first && dfs(s, p, i + 1, j + 1); // @step:charBranch',
    '}',
  ],
};

const REGEX_S2: Record<string, string[]> = {
  java: [
    'package class074;',
    '',
    '// 阶段 2: 记忆化搜索',
    'public class Code04_RegexStage2 {',
    '    public static boolean isMatch(String str, String pat) {',
    '        char[] s = str.toCharArray();',
    '        char[] p = pat.toCharArray();',
    '        int[][] memo = new int[s.length + 1][p.length + 1]; // @step:memoInit',
    '        return dfsMemo(s, p, 0, 0, memo); // @step:callRoot',
    '    }',
    '',
    '    public static boolean dfsMemo(char[] s, char[] p, int i, int j, int[][] memo) { // @step:fnEnter',
    '        if (memo[i][j] != 0) return memo[i][j] == 2; // @step:memoCheck',
    '        if (j == p.length) { // @step:baseCheck',
    '            memo[i][j] = (i == s.length) ? 2 : 1;',
    '            return memo[i][j] == 2;',
    '        }',
    '        boolean first = i < s.length && (s[i] == p[j] || p[j] == \'.\');',
    '        boolean ans;',
    '        if (j + 1 < p.length && p[j + 1] == \'*\') { // @step:starCheck',
    '            ans = dfsMemo(s, p, i, j + 2, memo) || (first && dfsMemo(s, p, i + 1, j, memo));',
    '        } else {',
    '            ans = first && dfsMemo(s, p, i + 1, j + 1, memo);',
    '        }',
    '        memo[i][j] = ans ? 2 : 1; // @step:memoStore',
    '        return ans;',
    '    }',
    '}',
  ],
  cpp: [
    '#include <string>',
    '#include <vector>',
    'using namespace std;',
    '',
    '// 阶段 2: 记忆化搜索 memo[i][j]',
    'bool dfsMemo(const string& s, const string& p, int i, int j, vector<vector<int>>& memo) { // @step:fnEnter',
    '    if (memo[i][j] != -1) return memo[i][j] == 1; // @step:memoCheck',
    '    if (j == p.length()) { // @step:baseCheck',
    '        memo[i][j] = (i == s.length()) ? 1 : 0;',
    '        return memo[i][j] == 1;',
    '    }',
    '    bool first = i < s.length() && (s[i] == p[j] || p[j] == \'.\');',
    '    bool ans;',
    '    if (j + 1 < p.length() && p[j + 1] == \'*\') { // @step:starCheck',
    '        ans = dfsMemo(s, p, i, j + 2, memo) || (first && dfsMemo(s, p, i + 1, j, memo));',
    '    } else {',
    '        ans = first && dfsMemo(s, p, i + 1, j + 1, memo);',
    '    }',
    '    memo[i][j] = ans ? 1 : 0; // @step:memoStore',
    '    return ans;',
    '}',
  ],
  python: [
    'def is_match_stage2(s: str, p: str) -> bool:',
    '    """阶段 2: 记忆化搜索"""',
    '    memo = [[-1] * (len(p) + 1) for _ in range(len(s) + 1)] # @step:memoInit',
    '    def dfs(i: int, j: int) -> bool: # @step:fnEnter',
    '        if memo[i][j] != -1: # @step:memoCheck',
    '            return memo[i][j] == 1',
    '        if j == len(p): # @step:baseCheck',
    '            memo[i][j] = 1 if i == len(s) else 0',
    '            return memo[i][j] == 1',
    '        first = i < len(s) and (s[i] == p[j] or p[j] == ".")',
    '        if j + 1 < len(p) and p[j + 1] == "*": # @step:starCheck',
    '            ans = dfs(i, j + 2) or (first and dfs(i + 1, j))',
    '        else:',
    '            ans = first and dfs(i + 1, j + 1)',
    '        memo[i][j] = 1 if ans else 0 # @step:memoStore',
    '        return ans',
    '    return dfs(0, 0) # @step:callRoot',
  ],
  javascript: [
    '// 阶段 2: 记忆化搜索',
    'export function isMatchStage2(s, p) {',
    '  const memo = Array.from({ length: s.length + 1 }, () => new Array(p.length + 1).fill(-1)); // @step:memoInit',
    '  function dfs(i, j) { // @step:fnEnter',
    '    if (memo[i][j] !== -1) return memo[i][j] === 1; // @step:memoCheck',
    '    if (j === p.length) { // @step:baseCheck',
    '      memo[i][j] = i === s.length ? 1 : 0;',
    '      return memo[i][j] === 1;',
    '    }',
    '    const first = i < s.length && (s[i] === p[j] || p[j] === ".");',
    '    let ans = false;',
    '    if (j + 1 < p.length && p[j + 1] === "*") { // @step:starCheck',
    '      ans = dfs(i, j + 2) || (first && dfs(i + 1, j));',
    '    } else {',
    '      ans = first && dfs(i + 1, j + 1);',
    '    }',
    '    memo[i][j] = ans ? 1 : 0; // @step:memoStore',
    '    return ans;',
    '  }',
    '  return dfs(0, 0); // @step:callRoot',
    '}',
  ],
};

const REGEX_S3: Record<string, string[]> = {
  java: [
    'package class074;',
    '',
    '// 阶段 3: 严格位置依赖二维 DP',
    'public class Code04_RegexStage3 {',
    '    public static boolean isMatch(String str, String pat) {',
    '        char[] s = str.toCharArray();',
    '        char[] p = pat.toCharArray();',
    '        int n = s.length, m = p.length;',
    '        boolean[][] dp = new boolean[n + 1][m + 1]; // @step:initDp',
    '        dp[n][m] = true; // @step:baseEmpty',
    '        for (int j = m - 1; j >= 0; j--) { // @step:baseStarLoop',
    '            dp[n][j] = j + 1 < m && p[j + 1] == \'*\' && dp[n][j + 2]; // @step:baseStarSet',
    '        }',
    '        for (int i = n - 1; i >= 0; i--) { // @step:outerLoop',
    '            for (int j = m - 1; j >= 0; j--) { // @step:innerLoop',
    '                if (j + 1 == m || p[j + 1] != \'*\') {',
    '                    dp[i][j] = (s[i] == p[j] || p[j] == \'.\') && dp[i + 1][j + 1]; // @step:charTransition',
    '                } else {',
    '                    dp[i][j] = dp[i][j + 2] || ((s[i] == p[j] || p[j] == \'.\') && dp[i + 1][j]); // @step:starTransition',
    '                }',
    '            }',
    '        }',
    '        return dp[0][0]; // @step:returnAns',
    '    }',
    '}',
  ],
  cpp: [
    '#include <string>',
    '#include <vector>',
    'using namespace std;',
    '',
    '// 阶段 3: 严格位置依赖二维 DP',
    'bool isMatch2D(string s, string p) {',
    '    int n = s.length(), m = p.length();',
    '    vector<vector<bool>> dp(n + 1, vector<bool>(m + 1, false)); // @step:initDp',
    '    dp[n][m] = true; // @step:baseEmpty',
    '    for (int j = m - 1; j >= 0; --j) { // @step:baseStarLoop',
    '        dp[n][j] = j + 1 < m && p[j + 1] == \'*\' && dp[n][j + 2]; // @step:baseStarSet',
    '    }',
    '    for (int i = n - 1; i >= 0; --i) { // @step:outerLoop',
    '        for (int j = m - 1; j >= 0; --j) { // @step:innerLoop',
    '            if (j + 1 == m || p[j + 1] != \'*\') {',
    '                dp[i][j] = (s[i] == p[j] || p[j] == \'.\') && dp[i + 1][j + 1]; // @step:charTransition',
    '            } else {',
    '                dp[i][j] = dp[i][j + 2] || ((s[i] == p[j] || p[j] == \'.\') && dp[i + 1][j]); // @step:starTransition',
    '            }',
    '        }',
    '    }',
    '    return dp[0][0]; // @step:returnAns',
    '}',
  ],
  python: [
    'def is_match_stage3(s: str, p: str) -> bool:',
    '    """阶段 3: 严格二维动态规划"""',
    '    n, m = len(s), len(p)',
    '    dp = [[False] * (m + 1) for _ in range(n + 1)] # @step:initDp',
    '    dp[n][m] = True # @step:baseEmpty',
    '    for j in range(m - 1, -1, -1): # @step:baseStarLoop',
    '        dp[n][j] = j + 1 < m and p[j + 1] == "*" and dp[n][j + 2] # @step:baseStarSet',
    '    for i in range(n - 1, -1, -1): # @step:outerLoop',
    '        for j in range(m - 1, -1, -1): # @step:innerLoop',
    '            if j + 1 == m or p[j + 1] != "*":',
    '                dp[i][j] = (s[i] == p[j] or p[j] == ".") and dp[i + 1][j + 1] # @step:charTransition',
    '            else:',
    '                dp[i][j] = dp[i][j + 2] or ((s[i] == p[j] or p[j] == ".") and dp[i + 1][j]) # @step:starTransition',
    '    return dp[0][0] # @step:returnAns',
  ],
  javascript: [
    '// 阶段 3: 严格位置依赖二维 DP',
    'export function isMatchStage3(s, p) {',
    '  const n = s.length, m = p.length;',
    '  const dp = Array.from({ length: n + 1 }, () => new Array(m + 1).fill(false)); // @step:initDp',
    '  dp[n][m] = true; // @step:baseEmpty',
    '  for (let j = m - 1; j >= 0; j--) { // @step:baseStarLoop',
    '    dp[n][j] = j + 1 < m && p[j + 1] === "*" && dp[n][j + 2]; // @step:baseStarSet',
    '  }',
    '  for (let i = n - 1; i >= 0; i--) { // @step:outerLoop',
    '    for (let j = m - 1; j >= 0; j--) { // @step:innerLoop',
    '      if (j + 1 === m || p[j + 1] !== "*") {',
    '        dp[i][j] = (s[i] === p[j] || p[j] === ".") && dp[i + 1][j + 1]; // @step:charTransition',
    '      } else {',
    '        dp[i][j] = dp[i][j + 2] || ((s[i] === p[j] || p[j] === ".") && dp[i + 1][j]); // @step:starTransition',
    '      }',
    '    }',
    '  }',
    '  return dp[0][0]; // @step:returnAns',
    '}',
  ],
};

// ==========================================
// 2. 通配符匹配 (Wildcard Matching)
// ==========================================

const WILDCARD_S1: Record<string, string[]> = {
  java: [
    '// 阶段 1: 暴力递归',
    'public static boolean isMatch(String str, String pat) {',
    '    return dfs(str.toCharArray(), pat.toCharArray(), 0, 0); // @step:callRoot',
    '}',
    'public static boolean dfs(char[] s, char[] p, int i, int j) { // @step:fnEnter',
    '    if (j == p.length) return i == s.length; // @step:baseCheck',
    '    if (p[j] == \'*\') { // @step:starCheck',
    '        return dfs(s, p, i, j + 1) // @step:starBranch0',
    '            || (i < s.length && dfs(s, p, i + 1, j)); // @step:starBranch1',
    '    }',
    '    boolean match = i < s.length && (s[i] == p[j] || p[j] == \'?\'); // @step:charBranch',
    '    return match && dfs(s, p, i + 1, j + 1); // @step:returnResult',
    '}',
  ],
  cpp: [
    '// 阶段 1: 暴力递归',
    'bool isMatch(string s, string p) {',
    '    return dfs(s, p, 0, 0); // @step:callRoot',
    '}',
    'bool dfs(const string& s, const string& p, int i, int j) { // @step:fnEnter',
    '    if (j == p.length()) return i == s.length(); // @step:baseCheck',
    '    if (p[j] == \'*\') { // @step:starCheck',
    '        return dfs(s, p, i, j + 1) // @step:starBranch0',
    '            || (i < s.length() && dfs(s, p, i + 1, j)); // @step:starBranch1',
    '    }',
    '    bool match = i < s.length() && (s[i] == p[j] || p[j] == \'?\'); // @step:charBranch',
    '    return match && dfs(s, p, i + 1, j + 1); // @step:returnResult',
    '}',
  ],
  python: [
    '# 阶段 1: 暴力递归',
    'def is_match_stage1(s: str, p: str) -> bool:',
    '    return dfs(s, p, 0, 0) # @step:callRoot',
    '# end is_match',
    'def dfs(s: str, p: str, i: int, j: int) -> bool: # @step:fnEnter',
    '    if j == len(p): return i == len(s) # @step:baseCheck',
    '    if p[j] == "*": # @step:starCheck',
    '        return dfs(s, p, i, j + 1) \\ # @step:starBranch0',
    '            or (i < len(s) and dfs(s, p, i + 1, j)) # @step:starBranch1',
    '    # end if',
    '    match = i < len(s) and (s[i] == p[j] or p[j] == "?") # @step:charBranch',
    '    return match and dfs(s, p, i + 1, j + 1) # @step:returnResult',
    '# end dfs',
  ],
  javascript: [
    '// 阶段 1: 暴力递归',
    'export function isMatchStage1(s, p) {',
    '  return dfs(s, p, 0, 0); // @step:callRoot',
    '}',
    'function dfs(s, p, i, j) { // @step:fnEnter',
    '  if (j === p.length) return i === s.length; // @step:baseCheck',
    '  if (p[j] === "*") { // @step:starCheck',
    '    return dfs(s, p, i, j + 1) // @step:starBranch0',
    '        || (i < s.length && dfs(s, p, i + 1, j)); // @step:starBranch1',
    '  }',
    '  const match = i < s.length && (s[i] === p[j] || p[j] === "?"); // @step:charBranch',
    '  return match && dfs(s, p, i + 1, j + 1); // @step:returnResult',
    '}',
  ],
};

const WILDCARD_S2: Record<string, string[]> = {
  cpp: [
    '#include <string>',
    '#include <vector>',
    'using namespace std;',
    '',
    '// 阶段 2: 记忆化搜索 memo[i][j]',
    'bool dfsMemo(const string& s, const string& p, int i, int j, vector<vector<int>>& memo) { // @step:fnEnter',
    '    if (memo[i][j] != -1) return memo[i][j] == 1; // @step:memoCheck',
    '    if (j == p.length()) { // @step:baseCheck',
    '        memo[i][j] = (i == s.length()) ? 1 : 0;',
    '        return memo[i][j] == 1;',
    '    }',
    '    bool ans = false;',
    '    if (p[j] == \'*\') { // @step:starCheck',
    '        ans = dfsMemo(s, p, i, j + 1, memo) || (i < s.length() && dfsMemo(s, p, i + 1, j, memo));',
    '    } else {',
    '        bool match = i < s.length() && (s[i] == p[j] || p[j] == \'?\');',
    '        ans = match && dfsMemo(s, p, i + 1, j + 1, memo);',
    '    }',
    '    memo[i][j] = ans ? 1 : 0; // @step:memoStore',
    '    return ans;',
    '}',
  ],
  java: [
    'package class074;',
    '',
    '// 阶段 2: 记忆化搜索',
    'public class Code05_WildcardStage2 {',
    '    public static boolean isMatch(String str, String pat) {',
    '        char[] s = str.toCharArray();',
    '        char[] p = pat.toCharArray();',
    '        int[][] memo = new int[s.length + 1][p.length + 1]; // @step:memoInit',
    '        return dfsMemo(s, p, 0, 0, memo); // @step:callRoot',
    '    }',
    '',
    '    public static boolean dfsMemo(char[] s, char[] p, int i, int j, int[][] memo) { // @step:fnEnter',
    '        if (memo[i][j] != 0) return memo[i][j] == 2; // @step:memoCheck',
    '        if (j == p.length) { // @step:baseCheck',
    '            memo[i][j] = (i == s.length) ? 2 : 1;',
    '            return memo[i][j] == 2;',
    '        }',
    '        boolean ans = false;',
    '        if (p[j] == \'*\') { // @step:starCheck',
    '            ans = dfsMemo(s, p, i, j + 1, memo) || (i < s.length && dfsMemo(s, p, i + 1, j, memo));',
    '        } else {',
    '            boolean match = i < s.length && (s[i] == p[j] || p[j] == \'?\');',
    '            ans = match && dfsMemo(s, p, i + 1, j + 1, memo);',
    '        }',
    '        memo[i][j] = ans ? 2 : 1; // @step:memoStore',
    '        return ans;',
    '    }',
    '}',
  ],
  python: [
    'def is_match_stage2(s: str, p: str) -> bool:',
    '    """阶段 2: 记忆化搜索"""',
    '    memo = [[-1] * (len(p) + 1) for _ in range(len(s) + 1)] # @step:memoInit',
    '    def dfs(i: int, j: int) -> bool: # @step:fnEnter',
    '        if memo[i][j] != -1: # @step:memoCheck',
    '            return memo[i][j] == 1',
    '        if j == len(p): # @step:baseCheck',
    '            memo[i][j] = 1 if i == len(s) else 0',
    '            return memo[i][j] == 1',
    '        if p[j] == "*": # @step:starCheck',
    '            ans = dfs(i, j + 1) or (i < len(s) and dfs(i + 1, j))',
    '        else:',
    '            match = i < len(s) and (s[i] == p[j] or p[j] == "?")',
    '            ans = match and dfs(i + 1, j + 1)',
    '        memo[i][j] = 1 if ans else 0 # @step:memoStore',
    '        return ans',
    '    return dfs(0, 0) # @step:callRoot',
  ],
  javascript: [
    '// 阶段 2: 记忆化搜索',
    'export function isMatchStage2(s, p) {',
    '  const memo = Array.from({ length: s.length + 1 }, () => new Array(p.length + 1).fill(-1)); // @step:memoInit',
    '  function dfs(i, j) { // @step:fnEnter',
    '    if (memo[i][j] !== -1) return memo[i][j] === 1; // @step:memoCheck',
    '    if (j === p.length) { // @step:baseCheck',
    '      memo[i][j] = i === s.length ? 1 : 0;',
    '      return memo[i][j] === 1;',
    '    }',
    '    let ans = false;',
    '    if (p[j] === "*") { // @step:starCheck',
    '      ans = dfs(i, j + 1) || (i < s.length && dfs(i + 1, j));',
    '    } else {',
    '      const match = i < s.length && (s[i] === p[j] || p[j] === "?");',
    '      ans = match && dfs(i + 1, j + 1);',
    '    }',
    '    memo[i][j] = ans ? 1 : 0; // @step:memoStore',
    '    return ans;',
    '  }',
    '  return dfs(0, 0); // @step:callRoot',
    '}',
  ],
};

const WILDCARD_S3: Record<string, string[]> = {
  cpp: [
    '#include <string>',
    '#include <vector>',
    'using namespace std;',
    '',
    '// 阶段 3: 严格位置依赖二维 DP',
    'bool isMatch2D(string s, string p) {',
    '    int n = s.length(), m = p.length();',
    '    vector<vector<bool>> dp(n + 1, vector<bool>(m + 1, false)); // @step:initDp',
    '    dp[n][m] = true; // @step:baseEmpty',
    '    for (int j = m - 1; j >= 0 && p[j] == \'*\'; --j) dp[n][j] = true; // @step:baseStarLoop',
    '    for (int i = n - 1; i >= 0; --i) { // @step:outerLoop',
    '        for (int j = m - 1; j >= 0; --j) { // @step:innerLoop',
    '            if (p[j] != \'*\') {',
    '                dp[i][j] = (s[i] == p[j] || p[j] == \'?\') && dp[i + 1][j + 1]; // @step:charTransition',
    '            } else {',
    '                dp[i][j] = dp[i + 1][j] || dp[i][j + 1]; // @step:starTransition',
    '            }',
    '        }',
    '    }',
    '    return dp[0][0]; // @step:returnAns',
    '}',
  ],
  java: [
    'package class074;',
    '',
    '// 阶段 3: 严格位置依赖二维 DP',
    'public class Code05_WildcardStage3 {',
    '    public static boolean isMatch(String str, String pat) {',
    '        char[] s = str.toCharArray();',
    '        char[] p = pat.toCharArray();',
    '        int n = s.length, m = p.length;',
    '        boolean[][] dp = new boolean[n + 1][m + 1]; // @step:initDp',
    '        dp[n][m] = true; // @step:baseEmpty',
    '        for (int j = m - 1; j >= 0 && p[j] == \'*\'; j--) { // @step:baseStarLoop',
    '            dp[n][j] = true;',
    '        }',
    '        for (int i = n - 1; i >= 0; i--) { // @step:outerLoop',
    '            for (int j = m - 1; j >= 0; j--) { // @step:innerLoop',
    '                if (p[j] != \'*\') {',
    '                    dp[i][j] = (s[i] == p[j] || p[j] == \'?\') && dp[i + 1][j + 1]; // @step:charTransition',
    '                } else {',
    '                    dp[i][j] = dp[i + 1][j] || dp[i][j + 1]; // @step:starTransition',
    '                }',
    '            }',
    '        }',
    '        return dp[0][0]; // @step:returnAns',
    '    }',
    '}',
  ],
  python: [
    'def is_match_wildcard_stage3(s: str, p: str) -> bool:',
    '    """阶段 3: 严格二维动态规划"""',
    '    n, m = len(s), len(p)',
    '    dp = [[False] * (m + 1) for _ in range(n + 1)] # @step:initDp',
    '    dp[n][m] = True # @step:baseEmpty',
    '    j = m - 1',
    '    while j >= 0 and p[j] == "*": dp[n][j] = True; j -= 1 # @step:baseStarLoop',
    '    for i in range(n - 1, -1, -1): # @step:outerLoop',
    '        for j in range(m - 1, -1, -1): # @step:innerLoop',
    '            if p[j] != "*":',
    '                dp[i][j] = (s[i] == p[j] or p[j] == "?") and dp[i + 1][j + 1] # @step:charTransition',
    '            else:',
    '                dp[i][j] = dp[i + 1][j] or dp[i][j + 1] # @step:starTransition',
    '    return dp[0][0] # @step:returnAns',
  ],
  javascript: [
    '// 阶段 3: 严格位置依赖二维 DP',
    'export function isMatchWildcardStage3(s, p) {',
    '  const n = s.length, m = p.length;',
    '  const dp = Array.from({ length: n + 1 }, () => new Array(m + 1).fill(false)); // @step:initDp',
    '  dp[n][m] = true; // @step:baseEmpty',
    '  for (let j = m - 1; j >= 0 && p[j] === "*"; j--) dp[n][j] = true; // @step:baseStarLoop',
    '  for (let i = n - 1; i >= 0; i--) { // @step:outerLoop',
    '    for (let j = m - 1; j >= 0; j--) { // @step:innerLoop',
    '      if (p[j] !== "*") {',
    '        dp[i][j] = (s[i] === p[j] || p[j] === "?") && dp[i + 1][j + 1]; // @step:charTransition',
    '      } else {',
    '        dp[i][j] = dp[i + 1][j] || dp[i][j + 1]; // @step:starTransition',
    '      }',
    '    }',
    '  }',
    '  return dp[0][0]; // @step:returnAns',
    '}',
  ],
};

// ==========================================
// 3. 模板注册与锚点查询
// ==========================================

const STAGE_TEMPLATES: StageCodeMap = {
  'regex:s1': REGEX_S1,
  'regex:s2': REGEX_S2,
  'regex:s3': REGEX_S3,
  'wildcard:s1': WILDCARD_S1,
  'wildcard:s2': WILDCARD_S2,
  'wildcard:s3': WILDCARD_S3,
};

const registry = createStageCodeRegistry<StringDpKind>('string-dp', STAGE_TEMPLATES);
registry.register();

export const registerStringDpTemplates = registry.register;
export const getStringDpAnchor: (
  stage: number,
  kind: StringDpKind,
  anchor: string,
) => HighlightTarget = registry.getAnchor;
