/**
 * 左程云算法通关课 Class 036 与 Class 037 二叉树高频题目专题
 * 四语言权威解法与精准 1-Based 代码行号映射
 */

// ----------------------------------------------------
// 1. Level Order (Class 036 Code01)
// ----------------------------------------------------
export const LEVEL_ORDER_036_CODES = {
  java: [
    'public List<List<Integer>> levelOrder(TreeNode root) {',
    '    List<List<Integer>> ans = new ArrayList<>();',
    '    if (root == null) return ans;',
    '    Queue<TreeNode> queue = new LinkedList<>();',
    '    queue.offer(root);',
    '    while (!queue.isEmpty()) {',
    '        int size = queue.size();',
    '        List<Integer> level = new ArrayList<>();',
    '        for (int i = 0; i < size; i++) {',
    '            TreeNode cur = queue.poll();',
    '            level.add(cur.val);',
    '            if (cur.left != null) queue.offer(cur.left);',
    '            if (cur.right != null) queue.offer(cur.right);',
    '        }',
    '        ans.add(level);',
    '    }',
    '    return ans;',
    '}',
  ],
  cpp: [
    'vector<vector<int>> levelOrder(TreeNode* root) {',
    '    vector<vector<int>> ans;',
    '    if (!root) return ans;',
    '    queue<TreeNode*> q;',
    '    q.push(root);',
    '    while (!q.empty()) {',
    '        int sz = q.size();',
    '        vector<int> level;',
    '        for (int i = 0; i < sz; ++i) {',
    '            auto cur = q.front(); q.pop();',
    '            level.push_back(cur->val);',
    '            if (cur->left) q.push(cur->left);',
    '            if (cur->right) q.push(cur->right);',
    '        }',
    '        ans.push_back(level);',
    '    }',
    '    return ans;',
    '}',
  ],
  python: [
    'def levelOrder(root: Optional[TreeNode]) -> List[List[int]]:',
    '    if not root: return []',
    '    ans, q = [], collections.deque([root])',
    '    while q:',
    '        level = []',
    '        for _ in range(len(q)):',
    '            node = q.popleft()',
    '            level.append(node.val)',
    '            if node.left: q.append(node.left)',
    '            if node.right: q.append(node.right)',
    '        ans.append(level)',
    '    return ans',
  ],
  javascript: [
    'function levelOrder(root) {',
    '    if (!root) return [];',
    '    const ans = [], q = [root];',
    '    while (q.length > 0) {',
    '        const size = q.length, level = [];',
    '        for (let i = 0; i < size; i++) {',
    '            const cur = q.shift();',
    '            level.push(cur.val);',
    '            if (cur.left) q.push(cur.left);',
    '            if (cur.right) q.push(cur.right);',
    '        }',
    '        ans.push(level);',
    '    }',
    '    return ans;',
    '}',
  ],
};

export const LEVEL_ORDER_036_LINES = {
  entry: { java: 1, cpp: 1, python: 1, javascript: 1 },
  initQueue: { java: 4, cpp: 4, python: 3, javascript: 3 },
  loopLevel: { java: 6, cpp: 6, python: 4, javascript: 4 },
  pollNode: { java: 10, cpp: 10, python: 7, javascript: 7 },
  enqueueChildren: { java: 12, cpp: 12, python: 9, javascript: 9 },
  finishLevel: { java: 15, cpp: 15, python: 11, javascript: 12 },
  returnAns: { java: 17, cpp: 17, python: 12, javascript: 14 },
};

// ----------------------------------------------------
// 2. Zigzag Level Order (Class 036 Code02)
// ----------------------------------------------------
export const ZIGZAG_036_CODES = {
  java: [
    'public List<List<Integer>> zigzagLevelOrder(TreeNode root) {',
    '    List<List<Integer>> ans = new ArrayList<>();',
    '    if (root == null) return ans;',
    '    Queue<TreeNode> queue = new LinkedList<>();',
    '    queue.offer(root);',
    '    boolean isReverse = false;',
    '    while (!queue.isEmpty()) {',
    '        int size = queue.size();',
    '        LinkedList<Integer> level = new LinkedList<>();',
    '        for (int i = 0; i < size; i++) {',
    '            TreeNode cur = queue.poll();',
    '            if (!isReverse) level.addLast(cur.val);',
    '            else level.addFirst(cur.val);',
    '            if (cur.left != null) queue.offer(cur.left);',
    '            if (cur.right != null) queue.offer(cur.right);',
    '        }',
    '        ans.add(level);',
    '        isReverse = !isReverse;',
    '    }',
    '    return ans;',
    '}',
  ],
  cpp: [
    'vector<vector<int>> zigzagLevelOrder(TreeNode* root) {',
    '    vector<vector<int>> ans;',
    '    if (!root) return ans;',
    '    queue<TreeNode*> q;',
    '    q.push(root);',
    '    bool isReverse = false;',
    '    while (!q.empty()) {',
    '        int sz = q.size();',
    '        deque<int> level;',
    '        for (int i = 0; i < sz; ++i) {',
    '            auto cur = q.front(); q.pop();',
    '            if (!isReverse) level.push_back(cur->val);',
    '            else level.push_front(cur->val);',
    '            if (cur->left) q.push(cur->left);',
    '            if (cur->right) q.push(cur->right);',
    '        }',
    '        ans.push_back(vector<int>(level.begin(), level.end()));',
    '        isReverse = !isReverse;',
    '    }',
    '    return ans;',
    '}',
  ],
  python: [
    'def zigzagLevelOrder(root: Optional[TreeNode]) -> List[List[int]]:',
    '    if not root: return []',
    '    ans, q, is_rev = [], collections.deque([root]), False',
    '    while q:',
    '        level = collections.deque()',
    '        for _ in range(len(q)):',
    '            node = q.popleft()',
    '            if not is_rev: level.append(node.val)',
    '            else: level.appendleft(node.val)',
    '            if node.left: q.append(node.left)',
    '            if node.right: q.append(node.right)',
    '        ans.append(list(level))',
    '        is_rev = not is_rev',
    '    return ans',
  ],
  javascript: [
    'function zigzagLevelOrder(root) {',
    '    if (!root) return [];',
    '    const ans = [], q = [root];',
    '    let isReverse = false;',
    '    while (q.length > 0) {',
    '        const size = q.length, level = [];',
    '        for (let i = 0; i < size; i++) {',
    '            const cur = q.shift();',
    '            if (!isReverse) level.push(cur.val);',
    '            else level.unshift(cur.val);',
    '            if (cur.left) q.push(cur.left);',
    '            if (cur.right) q.push(cur.right);',
    '        }',
    '        ans.push(level);',
    '        isReverse = !isReverse;',
    '    }',
    '    return ans;',
    '}',
  ],
};

export const ZIGZAG_036_LINES = {
  entry: { java: 1, cpp: 1, python: 1, javascript: 1 },
  initReverse: { java: 6, cpp: 6, python: 3, javascript: 4 },
  loopLevel: { java: 7, cpp: 7, python: 4, javascript: 5 },
  zigzagCollect: { java: 12, cpp: 12, python: 8, javascript: 9 },
  reverseToggle: { java: 18, cpp: 18, python: 13, javascript: 15 },
  returnAns: { java: 20, cpp: 20, python: 14, javascript: 17 },
};

// ----------------------------------------------------
// 3. Width of Binary Tree (Class 036 Code03)
// ----------------------------------------------------
export const WIDTH_036_CODES = {
  java: [
    'public int widthOfBinaryTree(TreeNode root) {',
    '    if (root == null) return 0;',
    '    int maxWidth = 0;',
    '    Queue<Pair<TreeNode, Integer>> queue = new LinkedList<>();',
    '    queue.offer(new Pair<>(root, 1));',
    '    while (!queue.isEmpty()) {',
    '        int size = queue.size();',
    '        int base = queue.peek().getValue();',
    '        int left = 0, right = 0;',
    '        for (int i = 0; i < size; i++) {',
    '            Pair<TreeNode, Integer> pair = queue.poll();',
    '            TreeNode node = pair.getKey();',
    '            int idx = pair.getValue() - base;',
    '            if (i == 0) left = idx;',
    '            if (i == size - 1) right = idx;',
    '            if (node.left != null) queue.offer(new Pair<>(node.left, idx * 2));',
    '            if (node.right != null) queue.offer(new Pair<>(node.right, idx * 2 + 1));',
    '        }',
    '        maxWidth = Math.max(maxWidth, right - left + 1);',
    '    }',
    '    return maxWidth;',
    '}',
  ],
  cpp: [
    'int widthOfBinaryTree(TreeNode* root) {',
    '    if (!root) return 0;',
    '    unsigned long long maxWidth = 0;',
    '    queue<pair<TreeNode*, unsigned long long>> q;',
    '    q.push({root, 1});',
    '    while (!q.empty()) {',
    '        int sz = q.size();',
    '        auto base = q.front().second;',
    '        unsigned long long left = 0, right = 0;',
    '        for (int i = 0; i < sz; ++i) {',
    '            auto [node, idx] = q.front(); q.pop();',
    '            idx -= base;',
    '            if (i == 0) left = idx;',
    '            if (i == sz - 1) right = idx;',
    '            if (node->left) q.push({node->left, idx * 2});',
    '            if (node->right) q.push({node->right, idx * 2 + 1});',
    '        }',
    '        maxWidth = max(maxWidth, right - left + 1);',
    '    }',
    '    return maxWidth;',
    '}',
  ],
  python: [
    'def widthOfBinaryTree(root: Optional[TreeNode]) -> int:',
    '    if not root: return 0',
    '    max_width, q = 0, collections.deque([(root, 1)])',
    '    while q:',
    '        sz = len(q)',
    '        _, base = q[0]',
    '        left, right = 0, 0',
    '        for i in range(sz):',
    '            node, idx = q.popleft()',
    '            idx -= base',
    '            if i == 0: left = idx',
    '            if i == sz - 1: right = idx',
    '            if node.left: q.append((node.left, idx * 2))',
    '            if node.right: q.append((node.right, idx * 2 + 1))',
    '        max_width = max(max_width, right - left + 1)',
    '    return max_width',
  ],
  javascript: [
    'function widthOfBinaryTree(root) {',
    '    if (!root) return 0;',
    '    let maxWidth = 0;',
    '    const q = [[root, 1n]];',
    '    while (q.length > 0) {',
    '        const sz = q.length, base = q[0][1];',
    '        let left = 0n, right = 0n;',
    '        for (let i = 0; i < sz; i++) {',
    '            const [node, rawIdx] = q.shift();',
    '            const idx = rawIdx - base;',
    '            if (i === 0) left = idx;',
    '            if (i === sz - 1) right = idx;',
    '            if (node.left) q.push([node.left, idx * 2n]);',
    '            if (node.right) q.push([node.right, idx * 2n + 1n]);',
    '        }',
    '        const curWidth = Number(right - left + 1n);',
    '        maxWidth = Math.max(maxWidth, curWidth);',
    '    }',
    '    return maxWidth;',
    '}',
  ],
};

export const WIDTH_036_LINES = {
  entry: { java: 1, cpp: 1, python: 1, javascript: 1 },
  initQueue: { java: 5, cpp: 5, python: 3, javascript: 4 },
  whileLoop: { java: 6, cpp: 6, python: 4, javascript: 5 },
  baseOffset: { java: 8, cpp: 8, python: 6, javascript: 6 },
  forLoop: { java: 10, cpp: 10, python: 8, javascript: 8 },
  pollNode: { java: 11, cpp: 11, python: 9, javascript: 9 },
  calcIdx: { java: 13, cpp: 12, python: 10, javascript: 10 },
  pushLeft: { java: 16, cpp: 15, python: 13, javascript: 13 },
  pushRight: { java: 17, cpp: 16, python: 14, javascript: 14 },
  calcSpan: { java: 19, cpp: 18, python: 15, javascript: 17 },
  returnAns: { java: 21, cpp: 20, python: 16, javascript: 19 },
};

// ----------------------------------------------------
// 4. Depth of Binary Tree (Class 036 Code04)
// ----------------------------------------------------
export const DEPTH_036_CODES = {
  java: [
    'public int maxDepth(TreeNode root) {',
    '    if (root == null) return 0;',
    '    return Math.max(maxDepth(root.left), maxDepth(root.right)) + 1;',
    '}',
    'public int minDepth(TreeNode root) {',
    '    if (root == null) return 0;',
    '    if (root.left == null) return minDepth(root.right) + 1;',
    '    if (root.right == null) return minDepth(root.left) + 1;',
    '    return Math.min(minDepth(root.left), minDepth(root.right)) + 1;',
    '}',
  ],
  cpp: [
    'int maxDepth(TreeNode* root) {',
    '    if (!root) return 0;',
    '    return max(maxDepth(root->left), maxDepth(root->right)) + 1;',
    '}',
    'int minDepth(TreeNode* root) {',
    '    if (!root) return 0;',
    '    if (!root->left) return minDepth(root->right) + 1;',
    '    if (!root->right) return minDepth(root->left) + 1;',
    '    return min(minDepth(root->left), minDepth(root->right)) + 1;',
    '}',
  ],
  python: [
    'def maxDepth(root: Optional[TreeNode]) -> int:',
    '    if not root: return 0',
    '    return max(maxDepth(root.left), maxDepth(root.right)) + 1',
    '',
    'def minDepth(root: Optional[TreeNode]) -> int:',
    '    if not root: return 0',
    '    if not root.left: return minDepth(root.right) + 1',
    '    if not root.right: return minDepth(root.left) + 1',
    '    return min(minDepth(root.left), minDepth(root.right)) + 1',
  ],
  javascript: [
    'function maxDepth(root) {',
    '    if (!root) return 0;',
    '    return Math.max(maxDepth(root.left), maxDepth(root.right)) + 1;',
    '}',
    'function minDepth(root) {',
    '    if (!root) return 0;',
    '    if (!root.left) return minDepth(root.right) + 1;',
    '    if (!root.right) return minDepth(root.left) + 1;',
    '    return Math.min(minDepth(root.left), minDepth(root.right)) + 1;',
    '}',
  ],
};

export const DEPTH_036_LINES = {
  maxEntry: { java: 1, cpp: 1, python: 1, javascript: 1 },
  maxRecur: { java: 3, cpp: 3, python: 3, javascript: 3 },
  minEntry: { java: 5, cpp: 5, python: 5, javascript: 5 },
  minSingleChild: { java: 7, cpp: 7, python: 7, javascript: 7 },
  minBoth: { java: 9, cpp: 9, python: 9, javascript: 9 },
};

// ----------------------------------------------------
// 5. Preorder Serialize & Deserialize (Class 036 Code05)
// ----------------------------------------------------
export const PREORDER_SERIALIZE_036_CODES = {
  java: [
    'public class Codec {',
    '    public String serialize(TreeNode root) {',
    '        StringBuilder sb = new StringBuilder();',
    '        dfsSerial(root, sb);',
    '        return sb.toString();',
    '    }',
    '    private void dfsSerial(TreeNode node, StringBuilder sb) {',
    '        if (node == null) { sb.append("#,"); return; }',
    '        sb.append(node.val).append(",");',
    '        dfsSerial(node.left, sb);',
    '        dfsSerial(node.right, sb);',
    '    }',
    '    public TreeNode deserialize(String data) {',
    '        Queue<String> q = new LinkedList<>(Arrays.asList(data.split(",")));',
    '        return build(q);',
    '    }',
    '    private TreeNode build(Queue<String> q) {',
    '        String val = q.poll();',
    '        if (val.equals("#")) return null;',
    '        TreeNode head = new TreeNode(Integer.parseInt(val));',
    '        head.left = build(q);',
    '        head.right = build(q);',
    '        return head;',
    '    }',
    '}',
  ],
  cpp: [
    'class Codec {',
    'public:',
    '    string serialize(TreeNode* root) {',
    '        if (!root) return "#,";',
    '        return to_string(root->val) + "," + serialize(root->left) + serialize(root->right);',
    '    }',
    '    TreeNode* deserialize(string data) {',
    '        queue<string> q;',
    '        stringstream ss(data); string item;',
    '        while (getline(ss, item, \',\')) if (!item.empty()) q.push(item);',
    '        return build(q);',
    '    }',
    '    TreeNode* build(queue<string>& q) {',
    '        string val = q.front(); q.pop();',
    '        if (val == "#") return nullptr;',
    '        auto head = new TreeNode(stoi(val));',
    '        head->left = build(q); head->right = build(q);',
    '        return head;',
    '    }',
    '};',
  ],
  python: [
    'class Codec:',
    '    def serialize(self, root: TreeNode) -> str:',
    '        if not root: return "#,"',
    '        return f"{root.val}," + self.serialize(root.left) + self.serialize(root.right)',
    '    def deserialize(self, data: str) -> TreeNode:',
    '        vals = collections.deque(data.split(","))',
    '        def build():',
    '            val = vals.popleft()',
    '            if val == "#" or not val: return None',
    '            node = TreeNode(int(val))',
    '            node.left, node.right = build(), build()',
    '            return node',
    '        return build()',
  ],
  javascript: [
    'class Codec {',
    '    serialize(root) {',
    '        if (!root) return "#,";',
    '        return `${root.val},${this.serialize(root.left)}${this.serialize(root.right)}`;',
    '    }',
    '    deserialize(data) {',
    '        const q = data.split(",").filter(s => s.length > 0);',
    '        const build = () => {',
    '            const val = q.shift();',
    '            if (val === "#" || !val) return null;',
    '            const head = new TreeNode(Number(val));',
    '            head.left = build(); head.right = build();',
    '            return head;',
    '        };',
    '        return build();',
    '    }',
    '}',
  ],
};

export const PREORDER_SERIALIZE_036_LINES = {
  serialEntry: { java: 2, cpp: 3, python: 2, javascript: 2 },
  appendNode: { java: 9, cpp: 5, python: 4, javascript: 4 },
  deserialEntry: { java: 13, cpp: 7, python: 5, javascript: 6 },
  buildRecur: { java: 20, cpp: 16, python: 9, javascript: 10 },
};

// ----------------------------------------------------
// 6. Levelorder Serialize & Deserialize (Class 036 Code06)
// ----------------------------------------------------
export const LEVELORDER_SERIALIZE_036_CODES = {
  java: [
    'public class LevelCodec {',
    '    public String serialize(TreeNode root) {',
    '        if (root == null) return "#,";',
    '        StringBuilder sb = new StringBuilder();',
    '        Queue<TreeNode> q = new LinkedList<>();',
    '        q.offer(root); sb.append(root.val).append(",");',
    '        while (!q.isEmpty()) {',
    '            TreeNode cur = q.poll();',
    '            if (cur.left != null) { sb.append(cur.left.val).append(","); q.offer(cur.left); }',
    '            else sb.append("#,");',
    '            if (cur.right != null) { sb.append(cur.right.val).append(","); q.offer(cur.right); }',
    '            else sb.append("#,");',
    '        }',
    '        return sb.toString();',
    '    }',
    '}',
  ],
  cpp: [
    'string serialize(TreeNode* root) {',
    '    if (!root) return "#,";',
    '    string ans;',
    '    queue<TreeNode*> q; q.push(root);',
    '    ans += to_string(root->val) + ",";',
    '    while (!q.empty()) {',
    '        auto cur = q.front(); q.pop();',
    '        if (cur->left) { ans += to_string(cur->left->val) + ","; q.push(cur->left); }',
    '        else ans += "#,";',
    '        if (cur->right) { ans += to_string(cur->right->val) + ","; q.push(cur->right); }',
    '        else ans += "#,";',
    '    }',
    '    return ans;',
    '}',
  ],
  python: [
    'def serialize(root: TreeNode) -> str:',
    '    if not root: return "#,"',
    '    res, q = [str(root.val)], collections.deque([root])',
    '    while q:',
    '        cur = q.popleft()',
    '        if cur.left: res.append(str(cur.left.val)); q.append(cur.left)',
    '        else: res.append("#")',
    '        if cur.right: res.append(str(cur.right.val)); q.append(cur.right)',
    '        else: res.append("#")',
    '    return ",".join(res) + ","',
  ],
  javascript: [
    'function serialize(root) {',
    '    if (!root) return "#,";',
    '    const res = [root.val], q = [root];',
    '    while (q.length > 0) {',
    '        const cur = q.shift();',
    '        if (cur.left) { res.push(cur.left.val); q.push(cur.left); }',
    '        else res.push("#");',
    '        if (cur.right) { res.push(cur.right.val); q.push(cur.right); }',
    '        else res.push("#");',
    '    }',
    '    return res.join(",") + ",";',
    '}',
  ],
};

export const LEVELORDER_SERIALIZE_036_LINES = {
  entry: { java: 2, cpp: 1, python: 1, javascript: 1 },
  rootQueue: { java: 6, cpp: 4, python: 3, javascript: 3 },
  expandChildren: { java: 9, cpp: 8, python: 6, javascript: 6 },
  finish: { java: 14, cpp: 13, python: 10, javascript: 11 },
};

// ----------------------------------------------------
// 7. Build Tree from Preorder & Inorder (Class 036 Code07)
// ----------------------------------------------------
export const BUILD_TREE_036_CODES = {
  java: [
    'public TreeNode buildTree(int[] preorder, int[] inorder) {',
    '    Map<Integer, Integer> map = new HashMap<>();',
    '    for (int i = 0; i < inorder.length; i++) map.put(inorder[i], i);',
    '    return build(preorder, 0, preorder.length - 1, 0, inorder.length - 1, map);',
    '}',
    'private TreeNode build(int[] pre, int l1, int r1, int l2, int r2, Map<Integer, Integer> map) {',
    '    if (l1 > r1) return null;',
    '    TreeNode root = new TreeNode(pre[l1]);',
    '    int k = map.get(pre[l1]);',
    '    int leftLen = k - l2;',
    '    root.left = build(pre, l1 + 1, l1 + leftLen, l2, k - 1, map);',
    '    root.right = build(pre, l1 + leftLen + 1, r1, k + 1, r2, map);',
    '    return root;',
    '}',
  ],
  cpp: [
    'TreeNode* buildTree(vector<int>& pre, vector<int>& in) {',
    '    unordered_map<int, int> pos;',
    '    for (int i = 0; i < in.size(); ++i) pos[in[i]] = i;',
    '    return build(pre, 0, pre.size() - 1, 0, in.size() - 1, pos);',
    '}',
    'TreeNode* build(vector<int>& pre, int l1, int r1, int l2, int r2, unordered_map<int,int>& pos) {',
    '    if (l1 > r1) return nullptr;',
    '    auto root = new TreeNode(pre[l1]);',
    '    int k = pos[pre[l1]], leftLen = k - l2;',
    '    root->left = build(pre, l1 + 1, l1 + leftLen, l2, k - 1, pos);',
    '    root->right = build(pre, l1 + leftLen + 1, r1, k + 1, r2, pos);',
    '    return root;',
    '}',
  ],
  python: [
    'def buildTree(preorder: List[int], inorder: List[int]) -> Optional[TreeNode]:',
    '    pos = {v: i for i, v in enumerate(inorder)}',
    '    def build(l1, r1, l2, r2):',
    '        if l1 > r1: return None',
    '        root = TreeNode(preorder[l1])',
    '        k = pos[preorder[l1]]',
    '        left_len = k - l2',
    '        root.left = build(l1 + 1, l1 + left_len, l2, k - 1)',
    '        root.right = build(l1 + left_len + 1, r1, k + 1, r2)',
    '        return root',
    '    return build(0, len(preorder) - 1, 0, len(inorder) - 1)',
  ],
  javascript: [
    'function buildTree(preorder, inorder) {',
    '    const pos = new Map();',
    '    inorder.forEach((v, i) => pos.set(v, i));',
    '    function build(l1, r1, l2, r2) {',
    '        if (l1 > r1) return null;',
    '        const root = new TreeNode(preorder[l1]);',
    '        const k = pos.get(preorder[l1]);',
    '        const leftLen = k - l2;',
    '        root.left = build(l1 + 1, l1 + leftLen, l2, k - 1);',
    '        root.right = build(l1 + leftLen + 1, r1, k + 1, r2);',
    '        return root;',
    '    }',
    '    return build(0, preorder.length - 1, 0, inorder.length - 1);',
    '}',
  ],
};

export const BUILD_TREE_036_LINES = {
  entry: { java: 1, cpp: 1, python: 1, javascript: 1 },
  hashInorder: { java: 3, cpp: 3, python: 2, javascript: 3 },
  rootPivot: { java: 8, cpp: 8, python: 5, javascript: 6 },
  buildLeftRight: { java: 11, cpp: 11, python: 8, javascript: 9 },
  finish: { java: 13, cpp: 13, python: 10, javascript: 12 },
};

// ----------------------------------------------------
// 8. Completeness of Binary Tree (Class 036 Code08)
// ----------------------------------------------------
export const COMPLETENESS_036_CODES = {
  java: [
    'public boolean isCompleteTree(TreeNode root) {',
    '    if (root == null) return true;',
    '    Queue<TreeNode> q = new LinkedList<>();',
    '    q.offer(root);',
    '    boolean leaf = false;',
    '    while (!q.isEmpty()) {',
    '        TreeNode cur = q.poll();',
    '        TreeNode l = cur.left, r = cur.right;',
    '        if (leaf && (l != null || r != null)) return false;',
    '        if (l == null && r != null) return false;',
    '        if (l != null) q.offer(l);',
    '        if (r != null) q.offer(r);',
    '        if (l == null || r == null) leaf = true;',
    '    }',
    '    return true;',
    '}',
  ],
  cpp: [
    'bool isCompleteTree(TreeNode* root) {',
    '    if (!root) return true;',
    '    queue<TreeNode*> q; q.push(root);',
    '    bool leaf = false;',
    '    while (!q.empty()) {',
    '        auto cur = q.front(); q.pop();',
    '        auto l = cur->left, r = cur->right;',
    '        if (leaf && (l || r)) return false;',
    '        if (!l && r) return false;',
    '        if (l) q.push(l);',
    '        if (r) q.push(r);',
    '        if (!l || !r) leaf = true;',
    '    }',
    '    return true;',
    '}',
  ],
  python: [
    'def isCompleteTree(root: Optional[TreeNode]) -> bool:',
    '    if not root: return True',
    '    q, leaf = collections.deque([root]), False',
    '    while q:',
    '        cur = q.popleft()',
    '        l, r = cur.left, cur.right',
    '        if leaf and (l or r): return False',
    '        if not l and r: return False',
    '        if l: q.append(l)',
    '        if r: q.append(r)',
    '        if not l or not r: leaf = True',
    '    return True',
  ],
  javascript: [
    'function isCompleteTree(root) {',
    '    if (!root) return true;',
    '    const q = [root];',
    '    let leaf = false;',
    '    while (q.length > 0) {',
    '        const cur = q.shift();',
    '        const l = cur.left, r = cur.right;',
    '        if (leaf && (l || r)) return false;',
    '        if (!l && r) return false;',
    '        if (l) q.push(l);',
    '        if (r) q.push(r);',
    '        if (!l || !r) leaf = true;',
    '    }',
    '    return true;',
    '}',
  ],
};

export const COMPLETENESS_036_LINES = {
  entry: { java: 1, cpp: 1, python: 1, javascript: 1 },
  ruleCheck: { java: 9, cpp: 8, python: 7, javascript: 8 },
  leafTrigger: { java: 13, cpp: 12, python: 11, javascript: 12 },
  returnTrue: { java: 15, cpp: 14, python: 12, javascript: 14 },
};

// ----------------------------------------------------
// 9. Count Complete Tree Nodes (Class 036 Code09)
// ----------------------------------------------------
export const COUNT_NODES_036_CODES = {
  java: [
    'public int countNodes(TreeNode root) {',
    '    if (root == null) return 0;',
    '    return count(root, 1, mostLeft(root, 1));',
    '}',
    'private int count(TreeNode node, int level, int h) {',
    '    if (level == h) return 1;',
    '    if (mostLeft(node.right, level + 1) == h) {',
    '        return (1 << (h - level)) + count(node.right, level + 1, h);',
    '    } else {',
    '        return (1 << (h - level - 1)) + count(node.left, level + 1, h);',
    '    }',
    '}',
    'private int mostLeft(TreeNode node, int level) {',
    '    while (node != null) { level++; node = node.left; }',
    '    return level - 1;',
    '}',
  ],
  cpp: [
    'int countNodes(TreeNode* root) {',
    '    if (!root) return 0;',
    '    return count(root, 1, mostLeft(root, 1));',
    '}',
    'int count(TreeNode* node, int level, int h) {',
    '    if (level == h) return 1;',
    '    if (mostLeft(node->right, level + 1) == h) {',
    '        return (1 << (h - level)) + count(node->right, level + 1, h);',
    '    } else {',
    '        return (1 << (h - level - 1)) + count(node->left, level + 1, h);',
    '    }',
    '}',
    'int mostLeft(TreeNode* node, int level) {',
    '    while (node) { level++; node = node->left; }',
    '    return level - 1;',
    '}',
  ],
  python: [
    'def countNodes(root: Optional[TreeNode]) -> int:',
    '    if not root: return 0',
    '    def most_left(node, level):',
    '        while node: level += 1; node = node.left',
    '        return level - 1',
    '    h = most_left(root, 1)',
    '    def count(node, level):',
    '        if level == h: return 1',
    '        if most_left(node.right, level + 1) == h:',
    '            return (1 << (h - level)) + count(node.right, level + 1)',
    '        else:',
    '            return (1 << (h - level - 1)) + count(node.left, level + 1)',
    '    return count(root, 1)',
  ],
  javascript: [
    'function countNodes(root) {',
    '    if (!root) return 0;',
    '    function mostLeft(node, level) {',
    '        while (node) { level++; node = node.left; }',
    '        return level - 1;',
    '    }',
    '    const h = mostLeft(root, 1);',
    '    function count(node, level) {',
    '        if (level === h) return 1;',
    '        if (mostLeft(node.right, level + 1) === h) {',
    '            return (1 << (h - level)) + count(node.right, level + 1);',
    '        } else {',
    '            return (1 << (h - level - 1)) + count(node.left, level + 1);',
    '        }',
    '    }',
    '    return count(root, 1);',
    '}',
  ],
};

export const COUNT_NODES_036_LINES = {
  entry: { java: 1, cpp: 1, python: 1, javascript: 1 },
  calcHeight: { java: 3, cpp: 3, python: 6, javascript: 7 },
  probeRight: { java: 7, cpp: 7, python: 9, javascript: 10 },
  accumulateFullSubtree: { java: 8, cpp: 8, python: 10, javascript: 11 },
  finish: { java: 12, cpp: 12, python: 13, javascript: 16 },
};

// ----------------------------------------------------
// 10. LCA (Class 037 Code01)
// ----------------------------------------------------
export const LCA_037_CODES = {
  java: [
    'public TreeNode lowestCommonAncestor(TreeNode root, TreeNode p, TreeNode q) {',
    '    if (root == null || root == p || root == q) return root;',
    '    TreeNode left = lowestCommonAncestor(root.left, p, q);',
    '    TreeNode right = lowestCommonAncestor(root.right, p, q);',
    '    if (left != null && right != null) return root;',
    '    return left != null ? left : right;',
    '}',
  ],
  cpp: [
    'TreeNode* lowestCommonAncestor(TreeNode* root, TreeNode* p, TreeNode* q) {',
    '    if (!root || root == p || root == q) return root;',
    '    auto left = lowestCommonAncestor(root->left, p, q);',
    '    auto right = lowestCommonAncestor(root->right, p, q);',
    '    if (left && right) return root;',
    '    return left ? left : right;',
    '}',
  ],
  python: [
    'def lowestCommonAncestor(root: TreeNode, p: TreeNode, q: TreeNode) -> TreeNode:',
    '    if not root or root == p or root == q: return root',
    '    left = lowestCommonAncestor(root.left, p, q)',
    '    right = lowestCommonAncestor(root.right, p, q)',
    '    if left and right: return root',
    '    return left if left else right',
  ],
  javascript: [
    'function lowestCommonAncestor(root, p, q) {',
    '    if (!root || root === p || root === q) return root;',
    '    const left = lowestCommonAncestor(root.left, p, q);',
    '    const right = lowestCommonAncestor(root.right, p, q);',
    '    if (left && right) return root;',
    '    return left ? left : right;',
    '}',
  ],
};

export const LCA_037_LINES = {
  entry: { java: 1, cpp: 1, python: 1, javascript: 1 },
  baseCheck: { java: 2, cpp: 2, python: 2, javascript: 2 },
  bothFound: { java: 5, cpp: 5, python: 5, javascript: 5 },
  passUp: { java: 6, cpp: 6, python: 6, javascript: 6 },
};

// ----------------------------------------------------
// 11. LCA BST (Class 037 Code02)
// ----------------------------------------------------
export const LCA_BST_037_CODES = {
  java: [
    'public TreeNode lowestCommonAncestor(TreeNode root, TreeNode p, TreeNode q) {',
    '    while (root != null) {',
    '        if (root.val > p.val && root.val > q.val) root = root.left;',
    '        else if (root.val < p.val && root.val < q.val) root = root.right;',
    '        else return root;',
    '    }',
    '    return null;',
    '}',
  ],
  cpp: [
    'TreeNode* lowestCommonAncestor(TreeNode* root, TreeNode* p, TreeNode* q) {',
    '    while (root) {',
    '        if (root->val > p->val && root->val > q->val) root = root->left;',
    '        else if (root->val < p->val && root->val < q->val) root = root->right;',
    '        else return root;',
    '    }',
    '    return nullptr;',
    '}',
  ],
  python: [
    'def lowestCommonAncestor(root: TreeNode, p: TreeNode, q: TreeNode) -> TreeNode:',
    '    while root:',
    '        if root.val > p.val and root.val > q.val: root = root.left',
    '        elif root.val < p.val and root.val < q.val: root = root.right',
    '        else: return root',
    '    return None',
  ],
  javascript: [
    'function lowestCommonAncestor(root, p, q) {',
    '    while (root) {',
    '        if (root.val > p.val && root.val > q.val) root = root.left;',
    '        else if (root.val < p.val && root.val < q.val) root = root.right;',
    '        else return root;',
    '    }',
    '    return null;',
    '}',
  ],
};

export const LCA_BST_037_LINES = {
  entry: { java: 1, cpp: 1, python: 1, javascript: 1 },
  goLeft: { java: 3, cpp: 3, python: 3, javascript: 3 },
  goRight: { java: 4, cpp: 4, python: 4, javascript: 4 },
  splitFork: { java: 5, cpp: 5, python: 5, javascript: 5 },
};

// ----------------------------------------------------
// 12. Path Sum II (Class 037 Code03)
// ----------------------------------------------------
export const PATH_SUM_II_037_CODES = {
  java: [
    'public List<List<Integer>> pathSum(TreeNode root, int targetSum) {',
    '    List<List<Integer>> ans = new ArrayList<>();',
    '    if (root == null) return ans;',
    '    List<Integer> path = new ArrayList<>();',
    '    dfs(root, targetSum, path, ans);',
    '    return ans;',
    '}',
    'private void dfs(TreeNode cur, int remain, List<Integer> path, List<List<Integer>> ans) {',
    '    path.add(cur.val); remain -= cur.val;',
    '    if (cur.left == null && cur.right == null && remain == 0) {',
    '        ans.add(new ArrayList<>(path));',
    '    }',
    '    if (cur.left != null) dfs(cur.left, remain, path, ans);',
    '    if (cur.right != null) dfs(cur.right, remain, path, ans);',
    '    path.remove(path.size() - 1);',
    '}',
  ],
  cpp: [
    'vector<vector<int>> pathSum(TreeNode* root, int targetSum) {',
    '    vector<vector<int>> ans; vector<int> path;',
    '    if (!root) return ans;',
    '    dfs(root, targetSum, path, ans);',
    '    return ans;',
    '}',
    'void dfs(TreeNode* cur, int remain, vector<int>& path, vector<vector<int>>& ans) {',
    '    path.push_back(cur->val); remain -= cur->val;',
    '    if (!cur->left && !cur->right && remain == 0) ans.push_back(path);',
    '    if (cur->left) dfs(cur->left, remain, path, ans);',
    '    if (cur->right) dfs(cur->right, remain, path, ans);',
    '    path.pop_back();',
    '}',
  ],
  python: [
    'def pathSum(root: Optional[TreeNode], targetSum: int) -> List[List[int]]:',
    '    ans, path = [], []',
    '    def dfs(cur, remain):',
    '        if not cur: return',
    '        path.append(cur.val); remain -= cur.val',
    '        if not cur.left and not cur.right and remain == 0: ans.append(list(path))',
    '        if cur.left: dfs(cur.left, remain)',
    '        if cur.right: dfs(cur.right, remain)',
    '        path.pop()',
    '    dfs(root, targetSum)',
    '    return ans',
  ],
  javascript: [
    'function pathSum(root, targetSum) {',
    '    const ans = [], path = [];',
    '    function dfs(cur, remain) {',
    '        if (!cur) return;',
    '        path.push(cur.val); remain -= cur.val;',
    '        if (!cur.left && !cur.right && remain === 0) ans.push([...path]);',
    '        if (cur.left) dfs(cur.left, remain);',
    '        if (cur.right) dfs(cur.right, remain);',
    '        path.pop();',
    '    }',
    '    dfs(root, targetSum);',
    '    return ans;',
    '}',
  ],
};

export const PATH_SUM_II_037_LINES = {
  entry: { java: 1, cpp: 1, python: 1, javascript: 1 },
  pushVal: { java: 9, cpp: 8, python: 5, javascript: 5 },
  foundLeaf: { java: 11, cpp: 9, python: 6, javascript: 6 },
  backtrack: { java: 15, cpp: 12, python: 9, javascript: 9 },
};

// ----------------------------------------------------
// 13. Balanced Binary Tree (Class 037 Code04)
// ----------------------------------------------------
export const BALANCED_TREE_037_CODES = {
  java: [
    'public boolean isBalanced(TreeNode root) {',
    '    return process(root).isBalanced;',
    '}',
    'static class Info {',
    '    boolean isBalanced; int height;',
    '    Info(boolean b, int h) { isBalanced = b; height = h; }',
    '}',
    'private Info process(TreeNode x) {',
    '    if (x == null) return new Info(true, 0);',
    '    Info l = process(x.left);',
    '    Info r = process(x.right);',
    '    int h = Math.max(l.height, r.height) + 1;',
    '    boolean bal = l.isBalanced && r.isBalanced && Math.abs(l.height - r.height) <= 1;',
    '    return new Info(bal, h);',
    '}',
  ],
  cpp: [
    'struct Info { bool isBalanced; int height; };',
    'bool isBalanced(TreeNode* root) { return process(root).isBalanced; }',
    'Info process(TreeNode* x) {',
    '    if (!x) return {true, 0};',
    '    auto l = process(x->left), r = process(x->right);',
    '    int h = max(l.height, r.height) + 1;',
    '    bool bal = l.isBalanced && r.isBalanced && abs(l.height - r.height) <= 1;',
    '    return {bal, h};',
    '}',
  ],
  python: [
    'def isBalanced(root: Optional[TreeNode]) -> bool:',
    '    def process(x):',
    '        if not x: return True, 0',
    '        l_bal, l_h = process(x.left)',
    '        r_bal, r_h = process(x.right)',
    '        h = max(l_h, r_h) + 1',
    '        bal = l_bal and r_bal and abs(l_h - r_h) <= 1',
    '        return bal, h',
    '    return process(root)[0]',
  ],
  javascript: [
    'function isBalanced(root) {',
    '    function process(x) {',
    '        if (!x) return { isBalanced: true, height: 0 };',
    '        const l = process(x.left), r = process(x.right);',
    '        const h = Math.max(l.height, r.height) + 1;',
    '        const bal = l.isBalanced && r.isBalanced && Math.abs(l.height - r.height) <= 1;',
    '        return { isBalanced: bal, height: h };',
    '    }',
    '    return process(root).isBalanced;',
    '}',
  ],
};

export const BALANCED_TREE_037_LINES = {
  entry: { java: 1, cpp: 2, python: 1, javascript: 1 },
  baseCheck: { java: 10, cpp: 4, python: 3, javascript: 3 },
  aggregateInfo: { java: 13, cpp: 6, python: 6, javascript: 5 },
  returnInfo: { java: 15, cpp: 8, python: 8, javascript: 7 },
};

export const BALANCED_TREE_037_STAGE1_CODES = BALANCED_TREE_037_CODES;
export const BALANCED_TREE_037_STAGE1_LINES = BALANCED_TREE_037_LINES;

export const BALANCED_TREE_037_STAGE2_CODES = {
  java: [
    'public class Solution {',
    '    public boolean isBalanced(TreeNode root) {',
    '        return check(root) != -1;',
    '    }',
    '    private int check(TreeNode node) {',
    '        if (node == null) return 0;',
    '        int left = check(node.left);',
    '        if (left == -1) return -1;',
    '        int right = check(node.right);',
    '        if (right == -1) return -1;',
    '        if (Math.abs(left - right) > 1) return -1;',
    '        return Math.max(left, right) + 1;',
    '    }',
    '}',
  ],
  cpp: [
    'class Solution {',
    'public:',
    '    bool isBalanced(TreeNode* root) {',
    '        return check(root) != -1;',
    '    }',
    '    int check(TreeNode* node) {',
    '        if (!node) return 0;',
    '        int left = check(node->left);',
    '        if (left == -1) return -1;',
    '        int right = check(node->right);',
    '        if (right == -1) return -1;',
    '        if (abs(left - right) > 1) return -1;',
    '        return max(left, right) + 1;',
    '    }',
    '};',
  ],
  python: [
    'class Solution:',
    '    def isBalanced(self, root: Optional[TreeNode]) -> bool:',
    '        def check(node):',
    '            if not node:',
    '                return 0',
    '            left = check(node.left)',
    '            if left == -1: return -1',
    '            right = check(node.right)',
    '            if right == -1: return -1',
    '            if abs(left - right) > 1: return -1',
    '            return max(left, right) + 1',
    '        return check(root) != -1',
  ],
  javascript: [
    'function isBalanced(root) {',
    '    function check(node) {',
    '        if (!node) return 0;',
    '        const left = check(node.left);',
    '        if (left === -1) return -1;',
    '        const right = check(node.right);',
    '        if (right === -1) return -1;',
    '        if (Math.abs(left - right) > 1) return -1;',
    '        return Math.max(left, right) + 1;',
    '    }',
    '    return check(root) !== -1;',
    '}',
  ],
};

export const BALANCED_TREE_037_STAGE2_LINES = {
  entry: { java: 2, cpp: 3, python: 2, javascript: 1 },
  baseNull: { java: 6, cpp: 7, python: 4, javascript: 3 },
  checkLeft: { java: 7, cpp: 8, python: 6, javascript: 4 },
  pruneLeft: { java: 8, cpp: 9, python: 7, javascript: 5 },
  checkRight: { java: 9, cpp: 10, python: 8, javascript: 6 },
  pruneRight: { java: 10, cpp: 11, python: 9, javascript: 7 },
  checkDiff: { java: 11, cpp: 12, python: 10, javascript: 8 },
  returnHeight: { java: 12, cpp: 13, python: 11, javascript: 9 },
  done: { java: 3, cpp: 4, python: 12, javascript: 11 },
};

export const BALANCED_TREE_037_STAGE3_CODES = {
  java: [
    'public class Solution {',
    '    public boolean isBalanced(TreeNode root) {',
    '        if (root == null) return true;',
    '        Deque<TreeNode> stack = new ArrayDeque<>();',
    '        Map<TreeNode, Integer> heightMap = new HashMap<>();',
    '        TreeNode curr = root, lastVisited = null;',
    '        while (curr != null || !stack.isEmpty()) {',
    '            while (curr != null) {',
    '                stack.push(curr);',
    '                curr = curr.left;',
    '            }',
    '            TreeNode top = stack.peek();',
    '            if (top.right != null && top.right != lastVisited) {',
    '                curr = top.right;',
    '            } else {',
    '                stack.pop();',
    '                int l = heightMap.getOrDefault(top.left, 0);',
    '                int r = heightMap.getOrDefault(top.right, 0);',
    '                if (Math.abs(l - r) > 1) return false;',
    '                heightMap.put(top, Math.max(l, r) + 1);',
    '                lastVisited = top;',
    '            }',
    '        }',
    '        return true;',
    '    }',
    '}',
  ],
  cpp: [
    'class Solution {',
    'public:',
    '    bool isBalanced(TreeNode* root) {',
    '        if (!root) return true;',
    '        stack<TreeNode*> st;',
    '        unordered_map<TreeNode*, int> heightMap;',
    '        TreeNode* curr = root;',
    '        TreeNode* lastVisited = nullptr;',
    '        while (curr || !st.empty()) {',
    '            while (curr) {',
    '                st.push(curr);',
    '                curr = curr->left;',
    '            }',
    '            TreeNode* top = st.top();',
    '            if (top->right && top->right != lastVisited) {',
    '                curr = top->right;',
    '            } else {',
    '                st.pop();',
    '                int l = top->left ? heightMap[top->left] : 0;',
    '                int r = top->right ? heightMap[top->right] : 0;',
    '                if (abs(l - r) > 1) return false;',
    '                heightMap[top] = max(l, r) + 1;',
    '                lastVisited = top;',
    '            }',
    '        }',
    '        return true;',
    '    }',
    '};',
  ],
  python: [
    'class Solution:',
    '    def isBalanced(self, root: Optional[TreeNode]) -> bool:',
    '        if not root: return True',
    '        stack = []',
    '        height_map = {}',
    '        curr, last_visited = root, None',
    '        while curr or stack:',
    '            while curr:',
    '                stack.append(curr)',
    '                curr = curr.left',
    '            top = stack[-1]',
    '            if top.right and top.right != last_visited:',
    '                curr = top.right',
    '            else:',
    '                stack.pop()',
    '                l = height_map.get(top.left, 0)',
    '                r = height_map.get(top.right, 0)',
    '                if abs(l - r) > 1: return False',
    '                height_map[top] = max(l, r) + 1',
    '                last_visited = top',
    '        return True',
  ],
  javascript: [
    'function isBalanced(root) {',
    '    if (!root) return true;',
    '    const stack = [];',
    '    const heightMap = new Map();',
    '    let curr = root, lastVisited = null;',
    '    while (curr || stack.length > 0) {',
    '        while (curr) {',
    '            stack.push(curr);',
    '            curr = curr.left;',
    '        }',
    '        const top = stack[stack.length - 1];',
    '        if (top.right && top.right !== lastVisited) {',
    '            curr = top.right;',
    '        } else {',
    '            stack.pop();',
    '            const l = top.left ? (heightMap.get(top.left) || 0) : 0;',
    '            const r = top.right ? (heightMap.get(top.right) || 0) : 0;',
    '            if (Math.abs(l - r) > 1) return false;',
    '            heightMap.set(top, Math.max(l, r) + 1);',
    '            lastVisited = top;',
    '        }',
    '    }',
    '    return true;',
    '}',
  ],
};

export const BALANCED_TREE_037_STAGE3_LINES = {
  entry: { java: 3, cpp: 4, python: 3, javascript: 2 },
  pushLeft: { java: 9, cpp: 11, python: 9, javascript: 8 },
  checkRight: { java: 13, cpp: 15, python: 13, javascript: 12 },
  popAndCalc: { java: 16, cpp: 18, python: 16, javascript: 15 },
  checkDiff: { java: 19, cpp: 21, python: 19, javascript: 18 },
  saveHeight: { java: 20, cpp: 22, python: 20, javascript: 19 },
  done: { java: 24, cpp: 26, python: 21, javascript: 22 },
};


// ----------------------------------------------------
// 14. Validate BST (Class 037 Code05)
// ----------------------------------------------------
export const VALIDATE_BST_037_CODES = {
  java: [
    'public boolean isValidBST(TreeNode root) {',
    '    return inOrder(root);',
    '}',
    'private Long prev = null;',
    'private boolean inOrder(TreeNode node) {',
    '    if (node == null) return true;',
    '    if (!inOrder(node.left)) return false;',
    '    if (prev != null && node.val <= prev) return false;',
    '    prev = (long) node.val;',
    '    return inOrder(node.right);',
    '}',
  ],
  cpp: [
    'long long prevVal = LLONG_MIN;',
    'bool isValidBST(TreeNode* root) {',
    '    if (!root) return true;',
    '    if (!isValidBST(root->left)) return false;',
    '    if (root->val <= prevVal) return false;',
    '    prevVal = root->val;',
    '    return isValidBST(root->right);',
    '}',
  ],
  python: [
    'def isValidBST(root: Optional[TreeNode]) -> bool:',
    '    prev = float("-inf")',
    '    def inorder(node):',
    '        nonlocal prev',
    '        if not node: return True',
    '        if not inorder(node.left): return False',
    '        if node.val <= prev: return False',
    '        prev = node.val',
    '        return inorder(node.right)',
    '    return inorder(root)',
  ],
  javascript: [
    'function isValidBST(root) {',
    '    let prev = -Infinity;',
    '    function inOrder(node) {',
    '        if (!node) return true;',
    '        if (!inOrder(node.left)) return false;',
    '        if (node.val <= prev) return false;',
    '        prev = node.val;',
    '        return inOrder(node.right);',
    '    }',
    '    return inOrder(root);',
    '}',
  ],
};

export const VALIDATE_BST_037_LINES = {
  entry: { java: 1, cpp: 2, python: 1, javascript: 1 },
  leftDfs: { java: 7, cpp: 4, python: 6, javascript: 5 },
  monotoneCheck: { java: 8, cpp: 5, python: 7, javascript: 6 },
  updatePrev: { java: 9, cpp: 6, python: 8, javascript: 7 },
  rightDfs: { java: 10, cpp: 7, python: 9, javascript: 8 },
};

// ----------------------------------------------------
// 15. Trim BST (Class 037 Code06)
// ----------------------------------------------------
export const TRIM_BST_037_CODES = {
  java: [
    'public TreeNode trimBST(TreeNode root, int low, int high) {',
    '    if (root == null) return null;',
    '    if (root.val < low) return trimBST(root.right, low, high);',
    '    if (root.val > high) return trimBST(root.left, low, high);',
    '    root.left = trimBST(root.left, low, high);',
    '    root.right = trimBST(root.right, low, high);',
    '    return root;',
    '}',
  ],
  cpp: [
    'TreeNode* trimBST(TreeNode* root, int low, int high) {',
    '    if (!root) return nullptr;',
    '    if (root->val < low) return trimBST(root->right, low, high);',
    '    if (root->val > high) return trimBST(root->left, low, high);',
    '    root->left = trimBST(root->left, low, high);',
    '    root->right = trimBST(root->right, low, high);',
    '    return root;',
    '}',
  ],
  python: [
    'def trimBST(root: Optional[TreeNode], low: int, high: int) -> Optional[TreeNode]:',
    '    if not root: return None',
    '    if root.val < low: return trimBST(root.right, low, high)',
    '    if root.val > high: return trimBST(root.left, low, high)',
    '    root.left = trimBST(root.left, low, high)',
    '    root.right = trimBST(root.right, low, high)',
    '    return root',
  ],
  javascript: [
    'function trimBST(root, low, high) {',
    '    if (!root) return null;',
    '    if (root.val < low) return trimBST(root.right, low, high);',
    '    if (root.val > high) return trimBST(root.left, low, high);',
    '    root.left = trimBST(root.left, low, high);',
    '    root.right = trimBST(root.right, low, high);',
    '    return root;',
    '}',
  ],
};

export const TRIM_BST_037_LINES = {
  entry: { java: 1, cpp: 1, python: 1, javascript: 1 },
  trimLow: { java: 3, cpp: 3, python: 3, javascript: 3 },
  trimHigh: { java: 4, cpp: 4, python: 4, javascript: 4 },
  trimBoth: { java: 5, cpp: 5, python: 5, javascript: 5 },
  returnRoot: { java: 7, cpp: 7, python: 7, javascript: 7 },
};

// ----------------------------------------------------
// 16. House Robber III (Class 037 Code07)
// ----------------------------------------------------
export const HOUSE_ROBBER_III_037_CODES = {
  java: [
    'public int rob(TreeNode root) {',
    '    int[] res = dp(root);',
    '    return Math.max(res[0], res[1]);',
    '}',
    '// res[0] 不偷当前节点, res[1] 偷当前节点',
    'private int[] dp(TreeNode node) {',
    '    if (node == null) return new int[]{0, 0};',
    '    int[] left = dp(node.left);',
    '    int[] right = dp(node.right);',
    '    int robCur = node.val + left[0] + right[0];',
    '    int notRob = Math.max(left[0], left[1]) + Math.max(right[0], right[1]);',
    '    return new int[]{notRob, robCur};',
    '}',
  ],
  cpp: [
    'int rob(TreeNode* root) {',
    '    auto res = dp(root);',
    '    return max(res.first, res.second);',
    '}',
    'pair<int, int> dp(TreeNode* node) {',
    '    if (!node) return {0, 0};',
    '    auto left = dp(node->left), right = dp(node->right);',
    '    int robCur = node->val + left.first + right.first;',
    '    int notRob = max(left.first, left.second) + max(right.first, right.second);',
    '    return {notRob, robCur};',
    '}',
  ],
  python: [
    'def rob(root: Optional[TreeNode]) -> int:',
    '    def dp(node):',
    '        if not node: return 0, 0',
    '        l_not, l_rob = dp(node.left)',
    '        r_not, r_rob = dp(node.right)',
    '        rob_cur = node.val + l_not + r_not',
    '        not_rob = max(l_not, l_rob) + max(r_not, r_rob)',
    '        return not_rob, rob_cur',
    '    return max(dp(root))',
  ],
  javascript: [
    'function rob(root) {',
    '    function dp(node) {',
    '        if (!node) return [0, 0];',
    '        const left = dp(node.left), right = dp(node.right);',
    '        const robCur = node.val + left[0] + right[0];',
    '        const notRob = Math.max(left[0], left[1]) + Math.max(right[0], right[1]);',
    '        return [notRob, robCur];',
    '    }',
    '    const res = dp(root);',
    '    return Math.max(res[0], res[1]);',
    '}',
  ],
};

export const HOUSE_ROBBER_III_037_LINES = {
  entry: { java: 1, cpp: 1, python: 1, javascript: 1 },
  baseCheck: { java: 7, cpp: 6, python: 3, javascript: 3 },
  robCur: { java: 10, cpp: 8, python: 6, javascript: 6 },
  notRob: { java: 11, cpp: 9, python: 7, javascript: 7 },
  returnMax: { java: 3, cpp: 3, python: 9, javascript: 11 },
};
