/**
 * Class 054: 单调队列·上 四语言完整源码与精准 1-based 行号映射
 */

import { HighlightTarget } from '../../../../core/renderers/dark-code-terminal-presenter';

export interface CodeMapping {
  java: number;
  cpp: number;
  python: number;
  javascript: number;
}

// -------------------------------------------------------------
// Code01: 滑动窗口最大值 (Sliding Window Maximum)
// -------------------------------------------------------------
export const CODE01_SLIDING_WINDOW_CODES: Record<string, string[]> = {
  java: [
    'public class SlidingWindowMaximum {',
    '    public static int MAXN = 100001;',
    '    public static int[] deque = new int[MAXN];',
    '    public static int h, t;',
    '    ',
    '    public static int[] maxSlidingWindow(int[] arr, int k) {',
    '        h = t = 0;',
    '        int n = arr.length;',
    '        // 1. 先形成长度为 k - 1 的初始窗口',
    '        for (int i = 0; i < k - 1; i++) {',
    '            while (h < t && arr[deque[t - 1]] <= arr[i]) {',
    '                t--; // 淘汰队尾劣质较小值',
    '            }',
    '            deque[t++] = i;',
    '        }',
    '        int m = n - k + 1;',
    '        int[] ans = new int[m];',
    '        // 2. 窗口开始完整右滑',
    '        for (int l = 0, r = k - 1; l < m; l++, r++) {',
    '            while (h < t && arr[deque[t - 1]] <= arr[r]) {',
    '                t--; // 淘汰比当前 r 小的值',
    '            }',
    '            deque[t++] = r;',
    '            ans[l] = arr[deque[h]]; // 队头即为窗口最大值',
    '            if (deque[h] == l) {',
    '                h++; // 移出过期队头',
    '            }',
    '        }',
    '        return ans;',
    '    }',
    '}',
  ],
  cpp: [
    'class Solution {',
    'public:',
    '    vector<int> maxSlidingWindow(vector<int>& arr, int k) {',
    '        int n = arr.size();',
    '        deque<int> dq; // 存储数组下标',
    '        for (int i = 0; i < k - 1; i++) {',
    '            while (!dq.empty() && arr[dq.back()] <= arr[i]) {',
    '                dq.pop_back();',
    '            }',
    '            dq.push_back(i);',
    '        }',
    '        vector<int> ans;',
    '        for (int l = 0, r = k - 1; r < n; l++, r++) {',
    '            while (!dq.empty() && arr[dq.back()] <= arr[r]) {',
    '                dq.pop_back();',
    '            }',
    '            dq.push_back(r);',
    '            ans.push_back(arr[dq.front()]);',
    '            if (dq.front() == l) {',
    '                dq.pop_front();',
    '            }',
    '        }',
    '        return ans;',
    '    }',
    '};',
  ],
  python: [
    'from collections import deque',
    '',
    'class Solution:',
    '    def maxSlidingWindow(self, arr: list[int], k: int) -> list[int]:',
    '        n = len(arr)',
    '        dq = deque()  # 存放下标',
    '        for i in range(k - 1):',
    '            while dq and arr[dq[-1]] <= arr[i]:',
    '                dq.pop()',
    '            dq.append(i)',
    '        ans = []',
    '        for l, r in zip(range(n - k + 1), range(k - 1, n)):',
    '            while dq and arr[dq[-1]] <= arr[r]:',
    '                dq.pop()',
    '            dq.append(r)',
    '            ans.append(arr[dq[0]])  # 队头最大',
    '            if dq[0] == l:',
    '                dq.popleft()  # 过期弹出',
    '        return ans',
  ],
  javascript: [
    'function maxSlidingWindow(arr, k) {',
    '    const n = arr.length;',
    '    const dq = []; // 模拟双端队列存放下标',
    '    for (let i = 0; i < k - 1; i++) {',
    '        while (dq.length > 0 && arr[dq[dq.length - 1]] <= arr[i]) {',
    '            dq.pop();',
    '        }',
    '        dq.push(i);',
    '    }',
    '    const ans = [];',
    '    for (let l = 0, r = k - 1; r < n; l++, r++) {',
    '        while (dq.length > 0 && arr[dq[dq.length - 1]] <= arr[r]) {',
    '            dq.pop();',
    '        }',
    '        dq.push(r);',
    '        ans.push(arr[dq[0]]);',
    '        if (dq[0] === l) {',
    '            dq.shift();',
    '        }',
    '    }',
    '    return ans;',
    '}',
  ],
};

export const CODE01_SLIDING_WINDOW_LINES: Record<string, CodeMapping> = {
  entry:       { java: 6, cpp: 3, python: 4, javascript: 1 },
  initPre:     { java: 10, cpp: 6, python: 7, javascript: 4 },
  popBackPre:  { java: 12, cpp: 8, python: 9, javascript: 6 },
  pushPre:     { java: 14, cpp: 10, python: 10, javascript: 8 },
  slideLoop:   { java: 19, cpp: 13, python: 12, javascript: 11 },
  popBackCur:  { java: 21, cpp: 15, python: 14, javascript: 13 },
  pushCur:     { java: 23, cpp: 17, python: 15, javascript: 15 },
  recordMax:   { java: 24, cpp: 18, python: 16, javascript: 16 },
  popExpired:  { java: 26, cpp: 20, python: 18, javascript: 18 },
  returnAns:   { java: 29, cpp: 23, python: 19, javascript: 21 },
};

// -------------------------------------------------------------
// Code02: 绝对差不超过限制的最长连续子数组 (Longest Subarray with Limit)
// -------------------------------------------------------------
export const CODE02_LONGEST_SUBARRAY_CODES: Record<string, string[]> = {
  java: [
    'public class LongestSubarrayAbsoluteLimit {',
    '    public static int MAXN = 100001;',
    '    public static int[] maxDeque = new int[MAXN];',
    '    public static int[] minDeque = new int[MAXN];',
    '    public static int maxh, maxt, minh, mint;',
    '    ',
    '    public static int longestSubarray(int[] nums, int limit) {',
    '        maxh = maxt = minh = mint = 0;',
    '        int n = nums.length, ans = 0;',
    '        for (int l = 0, r = 0; l < n; l++) {',
    '            while (r < n && ok(nums, limit, nums[r])) {',
    '                push(nums, r++);',
    '            }',
    '            ans = Math.max(ans, r - l);',
    '            pop(l);',
    '        }',
    '        return ans;',
    '    }',
    '    private static boolean ok(int[] nums, int limit, int num) {',
    '        int max = maxh < maxt ? Math.max(nums[maxDeque[maxh]], num) : num;',
    '        int min = minh < mint ? Math.min(nums[minDeque[minh]], num) : num;',
    '        return max - min <= limit;',
    '    }',
    '    private static void push(int[] nums, int r) {',
    '        while (maxh < maxt && nums[maxDeque[maxt - 1]] <= nums[r]) maxt--;',
    '        maxDeque[maxt++] = r;',
    '        while (minh < mint && nums[minDeque[mint - 1]] >= nums[r]) mint--;',
    '        minDeque[mint++] = r;',
    '    }',
    '    private static void pop(int l) {',
    '        if (maxh < maxt && maxDeque[maxh] == l) maxh++;',
    '        if (minh < mint && minDeque[minh] == l) minh++;',
    '    }',
    '}',
  ],
  cpp: [
    'class Solution {',
    'public:',
    '    int longestSubarray(vector<int>& nums, int limit) {',
    '        deque<int> maxQ, minQ;',
    '        int n = nums.size(), ans = 0;',
    '        for (int l = 0, r = 0; l < n; l++) {',
    '            while (r < n) {',
    '                int maxV = maxQ.empty() ? nums[r] : max(nums[maxQ.front()], nums[r]);',
    '                int minV = minQ.empty() ? nums[r] : min(nums[minQ.front()], nums[r]);',
    '                if (maxV - minV > limit) break;',
    '                while (!maxQ.empty() && nums[maxQ.back()] <= nums[r]) maxQ.pop_back();',
    '                maxQ.push_back(r);',
    '                while (!minQ.empty() && nums[minQ.back()] >= nums[r]) minQ.pop_back();',
    '                minQ.push_back(r++);',
    '            }',
    '            ans = max(ans, r - l);',
    '            if (!maxQ.empty() && maxQ.front() == l) maxQ.pop_front();',
    '            if (!minQ.empty() && minQ.front() == l) minQ.pop_front();',
    '        }',
    '        return ans;',
    '    }',
    '};',
  ],
  python: [
    'from collections import deque',
    '',
    'class Solution:',
    '    def longestSubarray(self, nums: list[int], limit: int) -> int:',
    '        max_q, min_q = deque(), deque()',
    '        n, ans, r = len(nums), 0, 0',
    '        for l in range(n):',
    '            while r < n:',
    '                max_v = max(nums[max_q[0]], nums[r]) if max_q else nums[r]',
    '                min_v = min(nums[min_q[0]], nums[r]) if min_q else nums[r]',
    '                if max_v - min_v > limit:',
    '                    break',
    '                while max_q and nums[max_q[-1]] <= nums[r]:',
    '                    max_q.pop()',
    '                max_q.append(r)',
    '                while min_q and nums[min_q[-1]] >= nums[r]:',
    '                    min_q.pop()',
    '                min_q.append(r)',
    '                r += 1',
    '            ans = max(ans, r - l)',
    '            if max_q and max_q[0] == l:',
    '                max_q.popleft()',
    '            if min_q and min_q[0] == l:',
    '                min_q.popleft()',
    '        return ans',
  ],
  javascript: [
    'function longestSubarray(nums, limit) {',
    '    const maxQ = [], minQ = [];',
    '    const n = nums.length;',
    '    let ans = 0, r = 0;',
    '    for (let l = 0; l < n; l++) {',
    '        while (r < n) {',
    '            const maxV = maxQ.length ? Math.max(nums[maxQ[0]], nums[r]) : nums[r];',
    '            const minV = minQ.length ? Math.min(nums[minQ[0]], nums[r]) : nums[r];',
    '            if (maxV - minV > limit) break;',
    '            while (maxQ.length && nums[maxQ[maxQ.length - 1]] <= nums[r]) maxQ.pop();',
    '            maxQ.push(r);',
    '            while (minQ.length && nums[minQ[minQ.length - 1]] >= nums[r]) minQ.pop();',
    '            minQ.push(r++);',
    '        }',
    '        ans = Math.max(ans, r - l);',
    '        if (maxQ.length && maxQ[0] === l) maxQ.shift();',
    '        if (minQ.length && minQ[0] === l) minQ.shift();',
    '    }',
    '    return ans;',
    '}',
  ],
};

export const CODE02_LONGEST_SUBARRAY_LINES: Record<string, CodeMapping> = {
  entry:      { java: 7, cpp: 3, python: 4, javascript: 1 },
  loopL:      { java: 10, cpp: 6, python: 7, javascript: 5 },
  checkOk:    { java: 11, cpp: 10, python: 11, javascript: 9 },
  pushR:      { java: 12, cpp: 14, python: 19, javascript: 13 },
  updateAns:  { java: 14, cpp: 16, python: 20, javascript: 15 },
  popL:       { java: 15, cpp: 18, python: 22, javascript: 17 },
  returnAns:  { java: 17, cpp: 20, python: 25, javascript: 19 },
};

// -------------------------------------------------------------
// Code03: 接取落水的最小花盆 (Falling Water Flowerpot)
// -------------------------------------------------------------
export const CODE03_FLOWER_POT_CODES: Record<string, string[]> = {
  java: [
    'import java.util.Arrays;',
    '',
    'public class FallingWaterFlowerpot {',
    '    public static int minFlowerpot(int[][] arr, int d) {',
    '        int n = arr.length;',
    '        // 1. 水滴按 x 坐标升序排列',
    '        Arrays.sort(arr, (a, b) -> a[0] - b[0]);',
    '        int[] maxQ = new int[n], minQ = new int[n];',
    '        int maxh = 0, maxt = 0, minh = 0, mint = 0;',
    '        int ans = Integer.MAX_VALUE;',
    '        // 2. 双指针维护花盆宽度 [arr[l][0] .. arr[r-1][0]]',
    '        for (int l = 0, r = 0; l < n; l++) {',
    '            while (r < n && (maxh == maxt || arr[maxQ[maxh]][1] - arr[minQ[minh]][1] < d)) {',
    '                while (maxh < maxt && arr[maxQ[maxt - 1]][1] <= arr[r][1]) maxt--;',
    '                maxQ[maxt++] = r;',
    '                while (minh < mint && arr[minQ[mint - 1]][1] >= arr[r][1]) mint--;',
    '                minQ[mint++] = r++;',
    '            }',
    '            if (arr[maxQ[maxh]][1] - arr[minQ[minh]][1] >= d) {',
    '                ans = Math.min(ans, arr[r - 1][0] - arr[l][0]);',
    '            }',
    '            if (maxQ[maxh] == l) maxh++;',
    '            if (minQ[minh] == l) minh++;',
    '        }',
    '        return ans == Integer.MAX_VALUE ? -1 : ans;',
    '    }',
    '}',
  ],
  cpp: [
    '#include <vector>',
    '#include <deque>',
    '#include <algorithm>',
    'using namespace std;',
    '',
    'int minFlowerpot(vector<pair<int, int>>& arr, int d) {',
    '    sort(arr.begin(), arr.end()); // 按 x 坐标升序',
    '    deque<int> maxQ, minQ;',
    '    int n = arr.size(), ans = 1e9;',
    '    for (int l = 0, r = 0; l < n; l++) {',
    '        while (r < n && (maxQ.empty() || arr[maxQ.front()].second - arr[minQ.front()].second < d)) {',
    '            while (!maxQ.empty() && arr[maxQ.back()].second <= arr[r].second) maxQ.pop_back();',
    '            maxQ.push_back(r);',
    '            while (!minQ.empty() && arr[minQ.back()].second >= arr[r].second) minQ.pop_back();',
    '            minQ.push_back(r++);',
    '        }',
    '        if (arr[maxQ.front()].second - arr[minQ.front()].second >= d) {',
    '            ans = min(ans, arr[r - 1].first - arr[l].first);',
    '        }',
    '        if (!maxQ.empty() && maxQ.front() == l) maxQ.pop_front();',
    '        if (!minQ.empty() && minQ.front() == l) minQ.pop_front();',
    '    }',
    '    return ans == 1e9 ? -1 : ans;',
    '}',
  ],
  python: [
    'from collections import deque',
    '',
    'def min_flowerpot(arr: list[list[int]], d: int) -> int:',
    '    # 按照 x 坐标升序排序',
    '    arr.sort(key=lambda p: p[0])',
    '    n = len(arr)',
    '    max_q, min_q = deque(), deque()',
    '    ans = float("inf")',
    '    r = 0',
    '    for l in range(n):',
    '        while r < n and (not max_q or arr[max_q[0]][1] - arr[min_q[0]][1] < d):',
    '            while max_q and arr[max_q[-1]][1] <= arr[r][1]:',
    '                max_q.pop()',
    '            max_q.append(r)',
    '            while min_q and arr[min_q[-1]][1] >= arr[r][1]:',
    '                min_q.pop()',
    '            min_q.append(r)',
    '            r += 1',
    '        if max_q and arr[max_q[0]][1] - arr[min_q[0]][1] >= d:',
    '            ans = min(ans, arr[r - 1][0] - arr[l][0])',
    '        if max_q and max_q[0] == l:',
    '            max_q.popleft()',
    '        if min_q and min_q[0] == l:',
    '            min_q.popleft()',
    '    return -1 if ans == float("inf") else ans',
  ],
  javascript: [
    'function minFlowerpot(arr, d) {',
    '    // 按 x 升序排序',
    '    arr.sort((a, b) => a[0] - b[0]);',
    '    const n = arr.length;',
    '    const maxQ = [], minQ = [];',
    '    let ans = Infinity, r = 0;',
    '    for (let l = 0; l < n; l++) {',
    '        while (r < n && (maxQ.length === 0 || arr[maxQ[0]][1] - arr[minQ[0]][1] < d)) {',
    '            while (maxQ.length && arr[maxQ[maxQ.length - 1]][1] <= arr[r][1]) maxQ.pop();',
    '            maxQ.push(r);',
    '            while (minQ.length && arr[minQ[minQ.length - 1]][1] >= arr[r][1]) minQ.pop();',
    '            minQ.push(r++);',
    '        }',
    '        if (maxQ.length && arr[maxQ[0]][1] - arr[minQ[0]][1] >= d) {',
    '            ans = Math.min(ans, arr[r - 1][0] - arr[l][0]);',
    '        }',
    '        if (maxQ.length && maxQ[0] === l) maxQ.shift();',
    '        if (minQ.length && minQ[0] === l) minQ.shift();',
    '    }',
    '    return ans === Infinity ? -1 : ans;',
    '}',
  ],
};

export const CODE03_FLOWER_POT_LINES: Record<string, CodeMapping> = {
  entry:       { java: 4, cpp: 6, python: 3, javascript: 1 },
  sortPoints:  { java: 7, cpp: 7, python: 5, javascript: 3 },
  loopL:       { java: 12, cpp: 10, python: 9, javascript: 7 },
  expandR:     { java: 14, cpp: 12, python: 11, javascript: 9 },
  checkOk:     { java: 19, cpp: 17, python: 19, javascript: 15 },
  updateAns:   { java: 20, cpp: 18, python: 20, javascript: 16 },
  popL:        { java: 22, cpp: 20, python: 22, javascript: 18 },
  returnAns:   { java: 25, cpp: 23, python: 25, javascript: 21 },
};
