/**
 * 左神算法通关课 第 047 & 048 课 - 一维差分与二维差分代码与相对行号映射
 */

// 1. 一维差分
export const DIFF_1D_CODES: Record<string, string[]> = {
  java: [
    'public class Difference1D {',
    '    public static int[] corpFlightBookings(int[][] bookings, int n) {',
    '        int[] diff = new int[n + 2];',
    '        for (int[] b : bookings) {',
    '            diff[b[0]] += b[2];',
    '            diff[b[1] + 1] -= b[2];',
    '        }',
    '        int[] ans = new int[n];',
    '        ans[0] = diff[1];',
    '        for (int i = 1; i < n; i++) {',
    '            ans[i] = ans[i - 1] + diff[i + 1];',
    '        }',
    '        return ans;',
    '    }',
    '}',
  ],
  cpp: [
    'vector<int> corpFlightBookings(vector<vector<int>>& bookings, int n) {',
    '    vector<int> diff(n + 2, 0);',
    '    for (auto& b : bookings) {',
    '        diff[b[0]] += b[2];',
    '        diff[b[1] + 1] -= b[2];',
    '    }',
    '    vector<int> ans(n);',
    '    ans[0] = diff[1];',
    '    for (int i = 1; i < n; i++) {',
    '        ans[i] = ans[i - 1] + diff[i + 1];',
    '    }',
    '    return ans;',
    '}',
  ],
  python: [
    'def corp_flight_bookings(bookings: list[list[int]], n: int) -> list[int]:',
    '    diff = [0] * (n + 2)',
    '    for l, r, val in bookings:',
    '        diff[l] += val',
    '        diff[r + 1] -= val',
    '    ans = [0] * n',
    '    ans[0] = diff[1]',
    '    for i in range(1, n):',
    '        ans[i] = ans[i - 1] + diff[i + 1]',
    '    return ans',
  ],
  javascript: [
    'function corpFlightBookings(bookings, n) {',
    '    const diff = new Array(n + 2).fill(0);',
    '    for (const [l, r, val] of bookings) {',
    '        diff[l] += val;',
    '        diff[r + 1] -= val;',
    '    }',
    '    const ans = new Array(n).fill(0);',
    '    ans[0] = diff[1];',
    '    for (let i = 1; i < n; i++) {',
    '        ans[i] = ans[i - 1] + diff[i + 1];',
    '    }',
    '    return ans;',
    '}',
  ],
};

export const DIFF_1D_LINES = {
  entry: { java: 2, cpp: 1, python: 1, javascript: 1 },
  initDiff: { java: 3, cpp: 2, python: 2, javascript: 2 },
  updateLoop: { java: 4, cpp: 3, python: 3, javascript: 3 },
  applyAdd: { java: 5, cpp: 4, python: 4, javascript: 4 },
  applySub: { java: 6, cpp: 5, python: 5, javascript: 5 },
  initAns: { java: 9, cpp: 8, python: 7, javascript: 8 },
  prefixScan: { java: 11, cpp: 10, python: 9, javascript: 10 },
  returnAns: { java: 13, cpp: 12, python: 10, javascript: 12 },
};

// 2. 二维差分
export const DIFF_2D_CODES: Record<string, string[]> = {
  java: [
    'public class Difference2D {',
    '    public static int[][] solve(int[][] ops, int n, int m) {',
    '        int[][] diff = new int[n + 2][m + 2];',
    '        for (int[] op : ops) {',
    '            int x1 = op[0], y1 = op[1], x2 = op[2], y2 = op[3], val = op[4];',
    '            diff[x1][y1] += val;',
    '            diff[x2 + 1][y1] -= val;',
    '            diff[x1][y2 + 1] -= val;',
    '            diff[x2 + 1][y2 + 1] += val;',
    '        }',
    '        int[][] ans = new int[n + 1][m + 1];',
    '        for (int i = 1; i <= n; i++) {',
    '            for (int j = 1; j <= m; j++) {',
    '                ans[i][j] = ans[i - 1][j] + ans[i][j - 1] - ans[i - 1][j - 1] + diff[i][j];',
    '            }',
    '        }',
    '        return ans;',
    '    }',
    '}',
  ],
  cpp: [
    'vector<vector<int>> solve(vector<vector<int>>& ops, int n, int m) {',
    '    vector<vector<int>> diff(n + 2, vector<int>(m + 2, 0));',
    '    for (auto& op : ops) {',
    '        int x1 = op[0], y1 = op[1], x2 = op[2], y2 = op[3], val = op[4];',
    '        diff[x1][y1] += val;',
    '        diff[x2 + 1][y1] -= val;',
    '        diff[x1][y2 + 1] -= val;',
    '        diff[x2 + 1][y2 + 1] += val;',
    '    }',
    '    vector<vector<int>> ans(n + 1, vector<int>(m + 1, 0));',
    '    for (int i = 1; i <= n; i++) {',
    '        for (int j = 1; j <= m; j++) {',
    '            ans[i][j] = ans[i - 1][j] + ans[i][j - 1] - ans[i - 1][j - 1] + diff[i][j];',
    '        }',
    '    }',
    '    return ans;',
    '}',
  ],
  python: [
    'def solve_diff2d(ops: list[list[int]], n: int, m: int) -> list[list[int]]:',
    '    diff = [[0] * (m + 2) for _ in range(n + 2)]',
    '    for x1, y1, x2, y2, val in ops:',
    '        diff[x1][y1] += val',
    '        diff[x2 + 1][y1] -= val',
    '        diff[x1][y2 + 1] -= val',
    '        diff[x2 + 1][y2 + 1] += val',
    '    ans = [[0] * (m + 1) for _ in range(n + 1)]',
    '    for i in range(1, n + 1):',
    '        for j in range(1, m + 1):',
    '            ans[i][j] = ans[i - 1][j] + ans[i][j - 1] - ans[i - 1][j - 1] + diff[i][j]',
    '    return ans',
  ],
  javascript: [
    'function solveDiff2D(ops, n, m) {',
    '    const diff = Array.from({ length: n + 2 }, () => new Array(m + 2).fill(0));',
    '    for (const [x1, y1, x2, y2, val] of ops) {',
    '        diff[x1][y1] += val;',
    '        diff[x2 + 1][y1] -= val;',
    '        diff[x1][y2 + 1] -= val;',
    '        diff[x2 + 1][y2 + 1] += val;',
    '    }',
    '    const ans = Array.from({ length: n + 1 }, () => new Array(m + 1).fill(0));',
    '    for (let i = 1; i <= n; i++) {',
    '        for (let j = 1; j <= m; j++) {',
    '            ans[i][j] = ans[i - 1][j] + ans[i][j - 1] - ans[i - 1][j - 1] + diff[i][j];',
    '        }',
    '    }',
    '    return ans;',
    '}',
  ],
};

export const DIFF_2D_LINES = {
  entry: { java: 2, cpp: 1, python: 1, javascript: 1 },
  initDiff: { java: 3, cpp: 2, python: 2, javascript: 2 },
  updateCorners: { java: 6, cpp: 5, python: 4, javascript: 5 },
  initAns: { java: 11, cpp: 10, python: 8, javascript: 10 },
  prefix2D: { java: 14, cpp: 13, python: 11, javascript: 13 },
  returnAns: { java: 16, cpp: 15, python: 12, javascript: 15 },
};
