/**
 * 第 90 课：左神贪心算法专题 2 - 四语言代码与 1-based 行号映射定义
 * 覆盖 6 道题目全部 3 阶段 (共 18 组独立代码映射)
 */

// ==========================================
// Code01: 砍竹子 II (剪绳子 II)
// ==========================================

export const CUTTING_BAMBOO_STAGE1_CODES: Record<string, string[]> = {
  java: [
    'public class CuttingBambooDFS {',
    '    // 阶段1: 暴力分割DFS',
    '    public static int maxProduct(int n) {',
    '        if (n <= 3) return n - 1;',
    '        return dfs(n);',
    '    }',
    '    private static int dfs(int rest) {',
    '        if (rest <= 4) return rest;',
    '        int max = 0;',
    '        for (int i = 1; i < rest; i++) {',
    '            max = Math.max(max, i * dfs(rest - i));',
    '        }',
    '        return max;',
    '    }',
    '}',
  ],
  cpp: [
    'class CuttingBambooDFS {',
    'public:',
    '    int maxProduct(int n) {',
    '        if (n <= 3) return n - 1;',
    '        return dfs(n);',
    '    }',
    'private:',
    '    int dfs(int rest) {',
    '        if (rest <= 4) return rest;',
    '        int res = 0;',
    '        for (int i = 1; i < rest; i++) {',
    '            res = max(res, i * dfs(rest - i));',
    '        }',
    '        return res;',
    '    }',
    '};',
  ],
  python: [
    'class CuttingBambooDFS:',
    '    def maxProduct(self, n: int) -> int:',
    '        if n <= 3:',
    '            return n - 1',
    '        def dfs(rest):',
    '            if rest <= 4:',
    '                return rest',
    '            res = 0',
    '            for i in range(1, rest):',
    '                res = max(res, i * dfs(rest - i))',
    '            return res',
    '        return dfs(n)',
  ],
  javascript: [
    'function cuttingBambooDFS(n) {',
    '  if (n <= 3) return n - 1;',
    '  function dfs(rest) {',
    '    if (rest <= 4) return rest;',
    '    let max = 0;',
    '    for (let i = 1; i < rest; i++) {',
    '      max = Math.max(max, i * dfs(rest - i));',
    '    }',
    '    return max;',
    '  }',
    '  return dfs(n);',
    '}',
  ],
};

export const CUTTING_BAMBOO_STAGE1_LINES: Record<string, Record<string, number>> = {
  java: { init: 4, dfs: 7, base: 8, loop: 10, pick: 11, ret: 13 },
  cpp: { init: 4, dfs: 8, base: 9, loop: 11, pick: 12, ret: 14 },
  python: { init: 3, dfs: 5, base: 6, loop: 9, pick: 10, ret: 11 },
  javascript: { init: 2, dfs: 3, base: 4, loop: 6, pick: 7, ret: 9 },
};

export const CUTTING_BAMBOO_STAGE2_CODES: Record<string, string[]> = {
  java: [
    'public class CuttingBambooGreedy {',
    '    private static final int MOD = 1000000007;',
    '    public static int cuttingBamboo(int n) {',
    '        if (n == 2) return 1;',
    '        if (n == 3) return 2;',
    '        long ans = 1;',
    '        int rem = n % 3;',
    '        int m = n / 3;',
    '        if (rem == 1) { m -= 1; ans = 4; }',
    '        else if (rem == 2) { ans = 2; }',
    '        ans = (ans * power(3, m, MOD)) % MOD;',
    '        return (int) ans;',
    '    }',
    '    private static long power(long base, int exp, int mod) {',
    '        long res = 1;',
    '        while (exp > 0) {',
    '            if ((exp & 1) == 1) res = (res * base) % mod;',
    '            base = (base * base) % mod;',
    '            exp >>= 1;',
    '        }',
    '        return res;',
    '    }',
    '}',
  ],
  cpp: [
    'class CuttingBambooGreedy {',
    '    const int MOD = 1000000007;',
    'public:',
    '    int cuttingBamboo(int n) {',
    '        if (n == 2) return 1;',
    '        if (n == 3) return 2;',
    '        long long ans = 1;',
    '        int rem = n % 3, m = n / 3;',
    '        if (rem == 1) { m -= 1; ans = 4; }',
    '        else if (rem == 2) { ans = 2; }',
    '        ans = (ans * power(3, m, MOD)) % MOD;',
    '        return ans;',
    '    }',
    'private:',
    '    long long power(long long base, int exp, int mod) {',
    '        long long res = 1;',
    '        while (exp > 0) {',
    '            if (exp & 1) res = (res * base) % mod;',
    '            base = (base * base) % mod;',
    '            exp >>= 1;',
    '        }',
    '        return res;',
    '    }',
    '};',
  ],
  python: [
    'class CuttingBambooGreedy:',
    '    def cuttingBamboo(self, n: int) -> int:',
    '        MOD = 10**9 + 7',
    '        if n == 2: return 1',
    '        if n == 3: return 2',
    '        rem, m = n % 3, n // 3',
    '        ans = 1',
    '        if rem == 1:',
    '            m -= 1; ans = 4',
    '        elif rem == 2:',
    '            ans = 2',
    '        ans = (ans * pow(3, m, MOD)) % MOD',
    '        return ans',
  ],
  javascript: [
    'function cuttingBambooGreedy(n) {',
    '  const MOD = 1000000007n;',
    '  if (n === 2) return 1;',
    '  if (n === 3) return 2;',
    '  let m = Math.floor(n / 3);',
    '  const rem = n % 3;',
    '  let ans = 1n;',
    '  if (rem === 1) { m -= 1; ans = 4n; }',
    '  else if (rem === 2) { ans = 2n; }',
    '  let base = 3n, exp = BigInt(m);',
    '  while (exp > 0n) {',
    '    if (exp & 1n) ans = (ans * base) % MOD;',
    '    base = (base * base) % MOD;',
    '    exp >>= 1n;',
    '  }',
    '  return Number(ans);',
    '}',
  ],
};

export const CUTTING_BAMBOO_STAGE2_LINES: Record<string, Record<string, number>> = {
  java: { check2: 4, check3: 5, mod3: 7, rem1: 9, rem2: 10, pow: 11, ret: 12 },
  cpp: { check2: 5, check3: 6, mod3: 8, rem1: 9, rem2: 10, pow: 11, ret: 12 },
  python: { check2: 4, check3: 5, mod3: 6, rem1: 8, rem2: 10, pow: 12, ret: 13 },
  javascript: { check2: 3, check3: 4, mod3: 6, rem1: 8, rem2: 9, pow: 12, ret: 16 },
};

export const CUTTING_BAMBOO_STAGE3_CODES: Record<string, string[]> = {
  java: [
    '// 阶段3: 导数与连续极值反证法',
    '// 目标: 拆成 m 份使得 (n/m)^m 最大',
    '// 等价于求 f(x) = x^(1/x) 的极值点',
    '// 求导: f\'(x) = x^(1/x) * (1 - ln x) / x^2',
    '// 极值点: 1 - ln x = 0 => x = e ≈ 2.71828',
    '// 离散整数中距离 e 最近的是 3, 其次是 2',
    '// 代数验证: 3^2 = 9 > 2^3 = 8',
    'public class CuttingBambooProof {',
    '    public static void verify() {',
    '        assert Math.pow(3, 2) > Math.pow(2, 3);',
    '    }',
    '}',
  ],
  cpp: [
    '// 阶段3: 导数与连续极值反证法',
    '// f(x) = x^(1/x) 在 x = e 处导数为 0 取得全局最大值',
    '// 离散整数中 f(3) = 3^(1/3) ≈ 1.442 > f(2) = 2^(1/2) ≈ 1.414',
    '// 故在正整数域中优先拆成 3 最优, 其次是 2',
    'struct CuttingBambooProof {',
    '    static void verify() {',
    '        // 3^2 > 2^3',
    '    }',
    '};',
  ],
  python: [
    '# 阶段3: 导数极值与均值不等式反证',
    '# 对 f(x) = x^(1/x) 求导可得驻点 x = e ≈ 2.718',
    '# 整数中 f(3) ≈ 1.4422 > f(2) ≈ 1.4142 > f(4) = 1.4142',
    '# 故优先拆成 3 为全局唯一最优整数贪心选择',
    'def verify_proof():',
    '    pass',
  ],
  javascript: [
    '// 阶段3: 导数连续极值反证法',
    '// f(x) = x^(1/x) 在驻点 x = e ≈ 2.718 取到全局最大值',
    '// 离散整数候选集: f(3) > f(2) > f(4) > f(1)',
    '// 故尽力拆 3 为全局最优策略',
    'function verifyProof() {}',
  ],
};

export const CUTTING_BAMBOO_STAGE3_LINES: Record<string, Record<string, number>> = {
  java: { intro: 2, deriv: 4, solve: 5, comp: 7, verify: 10 },
  cpp: { intro: 2, deriv: 3, solve: 4, comp: 6, verify: 7 },
  python: { intro: 2, deriv: 3, solve: 4, comp: 5, verify: 6 },
  javascript: { intro: 2, deriv: 3, solve: 4, comp: 5, verify: 5 },
};

// ==========================================
// Code02: 分成 k 份的最大乘积
// ==========================================

export const MAX_PRODUCT_K_STAGE1_CODES: Record<string, string[]> = {
  java: [
    'public class MaxProductKPartsDFS {',
    '    // 阶段1: 暴力分割枚举DFS',
    '    public static int maxProduct(int n, int k) {',
    '        return dfs(n, k);',
    '    }',
    '    private static int dfs(int rest, int partsLeft) {',
    '        if (partsLeft == 1) return rest;',
    '        int max = 0;',
    '        for (int cur = 1; cur <= rest - partsLeft + 1; cur++) {',
    '            max = Math.max(max, cur * dfs(rest - cur, partsLeft - 1));',
    '        }',
    '        return max;',
    '    }',
    '}',
  ],
  cpp: [
    'class MaxProductKPartsDFS {',
    'public:',
    '    int maxProduct(int n, int k) {',
    '        return dfs(n, k);',
    '    }',
    'private:',
    '    int dfs(int rest, int partsLeft) {',
    '        if (partsLeft == 1) return rest;',
    '        int res = 0;',
    '        for (int cur = 1; cur <= rest - partsLeft + 1; ++cur) {',
    '            res = max(res, cur * dfs(rest - cur, partsLeft - 1));',
    '        }',
    '        return res;',
    '    }',
    '};',
  ],
  python: [
    'class MaxProductKPartsDFS:',
    '    def maxProduct(self, n: int, k: int) -> int:',
    '        def dfs(rest, parts):',
    '            if parts == 1: return rest',
    '            res = 0',
    '            for cur in range(1, rest - parts + 2):',
    '                res = max(res, cur * dfs(rest - cur, parts - 1))',
    '            return res',
    '        return dfs(n, k)',
  ],
  javascript: [
    'function maxProductKPartsDFS(n, k) {',
    '  function dfs(rest, parts) {',
    '    if (parts === 1) return rest;',
    '    let max = 0;',
    '    for (let cur = 1; cur <= rest - parts + 1; cur++) {',
    '      max = Math.max(max, cur * dfs(rest - cur, parts - 1));',
    '    }',
    '    return max;',
    '  }',
    '  return dfs(n, k);',
    '}',
  ],
};

export const MAX_PRODUCT_K_STAGE1_LINES: Record<string, Record<string, number>> = {
  java: { init: 4, dfs: 6, base: 7, loop: 9, pick: 10, ret: 12 },
  cpp: { init: 4, dfs: 7, base: 8, loop: 10, pick: 11, ret: 13 },
  python: { init: 3, dfs: 4, base: 4, loop: 6, pick: 7, ret: 9 },
  javascript: { init: 2, dfs: 2, base: 3, loop: 5, pick: 6, ret: 10 },
};

export const MAX_PRODUCT_K_STAGE2_CODES: Record<string, string[]> = {
  java: [
    'public class MaxProductKPartsGreedy {',
    '    private static final int MOD = 1000000007;',
    '    public static int maxValue(long n, long k) {',
    '        long a = n / k;',
    '        long b = n % k;',
    '        long p1 = power(a + 1, b, MOD);',
    '        long p2 = power(a, k - b, MOD);',
    '        return (int) ((p1 * p2) % MOD);',
    '    }',
    '    private static long power(long x, long p, int mod) {',
    '        long ans = 1;',
    '        while (p > 0) {',
    '            if ((p & 1) == 1) ans = (ans * x) % mod;',
    '            x = (x * x) % mod;',
    '            p >>= 1;',
    '        }',
    '        return ans;',
    '    }',
    '}',
  ],
  cpp: [
    'class MaxProductKPartsGreedy {',
    '    const int MOD = 1000000007;',
    'public:',
    '    int maxValue(long long n, long long k) {',
    '        long long a = n / k;',
    '        long long b = n % k;',
    '        long long p1 = power(a + 1, b, MOD);',
    '        long long p2 = power(a, k - b, MOD);',
    '        return (p1 * p2) % MOD;',
    '    }',
    'private:',
    '    long long power(long long x, long long p, int mod) {',
    '        long long ans = 1;',
    '        while (p > 0) {',
    '            if (p & 1) ans = (ans * x) % mod;',
    '            x = (x * x) % mod;',
    '            p >>= 1;',
    '        }',
    '        return ans;',
    '    }',
    '};',
  ],
  python: [
    'class MaxProductKPartsGreedy:',
    '    def maxValue(self, n: int, k: int) -> int:',
    '        MOD = 10**9 + 7',
    '        a = n // k',
    '        b = n % k',
    '        p1 = pow(a + 1, b, MOD)',
    '        p2 = pow(a, k - b, MOD)',
    '        return (p1 * p2) % MOD',
  ],
  javascript: [
    'function maxProductKPartsGreedy(n, k) {',
    '  const MOD = 1000000007n;',
    '  const bigN = BigInt(n), bigK = BigInt(k);',
    '  const a = bigN / bigK;',
    '  const b = bigN % bigK;',
    '  function powMod(base, exp) {',
    '    let res = 1n;',
    '    while (exp > 0n) {',
    '      if (exp & 1n) res = (res * base) % MOD;',
    '      base = (base * base) % MOD;',
    '      exp >>= 1n;',
    '    }',
    '    return res;',
    '  }',
    '  const p1 = powMod(a + 1n, b);',
    '  const p2 = powMod(a, bigK - b);',
    '  return Number((p1 * p2) % MOD);',
    '}',
  ],
};

export const MAX_PRODUCT_K_STAGE2_LINES: Record<string, Record<string, number>> = {
  java: { div: 4, rem: 5, p1: 6, p2: 7, ret: 8 },
  cpp: { div: 5, rem: 6, p1: 7, p2: 8, ret: 9 },
  python: { div: 4, rem: 5, p1: 6, p2: 7, ret: 8 },
  javascript: { div: 4, rem: 5, p1: 16, p2: 17, ret: 18 },
};

export const MAX_PRODUCT_K_STAGE3_CODES: Record<string, string[]> = {
  java: [
    '// 阶段3: 极差反证法',
    '// 设存在两份 x 与 y 满足 x - y >= 2',
    '// 若将 x 减 1, y 加 1 (和保持不变):',
    '// 新乘积: (x - 1) * (y + 1) = xy + x - y - 1',
    '// 增量 Δ = (x - y) - 1 >= 2 - 1 = 1 > 0',
    '// 结论: 任意两数差距 >= 2 时, 靠近均值严格导致乘积增大',
    '// 故最优划分中任何两份的极差必 <= 1',
    'public class MaxProductKProof {}',
  ],
  cpp: [
    '// 阶段3: 极差反证证明',
    '// (x - 1)(y + 1) - xy = x - y - 1',
    '// 当 x - y >= 2 时, 差值严格 > 0',
    '// 任意极差 >= 2 的分配均非最优解',
    'struct MaxProductKProof {};',
  ],
  python: [
    '# 阶段3: 极差反证法证明',
    '# (x - 1)(y + 1) = xy + (x - y - 1)',
    '# 当 x - y >= 2 时, (x - y - 1) >= 1 > 0',
    '# 故均分使极差 <= 1 为唯一全局最优解',
    'pass',
  ],
  javascript: [
    '// 阶段3: 均值极差反证法',
    '// (x - 1)(y + 1) - xy = x - y - 1 >= 1 > 0 (当 x - y >= 2)',
    '// 证明完毕: 各份之间极差至多为 1',
    'function verifyKPartsProof() {}',
  ],
};

export const MAX_PRODUCT_K_STAGE3_LINES: Record<string, Record<string, number>> = {
  java: { intro: 2, diff: 4, delta: 5, conclusion: 7 },
  cpp: { intro: 2, diff: 2, delta: 3, conclusion: 4 },
  python: { intro: 2, diff: 2, delta: 3, conclusion: 4 },
  javascript: { intro: 2, diff: 2, delta: 3, conclusion: 3 },
};

// ==========================================
// Code03: 会议独占时间段的最大会议数量
// ==========================================

export const MEETING_MONOPOLY_STAGE1_CODES: Record<string, string[]> = {
  java: [
    'public class MeetingMonopolyDFS {',
    '    // 阶段1: 暴力组合穷举',
    '    public static int maxMeetings(int[][] intervals) {',
    '        return dfs(intervals, 0, -1);',
    '    }',
    '    private static int dfs(int[][] intervals, int idx, int lastEnd) {',
    '        if (idx == intervals.length) return 0;',
    '        int p1 = dfs(intervals, idx + 1, lastEnd); // 不选',
    '        int p2 = 0;',
    '        if (intervals[idx][0] >= lastEnd) {',
    '            p2 = 1 + dfs(intervals, idx + 1, intervals[idx][1]); // 选',
    '        }',
    '        return Math.max(p1, p2);',
    '    }',
    '}',
  ],
  cpp: [
    'class MeetingMonopolyDFS {',
    'public:',
    '    int maxMeetings(vector<vector<int>>& intervals) {',
    '        return dfs(intervals, 0, -1);',
    '    }',
    'private:',
    '    int dfs(const vector<vector<int>>& intervals, int idx, int lastEnd) {',
    '        if (idx == (int)intervals.size()) return 0;',
    '        int p1 = dfs(intervals, idx + 1, lastEnd);',
    '        int p2 = 0;',
    '        if (intervals[idx][0] >= lastEnd) {',
    '            p2 = 1 + dfs(intervals, idx + 1, intervals[idx][1]);',
    '        }',
    '        return max(p1, p2);',
    '    }',
    '};',
  ],
  python: [
    'class MeetingMonopolyDFS:',
    '    def maxMeetings(self, intervals: list[list[int]]) -> int:',
    '        def dfs(idx, lastEnd):',
    '            if idx == len(intervals): return 0',
    '            p1 = dfs(idx + 1, lastEnd)',
    '            p2 = 0',
    '            if intervals[idx][0] >= lastEnd:',
    '                p2 = 1 + dfs(idx + 1, intervals[idx][1])',
    '            return max(p1, p2)',
    '        return dfs(0, -1)',
  ],
  javascript: [
    'function meetingMonopolyDFS(intervals) {',
    '  function dfs(idx, lastEnd) {',
    '    if (idx === intervals.length) return 0;',
    '    const p1 = dfs(idx + 1, lastEnd);',
    '    let p2 = 0;',
    '    if (intervals[idx][0] >= lastEnd) {',
    '      p2 = 1 + dfs(idx + 1, intervals[idx][1]);',
    '    }',
    '    return Math.max(p1, p2);',
    '  }',
    '  return dfs(0, -1);',
    '}',
  ],
};

export const MEETING_MONOPOLY_STAGE1_LINES: Record<string, Record<string, number>> = {
  java: { init: 4, dfs: 6, skip: 8, check: 10, pick: 11, ret: 13 },
  cpp: { init: 4, dfs: 7, skip: 9, check: 11, pick: 12, ret: 14 },
  python: { init: 3, dfs: 4, skip: 5, check: 7, pick: 8, ret: 9 },
  javascript: { init: 2, dfs: 2, skip: 4, check: 6, pick: 7, ret: 9 },
};

export const MEETING_MONOPOLY_STAGE2_CODES: Record<string, string[]> = {
  java: [
    'import java.util.Arrays;',
    'public class MeetingMonopolyGreedy {',
    '    // 阶段2: 结束时间排序贪心 + 洛谷桶优化',
    '    public static int maxMeetings(int[][] intervals) {',
    '        Arrays.sort(intervals, (a, b) -> a[1] - b[1]);',
    '        int ans = 0, curEnd = Integer.MIN_VALUE;',
    '        for (int[] meet : intervals) {',
    '            if (meet[0] >= curEnd) {',
    '                ans++;',
    '                curEnd = meet[1];',
    '            }',
    '        }',
    '        return ans;',
    '    }',
    '}',
  ],
  cpp: [
    '#include <vector>',
    '#include <algorithm>',
    'using namespace std;',
    'class MeetingMonopolyGreedy {',
    'public:',
    '    int maxMeetings(vector<vector<int>>& intervals) {',
    '        sort(intervals.begin(), intervals.end(), [](const auto& a, const auto& b) {',
    '            return a[1] < b[1];',
    '        });',
    '        int ans = 0, curEnd = -1e9;',
    '        for (const auto& meet : intervals) {',
    '            if (meet[0] >= curEnd) {',
    '                ans++;',
    '                curEnd = meet[1];',
    '            }',
    '        }',
    '        return ans;',
    '    }',
    '};',
  ],
  python: [
    'class MeetingMonopolyGreedy:',
    '    def maxMeetings(self, intervals: list[list[int]]) -> int:',
    '        intervals.sort(key=lambda x: x[1])',
    '        ans = 0',
    '        curEnd = -10**9',
    '        for start, end in intervals:',
    '            if start >= curEnd:',
    '                ans += 1',
    '                curEnd = end',
    '        return ans',
  ],
  javascript: [
    'function meetingMonopolyGreedy(intervals) {',
    '  intervals.sort((a, b) => a[1] - b[1]);',
    '  let ans = 0, curEnd = -Infinity;',
    '  for (const [start, end] of intervals) {',
    '    if (start >= curEnd) {',
    '      ans++;',
    '      curEnd = end;',
    '    }',
    '  }',
    '  return ans;',
    '}',
  ],
};

export const MEETING_MONOPOLY_STAGE2_LINES: Record<string, Record<string, number>> = {
  java: { sort: 5, loop: 7, check: 8, pick: 9, update: 10, ret: 13 },
  cpp: { sort: 7, loop: 11, check: 12, pick: 13, update: 14, ret: 17 },
  python: { sort: 3, loop: 6, check: 7, pick: 8, update: 9, ret: 10 },
  javascript: { sort: 2, loop: 4, check: 5, pick: 6, update: 7, ret: 10 },
};

export const MEETING_MONOPOLY_STAGE3_CODES: Record<string, string[]> = {
  java: [
    '// 阶段3: 区间调度反证法',
    '// 设最优解为 OPT = {i1, i2, ..., ik}, 贪心解为 GREEDY = {g1, g2, ..., gm}',
    '// 归纳证明: 对任意 r, g_r.end <= i_r.end',
    '// 基础步骤: g1 是所有区间中 end 最小者, 显然 g1.end <= i1.end',
    '// 归纳步骤: 若 g_{r-1}.end <= i_{r-1}.end,',
    '// 则 i_r 可选 => i_r.start >= i_{r-1}.end >= g_{r-1}.end',
    '// 贪心算法在可选集中必挑 end 最小的 g_r, 故 g_r.end <= i_r.end',
    '// 结论: 贪心解永远不比最优解更晚结束, 必有 m >= k, 贪心即最优!',
    'public class MeetingMonopolyProof {}',
  ],
  cpp: [
    '// 阶段3: 最优子结构数学归纳反证',
    '// 归纳命题: g_r.end <= opt_r.end',
    '// 贪心每次挑选结束最早者, 留给后续区间的相容时间段严格 >= OPT',
    '// 故不可能存在一个合法解的区间数超过贪心解',
    'struct MeetingMonopolyProof {};',
  ],
  python: [
    '# 阶段3: 贪心相容反证法',
    '# 贪心解第 r 个区间的结束时刻永远 <= 任意可行解第 r 个区间的结束时刻',
    '# 留出的空余时间 [g_r.end, +∞) 严格包含可行解的空余时间',
    '# 故贪心容纳数量 m >= k, 贪心解全局最优',
    'pass',
  ],
  javascript: [
    '// 阶段3: 归纳置换反证法',
    '// 任意阶段贪心解 g_r 留给后续的时间裕度不劣于最优解 opt_r',
    '// 任何试图替换成更晚结束区间的做法都只会压缩后续选择空间',
    'function verifyMonopolyProof() {}',
  ],
};

export const MEETING_MONOPOLY_STAGE3_LINES: Record<string, Record<string, number>> = {
  java: { intro: 2, base: 4, step: 6, conclusion: 8 },
  cpp: { intro: 2, base: 2, step: 3, conclusion: 4 },
  python: { intro: 2, base: 2, step: 3, conclusion: 4 },
  javascript: { intro: 2, base: 2, step: 3, conclusion: 3 },
};

// ==========================================
// Code04: 会议只占一天的最大会议数量
// ==========================================

export const MEETING_ONE_DAY_STAGE1_CODES: Record<string, string[]> = {
  java: [
    'public class MeetingOneDayBrute {',
    '    // 阶段1: 暴力匹配枚举',
    '    public static int maxEvents(int[][] events) {',
    '        return dfs(events, 0, new boolean[events.length]);',
    '    }',
    '    private static int dfs(int[][] events, int day, boolean[] used) {',
    '        if (day > 100) return 0;',
    '        int max = dfs(events, day + 1, used); // 今天不参会',
    '        for (int i = 0; i < events.length; i++) {',
    '            if (!used[i] && events[i][0] <= day && day <= events[i][1]) {',
    '                used[i] = true;',
    '                max = Math.max(max, 1 + dfs(events, day + 1, used));',
    '                used[i] = false;',
    '            }',
    '        }',
    '        return max;',
    '    }',
    '}',
  ],
  cpp: [
    'class MeetingOneDayBrute {',
    'public:',
    '    int maxEvents(vector<vector<int>>& events) {',
    '        vector<bool> used(events.size(), false);',
    '        return dfs(events, 1, used);',
    '    }',
    'private:',
    '    int dfs(const vector<vector<int>>& events, int day, vector<bool>& used) {',
    '        if (day > 50) return 0;',
    '        int res = dfs(events, day + 1, used);',
    '        for (size_t i = 0; i < events.size(); ++i) {',
    '            if (!used[i] && events[i][0] <= day && day <= events[i][1]) {',
    '                used[i] = true;',
    '                res = max(res, 1 + dfs(events, day + 1, used));',
    '                used[i] = false;',
    '            }',
    '        }',
    '        return res;',
    '    }',
    '};',
  ],
  python: [
    'class MeetingOneDayBrute:',
    '    def maxEvents(self, events: list[list[int]]) -> int:',
    '        used = [False] * len(events)',
    '        def dfs(day):',
    '            if day > 50: return 0',
    '            res = dfs(day + 1)',
    '            for i in range(len(events)):',
    '                if not used[i] and events[i][0] <= day <= events[i][1]:',
    '                    used[i] = True',
    '                    res = max(res, 1 + dfs(day + 1))',
    '                    used[i] = False',
    '            return res',
    '        return dfs(1)',
  ],
  javascript: [
    'function meetingOneDayBrute(events) {',
    '  const used = new Array(events.length).fill(false);',
    '  function dfs(day) {',
    '    if (day > 50) return 0;',
    '    let max = dfs(day + 1);',
    '    for (let i = 0; i < events.length; i++) {',
    '      if (!used[i] && events[i][0] <= day && day <= events[i][1]) {',
    '        used[i] = true;',
    '        max = Math.max(max, 1 + dfs(day + 1));',
    '        used[i] = false;',
    '      }',
    '    }',
    '    return max;',
    '  }',
    '  return dfs(1);',
    '}',
  ],
};

export const MEETING_ONE_DAY_STAGE1_LINES: Record<string, Record<string, number>> = {
  java: { init: 4, dfs: 7, skip: 8, loop: 9, pick: 11, ret: 16 },
  cpp: { init: 5, dfs: 8, skip: 9, loop: 10, pick: 12, ret: 17 },
  python: { init: 3, dfs: 4, skip: 6, loop: 7, pick: 9, ret: 12 },
  javascript: { init: 2, dfs: 3, skip: 5, loop: 6, pick: 8, ret: 14 },
};

export const MEETING_ONE_DAY_STAGE2_CODES: Record<string, string[]> = {
  java: [
    'import java.util.*;',
    'public class MeetingOneDayGreedy {',
    '    public static int maxEvents(int[][] events) {',
    '        Arrays.sort(events, (a, b) -> a[0] - b[0]);',
    '        int n = events.length, maxDay = 0;',
    '        for (int[] e : events) maxDay = Math.max(maxDay, e[1]);',
    '        PriorityQueue<Integer> heap = new PriorityQueue<>();',
    '        int i = 0, ans = 0;',
    '        for (int day = 1; day <= maxDay; day++) {',
    '            while (i < n && events[i][0] == day) heap.add(events[i++][1]);',
    '            while (!heap.isEmpty() && heap.peek() < day) heap.poll();',
    '            if (!heap.isEmpty()) {',
    '                heap.poll();',
    '                ans++;',
    '            }',
    '        }',
    '        return ans;',
    '    }',
    '}',
  ],
  cpp: [
    '#include <vector>',
    '#include <algorithm>',
    '#include <queue>',
    'using namespace std;',
    'class MeetingOneDayGreedy {',
    'public:',
    '    int maxEvents(vector<vector<int>>& events) {',
    '        sort(events.begin(), events.end(), [](const auto& a, const auto& b) { return a[0] < b[0]; });',
    '        int n = events.size(), maxDay = 0;',
    '        for (const auto& e : events) maxDay = max(maxDay, e[1]);',
    '        priority_queue<int, vector<int>, greater<int>> heap;',
    '        int i = 0, ans = 0;',
    '        for (int day = 1; day <= maxDay; ++day) {',
    '            while (i < n && events[i][0] == day) heap.push(events[i++][1]);',
    '            while (!heap.empty() && heap.top() < day) heap.pop();',
    '            if (!heap.empty()) { heap.pop(); ans++; }',
    '        }',
    '        return ans;',
    '    }',
    '};',
  ],
  python: [
    'import heapq',
    'class MeetingOneDayGreedy:',
    '    def maxEvents(self, events: list[list[int]]) -> int:',
    '        events.sort(key=lambda x: x[0])',
    '        n = len(events)',
    '        maxDay = max(e[1] for e in events)',
    '        heap, i, ans = [], 0, 0',
    '        for day in range(1, maxDay + 1):',
    '            while i < n and events[i][0] == day:',
    '                heapq.heappush(heap, events[i][1]); i += 1',
    '            while heap and heap[0] < day:',
    '                heapq.heappop(heap)',
    '            if heap:',
    '                heapq.heappop(heap); ans += 1',
    '        return ans',
  ],
  javascript: [
    'function meetingOneDayGreedy(events) {',
    '  events.sort((a, b) => a[0] - b[0]);',
    '  const n = events.length;',
    '  let maxDay = 0;',
    '  for (const e of events) if (e[1] > maxDay) maxDay = e[1];',
    '  const heap = [];',
    '  function push(val) { heap.push(val); heap.sort((a, b) => a - b); }',
    '  let i = 0, ans = 0;',
    '  for (let day = 1; day <= maxDay; day++) {',
    '    while (i < n && events[i][0] === day) push(events[i++][1]);',
    '    while (heap.length > 0 && heap[0] < day) heap.shift();',
    '    if (heap.length > 0) { heap.shift(); ans++; }',
    '  }',
    '  return ans;',
    '}',
  ],
};

export const MEETING_ONE_DAY_STAGE2_LINES: Record<string, Record<string, number>> = {
  java: { sort: 4, loop: 9, addToday: 10, removeExpired: 11, attend: 13, ret: 17 },
  cpp: { sort: 8, loop: 13, addToday: 14, removeExpired: 15, attend: 16, ret: 18 },
  python: { sort: 4, loop: 8, addToday: 10, removeExpired: 12, attend: 14, ret: 15 },
  javascript: { sort: 2, loop: 9, addToday: 10, removeExpired: 11, attend: 12, ret: 14 },
};

export const MEETING_ONE_DAY_STAGE3_CODES: Record<string, string[]> = {
  java: [
    '// 阶段3: 早截止失效不可逆反证',
    '// 设今天为 day, 可选会议集合中存在 A(end=e_A) 与 B(end=e_B), 且 e_A < e_B',
    '// 贪心选择: 今天参加 A, 将 B 留到未来',
    '// 反证法: 假设今天参加 B, 将 A 留到未来',
    '// 考虑未来的任意一天 day\' > day:',
    '// 若可以在 day\' 参加 A, 则必有 day\' <= e_A < e_B => 同样必可在此日参加 B!',
    '// 但若 e_A < day\' <= e_B, 则 A 已经过期失效, 而 B 依然有效',
    '// 结论: 优先消费即将过期的 A, 无论如何都不会比优先消费 B 更差!',
    'public class MeetingOneDayProof {}',
  ],
  cpp: [
    '// 阶段3: 期限紧迫性拟序反证',
    '// 结束时间早的会议生存周期短, 延迟参加导致过期的概率严格更高',
    '// 结束时间晚的会议容忍度高, 留给未来的相容空间严格更大',
    '// 交换二者参加顺序无法获得任何正收益, 贪心解最优',
    'struct MeetingOneDayProof {};',
  ],
  python: [
    '# 阶段3: 失效单调性反证法',
    '# 会议 A 截止日 e_A < 会议 B 截止日 e_B',
    '# 今天消耗 A 是安全的, 将 B 留给明天相容区间更大',
    '# 若今天消耗 B 而留 A, A 极可能在明天过期造成名额净损失',
    'pass',
  ],
  javascript: [
    '// 阶段3: 早截止优先反证法',
    '// 设 e_A < e_B, 在时刻 t 参加 A 优于参加 B',
    '// 因为任何能参加 A 的未来日期必然能参加 B, 反之不成立',
    'function verifyOneDayProof() {}',
  ],
};

export const MEETING_ONE_DAY_STAGE3_LINES: Record<string, Record<string, number>> = {
  java: { intro: 2, greedy: 3, assume: 4, compare: 6, conclusion: 8 },
  cpp: { intro: 2, greedy: 2, assume: 3, compare: 4, conclusion: 4 },
  python: { intro: 2, greedy: 2, assume: 3, compare: 4, conclusion: 5 },
  javascript: { intro: 2, greedy: 2, assume: 3, compare: 4, conclusion: 4 },
};

// ==========================================
// Code05: IPO 项目最大化资本
// ==========================================

export const IPO_STAGE1_CODES: Record<string, string[]> = {
  java: [
    'public class IPODFS {',
    '    // 阶段1: 暴力排列搜索',
    '    public static int findMaximizedCapital(int k, int w, int[] profits, int[] capital) {',
    '        return dfs(k, w, profits, capital, new boolean[profits.length]);',
    '    }',
    '    private static int dfs(int k, int w, int[] p, int[] c, boolean[] used) {',
    '        if (k == 0) return w;',
    '        int max = w;',
    '        for (int i = 0; i < p.length; i++) {',
    '            if (!used[i] && w >= c[i]) {',
    '                used[i] = true;',
    '                max = Math.max(max, dfs(k - 1, w + p[i], p, c, used));',
    '                used[i] = false;',
    '            }',
    '        }',
    '        return max;',
    '    }',
    '}',
  ],
  cpp: [
    'class IPODFS {',
    'public:',
    '    int findMaximizedCapital(int k, int w, vector<int>& profits, vector<int>& capital) {',
    '        vector<bool> used(profits.size(), false);',
    '        return dfs(k, w, profits, capital, used);',
    '    }',
    'private:',
    '    int dfs(int k, int w, const vector<int>& p, const vector<int>& c, vector<bool>& used) {',
    '        if (k == 0) return w;',
    '        int res = w;',
    '        for (size_t i = 0; i < p.size(); ++i) {',
    '            if (!used[i] && w >= c[i]) {',
    '                used[i] = true;',
    '                res = max(res, dfs(k - 1, w + p[i], p, c, used));',
    '                used[i] = false;',
    '            }',
    '        }',
    '        return res;',
    '    }',
    '};',
  ],
  python: [
    'class IPODFS:',
    '    def findMaximizedCapital(self, k: int, w: int, profits: list[int], capital: list[int]) -> int:',
    '        used = [False] * len(profits)',
    '        def dfs(k_left, cur_w):',
    '            if k_left == 0: return cur_w',
    '            res = cur_w',
    '            for i in range(len(profits)):',
    '                if not used[i] and cur_w >= capital[i]:',
    '                    used[i] = True',
    '                    res = max(res, dfs(k_left - 1, cur_w + profits[i]))',
    '                    used[i] = False',
    '            return res',
    '        return dfs(k, w)',
  ],
  javascript: [
    'function ipoDFS(k, w, profits, capital) {',
    '  const used = new Array(profits.length).fill(false);',
    '  function dfs(kLeft, curW) {',
    '    if (kLeft === 0) return curW;',
    '    let max = curW;',
    '    for (let i = 0; i < profits.length; i++) {',
    '      if (!used[i] && curW >= capital[i]) {',
    '        used[i] = true;',
    '        max = Math.max(max, dfs(kLeft - 1, curW + profits[i]));',
    '        used[i] = false;',
    '      }',
    '    }',
    '    return max;',
    '  }',
    '  return dfs(k, w);',
    '}',
  ],
};

export const IPO_STAGE1_LINES: Record<string, Record<string, number>> = {
  java: { init: 4, dfs: 6, base: 7, loop: 9, pick: 11, ret: 15 },
  cpp: { init: 4, dfs: 7, base: 8, loop: 10, pick: 12, ret: 16 },
  python: { init: 3, dfs: 4, base: 5, loop: 7, pick: 9, ret: 12 },
  javascript: { init: 2, dfs: 3, base: 4, loop: 6, pick: 8, ret: 13 },
};

export const IPO_STAGE2_CODES: Record<string, string[]> = {
  java: [
    'import java.util.*;',
    'public class IPOGreedy {',
    '    static class Project { int p, c; Project(int p, int c) { this.p = p; this.c = c; } }',
    '    public static int findMaximizedCapital(int k, int w, int[] profits, int[] capital) {',
    '        PriorityQueue<Project> costHeap = new PriorityQueue<>((a, b) -> a.c - b.c);',
    '        PriorityQueue<Integer> profitHeap = new PriorityQueue<>((a, b) -> b - a);',
    '        for (int i = 0; i < profits.length; i++) costHeap.add(new Project(profits[i], capital[i]));',
    '        for (int round = 0; round < k; round++) {',
    '            while (!costHeap.isEmpty() && costHeap.peek().c <= w) {',
    '                profitHeap.add(costHeap.poll().p);',
    '            }',
    '            if (profitHeap.isEmpty()) break;',
    '            w += profitHeap.poll();',
    '        }',
    '        return w;',
    '    }',
    '}',
  ],
  cpp: [
    '#include <vector>',
    '#include <queue>',
    'using namespace std;',
    'class IPOGreedy {',
    'public:',
    '    int findMaximizedCapital(int k, int w, vector<int>& profits, vector<int>& capital) {',
    '        using pii = pair<int, int>; // {cost, profit}',
    '        priority_queue<pii, vector<pii>, greater<pii>> costHeap;',
    '        priority_queue<int> profitHeap;',
    '        for (size_t i = 0; i < profits.size(); ++i) costHeap.push({capital[i], profits[i]});',
    '        for (int round = 0; round < k; ++round) {',
    '            while (!costHeap.empty() && costHeap.top().first <= w) {',
    '                profitHeap.push(costHeap.top().second); costHeap.pop();',
    '            }',
    '            if (profitHeap.empty()) break;',
    '            w += profitHeap.top(); profitHeap.pop();',
    '        }',
    '        return w;',
    '    }',
    '};',
  ],
  python: [
    'import heapq',
    'class IPOGreedy:',
    '    def findMaximizedCapital(self, k: int, w: int, profits: list[int], capital: list[int]) -> int:',
    '        costHeap = [(c, p) for c, p in zip(capital, profits)]',
    '        heapq.heapify(costHeap)',
    '        profitHeap = []',
    '        for _ in range(k):',
    '            while costHeap and costHeap[0][0] <= w:',
    '                c, p = heapq.heappop(costHeap)',
    '                heapq.heappush(profitHeap, -p)',
    '            if not profitHeap: break',
    '            w += -heapq.heappop(profitHeap)',
    '        return w',
  ],
  javascript: [
    'function ipoGreedy(k, w, profits, capital) {',
    '  const projects = profits.map((p, i) => ({ p, c: capital[i] }));',
    '  projects.sort((a, b) => a.c - b.c);',
    '  const profitHeap = [];',
    '  function pushProfit(val) { profitHeap.push(val); profitHeap.sort((a, b) => b - a); }',
    '  let idx = 0;',
    '  for (let round = 0; round < k; round++) {',
    '    while (idx < projects.length && projects[idx].c <= w) {',
    '      pushProfit(projects[idx++].p);',
    '    }',
    '    if (profitHeap.length === 0) break;',
    '    w += profitHeap.shift();',
    '  }',
    '  return w;',
    '}',
  ],
};

export const IPO_STAGE2_LINES: Record<string, Record<string, number>> = {
  java: { init: 5, fill: 7, loop: 8, unlock: 9, check: 12, invest: 13, ret: 15 },
  cpp: { init: 8, fill: 11, loop: 12, unlock: 13, check: 16, invest: 17, ret: 19 },
  python: { init: 4, fill: 5, loop: 7, unlock: 8, check: 11, invest: 12, ret: 13 },
  javascript: { init: 2, fill: 3, loop: 7, unlock: 8, check: 11, invest: 12, ret: 14 },
};

export const IPO_STAGE3_CODES: Record<string, string[]> = {
  java: [
    '// 阶段3: 单调资本扩张支配证明',
    '// 设当前已解锁项目集合为 S, 贪心选择最大利润项目 p_max',
    '// 反证法: 假设选择另一可用项目 p_other (p_other < p_max)',
    '// 完成 p_other 后资本为 w + p_other < w + p_max',
    '// 资本具有单调性: 资本越大, 可解锁的项目集合必定是超集 (S_other ⊆ S_max)',
    '// 故选 p_max 不仅当前增益最大, 且后续可解锁的范围绝对不劣于选 p_other',
    '// 局部最优决策严格支配所有其他决策, 贪心解全局最优',
    'public class IPOProof {}',
  ],
  cpp: [
    '// 阶段3: 拟阵贪心选择性质证明',
    '// 本金 w 单调递增, 解锁的项目池单调扩张',
    '// 每次做利润最大化项目使得下一步本金上界最大化',
    '// 超集支配律确保不可能存在跨轮次收益逆转',
    'struct IPOProof {};',
  ],
  python: [
    '# 阶段3: 资本支配单调性证明',
    '# 选 p_max 带来最大的当前资本增量',
    '# 由于解锁条件 c[i] <= w 随 w 增大而单调变宽',
    '# 高资本解锁的项目池严格包含低资本的项目池',
    'pass',
  ],
  javascript: [
    '// 阶段3: 资本扩张支配反证',
    '// w\' = w + p_max 严格大于 w + p_other',
    '// 更高本金意味着未来更大的选择集合与自由度',
    'function verifyIPOProof() {}',
  ],
};

export const IPO_STAGE3_LINES: Record<string, Record<string, number>> = {
  java: { intro: 2, assume: 4, compare: 5, superset: 6, conclusion: 7 },
  cpp: { intro: 2, assume: 2, compare: 3, superset: 4, conclusion: 4 },
  python: { intro: 2, assume: 2, compare: 3, superset: 4, conclusion: 5 },
  javascript: { intro: 2, assume: 2, compare: 3, superset: 3, conclusion: 4 },
};

// ==========================================
// Code06: 加入差值绝对值直到长度固定
// ==========================================

export const ABS_VALUE_ADD_STAGE1_CODES: Record<string, string[]> = {
  java: [
    'import java.util.*;',
    'public class AbsValueAddDFS {',
    '    // 阶段1: 暴力集合模拟扩散',
    '    public static int getFinalLength(int[] arr) {',
    '        Set<Integer> set = new HashSet<>();',
    '        List<Integer> list = new ArrayList<>();',
    '        for (int x : arr) { set.add(x); list.add(x); }',
    '        while (true) {',
    '            int sizeBefore = list.size();',
    '            for (int i = 0; i < sizeBefore; i++) {',
    '                for (int j = i + 1; j < sizeBefore; j++) {',
    '                    int diff = Math.abs(list.get(i) - list.get(j));',
    '                    if (set.add(diff)) list.add(diff);',
    '                }',
    '            }',
    '            if (list.size() == sizeBefore) break;',
    '        }',
    '        return list.size();',
    '    }',
    '}',
  ],
  cpp: [
    '#include <vector>',
    '#include <unordered_set>',
    'using namespace std;',
    'class AbsValueAddDFS {',
    'public:',
    '    int getFinalLength(vector<int>& arr) {',
    '        unordered_set<int> st(arr.begin(), arr.end());',
    '        vector<int> list = arr;',
    '        while (true) {',
    '            size_t before = list.size();',
    '            for (size_t i = 0; i < before; ++i) {',
    '                for (size_t j = i + 1; j < before; ++j) {',
    '                    int diff = abs(list[i] - list[j]);',
    '                    if (st.insert(diff).second) list.push_back(diff);',
    '                }',
    '            }',
    '            if (list.size() == before) break;',
    '        }',
    '        return list.size();',
    '    }',
    '};',
  ],
  python: [
    'class AbsValueAddDFS:',
    '    def getFinalLength(self, arr: list[int]) -> int:',
    '        st = set(arr)',
    '        lst = list(arr)',
    '        while True:',
    '            before = len(lst)',
    '            for i in range(before):',
    '                for j in range(i + 1, before):',
    '                    diff = abs(lst[i] - lst[j])',
    '                    if diff not in st:',
    '                        st.add(diff)',
    '                        lst.append(diff)',
    '            if len(lst) == before: break',
    '        return len(lst)',
  ],
  javascript: [
    'function absValueAddDFS(arr) {',
    '  const set = new Set(arr);',
    '  const list = [...arr];',
    '  while (true) {',
    '    const before = list.length;',
    '    for (let i = 0; i < before; i++) {',
    '      for (let j = i + 1; j < before; j++) {',
    '        const diff = Math.abs(list[i] - list[j]);',
    '        if (!set.has(diff)) {',
    '          set.add(diff);',
    '          list.push(diff);',
    '        }',
    '      }',
    '    }',
    '    if (list.length === before) break;',
    '  }',
    '  return list.length;',
    '}',
  ],
};

export const ABS_VALUE_ADD_STAGE1_LINES: Record<string, Record<string, number>> = {
  java: { init: 5, whileLoop: 8, doubleLoop: 10, checkDiff: 12, add: 13, breakCheck: 16, ret: 18 },
  cpp: { init: 7, whileLoop: 9, doubleLoop: 11, checkDiff: 13, add: 14, breakCheck: 17, ret: 19 },
  python: { init: 3, whileLoop: 5, doubleLoop: 7, checkDiff: 9, add: 11, breakCheck: 13, ret: 14 },
  javascript: { init: 2, whileLoop: 4, doubleLoop: 6, checkDiff: 8, add: 10, breakCheck: 15, ret: 17 },
};

export const ABS_VALUE_ADD_STAGE2_CODES: Record<string, string[]> = {
  java: [
    'import java.util.*;',
    'public class AbsValueAddGreedy {',
    '    // 阶段2: 欧几里得 GCD 数论贪心',
    '    public static int getFinalLength(int[] arr) {',
    '        int max = 0, g = 0;',
    '        boolean hasZero = false;',
    '        Set<Integer> set = new HashSet<>();',
    '        for (int x : arr) {',
    '            if (x == 0) hasZero = true;',
    '            if (set.contains(x)) hasZero = true; // 相同数差值为0',
    '            set.add(x);',
    '            max = Math.max(max, x);',
    '            g = gcd(g, x);',
    '        }',
    '        if (max == 0) return 1;',
    '        int count = max / g;',
    '        return hasZero ? count + 1 : count;',
    '    }',
    '    private static int gcd(int a, int b) {',
    '        return b == 0 ? a : gcd(b, a % b);',
    '    }',
    '}',
  ],
  cpp: [
    '#include <vector>',
    '#include <numeric>',
    '#include <unordered_set>',
    'using namespace std;',
    'class AbsValueAddGreedy {',
    'public:',
    '    int getFinalLength(vector<int>& arr) {',
    '        int maxVal = 0, g = 0;',
    '        bool hasZero = false;',
    '        unordered_set<int> st;',
    '        for (int x : arr) {',
    '            if (x == 0 || st.count(x)) hasZero = true;',
    '            st.insert(x);',
    '            maxVal = max(maxVal, x);',
    '            g = gcd(g, x);',
    '        }',
    '        if (maxVal == 0) return 1;',
    '        int ans = maxVal / g;',
    '        return hasZero ? ans + 1 : ans;',
    '    }',
    'private:',
    '    int gcd(int a, int b) { return b == 0 ? a : gcd(b, a % b); }',
    '};',
  ],
  python: [
    'import math',
    'class AbsValueAddGreedy:',
    '    def getFinalLength(self, arr: list[int]) -> int:',
    '        max_val, g = 0, 0',
    '        has_zero = False',
    '        st = set()',
    '        for x in arr:',
    '            if x == 0 or x in st: has_zero = True',
    '            st.add(x)',
    '            max_val = max(max_val, x)',
    '            g = math.gcd(g, x)',
    '        if max_val == 0: return 1',
    '        ans = max_val // g',
    '        return ans + 1 if has_zero else ans',
  ],
  javascript: [
    'function absValueAddGreedy(arr) {',
    '  let max = 0, g = 0, hasZero = false;',
    '  const set = new Set();',
    '  function gcd(a, b) { return b === 0 ? a : gcd(b, a % b); }',
    '  for (const x of arr) {',
    '    if (x === 0 || set.has(x)) hasZero = true;',
    '    set.add(x);',
    '    if (x > max) max = x;',
    '    g = gcd(g, x);',
    '  }',
    '  if (max === 0) return 1;',
    '  const ans = Math.floor(max / g);',
    '  return hasZero ? ans + 1 : ans;',
    '}',
  ],
};

export const ABS_VALUE_ADD_STAGE2_LINES: Record<string, Record<string, number>> = {
  java: { init: 5, loop: 8, checkZero: 9, updateGCD: 13, checkZeroMax: 15, calcCount: 16, ret: 17 },
  cpp: { init: 8, loop: 11, checkZero: 12, updateGCD: 15, checkZeroMax: 17, calcCount: 18, ret: 19 },
  python: { init: 4, loop: 7, checkZero: 8, updateGCD: 11, checkZeroMax: 12, calcCount: 13, ret: 14 },
  javascript: { init: 2, loop: 5, checkZero: 6, updateGCD: 9, checkZeroMax: 11, calcCount: 12, ret: 13 },
};

export const ABS_VALUE_ADD_STAGE3_CODES: Record<string, string[]> = {
  java: [
    '// 阶段3: 裴蜀定理与差值闭包证明',
    '// 设 S 为最终差值绝对值封闭集合',
    '// 1. 封闭性: 对任意 x, y ∈ S, |x - y| ∈ S',
    '// 2. 欧几里得辗转相除法本质就是连续更相减损',
    '//    不断做差必然能得到所有数的最大公约数 g = gcd(arr)',
    '// 3. 一旦 g ∈ S, 通过不断加上 g (或与更大数做差):',
    '//    g, 2g, 3g, ..., k*g = max(arr) 必然全部进入 S',
    '// 4. 且由于 S 中任何数都是初始数的整系数线性组合, 绝不可能产生不是 g 的倍数的正数',
    '// 结论: 正整数恰好有 max/g 个, 若产生 0 则额外计入 0',
    'public class AbsValueAddProof {}',
  ],
  cpp: [
    '// 阶段3: 裴蜀定理与更相减损术闭包证明',
    '// 更相减损术表明: 差值运算生成的最小正整数即为 gcd(arr) = g',
    '// 生成的任意数必为 g 的倍数, 且 [g, 2g, ..., max] 全覆盖',
    '// 故最终正整数个数精确等于 max / g, 证明成立',
    'struct AbsValueAddProof {};',
  ],
  python: [
    '# 阶段3: 欧几里得闭包定理证明',
    '# 任何两个数作差不会改变最大公约数因子的封闭性',
    '# 最小非零差值必收敛为 g = gcd(arr)',
    '# 由辗转相加性质知 {g, 2g, ..., max} 全体生成',
    'pass',
  ],
  javascript: [
    '// 阶段3: 数论更相减损闭包证明',
    '// 差值运算的闭包等价于 gcd(arr) 生成的理想格点',
    '// 集合中的正数必然恰为 {1g, 2g, ..., (max/g)g}',
    'function verifyAbsValueProof() {}',
  ],
};

export const ABS_VALUE_ADD_STAGE3_LINES: Record<string, Record<string, number>> = {
  java: { intro: 2, closed: 3, gcd: 5, multiples: 7, conclusion: 9 },
  cpp: { intro: 2, closed: 2, gcd: 2, multiples: 3, conclusion: 4 },
  python: { intro: 2, closed: 2, gcd: 3, multiples: 4, conclusion: 4 },
  javascript: { intro: 2, closed: 2, gcd: 2, multiples: 3, conclusion: 3 },
};
