/**
 * 左程云算法通关课 Class 060: 拓扑排序扩展专题
 * 6 道重难点算法的 Java / C++ / Python / JavaScript 4 语言标准实现与 1-based 精准行号映射
 */

// ==========================================
// 1. Code01: 最大食物链计数 (洛谷 P4017)
// ==========================================
export const FOOD_CHAIN_060_CODES = {
  cpp: [
    '#include <vector>',
    '#include <queue>',
    'using namespace std;',
    '',
    'int foodChainCount(int n, vector<vector<int>>& edges) {',
    '    const int MOD = 80112002;',
    '    vector<vector<int>> adj(n + 1);',
    '    vector<int> inDegree(n + 1, 0), outDegree(n + 1, 0), lines(n + 1, 0);',
    '    for (auto& e : edges) {',
    '        adj[e[0]].push_back(e[1]);',
    '        outDegree[e[0]]++; inDegree[e[1]]++;',
    '    }',
    '    queue<int> q;',
    '    for (int i = 1; i <= n; ++i) {',
    '        if (inDegree[i] == 0) { lines[i] = 1; q.push(i); }',
    '    }',
    '    int total = 0;',
    '    while (!q.empty()) {',
    '        int u = q.front(); q.pop();',
    '        if (outDegree[u] == 0) total = (total + lines[u]) % MOD;',
    '        for (int v : adj[u]) {',
    '            lines[v] = (lines[v] + lines[u]) % MOD;',
    '            if (--inDegree[v] == 0) q.push(v);',
    '        }',
    '    }',
    '    return total;',
    '}',
  ],
  java: [
    'package class060;',
    'import java.util.*;',
    '',
    'public class Code01_FoodChain {',
    '    public static int foodChainCount(int n, int[][] edges) {',
    '        int MOD = 80112002;',
    '        List<List<Integer>> adj = new ArrayList<>();',
    '        for (int i = 0; i <= n; i++) adj.add(new ArrayList<>());',
    '        int[] inDegree = new int[n + 1], outDegree = new int[n + 1], lines = new int[n + 1];',
    '        for (int[] e : edges) {',
    '            adj.get(e[0]).add(e[1]);',
    '            outDegree[e[0]]++; inDegree[e[1]]++;',
    '        }',
    '        Queue<Integer> q = new LinkedList<>();',
    '        for (int i = 1; i <= n; i++) {',
    '            if (inDegree[i] == 0) { lines[i] = 1; q.offer(i); }',
    '        }',
    '        int total = 0;',
    '        while (!q.isEmpty()) {',
    '            int u = q.poll();',
    '            if (outDegree[u] == 0) total = (total + lines[u]) % MOD;',
    '            for (int v : adj.get(u)) {',
    '                lines[v] = (lines[v] + lines[u]) % MOD;',
    '                if (--inDegree[v] == 0) q.offer(v);',
    '            }',
    '        }',
    '        return total;',
    '    }',
    '}',
  ],
  python: [
    'from collections import deque',
    '',
    'def food_chain_count(n: int, edges: list[list[int]]) -> int:',
    '    MOD = 80112002',
    '    adj = [[] for _ in range(n + 1)]',
    '    in_deg = [0] * (n + 1)',
    '    out_deg = [0] * (n + 1)',
    '    lines = [0] * (n + 1)',
    '    for u, v in edges:',
    '        adj[u].append(v)',
    '        out_deg[u] += 1; in_deg[v] += 1',
    '    q = deque([i for i in range(1, n + 1) if in_deg[i] == 0])',
    '    for i in q: lines[i] = 1',
    '    total = 0',
    '    while q:',
    '        u = q.popleft()',
    '        if out_deg[u] == 0: total = (total + lines[u]) % MOD',
    '        for v in adj[u]:',
    '            lines[v] = (lines[v] + lines[u]) % MOD',
    '            in_deg[v] -= 1',
    '            if in_deg[v] == 0: q.append(v)',
    '    return total',
  ],
  javascript: [
    'function foodChainCount(n, edges) {',
    '  const MOD = 80112002;',
    '  const adj = Array.from({ length: n + 1 }, () => []);',
    '  const inDegree = new Array(n + 1).fill(0);',
    '  const outDegree = new Array(n + 1).fill(0);',
    '  const lines = new Array(n + 1).fill(0);',
    '  for (const [u, v] of edges) {',
    '    adj[u].push(v);',
    '    outDegree[u]++; inDegree[v]++;',
    '  }',
    '  const q = [];',
    '  for (let i = 1; i <= n; i++) {',
    '    if (inDegree[i] === 0) { lines[i] = 1; q.push(i); }',
    '  }',
    '  let total = 0;',
    '  while (q.length > 0) {',
    '    const u = q.shift();',
    '    if (outDegree[u] === 0) total = (total + lines[u]) % MOD;',
    '    for (const v of adj[u]) {',
    '      lines[v] = (lines[v] + lines[u]) % MOD;',
    '      if (--inDegree[v] === 0) q.push(v);',
    '    }',
    '  }',
    '  return total;',
    '}',
  ],
};

export const FOOD_CHAIN_060_LINES = {
  init: { cpp: 6, java: 6, python: 4, javascript: 2 },
  findZeroIn: { cpp: 14, java: 15, python: 12, javascript: 12 },
  pollNode: { cpp: 19, java: 20, python: 16, javascript: 17 },
  accumulateConsumer: { cpp: 20, java: 21, python: 17, javascript: 18 },
  relaxEdge: { cpp: 22, java: 23, python: 19, javascript: 20 },
  pushQueue: { cpp: 23, java: 24, python: 21, javascript: 21 },
  returnTotal: { cpp: 26, java: 28, python: 22, javascript: 25 },
};

// ==========================================
// 2. Code02: 喧闹和富有 (LeetCode 851)
// ==========================================
export const LOUD_AND_RICH_060_CODES = {
  cpp: [
    '#include <vector>',
    '#include <queue>',
    '#include <numeric>',
    'using namespace std;',
    '',
    'vector<int> loudAndRich(vector<vector<int>>& richer, vector<int>& quiet) {',
    '    int n = quiet.size();',
    '    vector<vector<int>> adj(n);',
    '    vector<int> inDegree(n, 0), ans(n);',
    '    iota(ans.begin(), ans.end(), 0);',
    '    for (auto& r : richer) { adj[r[0]].push_back(r[1]); inDegree[r[1]]++; }',
    '    queue<int> q;',
    '    for (int i = 0; i < n; ++i) if (inDegree[i] == 0) q.push(i);',
    '    while (!q.empty()) {',
    '        int u = q.front(); q.pop();',
    '        for (int v : adj[u]) {',
    '            if (quiet[ans[u]] < quiet[ans[v]]) ans[v] = ans[u];',
    '            if (--inDegree[v] == 0) q.push(v);',
    '        }',
    '    }',
    '    return ans;',
    '}',
  ],
  java: [
    'package class060;',
    'import java.util.*;',
    '',
    'public class Code02_LoudAndRich {',
    '    public static int[] loudAndRich(int[][] richer, int[] quiet) {',
    '        int n = quiet.length;',
    '        List<List<Integer>> adj = new ArrayList<>();',
    '        for (int i = 0; i < n; i++) adj.add(new ArrayList<>());',
    '        int[] inDegree = new int[n], ans = new int[n];',
    '        for (int i = 0; i < n; i++) ans[i] = i;',
    '        for (int[] r : richer) { adj.get(r[0]).add(r[1]); inDegree[r[1]]++; }',
    '        Queue<Integer> q = new LinkedList<>();',
    '        for (int i = 0; i < n; i++) if (inDegree[i] == 0) q.offer(i);',
    '        while (!q.isEmpty()) {',
    '            int u = q.poll();',
    '            for (int v : adj.get(u)) {',
    '                if (quiet[ans[u]] < quiet[ans[v]]) ans[v] = ans[u];',
    '                if (--inDegree[v] == 0) q.offer(v);',
    '            }',
    '        }',
    '        return ans;',
    '    }',
    '}',
  ],
  python: [
    'from collections import deque',
    '',
    'def loud_and_rich(richer: list[list[int]], quiet: list[int]) -> list[int]:',
    '    n = len(quiet)',
    '    adj = [[] for _ in range(n)]',
    '    in_deg = [0] * n',
    '    ans = list(range(n))',
    '    for u, v in richer: adj[u].append(v); in_deg[v] += 1',
    '    q = deque([i for i in range(n) if in_deg[i] == 0])',
    '    while q:',
    '        u = q.popleft()',
    '        for v in adj[u]:',
    '            if quiet[ans[u]] < quiet[ans[v]]: ans[v] = ans[u]',
    '            in_deg[v] -= 1',
    '            if in_deg[v] == 0: q.append(v)',
    '    return ans',
  ],
  javascript: [
    'function loudAndRich(richer, quiet) {',
    '  const n = quiet.length;',
    '  const adj = Array.from({ length: n }, () => []);',
    '  const inDegree = new Array(n).fill(0);',
    '  const ans = Array.from({ length: n }, (_, i) => i);',
    '  for (const [u, v] of richer) { adj[u].push(v); inDegree[v]++; }',
    '  const q = [];',
    '  for (let i = 0; i < n; i++) if (inDegree[i] === 0) q.push(i);',
    '  while (q.length > 0) {',
    '    const u = q.shift();',
    '    for (const v of adj[u]) {',
    '      if (quiet[ans[u]] < quiet[ans[v]]) ans[v] = ans[u];',
    '      if (--inDegree[v] === 0) q.push(v);',
    '    }',
    '  }',
    '  return ans;',
    '}',
  ],
};

export const LOUD_AND_RICH_060_LINES = {
  init: { cpp: 7, java: 6, python: 4, javascript: 2 },
  findZeroIn: { cpp: 13, java: 14, python: 9, javascript: 8 },
  pollNode: { cpp: 15, java: 16, python: 11, javascript: 10 },
  updateQuiet: { cpp: 17, java: 18, python: 13, javascript: 12 },
  pushQueue: { cpp: 18, java: 19, python: 15, javascript: 13 },
  returnAns: { cpp: 21, java: 22, python: 16, javascript: 16 },
};

// ==========================================
// 3. Code03: 并行课程 III (LeetCode 2050)
// ==========================================
export const PARALLEL_COURSES_060_CODES = {
  cpp: [
    '#include <vector>',
    '#include <queue>',
    '#include <algorithm>',
    'using namespace std;',
    '',
    'int minimumTime(int n, vector<vector<int>>& relations, vector<int>& time) {',
    '    vector<vector<int>> adj(n + 1);',
    '    vector<int> inDegree(n + 1, 0), cost(n + 1, 0);',
    '    for (auto& r : relations) { adj[r[0]].push_back(r[1]); inDegree[r[1]]++; }',
    '    queue<int> q;',
    '    for (int i = 1; i <= n; ++i) {',
    '        if (inDegree[i] == 0) { cost[i] = time[i - 1]; q.push(i); }',
    '    }',
    '    int total = 0;',
    '    while (!q.empty()) {',
    '        int u = q.front(); q.pop();',
    '        total = max(total, cost[u]);',
    '        for (int v : adj[u]) {',
    '            cost[v] = max(cost[v], cost[u] + time[v - 1]);',
    '            if (--inDegree[v] == 0) q.push(v);',
    '        }',
    '    }',
    '    return total;',
    '}',
  ],
  java: [
    'package class060;',
    'import java.util.*;',
    '',
    'public class Code03_ParallelCoursesIII {',
    '    public static int minimumTime(int n, int[][] relations, int[] time) {',
    '        List<List<Integer>> adj = new ArrayList<>();',
    '        for (int i = 0; i <= n; i++) adj.add(new ArrayList<>());',
    '        int[] inDegree = new int[n + 1], cost = new int[n + 1];',
    '        for (int[] r : relations) { adj.get(r[0]).add(r[1]); inDegree[r[1]]++; }',
    '        Queue<Integer> q = new LinkedList<>();',
    '        for (int i = 1; i <= n; i++) {',
    '            if (inDegree[i] == 0) { cost[i] = time[i - 1]; q.offer(i); }',
    '        }',
    '        int total = 0;',
    '        while (!q.isEmpty()) {',
    '            int u = q.poll();',
    '            total = Math.max(total, cost[u]);',
    '            for (int v : adj.get(u)) {',
    '                cost[v] = Math.max(cost[v], cost[u] + time[v - 1]);',
    '                if (--inDegree[v] == 0) q.offer(v);',
    '            }',
    '        }',
    '        return total;',
    '    }',
    '}',
  ],
  python: [
    'from collections import deque',
    '',
    'def minimum_time(n: int, relations: list[list[int]], time: list[int]) -> int:',
    '    adj = [[] for _ in range(n + 1)]',
    '    in_deg = [0] * (n + 1)',
    '    cost = [0] * (n + 1)',
    '    for u, v in relations: adj[u].append(v); in_deg[v] += 1',
    '    q = deque([i for i in range(1, n + 1) if in_deg[i] == 0])',
    '    for i in q: cost[i] = time[i - 1]',
    '    total = 0',
    '    while q:',
    '        u = q.popleft()',
    '        total = max(total, cost[u])',
    '        for v in adj[u]:',
    '            cost[v] = max(cost[v], cost[u] + time[v - 1])',
    '            in_deg[v] -= 1',
    '            if in_deg[v] == 0: q.append(v)',
    '    return total',
  ],
  javascript: [
    'function minimumTime(n, relations, time) {',
    '  const adj = Array.from({ length: n + 1 }, () => []);',
    '  const inDegree = new Array(n + 1).fill(0);',
    '  const cost = new Array(n + 1).fill(0);',
    '  for (const [u, v] of relations) { adj[u].push(v); inDegree[v]++; }',
    '  const q = [];',
    '  for (let i = 1; i <= n; i++) {',
    '    if (inDegree[i] === 0) { cost[i] = time[i - 1]; q.push(i); }',
    '  }',
    '  let total = 0;',
    '  while (q.length > 0) {',
    '    const u = q.shift();',
    '    total = Math.max(total, cost[u]);',
    '    for (const v of adj[u]) {',
    '      cost[v] = Math.max(cost[v], cost[u] + time[v - 1]);',
    '      if (--inDegree[v] === 0) q.push(v);',
    '    }',
    '  }',
    '  return total;',
    '}',
  ],
};

export const PARALLEL_COURSES_060_LINES = {
  init: { cpp: 7, java: 6, python: 4, javascript: 2 },
  findZeroIn: { cpp: 11, java: 12, python: 9, javascript: 8 },
  pollNode: { cpp: 16, java: 17, python: 13, javascript: 13 },
  relaxCost: { cpp: 19, java: 20, python: 16, javascript: 16 },
  pushQueue: { cpp: 20, java: 21, python: 18, javascript: 17 },
  returnTotal: { cpp: 23, java: 25, python: 19, javascript: 21 },
};

// ==========================================
// 4. Code04: 参加会议的最多员工数 (LeetCode 2127)
// ==========================================
export const MAX_EMPLOYEES_060_CODES = {
  cpp: [
    '#include <vector>',
    '#include <queue>',
    '#include <algorithm>',
    'using namespace std;',
    '',
    'int maximumInvitations(vector<int>& favorite) {',
    '    int n = favorite.size();',
    '    vector<int> inDegree(n, 0), maxDepth(n, 0);',
    '    for (int v : favorite) inDegree[v]++;',
    '    queue<int> q;',
    '    for (int i = 0; i < n; ++i) if (inDegree[i] == 0) q.push(i);',
    '    while (!q.empty()) {',
    '        int u = q.front(); q.pop();',
    '        int v = favorite[u];',
    '        maxDepth[v] = max(maxDepth[v], maxDepth[u] + 1);',
    '        if (--inDegree[v] == 0) q.push(v);',
    '    }',
    '    int maxRing = 0, sumTwoRing = 0;',
    '    for (int i = 0; i < n; ++i) {',
    '        if (inDegree[i] > 0) {',
    '            inDegree[i] = 0; int ringSize = 1;',
    '            for (int curr = favorite[i]; curr != i; curr = favorite[curr]) {',
    '                ringSize++; inDegree[curr] = 0;',
    '            }',
    '            if (ringSize == 2) sumTwoRing += 2 + maxDepth[i] + maxDepth[favorite[i]];',
    '            else maxRing = max(maxRing, ringSize);',
    '        }',
    '    }',
    '    return max(maxRing, sumTwoRing);',
    '}',
  ],
  java: [
    'package class060;',
    'import java.util.*;',
    '',
    'public class Code04_MaxEmployeesMeeting {',
    '    public static int maximumInvitations(int[] favorite) {',
    '        int n = favorite.length;',
    '        int[] inDegree = new int[n], maxDepth = new int[n];',
    '        for (int v : favorite) inDegree[v]++;',
    '        Queue<Integer> q = new LinkedList<>();',
    '        for (int i = 0; i < n; i++) if (inDegree[i] == 0) q.offer(i);',
    '        while (!q.isEmpty()) {',
    '            int u = q.poll();',
    '            int v = favorite[u];',
    '            maxDepth[v] = Math.max(maxDepth[v], maxDepth[u] + 1);',
    '            if (--inDegree[v] == 0) q.offer(v);',
    '        }',
    '        int maxRing = 0, sumTwoRing = 0;',
    '        for (int i = 0; i < n; i++) {',
    '            if (inDegree[i] > 0) {',
    '                inDegree[i] = 0; int ringSize = 1;',
    '                for (int curr = favorite[i]; curr != i; curr = favorite[curr]) {',
    '                    ringSize++; inDegree[curr] = 0;',
    '                }',
    '                if (ringSize == 2) sumTwoRing += 2 + maxDepth[i] + maxDepth[favorite[i]];',
    '                else maxRing = Math.max(maxRing, ringSize);',
    '            }',
    '        }',
    '        return Math.max(maxRing, sumTwoRing);',
    '    }',
    '}',
  ],
  python: [
    'from collections import deque',
    '',
    'def maximum_invitations(favorite: list[int]) -> int:',
    '    n = len(favorite)',
    '    in_deg = [0] * n',
    '    max_depth = [0] * n',
    '    for v in favorite: in_deg[v] += 1',
    '    q = deque([i for i in range(n) if in_deg[i] == 0])',
    '    while q:',
    '        u = q.popleft()',
    '        v = favorite[u]',
    '        max_depth[v] = max(max_depth[v], max_depth[u] + 1)',
    '        in_deg[v] -= 1',
    '        if in_deg[v] == 0: q.append(v)',
    '    max_ring = sum_two_ring = 0',
    '    for i in range(n):',
    '        if in_deg[i] > 0:',
    '            in_deg[i] = 0; ring_size = 1',
    '            curr = favorite[i]',
    '            while curr != i:',
    '                ring_size += 1; in_deg[curr] = 0; curr = favorite[curr]',
    '            if ring_size == 2:',
    '                sum_two_ring += 2 + max_depth[i] + max_depth[favorite[i]]',
    '            else: max_ring = max(max_ring, ring_size)',
    '    return max(max_ring, sum_two_ring)',
  ],
  javascript: [
    'function maximumInvitations(favorite) {',
    '  const n = favorite.length;',
    '  const inDegree = new Array(n).fill(0);',
    '  const maxDepth = new Array(n).fill(0);',
    '  for (const v of favorite) inDegree[v]++;',
    '  const q = [];',
    '  for (let i = 0; i < n; i++) if (inDegree[i] === 0) q.push(i);',
    '  while (q.length > 0) {',
    '    const u = q.shift();',
    '    const v = favorite[u];',
    '    maxDepth[v] = Math.max(maxDepth[v], maxDepth[u] + 1);',
    '    if (--inDegree[v] === 0) q.push(v);',
    '  }',
    '  let maxRing = 0, sumTwoRing = 0;',
    '  for (let i = 0; i < n; i++) {',
    '    if (inDegree[i] > 0) {',
    '      inDegree[i] = 0; let ringSize = 1;',
    '      for (let curr = favorite[i]; curr != i; curr = favorite[curr]) {',
    '        ringSize++; inDegree[curr] = 0;',
    '      }',
    '      if (ringSize === 2) sumTwoRing += 2 + maxDepth[i] + maxDepth[favorite[i]];',
    '      else maxRing = Math.max(maxRing, ringSize);',
    '    }',
    '  }',
    '  return Math.max(maxRing, sumTwoRing);',
    '}',
  ],
};

export const MAX_EMPLOYEES_060_LINES = {
  init: { cpp: 7, java: 6, python: 4, javascript: 2 },
  peelBranch: { cpp: 12, java: 12, python: 9, javascript: 8 },
  updateDepth: { cpp: 15, java: 15, python: 12, javascript: 11 },
  traverseRing: { cpp: 19, java: 19, python: 17, javascript: 16 },
  classifyRing: { cpp: 24, java: 24, python: 23, javascript: 21 },
  returnResult: { cpp: 28, java: 28, python: 26, javascript: 26 },
};

// ==========================================
// 5. Code05: 戳印序列 (LeetCode 936)
// ==========================================
export const STAMPING_SEQUENCE_060_CODES = {
  cpp: [
    '#include <vector>',
    '#include <string>',
    '#include <queue>',
    '#include <algorithm>',
    'using namespace std;',
    '',
    'vector<int> movesToStamp(string stamp, string target) {',
    '    int m = stamp.length(), n = target.length();',
    '    int maxStarts = n - m + 1;',
    '    vector<int> inDegree(maxStarts, m);',
    '    vector<vector<int>> graph(n);',
    '    queue<int> q;',
    '    for (int i = 0; i < maxStarts; ++i) {',
    '        for (int j = 0; j < m; ++j) {',
    '            if (target[i + j] == stamp[j]) {',
    '                if (--inDegree[i] == 0) q.push(i);',
    '            } else graph[i + j].push_back(i);',
    '        }',
    '    }',
    '    vector<bool> visited(n, false);',
    '    vector<int> path;',
    '    while (!q.empty()) {',
    '        int start = q.front(); q.pop();',
    '        path.push_back(start);',
    '        for (int i = 0; i < m; ++i) {',
    '            if (!visited[start + i]) {',
    '                visited[start + i] = true;',
    '                for (int neighbor : graph[start + i]) {',
    '                    if (--inDegree[neighbor] == 0) q.push(neighbor);',
    '                }',
    '            }',
    '        }',
    '    }',
    '    if (path.size() != maxStarts) return {};',
    '    reverse(path.begin(), path.end());',
    '    return path;',
    '}',
  ],
  java: [
    'package class060;',
    'import java.util.*;',
    '',
    'public class Code05_StampingSequence {',
    '    public static int[] movesToStamp(String stamp, String target) {',
    '        int m = stamp.length(), n = target.length();',
    '        int maxStarts = n - m + 1;',
    '        int[] inDegree = new int[maxStarts]; Arrays.fill(inDegree, m);',
    '        List<List<Integer>> graph = new ArrayList<>();',
    '        for (int i = 0; i < n; i++) graph.add(new ArrayList<>());',
    '        Queue<Integer> q = new LinkedList<>();',
    '        for (int i = 0; i < maxStarts; i++) {',
    '            for (int j = 0; j < m; j++) {',
    '                if (target.charAt(i + j) == stamp.charAt(j)) {',
    '                    if (--inDegree[i] == 0) q.offer(i);',
    '                } else graph.get(i + j).add(i);',
    '            }',
    '        }',
    '        boolean[] visited = new boolean[n];',
    '        List<Integer> path = new ArrayList<>();',
    '        while (!q.isEmpty()) {',
    '            int start = q.poll();',
    '            path.add(start);',
    '            for (int i = 0; i < m; i++) {',
    '                if (!visited[start + i]) {',
    '                    visited[start + i] = true;',
    '                    for (int neighbor : graph.get(start + i)) {',
    '                        if (--inDegree[neighbor] == 0) q.offer(neighbor);',
    '                    }',
    '                }',
    '            }',
    '        }',
    '        if (path.size() != maxStarts) return new int[0];',
    '        int[] ans = new int[maxStarts];',
    '        for (int i = 0; i < maxStarts; i++) ans[i] = path.get(maxStarts - 1 - i);',
    '        return ans;',
    '    }',
    '}',
  ],
  python: [
    'from collections import deque',
    '',
    'def moves_to_stamp(stamp: str, target: str) -> list[int]:',
    '    m, n = len(stamp), len(target)',
    '    max_starts = n - m + 1',
    '    in_deg = [m] * max_starts',
    '    graph = [[] for _ in range(n)]',
    '    q = deque()',
    '    for i in range(max_starts):',
    '        for j in range(m):',
    '            if target[i + j] == stamp[j]:',
    '                in_deg[i] -= 1',
    '                if in_deg[i] == 0: q.append(i)',
    '            else: graph[i + j].append(i)',
    '    visited = [False] * n',
    '    path = []',
    '    while q:',
    '        start = q.popleft()',
    '        path.append(start)',
    '        for i in range(m):',
    '            if not visited[start + i]:',
    '                visited[start + i] = True',
    '                for neighbor in graph[start + i]:',
    '                    in_deg[neighbor] -= 1',
    '                    if in_deg[neighbor] == 0: q.append(neighbor)',
    '    return path[::-1] if len(path) == max_starts else []',
  ],
  javascript: [
    'function movesToStamp(stamp, target) {',
    '  const m = stamp.length, n = target.length;',
    '  const maxStarts = n - m + 1;',
    '  const inDegree = new Array(maxStarts).fill(m);',
    '  const graph = Array.from({ length: n }, () => []);',
    '  const q = [];',
    '  for (let i = 0; i < maxStarts; i++) {',
    '    for (let j = 0; j < m; j++) {',
    '      if (target[i + j] === stamp[j]) {',
    '        if (--inDegree[i] === 0) q.push(i);',
    '      } else graph[i + j].push(i);',
    '    }',
    '  }',
    '  const visited = new Array(n).fill(false);',
    '  const path = [];',
    '  while (q.length > 0) {',
    '    const start = q.shift();',
    '    path.push(start);',
    '    for (let i = 0; i < m; i++) {',
    '      if (!visited[start + i]) {',
    '        visited[start + i] = true;',
    '        for (const neighbor of graph[start + i]) {',
    '          if (--inDegree[neighbor] === 0) q.push(neighbor);',
    '        }',
    '      }',
    '    }',
    '  }',
    '  return path.length === maxStarts ? path.reverse() : [];',
    '}',
  ],
};

export const STAMPING_SEQUENCE_060_LINES = {
  init: { cpp: 7, java: 6, python: 4, javascript: 2 },
  matchWindow: { cpp: 13, java: 13, python: 9, javascript: 8 },
  pollWindow: { cpp: 23, java: 23, python: 18, javascript: 18 },
  wildcardPropagate: { cpp: 26, java: 26, python: 21, javascript: 21 },
  returnPath: { cpp: 34, java: 35, python: 27, javascript: 29 },
};

// ==========================================
// 6. Code06: 有向图中的最长颜色路径 (LeetCode 1857)
// ==========================================
export const LARGEST_COLOR_VALUE_060_CODES = {
  cpp: [
    '#include <vector>',
    '#include <string>',
    '#include <queue>',
    '#include <algorithm>',
    'using namespace std;',
    '',
    'int largestPathValue(string colors, vector<vector<int>>& edges) {',
    '    int n = colors.size();',
    '    vector<vector<int>> adj(n);',
    '    vector<int> inDegree(n, 0);',
    '    for (auto& e : edges) { adj[e[0]].push_back(e[1]); inDegree[e[1]]++; }',
    '    queue<int> q;',
    '    for (int i = 0; i < n; ++i) if (inDegree[i] == 0) q.push(i);',
    '    vector<vector<int>> dp(n, vector<int>(26, 0));',
    '    int visitedCount = 0, ans = 0;',
    '    while (!q.empty()) {',
    '        int u = q.front(); q.pop();',
    '        visitedCount++;',
    '        int c = colors[u] - \'a\';',
    '        ans = max(ans, ++dp[u][c]);',
    '        for (int v : adj[u]) {',
    '            for (int k = 0; k < 26; ++k) dp[v][k] = max(dp[v][k], dp[u][k]);',
    '            if (--inDegree[v] == 0) q.push(v);',
    '        }',
    '    }',
    '    return visitedCount == n ? ans : -1;',
    '}',
  ],
  java: [
    'package class060;',
    'import java.util.*;',
    '',
    'public class Code06_LargestColorValue {',
    '    public static int largestPathValue(String colors, int[][] edges) {',
    '        int n = colors.length();',
    '        List<List<Integer>> adj = new ArrayList<>();',
    '        for (int i = 0; i < n; i++) adj.add(new ArrayList<>());',
    '        int[] inDegree = new int[n];',
    '        for (int[] e : edges) { adj.get(e[0]).add(e[1]); inDegree[e[1]]++; }',
    '        Queue<Integer> q = new LinkedList<>();',
    '        for (int i = 0; i < n; i++) if (inDegree[i] == 0) q.offer(i);',
    '        int[][] dp = new int[n][26];',
    '        int visitedCount = 0, ans = 0;',
    '        while (!q.isEmpty()) {',
    '            int u = q.poll();',
    '            visitedCount++;',
    '            int c = colors.charAt(u) - \'a\';',
    '            ans = Math.max(ans, ++dp[u][c]);',
    '            for (int v : adj.get(u)) {',
    '                for (int k = 0; k < 26; k++) dp[v][k] = Math.max(dp[v][k], dp[u][k]);',
    '                if (--inDegree[v] == 0) q.offer(v);',
    '            }',
    '        }',
    '        return visitedCount == n ? ans : -1;',
    '    }',
    '}',
  ],
  python: [
    'from collections import deque',
    '',
    'def largest_path_value(colors: str, edges: list[list[int]]) -> int:',
    '    n = len(colors)',
    '    adj = [[] for _ in range(n)]',
    '    in_deg = [0] * n',
    '    for u, v in edges: adj[u].append(v); in_deg[v] += 1',
    '    q = deque([i for i in range(n) if in_deg[i] == 0])',
    '    dp = [[0] * 26 for _ in range(n)]',
    '    visited_count = ans = 0',
    '    while q:',
    '        u = q.popleft()',
    '        visited_count += 1',
    '        c = ord(colors[u]) - ord("a")',
    '        dp[u][c] += 1',
    '        ans = max(ans, dp[u][c])',
    '        for v in adj[u]:',
    '            for k in range(26):',
    '                if dp[u][k] > dp[v][k]: dp[v][k] = dp[u][k]',
    '            in_deg[v] -= 1',
    '            if in_deg[v] == 0: q.append(v)',
    '    return ans if visited_count == n else -1',
  ],
  javascript: [
    'function largestPathValue(colors, edges) {',
    '  const n = colors.length;',
    '  const adj = Array.from({ length: n }, () => []);',
    '  const inDegree = new Array(n).fill(0);',
    '  for (const [u, v] of edges) { adj[u].push(v); inDegree[v]++; }',
    '  const q = [];',
    '  for (let i = 0; i < n; i++) if (inDegree[i] === 0) q.push(i);',
    '  const dp = Array.from({ length: n }, () => new Array(26).fill(0));',
    '  let visitedCount = 0, ans = 0;',
    '  while (q.length > 0) {',
    '    const u = q.shift();',
    '    visitedCount++;',
    '    const c = colors.charCodeAt(u) - 97;',
    '    ans = Math.max(ans, ++dp[u][c]);',
    '    for (const v of adj[u]) {',
    '      for (let k = 0; k < 26; k++) {',
    '        if (dp[u][k] > dp[v][k]) dp[v][k] = dp[u][k];',
    '      }',
    '      if (--inDegree[v] === 0) q.push(v);',
    '    }',
    '  }',
    '  return visitedCount === n ? ans : -1;',
    '}',
  ],
};

export const LARGEST_COLOR_VALUE_060_LINES = {
  init: { cpp: 7, java: 6, python: 4, javascript: 2 },
  findZeroIn: { cpp: 13, java: 13, python: 9, javascript: 7 },
  pollNode: { cpp: 17, java: 17, python: 12, javascript: 11 },
  relax26Colors: { cpp: 22, java: 22, python: 18, javascript: 16 },
  pushQueue: { cpp: 23, java: 23, python: 20, javascript: 18 },
  returnResult: { cpp: 26, java: 26, python: 21, javascript: 21 },
};
